### ISSUE TITLE
FNX3-13580 ⁃ Refactor "isCustomTab" to better adhere to architecture

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1000]
Per @boek's comment [here](https://github.com/mozilla-mobile/fenix/pull/944#pullrequestreview-214076395), we should handle custom tabs in a way that is more clearly following our new architecture.

**Comment by jonalmeida** [comment]
A quick look at the codebase, at it seems like most of the things being done with the `isCustomTab` checks can be moved into one place in the `CustomTabsIntegration` class since that is only executed for a Custom Tab.

For example, similar to Fenix, r-b removes the toolbar's `urlBoxView` background in a CT. This can be done in the init block of the integration class: https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/browser/CustomTabsIntegration.kt#L30-L32

**Comment by sblatz** [comment]
@NotWoods are you actively working on this?

**Comment by jonalmeida** [comment]
There's some [initial work here](https://github.com/mozilla-mobile/android-components/pull/3776) that Tiger is looking into.

**Comment by NotWoods** [comment]
I'm also doing follow-up work based on mozilla-mobile/android-components#3709

**Comment by NotWoods** [comment]
Fixed with the new split custom tabs code
