### ISSUE TITLE
FNX-4711 ⁃ Settings for crash reporting

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1003]
User Story
As a user I have the option to enable/disable crash reporting in settings.

## Next Steps 
* Immediate task: Estimate/size user story with points (during backlog grooming)
* Engineers need to breakdown the user story, size all the individual tasks, and link the tasks to this user story (Done by Eng on Sprint Planning day)

### Acceptance Criteria (Added by PM)
* I can enable/disable crash reporting in settings. 
* When I have disabled crash reporting, no reports are sent to Sentry
* When I have disabled crash reporting, no reports are sent to Socorro
* When I have disabled crash reporting, Fenix will never ask me to send a crash report

**Comment by sblatz** [comment]
To confirm what this means:

Should this box just be unchecked if the user has switched their data preference for crash reporting off?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/54551850-1474b800-496c-11e9-9b35-16df7cdd584e.png">

**Comment by sv-ohorvath** [comment]
There is also a checkbox on the app crashed dialog:
![Screenshot_20190328-082712](https://user-images.githubusercontent.com/4037709/55157721-ca5ab600-5165-11e9-9b85-e1b75600afb4.png)
This should be removed/un-checked when the crash reporter is turned off.

**Comment by sblatz** [comment]
@sv-ohorvath I will create a follow-up bug for this.

**Comment by sv-ohorvath** [comment]
Ok, so I can close this. Thanks!

**Comment by sblatz** [comment]
@brampitoyo I think we will need to add the checkbox back and just default it to the state the user has in the settings (or remove the setting altogether). 

Unfortunately removing the checkbox is not a trivial change as I anticipated, and after spending over a day working on it I discovered an issue with the way crash reporting is handled by GV/A-C that makes this change incredibly difficult and time consuming. 

I am also concerned that user would be sending crash reports *without knowing it* since it would be buried deep in the settings, rather than asking users on each prompt since the data could be identifiable. 

Please let me know if you'd like to chat about this more!

**Comment by brampitoyo** [comment]
@sblatz wrote:
> Unfortunately removing the checkbox is not a trivial change as I anticipated

Adding the checkbox back in is fine by me. I have updated the mockup to suit: https://mozilla.invisionapp.com/share/P7R8W1ZWHM6
