### ISSUE TITLE
[Bug] font inflation issue on rexdl.com

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#10098]
Originally reported here: https://github.com/webcompat/web-bugs/issues/51736

STR:

1. go to https://rexdl.com/android/spotify-music-apk-mod-download.html/
1. click "go to download page"

Expected: the text looks similar to Chrome Mobile or Fennec.
Actual: the fonts are all blown up. :bomb: 

(see screenshots here: https://github.com/webcompat/web-bugs/issues/51736#issuecomment-617050598)

**Comment by buttercookie42** [comment]
> or Fennec.

(Side note, but of course this applies only if you didn't enable font size scaling in Fennec as well...)

I'll try and take a look at what is happening there, though looking at their layout I'm not sure how best to detect that kind of situation (and I'm not at all set up to debug Blink for finding out why they don't inflate the list and just reading through their source doesn't give any immediate clues, either).

The most immediate solution would be if that page could simply use a proper `<meta
name=viewport content="width=device-width, initial-scale=1.0">` tag like they ought to anyway - the main page of rexdl.com already does that and the layout of the download page seems to look okay when resized to a narrow window width, too, so I'm not sure why they left that off there...

**Comment by buttercookie42** [comment]
I've taken a look at the layout of that page, but didn't spot any obvious opportunity for doing something different there without potentially regressing other pages.
I'm also still not sure what exactly Chrome is doing differently there from reading [their source](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/layout/text_autosizer.cc) alone, though they must probably in some way use smaller font inflation flow root-equivalents [1] so that each of the download buttons is considered individually and hence remains below the font inflation threshold.
In that case it would probably be unwise to attempt copying whatever they're doing without also implementing their font inflation "fingerprinting" (see [bug 786382](https://bugzilla.mozilla.org/show_bug.cgi?id=786382#c11)) as well, otherwise we'd be running into the opposite problem - text not inflating and remaining illegibly small when it actually should inflate.

Plus while the current state isn't ideal, there are worse examples out there and at least it means the download links are readable without having to zoom in despite them having forgotten to use `<meta name=viewport content="width=device-width, initial-scale=1.0">` on their download page, too.



[1] Small recap: We divide a page into font inflation flow roots and check the amount of text inside each flow root. If it's above the inflation threshold we'll inflate it, if it isn't we assume it's some sort of header/footer/nav bar and the like and don't touch its font size.

**Comment by miketaylr** [comment]
This is still a valid bug, but oh well. 😿
