### ISSUE TITLE
FNX-3297 ⁃ [Bug] add on not loaded

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10120]
## Steps to reproduce
this is the second built without addon
after updating browse as usual

### Expected behavior
add on loaded

### Actual behavior
no addon

### Device information
* Android device: N960F Android 10 april patch
* Fenix version: 200422 16:13

**Comment by sflorean** [comment]
@wijayafamily could you please share what addon has the issue?

**Comment by wijayafamily** [comment]
all add-ons, ublock origin, https everywhere, noscript security suite.

**Comment by wijayafamily** [comment]
![Screenshot_20200424-065844_Firefox Nightly](https://user-images.githubusercontent.com/63433757/80166129-62e09580-8607-11ea-99a9-1977194d2b58.jpg)
![Screenshot_20200424-065815_Firefox Nightly](https://user-images.githubusercontent.com/63433757/80166147-6d029400-8607-11ea-9075-73214f7a6bf4.jpg)

**Comment by wijayafamily** [comment]
ok, partly my fault, the last 3 build of fenix reset allow addon on private browsing to off. and I didn't see that, proceed to websites but no warning or whatsoever that I need to enable it for private browsing even in the add on setting page.

**Comment by wijayafamily** [comment]
this can happen to anyone, I would suggest a notification if add on is enabled, allow in private is off, private mode is on, tell user about it.

on addon settings if private mode on, allow in private off, settings page should say that.

**Comment by csadilek** [comment]
@wijayafamily Sorry, for the troubles. The first issue you ran into was https://github.com/mozilla-mobile/fenix/issues/10070 and a recent regression described in https://bugzilla.mozilla.org/show_bug.cgi?id=1631137.

Everything should be back to normal in Nightly 200424 06:01.

The second issue is due to us adjusting the private browsing default to align with desktop. Add-ons do run in private browsing by default. The ticket is here: https://github.com/mozilla-mobile/fenix/issues/6123

I've forward your concern to our UX team here: https://github.com/mozilla-mobile/fenix/issues/6123#issuecomment-619023367 and I agree that this can be improved.

Thanks for filing!
