### ISSUE TITLE
FNX-3302 ⁃ Nightly was not downloaded regularly

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#10129]
## Steps to reproduce
Google Play stopped proposing Nightly on one of devices. I cannot provide nice replication steps, but it was probably after using option "Leave beta programs" from Google Play.

### Expected behavior
Firefox should have some protection and show link to Google Play when version on device seems to be too old and there is an update (for Nightly it should be done for example after 2 days or similar short period)

I classify it as bug, not FR ~~> even, if GP has got some non~~clear behavior, lack of making updating app when there is new version, is problematic.

### Actual behavior
Nothing.

### Device information
* Android device: S7 / Android 8
* Fenix version: Nightly from March

**Comment by SS1113** [comment]
Hi, @marcinwiacek If you are referring to Nightly versions being delayed and are being updated less frequently than before from Google Play, it's due to the ongoing pandemic situation, you can read more about it [here](https://www.androidpolice.com/2020/03/16/google-play-store-app-reviews-will-take-7-days-or-longer/). You can download latest Nightly versions for testing [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2).

**Comment by marcinwiacek** [comment]
thx. I didn't get update for (less or more) about month - my last version was 200320 and I had to update it manually to 200422 (from Google Play app). Phone just haven't seen update.

I think, that regular checks for app itself should be done (maybe once a week or something).

**Comment by marcinwiacek** [comment]
hmmm, situation from today (again) - Google Play didn't propose me update on the list of updates, I had to do it manually (find app in the store, enter its' screen and press Update). App after update is not shown on the list of last updated apps. Google Play 19.7.12

**Comment by liuche** [comment]
Since this is a Google Play Store problem, there's not much that we can do about it. Adding a prompt in-app will be annoying to some users, so I'm going to close this bug as not actionable.
