### ISSUE TITLE
FNX-3320 ⁃ Validate performance of bottom dynamic nav bar feature

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#10157]
The bottom dynamic nav bar https://github.com/mozilla-mobile/fenix/issues/4383 is behind a feature flag currently https://github.com/mozilla-mobile/fenix/issues/8775. We should validate the performance of the feature before it ships.

Release criteria TBD...

**Comment by mcomella** [comment]
Triage: acreskey is investigating this from a platform perspective: waiting. I'd assign them but they don't have permissions to be assigned yet.

**Comment by acreskeyMoz** [comment]
I initially had concerns that the dynamic Nav Bar's behaviour could result in a resize of GeckoView. (Leading to expensive reflows.)
However, after looking into the source and discussing this with multiple teams, it turns out that that is not the case.
The Nav Bar is a visual element which animates up and down based on the input/scroll events.
There are numerous potential correctness issues, depending on the varied content being presented.

However I do not see any performance problems.
In local testing and profiling on a lower end phone, Moto G5, the bottom dynamic Nav Bar was perfectly performant.

**Comment by mcomella** [comment]
I looked at a profile acreskeyMoz took for this interaction and I didn't see anything concerning on the Java main thread: lgtm.

**Comment by yoasif** [comment]
@mcomella I'm not able to reproduce today, but yesterday I saw some really bad janking when doing this interaction: https://github.com/mozilla-mobile/fenix/issues/11044

Not sure if this was measured, but may be worth a look.

**Comment by mcomella** [comment]
> @mcomella I'm not able to reproduce today, but yesterday I saw some really bad janking when doing this interaction: #11044

@yoasif Thanks for the note – to be explicit, you saw bad janking in the toolbar with the url bar when doing that interaction? Or is your issue totally captured in #11044?
