### ISSUE TITLE
Separate clear history from site data

### ISSUE THREAD

**Issue by RichardRobertson** [mozilla-mobile/fenix#10175]
### Why/User Benefit/User Problem
Firefox Beta for Android can be configured to clear certain items on exit. History and site data are a single checkbox so I am not given the choice to clear history but keep site data.

### What/Requirements
I use sites that store local data so I can use it again next time without any cookies or sign in. I don't want to store a history but I do want the data I typed into that site.
Example is https://ac-turnip.com/ 

### Acceptance Criteria (how do I know when I’m done?)
Separate checkboxes for history and site data.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-215)

**Comment by mattmccutchen** [comment]
I have the opposite use case: keep history (so I can find things again if I didn't think to bookmark them) and clear site data that might be used to track me across sessions.  It surprises me that site data wasn't just grouped with cookies because they have essentially the same privacy implications.

If and when #10581 is implemented, I'll probably have a much better and more flexible solution by deleting and recreating a container.  Workaround in the meantime (for my rooted phone), which I just tested and it seems to work:

1. Force stop Firefox and back up `/data/data/org.mozilla.firefox/files/places*`.  (Since an SQLite database can consist of a variable number of files and mixing and matching them can corrupt the database, it's important to delete _all_ `places*` files from the destination before copying whatever files currently exist on the source, and likewise on restore.  I have a widget on the home screen that runs a script in the jackpal terminal that does `su` to the app user and changes to the app SELinux context before manipulating the files; I can provide more details if anyone is interested.)
2. Start Firefox and "Quit", configured to clear history and site data.
3. Force stop Firefox and restore `/data/data/org.mozilla.firefox/files/places*`.

I considered deleting `/data/data/org.mozilla.firefox/files/mozilla/PROFILE_DIR/storage`, but I'm not sure if that gets everything; I'd much rather use the official "delete browsing data" feature.

**Comment by hackel** [comment]
Any chance of increasing the priority of this issue?  For a privacy-focused browser, this is a rather critical privacy issue and it hasn't been touched in a year.

I'm extremely uncomfortable not knowing what localstorage and indexdb data is being stored in my profile and having no way to delete it without erasing my entire history. (Presumably across all my other synced devices as well.)

**Comment by mattmccutchen** [comment]
@hackel If you're using Firefox Sync, one workaround (inefficient but hopefully reliable) might be to wipe the Android app's storage via the OS, open the app again, sign into Firefox Sync, and let it automatically re-download all the other [categories of synced data](https://support.mozilla.org/en-US/kb/how-do-i-choose-what-information-sync-firefox).  It sounds like cookies, local storage, etc. are never synced.  Want to try that and report to us whether it works?  I don't use Firefox Sync myself, so it's probably easier if you try it than if I set up an environment just for this test.

**Comment by hackel** [comment]
@mattmccutchen Yes, that would certainly erase all site data, but it would also take all my open tabs, extensions and their configs, etc. along with it, so it's really not a good solution for this particular issue.  I could probably achieve the same by first deactivating sync and then erasing my history and site data.  I may experiment with such a workaround.

**Comment by B0ycee** [comment]
Anyone have any ideas how to get this more visible to potential developers?  Been open a couple of years and this seems like a sensible change that aligns with desktop Firefox.  Without it I cannot use the application.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813099

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
