### ISSUE TITLE
FNX-3340 ⁃ [Bug] Reader mode sometimes renders content in corner of page

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#10184]
## Steps to reproduce
Go to [url](https://krebsonsecurity.com/2020/04/when-in-doubt-hang-up-look-up-call-back/)
Enter reader mode
If the problem doesn't occur, hit back to exit Reader mode, zoom out all the way, and enter reader mode again

### Expected behavior
Reader mode occupies entire visible space

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/485789/80206387-32dec580-85fa-11ea-8e15-634396cd9dc2.png)UNITO-UNDERSCORE!20200424-070610!

### Device information
* Android device: Sony Xperia xz1c
* Fenix version: Nightly 200422 16:13 (Build #21131617)
39.0.20200422145552, 1ee8c073e
GV: 77.0a1-20200422093542
AS: 0.57.0

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is reproducible using the URL from the description.
It seems that the page is zoomed-in when you disable the reader mode and after re-enabling the reader mode will determinate the page to be zoomed out.

Build:
- Firefox Preview Nightly 4/24 #21150607.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9).

![20200424_145703](https://user-images.githubusercontent.com/40264165/80210261-211e1200-863c-11ea-9129-d293ed4d3299.gif)

**Comment by yoasif** [comment]
I think this is a dupe of https://github.com/mozilla-mobile/fenix/issues/2633

**Comment by csadilek** [comment]
@yoasif yes, thanks! Let's dupe this to #2633. I know this was filed a long time ago, but we've actively moved extension support forward and are getting close to being able to resolve this, as described in: https://github.com/mozilla-mobile/android-components/issues/2985

There were a lot of missing pieces, which hopefully will fall in place soon.
