### ISSUE TITLE
FNX-3343 ⁃ [Bug] "Add shortcut" for PB pop-up has a large space between the text and the buttons

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10188]
## Steps to reproduce
1. Have a clean profile, and tap on the private icon three times in order for the pop-up to be displayed.

### Expected behavior
The pop-up is displayed with no UI issues.

### Actual behavior
There is a large space between the "Add a shortcut to open private tabs from your Home screen." text and the [Add shortcut] button - please see the screenshot below.

### Device information
* Android device: all
* Fenix version: 4/24 Nightly build

![](https://user-images.githubusercontent.com/40694158/80217022-ad820200-8647-11ea-889e-ed543696d023.png)

**Comment by Diana-Rus** [comment]
HI, verified as fixed with Google Pixel 3XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) on FIrefox Peview Nightly 4/ 27 .

Google Pixel 3 XL - GIF
![20200427-100718](https://user-images.githubusercontent.com/49859863/80346754-ea324100-8873-11ea-8461-18e9c99af9c6.gif)

Samsung Galaxy S9 - GIF
![20200427-102302](https://user-images.githubusercontent.com/49859863/80346844-16e65880-8874-11ea-86e5-bef8a1de44a0.gif)

Sony Xperia Z5 - GIF
![20200427-103112](https://user-images.githubusercontent.com/49859863/80346794-fd451100-8873-11ea-88cf-392ca2c273fe.gif)
