### ISSUE TITLE
FNX-3391 ⁃ Please reimplement Fennec New Tab/URL Entry/Home screen

### ISSUE THREAD

**Issue by yump** [mozilla-mobile/fenix#10255]
### Why/User Benefit/User Problem
Fenix is expected to replace Fennec. From a development perspective you may be building a new UX, but users will experience this as a (large) change to the old UX.  The potential benefit of any UX change should be weighed against invalidating the muscle memory of all present users.  UX changes begin life as harmful, and must greatly improve over the old UX to balance the harm.

Although I understand that there is a lot planning, design, and coding invested into the new library menus, millions (I hope) of users have invested an enormous amount of experience in Fennec's workflow. I don't have the analytics, but it would not surprise me if the total amount of human-years spent interacting with Fennec's new tab page was comparable to a lifespan.  Please count this cost.

And the Fennec UX is itself the result of a lot careful design, programming, and refinement. It is not _bad_. There are things that could be better, but wholesale replacement can introduce new problems as much as it fixes old ones.

### What/Requirements
Please get Fennec's UX working in Fenix first, then make incremental changes from there.

### Acceptance Criteria (how do I know when I’m done?)
The experience of opening a new tab, or navigating to a different website, is behaviorally indistinguishable from Fennec.

**Comment by kbrosnan** [comment]
Fenix is not intended to be a 1:1 replacement of Fenenc. You can look over https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+is%3Aissue+label%3AFeature%3AFennecTransition for a list of identified differences. If there is something missing please open up individual issues for each feature.

One of the main areas we have identified is reworking the tabs view. There is work on a more traditional tabs tray instead of the home screen tabs list. You can follow along at https://github.com/orgs/mozilla-mobile/projects/53
