### ISSUE TITLE
[Bug] Task status badge in README is broken

### ISSUE THREAD

**Issue by danielzgtg** [mozilla-mobile/fenix#10256]
## Steps to reproduce
1. Open https://github.com/mozilla-mobile/fenix (in any browser)
1. Scroll down to the README
1. Click on "task status"

### Expected behavior
To see the badge contents, and for the badge as as a link not to be broken. If that is not possible, for the broken badge to be removed.

### Actual behavior
![image](https://user-images.githubusercontent.com/25646384/80439586-e4207c80-88d4-11ea-8cb5-cc2046345bce.png)

![image](https://user-images.githubusercontent.com/25646384/80439594-e7b40380-88d4-11ea-9f84-16df5c327dab.png)

**Comment by sv-sdeiac** [comment]
Hi, this is not a Firefox issue since it can be reproducible using other browsers. 
Also, it seems to be reproducible only with the broken icon link and I can't found other repositories with this problem. 

Devices/builds
- Windows 10 - x64bit (Google Chrome);
- Google Pixel (Android 10) - (Firefox for Android 68.7.0, Firefox Preview Nightly 4/28, Chrome).

**Comment by eliserichards** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/43795363/80529738-8421e880-895d-11ea-801c-a4c1c97710a4.png">

The link, https://github.taskcluster.net/v1/repository/mozilla-mobile/fenix/master/latest, is no longer valid.

**Comment by liuche** [comment]
@JohanLorenzo or @MihaiTabara, two quick questions here:
- Is there a new "master" output for Fenix TC runs on master, or is that Nightly?
- Will there be CI badging like what we used to have, or is that something Releng has decided to leave off? If so, we could remove it (or just link to the correct task output). I couldn't find it when looking at the [task page](https://firefox-ci-tc.services.mozilla.com/tasks/groups/X2qzYNZeSxm9QFJYzle6EQ).

I noticed the badging is missing from all the other repos to, so I can make that change if CI badging isn't supported anymore.

**Comment by JohanLorenzo** [comment]
Thank you for calling this out, @liuche! I hadn't noticed the badge is broken. I looked more closely at it and I see it points to these 2 URLs:
 * https://github.taskcluster.net/v1/repository/mozilla-mobile/fenix/master/badge.svg
 * https://github.taskcluster.net/v1/repository/mozilla-mobile/fenix/master/latest

`taskcluster.net` references the old Taskcluster instance. We need to update the locations to use firefox-ci-tc.services.mozilla.com instead. That said, I don't know what the new location is. @owlishDeveloper, would you know where the new location of the GH badge is?

**Comment by owlishDeveloper** [comment]
@JohanLorenzo  needs to be a new API endpoint for this one. I'd file a bug with Taskcluster team for this

**Comment by JohanLorenzo** [comment]
Got it! I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1640155 🙂

**Comment by djmitche** [comment]
The badge endpoint still exists:

* docs - https://firefox-ci-tc.services.mozilla.com/docs/reference/integrations/github/api#badge
* url - https://firefox-ci-tc.services.mozilla.com/api/github/v1/repository/mozilla-mobile/fenix/master/badge.svg
* image - <img src="https://firefox-ci-tc.services.mozilla.com/api/github/v1/repository/mozilla-mobile/fenix/master/badge.svg">

I believe the "no info yet" is because it is using the (technically still experimental) checks API.  So it may be best to just not use a TC badge for the moment :(
