### ISSUE TITLE
In_content search telemetry for Baidu not tracked

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/fenix#10300]
## Steps to reproduce
Go to Baidu and search for anything

### Expected behavior
Sap or organic telemetry is tracked

### Actual behavior
No metric is tracked

### Device information
* Android device: Any
* Fenix version: Latest develop

### Engineering info
The problem is that the Desktop codes for tracking are different than those on mobile. We need to research and understand the differences (example: `word` instead of `wd` for `queryParam`)

**Comment by rxumoz** [comment]
Hi @BranescuMihai  @eliserichards 
According to our investigation, besides the params, Baidu has two different types of search urls on mobile, which could also make trouble.
Originally what we set in the search engine is like: https://m.baidu.com/s?from=1000969a&word=test
But after an in_content search the url will be redirect to something like: https://m.baidu.com/from=1000969a/s?word=test&...
The positions of `s?` and `from=1000969a` are changed， so it might need more modification in code to track Baidu related search telemetry.
We Beijing office would like to see the data of Baidu search, so maybe we can have some discussion and then I can help to submit a PR.

**Comment by rxumoz** [comment]
Hi hi I've submit a draft PR here: https://github.com/mozilla-mobile/fenix/pull/19127

There is still a problem. Let's see the log and the json from Glean debug pings viewer:
<img width="798" alt="截屏2021-04-20 上午10 01 09" src="https://user-images.githubusercontent.com/33616048/115343869-1a8a9200-a1df-11eb-80a5-271ea8b866d2.png">
<img width="419" alt="截屏2021-04-20 上午10 01 22" src="https://user-images.githubusercontent.com/33616048/115343900-2413fa00-a1df-11eb-9364-99fabc2d7935.png">

The key of _baidu_ has been converted to _other_ , due to "1000969a" is not started with a letter but a figure I think. I've found the label format requirement [here](https://searchfox.org/mozilla-mobile/source/application-services/components/external/glean/docs/user/user/metrics/index.md#69) saying the format should be like ^[a-z_][a-z0-9_-]{0,29}(\\.[a-z_][a-z0-9_-]{0,29})*$

Thus we may discuss about how to deal with it.

Don't really know whom I should communicate with, so just @kbrosnan
