### ISSUE TITLE
FNX3-13802 ⁃ pressing back button should return to history

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1031]
### Steps to reproduce
1. Menu > Your Library > History
1. click on a website from your history
1. press the back button of your device

### Expected behavior
You return to the history view.

### Actual behavior
You are on the Fenix home screen.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 92559622195f44d1f715ae002809cf6e00eacecf

**Comment by ekager** [comment]
I think this isn't necessarily a "bug" and we need UX feedback on this. 
Chrome opens History similar to how Fenix does (in its own fragment) and clicking back after opening an item does not bring you back to History. 
Fennec opens history in a view inside of the current tab, and selecting an item and pressing back does take you back to History. 
The engineering instinct was to pop to the home screen when the user selects a history item so that pressing back does not take you back to history and muddy the backstack, but it is a trivial change if UX decides differently.

**Comment by boek** [comment]
dup of #1012
