### ISSUE TITLE
FNX2-13137 ⁃ Improve performance of opening context menu with bookmarked item

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#10356]
Follow-up from context menu performance investigation https://github.com/mozilla-mobile/fenix/issues/10096. We defined the following release criteria:

> GIVEN Fenix on 2018 (low-end|high-end) Android reference
AND a bookmarked page is loaded
WHEN opening the Context Menu
THEN the Context Menu is rendered in less than 100ms

Excluding the 200ms animation, my measurements https://github.com/mozilla-mobile/fenix/issues/10096#issuecomment-622564811 showed the menu render time is above 100ms on the Galaxy S5 (272.33ms or 176.3ms, depending on how you look at it), a low-end device, but below 100 ms on the Pixel 2 (99.33ms or 71.30ms). We should improve performance to hit our release criteria on low-end devices.

To validate that hitting our release criteria is possible, we may want to create a standalone app that inflates a simple view when an onscreen button is tapped and measure how long it takes for that view to appear. I filed https://github.com/mozilla-mobile/perf-frontend-issues/issues/107 for this work.

**Comment by MarcLeclair** [comment]
After looking at this and playing around with our XML layout, it doesn't seem there's much to be done in terms of easy gains. There might be possibilities in improving our measurement or some of the things we do by hand, but I'm not sure it would be worth looking into this before release. 

On the G5, opening the context menu took ~150ms on first click, second and third click ranged from 105-120ms and all subsequent clicks were below 90ms. 

There's also another odd behavior where, sometimes, I would see the full inflation and other times, the profile would catch it differently. My guess is that it was just faster, but I don't want to assume too much.

Here's two profile that explain the above comment: 

1) https://share.firefox.dev/2Y8wyfp --> there's 1 chunk of 50ms for `inflate` for the `createViewHolder` which doesn't seem right but I can't reproduce that 100% of the time

2) https://share.firefox.dev/2Y47G8D --> has multiple `onCreateViewHolder` and inflate broken down in smaller chunk.

Maybe this is because the method happened too quickly for the profiler to catch them? I'm not sure.

**Comment by mcomella** [comment]
Tracking on JIRA: https://jira.mozilla.com/browse/FXP-1276
