### ISSUE TITLE
FNX-3480 ⁃ Tab tray home button seems superfluous, since new tab could easily do this

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10373]
### Why/User Benefit/User Problem
As a user, I would like to access home like competing browsers and Fennec, and not have two buttons that seemingly do the same thing (new tab/home). 

### What/Requirements
* Fix https://github.com/mozilla-mobile/fenix/issues/10368
* remove home button in tab tray

### Acceptance Criteria (how do I know when I’m done?)
Home button is not present in tab tray any more.

**Comment by Cheap-Skate** [comment]
+1, I find this new system very confusing. Same reasons as @yoasif.

**Comment by cadeyrn** [comment]
If this issue is basically nothing else than implementing #10368 and then removing the button which does only the same if #10368 will be implemented then I don't understand why this issue is needed.

At the moment both buttons do different things and it doesn't make sense to remove the button unless #10368 will be implement. But then, again, it should be handled by #10368.

**Comment by yoasif** [comment]
@cadeyrn One could flesh out https://github.com/mozilla-mobile/fenix/issues/7551 and the button might be less superfluous.

**Comment by topotropic** [comment]
Thanks for the feedback, home button is gone so I'll close it. 
We'll consider https://github.com/mozilla-mobile/fenix/issues/10368
