### ISSUE TITLE
Crash in OOM Small due to a page with a lot of images

### ISSUE THREAD

**Issue by ktaeleman** [mozilla-mobile/fenix#10385]
## Steps to reproduce
Go to https://musicgenretree.org/chart.html

### Actual behavior
After a couple of seconds the browser crashes

### Device information
* Android device: ?
* Fenix version: ?

**Comment by lindongbin** [comment]
no crash on fennec production
null (Build #2015738003)
40.0.20200430224518, 2227e0a76
GV: 76.0-20200424000239
AS: 0.58.2
Saturday 5/2 @ 6:07 PM

**Comment by ebalazs-sv** [comment]
Hi and thanks for this report!
I can reproduce this on Firefox Preview Nightly 200507 GV 77 from 5/7 with Motorola Moto G6 (Android 8), LG G7 fit (Android 8) following the steps:

#### Steps to reproduce:
1. Launch Fenix;
2. Go to https://musicgenretree.org/chart.html;
3. Observe the behavior;

#### Expected behavior
The page is loading.

#### Actual behavior
The page loads for 1-2 seconds and then crashes.

#### Notes:
[Video](https://drive.google.com/open?id=1FKUp5micvaPB3ca0xg2hIfv4VqvMs3oA)
[Crash-page.txt](https://github.com/mozilla-mobile/fenix/files/4593428/Crash-page.txt)
When restarting Fenix, the page is displayed in Open tabs, and when accessing it, will crash again.
This is not reproducible on Pixel 2 (Android 9), OnePlus 6T (Android 9), Huawei MediaPad M3 Lite 10 (Android 7.0), Samsung Galaxy S9 (Android 8).

**Comment by liuche** [comment]
@ekager what's the gecko reason here? or because it's in web content.

**Comment by ekager** [comment]
Yeah from first glance I assumed Gecko because 100% on a specific website but looks like it could be related to https://github.com/mozilla-mobile/fenix/issues/10517 or https://github.com/mozilla-mobile/fenix/issues/9483

**Comment by mcarare** [comment]
@ebalazs-sv can you still reproduces this on the devices you mentioned? I haven't been able to reproduce this. TY!

**Comment by ebalazs-sv** [comment]
@mcarare Yes, this is still reproducible on Fenix Nightly Build 21480607, from 5/27, with Motorola Moto G6 (Android 8).

**Comment by Mugurell** [comment]
I'd also believe this is a memory issue but I tried to reproduce it on different devices / emulators and I couldn't.
@ebalazs-sv if this is still reproducing could you please help with a Socorro report? It would help better understand the issue and a crash signature would allow a better assessment of it's real world prevalence.

**Comment by ebalazs-sv** [comment]
@Mugurell This is still reproducible on the latest Fenix Nightly Build #217406609 from 6/22 with Motorola Moto G6 (Android 8).
Socorro report:
https://crash-stats.mozilla.org/report/index/bab030a4-6da6-4fb4-b49a-b0fe30200622#tab-details

**Comment by Mugurell** [comment]
Thank you Eliza!
Based on the crash signature looks like we are seeing many of these on all platforms. May be a core issue. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1647269.
