### ISSUE TITLE
[Bug] Screen does not render when going back from footnote hyperlink

### ISSUE THREAD

**Issue by marthinwurer** [mozilla-mobile/fenix#10424]
## Steps to reproduce
Go to https://danluu.com/everything-is-broken/ (extremely ironic that this page caused this)
Scroll to the bottom
Hit the return link for footnote 3
Hit the back button
(You might need to do this a few times)

### Expected behavior
The website renders where I was at the bottom of the page

### Actual behavior
I either get a blank white screen or can only see hyperlinks

### Device information
* Android device: S8, Android 9
* Fenix version: 4.3.0 (Build #21082025)
38.0.0, 9f4362b6f
GV: 76.0-20200406152003
AS: 0.55.0

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is reproducible using the latest version of Firefox Preview RC 4.3.0.
Also, I wasn't able to reproduce it using the latest version of Firefox Preview Nightly 5/6 #21270609.

Devices:
- LGG7 fit (Android 8.1).

Also, I can see a different behavior using Google Pixel 3 (Android 10) and Samsung Galaxy Note 8 (Android 9). The pages are rendered correctly but with a lack of time(1-2 sec).
