### ISSUE TITLE
FNX-4283 ⁃ [Bug] getProcessStartTimeTicks crash

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#10434]
Crash in `fenix.perf` with `getProcessStartTimeTicks` in 5.0.0 release build.

Sentry log: https://sentry.prod.mozaws.net/operations/fenix/issues/8293980/

**Comment by liuche** [comment]
@mcomella is this something from perf team monitoring?

**Comment by mcarare** [comment]
@liuche This seems to be a problem specific to using a privacy manager that relies on a hooking mechanism (SandHook) and it blocks reading the file in [Stat.kt](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/perf/Stat.kt#L28). The most we can do is catch the exception or maybe @mcomella has another idea.
 I do not think this crash will have a high recurrence.

**Comment by mcomella** [comment]
>  The most we can do is catch the exception or maybe @mcomella has another idea.

Yeah, I think we'll have to catch the exception.

This doesn't seem to have a high crash count and does seem to be related to OS customization so it doesn't urgent: I'll wait for triage later today to figure out the priority. This is probably a permacrash though and the fix is straightforward so I think we should address it, despite the low crash count.

**Comment by liuche** [comment]
This is with 1% rollout, but reasons seem good, I'll remove the RB label.
