### ISSUE TITLE
FNX-4281 ⁃ [Bug] Cannot invoke observeForever on a background thread Crash

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#10432]
Filing from [Sentry report](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8308657/?query=is%3Aunresolved%20Cannot%20invoke%20observeForever%20on%20a%20background%20thread) in Fennec Beta channel.

Error from FxA: `Cannot invoke observeForever on a background thread`

**Comment by liuche** [comment]
@eoger @grigoryk didn't find anything earlier than 76.0.0 release on Monday, so this looks new.

**Comment by grigoryk** [comment]
Copying from Slack:
-  hmm, all stacktraces have FennecMigrator in the path
-   … which is likely a false flag, since that just happens to be the bit that initializes the account manager here; that logic didn’t change in months, so likely we’ve changed something elsewhere that would before init the account manager on the main thread, and now it’s happening on the background thread instead and breaks
-   so looks like there are at least two bugs here, one old (but was hiding and we weren’t hitting it) and one new (but not directly related to fxa/sync/a-s)

Will take a closer look later today. My bet currently is some Fenix change caused this.

**Comment by liuche** [comment]
Any updates on this @grigoryk? I don't have a good gauge yet on how crashes in Beta rollout correspond to seriousness, bc this is the first release I've done on Beta, but if Beta is only 2-3x Fenix population, then this is very high for what I'd accept for Fenix release.
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8308657/

~200/day at 5% release (compared to ~10/day for Fenix at 5%)

**Comment by liuche** [comment]
I'm going to leave 76.0.0 at 5% rollout for Firefox Beta until this is ready, because the crash rate still seems high to me.

I won't be cutting a 5.1 until the [high crashes](https://github.com/mozilla-mobile/android-components/issues/6903) on Nightly are resolved, but my inclination is to put this fix out in a new cut (rather than an uplift to the 76 branch).

**Comment by pocmo** [comment]
For reference here is the same crash in fennec-nightly:
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7699335

There we saw it first `March 27`.

**Comment by grigoryk** [comment]
@pocmo thanks! My bad with this one, I completely missed the nightly crash :( https://github.com/mozilla-mobile/android-components/pull/6964 should fix the problem.

**Comment by liuche** [comment]
Going to close this since it's now on the 5.0 branch and will land in master with an AC update, will keep an eye on crashes during rollout of 76.
