### ISSUE TITLE
FNX-4300 ⁃ [Bug] History, Bookmarks should not use "back" to exit, they should be closed

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10462]
References: https://github.com/mozilla-mobile/fenix/issues/5727 and https://github.com/mozilla-mobile/fenix/issues/10343

## Steps to reproduce
1. Open Bookmarks or History via menu

### Expected behavior
There is a "close" button like in Chrome or Edge instead of a back button. This is because since the history or bookmarks page are not part of the tab stack (or even the historical stack used while using the standard back navigation in Android), users are not "going back" anywhere (like the Library), they are simply closing the pane that they opened. 

Chrome:

![signal-attachment-2020-05-07-012010](https://user-images.githubusercontent.com/152493/81257318-f307dd00-9000-11ea-8c43-6a39a76a55d0.png)

Edge:

![signal-attachment-2020-05-07-012014](https://user-images.githubusercontent.com/152493/81257334-fef39f00-9000-11ea-8b3e-c4f19c356c72.png)

### Actual behavior
There is a back button.

### Device information
* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by goforbg** [comment]
Wow this has so many complications, I have worked on this for the past 2 hours now and to understand it took me a long (maybe it's just me). 

I created menu that supported a close button for history, and added a close button to bookmark's menu bar but calling onBackPressed() or BookmarkFragmentView.onBackpressed() didn't work, I tried popbackstack from support fragmentmanager but that ended up not going in to the fragment on next menu item clicked. To solve this I called BookmarkFragmentDirections.actionGlobalHome() using nav. 

So all I have to do now is to remove the back button, should be simple right? well, not really.
The toolbar is called from overriding the function showToolbar which calls the inflategetSupportActionBarAndInflateIfNecessary.

I created another SupportActionBarWithoutBack button function, but once this is inflated the toolbarinflated variable is set to true so that means, apart from Bookmarks and History not having back button (which is what we want), we don't have a back button for Settings, Help and stuff.

Never expected this to be as complex, I hope my comment helps someone to fix this bug or maybe I'll do it myself after a while.

**Comment by brampitoyo** [comment]
@topotropic Let me try to summarise the problem. The flow that demonstrates the issue @yoasif wrote is as follow:

1. Open Firefox —— show new tab page
2. Tap a top site —— show website number 1
3. Tap main menu → Library —— show Library page
4. Tap Bookmarks —— show Bookmarks sub-page
5. Tap a bookmark item —— show website number 2

If the user then presses the Android System Back button, it’s obvious that they should go back.

The question is: back to which page? There seems to be two alternatives:

- Back to page 5: Bookmarks sub-page
- Back to page 2: website number 1

Fenix chose the latter: the user goes back to website number 1. This means that they bypass both the Bookmarks sub-page and the Library page.

This means that both of those pages aren’t part of the “history stack”. And if they’re not part of the stack, then the top app bar shouldn’t show a Back button. Instead, it should show a Quit “x” button.

I think that @yoasif is partly right, and partly incorrect.

- Correct: the “root” Library page itself should show a Quit “x” button, because it’s not part of the history stack. This page shouldn’t show a Back button, because it’s not part of the “history stack”
- Partly incorrect: the “sub-pages” History and Bookmarks can be navigated “up” (back to “root” Library page) or “down” (to a bookmark folder). We should show a Quit “x” button to dismiss the whole Library screen, and should keep showing the Back button to allow users to navigate “up” to the “root” level

I don’t think this is a critical fix for the app. What do you think?

**Comment by yoasif** [comment]
@brampitoyo I think you may be missing a small bit of context -- issue https://github.com/mozilla-mobile/fenix/issues/10343

That says that the "Library" goes away entirely.

**Comment by brampitoyo** [comment]
@yoasif Yes, indeed I was missing a bit of context. Thanks for the reference!

If the “Library” root page goes away entirely, then it seems like “Bookmarks” and “History” can both be pages that have a Quit “x” button.

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/7931

Upon further consideration, I don't think the back button needs to go away if a user is inside a hierarchy, it just doesn't need to appear when a user is at the top level of Bookmarks.

The close button should always appear, even if the back button is present.

**Comment by ekager** [comment]
> @yoasif Yes, indeed I was missing a bit of context. Thanks for the reference!
> 
> If the “Library” root page goes away entirely, then it seems like “Bookmarks” and “History” can both be pages that have a Quit “x” button.

The Library page has indeed been removed, so I think this is actionable to switch to a close X.

**Comment by AmyYLee** [comment]
@ekager @yoasif - Is UX feedback still needed for this?

**Comment by yoasif** [comment]
@AmyYLee I think that we agree that this actionable per @ekager's comment. 

The close button should be added, I think that is pretty much the conclusion.

**Comment by topotropic** [comment]
Let's remove the back arrow for history and bookmarks root and just add it when you navigate into bookmark sub-folders and add an x to the right to quickly exit the view  <img width="867" alt="image" src="https://user-images.githubusercontent.com/353960/83774056-8b879080-a685-11ea-8ab5-0533efde8a6c.png">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build 200623 from 6/23** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-095739](https://user-images.githubusercontent.com/51314259/85371124-72615980-b538-11ea-8ee8-ae0aa4e53b67.gif)
