### ISSUE TITLE
FNX-4318 ⁃ [Bug]Can't install certain websites as PWAs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10483]
## Steps to reproduce
1. Navigate to the following websites:
https://www.lancome-usa.com/
https://www.pureformulas.com/
https://mag.continental.com/de/ 
https://asia.nikkei.com/
https://www.mynet.com/
https://www.digikala.com/
https://2048game.com/
1. Check if you can install them as PWA's 

### Expected behavior
The user should be able to install them

### Actual behavior
"Install" button missing from the ⋮ Main menu

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly build 200507 from 5/7

### Notes
❗ All the above mentioned websites can be installed as PWAs on Chrome

**Comment by NotWoods** [comment]
I checked each of the sites and tried to install them:

#### lancome-usa.com, pureformulas.com, mynet.com, 2048game.com
I couldn't find any Web App Manifest on these sites nor could I install them in Chrome. These sites don't appear to be PWAs.

#### asia.nikkei.com
I found a [manifest](https://asia.nikkei.com/assets/manifest.json) but it's not valid, it seems to be used for something else.

#### digikala.com
Successfully installed as PWA in Fenix!

#### mag.continental.com/de
This PWA has a [manifest](https://mag.continental.com/manifest.json), but we choose to install it as a regular shortcut because the icons are too small. Sites need to provide an icon at least 192x192 large, and the largest icon here is 180x180. I wasn't able to install this in Chrome either.

I'm going to close this issue, but let me know if I got anything wrong
