### ISSUE TITLE
FNX-4340 ⁃ [Bug] tab switcher UI latency

### ISSUE THREAD

**Issue by ujjwl3** [mozilla-mobile/fenix#10515]
## Steps to reproduce
Few open tabs

### Expected behavior
Smooth tab switch

### Actual behavior
There is a slight delay or lag when opening tab switcher

### Device information
Redmi Note 8 Pro

* Android device: 9
* Fenix version: 200508

**Comment by sv-sdeiac** [comment]
Hi @ujjwl3, thanks for your time to fill this bug. 
I wasn't able to reproduce your issue using the information from the description.
Can you please retry with the latest version of Firefox Preview Nightly?
Also, do you have any specific settings on your browser? This issue might be also due to Android. Maybe a little video with your problem can help us to reproduce your issue.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

Build:
- Firefox Preview Nightly 5/11 #21320625.

**Comment by ekager** [comment]
@ujjwl3 could you possibly give a recording or more information that could help us investigate this issue?

**Comment by struq** [comment]
This also occurs on Motorola XT1575 (Android 7.0) here, with both Preview 5.0 and Nightly 200531 fresh install. There is a one second delay after clicking the tab button and before the tab switcher appears, and another one second delay after clicking on a tab and before the content shows up. I'm attaching the screen recording.
[recording.zip](https://github.com/mozilla-mobile/fenix/files/4709192/recording.zip)

**Comment by liuche** [comment]
This is a video of the old tabs UI, and haven't heard back from reporter, QA says can't repro, so going to close.
