### ISSUE TITLE
FNX-4338 ⁃ [Bug] Redundant "Save to collection button" in 3 dot menu in overview

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10510]
## Steps to reproduce
Open the overview screen
There are three different ways to save tab to collection on this screen.

1. Save to collection button below the tabs
1. Long pressing on a particular tab 
1. Save to collection button in 3 dot menu near the open tabs heading

It would be better to have the share , delete tab buttons like the ones in private browsing instead of a repeated save to collection option.

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by brampitoyo** [comment]
Assigning this issue to @topotropic.

**Comment by AmyYLee** [comment]
> Assigning this issue to @topotropic.

Following up on this - @topotropic

**Comment by topotropic** [comment]
We moved tabs to a dedicated tab tray and also don't support longpress nor have the button atm. We will revisit it and take your feedback into consideration. Thanks!

**Comment by toupeira** [comment]
> We moved tabs to a dedicated tab tray and also don't support longpress nor have the button atm. We will revisit it and take your feedback into consideration. Thanks!

@topotropic the stable version has all this now, so the original issue seems relevant again. Can you reopen?

Having 3 options to save collections in the tab switcher seems like overkill, and I especially dislike the always-visible "Save to collection" button in the tab switcher because I don't use collections (they don't make sense to me because of their session-restoring behaviour and missing sync support).

I also see now that "Save to collection" in both places just activates the tab selection mode, I originally assumed it was a shortcut that selects all current tabs and immediately prompts for the collection, which would seem more useful if I actually used collections.

Some proposals:

- Make the "Save to collection" button less distracting, maybe by using white-on-black colors, or white-on-purple like the "Save tabs to collection" button on the home screen (which I see now is gone in Nightly)
- Remove the "Save to collection" button again, since we already have that option in the overflow menu.
- Change one of the "Save to collection" actions into a "Save all tabs to collection" shortcut.
- Replace the "Save to collection" button with a "Select all tabs" button, and then add Close and Share actions to the selection popup. At this point we wouldn't even really need the overflow menu anymore, so we could also consider moving the "Select all tabs" action into that spot.
