### ISSUE TITLE
FNX-4374 ⁃ [Bug] Tapping on the example link from Add search engine opens the support page

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#10551]
## Steps to reproduce
1. Go to settings;
1. Select "Add search engine" from "Search" option;
1. Select "Other";
1. Tap on the example link.

### Expected behavior
Nothing happens when you tap on the example link.

### Actual behavior
The support page from the "Learn more" hyperlink is opened.

### Device information
Android device:

* Google Pixel 3 (Android 10);
* Samsung Galaxy Note 8 (Android 9);
* LG G7 fit (Android 8.1).
* Fenix version: Firefox Preview Nightly 5/11 #21320625.

![20200511](https://user-images.githubusercontent.com/40264165/81539251-a6156500-9378-11ea-8b58-f5edaafd558a.gif)UNITO-UNDERSCORE!111400!

**Comment by ekager** [comment]
The Learn More support link has a larger touch target that is covering the example link. We should check with UX to see if we should change anything here.

**Comment by AmyYLee** [comment]
@brampitoyo for feedback

**Comment by brampitoyo** [comment]
@ekager @sv-sdeiac I think that the touch target should only cover the “Learn more” link, so if you tap anywhere else on that paragraph of text, nothing would happen.

**Comment by ValentinTimisica** [comment]
Reopening for QA.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-093053](https://user-images.githubusercontent.com/51314259/85368838-a6d31680-b534-11ea-9e7d-fc4c3a7f58cb.gif)

**Comment by mcarare** [comment]
I have discussed this with @AndiAJ . The behavior described is an a11y change I implemented, because the touch target for the learn more link would have been reported as too small by the accessibility scanner. The change follows the UX decision: "if you tap anywhere else on that paragraph of text, nothing would happen." Tapping anywhere on other text **does not trigger the link**, only tapping on the link row or in an a11y area of 48 height around the link.

I am closing this. @brampitoyo if you consider this not ok, please feel free to reopen and share your decision. TY!

**Comment by AndiAJ** [comment]
In this case, **verified as fixed** on the latest **Nightly Build 200623 from 6/23** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-093053](https://user-images.githubusercontent.com/51314259/85376178-0f73c080-b540-11ea-85d4-818e94c25669.gif)
