### ISSUE TITLE
[Bug] can't add spot.ecloud.global as search engine

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#10605]
## Steps to reproduce
1. Go to settings
1. Go to search
1. Click on add search engine
1. Click on "other"
1. In the text areas, put this: Name: Spot, or whatever you want. Search string to use: https://spot.ecloud.global/?q=%s
1. Confirm (top right button)
    1. Expected behavior
It add the search engine
    1. Actual behavior
In red, below search string to use: Error connecting to "Spot"
![](https://user-images.githubusercontent.com/58657617/81734453-0d1f4080-9483-11ea-9437-4411260e7220.png)
    1. Device information

* Android device: 9
* Fenix version: 5.0, nightly 200512

### Notes
I could add other search engines without problem.
The search string is correct: copy paste `https://spot.ecloud.global/?q=firefox preview` in url bar, you'll have results for "firefox preview".
I managed to add it on desktop with the search bar (not url bar) by pressing the glass+ button:
![](https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2018-03-08-18-11-36-8dfe62.png)

It was happening in 4.3 version too.

**Comment by ValentinTimisica** [comment]
I investigated this and we receive `response.status=500`(check [this line](https://github.com/mozilla-mobile/fenix/blob/bded28a017dee70eb163f70fff38aa66e60f8806/app/src/main/java/org/mozilla/fenix/settings/search/SearchStringValidator.kt#L33)). The url from the request is "https://spot.ecloud.global/?q=1".

It seems like the problem relies in the [headers](https://github.com/mozilla-mobile/android-components/blob/35ce172ca134004be80873aa6e7f92e47ac89ee9/components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Client.kt#L98) we use in [this request](https://github.com/mozilla-mobile/fenix/blob/bded28a017dee70eb163f70fff38aa66e60f8806/app/src/main/java/org/mozilla/fenix/settings/search/SearchStringValidator.kt#L23).
The header that causes the problem is `"Accept-Language" to "*/*"`. You can see in the screenshots below (Postman) that if we exclude `Accept-Language` header the response will be 200, otherwise, the response is 500.

<img width="1061" alt="postman1" src="https://user-images.githubusercontent.com/52956363/81823668-33091b80-953d-11ea-959b-d7e3b5695398.png">
<img width="1066" alt="postman2" src="https://user-images.githubusercontent.com/52956363/81823686-38fefc80-953d-11ea-870d-5fe8c6769349.png">

The same, if we don't use any header, the response is 200, if we add only `Accept-Language` we will receive 500.

I also checked in desktop Chrome (it works, the response is 200) and for my search the value for `Accept-Language` was `en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7`.

Note that I bypassed the check(by returning Result.Success [here](https://github.com/mozilla-mobile/fenix/blob/bded28a017dee70eb163f70fff38aa66e60f8806/app/src/main/java/org/mozilla/fenix/settings/search/SearchStringValidator.kt#L32)) and I managed to add this custom search engine. After that I set this engine as default and made a search with it (same url as above) and it worked well (no error).

Maybe the GV team can help here?

**Comment by rthery** [comment]
This may be related to #9831

**Comment by B0pol** [comment]
It works now then I close it
