### ISSUE TITLE
FNX-4457 ⁃ Show most recently opened tabs at the top of the tab tray

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10665]
We currently stack tabs in the tab tray by oldest -> newest.  We should reverse that so users see their most recently opened tab at the top of the tab tray.

**Comment by yump** [comment]
Why? Fennec's tab tray grows down, and while there may be small benefits to a stack vs list metaphor, change is inherently bad.

**Comment by yoasif** [comment]
Chrome, Vivaldi, Kiwi, Samsung Internet, Fennec show the newest tabs at the bottom. Edge shows the newest tabs at the top. 

I think this is really hard to judge in the current Fenix because tab tray always starts at the top of the list, which is incorrect and is going to bias us as users because we want to see the tab we just opened, and Fenix is taking us to the top of the list which is the oldest tabs first.

It would be if we had the newest tabs on top but Fenix always started at the bottom of the list when opening tab tray. 

I'm not saying one is correct either way, but I never had a problem with Fennec, and clearly most people on Android are already using Chrome with the same behavior.

**Comment by yump** [comment]
Obviously, the tab tray should open to whichever end has the most recent tabs.  Otherwise you would be scrolling to the other end of the tray every time you opened it.  The question is whether the new tab end should be the top or the bottom, and most of Fenix's users will be transplanted from Fennec, so Fenix should match the behavior of Fennec except in cases where there is a very strong reason not to.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video Normal Browsing
![20200529-115510](https://user-images.githubusercontent.com/51314259/83241744-f3306e00-a1a3-11ea-95df-aaba32c466c7.gif)

► Video Private Browsing
![20200529-115557](https://user-images.githubusercontent.com/51314259/83241866-270b9380-a1a4-11ea-9647-2e2638a79e8c.gif)
