### ISSUE TITLE
FNX-4467 ⁃ [Bug] Reddit upload button does not work

### ISSUE THREAD

**Issue by Rodze** [mozilla-mobile/fenix#10680]
## Steps to reproduce
Open a submit page such as https://www.reddit.com/r/test/submit
Switch the Firefox option to desktop site
On the reloaded reddit page, go to image & video.
Touch the upload button

### Expected behavior
Firefox gives options to select local files.
It works on Chrome at least.

### Actual behavior
Nothing happens

### Device information
* Android device: Galaxy S9
* Fenix version: Nightly 200514 06:00 (Build #2015740211)

**Comment by partha2000** [comment]
@Rodze Can I work on this issue?

**Comment by Rodze** [comment]
> @Rodze Can I work on this issue?

I'm just a regular user, I don't manage the project or contribute to the code. So I can't answer that haha.

**Comment by partha2000** [comment]
I found that this issue is not reproducible on my device. In fact, the upload button works perfectly fine for images/videos on reddit.com/r/test/submit in the desktop mode. Let's see if others are able to reproduce this issue.

Android Device: Xiaomi Redmi Note 7 Pro ( Android 9 )
![reddit button](https://user-images.githubusercontent.com/39731590/82125682-2e569880-97c5-11ea-95ad-458151a66e7e.gif)

**Comment by Rodze** [comment]
@partha2000 

In light of you showing it working, I tested multiple Firefox configurations settings and the problem persisted.

Then, I decide to simply uninstall and install again and it's now working. Haha

Something broke it but god knows what. 

Gonna close this.

Thanks!
