### ISSUE TITLE
FNX-4534 ⁃ [Bug] Intermittent UI test error: testStrictVisitSheetDetails

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#10761]
Firebase: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5567630782097466087/executions/bs.4d7517b916beb41f/testcases/1/logs

**Comment by sv-ohorvath** [comment]
From the video it looks like the ETP shield is not indicating blocked trackers, thus the content description will not match with the expected:
![ETP indicator](https://user-images.githubusercontent.com/4037709/82811552-b4e03980-9e99-11ea-9987-7fac2796d4ed.png)

**Comment by sv-ohorvath** [comment]
@AaronMT you are familiar with the scripts running on this test page. Could this be a bug of trackers not being blocked all the time, or just a temp glitch?

**Comment by sv-ohorvath** [comment]
Actually I just found this bug: https://github.com/mozilla-mobile/fenix/issues/7907
@rpappalax @AaronMT  should I disable this test due to the above bug, even though I don't think it is failing frequently.

**Comment by AaronMT** [comment]
That bug is what I was running into a while back but I took the recommendations and changed the tracker domains used several months ago https://github.com/mozilla-mobile/fenix/pull/8733 – this is the local asset https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/assets/pages/etp.html

It might be worth copying the m-c tracking page and creating a local copy of trackingAPI.js to see if there's any difference now as there was recent activity in March 

https://hg.mozilla.org/mozilla-central/filelog/882de07e4cbe31a0617d1ae350236123dfdbe17f/browser/base/content/test/protectionsUI/trackingPage.html

https://dxr.mozilla.org/mozilla-central/source/browser/base/content/test/protectionsUI/trackingAPI.js

https://dxr.mozilla.org/mozilla-central/source/browser/base/content/test/protectionsUI/trackingPage.html

@sv-ohorvath

**Comment by sv-ohorvath** [comment]
Started failing again on the new test page: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8643226351238168716/executions/bs.c90e26897940ce05/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
https://github.com/mozilla-mobile/fenix/issues/11387 was fixed and verified. I also ran this test on Firebase and it didn't fail. I assume this is now fixed and I'll close the issue.
