### ISSUE TITLE
Add: Setup window/process at first start

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [mozilla-mobile/fenix#10769]
### Description
This is the preparation to add a "Setup Window/Process" at the first start after installation.

For example, Firefox Preview will not immediately connect to external servers without asking the user.

Currently, when Firefox Preview is first start after installation, it connects to external servers from Mozilla Services immediately without asking the user. The setup would solve this.

It is also generally possible to extend the setup with other options.

### Version
Android 9

Firefox Preview 5.0.0
https://github.com/mozilla-mobile/fenix/releases/tag/v5.0.0

**Comment by Hug385** [comment]
This is a very good idea for Data Privacy.

Data Privacy means that the user can decide with whom he wants to share the data. It requires authorization from the user first.

That means in Firefox you have to integrate this by default. It must not automatically connect to external servers at first startup or other nasty tricks.

On the Firefox desktop (tested with version 79), the problem is that the first time Firefox is started, it automatically connects to external servers such as Pocket, Mozilla Service, News Feed, pings etc. This without asking the user.
There is no setup at all. This is not privacy and not clean.
