### ISSUE TITLE
[Bug] [L10n]Menus and submenus are not translated in Arabic

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10779]
## Steps to reproduce
1. Open Fenix app and go to menu/Settings/Language.
1. Make a search after Arabic and choose the language.
    1. Expected behavior
The app is translated in the chosen language.
    1. Actual behavior
The following menus and/or submenus are affected:

* Follow device language - option from Language
Submenus:
* Logins and passwords
* Enhanced tracking protection->all the options available here aren't translated
* Delete browsing data->all the options available here aren't translated
* Delete browsing data on quit->all the options available here aren't translated
* Open links in apps
Menus:
* History
* Add-ons
* Add to top sites
* Save to collection
Homescreen sections are not translated: open Tabs, New Tab button, Save to collection.
    1. Device information
* Android device: Sony Xperia Z5 (Android 7)
* Fenix version: Firefox Beta 5.1.0-beta.1, fenix Nightly 200514 (Build #21350607)

**Comment by abodea** [comment]
Re-checked this issue on the latest Nightly 7/7 with Google Pixel 4 XL (10).
Note that this issue is partially fixed as the following are still not translated to Arabic:
 - Enhanced Tracking Protection
 - Delete browsing data
 - Delete browsing data on quit

Note that the entire menus are not translated and not only the title in settings.

![Screenshot_20200707-115609](https://user-images.githubusercontent.com/42831109/86784363-16cfb980-c06a-11ea-8dff-366f47a7608d.png)
![Screenshot_20200707-115559](https://user-images.githubusercontent.com/42831109/86784365-17685000-c06a-11ea-98e3-b39331d0be67.png)

**Comment by Delphine** [comment]
Arabic is currently at 73% completion for Fenix, so it is expected that some items appear untranslated at this time (threshold for shipping on release is 70% completion): https://pontoon.mozilla.org/ar/android-l10n/tags/

What would be concerning is a locale that appears at 100% completion on Pontoon, but still appears with unlocalized strings on Nightly.
Link to progress on Pontoon for locales on Fenix can be found here: https://pontoon.mozilla.org/projects/android-l10n/tags/fenix/
(Note we also depend on the l10n string imports on mobile-side to get the latest string updates in Nightly)
I'll work on something so we can align on all this going forwards :)
