### ISSUE TITLE
FNX-4599 ⁃ [Bug] Build date appears as "debug build"

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10814]
Report: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4919240856038450270/executions/bs.93fc5aef8dc94972/testcases/2/test-cases
`java.time.format.DateTimeParseException: Text 'debug build' could not be parsed at index 0
at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
at java.time.LocalDateTime.parse(LocalDateTime.java:486)
at org.mozilla.fenix.ui.robots.BuildDateAssertion$Companion.getLocalDateTimeFromString(SettingsSubMenuAboutRobot.kt:282)
at org.mozilla.fenix.ui.robots.BuildDateAssertion$Companion.verifyDateIsWithinRange(SettingsSubMenuAboutRobot.kt:236)`

**Comment by sv-ohorvath** [comment]
The build date is not displayed in this case, but a "debug build" label. Maybe this is expected in some cases? 
![2020-05-25_17-48-22](https://user-images.githubusercontent.com/4037709/82823368-19a68e80-9eb0-11ea-8914-1a45eceece2f.png)

**Comment by Mugurell** [comment]
Are there any more of these reports?
Or it seems like a one-off thing?

**Comment by sv-ohorvath** [comment]
@Mugurell the last one I've found is on this PR: https://github.com/mozilla-mobile/fenix/pull/10812/checks?check_run_id=703096186

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4776597090949444122/executions/bs.6a29452a3ce7176f/test-cases

**Comment by Mugurell** [comment]
Thanks Oana!
Great find above ^^!
Seems like these tests proved their importance and caught a small issue to be introduced by https://github.com/mozilla-mobile/fenix/pull/10812

Tagging @grigoryk

**Comment by grigoryk** [comment]
Thanks, @Mugurell . I'm a little confused - #10812 did not land yet. Which test run is https://github.com/mozilla-mobile/fenix/issues/10814#issue-622346869 taken from, @sv-ohorvath ?

I switched date to a hard-coded `debug build` only for debug builds; any other builds (e.g. those that we publish on Play Store) will have a real date.

**Comment by grigoryk** [comment]
Currently in the tree I don't see tests that verify presence of the build date - e.g. nothing failed in #10812 CI run (other than a bookmark intermittent).

There's this: https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt#L78 which ends up running https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt#L355-L359 but that doesn't look at the build date, either.

I must be missing something, since the only explanation I can see is that someone rebased their work of adding more UI tests on top a in-flight PR (#10812), and this was the result.

As-is, this doesn't seem actionable to me?

**Comment by ekager** [comment]
This looks at the build date and is the robot that `SettingsAboutTest` actually uses. https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt#L59

**Comment by grigoryk** [comment]
Ah, thanks @ekager ! I missed that. I don't see that particular failure in #10812 , I'm assuming that UI tests aren't running debug builds, and so this shouldn't be a problem?

**Comment by grigoryk** [comment]
#10812 landed with the test adjusted to account for `debug build` string. I filed #10914 to see if we want to switch UI tests to use non-debug builds.
