### ISSUE TITLE
FNX-4664 ⁃ feature request

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10890]
### What is the user problem or growth opportunity you want to see solved? 
Adding the features will increase customers and compete with other well established browsers.

### How do you know that this problem exists today? Why is this important? 
Enable the browser to be more friendly and usable

### Who will benefit from it?
All users

I request below features to be added.

1. Pull down to refresh.
1. Auto password generator similar to desktop version
1. More security info about the site such as certificate expiry date , cipher suite details.
1. Save as PDF the webpage
1. Customize the 3 dot menu in a horizontal grid layout similar to yandex browser to accomodate more items in an elegant way
1. Add option to change webview. I don't like your gecko webview because for app based url it never opens the url in the app when viewed in webview unlike chrome webview which immediately open the link in respective app on clicking it inside the webview page.

**Comment by cadeyrn** [comment]
Hi,

there should be one issue per feature request. Otherwise it's not possible for the developers to label the issues. If they want to implement one feature request but not another one, how should the labels be used? And the title of each issue should describe the feature request - "feature request" is not an appropriate title because, well, every feature request is a "feature request". How should people distinguish the feature requests in the issues list if all feature requests are named as "feature request"? And please use the search feature because there are already issues for most of your feature requets.

Thanks!

**Comment by kglazko** [comment]
Thank you for your feature request. There are already issues for the following:
Pull-to-refresh: https://github.com/mozilla-mobile/fenix/issues/3262
Auto-password generator: https://github.com/mozilla-mobile/fenix/issues/5661
Save to PDF: https://github.com/mozilla-mobile/fenix/issues/3709
View site certificate: https://github.com/mozilla-mobile/fenix/issues/8400

Sometimes features can take time to complete as we receive many new issues every day and have to prioritize as a small team. We appreciate your feedback and patience though as we work through them to make Fenix a better browser.

Please feel free to file the remaining issues separately, as mentioned by @cadeyrn above and I will triage them as they come in. I will close this issue, because as mentioned above, we prefer to have each issue represent a specific feature request or bug. I encourage you to add screenshots for the 3-dot one or a more detailed description as well. Closing this issue doesn't mean that it will fall off our radar- feel free to continue the discussion here if you have any questions or need help filing the remaining issues separately.

**Comment by sheikh-azharuddin** [comment]
Thanks I have already raised separate case for each issues. however I am not satisfied with the password generator feature...no update since Oct 2019. Also regarding the security info of the site I want to see the cipher suite used somewhat like TLs1.2_ecdhe_aes_256_gmc_sha256... like we see in desktop version about clicking about info...on clicking the lock icon in fenix it shows the url name also which is redundant since we have it in the address bar so I would suggest remove it and add cipher suite details one line ....elegant
