### ISSUE TITLE
Fennec migration: "Add to Home Screen" is displayed for pages already added to home screen

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#10948]
## Preconditions:
On Fennec add to home screen twitter.com.

## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta;
1. Launch Fenix and go to twitter.com;
1. Observe the behavior;
    1. Expected behavior
The twitter.com is displayed.
    1. Actual behavior
The "Add to Home Screen" pop-up is displayed. 
    1. Notes:
[Video](https://drive.google.com/open?id=1v7SsT5EvqtAUWtUf0k1Y5LLDJtokffRm)
The is not reproducible for olx.ro.
    1. Device information

* Android device: Nexus 5 (Android 6.0.1); Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7).
* Fenix version: Beta migration build 76.0.0-beta.1 from 5/1.

**Comment by Mugurell** [comment]
Thanks TitanNano!
This is why I moved this to Fenix.
We cannot have a 100% solution so maybe this would not warrant the high effort needed to support this through migration.
But with the above API we would still resolve the issue for ~half of the userbase, so I think that's good enough to warrant a smaller patch on Fenix.

**Comment by Mugurell** [comment]
Copying to here the commit message to make it easier for the new behavior to be tracked:

It is possible that after migration users would already have Firefox PWAs on
their screen.
Since they already know about this functionality, we should not promote it to
them with the one-off FirstTimePwaFragment.

To query installed PWAs we'll use an API available only on Android >= 26 which
means that we will probably have half of users with PWAs still see the
onboarding but half which will not.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration build 5.1.0-beta.2 with Motorola Moto G6 (Android 8).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly Migration Build 2015743089 from 5/29 with Motorola Moto G6 (Android 8). "Add to Home Screen" is not displayed for the pages that are already added on the home screen.

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Beta Migration Build 5.1.0-beta.3 with Motorola Moto G6 (Android 8), Google Pixel 3XL (Android 9), Huawei MediaPad M3 lite (Android 7).

**Comment by Mugurell** [comment]
Closing this since the migration completed.
