### ISSUE TITLE
FNX-7649 ⁃ [Bug] Performance: 100ms App Link delay before GeckoView is asked to open a tab

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#10942]
Steps to reproduce:

1. Launch Fenix Nightly and go to google.com (or anything that's not mozilla.org).
1. Leave Fenix and go to the Android home screen.
1. Trigger an app link intent by executing the following on a connected desktop machine: `adb shell am start-activity -d "https://www.mozilla.org/en-US/" -a android.intent.action.VIEW org.mozilla.fenix.nightly/org.mozilla.fenix.IntentReceiverActivity`

Profile: https://share.firefox.dev/3er0ytd

You can see that there is a 100ms delay between activity starting on the Java UI thread and activity starting on the Gecko Parent Process thread.
More specifically, `android.app.ActivityThread.handleLaunchActivity` is called 100ms before `GeckoViewSupport::Open` is called.

This is on a Moto G5, as usual.

**Comment by mstange** [comment]
I filed [bug 1641129](https://bugzilla.mozilla.org/show_bug.cgi?id=1641129) on the additional 150ms delay seen on the Gecko side.

**Comment by mcomella** [comment]
If you wanted to determine the source of the issue, you could try to reproduce in Reference Browser.

I wonder if the creation of IntentReceiverActivity and redirection to `MainActivity` is partially introducing this overhead.

**Comment by rocketsroger** [comment]
Debugging from Java level, there is no one operation that is particularly longer than others.  More than half of the delay was waking up IntentReceiverActivity and starting the BrowserActivity.

**Comment by rocketsroger** [comment]
Don't see any operations that we an optimize here.  Closing.

**Comment by rocketsroger** [comment]
One thing that stands out is that your profile is different from mine:
https://share.firefox.dev/2Y2h0K8

The difference is that on your profile I can see that `HomeActivity.onNewIntent()` is called before `IntentReceiverActivity` starts to handle the intent.  On my profile, the intent went straight two `IntentReceiverActivity`.  I suspect that this is how older Android OS handles an intent sent to the app.  The time difference here was 50 ms.  (Nothing we can do here)

Other than the difference.  Most of the operations are around 5 ms and the rest are just Android OS operations.  I've looked though each operation and there are none that we can remove without removing features.

Unfortunately, I couldn't find anything big enough that we can act on to improve performance.

**Comment by mcomella** [comment]
@rocketsroger Is it possible to move these operations to happen after Gecko starts to load the page instead?

For context, I would like to remove `IntentReceiverActivity` after launch, when it's a less risky change because it has a non-trivial impact on startup: https://github.com/mozilla-mobile/fenix/issues/7927

**Comment by rocketsroger** [comment]
> For context, I would like to remove `IntentReceiverActivity` after launch, when it's a less risky change because it has a non-trivial impact on startup: #7927

Unfortunately removing `IntentReceiverActivity` is more of a architecture question.  If we use other activity to handle intent filter in Android Manifest it can cause other issues.  If `IntentReceiverActivity` is removed we might save maybe 5 ms since the operations that we perform in `IntentReceiverActivity` will still have to be performed.  Only thing we'll be saving is the extra `startActivity()` call.

**Comment by mcomella** [comment]
> If `IntentReceiverActivity` is removed we might save maybe 5 ms since the operations that we perform in `IntentReceiverActivity` will still have to be performed. Only thing we'll be saving is the extra `startActivity()` call.

@rocketsroger I think it's more than that. In this profile, I see at least:
- ActivityThread.handleLaunchActivity – 25ms (before our code)
- Activity.startActivity + Activity.finsh - 10ms (inside processIntent)
- ActivityThread.handlePauseActivity – 33ms

For a total of 68ms. This isn't an entirely accurate indicator of the impact of IntentReceiverActivity but I'm confident the activity redirection is having a non-trivial impact on startup speed. For example, the `MigrationDecisionActivity`, without needing to migrate, adds 120ms to startup times and I don't think all of that is checking if we're migrated. We could probably throw together a proof-of-concept that removes IntentReceiverActivity and measure the impact.

In fact, it seems like most of the 100ms delay could actually be directly attributed to IntentReceiverActivity. I don't suppose it's possible to remove this before shipping, right?

**Comment by rocketsroger** [comment]
> In fact, it seems like most of the 100ms delay could actually be directly attributed to IntentReceiverActivity (disclaimer: I only looked briefly). I don't suppose it's possible to remove this before shipping, right?

@mcomella You are correct that the cost is much higher on Motorola G5.  I should have been more clear.  When I say 5 ms, I meant with my profile with a faster device.

I thought about removing `IntentReceiverActivity` as a solution during the investigation.  By architecture decision what I meant is that to remove the delay from `IntentReceiverActivity` completely we will have to know before hand which activity we need to start.  If you take a look at `IntentProcessorType`, there are currently 3 possible activity (`ExternalAppBrowserActivity`, `HomeActivity` and `MigrationProgressActivity`) that can be launched.  This is a design decision to start a low cost activity to handle incoming intent rather than starting an activity with UI elements.

Unfortunately, removing `IntentReceiverActivity` might save us time on some device + use case combination.  But overall it will create more architecture issues with not a lot of gain.

**Comment by mcomella** [comment]
> Unfortunately, removing IntentReceiverActivity might save us time on some device + use case combination. But overall it will create more architecture issues with not a lot of gain.

@rocketsroger I disagree that this is low impact – the Moto G5 was selected to be a reference device because it's a roughly average low-end device used by our users. The average high-end device is a Pixel 2. We expect both of these devices to be performant because they represent our users. Given the performance improvements the perf team has been making are frequently 10ms (on the Moto G5), a 100ms improvement is huge.

As far as architecture issues, I think we can build our own abstractions that function as well as Activities for encapsulation. Perhaps replacing it in the next two weeks is unrealistic but I think it's feasible in a longer time.

Caveat: the Moto G5 and Pixel 2 are the reference devices from two years ago and we're in the process of refreshing them this year. That being said, the suspected low-end device, the Galaxy S7, appears to have similar performance issues with activity redirection, looking at the startup dashboards implications for the migration check time. Unfortunately, I don't have one so I can't test on it. If we found it wasn't an issue on this device, we can probably deprioritize this. For context on our users and which devices we should doing performance testing on, the Pixel 2 is still an above average device for our users despite being nearly 3 years old.

**Comment by rocketsroger** [comment]
@mcomella I understand your your suggestion.  However, I am still concerned that replacing `IntentReceiverActivity` with `HomeActivity` will cause other issues since not all intents are meant for `HomeActivity`.

@mstange unfortunately I don't have a Motorola G5 with me.  Can you please help try something for me?  Can you please profile this use case on the second time you send the intent to `IntentReceiverActivity`?  I see a long delay to start and pause `IntentReceiverActivity`.  I think it's because it was a cold start for the activity.

**Comment by mcomella** [comment]
> @mcomella I understand your your suggestion. However, I am still concerned that replacing `IntentReceiverActivity` with `HomeActivity` will cause other issues since not all intents are meant for `HomeActivity`.

As far as I can tell, the only two Activities that need to be highly performant are `HomeActivity` and `ExternalAppBrowserActivity`. My assumption has been that we'd move our intent processing logic directly into the most used one and it would do the redirecting so that we don't have the performance cost of redirecting to our most used, necessarily-performant activities. If possible, we should also consider merging `HomeActivity` and `ExternalAppBrowserActivity` so both use cases are performant.

What Intent issues are you concerned about? Another assumption I have is that, functionally, we would be able to recreate identical user behavior with this new implementation even if the encapsulation is different and possibly worse.

> @mstange unfortunately I don't have a Motorola G5 with me. Can you please help try something for me? Can you please profile this use case on the second time you send the intent to `IntentReceiverActivity`? I see a long delay to start and pause `IntentReceiverActivity`. I think it's because it was a cold start for the activity.

I believe this is a cold start for `IntentReceiverActivity` but not for the process:
- the STR implies the app is already running
- the profile calls `onStop` around 3s ([link](https://profiler.firefox.com/public/c44e16acdcb11152f6099eda7b7907dec4c8c191/stack-chart/?globalTrackOrder=2-3-0-1&hiddenGlobalTracks=2&hiddenLocalTracksByPid=22473-0-4-5-6~22575-0-2-3&localTrackOrderByPid=22473-2-3-4-0-1-5-6~22575-1-2-0-3~&thread=3&v=4)) but the shared profile with IntentReceiverActivity happens at 5s

The `IntentReceiverActivity` will always be cold started though because it's `finish`ed before launching the next activity.

**Comment by rocketsroger** [comment]
> What Intent issues are you concerned about? Another assumption I have is that, functionally, we would be able to recreate identical user behavior with this new implementation even if the encapsulation is different and possibly worse.

Ah, yes we were basically arguing for the same thing.  Unless we merge the activities together we can't eliminate the delay.  My main concern that this is a trade between performance vs design/maintainability.  I agree this is something that we should discuss.  I will open a feature request issue to track it.

> The IntentReceiverActivity will always be cold started though because it's finished before launching the next activity.

It does look like on my profile it's a resume and pause.  `IntentReceiverActivity` was not destroyed.  I was just hoping we have more data point on Motorola G5 on the second intent use case.

**Comment by mcomella** [comment]
@rocketsroger Thanks – I'm glad to hear we're on the same page. :)

If we remove `IntentReceiverActivity`, is it possible that users will lose their homescreen shortcuts? If so, we may want to do this very, very soon. If not, this can wait though 100ms is a big win so I'd like to have it sooner rather than later 😅

**Comment by rocketsroger** [comment]
> If we remove `IntentReceiverActivity`, is it possible that users will lose their homescreen shortcuts? If so, we may want to do this very, very soon. If not, this can wait though 100ms is a big win so I'd like to have it sooner rather than later 😅

I think this will require some serious discussions before moving forward.  If the decision is to eliminate `IntentReceiverActivity`, the change will not be a small one and there will be some risks involved as well.
