### ISSUE TITLE
FNX2-13304 ⁃ add ons required

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10943]
Can you please add below 2 important add-ons related to privacy and security?

Decentraleyes
ClearURLs

**Comment by SS1113** [comment]
Support for [Nano Adblocker](https://addons.mozilla.org/en-US/firefox/addon/nano-adblocker-firefox/) as well please...

**Comment by sheikh-azharuddin** [comment]
> Support for [Nano Adblocker](https://addons.mozilla.org/en-US/firefox/addon/nano-adblocker-firefox/) as well please...

Ublock origin is blocking all ads.. why need an ad blocker?

**Comment by SS1113** [comment]
>Ublock origin is blocking all ads.. why need an ad blocker?

@sheikh-azharuddin It has a very useful feature which lets me report website breakages, websites using which are anti-adbkock, unblocked pop-ups and Ads and other issues that uBlock Origin doens't have. As I come across a lot of websites which have all these issues I mentioned above on a regular basis I need to report them and get them fixed in order to use those websites, uBlock Origin just doesn't make it easy to do those things.

Now I know I can report them [here](https://github.com/uBlockOrigin/uAssets) and [here](https://www.reddit.com/r/uBlockOrigin/) but that's a lot more tedious than just tapping through 2 two or more clicks
 
![Screenshot_20200527_133821](https://user-images.githubusercontent.com/42088907/82994169-40201300-9ff1-11ea-9d2d-29ded332f49c.jpg)
![Screenshot_20200527-133539](https://user-images.githubusercontent.com/42088907/82994328-7b224680-9ff1-11ea-82e5-c934c112c6e6.png)
![Screenshot_20200527-133544](https://user-images.githubusercontent.com/42088907/82994339-807f9100-9ff1-11ea-88f8-5ca9606535ab.png)

**Comment by sheikh-azharuddin** [comment]
I think they should allow all add ons from add on store like desktop😅
Or for now allow only the add ons with recommended tag.

**Comment by cadeyrn** [comment]
> I think they should allow all add ons from add on store like desktop😅
>  Or for now allow only the add ons with recommended tag.

One step at a time. There is a reason why they start with a limited subset. Please see https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/ and https://blog.mozilla.org/addons/2020/04/14/april-extensions-for-firefox-preview/ for more information.

**Comment by SS1113** [comment]
@sheikh-azharuddin Yes, but it requires supporting the required API's which they're currently building. I'm requesting Nano Adblocker because it is built on the uBlock Origin's source code which is already supported so I think supporting it wouldn't be that hard.

**Comment by cadeyrn** [comment]
Nano Adblocker is not a recommended extension so this won't happen in the _near term_ (maybe at a later point, we will see). They still focus on recommended extensions. See the second link above:

> We intend to enable more add-ons from the Recommended Extensions program within the next few months and will be reaching out to developers soon.

**Comment by SS1113** [comment]
@cadeyrn I know all about that, but then the issue #10366 is also not requesting a recommended extension.

**Comment by liuche** [comment]
@Amejia481 is there a place to track add-on requests? Someone is also requesting userscript manager.

**Comment by Amejia481** [comment]
I'm not sure but @kewisch could help us to clarify.

**Comment by sheikh-azharuddin** [comment]
Thanks for adding 3 new add-ons😊
Please add option to notify users about that else how will people know new add ons added

**Comment by SS1113** [comment]
@sheikh-azharuddin it's being considered, follow this: https://github.com/mozilla-mobile/fenix/issues/9010.

**Comment by TheW0LVERIN3** [comment]
I think the honey team would be more than happy to work on adding the extension to the fenix browser. There would be no harm in contacting them

**Comment by TheW0LVERIN3** [comment]
For any developper/user who wants to experiment with fenix add on support. https://github.com/interfect/fenix this fork allows tons of extensions on fenix. Use it at your own risk.

**Comment by sheikh-azharuddin** [comment]
> For any developper/user who wants to experiment with fenix add on support. https://github.com/interfect/fenix this fork allows tons of extensions on fenix. Use it at your own risk.

You mean ice weasel?

**Comment by NotWoods** [comment]
We would like to expand our support to other add-ons but we are not keeping open requests for specific ones. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

**Comment by Jonta** [comment]
> Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

That blog looks much more wordy and broad than what I'm looking for

**Comment by Jonta** [comment]
Less wordy, but still

I'd like a feed that says "Addon X that does Y now available for Firefox Mobile. Click this sentence to check it out"

**Comment by sheikh-azharuddin** [comment]
If the fork version has added too many add ons what's the issue in adding to fenix???
