### ISSUE TITLE
[Bug] Private mode's homescreen is not translated in Spanish on Android 5&6

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10951]
## Steps to reproduce
1. Go to Settings and change the language to Spanish.
1. Go to the private mode and observe the homescreen.

### Expected behavior
The private browsing homescreen is translated in Spanish.

### Actual behavior
The private browsing homescreen is in English.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), OnePlus A3 (Android 6.0.1)
* Fenix version: Beta 5.1.0-beta.2, 5/27 Nightly build
* Not reproducible on Samsung Galaxy Note 8 (Android 9), Google Pixel 4 XL (Android 10), Samsung Galaxy Tab S3 (Android 8)

![spanish](https://user-images.githubusercontent.com/40694158/83027799-3b7f4d00-a039-11ea-89ec-32626807bab3.png)

**Comment by mcarare** [comment]
@softvision-miralobontiu I suppose you have chosen **Español** from the languages list (Without any region). The problem is actually that strings.xml (es) does not have the new string translated. For newer android versions the mechanism of finding the "BestMatch" for a string includes a fallback to that language but for another region, instead of choosing the default (English in this case) translation. This is not something we can straightforwardly fix in code, but it will be fixed as soon as a translation is available for this string.

Having said that, taking a look at the string.xml (es) I see that it is missing almost half of the translations. @Pike do you know how this happens? Translations for es-rAR, es-rCH and even es-rES are more complete. How should we handle this?

**Comment by Pike** [comment]
> Having said that, taking a look at the string.xml (es) I see that it is missing almost half of the translations. @Pike do you know how this happens? Translations for es-rAR, es-rCH and even es-rES are more complete. How should we handle this?

Redirecting this question to @gueroJeff, who's doing the PM work for mobile while D is out.

**Comment by Delphine** [comment]
Picking up the ball now that I'm back.
I don't think we should be testing locales this way. Please refer to my comment here for more info: https://github.com/mozilla-mobile/fenix/issues/11362#issuecomment-665822106

**Comment by softvision-miralobontiu** [comment]
I did not reproduce this anymore on neither of the builds: 1/4 Nightly build, Beta 85.0.0-beta.4 or RC 84.1.2 with Samsung Galaxy Tab A6 (Android 5.1.1).
I'll close this issue.
