### ISSUE TITLE
Add a TaskCluster task/action for draft pull requests

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#10985]
`event.pull_request.draft`

Brought up in an automation call was the idea of utilizing draft PR's as an opportunity for a means to use a separate Flank configuration and job for asynchronously re-running suspected flaky UI tests in with Flank on Firebase. It would be used [ui-test/kind.yml](https://github.com/mozilla-mobile/fenix/blob/master/taskcluster/ci/ui-test/kind.yml)

event actions: opened, re-opened, synhronize

(@CC @rpappalax @JohanLorenzo)

**Comment by JohanLorenzo** [comment]
Hey @AaronMT! 

I see the intent and I understand the need 🙂 Although, I don't think using `draft` is the best way to test a separate configuration. Don't worry, I have an alternative solution 😃 

I have 2 major concerns with drafts: 
 1. It may confuse people who genuinely want to open a draft PR => they will silently use the separate configuration and may not understand why the UI tests are busted. This may prevent them from promoting the draft PR to a ready-to-review one, which could likely fix the original issue. 
 2. Taskgraph needs to deal with draft PRs. That's a new feature to implement. I'm still unsure of the benefits of it, especially because of point 1. 

Alternative solution: use [try_task_config.json](https://github.com/mozilla-mobile/shared-docs/blob/fd8f0560f15d4b6d82e7b3b83aa01bf3c0acc7d9/android/taskcluster_guide.md#how-do-i-run-a-staging-nightlyrelease-on-prs). This file is understood by taskgraph and changes how a PR behaves. In the previous link, a PR generates a nightly graph (instead of a regular PR one). We can definitely create a `flank-async` graph that becomes active only with the right `try_task_config.json`. Thus, point 1 is addressed.

The changes in `ui-test/kind.yml` would be the same as if you added the `draft` support. Good news is: there's no taskgraph changes to make so point 2 is addressed too.

I'm happy to provide more pointers and information. I'd just like to make sure I fully understood your need and my proposal suits it 🙂 Let me know what you think!
