### ISSUE TITLE
FNX-11846 ⁃ [Bug] TabTrayView memory leak

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#10989]
## Steps to reproduce
1. Have Tabs Tray enabled
1. Click in and out of tabs tray while browsing

![Screenshot](https://user-images.githubusercontent.com/25442310/83164957-bb50fa00-a0c1-11ea-9a6e-9cd2970ee43e.png)UNITO-UNDERSCORE!20200528-115822!

### Device information
* Android device: ?
* Fenix version: ?

**Comment by ebarrenechea** [comment]
@boek I was playing around with the new tab tray feature and it seems this is still an issue (latest from master). I had a look at it and I think it's because the coroutine to collect the flow in `TabsTrayPresenter` is not being reset after the `TabTrayDialogFragment` is destroyed. 

I had a look at the code and the `TabsFeature` already extends `LifecycleAwareFeature` which should take care of stopping the coroutine based on lifecycle events. The missing piece seems to be registering the feature with the dialog fragment's lifecycle. Passing the lifecycle to the `TabsTrayView` constructor and having the view register on `init` works but I don't know if that's the correct pattern to apply in this codebase (maybe there's a component that handles that registration for the view).

I can put up a PR with my changes which seem to address the leak if you'd like but I don't know how useful it would be if there is a different approach to observing lifecycle events from features.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Fenix debug build from Master`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Screenshot
![rsz_screenshot_20200609-144307](https://user-images.githubusercontent.com/51314259/84144265-a7fa4300-aa60-11ea-8c62-94c1a6e513d8.png)
