### ISSUE TITLE
FNX-11854 ⁃ bug Remove scrolling from home

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#10997]
Sometimes when you go back to home it's in a scrolled state where you don't see the logo. Now that we got rid of open tabs we can always render from top.

**Comment by liuche** [comment]
Will be part of homescreen improvements.

**Comment by boek** [comment]
This has been fixed with another PR

**Comment by AndiAJ** [comment]
Hi, I've just checked this on the latest **`Nightly Build 200624 from 6/24`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

Doesn't seem to be working if you **switch to PB and tap the Private tab FAB (and vice-versa)**
► Video
![20200624-110216](https://user-images.githubusercontent.com/51314259/85519917-e4a26e80-b60a-11ea-8808-f20f2d38baa8.gif)

Is this **applicable only for the Tabs Tray interactions?**
I'm asking because if you create a collection, exit the Settings, History, Bookmarks etc the Home screen is in a scrolled state 

► Video
![20200624-105217](https://user-images.githubusercontent.com/51314259/85520173-3945e980-b60b-11ea-8050-5c7dbd71a0d5.gif)


@boek & @topotropic - Please review and advise. ☺️

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/28 with Google Pixel (Android 11) and LG G7 FIT (Android 8).
Note that the screen is still scrollable when no collections are added, but the logo is displayed.
