### ISSUE TITLE
Security lock icon customisation

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11046]
### What is the user problem or growth opportunity you want to see solved?
The security lock icon in the address bar is black in white theme and vice versa.. please change this icon color to green for secure websites and red for insecure website.

### How do you know that this problem exists today? Why is this important?
This will help to easily distinguish the secure website from insecure. From school days we were taught green for secure and red for danger and our brains have adapted to it and also color items catch the eyes more easily 

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1405)

**Comment by cadeyrn** [comment]
> please change this icon color to green for secure websites 

The green color was intentionally removed from Desktop Firefox a few months ago so it doesn't make sense to go the opposite way in Android Firefox.

According to Let's Encrypt ~85 percent of all page loads are via HTTPS. That's a very good reason **not** to highlight the default and secure state. Especially if you want to highlight the insecure state the default state should not be highlighted.

**Comment by sheikh-azharuddin** [comment]
> > please change this icon color to green for secure websites
> 
> The green color was intentionally removed from Desktop Firefox a few months ago so it doesn't make sense to go the opposite way in Android Firefox.
> 
> According to Let's Encrypt ~85 percent of all page loads are via HTTPS. That's a very good reason **not** to highlight the default and secure state. Especially if you want to highlight the insecure state the default state should not be highlighted.
> 
> Edit: It's a duplicate of #5924.

But in desktop version there is one preference item to change the gray color lock icon to green...in android version there is no such preference...I tried to add but not working... the preference item is

security.secure_connection_icon_color_gray

Forget what let's encrypt says let's have a vote what users actually wants... Moreover I don't see any harm by having the lock icon change to green color... Green for security red for danger makes more sense... 

Or please add the preference item in android version

**Comment by cadeyrn** [comment]
> Forget what let's encrypt says

No? **Data are important for decision making**, especially when it comes to security indicators. It's a completely different story whether we are talking about 10 or 85 percent encrypted traffic. With only 10 percent it makes sense to highlight the secure state because it's something special and there is an argument for highlighting the padlock in this case. But if already 85 percent are encrypted (trending upwards!) it doesn't make sense at all to highlight the padlock for HTTPS because it's the default case. 

Please read https://blog.mozilla.org/security/2019/10/15/improved-security-and-privacy-indicators-in-firefox-70/ for more context.

By the way, platform consistency is another strong argument. As I already said: Mozilla already made a decision for the Desktop Firefox. How would you explain to users why there was made a decision for Desktop but the opposite for Android?

I would be okay with a red line for the unencrypted padlock to be consistent with the Desktop but I am strongly against a completly red padlock and even more against a greed padlock.

But, as I also already said, your ticket is a duplicate of #5924. There is no need to discuss the same topic on two places.

**Comment by sheikh-azharuddin** [comment]
> > Forget what let's encrypt says
> 
> No? **Data are important for decision making**, especially when it comes to security indicators. It's a completely different story whether we are talking about 10 or 85 percent encrypted traffic. With only 10 percent it makes sense to highlight the secure state because it's something special and there is an argument for highlighting the padlock in this case. But if already 85 percent are encrypted (trending upwards!) it doesn't make sense at all to highlight the padlock for HTTPS because it's the default case.
> 
> Please read https://blog.mozilla.org/security/2019/10/15/improved-security-and-privacy-indicators-in-firefox-70/ for more context.
> 
> By the way, platform consistency is another strong argument. As I already said: Mozilla already made a decision for the Desktop Firefox. How would you explain to users why there was made a decision for Desktop but the opposite for Android?
> 
> I would be okay with a red strikethrough for the unencrypted padlock to be consistent with the Desktop but I am strongly against a completely red padlock and even more against a greed padlock.
> 
> But, as I also already said, your ticket is a duplicate of #5924. There is no need to discuss the same topic on two places.

Add the preference item then to android...here let user decide...
security.secure_connection_icon_color_gray

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
