### ISSUE TITLE
SPIKE: [Bug] Ensure that web prompts aren't above the Tabs Tray

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11043]
Similar to #11040, which is for Fenix chrome notifications, we should make sure that web content prompts (like "share microphone" or "allow notifications from this site") aren't showing up over the tabs tray.

**Comment by darkwing** [comment]
`alert()` calls also appear above tab tray:

https://industrious-muscari.glitch.me/

**Comment by darkwing** [comment]
I think this is a larger issue than just tab tray.  For example, if I tap the three-dot menu on the bottom right of the browser to view settings, the `alert()` displays over that menu as well.

**Comment by boek** [comment]
FWIW this is also the behavior in Fennec. Should we move this into the backlog @darkwing?

**Comment by jonalmeida** [comment]
Updated the ticket to clarify that this ticket is for alerts and prompts and not [WebNotifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API).

**Comment by sblatz** [comment]
Is this something we want to prioritize given that it's the behavior in Fennec as well @vesta0? 

This sounds like it may require quite a lot of effort.

**Comment by ekager** [comment]
Was this a UX ask or just a followup to #11040 ?

I think there's an argument to be had that while you're on the browser fragment with the tab tray open above a tab that you can still see, you may want to get alerts for the current page you're on? 

Considering that this is also the behavior Fennec has I'm wondering if there was a discussion sometime in Fennec history about this as well. 

Eng wise if we'd want to change this: 

We can't control the order of newly added dialog fragments AFAIK - ie you couldn't add a new dialog fragment (prompts received from a site are added as dialog fragments) beneath the tabs tray but above the browser fragment. 

We probably also would not want to just not show prompts as they come if the browser isn't focused, because a user could close the tabs tray and have missed an important prompt for their currently selected tab.

Possibly we could work in AC to implement some sort of "pending" prompt that only show once the engine has focus again and clear out when the session or site changes. 

I would suggest backburnering this unless it's a high priority product or UX ask.

**Comment by topotropic** [comment]
@betsymi paging you in here since you looked at banners and dialogs lately. 

Considering engineering effort and UX implications, I'd vote to keep it on top to avoid missing an important prompt as pointed out by Emily.
