### ISSUE TITLE
[Bug] Saved login fills but website becomes unresponsive

### ISSUE THREAD

**Issue by AlwyNjOshy** [mozilla-mobile/fenix#11079]
## Steps to reproduce - https://login.ual.com/oamsso-bin/login.pl?contextType=external
Login there and try to put saved password. saved password input wont works. Shows password were inserted but website non responsive. Try to login but no response 

### Device information Galaxy Tab S4
* Android device: 9
* Fenix version: 75.beta 6

**Comment by sflorean** [comment]
Tested with Samsung Galaxy Note 10 (Android 10) on Nightly 6/15 and here are my findings:
- If the password is copied and pasted, the site is not responding. (same results are on Chrome).
- If the password is typed from the keyboard, the site is usable. 
@ekager I think this is a site issue, not a browser issue, due to the fact that the same results have been observed on Chrome.

**Comment by AlwyNjOshy** [comment]
I was not copying any password. It happens when try to use the saved password on the browser. It works with chrome not in firefox. 
![6374](https://user-images.githubusercontent.com/20915475/85083538-abe04080-b197-11ea-9eea-907958858d69.png)

**Comment by ekager** [comment]
@AlwyNjOshy are you still experiencing this issue?

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664863
