### ISSUE TITLE
FNX-11949 ⁃ [Bug] What's new page said Firefox 5.0

### ISSUE THREAD

**Issue by J-Siu** [mozilla-mobile/fenix#11086]
## Steps to reproduce
Settings ~~> About Firefox Nightly~~ > What's new in Firefox Nightly

### Expected behavior
Should show the current nightly version

### Actual behavior
Show Firefox 5.0 ...

### Device information
* Android device: oneplue 6t
* Fenix version: 200530 06:01

**Comment by cadeyrn** [comment]
The What's new page only highlights major releases. This was already the case with every updae before. So it's not a bug but the expected behaviour.

**Comment by J-Siu** [comment]
Where can I see version 5 inside the app?

**Comment by LittleAngelwings** [comment]
On that page you called. There's the version named. But which version you mean? The 5.0... you had written is not a Nightly version. The version you named 200530 is a nightly version. The description "what's new" is only for the (mayor) releases. The nightlies version don't called 5.0 or higher/lower.They have only the daily number-code like 200530 (year-month-day)

**Comment by J-Siu** [comment]
This is so confusing @.@

Shouldn't the major release be >76 now?

**Comment by cadeyrn** [comment]
> Shouldn't the major release be >76.x.x now?

Firefox Beta has the version number 75, there will be version 76 soon.
The stable release of Firefox Preview has the version number 5.0, there will be version 5.1 soon.

As LittleAngelwings said: There is no "What's new" page for Nightly builds, only for stable releases of Firefox Preview. That's why the link shows the highlights of Firefox Preview 5.0

**Comment by J-Siu** [comment]
Oh, 5.0 is for the non-nightly preview. Got it. Thanks for the explanation.
