### ISSUE TITLE
FNX-11964 ⁃ [Bug] Navigation buttons are almost invisible with new tab tray and private mode

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11099]
## Steps to reproduce
1. enable new tab tray in secret settings
1. Set white theme in settings
1. Go to private mode (click on the button at the top left, don't just click on the icon in the tabs drawer)
    1. Expected behavior
I can see the navigation buttons
    1. Actual behavior
It's white on white:
![](https://user-images.githubusercontent.com/58657617/83351850-d92f9080-a347-11ea-9273-7e6aa211071a.png)
there is no problem with normal mode and dark theme 
![](https://user-images.githubusercontent.com/58657617/83351864-ec426080-a347-11ea-9948-1b0ecaa50280.png)
or normal mode + white theme
    1. Device information

* Android device: Android 9: Pocophone F1, /e/ 0.9 (fork of LineageOS 16.0), no google services but microG. 
* Fenix version: Nightly 200531 06:00. Still reproducible with Nightly 200622 06:01.

**Comment by cadeyrn** [comment]
> Android device: 9

Maybe you should provide more information about your device such the vendor and model name. I can't confirm this issue on the OnePlus 7T Pro with Android 10.

**Comment by SS1113** [comment]
This is how it looks on my device, Motorola One Power, Android 10. Definitely the button are being shaded. 
![Screenshot_20200531-182654](https://user-images.githubusercontent.com/42088907/83352948-a8972900-a33e-11ea-9bc7-7d3edc80de9a.png)

**Comment by cadeyrn** [comment]
@SS1113 It seems that your builds does not yet contain #11010 ("Add white/dark BG for Android bottom bar (currently it has opacity)").

**Comment by SS1113** [comment]
@cadeyrn The issue is now not reproducible in normal mode after the latest Nightly however the buttons are shaded in white in Private browsing mode.

Device: Motorola One Power, Android 10.
Fenix: Nightly 200601 06:00.

**Comment by cadeyrn** [comment]
Screenshot from OnePlus 7T Pro McLaren with Android 10:

![Screenshot_20200601-101020](https://user-images.githubusercontent.com/1100614/83389292-43037500-a3f0-11ea-8e08-eadec3f645ab.jpg)

So it seems device specific and not Android specific since we both use Android 10.

**Comment by SS1113** [comment]
@cadeyrn Yeah, that seems to be the case since I'm not able to reproduce this on Realme C3, Android 10.

**Comment by yoasif** [comment]
Also seeing this on Pixel 2 (Android 10).

![signal-attachment-2020-06-04-152653](https://user-images.githubusercontent.com/152493/83805246-86bede80-a67d-11ea-9371-3e732b5a24e7.png)

**Comment by Diana-Rus** [comment]
Hi, reproducible with Sony Xperia Z5 (Android 7) and Samsung Galaxy S9 (Android 8) with Light theme, Nightly 6/22.
With Google Pixel 3 XL (Android 9) the device button's are visible.

**Comment by B0pol** [comment]
> > Android device: 9
> 
> Maybe you should provide more information about your device such the vendor and model name because it doesn't seem to affect all devices. I can't confirm this issue on the OnePlus 7T Pro with Android 10.

Pocophone F1, /e/ 0.9 (fork of LineageOS 16.0), no gapps but microG.

**Comment by cadeyrn** [comment]
Do we already know the cause of this issue?

In the Firefox support another user reported this issue. He has a Honor 7 with Android 6.

**Comment by SS1113** [comment]
Still reproducing on **`Nightly 200704 18:05`** in Private Browsing Mode.
Device: **Motorola One Power, Android 10**.

**Comment by Diana-Rus** [comment]
Hi, issue is fixed, now the android navigation bar has visible buttons for user with the devices on which i encountered them: Sony Xperia Z5 (Android 7) and Samsung Galaxy S9 (Android 8) which have had problems before with the navigation bar when tabs tray was opened.

<details closed><summary>Sony Xperia Z5 - GIF- Nav bar - Tabs tray - Dark mode,Light mode and Private mode</summary>

![20200716-125220](https://user-images.githubusercontent.com/49859863/87657679-cfc97e80-c763-11ea-93a4-dda0936a9f99.gif)
</details>
<details closed><summary>Samsung Galaxy S9 - GIF- Nav bar - Tabs tray -Dark mode,Light mode and Private mode</summary>

![20200716-125526](https://user-images.githubusercontent.com/49859863/87658011-48303f80-c764-11ea-8cf9-0e236718e662.gif)
</details>

Note: 
- Even though the issue is fixed it seems that the navigation bar color is inconsistent on different devices/OS, when light mode is used, in both normal mode and private mode, can be seen in the added GIF's
