### ISSUE TITLE
FNX-12043 ⁃ [Bug] The "beta" tag is missing in the homescreen icon in the latest beta version 77.0.0-beta.1

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11165]
## Steps to reproduce
The beta tag is missing in the homescreen icon in the latest beta version `77.0.0-beta.1`. This makes it harder to distinguish between the [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox) (Fennec) and the [Firefox Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) (Fenix)

### Expected behavior
Beta tag should be available

### Actual behavior
Beta tag isn't available

### Device information
* Android device: Motorola One Power, Android 10.
* Fenix version: 77.0.0-beta.1

**Comment by liuche** [comment]
We're running an experiment, so for now, we're removing the "beta" tag for this channel. Thank you for reporting!

**Comment by Madis0** [comment]
Why not just push the Fenix as stable for real? Even with a staged rollout, it would be much less deceptive than this.

**Comment by filips123** [comment]
Because Fenix still doesn't support all features from stable Firefox and has come bugs.

**Comment by Madis0** [comment]
Then it shouldn't be advertised as such...

**Comment by DanHakimi** [comment]
Didn't you guys learn your lesson about experimenting on your users?

If the experiment is false advertising, I've got news for you: it's still immoral.

**Comment by yump** [comment]
Lying about which release channel is being installed is especially egregious because a user's tabs are not portable between release channels. I installed Beta years ago back when Fenec's performance was rapidly improving, but I am currently locked in to Fenix by my open tabs, even though it has yet to reach feature parity (1/5 add-ons working) or functional parity (extremely aggressive unloading and loss of form contents under memory pressure) with Fennec.

In my case it's entirely my own damn fault, but users should not be put in this situation.
