### ISSUE TITLE
FNX-12119 ⁃ [Private Browsing] Change default PBM setting to disable screenshots

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#11230]
Steps to reproduce:

Open a new tab in private browsing
Go to open apps view

Expected:
Private mode contents is hidden (for private homescreen and websites)

Actual:
Private mode contents is shown.

Rational: The idea of private browsing is that we keep your what you're looking at private except when you're actively using Private mode. Showing the contents of private browsing outside of the app (ie. open apps view) violates that. 

Secondly: We should have the default set to disabled for "allow screenshots in private browsing" in private browsing settings since this is linked to the ability to hide private mode screen in the open apps view.

![image](https://user-images.githubusercontent.com/5992746/83778817-33d33000-a659-11ea-81e7-cc24b9d73a3d.png)

**Comment by mcarare** [comment]
@AmyYLee Is this same as : https://github.com/mozilla-mobile/fenix/issues/11153 + the default setting for allowing screenshots?

**Comment by AmyYLee** [comment]
@mcarare Yes it is. I was told I should open a new issue for the default toggle change.

**Comment by mcarare** [comment]
@Amy Lee, as a note, I've submitted a fix for the first part (hiding preview in private), but it does not depend on the default setting for allowing screenshots.

**Comment by ekager** [comment]
Separated out the two issues so that #11153 is tracking always hiding in the app viewer, and this can track changing the default screenshot setting to not allowed

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200609 from 6/9`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200609-155335](https://user-images.githubusercontent.com/51314259/84150600-c2391e80-aa6a-11ea-8e6d-d793ce0a64c3.gif)

**Comment by Mugurell** [comment]
Looked a bit at this, it seems like it is not possible anymore to override the thumbnail shown in the Recents Screen.
https://stackoverflow.com/a/49340273/4249825

In the scenario that screenshots are allowed but we want to hide the UI in the Recents Screen
We'd need to know when the app thumbnail is put in the Recent Screen.
And Android doesn't seem to offer such an API anymore.

Trying to hide the UI in `onPause` will actually race with Android taking the screenshot to display in Recents, that's why it may be possible that on some devices this might work but on others not.
Tried to use `onWindowFocusChanged` which is called before onPause but even with that I'd only get 50-50 chances of the UI being blocked or not.
I don't think we can rest on this kind of non-deterministic behavior.

Possible areas of further investigations: 
- find the framework call for Recents thumbnail
- find a sure way to detect the Recents button
Even the above I don't think will bring 100% confidence based on the current Android fragmentation.

Users have a reliable way of hiding the UI in Recents - just have the "Allow screenshots in private browsing" toggled off.
Otherwise, if screenshots are allowed the user can easily tap once on the thumbnail and make a screenshot in the app.

So with the added benefit being so small and with Android not easily supporting this I would propose skipping this feature.
