### ISSUE TITLE
[webcontent] Text selection is buggy, especially for sites with custom text editors

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#11301]
Sorry if I explain this badly, my technological volcab is basically non-existent.

### Site with issue and any steps to reproduce
Sites which this affects: github.com (when creating this issue!) crypt.ee/docs (Cryptee has a text editor but its unusable due to the way Firefox selects text), reddit.com (when commenting), and others. Seems to be any site which allows custom text formatting.

Examples:
![SM-G955F](https://user-images.githubusercontent.com/63871973/83947758-eac5dc00-a810-11ea-8118-11356e20af8f.gif)UNITO-UNDERSCORE!20200606-161225!

![SM-G955F](https://user-images.githubusercontent.com/63871973/83947910-e0f0a880-a811-11ea-9db7-78ee6eb3e9fd.gif)UNITO-UNDERSCORE!20200606-162055!

In both examples it works eventually, but only after long pressing multiple times. Usually its worse than this!

### Expected behavior
Text is selected, like in other browsers

### Actual behavior
Double tapping on text shows 2 options: Paste, Select All
Long pressing on text does nothing.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes, any firefox android browser acts the same, with the exception of Focus which i haven't tried.

### Device information
* Android device: 9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1745)

**Comment by johnozbay** [comment]
Hey there @kglazko, @kbrosnan 👋🏻

Maker of Cryptee ([crypt.ee](https://crypt.ee)) here! 
This issue is affecting all our users on Firefox, and I just got a notification that this issue is marked as stale – so thought I'll chime in here. This issue is still out there and is deeply problematic for all android users. 

If you navigate to this exact page / github thread, type something into the comment box and try to select a word by tapping / double tapping on the word, you'll notice that you can't select a single word like the way you can in the rest of the operating system, and you can either "select all" or nothing. 

It's not just editable text-boxes, it seems to also affect regular input fields & textarea elements as well. 
i.e. type anything into Github's search box on this page, and try to select just a single word. 
While it's less critical for input fields, it's a lot more critical for textarea elements.

As far as I can tell all sites with input boxes, textareas and all custom-editors / content editable fields are affected. 

I found another thread, so linking these two : 
https://github.com/mozilla-mobile/fenix/issues/9714

Looks like it's related to this : 
https://bugzilla.mozilla.org/show_bug.cgi?id=1365119

And just to link a few more things, here are a few other comments from the rest of the internet : 
https://www.reddit.com/r/firefox/comments/i70t6o/four_month_old_bug_in_fenix_blocked_by_3_year_old/

As a privacy-first, web-based rich document editor maker, this is starting to become a real problem for our users, and we're basically recommending them not to use Firefox every time this comes up. I can't imagine other providers being too happy about this either.

Thank you so much for your time and help ✌🏻
All the very best,
J

---

Here are two screenshots from this very page on github to demonstrate the issue.

## All Other Browsers and apps in Android (expected behavior) : 

<img src="https://user-images.githubusercontent.com/611338/109137745-3c791280-7762-11eb-8c3b-c4e7cf0baac7.jpg" width="480">

## Firefox : 

<img src="https://user-images.githubusercontent.com/611338/109137749-3f740300-7762-11eb-9ef1-7054abcff127.jpg" width="480">

**Comment by mariansima** [comment]
This issue was reproduced on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Comment by johnozbay** [comment]
I believe this is still affecting our users, as we're still receiving complaints from some of our users. 
I don't think this issue is stale.

**Comment by B0pol** [comment]
bump

**Comment by B0pol** [comment]
???

**Comment by johnozbay** [comment]
Hey team Mozilla — this has been sitting in the backlog for 2,5 years now and the only activity has been the bot auto-closing, and us begging and bumping to reopen it. At the moment it's physically impossible to select text in rich text editors, such as this comment box in Github. Could we at least keep this open please?

**Comment by tx71** [comment]
Very much still an issue indeed, would be nice if this bug gets some love!

**Comment by kbrosnan** [comment]
Anyone continuing to have problems with text editors should file a new report at https://bugzilla.mozilla.org/enter_bug.cgi?product=Geckoview&component=IME which will get the bug in front of the correct people. Please provide:

*  your Firefox version
* phone model
* Android version
* the website you are having problems with
* if you are using a custom keyboard which one

We are not tracking any new bugs in this repository. https://github.com/mozilla-mobile/fenix/issues/26855
