### ISSUE TITLE
[Bug] Not all strings are translated in French

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11362]
## Steps to reproduce
1. Launch nightly
1. Set the language to French
1. Go back to home screen
1. Open the menu. You'll see "Modules complémentaires" (it means "Add-ons")
1. Launch a page
1. Open the menu.
    1. Expected behavior
You see "Modules complémentaires"
    1. Actual behavior
You see Add-ons
    1. Device information

* Android device: Pocophone F1, android 9
* Fenix version: Nightly 200609 06:00 (Build #21610606)

### Notes
I know nightly might be untranslated because it take time, but here there are already two translated strings for Add-ont, therefore I reported that

The duplicate:

* there is the string preference_addons which is translated and is accessible via settings.
* there is the string browser_menu_addons which is translated and used in the menu in home screen

And I can't figure out why it's not using one of these two strings, I can't find the hardcoded string if it exists.

In stable 5.1 all three places where we can see "Add-ons" are translated.

**Comment by mcarare** [comment]
The menu item has changed, the strings are in AC, not translated, at the moment.

**Comment by liuche** [comment]
How should we handle these kinds of missing translation issues, @Delphine? Could be possible these translation imports were lagging due to string freeze, also see #10957 #10951

**Comment by Delphine** [comment]
So the thing is that, in general, we can't really know when a localizer will get to his Nightly strings or not - especially when we don't have clear deadlines for completion of strings.
In fact, we don't have an l10n timeline for the next release yet, so localizers don't know by when they are supposed to complete these incoming strings.

Please note also that we can only ask for French and German locales to always be 100% complete at the day of l10n completion deadline, as per agreement with Leadership. Because of this, I'm not sure it makes sense to test for complete locales other than French and German - and doing this only once we hit the l10n deadline date.

In order to catch issues and hardcoded strings earlier on though, I would suggest to start testing in-context French, German and Italian strings (Italian is a very reactive locale) just a bit before we hit the l10n completion deadline.
Who should I contact on QA side about this so we can align?
thanks!

**Comment by Delphine** [comment]
Update: the add-ons missing strings are due to the fact that these were a-c strings that were never exposed to us (but what I say above remains true ;) ).
There was an issue on file for that, and it's been resolved since: https://github.com/mozilla-mobile/android-components/issues/7777
Unfortunately, they came in too late for the release...

**Comment by B0pol** [comment]
It's been fixed
