### ISSUE TITLE
Make "Send to device" show long device names

### ISSUE THREAD

**Issue by saschanaz** [mozilla-mobile/fenix#11374]
### What is the user problem or growth opportunity you want to see solved?
It's hard to select among multiple similar device names when I can't see the full names:

![image](https://user-images.githubusercontent.com/3396686/84168850-329a6c80-aa78-11ea-8bf1-20a88f8e0213.png)

### How do you know that this problem exists today? Why is this important?
I can't see which is the right one to share.

### Who will benefit from it?
Me and users with multiple Firefox instances

**Comment by AmyYLee** [comment]
@betsymi For recommendation on strings

**Comment by irvinm** [comment]
I just upgraded to Fenix and thought I could share my experience on this matter as it was one of the first things I noticed.

I obviously have a lot of connected profiles between all of my devices including desktop, VMs, and mobile.  When I went to send a URL to my desktop Firefox, I quickly discovered I could not differentiate between a few of my profiles as the names were truncated.  I had to resort to emailing myself the link as I wanted to be sure it was sent to the correct device and profile.

Obviously people can rename the profiles to be unique at a shorter length, but the default name is "(account)'s Firefox on (device name)" and that in and of itself might be longer than can be displayed.  I was appending the profile creation date to the standard name, but this won't be displayed.  [Because of this issue, I have cleaned up my profile names but others may run into this problem and really there should be a way to display longer names]

![2020-08-28_19-30-43](https://user-images.githubusercontent.com/979729/91622514-672a1000-e965-11ea-8c5c-0980912a7053.jpg)

![2020-08-28_19-28-19](https://user-images.githubusercontent.com/979729/91622921-54183f80-e967-11ea-927a-b6022dd9157a.jpg)

**Comment by SharakPL** [comment]
There was no problem with this in previous design (a year back?) so why not use good old ways?

**Comment by dbogdanov** [comment]
I have this issue as well. Makes sharing tabs very complicated when the truncated strings are the same across devices and you have to be mindful of whether you've sent a tab to the correct device.

**Comment by saschanaz** [comment]
Err, can we reopen this?
