### ISSUE TITLE
[UX] Let users know about PiP

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11408]
## User Story
* As a user, I want to know that I have the option of continuing to watch a video while moving on to other tabs or applications.

PiP is a feature that has already been built. This user story is about letting the user know about PiP. Let's aim for the minimum change here. We already have a message to the user about "Entering full screen mode". Can we add something about PiP to the same string? E.g. Entering full screen mode, minimize to continue watching the video outside of the browser" or something more user friendly :grinning: 

### Acceptance Criteria
* I know how to enter Picture in Picture mode.

**Comment by vesta0** [comment]
@betsymi here is the issue we chatted about yesterday. Would be great if we have something before string freeze.

**Comment by betsymi** [comment]
> @betsymi thanks for looking into this last minute. I think your recommendation makes sense.
> 
> Will keep this issue in the UX backlog so we don't lose track of it for future.

I have been discussing with UX design team members how to address this in a different way. We can take this through the framework to understand when and how to give users access to this feature. cc @lime124

**Comment by black7375** [comment]
@vesta0 
> PiP is a feature that has already been built.

I didn't even know if the PIP function was implemented...
I didn't know that I could use it only by entering full screen.

Full screen is mainly used in professional video apps (`YouTube`, `Netflix`, ..etc), and browsers view video descriptions and feedback together.

### 1. Activate
The [Yandex browser](https://play.google.com/store/apps/details?id=com.yandex.browser.alpha) is the best example of PIP feature.
If I switch to another tab or try to go to the home screen while the video is turned on, ask as the pop-up.  (In the first run)
PIP is appropriate because it is a function used to switch to another action while the video is on.

- Activate at swith tab or app
![Yandex-0_PIP_Activate](https://user-images.githubusercontent.com/25581533/94316295-9dae7700-ff73-11ea-8a02-7fed4dd55197.jpg)
- PIP at other app
![Yandex-1_Home_PIP](https://user-images.githubusercontent.com/25581533/94316926-cf740d80-ff74-11ea-9305-66cf75f08a5c.jpg)
- PIP at other tab
![Yandex-2_Tab_PIP](https://user-images.githubusercontent.com/25581533/94316960-d8fd7580-ff74-11ea-8991-2f8769e5a9e3.jpg)

Other activate suggestion.
If `PWA` is possible, press `3-Dot` button to get an install button.
If the site has the video on, I think it's good to display it when you press the menu.

### 2. Setting
In addition, it does not exist in the settings.
I think it is difficult for the user to recognize the feature.

PIP requires permission and is optional.
Therefore, I think it should be possible to control it in the settings.

- Firefox
![Fenix-0_Setting](https://user-images.githubusercontent.com/25581533/94317731-68575880-ff76-11ea-8a0b-4412938e0f3b.jpg)
- Yandex
![Yandex-3_Setting](https://user-images.githubusercontent.com/25581533/94317742-6d1c0c80-ff76-11ea-96d2-38c5c6a0cd57.jpg)

### 3. Exit message
The exit message is not clear.

1. **Results first**
Users already know what they are doing.
It is intuitive to write the result first.
2. **A word `Dismiss`**
Drag is a good word, but `dismiss` is not.
I think `Close` is a universal word, such as being used in a PC.

- Firefox
![Fenix-1_Close](https://user-images.githubusercontent.com/25581533/94318332-ce90ab00-ff77-11ea-9447-849b8496366e.jpg)
- Yandex
![Yandex-4_Close](https://user-images.githubusercontent.com/25581533/94318248-9a1cef00-ff77-11ea-86fd-4da506acca22.jpg)

I hope my feedback was helpful.

**Comment by vesta0** [comment]
Thank you for sharing your thoughts and research @black7375 I think it will be very helpful for our UX team who will be working on this.

**Comment by black7375** [comment]
Is there any progress?

**Comment by pwd-github** [comment]
Can the notification not be used at all? When you play a video Android displays that Firefox is playing a video, why not add the PiP button to that?
