### ISSUE TITLE
FNX-12345 ⁃ [feature request] It's hard to swipe horizontally when there're 6 apps suggestions in the "Recently used" sub tray in share sheet

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11412]
Currently there're 6 apps suggestions in the share sheet sub tray (please see the screenshot for what I'm saying). It's making it harder to swipe horizontally to select others share targets/apps since it's triggering the system swipe gesture (back gesture) most of the time because there's very less space remaining to swipe horizontally thus I end up exiting the share sheet instead. 

Can you reduce the number of apps suggested in the "Recently used" sub tray in share sheet or make it so that it doesn't trigger the system back gesture so easily?

![Fotor](https://user-images.githubusercontent.com/42088907/84236612-6cef2280-aae7-11ea-86e9-3ef463255562.jpg)UNITO-UNDERSCORE!159177209154166!

**Comment by SS1113** [comment]
@mcarare Hi, in the new beta version `5.2.0-beta.1` I can swipe the whole share sheet menu (Recently userd+ All actions). Is it intentional? If so this solves the issues I was raising.


![Screenshot_20200610-121329](https://user-images.githubusercontent.com/42088907/84235686-cbb39c80-aae5-11ea-8a3b-5dcc6fcb4075.png)

**Comment by mcarare** [comment]
@SS1113 yes, it was introduced in https://github.com/mozilla-mobile/fenix/pull/11077. If you can test also on the latest Nightly from Playstore please close this issue if the feature works as expected. Thank you!
