### ISSUE TITLE
FNX-12351 ⁃ [Bug] APK's no longer being generated for stable releases?

### ISSUE THREAD

**Issue by Vinnl** [mozilla-mobile/fenix#11418]
## Steps to reproduce
It used to be the case that new stable releases would provide APKs on the GitHub releases page in one or two days, but if I now go to either of the latest two releases, no APKs are available:

* https://github.com/mozilla-mobile/fenix/releases/tag/v5.1.0
* https://github.com/mozilla-mobile/fenix/releases/tag/v5.1.1

This might be intentional, but if not, here's a heads-up :grinning:

### Expected behavior
APK downloads to be available.

### Actual behavior
No APK downloads are available for Firefox Preview 5.1.0 and later.

### Device information
* Android device: N/A
* Fenix version: 5.1.0 and up

**Comment by SS1113** [comment]
@Vinnl I have already raised this issue: https://github.com/mozilla-mobile/fenix/issues/11030. Apparently they'll publish the APKs  to GitHub only after they release it to 100% of Play Store users. I already said that they should public the links to there Taskcluster somewhere easily accessible such as GitHub's `Readme` page for users who want to install early versions. 

But if you want you can download the builds from the Taskcluster: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2

Firefox Preview releases are available under the "Production" label.

**Comment by Vinnl** [comment]
Thanks for the pointers @SS1113! I'll close this one then and subscribe to yours.

**Comment by callegar** [comment]
Delivering on play store /before/ the delivery on github is a bit weird, surely discouraging the part of users who would be willing to report issues and provide feeback on github rather than leaving a negative feedback on the playstore when they encounter an issue.
I would recommend at least updating the readme on github to point at where the builds can be found.

There is an additional issue, though. Those who started with the downloads from github see the application in the playstore in a status where it cannot be upgraded from there unless one uninistalls and reinstalls from the playstore, loosing all personal data, passwords, etc.

**Comment by SS1113** [comment]
@callegar The builds have the same APK signature as on the Play Store so they can be updated through Play Store as well without losing any data.


Can you & @Vinnl leave a comment or a like on the issue I created #11030 ( I don't know how get Mozilla's attention on the issue, that's why the suggestion).

But I'm glad that I'm not the only one who thinks builds should be accessible to users who want to test and use early versions. And in doing so help report bugs, get involved in the development by suggesting improvements, by filing bugs and by other ways.

**Comment by Vinnl** [comment]
I'd prefer not adding noise without contributing new information to the conversation; I've :+1:'d it. That said, if the APKs do eventually get published on the GitHub Releases page I don't mind _too_ much; I suppose the rollout to 100% of users is just taking a longer time than usual for the last two releases.

**Comment by callegar** [comment]
@SS1113 I have just checked. The play store client recognizes the "firefox preview" installed from github's apks, but only proposes to "open" the application, not to upgrade it, even if my app is at version 5 and the play store is at 5.1.1. To upgrade you need to uninstall and re-install. The reinstalled version does not see the data of the previous one, even if - from my understanding - android usually backs up and restores the data of official (playstore) applications.

The github apk is now 2 versions late 5.1 and 5.1.1. Because new updates may also bring in security fixes remaining at some apk when new versions are available seems unwise unless you are in a restricted testing environment.

**Comment by SS1113** [comment]
@callegar That shouldn't happen! But I have checked it again by downloading the `Firefox Preview 5.0.0` from GitHub and thr Play Store offered me the update to `5.1.1` and I was able to update successfully! 

Try clearing the Play Store's cache and force stop it and restart your device. And if it still doesn't work clear the data of the Play Store (don't worry you won't lose anything) and restart your device.

**Comment by callegar** [comment]
Yep, tried on another device and worked there.

**Comment by physkets** [comment]
That does not help people who do not have Google's Play Services installed. The only mode of obtaining Fenix's new releases is via the APKs on GitHub.

**Comment by cadeyrn** [comment]
@physkets No, it's not the only way. Please read the first comment after the original report.

**Comment by physkets** [comment]
@cadeyrn So under [Production](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production), do I click on 'latest' and choose the appropriate APK, or do I navigate by date to the latest?

**Comment by cadeyrn** [comment]
You can do both but "latest" is the fastest way.

**Comment by neekless** [comment]
The latest in https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production is 13 days old and is not the same as the play store

**Comment by physkets** [comment]
@neekless Try this: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest
