### ISSUE TITLE
Add an option to move tabs to collections (and thus delete them from the usual tab list)

### ISSUE THREAD

**Issue by tukusejssirs** [mozilla-mobile/fenix#11463]
Currently, when I create a new collection from selected tabs (or add them to an existing collection), they are actually copied/duplicated in the collection.

I wish that they would be automatically deleted from the usual tab list once they are _moved_ into a collection. Optionally, there could be either a global settings for this or a checkbox somewhere during the process of moving the tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1987)

**Comment by tukusejssirs** [comment]
Actually, I have an older issue #3005 that dealt precisely with this, but in Fennec (I opened this issue for Fenix / FF Nightly for Android). As I see it, the FF mobile devs what to see the collections as named bookmarks, but the real users view them as tab groups. I am in the other camp as if I am in a need to create a bookmark, I create one, I can even create folders for them. However, currently there is no way to create a tab group on FF without third-party extension. I DESPARATELY need one! (I know there’s already open an issue for the tab groups, #5967).

**Comment by JNavas2** [comment]
Collections are actually defined as **saved tabs**–see [Comment](https://github.com/mozilla-mobile/fenix/issues/11506#issuecomment-643264112) on #11506
> This is intentional behavior with collections currently. We are restoring the state of the tab with history as well.

I think this unfortunate, because it greatly reduces the usefulness of Collections to me.
I had hoped/assumed Collections would be like Tab Groups.
I'll have to go back to using Bookmark folders. :disappointed:

**Comment by madb1lly** [comment]
Hi @tukusejssirs,

I agree that not removing tabs from the tab list when they are saved to a collection is frustrating, but my only case when this _is_ useful is when I want to send several tabs to another Firefox instance then saving to collection and sharing them all together is the quickest way.

I have to say this is actually the only way I'm using collections at the moment, because the issue you explain makes using collections a pain.

Cheers 🙂

**Comment by Dunexus** [comment]
You can send tabs to other devices or sync tabs using FxA in fenix as well without using collections.

**Comment by JNavas2** [comment]
@Dunexus 
Yes, I can explicitly Share (send) tab(s) to other devices in Fenix Preview, but it's not as simple and foolproof as in Chrome, where I can open my desktop and see my open mobile tabs, explicitly shared or not, because tabs are automatically synced in Chrome. Fenix Preview only syncs History and Bookmarks AFAIK.

Regardless, as you point out, tab sharing is not a good use case for Collections.

**Comment by Dunexus** [comment]
@JNavas2 
Open tabs can be synced but the integration in search results is this a work in progress (see https://github.com/mozilla-mobile/fenix/issues/11245).
Other fixes about tab sync are tracked in the issues.
These additions will probably make cross devices browsing closer to what you describe.

**Comment by decadent** [comment]
Alternatively to closing the tabs automatically, the selection could simply be kept after saving a collection. This way, I could either close the chosen tabs or remove the selection with the ‘X’ button.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812751

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
