### ISSUE TITLE
Suggestion for the Tab Switcher

### ISSUE THREAD

**Issue by Oranko** [mozilla-mobile/fenix#11513]
### What is the user problem or growth opportunity you want to see solved?
Too many taps and screens to go through to start a new search. To start a new search one has to first click on tab count, then on the plus icon and then finally on the search bar. In the previous/ stable version it is just two taps: click on the tab count and then on the search bar.
**My Suggestion**: When clicking on + in tab tray along with opening the home page/ new tab make the search bar come in focus automatically so that the keyboard pops up as soon as we open a new tab so that we can begin a new search in just two taps. For the quick tiles you can add them to a drop down menu when the search bar is in focus and replace them with the search suggestions once we start typing (a bit similar to Samsung browser).
**Another small tweak**: Long press on the tab count to start a new tab with search bar in focus. So that if a person wants to start a new search he can do it quickly this way and if a person to open the quick tiles without having to deal with the autofocus on search bar can do it the traditional way.

### How do you know that this problem exists today? Why is this important?
This is a small feature that will definitely save time and effort by significantly reducing the time to start a new search.

### Who will benefit from it?
Everyone who wants to save time.

**Comment by cadeyrn** [comment]
> Long press on the tab count to start a new tab with search bar in focus

A few days ago a long press behaviour for the tab counter was already implemented. It opens a menu with options to close the current tab, open a new tab or open a private tab. This proposal conflicts with the already implemented behaviour.

**Comment by Shaurya-Kalia** [comment]
> > Long press on the tab count to start a new tab with search bar in focus
> 
> A few days ago a long press behaviour for the tab counter was already implemented. It opens a menu with options to close the current tab, open a new tab or open a private tab. This proposal conflicts with the already implemented behaviour.

I would say that it is a better solution. My primary usage of tab switcher is switching apps and not opening new one. A keyboard and search bar appearing will feel distracting and take space. Existing implementation of opening a new tab on long press appears to be a good solution since it preserves the tab tray's function, while also preventing extra click and thumb movement to open new tab from tab tray, though slight modifications can be made such as to open a new tab directly or a new private tab directly, when in normal or private mode respectively, rather than showing separate options for them, to save time as the op desires

**Comment by Gauravjani207** [comment]
Yes. This feature would help people. If possible, please implemente it.

**Comment by yoasif** [comment]
I didn't see this issue in search, so I created a more specific issue here: https://github.com/mozilla-mobile/fenix/issues/11955 (naming issues for search helps!).

**Comment by AmyYLee** [comment]
@brampitoyo and @topotropic  for UX consideration

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

🚩 Flag added 

Need to do some quantative analysis first

**Comment by JVariance** [comment]
Please give us the option in settings to directly open a new tab with focus on the address bar instead of the popup (close tab, new private tab, new tab) on longpress on the tab counter! The current behavior is so annoyingly unconveniant on a permanent basis.

I rarely open a private tab and I also rarely close tabs via this popup.
