### ISSUE TITLE
FNX2-13516 ⁃ [Bug] inconsistent icon size in tab counter long press menu

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11563]
### Steps to reproduce
1. open a tab
1. long press on the tab counter

### Expected behavior
consistent icon sizes.

### Actual behavior
The close icon is noticeably smaller than the other icons.

![Screenshot](https://user-images.githubusercontent.com/1100614/84588827-d09c8700-ae2a-11ea-8dfd-4686d99a415a.jpg)UNITO-UNDERSCORE!20200611-212437!

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 7e6116512c354eb1d8524f8922f7970fe155c65c

**Comment by AmyYLee** [comment]
@cadeyrn I agree the close icon is too small and should match the size of the other icons in the list. Let me know if you need anything from me to fix this. Thanks!

**Comment by hakkikaancaliskan** [comment]
Both icon is 24x24 and looks like no problem on engineering but ic_close.xml is noticably smaller in 24x24.

**Comment by gabrielluong** [comment]
Icons are sometimes found here https://design.firefox.com/icons/viewer/. One thing I would do is re-verify if the path in the svg is correct with the ones in the icon viewer.

**Comment by hakkikaancaliskan** [comment]
I've fixed this, will open pr.

**Comment by hakkikaancaliskan** [comment]
> 
> 
> Icons are sometimes found here https://design.firefox.com/icons/viewer/. One thing I would do is re-verify if the path in the svg is correct with the ones in the icon viewer.

All icons 16x16 in that site, so I grabbed from photon.

**Comment by Diana-Rus** [comment]
Hi, issue is fixed with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9) with latest Nightly 200712
<details closed>
<summary>Samsung Galaxy S9 (A8) - Fixed</summary>

![Screenshot_20200713-103704_Firefox Nightly](https://user-images.githubusercontent.com/49859863/87283663-2fbeeb80-c4fe-11ea-8e3f-0ff3ad3b5a32.jpg)
</details>

<details closed>
<summary>Google Pixel 3 XL (A9) - Fixed</summary>

![Screenshot_20200713-115046](https://user-images.githubusercontent.com/49859863/87284375-f63ab000-c4fe-11ea-9df7-2497c2eb6e88.png)
</details>
