### ISSUE TITLE
FNX-4834 ⁃ Address notification email in metrics.yaml

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1157]
Our initial batch of metrics will stop collecting next March. We should add an appropriate email to be notified or come up with another way to track renewing them.

**Comment by Dexterp37** [comment]
Hey @boek ! I think this is important and not only about the metric expiration itself: this will be the advertised email for the "contact point" in the probe dictionary. Moreover, that's also used by data-stewards to verify, in the future, that the data is still useful/needed.

**Comment by boek** [comment]
@bbinto We need a product email to put here :)

**Comment by bbinto** [comment]
@liuche any idea based on your previous knowledge?

Should we create an internal fenix-telemetry email list?

**Comment by liuche** [comment]
These emails shouldn't be incredibly intrusive, and the goal is to create a regular checkin for Product, both to a) be refreshed on what probes are being collected, because it's likely there are a lot of probes, b) reaffirm that those are still useful, not redundant, still relevant.

To that end, I'd suggest including an existing mailing list, that all Product will already be on, that can include a bigger group as well. The risk with a new mailing list is that there are already so many mailing lists for new people to be added to, that it risks being missed.

On the other hand, if there's a mailing list where the team is already receiving updates on telemetry, or crashes, that could be another good candidate.

The goal here though is for the Product owners to be seeing and choosing to refresh (or remove) probes as their expiry comes up.

**Comment by bbinto** [comment]
Thanks @liuche - let's use fenix-core@mozilla.com
