### ISSUE TITLE
Provide android notification channels for each push subscription domain

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#11587]
### What is the user problem or growth opportunity you want to see solved?
There is currently no way for users to give individual importance for web notifications from different domains. All web notifications have the same importance / priority. 

This could be solved by creating a notification channel for each domain and bundling them all under a combined "Web Notifications" channel group as described here https://developer.android.com/training/notify-user/channels#CreateChannelGroup.

### How do you know that this problem exists today? Why is this important?
Having more than one push subscription from different sites can become somewhat annoying. Since I can not distinguish between the origins of the notifications without looking at them, there is no way to determine if a new notification is important to me at the moment.

### Who will benefit from it?
All Android users with an OS version of 8 or higher.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2148)

**Comment by jonalmeida** [comment]
Adding `UX-investigation` because the request seems like something we ought to do, but conflicts with our current paradigm on how to handle site permissions.

### Current Behaviour

All site permissions are in Settings > Site permissons. This lets you control which site can send you Web Notifications.

### Expected Behaviour

Create an [Android notification channel](https://developer.android.com/training/notify-user/channels) for each site so that the user can control which Web Notifications with more system granularity settings.

An example of what this request can be compared to:

<img width="320" alt="Screen Shot 2020-07-02 at 2 53 00 AM" src="https://user-images.githubusercontent.com/1370580/86326150-45cfd080-bc0f-11ea-93eb-f2154702de65.png">

Here, Chrome creates a notification group called 'Sites' where each site has it's own set of notification controls. For example `web-push-book.guantface.com`:

<img width="320" alt="Screen Shot 2020-07-02 at 2 54 50 AM" src="https://user-images.githubusercontent.com/1370580/86326250-6a2bad00-bc0f-11ea-971f-8cbf914850f1.png">

If go the same route, I believe we would be sacrificing the consistency of our site controls since we now have two places where you can enable/disable them: in the 'Site permissions' setting and the Android notification group.

**Comment by TitanNano** [comment]
@jonalmeida I think if a user revokes the permission for a site then the notification channel should be deleted.

**Comment by jonalmeida** [comment]
> @jonalmeida I think if a user revokes the permission for a site then the notification channel should be deleted.

Disabling the notification setting shouldn't remove the channel, but deleting the custom site permissions for that site probably should. I'm going to leave it for UX to follow up on.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809278

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
