### ISSUE TITLE
[Bug] [Suggestions] Various three-dot menus have become very small

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11716]
The three-dot menu has become really small when at various places in Fenix.

The three-dot menu in the collections, the new Tabs Tray, the bookmarks menu, the Top Sites long-press menu have become very small If this is intentional then I suggest you to please revert it to the state it was before!

**Edit**: After thinkig about it a little bit, I think **three-dot menu of the bottom navigation bar and the menu at the new Tabs Tray should be  made bigger** (reverted to how it was before) because when navigating the thumb finger is around at the centre of the display and clicking it requires that the menu should be bigger so it can be clicked easily while using the phone with only one hand. Otherwise I have to move my finger further to the right and it'll be a bit harder to press the menu.

Device: **Motorola One Power, Android 10**.
Fenix: **`Nightly 200617 18:01`**.

![Screenshot](https://user-images.githubusercontent.com/42088907/84966413-04183380-b101-11ea-9959-f89b5e56e60e.png)UNITO-UNDERSCORE!20200618-063848!

![Screenshot](https://user-images.githubusercontent.com/42088907/84989832-c97bbe80-b133-11ea-8ea5-e2308c317018.png)UNITO-UNDERSCORE!20200618-124438!
![Screenshot](https://user-images.githubusercontent.com/42088907/84989840-cd0f4580-b133-11ea-9726-12a853e78e7f.png)UNITO-UNDERSCORE!20200618-124430!

![Screenshot](https://user-images.githubusercontent.com/42088907/84997197-c5549e80-b13d-11ea-93b6-df827cdbabec.png)UNITO-UNDERSCORE!20200618-135704!

![Fotor](https://user-images.githubusercontent.com/42088907/84998494-6db73280-b13f-11ea-8c7d-1bafa66e5c6f.jpg)UNITO-UNDERSCORE!159246958949487!

**Comment by Dunexus** [comment]
See https://github.com/mozilla-mobile/fenix/issues/1871#issuecomment-643964563 for UX context about the menus min/max width change.

**Comment by Mugurell** [comment]
This seems to clash with #1871 per which all menus now wrap their text automatically while still being at least 112dp wide.
To keep consistency across all menus maybe we could increase their minimum size?
Asking for UXs second opinion.

**Comment by SS1113** [comment]
Yes, I think the menu's default width should be increased. The behaviour is already inconsistent, when at the Fenix homescreen the three-dot menu is smaller and the same menu when opened when a website loaded is bigger.
The menu's width should be increased to match with the size when a website is loaded.

**Comment by AmyYLee** [comment]
Did the size of the 3-dot menu change sizes at some point? The 3-dot menu should be consistently the same size in the app.

**Comment by Mugurell** [comment]
> Did the size of the 3-dot menu change sizes at some point? The 3-dot menu should be consistently the same size in the app.

Please see https://github.com/mozilla-mobile/fenix/issues/1871#issuecomment-643964563

It was a [priority from product](https://github.com/mozilla-mobile/fenix/issues/1871#issuecomment-642782239) to have the menus wrapping their content.

**Comment by SS1113** [comment]
AmyYLee is correct! In my opinion the 3-dot menus should never change their sizes. That feels really inconsistent! No app or browser I have seen does this. 

Dynamically changing those menus really confuse and are very inconsistent across the browser! 3-dot menus in Fenix  perform some of the very important functions and having them change sizes suddenly will feel very unusual to users who have seen the same sized menus across the Android app ecosystem. This will definitely feel like a bug to new and existing users as some menus are really small in their width! Making them hard to tap when using with just one hand.

**Comment by ShatteredPixel** [comment]
Hi, I'm the reporter of this issue. Please let me know if you need more information.

Thanks! :)

**Comment by Mugurell** [comment]
> Please see [#1871 (comment)](https://github.com/mozilla-mobile/fenix/issues/1871#issuecomment-643964563)
> 
> It was a [priority from product](https://github.com/mozilla-mobile/fenix/issues/1871#issuecomment-642782239) to have the menus wrapping their content.

Atm this is the expected behavior.
Asking again for UX feedback if we should do anything about the current UX, like having a bigger minimum width maybe? ..
Which would mean blank space for certain menus, something that I think we wanted to avoid..

**Comment by ShatteredPixel** [comment]
If the UX team is reading this I want to make some arguments with them. If you may allow then please listen to me...


You want to wrap the menus around the amount of text displayed, right? Okay then, here's the problem is with it; it doesn't match or feel like any consistently designed Android app I have come across until now or AOSP android itself. The concept itself is not wrong but there are _a lot_ of problems with it, one of them is inconsistencies within Fenix itself and compared to Android app ecosystem and AOSP android itself.  

***Here's how the Chrome browser behaves, please look at the consistency between the 3-dot menus, they are represented with same consistency with respect the context across the Chrome browser:***


![Screenshot_20200717-111528](https://user-images.githubusercontent.com/68282543/87763743-e1c62280-c832-11ea-8351-6d5d3f875759.png)
![Screenshot_20200717-111549](https://user-images.githubusercontent.com/68282543/87763749-e2f74f80-c832-11ea-94a2-448b4f303251.png)


![Screenshot_20200717-112025](https://user-images.githubusercontent.com/68282543/87763735-df63c880-c832-11ea-8105-40323d236d27.png)

![Screenshot_20200717-111903](https://user-images.githubusercontent.com/68282543/87763751-e4287c80-c832-11ea-82d8-2ffa4f3638ad.png)

![Screenshot_20200717-111912](https://user-images.githubusercontent.com/68282543/87763753-e559a980-c832-11ea-80a6-621b872caf14.png)
![Screenshot_20200717-143502](https://user-images.githubusercontent.com/68282543/87769203-eabaf200-c83a-11ea-8f81-d6abe2eccbd5.png)



***Vivaldi Browser's 3-dot menus behavior:***

![1](https://user-images.githubusercontent.com/68282543/87769584-7b91cd80-c83b-11ea-86c8-503a22ff831a.png)
![2](https://user-images.githubusercontent.com/68282543/87769596-7f255480-c83b-11ea-883f-f6d485a6fa03.png)
![3](https://user-images.githubusercontent.com/68282543/87769603-82204500-c83b-11ea-96f4-e19426f2e59b.png)
![Screenshot_20200717-152749](https://user-images.githubusercontent.com/68282543/87774548-4b99f880-c842-11ea-9185-6779ed945d76.png)
![Screenshot_20200717-152801](https://user-images.githubusercontent.com/68282543/87774556-4e94e900-c842-11ea-90b5-26f230332959.png)


  



***Here's how Material File's 3-dot menus behave:***

![Screenshot_20200717-135919](https://user-images.githubusercontent.com/68282543/87766834-6155f080-c837-11ea-8d19-d2205436a360.png)
![Screenshot_20200717-135930](https://user-images.githubusercontent.com/68282543/87766844-63b84a80-c837-11ea-8e55-3b14a7934ac7.png)
![Screenshot_20200717-140014](https://user-images.githubusercontent.com/68282543/87766850-64e97780-c837-11ea-9b23-64440de8cbaa.png)
![Screenshot_20200717-140123](https://user-images.githubusercontent.com/68282543/87766853-661aa480-c837-11ea-893e-2f67d618390f.png)


***YouTube's 3-dot menus behavior:***

![rd_15949763874554](https://user-images.githubusercontent.com/68282543/87768781-4c2e9100-c83a-11ea-8410-85e8a83abbf3.jpg)
![jftr_159497621565089](https://user-images.githubusercontent.com/68282543/87768787-4f298180-c83a-11ea-9fd7-ac1fd595b991.jpg)




***Gmail's 3-dot menus behavior:***

![1](https://user-images.githubusercontent.com/68282543/87770616-df68c600-c83c-11ea-8230-a2ee8d2de1d8.jpg)
![2](https://user-images.githubusercontent.com/68282543/87770624-e1cb2000-c83c-11ea-9ece-5f9fc649952b.jpg)
![3](https://user-images.githubusercontent.com/68282543/87770627-e263b680-c83c-11ea-9c86-ab5304111dcc.jpg)
![3](https://user-images.githubusercontent.com/68282543/87770631-e2fc4d00-c83c-11ea-929f-481a6787087e.png)


***Files by Google's 3-dot menus behavior:***
![hg_15949777448740](https://user-images.githubusercontent.com/68282543/87771752-6a968b80-c83e-11ea-9698-7cb491631610.jpg)
![lkj_159497781882226](https://user-images.githubusercontent.com/68282543/87771762-6c604f00-c83e-11ea-867d-ae925fd3a772.jpg)
![Fgjr_159497787224088](https://user-images.githubusercontent.com/68282543/87771765-6d917c00-c83e-11ea-8052-ec4c42cfc42c.jpg)
![Screenshot_20200717-112612](https://user-images.githubusercontent.com/68282543/87771770-6ec2a900-c83e-11ea-9110-8959322755c3.png)
![Screenshot_20200717-112617](https://user-images.githubusercontent.com/68282543/87771775-6ff3d600-c83e-11ea-9b06-162e8faf9e50.png)


***AOSP Android's 3-dot menus behavior:***

![Screenshot_20200717-115313](https://user-images.githubusercontent.com/68282543/87773117-50f64380-c840-11ea-815c-2ed12d302628.png)
![Screenshot_20200717-115321](https://user-images.githubusercontent.com/68282543/87773124-53589d80-c840-11ea-8f9e-33cab3fda410.png)
![Screenshot_20200717-115338](https://user-images.githubusercontent.com/68282543/87773137-55baf780-c840-11ea-8c3b-d06aa6f1f0a3.png)



![Screenshot_20200717-140159](https://user-images.githubusercontent.com/68282543/87773143-594e7e80-c840-11ea-9bb7-aff894611dfe.png)


Google Messages, Google Phoen, Google Clock, etc. behave the same way...

Now I can go on like this but do you see a pattern in them? if yes, then I want you to think about it.





Okay, now see the screenshots of Fenix's behavior in comment 0 i.e in the issue's description.

**Comment by ShatteredPixel** [comment]
Please refer the above comment for the context: https://github.com/mozilla-mobile/fenix/issues/11716#issuecomment-660013061


Adding another comment because the above comment has become very long and it'll confuse anyone looking at it, even I'm having a hard time comprehending what I actually want to say by looking at it. 

In short, what I want ot say is make the menus consistent bases on where they are opening. Please see the screenshots;

### Make these menus consistently sized (Main 3-dot menu of the bottom/top toolbar), they seem to be changing sizes, which is not what you'd expect from a consistently designed app, look at Chrome browser for example: 

![Screenshot_20200719-191307](https://user-images.githubusercontent.com/68282543/87876601-a9f0e380-c9c8-11ea-9f6d-30ad5e9a4d98.png)
![Screenshot_20200719-191313](https://user-images.githubusercontent.com/68282543/87876604-ae1d0100-c9c8-11ea-8cd5-8a7fcd1e9622.png)
![Screenshot_20200719-191318](https://user-images.githubusercontent.com/68282543/87876609-b4ab7880-c9c8-11ea-90aa-79b3ab66e4e1.png)

### Make these menus consistently sized (Bookmarks, Bookmarks folder, History and tabs tray's 3-dot menus menus):

![Screenshot_20200719-191225](https://user-images.githubusercontent.com/68282543/87876673-516e1600-c9c9-11ea-8d87-76eaca4364b5.png)
![eiw23r_159516668662211](https://user-images.githubusercontent.com/68282543/87876688-6b0f5d80-c9c9-11ea-8bfc-846d04d14aa3.jpg)
![Screenshot_20200719-191817](https://user-images.githubusercontent.com/68282543/87876704-867a6880-c9c9-11ea-911a-51fe6c5dbf0e.png)
![Screenshot_20200719-192801](https://user-images.githubusercontent.com/68282543/87876707-8a0def80-c9c9-11ea-8747-f2a80d5d9a8a.png)

### The only menu I don't have any problem with is this Top Sites' long press menu but I leave that to you to decide what its size should match with or should be left to stay as it is.

![Screenshot_20200719-191633](https://user-images.githubusercontent.com/68282543/87876750-c6d9e680-c9c9-11ea-8abb-09f6695b1cb8.png)

**Comment by Mugurell** [comment]
@ShatteredPixel The menus have dynamic widths now I think mainly because of these two reasons:
 - There are locales (maybe even some menus in English) with translated menu titles which are too big to fit in one hardcoded menu width and so important information about that option may be lost. Cannot make all menus as wide as the screen (to allow for this worst case) as that would mean a lot of empty space in many cases.
- There are locales (and even menus in English) with translated menu titles which are very small - 1 / 2 small words. If we would have all menus half/2 thirds the screen it would mean a lot of empty space, issue that was raised by other users.

Dynamic menus that would wrap their contents resolve both issues but that indeed means menus would have different sizes all around the app.

Looking forward to UX feedback.

**Comment by ShatteredPixel** [comment]
I know a little bit about the menus are cutting their sizes. Having too much empty space was indeed a bit weird for me too and I also wanted to see their sizes reduce somewhat in the past but I didn't imagine this situation of menus dynamically changing their sizes (I'm still having a hard time imagine why the 3-dot main menu is changing sizes dynamically 🤔, I mean the same menu has 3 different sizes now; one on the homescreen, another when a website is opened, and another one when add-ons sub menu is opened!). I have not seen any app do this and it'll definitely feel like a bug to anyone who's looking at it, I think. Do you know any app that does this? I have never seen a single menu that has several size in the same position in any app.

I'm only talking keeping English language in mind but of course all other languages should also be kept in mind. If the benefits are really outweighing the negatives we're getting in return then the current menu sizes could be kept. I'm also looking forward to what UX team has to say on this.



But it really does make me curious as to how other browsers like Chrome are handling this situation? I have not seen it behave like this as Chrome also supports several languages. Are they also changing the menu sizes dynamically for the same menu on other languages? Do you any ideas?

**Comment by NotWoods** [comment]
I've updated @ShatteredPixel's comments to make the images easier to preview. Clicking on images will load the full-size version.

**Comment by ShatteredPixel** [comment]
I have noticed something this morning.
Are the 3-dot menus changing sizes when a website is PWA?!

Here're some of the screenshots compared to menus on normal websites;

This is on "LiveChart.me": 
![Screenshot_20200720-093949.png](https://user-images.githubusercontent.com/68282543/87899100-c09d4600-ca6d-11ea-82f3-e5d3acf7493e.png)

This is on twitter.com: 

![dbior_159521828309320.jpg](https://user-images.githubusercontent.com/68282543/87899150-e75b7c80-ca6d-11ea-9378-772c3d688811.jpg)

This is on "instagram.com" :
![Screenshot_20200720-093830.png](https://user-images.githubusercontent.com/68282543/87899188-03f7b480-ca6e-11ea-8f9d-242e825d2af1.png)

This is on "MyAnimeList.net" : ![Screenshot_20200720-095014.png](https://user-images.githubusercontent.com/68282543/87899450-d7906800-ca6e-11ea-85b2-47c6e4c81133.png)

___

This is on *Androidpolice.com" which is a normal website:

![Screenshot_20200720-094431.png](https://user-images.githubusercontent.com/68282543/87899213-1d006580-ca6e-11ea-94e3-d0615f43a687.png)


This is on "arstechnica.com" which is a normal website: 

![Screenshot_20200720-095204.png](https://user-images.githubusercontent.com/68282543/87899432-c9dae280-ca6e-11ea-9868-1845619f9198.png)



Please tell me what's happening...

**Comment by NotWoods** [comment]
Since "Add to home screen" is the longest item in the menu (at least in English) and it's replaced by "Install" for PWAs, yes the current menu changes size. No additional issue is needed as this relates to the current issue.

**Comment by ShatteredPixel** [comment]
Thanks for the clarification!

I am feeling dizzy now... it feels like I have not yet accepted reality of Fenix changing menu sizes, LOL!

I am gonna take a break from this, I think. If I keep this up, I might no more think clearly about the UX and suggest something entirely wrong! as you can see I was about file a new issue for this a while ago! :sweat_smile:

Thanks again for the clarification! and goodbye for a while... I think. ;)

**Comment by AmyYLee** [comment]
@brampitoyo for comment

**Comment by brampitoyo** [comment]
@ShatteredPixel What would your proposal be, after looking at Material Design’s menus guidelines and recommendations? https://material.io/components/menus#specs

Are you suggesting that the menu should have static width 100% of the time for total consistency (instead of dynamically fitting to the text)? Or that it should have a wider minimum width? Can you outline a bit more?

**Comment by ShatteredPixel** [comment]
> 
> @ShatteredPixel What would your proposal be, after looking at Material Design’s menus guidelines and recommendations? https://material.io/components/menus#specs

I'm sorry @brampitoyo, this is something that I cannot do because I am not a UX and UI designer and I don't have a bit of knowledge about how to design UI. Everything that I am saying here is coming from a general user who is just observing how the Material Design is being implemented and looking like in all apps that I am using. I was there when Holo design was being used in Android apps and I was also there when Google announced the Material Design and apps started adapting it. I don't know why, but I just get the feeling that how Fenix is acting is a bit unusual. That's it. It doesn't feel natural to me at all. I cannot take the responsibility of proposing _anything_ here. Because they are based on my instincts and they could go wrong.  
> 
> Are you suggesting that the menu should have static width 100% of the time for total consistency (instead of dynamically fitting to the text)? Or that it should have a wider minimum width? Can you outline a bit more?

### **https://github.com/mozilla-mobile/fenix/issues/11716#issuecomment-660013061 have a look at this comment, and focus only on the Chrome Browser:**


 3-dot menus _are_ changing sizes here BUT only with respect to the context of where they are opening and they are also big enough and also feel okay to me which in case of Fenix it doesn't for me: 

- Look at the 3-dot menus of:

  - Main 3-dot menu
  - Tabs tray 3-dot menu
  - Open a website, PWA or otherwise; Look at the 3-dot main menu
 
- Look at the 3-dot menus of:

  - Individual Bookmarks items' 3-dot menu
  - Individual Bookmarks folder's 3-dot menu

- Look at the 3-dot menus of:

  - long press on one of the bookmarks items and click at the 3-dot menu in the header
  - long press on one of the History items and click at the 3-dot menu in the header

I am not sure if this particular feature is available everywhere but look for the "Articles for you" at the homescreen;

- Look at the 3-dot and long press menu of:

  - 3-dot menu of one of the "Articles for you"
  - long press menu of one of the "Articles for you"

- Look at the long press menu of:

  - Top Sites

- Look at the long press menu of:

    - long press on a link in the website; look at the pop-up menu

 
**I see a pattern in all the above mentioned menus here.**


And from your comment it seems I was not clear on what I am talking about here. As mentioned in the https://github.com/mozilla-mobile/fenix/issues/11716#issuecomment-660650950 I want the menus to be like how Chrome browser is behaving.

Should you increase the menu sizes (minimum or otherwise) a bit more? Should you give a pattern to them like how Chrome browser is doing? Should you give them a static 100% width all the time? or Change them dynamically based on the amount of text displayed? I am sorry, but I cannot give answers to them. I am expressing the "feeling" towards the design I am seeing in Fenix and that feeling says that something is wrong with Fenix. This is as clear as I can get. 



Thank you. :)

**Comment by brampitoyo** [comment]
@apbitner Thanks for pinging me on this issue. This still needs UX feedback.

## Main menu

This menu contains icons before the text. After the text, it can either contain icons, toggle, or nothing at all.

| New Tab Page | Webpage | Webpage → Submenu |
| --- | --- | --- |
| <img width="240" src="https://user-images.githubusercontent.com/51007/91002003-7cc7ce80-e621-11ea-8b19-5c6075b33648.png"> | <img width="240" src="https://user-images.githubusercontent.com/51007/91002008-82251900-e621-11ea-9224-27820520b61a.png"> | <img width="240" src="https://user-images.githubusercontent.com/51007/91002011-85b8a000-e621-11ea-9d05-a973c0a09a28.png"> |
| 228dp | 240dp | 240dp |

### Suggestions

- Set a new `min-width` value that applies to all main menus: 240dp
- Keep the same `max-width` value: 280dp

This will ensure that main menus are wide by default. For languages with longer strings than English, these menus will have consistent width (even though it could be wider than 240dp)

Remember: what matters isn’t the width in and of itself. It’s the _consistency_ of width that appears when you use a language.

## All other menus

These menus only contain text. They appear in many places.

| New Tab Page → Top Sites | New Tab Page → Collections |
| --- | --- |
| <img width="240" src="https://user-images.githubusercontent.com/51007/91003871-a9321980-e626-11ea-9a40-f7cdceb22c68.png"> | <img width="240" src="https://user-images.githubusercontent.com/51007/91003885-b3ecae80-e626-11ea-879d-47a5a95558bf.png"> |
| 166dp | 163dp |

| Tab Tray |
| --- |
| <img width="240" src="https://user-images.githubusercontent.com/51007/91003898-ba7b2600-e626-11ea-96dd-9606c7ed08f5.png"> |
| 158dp |

| History | History → Edit |
| --- | --- |
| <img width="240" src="https://user-images.githubusercontent.com/51007/91004129-6d4b8400-e627-11ea-9ce8-194ba9b43a91.png"> | <img width="240" src="https://user-images.githubusercontent.com/51007/91004214-a7b52100-e627-11ea-893b-b310d63c427e.png"> |
| 250dp | 196dp |

| Bookmarks | Bookmarks → Edit |
| --- | --- |
| <img width="240" src="https://user-images.githubusercontent.com/51007/91004277-d7fcbf80-e627-11ea-846c-c1f4bc174c83.png"> | <img width="240" src="https://user-images.githubusercontent.com/51007/91004301-e519ae80-e627-11ea-894f-7b74e192f384.png"> |
| 250dp | 196dp |

| Settings → Search |
| --- |
| <img width="240" src="https://user-images.githubusercontent.com/51007/91004505-7852e400-e628-11ea-96a6-0e79f925ce5f.png"> |
| 112dp |

| Settings → Logins and passwords → Saved logins | Settings → Logins and passwords → Saved logins → Individual item |
| --- | --- |
| <img width="240" src="https://user-images.githubusercontent.com/51007/91004519-8274e280-e628-11ea-91fc-8fe1b0a52d39.png"> | <img width="240" src="https://user-images.githubusercontent.com/51007/91004516-80128880-e628-11ea-8b6e-736422518ed4.png"> |
| 250dp | 196dp |

### Suggestions

- Set a new `min-width` value that applies to all text-only, non-main menus: 180dp
- Keep the same `max-width` value: 280dp

180dp `min-width` isn’t perfect by any means, but it’s the best compromise for scripts tend to have the same or shorter strings compared to English. Included in this list are some of the most widely-used scripts: Chinese Traditional + Simplified, Indic Scripts like Hindi, Bengali, Marathi, Telugu and Tamil, Arabic, Japanese, etc.

For scripts that tend to have longer strings compared to English (this also includes many widely spoken languages: German, French, Italian, Spanish, Portuguese, Russian), the menu will scale up. Unfortunately, in their case, it won’t be as consistent as we like them to be.

Unfortunately, there’s not a single perfect solution that works in all case!

To our contributors: I’m curious to hear your opinion on these suggestions. What are your thoughts?

**Comment by Mugurell** [comment]
Thank you Bram for the suggestions!
Since there are many people interested in this I'd say hold a few more days until getting to implement this to hear possible feedback.
