### ISSUE TITLE
FNX-12703 ⁃ [Feature request] Add a search button in the Add-ons Manager.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11722]
Right now there're only a few extensions so it's easy to know what add-on are installed and can be easily managed but when more add-ons become available let's say 50 or even 102 as the current "Recommended Extensions" are it'll become harder to manually search each add-on and manage it. So add a search feature in the Add-ons Manager.

**Comment by Amejia481** [comment]
cc @brampitoyo

**Comment by brampitoyo** [comment]
@SS1113 Thanks for your comment. In the future, we plan to move installation of all non-featured add-ons to AMO, so the Add-ons Manager page would never feature more than – let’s say, between 20 to 30 add-ons at a time.

Since AMO already has a search function, and the number of add-ons listed on Firefox Preview is never going to be overwhelming, I don’t think that we should have a search function in our manager.

**Comment by SS1113** [comment]
@brampitoyo I want make another argument if you may allow.

So let's say that I have installed 50 add-ons instead and I want to search for  a specific add-on in those 50 add-ons don't you think adding a search function would be really useful in this situation since I can type in a few letters and it'll bring me the needed add-on instead of searching the needed add-on manually through scrolling, just like how the stock Android does; if I type in something I want to search it'll bring me the app I have installed and if it isn't installed and if I press the search button it'll take me to the Play Store where the search query I entered is searched in the Play Store.

I hope you think about what I'm saying. Thank you.

**Comment by SS1113** [comment]
@brampitoyo sorry for tagging you again but I haven't received any reply. I really do think that this feature should be added. So please have a look at my [comment](https://github.com/mozilla-mobile/fenix/issues/11722#issuecomment-647224474) again. _Please..._

**Comment by brampitoyo** [comment]
@SS1113 Instead of implementing a search function outright, we should consider other solutions of sub-dividing the page, so that when there are many add-ons available to install, they are organised in a helpful way.

Think, perhaps, about having 2 in-page tabs that divide add-ons into recommended vs. installed. In each, you can further sort alphabetically, by last used, last updated, etc. This is similar to Google Play’s “My apps & games” section.

Would that help solve some of your problem?

Are you aware that we don’t have an add-ons search function on desktop?

Do you know that most of our users don’t install many add-ons (in most cases, it’s only 1)?

Either way, we will find a time to deal with this issue when we have enough installable add-ons – enough in quantity to make readability and management a problem.

Thanks for bringing this issue into our consideration!

**Comment by SS1113** [comment]
@brampitoyo 

>Are you aware that we don’t have an add-ons search function on desktop?

I am aware of that. I grew up in an environment where Desktops weren't common, I'm a mobile-first user. So anything that I say is oriented towards mobile users. I don't think design choices that are followed on desktop should always be followed on mobile as well.

>Think, perhaps, about having 2 in-page tabs that divide add-ons into recommended vs. installed. In each, you can further sort alphabetically, by last used, last updated, etc. This is similar to Google Play’s “My apps & games” section.

That might be helpful. But I still think having a search functions would be useful in that case as well since recently installed, recently used, and last updated, ect. change all the time so that'll confuse the users if the add-on that was there in a particular section isn't in that section after some time, in this case they will need a search function otherwise they'll have to search it manually by scrolling.

(BTW, I don't use Google Play to search my apps, I have a search bar in my app drawer for that ( and I use it extensively). And I never look at those other metrics except the recently updated apps section and that too only up to 4 or 5 app. They have never been useful for me).

>Do you know that most of our users don’t install many add-ons (in most cases, it’s only 1)?

Okay, that was really surprising to me! if most of your users don't install more than 1 add-on then what I'm suggesting won't be useful to them but it still might be useful to others who install lots of add-ons, I already have 5 add-ons installed out of the 6 available add-ons. I also plan to install the upcoming add-ons that you'll support in Fenix such as Privacy Possum, YouTube High Definition, and Decentraleyes as well. So that already makes them 8 add-ons out 9 supported add-ons. if I keep adding then I don't know how many I'll install (of course I'll need to balance and limit the amount of installed add-ons as it'll impact browser's performance).


>Either way, we will find a time to deal with this issue when we have enough installable add-ons – enough in quantity to make readability and management a problem.

Of course, I have faith in your development team since I already I'm love with what you've built. But I don't know if I'll be there when you build this feature and try to solve the problem of number of installed add-ons. That's why I'm filing this issue now itself so I can give my feedback now  before it being built into Fenix. 

Thanks for listening what I had to say about all of this. :)

**Comment by yoasif** [comment]
@brampitoyo I generally agree with you here, with not wanting to solve a problem that doesn't exist yet, but I just wanted to point out that I filed this bug two years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1499500 :wink:

**Comment by SS1113** [comment]
@yoasif I'm glad that there're some users who share the same idea with me!
(Desktop or mobile doesn't matter, I use Firefox on both platforms!)

I have looked at the issue in Bugzilla and it really makes me think that I already tried to do something similar in the past but when I pressed `Ctrl+F` there was nothing happening, I was even unable to find the "Find in page" in the hamburger menu on desktop. I always wondered about it. This must be changed!

Right now it is really frustrating to find each add-on manually (both on desktop and eventually would be on mobile as well!).

Locking/not providing the search functionality was definitely not a good choice on desktop. It needs to change now,I  mean, what's wrong with having a search function to search the installed add-ons, I don't get the idea at all here!
I really need a search function no matter what anyone says! This was already frustrating on desktop and it'll also become the same thing on mobile as well if left like this!

Please also think about the users who install more than one add-on as well. _Please_
