### ISSUE TITLE
FNX-12725 ⁃ [Bug] Easy to overlook FxA sign-in in Settings screen (UX question)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11745]
## Steps to reproduce
* Open Settings trying to sign in to FxA

### Expected behavior
FxA sign in is obvious

### Actual behavior
FxA sign in is special compared to other settings: it's a box at the top. I overlooked this because in at least one context in Android, that box normally has information I don't care about. I spent a while scanning the settings items before I found Sync. For example:
![image](https://user-images.githubusercontent.com/759372/85060187-a95ef600-b159-11ea-8d75-7bdbcc9f2675.png)

Android settings:
![image](https://user-images.githubusercontent.com/759372/85060205-b0860400-b159-11ea-9b00-55c171155511.png)

In the Android settings, that space is used to convey "active" information. For me, I intentionally enabled do not disturbed and set a time to disable it. I know I can access it from the notification tray. I know how to find it deeper in settings if I need it. The box isn't really useful to me so I always overlook it.

However, I can see the use case where a special box at the top is useful for non-power users: if I accidentally enabled Do Not Disturb and didn't know how to disable it, it's useful for it to be the top thing in Settings. So perhaps this problem just affects me and other power users and isn't useful to change the UX over.

### Device information
* Android device: P2
* Fenix version: Nightly 200618

**Comment by yoasif** [comment]
FWIW, Brave puts this in the "Advanced" section of their settings, but I think General makes more sense for Fenix. Chrome does what Fenix does once you have synced your account. 

Chrome also does the same thing as Fenix when you aren't yet signed in: 

![signal-2020-06-18-151722_002](https://user-images.githubusercontent.com/152493/85062673-e08fd000-b176-11ea-90b5-9fea8f4aa740.png)


Closing the ad makes it look more like a traditional settings UI:

![signal-2020-06-18-151722_001](https://user-images.githubusercontent.com/152493/85062686-e4bbed80-b176-11ea-9fe7-b19c354eb99d.png)


Sync gets its own section in Firefox desktop preferences, but the UI is pretty different, so I'm not sure much can be learned here.

**Comment by AmyYLee** [comment]
Assigned to @brampitoyo for feedback

**Comment by brampitoyo** [comment]
Hi @mcomella, our intention was to make the Sync section stand out quite a lot more than the rest of Settings, so it can’t be missed.

However, some users prefer to look at the list item directly, skipping the highlighted area. In their case, the area up above is miss-able precisely because it’s highlighted. If we just put it as a regular-looking list item, it will be scanned and thus won’t be missed.

Unfortunately, there’s no perfect solution to this problem

1. Make it too similar to other items, and we risk missing a lot of users who are only mildly scanning
2. Make it different from other items, and we risk missing users who prefer to scan a list directly while skipping other highlighted elements

When making our initial decision, we were banking on more users being in the first bucket than the second.

I would say that this isn’t a problem for the time being.

**Comment by mcomella** [comment]
Sounds good to me - thanks for thinking through this and the explanation! :) I hope these types of UX concerns I have are useful (and let me know if not so I can be less disruptive!).

**Comment by brampitoyo** [comment]
@mcomella It’s super useful! We’re almost always working at a detailed level, so details that would be obvious to users who have “more general” perspectives would be missed.
