### ISSUE TITLE
[Bug] Keyboard never pops back up after being dismissed on certain textboxes

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11785]
## Steps to reproduce
Go to www.Onlinegdb.com/online_c++_compiler
click on the centre text box 
keyboard appears
press back
click again on the centre text box

### Expected behavior
Keyboard appears. Note that for most other text boxes this is the current behaviour

### Actual behavior
Nothing. 

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by sheikh-azharuddin** [comment]
Works fine with gboard

**Comment by Diana-Rus** [comment]
Hi, I can reproduce the issue on latest Nightly 6/22 with 
- Sony Xperia Z5 (Android 7) - default keyboard
- Samsung Galaxy S9 (Android 8) - default keyboard (Samsung keyboard)
- Samsung Galaxy S9 (Android 8) - Gboard

Note:
- With Sony Xperia Z5 (Android 7), after tapping the first time on the text box the keyboard flickers as it seems that it wants to enable the caps lock of the keyboard, the same happens if you want to trigger again the keyboard(in case you did not leave a couple of seconds until the flicker stops) -check **Sony GIF**.
- With Samsung Galaxy S9 (Android 8) the default keyboard is re triggered after the first back action of the device button
- With Samsung Galaxy S9 - Gboard - it's inconsistent, after the first back action from device button, it can either not be triggered or it flickers(check GIF)
- After a refresh of the page the user can trigger again the keyboard

**Sony Xperia Z5 - GIF**
![20200622-124517](https://user-images.githubusercontent.com/49859863/85275491-14c20400-b489-11ea-8f76-39ab13755b0b.gif)
**Samsung Galaxy S9 - Default keyboard - GIF**
![20200622-125422](https://user-images.githubusercontent.com/49859863/85275622-420eb200-b489-11ea-8a90-79cbeaea14bd.gif)
**Samsung Galaxy S9 - Gboard enabled**
![20200622-125628](https://user-images.githubusercontent.com/49859863/85275812-9154e280-b489-11ea-95c5-662c97199ba3.gif)

**Comment by makotokato** [comment]
@s-ankur, Does central text box mean code editor or "Command line arguments:" text box?

**Comment by s-ankur** [comment]
I meant the code editor

**Comment by makotokato** [comment]
Thanks, this is GV issue. I look this via https://bugzilla.mozilla.org/show_bug.cgi?id=1658948
