### ISSUE TITLE
FNX-12775 ⁃ Crashing on webpage Microsoft Edge Insider News

### ISSUE THREAD

**Issue by atranel** [mozilla-mobile/fenix#11792]
Eveytime I check this website, Fenix crashes.
https://www.microsoftedgeinsider.com/en-us/whats-new

**Comment by sheikh-azharuddin** [comment]
Works fine here...

**Comment by atranel** [comment]
> Works fine here...
Well, other browsers have no problem. It crashes tab or whole browser.

**Comment by SS1113** [comment]
The whole browser crashes/force stops for me.

Device: Motorola One Power, Android 10.
Fenix: version 5.2.

**Comment by RealGJ** [comment]
Go to settings > about Firefox > crashes > and share that crash log here

**Comment by SS1113** [comment]
@RealGJ it is not there.

**Comment by Diana-Rus** [comment]
Hi, i managed to reproduce the crash with Samsung Galaxy S9 (Android 8) on latest Nightly 6/22 

Note:
- With Sony Xperia Z5 (Android 7) will not crash, after a couple of seconds of loading, the about:blank page will be present
- With Google Pixel 3 XL (Android 9) It will not crash, the page will load correctly

Crash Signature: libc.so@0x4b7f0 | libhwui.so@0x869ee
Crash link: https://crash-stats.mozilla.org/report/index/f23a137e-784e-47b6-aac4-216080200622#tab-details

This issue is the same with #6743. I think it's ok to close this issue and continue the investigation on the other one.
