### ISSUE TITLE
integrate ETP shield icon with the security lock icon

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11812]
### What is the user problem or growth opportunity you want to see solved?
Please remove ETP shield icon from address bar and integrate to the lock icon and it's menu similar to microsoft edge.
This will increase the space for website address and the ui will look less clutter and modern.
Attaching screenshot. Don't think my request as comparison to edge. It's just a request to enhance the beauty of the browser just like other browsers but with much more privacy protection.

### How do you know that this problem exists today? Why is this important?
The sheild icon occupies too much space leaving less for the website address. Specially with reader icon added the space is reduced further

### Who will benefit from it?
All users.

![6985](https://user-images.githubusercontent.com/58127841/85289746-6f5a6080-b487-11ea-816a-524bb25fdcc4.png)

![Screenshot](https://user-images.githubusercontent.com/58127841/85289778-78e3c880-b487-11ea-9283-9a518d0bd942.jpg)UNITO-UNDERSCORE!20200622-182341!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2450)

**Comment by AmyYLee** [comment]
@sheikh-azharuddin Thanks for the feedback. This is being considered.

**Comment by SS1113** [comment]
@AmyYLee I have an argument to make if you are considering integrating this feature into Fenix.

How do you handle the cases where the website's **SSL certificate has expired**. If we show the ETP's shield icon on the lock icon in this case then users may get confused and think the website is perhaps secure and there's nothing wrong with the website, since the shield icon is always perceived as they are being protected from something. They may think that the is website is indeed secure! 

This is how it shows now and if we integrate the ETP's shield icon with the lock icon then I think it'll confuse the users:

![Screenshot_20200624-131625](https://user-images.githubusercontent.com/42088907/85518663-196bf100-b61e-11ea-9215-ad076318accf.png)

**Comment by sheikh-azharuddin** [comment]
You need to handle like chromium browser such as edge...see the screenshot

![7009](https://user-images.githubusercontent.com/58127841/85519340-de9f9400-b5f0-11ea-873c-3acd036fb223.png)

**Comment by SS1113** [comment]
Yeah, that may work but the UX about integrating the ETP's icon with the security lock icon needs to be handles very cautiously and clearly convey the state of the SSL certificate at a glance when users look at the lock icon since users may not be willing to read the instructions that the Fenix has told them.

Nevertheless I think that the idea of integrating ETP's shield icon with the security lock icon is really amazing and it'll save a lot space in the address bar since it has become/will become a rarity.

**Comment by sheikh-azharuddin** [comment]
The page itself says secure connection failed/site not secure with big bold  red icon....if the user is fool to ignore that and still depend on the lock icon can't comment 🤐

**Comment by SS1113** [comment]
> The page itself says secure connection failed/site not secure with big bold  red icon....if the user is fool to ignore that and still depend on the lock icon can't comment 🤐

"Power users" or *advanced users" may willing to read it. But the average use won't care about it! They'll just click OK, OK, OK..... And then Yes and access the website. Handling security lock icon correctly is really important and it think this is why it is still kept even after having the big "secure connection failed" message! They don't care! And since only the partial website address is displayed with the omission of `https://`and `www` it has already made it somewhat harder to find if the website the user has visited is the one they intended to go to. Just imagine if a phising website is trying to act like the original website here! And if we mess up with the SSL security lock too, then I don't know what will happen!

And in-between they're some users who are not native to English language and don't know that much of English and browse with the English language set as the browser's and phone's default language. They don't know and will not read what is present to them. What will you argue in this case? I have witnessed several cases like this firsthand!

**Comment by sheikh-azharuddin** [comment]
You are too much overthinking...this implementation is already there in other browsers such as chrome/edge.... Even if it is a new user/noobie user they will use the default browser only which is chrome... So why someone will explore other browser like firefox unless they know little bit about security and privacy issue...
So much concern about user, my argument is still on why replace green security icon with plain white one?
Users have learned since the beginning green is secure, red is insecure.... So if you are really concerned about user why not bring that old implementation... 

All things apart we can have a red security icon with etp icon integrated same as edge that will solve the problem

**Comment by cadeyrn** [comment]
> my argument is still on why replace green security icon with plain white one?
Users have learned since the beginning green is secure, red is insecure....

https://blog.mozilla.org/security/2019/10/15/improved-security-and-privacy-indicators-in-firefox-70/

The article is about the Desktop Firefox but the same reasoning applies to Fenix as well:

> The formerly green lock icon will now become gray, with the intention of de-emphasizing the default (secure) connection state and instead putting more emphasis on broken or insecure connections.

**Comment by SS1113** [comment]
>You are too much overthinking...

Yeah, this is absolutely possible with me! 😂😂😂

But I'm saying _not_ saying to not go ahead with this feature but instead handle it with with some cautiousness. Let's see what **UX** comes up with.

Thanks for suggesting this feature!

**Comment by sheikh-azharuddin** [comment]
@cadeyrn 
Lol... contracting statement...one side you are saying people will ignore all security warning displayed on the webpage and will solely rely on the security icon....if that is true is it not important to highlight that properly with color??

How much true difference between secure and non secure lock icon existing implementation? Just a simple slash difference! Is it that much noticeable? With current icons there is high chance user will ignore the icon...
I suggest that red globe icon for insecure page with etp sheild icon like edge

![7013](https://user-images.githubusercontent.com/58127841/85529658-d0577500-b5fc-11ea-8ac3-53d33763fb58.png)
![7015](https://user-images.githubusercontent.com/58127841/85529669-d2b9cf00-b5fc-11ea-9729-e9419446d6f5.png)

**Comment by cadeyrn** [comment]
> Lol... contracting statement...one side you are saying people will ignore all security warning displayed on the webpage and will solely rely on the security icon....

No, I didn't say that. And there is also no "contracting statement" in my comment. I quoted from Mozilla's security blog why the lock icon is no longer green on Desktop Firefox and therefore why it shouldn't be green in Fenix. More than 84 percent of page loads of Firefox users are via HTTPS, so the lock would be almost always green and this wouldn't be a "highlighting" at all. I never said that the icon for unsecure connections could not be improved in Fenix. But again: This issue is about something entirely different, the color of the lock icon is not the topic.

**Comment by sheikh-azharuddin** [comment]
> > Lol... contracting statement...one side you are saying people will ignore all security warning displayed on the webpage and will solely rely on the security icon....
> 
> No, I didn't say that. And there is also no "contracting statement" in my comment. I quoted from Mozilla's security blog why the lock icon is no longer green on Desktop Firefox and therefore why it shouldn't be green in Fenix. More than 84 percent of page loads of Firefox users are via HTTPS according to Firefox telemetry. I never said that the icon for unsecure connections could not be improved in Fenix. But again: This issue is about something entirely different, the color of the lock icon is not the topic.

Oops sorry it was SS1113...😝

**Comment by SS1113** [comment]
>you are saying people will ignore all security warning displayed on the webpage and will solely rely on the security icon....

I'm saying it because they might have been advised to look for the **lock icon** or **`https://`** from the online articles they have read or from their "power user" friends; if the lock icon is there then the website is secure otherwise not it is not. Any discrepancies in that icon _will_ confuse the not so "power user" user.

Thanks for giving some really useful comments and giving constructive feedback on this, I'm sure the **UX** _will_ consider it! :)

P.S. I'm tired of commenting now! I'll go and take some rest! (But I'll be back with full energy though, so be ready! 😂😂😂).

**Comment by sheikh-azharuddin** [comment]
@SS1113 I am always ready for any argument/discussion...😎
Let's have a offline discussion in telegram once you get back your energy😈
What say? Keep comments clean here....

**Comment by SS1113** [comment]
@sheikh-azharuddin Just to be clear, these type of arguments are necessary, the issue needs to be filled with this type constructive feedback. So don't hesitate to add any comments you have here if you feel it is necessary (I'm sure the developers will agree with me here).

Going to Telegram to discuss this will hide the use cases and the feedback we are discussing here and the **UX** team won't be able to find it! 

I hope I made it clear.

That last line was a joke though.

Thanks! :)

**Comment by kbrosnan** [comment]
This is largely done. We chose not to overlay the two icons.
