### ISSUE TITLE
FNX-12820 ⁃ i want to old tabs

### ISSUE THREAD

**Issue by ningsibuqu** [mozilla-mobile/fenix#11834]
the new tabs very hard to use,please.

**Comment by SS1113** [comment]
@ningsibuqu Can you please explain how is the experience hard compared to the new Tabs Tray? And how do you think the experience can be made better? So it can be improved.

**Comment by ningsibuqu** [comment]
> @ningsibuqu Can you please explain how is the experience hard compared to the new Tabs Tray? And how do you think the experience can be made better? So it can be improved.

i just dont like secondary menu. so...

**Comment by SS1113** [comment]
>i just dont like secondary menu. so

@ningsibuqu That doens't contain any constructive feedback. All browers I know have the secondary menu to handle tabs because as having them in homescreen will clutter the available space and it'll make harder access other features of the browser that are on homescreen like Top Sites, Collections, etc.  Can you be a bit more descriptive about why you don't like it.

**Comment by B0pol** [comment]
Not the op and I don't old tabs back, but I want this one to be improved.

From most to less annoying

- almost unable to use when you have +8 tabs. I want to scroll and pick the tab at top, it closes the drawer
- when I have +8 tabs, it takes way top much size because of thumbnail previews. I like preview thanks to bottom nav bar, but this update is one step backwards with tabs way too high when you have too much tabs
- when you have lots of tabs, preview don't work
- when I have 0 tab, it stays open
- when I have 0 tab, it shows 0 instead of + (+ was the behaviour of 5.1.1 and before)
- bug https://github.com/mozilla-mobile/fenix/issues/11099

I'd have preferred fenix team to wait and fix more bugs before force releasing it. 
I liked when I had it in the secret settings, or on nightly, but there is too much bugs imo 

Therefore (offtopic) I went back to firefox non-preview 68.9.0 (also because of #10477 with dynamic nav bar released, bug https://github.com/mozilla-mobile/fenix/issues/11708 that affect custom tabs which I'm using a lot and is present in 5.2 version). It's sad because 5.1 was really great and didn't have all these bugs. I'll wait…

**Comment by ekager** [comment]
Please file specific issues about what you find difficult/broken so they can be triaged correctly.

**Comment by vrubleg** [comment]
@SS1113 Years ago browsers used a separate search bar. Now they use address bar as a search bar. If nobody is brave enough to try something new, things won't be ever improving.

**Comment by vrubleg** [comment]
The new ticket about the same thing is #11833

**Comment by SS1113** [comment]
@vrubleg I'm not resisting the change, changes do happen but those changes _must_ outweigh the negatives they bring with them! 

Why do you think most of the apps follow the same Material Design guidelines across the Android app ecosystem? because if we change that it'll feel alien to the users and will become difficult to navigate. Even the Fenix itself follows those guidelines.


I have presented my arguments about why the tabs shouldn't brought to homescreen of Fenix, and if you any constructive feedback about why it shouldn't be so then please give your point of view.

**Comment by vrubleg** [comment]
I think it is better to discuss it in the #11833. I already provided more information there. The main point: it reduces complexity without losing functionality the same way as the new address bar reduced complexity without losing functionality.

There are no other important things than tabs. Tabs are the most important part of the browser, and they must be really easily accessible, as much as possible. Collections and top sites could be removed from the browser completely. Just pin your top sites to the top of the list of the tabs, and allow to reorder opened tabs and making group of them (by moving one tab on another). This way, you keep the most important things on the first places, and won't loose any other functionality you have on the main screen now.

**Comment by SS1113** [comment]
@vrubleg 

>Tabs are the most important part of the browser

I completely agree! They need to be really easy to use. But I also say that I like the new tab tray layout. It makes the homescreen really clean. The **Top Sites** and the **Collections** have become really important features me! And don't want to have my homescreen clutter with the tabs.

I'm moving to the linked thread, Seems like some really interesting things are going on there!

**Comment by toluschr** [comment]
The new layout is so cumbersome, I don't even understand how I'm supposed to use it.

**Comment by vrubleg** [comment]
@toluschr same issue. I'm a programmer, and I'm always confused with this new UI. Downloaded old v5.1.1 and going to use it next few years until it works on most websites.

**Comment by MrPotatoLord** [comment]
It takes longer to open a new tab, old version was great.

**Comment by toluschr** [comment]
> It takes longer to open a new tab, old version was great.

How am I supposed to get to my collections on the home page?

**Comment by myfreeweb** [comment]
> I want to scroll and pick the tab at top, it closes the drawer

This is exactly the most frustrating part of the new drawer!
