### ISSUE TITLE
[Bug] Cursor movement doesn't work properly

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#11847]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1647139 - See movie on Bugzilla

User Agent: Mozilla/5.0 (Android 9; Mobile; rv:77.0) Gecko/77.0 Firefox/77.0

Steps to reproduce:

I tried to move the cursor, both in the URL bar and in text fields like the one I'm currently writing this.

Actual results:

Cursor just moves two times, then always gets reset instead of continuing to move in one direction.

Expected results:

Cursor should be able to move like I press the cursor buttons - without resets.

**Comment by hm-kay** [comment]
I am experiencing the same problem since a while. Maybe the following details add to a better understanding where the problem could be located.

It occurs in text fields and sometimes in the address bar. 

I cannot move the cursor to the left as expected, if the left cursor button is pressed and released repeatedly. Instead, it jumps to the end of the word and moves back and forth one or two characters to the left and to the right alternatingly.

If I press the right cursor button, the cursor either moves to the end of the word, or makes two quick movements, the first to the end of the word and the second to the beginning of the next word.

However, if I hold the cursor button down, the cursor moves as expected, in both directions.

![CursorMovementFaulty](https://user-images.githubusercontent.com/70947449/92468671-d01a4f00-f1d3-11ea-8165-63957d5ec08a.gif)

I am using the integrated on-screen-keyboard (Android Keyboard AOSP) with optional Cursor Keys.

![Screenshot_20200908-121355_LineageOS_Settings](https://user-images.githubusercontent.com/70947449/92464016-d5c06680-f1cc-11ea-8c1c-5d71e1603bde.png)

The behaviour does also occur if I try to move the cursor using hardware volume buttons

![Screenshot_20200908-121329_LineageOS_Settings](https://user-images.githubusercontent.com/70947449/92464118-02747e00-f1cd-11ea-8782-4396c66d48ea.png)

The cursor buttons do work flawlessly with every other application.

Pixel 1 (Sailfish)
Lineage 17.1 (The problem occured also before I switched from Lineage 16 to 17)
Fennec F-Droid 68.12.0 esr
