### ISSUE TITLE
[Bug] Reader mode only appears on switching tabs on certain pages due page not meeting the minimum amount of text

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11916]
## Steps to reproduce
Go to https://en.m.wikipedia.org/wiki/Academy#Academic_personnel

### Expected behavior
Reader mode option appears when the site loads

### Actual behavior
Nothing, even after waiting for some time.
You can switch tabs and come back to find the option is available

### Device information
* Android device: Asaus Zenfone
* Fenix version: Nightly

**Comment by csadilek** [comment]
For this we'd need to dig into readability.js. Our logic is here is the same as in Fennec, but the readerable check is known "to produce both false positives and false negatives". It's not clear why this would behave differently for some pages. My suspicion is that `isNodeVisible` lambda that's passed to `isProbablyReaderable` is causing this (returning false):

Fennec: https://searchfox.org/mozilla-central/source/toolkit/components/reader/Readerable.js#47
Fenix: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/readerview/src/main/assets/extensions/readerview/readerview-content.js#L36

**Comment by B0pol** [comment]
almost all pages on support.mozilla.org

@csadilek said

> Reader mode is a web extension in Fenix and we have a few restricted domains for which content scripts won't run for security reasons (just a few mozilla.org and firefox.com), but support.mozilla.org is one of them. That's why reader mode doesn't work in this case.

but also

> If you have other pages for which reader mode works in Firefox Desktop or previous versions on Android, please leave a comment on #11916

support.mozilla.org is in this case, the reader mode works in Firefox Desktop and with fennec. I don't see why it should be dropped, and if it should, then it also should be dropped on desktop.

**Comment by cadeyrn** [comment]
> I don't see why it should be disabled, and if it should, then it also should be disabled on desktop.

That was just explained in the paragraph you quoted The reader mode functionality is provided by an extension in Fenix and content scripts of extensions are not allowed to run on support.mozilla.org. The reader mode functionality is not an extension in Fennec and Firefox for Desktop.

**Comment by opusforlife2** [comment]
I GOT IT I GOT IT.

Reader Mode must have a minimum threshold for the quantity of text on the page to be considered suitable for converting.

On the mobile site of Wikipedia, text is hidden behind expandable headers. On pages where the intro at the top is short, Fenix doesn't show the icon, because the headers are collapsed by default. If you open a header with little text in it, it _still_ won't appear when you switch back to the tab. But if you open a header which has sufficient quantity of text in it, then come back to the tab, the icon will appear.

Take these examples:

- https://en.m.wikipedia.org/wiki/Greeting - Has a large enough intro. Shows the icon upon opening the page for the first time.
- https://en.m.wikipedia.org/wiki/Hello - Has a tiny intro. Doesn't show the icon for the first time. Doesn't show the icon even if you expand the "Early uses" header. But it _does_ show the icon when you expand the "Etymology" header.

**Comment by kbrosnan** [comment]
See https://github.com/mozilla/readability/issues/503 for similar problems with short paragraphs.

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by mariansima** [comment]
This issue was reproduced on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by opusforlife2** [comment]
Yo, stale bot. Please reopen.
