### ISSUE TITLE
FNX-12936 ⁃ How to download Firefox Preview .apk file from GitHub?

### ISSUE THREAD

**Issue by Rumpotkimhy** [mozilla-mobile/fenix#11933]
Cannot see a current .apk file for the last version

https://github.com/mozilla-mobile/fenix/releases

**Comment by ekager** [comment]
Sorry about that, I've just uploaded the apks for 5.2! Let me know if those don't work for you :)

**Comment by Rumpotkimhy** [comment]
Thank you very much, dear developer. :)

I hope that the apk file is always included in the future.

**Comment by SS1113** [comment]
@ekager this the reason why I said to not try to limit access to the APKs. I presented my arguments at length about it in the issue: https://github.com/mozilla-mobile/fenix/issues/11030. Please don't try to limit the access to APKs to users who are willing to install the early versions. You can see that if the users are coming to GitHub to download the APKs instead of downloading from Play Store you can be sure that they are willing to accept the risks of early software builds instead of not publishing the APKs you could put warning on the GitHub release page which will let them know that these are not tested with a wider audience and may not be stable enough. 

You can see that I already suggested users to close at least 2 issues same as this one asking for updated versions APKs, that makes it total of 4 issues on GitHub this is apart from the users who asking for the same on [/r/firefox](https://www.reddit.com/r/firefox) on Reddit.

Put a warning and let the users access the APKs.
