### ISSUE TITLE
Integrate Nimbus and implement bookmark icon experiment

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11987]
## User Story
As a user, I want to easily save a bookmark without getting sidetracked, so I can get the most out of my browsing session. 

According to Fenix Milestone 4 study: 
Many users wanting to save a bookmark, tapped on the ‘Bookmarks’ menu list icon instead of the ‘Add bookmark’ icon at the bottom of the menu. It is a sign the former is more easily discoverable than the latter. We should examine copy and organization of the menu to prevent users from making this mistake when attempting to add a bookmark.

### Acceptance Criteria
**Product acceptance criteria** 
* I know how to save a bookmark and can easily do it.

**Engineering acceptance criteria**
* Integrate Nimbus into Fenix to allow experimentation
* Create an experiment for the bookmark icon

**Comment by SS1113** [comment]
Okay. It'd be great if some of your studies were open and accessible all. I mean, I recently found out that most of the Firefox users only installed just one add-on at most from this https://github.com/mozilla-mobile/fenix/issues/11722#issuecomment-649227021. 


If I'm understanding this correctly you're saying that users are clicking "Bookmarks" 3-dot menu list item instead clicking on "Bookmark" icon at the bottom. I think this might be happening because uses who used Chrome/Chromium browser which don't feature icons in their 3-menu list items and have icons only at the top for saving a bookmark, page download, info and reload button. Having a filled star and an empty start icon might have also confused the users.

I think instead of modifying something related to the "Bookmarks" entry we can change that filled star icon to something else.

Or roll the menu list entries for "Bookmarks" and "History"  into a "Library" list entry we had a couple of versions ago and add another list entry that will say "Add to Bookmarks". But it'll also increase the amount of taps needed to view bookmarks or history.

**Comment by vesta0** [comment]
@ghost I think you are absolutely right. Users open toolbar and they see TWO :star:icon icons instead of ONE and possibly tap on the wrong one half of the time.

**Comment by violasong** [comment]
My current fix for this is changing the Bookmarks icon to be more different from the Bookmark icon. For the next step, grid-view menu, there's more flexibility for improving on this UI.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/55994/93911400-2f3d9080-fcb7-11ea-9f79-ad6900e6f408.png">

**Comment by amkcpu** [comment]
@vesta0 I would like to work on adding the new bookmark icon that @violasong proposed in the previous post.
@violasong Would you mind sharing the icon's XML data so I can add this?

**Comment by violasong** [comment]
Hi @amkcpu! Thanks for volunteering, although I think we need to work out some questions with this design internally. I'll update the issue when we have more details.

**Comment by liuche** [comment]
Some telemetry that we will need to measure:
Bookmark count
Probes that indicate when a bookmark is added by a user

**Comment by liuche** [comment]
cc nimbus work

**Comment by violasong** [comment]
Hypothesis: 
- Using the "Filled star with tray" icon for Bookmarks will help users differentiate between that toolbar item and the "Empty star" Bookmark action.

Success Criteria:
- Fewer users tap "Bookmarks" when they mean to tap the Bookmark action, which could be measured by more bookmarks created, or fewer instances of viewing the Bookmarks view without accessing a bookmark.

Results:
- If the new icon meets our success metric, we will use the new bookmark icon in the toolbar menu as well as other places where we might link to the Bookmarks view.
- We will obtain base metrics for measuring further changes to the toolbar menu. This work will happen in issue #14320.


<img width="551" alt="image" src="https://user-images.githubusercontent.com/55994/98763433-dae98f80-238e-11eb-9ef6-1fdeffcf02fc.png">

**Comment by eliserichards** [comment]
The initial Nimbus work has landed in AC:
* https://github.com/mozilla-mobile/android-components/pull/8948
* https://github.com/mozilla-mobile/android-components/pull/8261

**Comment by bifleming** [comment]
@eliserichards @gabrielluong is there still work to be done on the Fenix side for this? I see that it's not currently scoped to a sprint...

**Comment by gabrielluong** [comment]
> @eliserichards @gabrielluong is there still work to be done on the Fenix side for this? I see that it's not currently scoped to a sprint...

I think this is done. cc @jhugman ?
