### ISSUE TITLE
FNX-4865 ⁃ Rotating the display clears search input

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1198]
## Steps to reproduce
1. Enter a search term in the search bar.
1. Rotate the device to landscape.

### Expected behavior
The search term I entered should still be in the search bar.

### Actual behavior
The search bar has been cleared of input.

### Device information
* Android device: Nokia 3.1
* Fenix version: 1.0.1913

### Priority
I think this is a blocker.

**Comment by mheubusch** [comment]
@Verdi Does this need additional UX feedback or is this ready for eng?

**Comment by jatinkumarg** [comment]
Hey, I have added a PR (#1198).

Let me know if any changes are required.

**Comment by sblatz** [comment]
See https://github.com/mozilla-mobile/fenix/issues/1205#issuecomment-484186027 for why this is blocked.

**Comment by sblatz** [comment]
Sounds like @colintheshots is investigating bugs like this (namely how we can persist state with our architecture).

**Comment by colintheshots** [comment]
Blocked on #1994.

**Comment by lime124** [comment]
@vesta0 can this be a p1? this should be considered as data loss and be prevented if at all possible. also it looks like 1994 is a p1.

**Comment by vesta0** [comment]
@lime124 I agree. Changing it to P1.

**Comment by colintheshots** [comment]
I'm marking this QA Needed, but we may not have a build to test with until Monday as the Nightly is having build issues.

**Comment by bsurd** [comment]
Rotating from portrait to landscape or vice versa no longer clears the text. Tho it does to a select all action clearing the text if the user wants to input anything else. The user should remain in typing mode.. @jatinkumarg or @colintheshots could you have a look at this?

If tapping and continuing to type when hitting search it seems to crash the app. Rotating from portrait to landscape and back to portrait also crashes the app. I have logged that issue here: #2448

Removing the QA needed flag for now.

**Comment by vesta0** [comment]
The search input should remain in typing mode.

**Comment by sblatz** [comment]
I can no longer produce @bsurd's issue. Are you able to verify they're still happening on the latest nightly?

**Comment by bsurd** [comment]
Can confirm that the issue is no longer reproducible with the latest build (5/16). The search term remains in the input field and is no longer selected upon rotating the device.
