### ISSUE TITLE
[Bug] Fenix Nightly sometimes disappears from recent apps menu

### ISSUE THREAD

**Issue by nyanpasu64** [mozilla-mobile/fenix#11999]
## Steps to reproduce
Not sure exactly how to trigger the bug, but this occurs sporadically.

* Open Fenix and press the recent apps button. It's there as expected.
* Switch from Fenix to another app or the home screen (launcher), then open the recent apps menu.

### Expected behavior
Fenix remains on the recent apps menu.

### Actual behavior
Fenix is not in the recent apps menu. If you open Fenix again, it's still loaded in RAM, but will disappear from the recent apps menu as soon as you switch to the launcher or another app.

### Device information
* Android device: Moto G5 Plus, Android 8.1.0
* Fenix version: Nightly 200620 06:00 (this bug has been around for weeks, my version is about a week outdated, I'll update if it still happens)

**Comment by ebalazs-sv** [comment]
Hi! I can reproduce this issue on Nightly 200820 Build #2015759001 GV 81.0a1, from 8/20 with Motorola Moto G6 (Android 8).
### Steps to reproduce:
1. Launch Fenix and visit a website;
2. Crash Fenix with about:crashparent and restart the app;
3. Go to another app, Gmail;
4. Tap the Recent apps button;
### Expected behavior
Fenix is displayed in Recent apps.
### Actual behavior
Fenix is missing from the Recent apps. 

### Notes
![20200820_123021](https://user-images.githubusercontent.com/48799384/90753382-33097c00-e2e1-11ea-8475-2e9ffff4cd96.gif)


### Device information
- Android device: Motorola Moto G6 (Android 8), Google Pixel 4 (Android 10)
- Fenix version: Nightly 200820 Build #2015759001 GV 81.0a1, from 8/20
- This is not reproducible on Firefox Beta 80.0.1-beta.1, GV 80.0, from 8/15 and Firefox 79.0.5, GV 79.0.1, from 8/18.
