### ISSUE TITLE
FNX2-13025 ⁃ Don't close the keyboard while trying to search with another search engine that is below the keyboard

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12050]
While trying to search with another search engine other than the default one temporary, when I trying to scroll to select the search engine below the keyboard area by scrolling; the keyboard closes and when the search engine is selected I need to tap the search bar again to bring the keyboard focus again and click enter.

This can be improved if the keyboard doesn't close and instead the list of search engines can be scrolled without losing the keyboard focus, this way it won't lose focus and I can search with very few taps, currently it take too many taps to do a search with a search engine other than the default one. 

See the GIF:

![20200627](https://user-images.githubusercontent.com/42088907/85915927-3fbaa800-b83b-11ea-8653-8e6b61846612.gif)UNITO-UNDERSCORE!111543!

**Comment by brampitoyo** [comment]
@SS1113 

Currently, the process you’ve described looks like this:

- Tap on the address bar, keyboard opens
- Enter a keyword
- Tap “Shortcuts”
- Scroll down, keyboard closes
- Select a search engine
- Tap on the address bar again, keyboard opens
- Tap “Enter” key

Your proposed fix looks like this:

- Tap “Shortcuts”
- Scroll down, keyboard remains open
- Select a search engine (no need to tap on the address bar again to reopen the keyboard)
- Tap “Enter” key

However, this would make the behaviour of our “Search with” UI different from our search results UI, where the keyboard would minimise on scroll.

Today, the keyword you enter into the address bar will be shown as the first search suggestion, directly underneath. By simply tapping on this suggestion, you can perform a search without reopening the keyboard.

It seems like this feature would solve your problem? What do you think?

-----

If there is no solution other than making the keyboard reopen, we can do it at a different point in the process:

- Tap “Shortcuts”
- Scroll down, keyboard closes
- Select a search engine, keyboard opens (no need to tap on the address bar)
- Tap “Enter” key

Doing this will make the rest of the search suggestions less visible. If you want to scroll down the list for any reason, then the keyboard, which has just been opened, will be re-closed again.

**Comment by SS1113** [comment]
@brampitoyo 

What I am suggesting to do is; never close the keyboard.

Make the behaviour same in both the "Search results" UI and the "Search with" UI and allow the search suggestions list (including boomarks) and search engines' selection list to be scrolled without making the keyboard close. 

let's say I want to select a bookmark suggestion from the search suggestion list or after selecting a search engine, there will be suggestions to choose from other than the search suggestions from the search engine, if the suggested word from the selected search engine is selected then it will perform the search but if I want to select only a part of the bookmarked address or part  of the suggested word; right now it will go to the whole bookmarked address or search the whole search suggestion, what if I want to select it and edit it by clicking the ↖︎ button which the issue #8043 is already asking, in this case the keyboard needs to be open and if we make the keyboard open and close several times then it will annoy the users and they cannot predict when the keyboard will close or stay open as after using Fenix for over more than a year I'm having a hard time in predicting when it will close or stay open.

You may ask that how will the users know that there are still search or bookmark suggestions below the keyboard, in that case I will suggest adding a scroll bar indicator to indicate that there are further suggestions below the keyboard. 

At the end of the day, I am at the address bar because I want to type in something. There's no reason to close it until I finished typing/editing  whatever I wanted to search; be it a word suggestion from the search engine, selecting a search engine before a search is performed or a bookmark I want to edit before going to it.


---

If there is no solution other than making the keyboard reopen, we can do it at a different point in the process:

    Tap “Shortcuts”
    Scroll down, keyboard closes
    Select a search engine, keyboard opens (no need to tap on the address bar)
    Tap “Enter” key

This could work but as you say it will hide the other search suggestions and I have already said add a scroll bar to indicate that there are search suggestions below the keyboard allow and the list to be scrolled.

---


I am still with the suggestion of allowing the all sections' suggestions in the address bar be allowed to scroll (including the search engines' list) and add a scroll bar to indicate that there are still suggestions below the keyboard area without closing the keyboard.


I know this is some major behaviour I am asking to  change but to make it more intuitive, easy, predictable and make the existing process less frustrating, this is what I think should be done.

**Comment by ShatteredPixel** [comment]
Hi, I'm the reporter of this issue. Please let me know if you need more information.

Thanks! :)

**Comment by ShatteredPixel** [comment]
Hi, @brampitoyo I have gone through this again and I this the idea of never closing the keyboard is not that great since it is feeling a bit weird to me when I seriously think about it, since it is hiding other suggestions. Google translate, Solid Explorer, Material Files, Enpass, etc these are some of the apps that don't close the keyboard while something is typed and if this sort of behaviour is implemented in Fenix then it'd feel really weird as it'll take away half of the screen real-estate for the search suggestions and it's not worth it. I think we should keep the current behaviour as you are saying but the keyboard should pop-up when this 
↖︎ (Issue #8043) Is pressed in the future, okay?


What do you think? Have your thoughts changed since you made your comments or have any other ideas to improve the experience? 

But thanks a lot for listening to my suggestions. I'm really grateful for it. You can close the issue if you want now. Thanks again! :)

___


I had suggested to add a scrollbar to the tabs tray #11873 and I have noticed that Fenix currently lacks a scrollbar in almost every screen like, I won't suggest adding a scrollbar at the Fenix homescreen but don't you think they should a scrollbar in Fenix address bar's "Search With..." and Shortcuts screen, History, Bookmarks, etc.? Is it natural to expect a scrollbar in three situations? For example Vivaldi browser has a scrollbar bar in the address bar's suggestions for example. Don't you think this should be added?

Waiting for your thoughts on this.


Thanks.

**Comment by brampitoyo** [comment]
Hi @ShatteredPixel, you’re correct in writing that closing the keyboard on scroll is not a perfect solution. It’s only the best compromise, given the fact that the keyboard takes up so much space, and that scrolling up/down on the top-half of the screen all the time is not ergonomic. You either have to use two hands, move your hand up to reach the top-half, or strain your thumb.

Search suggestions can also get pretty long (history, bookmarks, open tabs, etc.). If most of the results are blocked by the keyboard, people may not be able to find the page that they want quickly. Or if they can, they will have to scroll quite a lot in the limited space provided.

Unfortunately, we cannot win against physics and biology!

## Keyboard up after tapping Refine (↖︎)

But we will, as you suggested, implement the behaviour where after you tap the Refine (↖︎) Icon, the keyboard will pop up again. Normally, the first three keyword suggestions are not covered by the keyboard – but in case people want to scroll down then go back up and refine, the keyboard will pop up again.

## Add scrollbar on different pages

To be honest, this issue hasn’t really entered our collective minds, so thanks a lot for filing them!

From doing a really quick look at other Google apps in Android, it seems that their scrollbar implementation is… all over the place.

- Doesn't have scrollbar
    - Settings
    - Google (but Google Settings does have a scrollbar)
    - News (but News Settings does have a scrollbar)
    - Drive (but Drive Settings does have a scrollbar)
    - Photos  (but Drive Settings does have a scrollbar)
    - Home
- Skinny, grey scrollbar
    - Chrome (but Chrome Settings doesn’t have a scrollbar)
    - Gmail
    - Messages
    - Hangouts
- Scrollbar with other designs
    - Contacts

We want to do two things here: look through Material Design Guidelines to see whether they have standard around scrollbar, and try to make Fenix as consistent as possible (given time, resource and platform limitations).

**Comment by sflorean** [comment]
Based on this [comment](https://github.com/mozilla-mobile/fenix/issues/12050#issuecomment-660814208) and the fact that the issue was closed, I will close this again.
