### ISSUE TITLE
FNX-4871 ⁃ Search term lost when tapping back into search field

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1205]
## Steps to reproduce
1. Search for anything (e.g. Firefox) and navigate to the search engine results page.
1. When on the search results page, tap the Fenix search field.

### Expected behavior
My search query, "Firefox" should be in the search field, and I should see search and history suggestions related to it.

### Actual behavior
My search query is gone and the url of the search engine results page is in the search field and it's the top suggestion.

### Device information
* Android device: Nokia 3.1
* Fenix version: 1.0.1913

### Priority
I think this is a blocker.

**Comment by sarentz** [comment]
This functionality already exists in A-C but it means that Fenix needs to start using the `feature-toolbar` to get this functionality.

It is unclear what the reason is for Fenix not using this component. Did @boek work on this earlier in the year?

**Comment by sblatz** [comment]
After quite a bit of work on this, I was able to narrow it down to being an issue with the way a-c is persisting search terms in their session. While I have a "hacky" implementation working for Fenix, I spoke with @pocmo, and he's going to fix this internally in a-c so that everyone benefits from the fix. 

This ticket will now be blocked on https://github.com/mozilla-mobile/android-components/issues/2771

**Comment by kbrosnan** [comment]
This is working as expected. Tapping into the address bar after performing a search brings back the search terms. Navigating to a new page no longer displays the search terms. Swipe killing the browser clears the search terms. Tested on a Pixel 3 and Galaxy S6.
