### ISSUE TITLE
[UX] Re-evaluate user’s starting point on return visits

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12062]
## User Story
As a user, I want to to have a choice in where I land when I re-launch the browser (e.g. Firefox homescreen, last open tab, custom URL, etc)

Product note: this is a recommendation from user research feedback. There is also performance considerations.

### Acceptance Criteria
* I can choose where my starting point is when re-launching the browser.

**Comment by BranescuMihai** [comment]
One slight disadvantage that I see is that with the tab tray feature and now this one, I feel like the collections feature will become even less visible to the users

**Comment by yoasif** [comment]
This is a desired feature (as you know) - see https://www.reddit.com/r/firefox/comments/i617id/any_way_to_make_firefox_on_android_open_on_my/

@BranescuMihai Collections has enough issues that I don't use them - we shouldn't keep user experience issues open just to promote a feature that isn't great yet.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

🚩 Flag added 

null

**Comment by yoasif** [comment]
In addition to UR, I am seeing a *lot* of feedback on this on social media and Play Store reviews. Even if the default is not changed (I would argue that it ought to be, because users expect state restoration as a platform convention), it really ought to be an option.

**Comment by yoasif** [comment]
Couple of points:

* it feels to me that the current behavior is intended to make it easy for people to choose to start a new session or to "continue" an existing session using collections
* this seems to be the reason that the top sites, address bar and collections are immediately available 

This feels like the wrong solution - we are interrupting a person's workflow in order to present our value, instead of making it easy to choose:

* we don't currently have a home button to allow people to easily get back to the home screen where collections/top sites are present
* search and tab tray is present on every screen, so that choice is already present
* collections don't need to only be present on the home screen (or at all!) - see https://github.com/mozilla-mobile/fenix/issues/10372 for my prior suggestion here, so it is not necessary to force a home page to get to "core" functionality or to hold off on https://github.com/mozilla-mobile/fenix/issues/7551

If we continue to have collections available on the home page, adding a home button (optionally) to the toolbar seems to be the easiest solution to allow people an easy way to get back to the home screen to get access to them (saving a tap in tab tray). Still, in a lot of ways, putting collections into content (home page) instead of chrome (like tab tray) feels kinda cheap, like a web port to an app, or a 1.0 mockup to an app, rather than a fully integrated experience - it would be like needing to close a Google Docs document in order to get to the list of documents in order to get back to another document instead of using a tab (tab tray) or switching to another window (collection) to access another documented. Why are the intermediary steps needed? Collections *only* being on the home page feels like a website that doesn't know about windows or tabs.

**Comment by fjorba** [comment]
Yes, I'd like to come back where I left my previous sessions. Everybody gets interrupted, often in the worst moment. Firefox should help us to know where we left things previously.

And no, I don't have the time or the need to organize my bookmarks.  They vary from week to week, and for me this is the reason that opening the browser where I left it in my previous session is the best solution.

Thanks.

**Comment by manywelps** [comment]
This is the primary reason I'm not updating.  Getting dumped on a useless page when I switch to firefox after it's closed is incredibly annoying.

90% of the time when I open firefox I want the page I was previously using.

**Comment by lando-cal** [comment]
As a user, I personally haven't even played with collections yet. I've been too busy trying to find my way back into a workflow.  

If things restored normally, and there was a button to start a collection, next to the button to open a new tab, I would be *much* more inclined to try them. This and page refreshes after switching apps have actually broken MFA for me on a couple of websites, as their MFA text is too long to read from the notification tray and I have to open my messaging app.

**Comment by yump** [comment]
How about opening to the tab list?  That's halfway to "last accessed tab", in the case where that's what the user wants to do, but avoids the enormous cost of re-loading the last-accessed tab, in case the user wants a different one.

**Comment by vesta0** [comment]
Product recommendation is to change the current behaviour and default to opening the user's last open tab after cold start + provide a setting to monitor if users are switching back and forth.

This decision was made due to the following factors:

1- Consistency within the app: Android may kill an app anytime and opening the homescreen when the user is expecting to open their last tab

2 - Consistency with other browsers: Users coming from other Android browsers expect this behaviour and in the absence of it, have complained about ending up with too many open tabs and the extra step required to close the tabs they don't need. We don't want our new users coming from other browsers to be "hoarding tabs" by accident. This also greatly impacts browser performance.

3 - User experience: Assuming that our primary goal is to optimize for quick information searches and help our users save time and get to where they need faster, we should take users' actual workflow into consideration. Many users have complained about ending up with too many tabs, and having to remember to go to their tab tray to close the tabs they don't need, so we may not be saving them time after all. Also with the removal of open tabs “Home” lost its hub functionality and now requires additional effort to continue where someone left off. 

Having said that, we know that landing people on the last tab without giving them a quick easy way to open a new tab, might also not be ideal as it requires users' mental effort to evaluate whether they still need the tab or not. So how might we make it easier for users to quickly open a new tab after landing on their last open tab? I have filed a [new ticket](#15138) for this SEPARATE investigation.

**Comment by tom-james-watson** [comment]
I presume you meant to link to https://github.com/mozilla-mobile/fenix/issues/15138 for the new ticket.

**Comment by yump** [comment]
While I prefer open-to-last-tab to the current behavior, I think the mental effort is a minor problem compared to the fact that the mental effort can't even start until the tab is finished re-loading from network, which can take many seconds, especially on a cold start.

**Comment by gtg947h** [comment]
I'm going to be the contrary one, and ask that (along with #5865 getting fixed) the browser just open to my bookmarks menu with a brand-new empty session, just like old Firefox did.

**Comment by ekager** [comment]
Updating based on discussions I had with other teammates. There are some UX/product decision to be made before engineering can take this on.

By return visits: do we just mean we want to remember if a user was on the browser when they left the app and launch them directly to their last selected tab (but pressing back will still take them to home etc) or do we mean every time the user starts the app they will start on the Browser view regardless if they have tabs open or not?

If we want to always go start at the browser, then we have more decisions to make. Similar to how Fennec and Chrome are set up, should the current "Home" content become the empty tab state? That is probably the best way forward from the engineering perspective to simplify a lot of the navigation logic, but will need large eng effort. 

cc @vesta0 @topotropic

**Comment by Bscremers** [comment]
> While I prefer open-to-last-tab to the current behavior, I think the mental effort is a minor problem compared to the fact that the mental effort can't even start until the tab is finished re-loading from network, which can take many seconds, especially on a cold start.

Yes this is what i want to.
Thats why i started using firefox in the first place.
I like the start screen option but onley when i click the web adress bar ore when i start a new tab.
But cold starting the browser i like to go back to the last page.

And i understand there are people who like to start at a clean home screen. Why not give them the disision to choose how they want to use this function?

**Comment by yoasif** [comment]
> Updating based on discussions I had with other teammates. There are some UX/product decision to be made before engineering can take this on.
> 
> By return visits: do we just mean we want to remember if a user was on the browser when they left the app and launch them directly to their last selected tab (but pressing back will still take them to home etc) or do we mean every time the user starts the app they will start on the Browser view regardless if they have tabs open or not?

I think what was requested was just to store the state of the browser on return visits, so it should be whatever the user was last doing, unless we somehow also want to do https://github.com/mozilla-mobile/fenix/issues/5865. 

I'm not sure I really understand the nuance you are commenting about here, because the home content *is* what is shown, as far as I understand it on return visits currently - meaning I see my top sites and collections.

**Comment by ekager** [comment]
the step we've taken in this direction is returning the user to the browser if they have tabs open **on cold start**. we can continue a discussion with UX on if this should be a pref and if there are other edge cases we need to address.

**Comment by fjorba** [comment]
I'm not sure to understand what a **cold start** means. But unless you let us go back to the previous behaviour (open the tabs I had opened the last time somebody interrupted me, or I closed the browser for whatever reason), I'll have to look for another browser.  And I have been using Mozilla since Nestcape 0.9; that's a loooong histotory.  Thanks.

**Comment by GottHeit** [comment]
Not sure if I can follow the discussion, but isn´t the topic about "launch them directly to their last selected tab on cold start instead of the home screen"? 
That is exactly what I would like to have back. Now I have to open firefox and then have to go the the last tab and to search the last position, where I stopped surfing. Annoying. 
Is this really about UX? Sounds like a setting in the options, so let "simply" users choose.

Besides other problems, like slow loading tabs, not sortable tabs, favorites not opening in existent tabs, no bookmarks on homescreen, senseless collections - which are not even syncing,  etc... but this is the most annoying problem.

I am using Vivaldi in the meantime, mobile+Desktop - as my workflow needs sync. And i never used another browser before and I started with early netscape too , but mobile surfing is my main focus.

**Comment by dessant** [comment]
Folks, update to the latest Firefox Nightly, the feature is already there and your last used tab is automatically opened on app start.

**Comment by ekager** [comment]
Going to tag this as QA needed (just for the behavior described in https://github.com/mozilla-mobile/fenix/issues/12062#issuecomment-708686212), let's open a new ticket for putting this behind a pref if that is what we want, "I can choose where my starting point is when re-launching the browser."

**Comment by Poopooracoocoo** [comment]
Thank you for changing this! :D At the moment this behaviour can be annoying as opening a new tab doesn't actually open a new tab yet.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201022 (Build #2015771115).
### Devices used:
- OnePlus 6T (Android 9)
- Samasung Galaxy S9 (Android 8.0.0)
