### ISSUE TITLE
Reset registered push notifications for all users due to 7164/7161

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#12077]
Without mozilla-mobile/android-components#7164 and mozilla-mobile/android-components#7161 users are getting push notifications that they never opted into. We should reset the approved push notifications so that users are not receiving notifications that they did not approve. This will reset push notifications for some user that allowed them but I don't think we have a way of knowing if it was user approved.

- - -
Transfered to Fenix so that the push resetting can be done only for this single product.

**Comment by jonalmeida** [comment]
We should identify which releases are affected by this bug first so we know where we would need to upstream the fix to.

**Comment by kbrosnan** [comment]
This made it to release so <org.mozilla.fenix> and <org.mozilla.firefox_beta> would be good targets. With the Play store cleanup we don't really need to touch <org.mozilla.fenix.nightly> or <org.mozilla.fennec_aurora>. We have not migrated <org.mozilla.firefox> users so as long as we don't ship the bug to them we don't need to reset the notifications for users.

**Comment by jonalmeida** [comment]
With the changes for mozilla-mobile/android-components#7161 in Fenix and Fennec Nightly, this should stop the effects of notifications without permission getting through.

It would be safer to let this change ride the train to Fenix Release users as well as it's already part of the next release that will be tested by QA.

Resetting push subscriptions for all might have an adverse effect since we don't have a fix to unblock  https://github.com/mozilla-mobile/android-components/issues/7143.
