### ISSUE TITLE
Tab View: Buttons too far up

### ISSUE THREAD

**Issue by AndiLeni** [mozilla-mobile/fenix#12148]
### What is the user problem or growth opportunity you want to see solved?
What I liked most about the new Fenix was the fact that all buttons are at the bottom of the screen and easily accessible.
With the new tab view this is unfortunately no longer the case.
The buttons for the private tabs and the menu are too high when you have some tabs open.

### How do you know that this problem exists today? Why is this important?
It is important because the screens are getting bigger and bigger.

### Who will benefit from it?
Anyone who has a smartphone with a large screen.

![grafik](https://user-images.githubusercontent.com/13385771/86221646-7408ce00-bb85-11ea-87ce-c1ad6659bd72.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2874)

**Comment by DavidBE-UK** [comment]
While this may be an issue for people who have the toolbar set to be at the bottom, for people like me who have the toolbar set to be at the TOP, we have the opposite problem. For us the tab switcher on the bottom sheet opens with the tabs starting too far down the page, and having the only new tab button right at the bottom is terrible. There needs to be SERIOUS thought given to providing different behaviour in the tab switcher overlay depending on whether Settings>Customise>Toolbar is set to top or bottom; it's currently the same for both and not good for either.

**Comment by cousteaulecommandant** [comment]
How about putting the tabs/private/dots bar at the bottom, and just integrate the + button into the bar, in the ugly space remaining between private and dots?  That seems like a reasonable use for that space.  (Unless it's reserved for some feature I missed, such as Pocket or Collection.) 

And for users such as @DavidBE-UK or myself who prefer the URL bar on top, I agree that the position of the bar should be changed.  And if possible, flip the whole menu so that it slides from the top instead of the bottom, for a cooler visual experience.  But maybe that deserves a separate issue.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812919

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
