### ISSUE TITLE
FNX2-15065 ⁃ [Bug] Reader mode not available for some pages

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#12184]
## Steps to reproduce
1. Open https://support.mozilla.org/en-US/kb/firefox-preview-your-rights

### Expected behavior
You should see the reader mode icon in the navigation bar

### Actual behavior
It's not available

### Device information
* Android device: 9
* Fenix version: nightly 200702 06:03

**Comment by csadilek** [comment]
Reader mode is a web extension in Fenix and we have a few restricted domains for which content scripts won't run for security reasons (just a few mozilla.org and firefox.com), but `support.mozilla.org` is one of them. That's why reader mode doesn't work in this case.

I am going to close this. We also have https://github.com/mozilla-mobile/fenix/issues/11916 to investigate improving readability.js checks.

**Comment by csadilek** [comment]
@B0pol Thanks for filing. If you have other pages for which reader mode works in Firefox Desktop or previous versions on Android, please leave a comment on #11916.
