### ISSUE TITLE
[Bug]Website does not load at first try

### ISSUE THREAD

**Issue by Lorinet** [mozilla-mobile/fenix#12199]
## Steps to reproduce
Open a tab with a heavy webpage in it. Exit Firefox, relaunch it, and while the page is still loading, make a google search. Then, after pressing enter in the URL bar, the search screen disappears, and that previous heavy site loads fully, but not ths Google search.

### Expected behavior
Load new site even when previous site is loading.

### Actual behavior
The previously loading site loads and the new site does not. Visiting an URL or making a search should cancel page loading in the respective tab and should start loading the new site.

### Device information
* Android device: Xiaomi Redmi 5 Plus, Havoc OS (Android 10)
* Fenix version: Mozilla Firefox 77.0.0-beta.2

**Comment by sv-ohorvath** [comment]
I noticed a similar issue, but in case the device/connection is faster:
1. Load a page: e.g. wikipedia.com, let it completely load.
2. Tap the URL bar and enter a different website, e.g. tripadvisor.com
3. Observe the URL shown after you press Go.
### Expected behavior
As soon as you submit the new URL/search, the address bar should instantly show the URL which has started loading.
### Actual behavior
The address bar shows the initial website URL while it loads the second, for a second or two, giving the impression that your new search didn't work.

**Comment by ekager** [comment]
@Lorinet are you still seeing this issue?
