### ISSUE TITLE
FNX2-15083 ⁃ [Releng] Publish Nightly app to Production track instead of nightly track

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#12208]
As part of the Nightly channel consolidation, we switched the org.mozilla.fenix to publish the Nightly app.

However, I forgot that you can't return a Production app back to "in-development", so while we are pushing Nightly builds to the org.mozilla.fenix channel, they are landing on the Nightly track -- but need to be on the Production track to be published.

We need to update our automation so that 1) we publish directly to the Production track, 2) automatically publish that release (because for nightly releases we should not require relman to publish each release).

**Comment by liuche** [comment]
Bugzilla for manual updates by relman on weekdays: https://bugzilla.mozilla.org/show_bug.cgi?id=1650180

@JohanLorenzo if you don't get a fix for this tomorrow, would someone else on your team be able to pick it up?

**Comment by SS1113** [comment]
Communication is what's lacking from your end to the users. Inform the users who are using the Fenix "production" channel that the app is transitioning to use the "Nightly" channel and give them enough time. Play Store page for Firefox Preview already lists the Nightly channel and with a Nightly version updated already! 

When asked for the communication, developers [lock the threads](https://github.com/mozilla-mobile/fenix/issues/12207). And accuse the users who are helping that they made incorrect assumptions about _several_ versions of Firefox on the Play Store (perhaps, if you communicated a little better, you won't have to do that)!

You might also mark this comment as "off-topic" but I don't want it file another issue on this repository. That's why I'm putting it here.

**Comment by sheikh-azharuddin** [comment]
Everything is so confusing and messy😡
Mozilla is forcing to move to Firefox preview(Firefox nightly now) from Firefox preview nightly and Firefox nightly....but what about the data???? You don't have sync features for collection and top sites...so if I move I will loose everything...plus I have to login again to all sites...how fair is this? There must be some way to export data or migrate data to the new Firefox nightly

**Comment by sheikh-azharuddin** [comment]
Also if Firefox preview nightly will be removed why it is still being updated in below link???

https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest

**Comment by Dunexus** [comment]
Nightlies have **NEVER** been here to be used as primary browser by users.
The goal of nightlies is to test features before they go to production channel. There is only one production channel, Firefox <org.mozilla.firefox>, not Preview, Beta, Nightly.

The transition period between Fennec and Fenix needed to have two distinct life cycle (main, beta and nightly) as Fenix couldn't replace Fennec before Fenix been considered features ready and stable enough by Firefox Mobile team.
This may be confusing but there was no other way to have both living during development phase.

Currently, this update channel issues is been addressed, see https://github.com/mozilla-mobile/fenix/issues/12207#issuecomment-653329878

**Comment by SS1113** [comment]
> Nightlies have **NEVER** been here to be used as primary browser by users.
> The goal of nightlies is to test features before they go to production channel. There is only one production channel, Firefox <org.mozilla.firefox>, not Preview, Beta, Nightly.
> 
> The transition period between Fennec and Fenix needed to have two distinct life cycle (main, beta and nightly) as Fenix couldn't replace Fennec before Fenix been considered features ready and stable enough by Firefox Mobile team.
> This may be confusing but there was no other way to have both living during development phase.
> 
> Currently, this update channel issues is been addressed, see [#12207 (comment)](https://github.com/mozilla-mobile/fenix/issues/12207#issuecomment-653329878)

I know the situation all too well. And why they needed those separate channels. But this is no way to handle it. Currently there are at least 3 different versions of Nightly. And a few weeks ago there were seemingly 2 Beta/ production channels were floating around in the guise of an experiment (this caused real trouble, and how many users do you think have installed the "beta" version instead of the "production" version and vice-versa?! And are now stuck on the "Beta" channel, for who knows how long). And now they're switching Fenix production channel to Nightly overnight! This muct be some sort of joke with users. And not to mention they accuse us the users of wrongly assuming which versions were what who try to help others in deciding what version**s** to install. If they communicate we wouldn't have to "assume" or "guess". 


They lock the threads when asked for communication from them! This is not how "Open development environment" where developers and users equally try to contribute in there capacity!

**Developers please stop experimenting with users. That's what I'm asking!**

**Comment by Dunexus** [comment]
>Currently there are at least 3 different versions of Nightly.
 
They are transitionning from the old Firefox Nightly <org.mozilla.fennec_aurora>, Fenix Nightly<org.mozilla.fenix.nightly> and Fenix <org.mozilla.fenix> to using only <org.mozilla.fenix> as new Firefox Nightly.
The in-app message was supposed to help but there was a bug leading to the wrong play store page.
Again, nightly is not supposed to be a stable version, when using it you should be open minded and prepared to such bugs.

>And a few weeks ago there were seemingly 2 Beta/ production channels were floating around in the guise of an experiment
 
There was Firefox / Firefox Beta on one hand and Firefox Preview / Firefox Preview Beta on the other hand.
The Preview label was clear about the last two being a preview of the rework of Firefox in active development.

>this caused real trouble, and how many users do you think have installed the "beta" version instead of the "production" version and vice-versa?! 

The "beta" label clearly means it is not production. Beta programs are available on the play store for so many apps (chrome, google maps, etc.)

>And now they're switching Fenix production channel to Nightly overnight

This is wrong, they switch **nightly** channel from the old one to firefox preview nightly, it should not affect users using versions other than nightly.
The [production channel](https://play.google.com/store/apps/details?id=org.mozilla.firefox) hasn't been changed (still <org.mozilla.firefox>) nor updated to Fenix yet.
