### ISSUE TITLE
[Feature request] Developers, please communicate with your users!

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12228]
I know why you needed those separate channels. I also know that Fenix is currently in a transition period. But this is no way to handle it! Currently there are at least 3 different versions of Nightly. And a few weeks ago there were seemingly 2 Beta/ production channels were floating around in the guise of an [experiment](https://github.com/mozilla-mobile/fenix/issues/11165) (this caused real trouble, and how many users do you think have installed the "beta" version instead of the "production" version and vice-versa?! And are now stuck on the "Beta" channel, for who knows how long). And now you are switching Fenix production channel to Nightly overnight! This must be some sort of joke with users. And not to mention you [accuse](https://github.com/mozilla-mobile/fenix/issues/12207#issuecomment-653329878) us, the users of wrongly assuming which versions were what who were trying to help others in deciding what versions to install! If you communicated a little we wouldn't have had to "assume" or "guess".

[You lock](https://github.com/mozilla-mobile/fenix/issues/12207) the threads when asked for communication from you (do you know how it feels when the issue gets marked as "off-topic"?, probably not)! This is not how "Open development environment" work where developers and users equally try to contribute in their capacity!

This sort of live experimenting with your users is going to cost us a lot! The users will definitely move to other browsers. The amount of versions on the Play Store is overwhelming right now!

I know the situation will improve overtime but I'm telling you if you keep going this route your users won't be happy! 

If you browse [/r/firefox](https://reddit.com/r/firefox) or [/r/Android](https://reddit.com/r/Android) for a while and
you'll know the users' cries for help! And you keep doing this. _Please_ know that we are only trying help you! And you wouldn't understand how much time I have spent in trying to resolve those users' queries and issues!

**Developers please stop experimenting with your users. That's what I'm asking! And communicate a little if possible, maybe?**

**Comment by SS1113** [comment]
I'm not going to file any further bug reports, reply to any comments from the developers who are asking for further info on the bugs reports/feature requests I have suggested, or be suggesting any design and UI/UX changes until I get a response from Mozilla!


@vesta0 I'm not sure if you are the product manager or not but I need a response from Mozilla on the issues I have raised! If I don't get a response then you can count me out from the users who give feedback on this repository!
I'm serious on this and I cannot contribute to any projects who are ignoring their users!

**Comment by Dunexus** [comment]
Sorry to tell you but lately your messages on this repository have become quite inappropriate.
Misusing bold, uppercase and exclamation mark make you sound like you are screaming and doesn't set a pleasant atmosphere to have a constructive discussion. Don't forget that the developers are also human being and deserve some common respect.

Please try to write down clearly and concisely your concerns and questions so the developer team will be able to take appropriate actions.
Based on what I have seen here since the very beginning of the project, it is wrong to say they are ignoring their users.

**Comment by SS1113** [comment]
@Dunexus I request you to please let voice my opinions!

**Comment by RealGJ** [comment]
@SS1113 Hello Brother, I understand your frustrations. But please remember, Mozilla is a Not for Profit organization and is totally running on Donations from users worldwide. So, There can be some problems. Please co-operate. I'm contributing like you. Cooperation is what we can do.

**Comment by SS1113** [comment]
@RealGJ I'm with developers and I have a lot of patience and I can solve the problems for myself; I'm capable of that much. 

I'm not raising this issue for me. Personally this doesn't  benifit me a lot. I'm saying all those things because I have seen users' cries for help. And I have handle it a lot; I cannot see someone suffering. That's why I want Mozilla to change their ways and communicate with their users. That's it. 

I'm very grateful for Mozilla for what they're doing for the open web and that's the reason why I want Mozilla to really improve. I very thankful to the developers who are working very hard day and night to improve the product we are using. I do. But I want some things to change that's why I'm raising this issue.

**Comment by SS1113** [comment]
Hi, @sheikh-azharuddin I have raised this issue. Can you say what opinions do you have about what I have said here?

**Comment by sheikh-azharuddin** [comment]
I have already said in the other thread which was locked and closed by the Devs.


Regarding the experience it is quite frustrating. While they claim other browser have similar builds .I disagree to that. Firefox has 5 builds which is confusing for users.ideally there should be 2 versions only---
Beta will be activated if user choose that in the play store itself( something like in below screenshot which microsoft edge and other apps have) so in this case if a user move to beta from stable there will be no data loss.... nightly should be a separate one...
Regarding the migration they could provide feature to export all data and migrate seemlessly...
![Screenshot_20200703-202116](https://user-images.githubusercontent.com/58127841/86480014-c2140200-bd3c-11ea-81a2-d00c30ab0d67.jpg)

**Comment by SS1113** [comment]
@sheikh-azharuddin yes, this is really confusing to general users! What I'm asking is that they improve it going forward and communicate with users a little more.

As you've always seen, I respect the developers a lot, I always try to reduce their workload by whatever means I can. 
And I also try to help anyone and everyone if I can here. But some users here say that I don't. Do you think that I'm that much of a bad person?

**Comment by sheikh-azharuddin** [comment]
I know that already bro how much you help others...all requests are first intercepted and filtered by you which reduces the number of open cases👍
So even if even Mozilla might ignore us they should listen to your feedbacks...

**Comment by RealGJ** [comment]
@SS1113 sorry brother! I didn't meant to hurt you. But I just thought that you were being arrogant. We should be arrogant towards profit oriented companies like Google which are stealing our data and earning profit by advertising from us. Sorry again!!

**Comment by vesta0** [comment]
The move to GeckoView and Android Components is a huge and possibly disruptive change, and getting this new version of Firefox into the hands of our community for testing and feedback as soon possible was a priority. Unfortunately, because of the Play Store distribution model, making the Preview version of this new Firefox widely available without disrupting existing users meant creating new apps called Firefox. We knew that this would cause some confusion for new users, but the benefits of this approach have definitely outweighed the risks. Thanks to the real-world testing and user feedback we got from that process, we're now able to consolidate those product lines down the traditional "release", "beta" and "nightly" channels with little risk of breaking the user experience. We're in the middle of that transition now, and while it hasn't been a perfect experience for everyone, we believe it's the best path to giving our users a reliable, high-quality next-generation Firefox. 

We're grateful for your patience and understanding and welcome your feedback during this transition, and if you'd like to follow the process more closely you can go to [Android community Matrix ](https://chat.mozilla.org/#/room/%23fx-android-community:mozilla.org) for all non-technical requests or issues.
