### ISSUE TITLE
FNX2-15153 ⁃ View the security of the website

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12298]
### What is the user problem or growth opportunity you want to see solved?
The website does not show the cipher suite or security suite while clicking the lock icon. It should show the cipher suite with tls version number... Something similar to what we see in desktop version on clicking more information... I don't want all details just a single line showing the cipher suite... Adding a single line under security lock icon wont do any harm... 

### How do you know that this problem exists today? Why is this important?
Sites must show the website security details

### Who will benefit from it?
All users

![Capture](https://user-images.githubusercontent.com/58127841/86536528-e9eb9d00-bed7-11ea-8a49-0acbaff78ade.PNG)

**Comment by SS1113** [comment]
I think, more information is necessary on what SSL certificate it is, when it'll expire, who issued it , etc. The more information we get about the SSL certificate the more good it is just like how Chrome does it.  The menu can be expanded to show all of this and even a sub menu/seperate pop-up page can be added just like how Chrome browser does it. It's a matter of security so I think the more information we have the more good it is! There's no benefit in hiding it, any benefits gained by hiding that info is subsided by the security information we get in return!

**Comment by cadeyrn** [comment]
How many users will benefit from this information? One of 50,000? It's an arbitrary number. I don't know at all which number is realistic but most users definitely can't do anything with this information and certainly not "all users" - that's for sure. I noticed that you write in really every feature request that _everyone_ would benefit. And that's not true. You should use this field to describe the real target audience of your suggestions.

---

The issue is moroe or less a duplicate of #8400. That issue is about exposing more certificate information.

**Comment by SS1113** [comment]
Let's keep the issue open and see what the developers say. That issue doesn't have enough information to make sure that this issue is a duplicate of that one, I think.

**Comment by kbrosnan** [comment]
Duplicate #8400
