### ISSUE TITLE
FNX2-15174 ⁃ Please provide a 64 bits beta build in Play Store

### ISSUE THREAD

**Issue by LaurentBonnaud** [mozilla-mobile/fenix#12337]
### What is the user problem or growth opportunity you want to see solved?
Current builds of Firefox beta are 32 bits.
This is strange because builds of Firefox (non beta, currently 68.10) are 64 bits.

### How do you know that this problem exists today? Why is this important?
In about:buildconfig I see ~~march=armv7~~a in clang compilation options.

### Who will benefit from it?
Everybody with a 64 bits version of Android, which is nowadays a vast majority of users.

**Comment by SS1113** [comment]
Mozilla does produce arm64 builds as well. If you are not getting them then, there're builds on GitHub release page you can download them.

**Comment by LaurentBonnaud** [comment]
I installed Firefox beta from the play store and got 32 bits builds on 2 different phones/tablets.

On the GitHub release page I only see source code archives.

**Comment by SS1113** [comment]
> On the GitHub release page I only see source code archives.
> 

Regarding that I have already raised some concerns in the issue https://github.com/mozilla-mobile/fenix/issues/11030.

You can download the builds from here: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2 if you want. 

Firefox beta is under 'fennec-beta' label
And Firefox Nightly is under 'Production' label. You can find them under the further label 'Latest'. But be aware that they might not be as stable as they're not tested with with a wider audience in a staged rollout! 
 
But keep this issue open so that developers can take a look into why 64bit builds are not being offered to you even after having a compatible 64bit device. Okay?

**Comment by kbrosnan** [comment]
The [Gekcoview builds are multi-arch](https://bugzilla.mozilla.org/show_bug.cgi?id=1508976). The results of about:buildconfig actually say `arm64-v8a armeabi-v7a x86 x86_64`. To know what build you are on you would need to pull the Android app version code for your install.

https://stackoverflow.com/questions/13469147/get-android-apk-file-versionname-or-versioncode-without-installing-apk
