### ISSUE TITLE
FNX2-15178 ⁃ [Feature Request]Add User-agent switcher addon

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#12341]
### What is the user problem or growth opportunity you want to see solved?
Ability to change browsers user-agent will solve the ability to see webpage from the perspective of other browsers including desktop versions.

### How do you know that this problem exists today? Why is this important?
Many people of the old Firefox version still uses this feature and may need it towork properly.

### Who will benefit from it?
Those who needs to change their browser fingerprint without changing browsers.

**Comment by Amejia481** [comment]
cc @vesta0

**Comment by sheikh-azharuddin** [comment]
Personally i will say we can do this through the about:config settings... The add ons present in the Firefox add on store for user agent mostly provides old user agent from other browsers... So its better to select the latest user agent and use it through preference... Try it result are outstanding 

On a side note Mozilla can add the add-on "user-agent switcher and manager" .. This is one of their high rated recommended extension. Also this will be better way for beta users too who don't have access to about:config page...

**Comment by vishalnandagopal** [comment]
> Personally i will say we can do this through the about:config 

I don't think we can change user agent value by a about:config tweak. Is there a property to change for this?

**Comment by sheikh-azharuddin** [comment]
You have to create one preference item...search in Google bro... 
![Screenshot_20200707-202637](https://user-images.githubusercontent.com/58127841/86800022-221ee700-c062-11ea-94af-488c03f95203.jpg)

**Comment by Oymate** [comment]
Just like the options, that's all :)

**Comment by cadeyrn** [comment]
about:config is not a solution since it's disabled on stable builds (#7865). Also I want to add that manipulated user agents cause a lot of trouble in Firefox support. So - _for me_ - the real question is: Why are you want to change the user agent? Understanding the use case(s) would allow to make a better informed decision.

Do you want to…

a) … change the user agent to the Desktop Firefox to get a "always Desktop" experience? Then solving #7039 would be a better solution.
b) … get a better experience of specific websites? If yes, which websites? I guess Google is a popular example. But I guess a better solution would be to have more talks between Mozilla and Google to finally get this solved. Or, as a last resort, Mozilla has the mechanism to override the user agent and to other kinds of intervention for specific websites. It would be wise to open issues for specific website problems.
c) … solve another use case? If so, which one?

**Comment by Oymate** [comment]
@cadeyrn It's the a) option, I know it is there but it still treats me like a mobile user.  :)

**Comment by BobVul** [comment]
> Why do you want to change the user agent?

I'm not the issue author but I do currently use [the mentioned user agent switcher addon](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) on the existing Firefox for Android. I fall under case (b). I set up a custom whitelist, which I use to send a desktop user agent to specific sites. The most glaring example being Imgur, which instead of providing just the raw image, forces mobile browsers over to their *much heavier* mobile site.

However, I can't say that *everyone* wants the direct image vs the mobile site, so I'm very hesitant to request an intervention that gets applied globally. A custom whitelist I can configure seems a much better solution.

**Comment by Tectract** [comment]
Right now, I would say that firefox has been CRITICALLY BROKEN, by the removal of USERAGENT.OVERRIDE.

There is currently no way to force websites to load in desktop mode. This is a basic, major feature of the browser that has been removed. 

I reported it as a bug and my bug report was very RUDELY force-closed. NOT COOL.

https://bugzilla.mozilla.org/show_bug.cgi?id=1657186

This is what drives people away from Firefox. Breaking major features and then acting like jerks to the users who go report the breakages in the bug trackers. 

We want useragent.override back. I don't want to have to install an extension from a 3rd-party to use basic features of the browser that were irrationally removed for no good reason. Being able to set a useragent string is something that browsers have supported since the 1990s. But apparently, 2020 arrives and Firefox devs now want to take this away from us.

**Comment by Tectract** [comment]
I don't appreciate being threatened and forcibly "shut up" by the bug tracker admins. You guys need change among your dev team.

**Comment by kbrosnan** [comment]
You were asked to abide by our [participation guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/). Acting out with all caps typing and making demands of the teams time is not respectful or professional.

**Comment by Oymate** [comment]
@kbrosnan  Hey, Is data-sync-user a bot?

**Comment by hwinnemoe** [comment]
@Oymate Yes, it is a bot. If you want to avoid its notifications, you can just block it via the three-dot-menu next to the _Follow_-button on https://github.com/data-sync-user.

![image](https://user-images.githubusercontent.com/42788925/89895001-5e061880-dbdb-11ea-9fda-9d2305a39368.png)

**Comment by NotWoods** [comment]
We would like to expand our support to other add-ons but we are not keeping open requests for specific ones. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates. You can also follow #7039 and #7865.
