### ISSUE TITLE
FNX2-15180 ⁃ [Crash] org.mozilla.fenix.perf.StartupReportFullyDrawn$attachReportFullyDrawn

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#12345]
> https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.SecurityException%3A%20at%20android.os.Parcel.readException%28Parcel.java%29&version=79.0.0-beta.5&date=%3C2020-07-07T14%3A58%3A43%2B00%3A00&date=%3E%3D2020-06-30T14%3A58%3A43%2B00%3A00

Mike, this is the number two top (startup) crash in Fenix 79b4 and 79b5 currently. Can you please take a look?

```
java.lang.SecurityException
	at android.os.Parcel.readException(Parcel.java:1967)
	at android.os.Parcel.readException(Parcel.java:1913)
	at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:8579)
	at android.app.Activity.reportFullyDrawn(Activity.java:2015)
	at org.mozilla.fenix.perf.StartupReportFullyDrawn$attachReportFullyDrawn$$inlined$doOnPreDraw$1.run(View.kt:1)
	at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:2)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1045)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2813)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Note that CrashStats says that 97.4% of these are happening on an _Unknown_ operating system and 2.6% on _Android_

* which is really odd. Is it possible that this is happening in automation?

**Comment by st3fan** [comment]
I put a release blocker label on this but I am actually not sure how critical this one this - let's triage and maybe @mcomella can leave an assessment here?

**Comment by mcomella** [comment]
According to similar reports on Sentry ([example](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8943770/events/316f936edf27494586d90525b109bcdf/)), the exception's message is:

> Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS

And this only appears to occur on Samsung devices.

After some googling, I could not find anyone else reporting issues with `reportFullyDrawn` and this `SecurityException`. However, I found similar `SecurityException` reports with stack traces including the ActivityManager (e.g. startActivity), and with similar messages (though "user -2" instead of "-1") ([example](https://developer.samsungknox.com/forum-topic/getting-javalangsecurityexception-permission-denial)). 

I was unable to find the true cause of this problem but to speculate, Samsung appears to include [additional security features on its device](https://en.wikipedia.org/wiki/Samsung_Knox) and perhaps throwing a SecurityException when calling `reportFullyDrawn` is a bug or intentional behavior in those systems.

We can make a hack fix – just catch the exception. We can't add the suggested permission because it's a platform permission. I'd like to further understand the cause but it's probably not worth the time right now.

---

Note: `SecurityException` may also be thrown from calling `reportFullyDrawn` on KitKat without the `UPDATE_DEVICE_STATS` permission ([source](https://graphics-geek.blogspot.com/2015/10/measuring-activity-startup-time.html?showComment=1446148482544#c3072258154342428556)) but we don't support KitKat.

**Comment by mcomella** [comment]
PR: https://github.com/mozilla-mobile/fenix/pull/12360 It's a speculative fix (since I can't reproduce locally) so we'll have to watch our crash reports to ensure it's fixed.

**Comment by WKSuperPower** [comment]
> > Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
> 
> And this only appears to occur on Samsung devices.
> 
> After some googling, I could not find anyone else reporting issues with `reportFullyDrawn` and this `SecurityException`. However, I found similar `SecurityException` reports with stack traces including the ActivityManager (e.g. startActivity), and with similar messages (though "user -2" instead of "-1") ([example](https://developer.samsungknox.com/forum-topic/getting-javalangsecurityexception-permission-denial)).
> 
> I was unable to find the true cause of this problem but to speculate, Samsung appears to include [additional security features on its device](https://en.wikipedia.org/wiki/Samsung_Knox) and perhaps throwing a SecurityException when calling `reportFullyDrawn` is a bug or intentional behavior in those systems.
> 
> We can make a hack fix – just catch the exception. We can't add the suggested permission because it's a platform permission. I'd like to further understand the cause but it's probably not worth the time right now.
> 

The Root cause of this security exception is the Multiuser feature.

## How do you know this?

Well, I'm the author of SuperPower - Root access Manager: https://forum.xda-developers.com/android/apps-games/superpower-root-access-manager-v3-5-t4087497

Since the Multiuser was introduced on Android 4.2.2, the "am" calls fails to run, and sends me that Security exception on Terminal Emulator.

The real fix is to pass the user who is calling the /system/bin/am" script in the "am" command-line:

## /system/bin/am broadcast --user 0 -a wkroot.tmanager.REQUEST.


As the SuperPower's su binary supports the Multiuser feature, there
is a trick that sets the argument to the "--user" parameter based on the current user that is invoking the su binary.

**Comment by mcomella** [comment]
> Since the Multiuser was introduced on Android 4.2.2, the "am" calls fails to run, and sends me that Security exception on Terminal Emulator.
> 
> The real fix is to pass the user who is calling the /system/bin/am" script into the "am" command-line:

I think this may be unrelated – our crash occurs in the application when `Activity.reportFullyDrawn` is called in what appears to be real user scenarios, not when accessing `am`. It could be related to the multiuser feature but the crash only occurs on Samsung devices on Android 9 so it seems unlikely.

**Comment by WKSuperPower** [comment]
< I think this may be unrelated – our crash occurs in the application when `Activity.reportFullyDrawn` is called in what appears to be real user scenarios, not when accessing `am`. It could be related to the multiuser feature but the crash only occurs on Samsung devices on Android 9 so it seems unlikely.

I'm sure that is the Multiuser feature that is causing the security exception (which occurs on all Android versions from 4.2.2 (where the Multiuser feature was  introduced) up.)

**Comment by WKSuperPower** [comment]
@mcomella after seeing the sources, I noticed that the reportFullyDrawn() is calling ### ActivityTaskManager, which in turn makes several calls to ActivityManager.

Note: the "/system/bin/am" command is just a script that invokes the ActivityManager.jar file.

**Comment by WKSuperPower** [comment]
@mcomella The best solution is to remove all calls to reportFullyDrawn().

**Comment by mcomella** [comment]
I see 1k crash events in yesterday's nightly at various times of the day ([source](https://sentry.prod.mozaws.net/operations/fenix/?query=is%3Aunresolved+release%3A%22org.mozilla.fenix-Nightly+200707+06%3A01%22+securityexception&sort=freq)) but no crashes in today's nightly ([source](https://sentry.prod.mozaws.net/operations/fenix/?query=is%3Aunresolved+release%3A%22org.mozilla.fenix-Nightly+200708+06%3A05%22+securityexception&sort=freq)): I think the fix resolved the issue.

---

> @mcomella after seeing the sources, I noticed that the reportFullyDrawn() is calling
ActivityTaskManager, which in turn makes several calls to ActivityManager.
>
> Note: the "/system/bin/am" command is just a script that invokes the ActivityManager.jar.

Interesting – I didn't realize the ActivityManagers were related or that the ActivityManager is so separated from the app.

> @mcomella The best solution is to remove all the calls to reportFullyDrawn().

We use `reportFullyDrawn` to record performance measurements so that's not ideal. The solution we went with is to catch the thrown SecurityException (PR: https://github.com/mozilla-mobile/fenix/pull/12360) and that appears to be working.

**Comment by mcomella** [comment]
QA: if possible, please verify the `SecurityException` crash is fixed in the latest Nightlies (either through Sentry or manual testing – I expect it to crash on startup on certain Samsung devices).

**Comment by Diana-Rus** [comment]
Hi, I didn't managed to reproduce the crash on build Firefox Beta 79.0.0-beta.5 and neither with Firefox Nightly 7/10 with Samsung Galaxy S9 (Android 8) and Samsung Galaxy Tab S3 (Android 8) with the following scenarios:

- Opening the app after a clear data through home screen device icon, through search widget, Fenix context menu->from device's homescreen through new tab and new private tab 
- Opening the app after a force stop
- Opening the app after a device restart

As a side note if it helps, on one of my crashes encountered on a build created locally from master for Operating system it was marked as "Unknown" - you can check this one https://crash-stats.mozilla.org/report/index/d3b94cd5-2035-48e4-9ba0-19c390200626 which was present on a local build and the difference here with same device : https://crash-stats.mozilla.org/report/index/77a14c71-0126-4052-96ec-7a6a10200708

**Comment by mcomella** [comment]
Here's a potentially incomplete list of all the crash reports this affects:
- https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7697983/
- https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7665206/
- https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8945768/
- https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7733264/
- https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8943086/
- https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8953241/
- https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8943770/

I think they're not grouped because they occur on different versions of Android, which have different stack traces.

**Comment by WKSuperPower** [comment]
> We use `reportFullyDrawn` to record performance measurements so that's not ideal. The solution we went with is to catch the thrown SecurityException (PR: #12360) and that appears to be working.

Your first patch does not fix the issue, just mask it. Your second patch also does not fix the issue because it just checks for Android 9, ignoring all others Android versions.

The SecurityExecption 

> Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS

is only thrown when an app or binary does when invoking the `am` without handling the Multiuser feature.

**Comment by mcomella** [comment]
> Your first patch does not fix the issue, it just masks it. Your second patch also does not fix the issue because it just checks for Android 9, ignoring all others Android versions.

From my perspective, the issue is that we're crashing on some devices. I believe the root cause is that Samsung modified the OS on some devices/configurations such that `reportFullyDrawn` crashes (probably to add security enhancements). To address it, we can't remove the call because we need to call `reportFullyDrawn` in production builds, and afaict there's nothing else we can change to prevent the exception from being thrown so our only option is to catch it.

@WKSuperPower iiuc, you're saying the root cause of the issue is actually that we're not supporting the multiuser feature correctly and if we did, we could avoid the crash. Is that right?

How would we support the multiuser feature correctly? Is there documentation?

Do you know why this only crashes on some Samsung devices? If we weren't handling an Android feature correctly, I'd expect it to crash across a range of devices.

---

Uplifted first PR https://github.com/mozilla-mobile/fenix/pull/12441 to v79: https://github.com/mozilla-mobile/fenix/pull/12521 Closed 2nd PR as it was too complex; I don't intend to follow-up on that approach.

**Comment by softvision-miralobontiu** [comment]
Hi all!
We were not able to reproduce the startup crash on Beta 79.0.0-beta.6 on the following devices:
* Samsung Galaxy Note 8 (Android 9),
* Samsung Galaxy Tab S6 (Android 9),
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Samsung Galaxy Tab S3 (Android 8),
* Samsung Galaxy S9 (Android 8),
* Samsung Galaxy S10+ (Android 10),
* Samsung Galaxy S7 (Android 7), and
* Samsung Galaxy Note 10 (Android 10).

**Comment by WKSuperPower** [comment]
> @WKSuperPower iiuc, you're saying the root cause of the issue is actually that we're not supporting the multiuser feature correctly and if we did, we could avoid the crash. Is that right?
> 
Only if you were calling "am" directly.

> Do you know why this only crashes on some Samsung devices? If we weren't handling an Android feature correctly, I'd expect it to crash across a range of devices.
> 

Technically, the issue is not with Fenix itself, but with the caller who naively invoke `am` without passing a user to it.

Even without running into the issue directly on Fenix, I'm able to easily reproduce it by sending a broadcast without passing a user to `am` (or passing user -1):

This is the intent that SuperPower's su binary uses (with Multiuser not being handled) to pass the root access request to SuperPower:

'/system/bin/am broadcast --user -1 -a 'wkroot.manager.RESULT' --ei caller_uid '10115' --es caller_bin 'jackpal.androidterm' --ei desired_uid '0' --es desired_cmd 'null' --ei allow '1' --ei all '1' --ei version_code '20''

this the result of above broadcast:

![Screenshot_2020-07-14-12-32-50](https://user-images.githubusercontent.com/67233524/87448276-0079ae80-c5d2-11ea-824c-826319e6a6a9.png)


If you remove the  '--user -1' the result will be:

![Screenshot_2020-07-14-12-27-00](https://user-images.githubusercontent.com/67233524/87448449-40d92c80-c5d2-11ea-92b6-a2bf4f80530f.png)

These results are because Android do not have users -1/-2.

Therefore, the solution is to pass the '--user 0' ('0' is the owner of the device ) into the 'am'.

I you switch  to another user (e.g.: user 1), you should pass '--user 1'. 

Yes, there is a broadicast being sent (probably from 'ActivityTaskManager' to 'ActivityManager').

Interesting how Fenix calls only one line of code, but that only line of code calls several lines of code.

**Comment by mcomella** [comment]
> Therefore, the solution is to pass the '--user 0' ('0' is the owner of the device ) into the
am.

If that's the case, we're unable to change this: we're calling a framework method, `reportFullyDrawn` which I presume was overwritten on Samsung devices and does not pass in the correct user in certain circumstances. As such, I think our only options are to not call the method or catch the exception.

---

> We were not able to reproduce the startup crash on Beta 79.0.0-beta.6 on the following devices:

@softvision-miralobontiu Are we okay to close then? We can open a new issue if we discover there's an alternative solution from the ongoing discussion.
