### ISSUE TITLE
[Bug] No scrollbar is shown

### ISSUE THREAD

**Issue by Baum55** [mozilla-mobile/fenix#12355]
## Steps to reproduce
Open this [wiki page](https://warhammerfantasy.fandom.com/wiki/The_End_Times) and scroll

### Expected behavior
Firefox shows a scroll bar like Chrome.

### Actual behavior
No scrollbar is shown.

Firefox Nightly
![Screenshot](https://user-images.githubusercontent.com/38204254/86824243-2bbe4400-c08e-11ea-8ed4-a98f8cda53e6.png)UNITO-UNDERSCORE!20200707-192550!

Google Chrome
![Screenshot](https://user-images.githubusercontent.com/38204254/86824263-31b42500-c08e-11ea-8d6f-0bfeba76ad40.png)UNITO-UNDERSCORE!20200707-192628!

### Device information
* Android device: Huawei P9 lite
* Fenix version: 200707 06:01

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3187)

**Comment by Diana-Rus** [comment]
Hi, checked with Samsung Galaxy S9 (Android 8) when making the recording you can see that the scroll bar is there, maybe you can check that as well. The position of the thumb position, for where you are in the page, with the "Find in page" bar enabled it's right above it, in the right corner, right above "x" button.

<details closed>
<summary>Samsung Galaxy S9 (A8) - position of the thumb position/</summary>

![20200708-172740](https://user-images.githubusercontent.com/49859863/86932608-4225d780-c142-11ea-91ce-c4df5d0cafe6.gif)
</details>

But I can see the need, of the thumb position, to be somehow adjusted in order to be more visible for the user.

**Comment by Baum55** [comment]
@Diana-Rus Thanks for the quick response.

You're right. I can reproduce and see it now. The thumb position is smaller compared to Chrome, but still there.

![Screenshot_20200708-231649](https://user-images.githubusercontent.com/38204254/86971740-f854e580-c171-11ea-9b56-394808b917d8.png)

It is a good idea to increase the visibility of the thumb position.
Should I close the issue?

**Comment by Diana-Rus** [comment]
Hi, no I think that we should leave it opened for triage and see whether there is a chance of improving it, display wise 😊.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813222

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
