### ISSUE TITLE
Private mode links should not be prompted open in app

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12388]
### What is the user problem or growth opportunity you want to see solved?
When I am trying to open any site in private mode which has respective app installed it shows a message to open in app however clicking on cancel does not allow to browse the site in browser. Like other browser the links should open normally in browser in private mode even through app is installed. If user wants he/she can click open in app after page loads. Please implement this feature... Too much irritating. 

### How do you know that this problem exists today? Why is this important?
Asking a user to open in app and not allowing to browse simply defeat the purpose of private mode 

### Who will benefit from it?
All users

![Screenshot](https://user-images.githubusercontent.com/58127841/86921889-60c4a800-c11b-11ea-8316-e5e9881fb687.jpg)UNITO-UNDERSCORE!20200708-182606!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3234)

**Comment by hyperfekt** [comment]
This happens with the 'open links in apps' setting enabled - hitting cancel on the resulting prompt on a private tab will not load the webpage.
Confirmed with Nightly 200710 06:01.

**Comment by sheikh-azharuddin** [comment]
Ideally it should open the link in browser only for private mode like other chromium browsers if user wants he can click open in app option...

**Comment by ShatteredPixel** [comment]
@rocketsroger Please take a look at this issue. Fenix is currently opening the webpages in the respective apps even if the webpages are opened in the Private Browsing Mode. I think this behavior is a serious breach of user privacy preferences and the Private Browsing Mode itself.

Thanks. :)

**Comment by rocketsroger** [comment]
> @rocketsroger Please take a look at this issue. Fenix is currently opening the webpages in the respective apps even if the webpages are opened in the Private Browsing Mode. I think this behavior is a serious breach of user privacy preferences and the Private Browsing Mode itself.

To confirm, you should see a prompt in private tab before it opens the external app, correct?

> I think the webpages shouldn't open in app even if the "Open links in app" is enabled and only let the users open only if they want through 3-dot menu. What do you think?

I agree.  If you turn off "Open links in apps" in settings, then external app can only be opened by user going through 3-dot menu.  The default "Open links in apps" should be off.  Can you please confirm?

Yes, I will definitely continue to work on this.  Thanks for bringing this to our attention.

**Comment by ShatteredPixel** [comment]
I have tested this again.

>To confirm, you should see a prompt in private tab before it opens the external app, correct?

Yeah, I forgot there would be a prompt if the link is going to be opened in-app. The behavior is as intended and is working correctly.

>I agree. If you turn off "Open links in apps" in settings, then external app can only be opened by user going through 3-dot menu. The default "Open links in apps" should be off. Can you please confirm?

Yeah, this too is working as expected. The default "Open links in apps" is in fact turned off by default. Thanks for clearing the confusion. 

---


**But**, Here's what this issue's reporter is saying: In Chrome browser's private browsing mode, lets say, for example, I searched for a laptop on Google search by typing "Asus laptop Amazon" then it'll bring me the search results, then I click one of the search results and now Chrome is opening that link in the browser itself and letting the user browser on Amazon website. 
Note: I have the Amazon app installed.

but in Fenix that link gets redirected and gets prompted to open the link in the installed  app when in private browsing mode and if I press on "Cancel" button the site stops loading and I have to load that link by going to 3-dot menu and clicking "reload" icon. And then I can browse the Amazon website in the Fenix itself.

___

I think this behavior can be improved by letting the website automatically reload and open that link in the browser itself if the user clicks on the "Cancel" button or we can make the behavior just like Chrome browser. **Or** we can let the user decide by letting them long press on the link and open that link in the new tab where the link doesn't open in the app and instead gets directly loaded and opened in the browser itself without any prompts. This is how Chrome browser handles links when the links are opened by long pressing them and opening them in the new tab both in normal and Incognito browsing mode. This would also make the "open links in app" more flexible and will provide users with more choice they want to open some links in the browser itself rather than letting Fenix open all the links open in app when the "open link in apps" is enabled.


Please let me know what do you think.

**Comment by rocketsroger** [comment]
> **Edit:** #12626 & #12624 I have gone ahead and opened these 2 issues related to the suggestions I made. Let me know what you think about them.

Thanks for raising the issues.  I'll look into them to improve the "Open links in apps" experience.  I understand that this functionality is very central to most users and we should polish it.  Thanks again for your help!

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807544

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
