### ISSUE TITLE
Ask whether the user wants to open a link in private mode or normal mode

### ISSUE THREAD

**Issue by MrSoke** [mozilla-mobile/fenix#12452]
### What is the user problem or growth opportunity you want to see solved?
Currently you can set firefox to open every link in private mode, but that often gets inconvinient since there are a lot of times you would need to open a link in normal mode, say for example it's a facebook link and you need to be logged in to see it, it is extremely inconvinient to have to copy that link and manually open it in normal mode. It would be way more convinient to have the option to make Firefox ask you in which mode do you want to open every link, and perhaps tell it to remember the option for specific websites.

### How do you know that this problem exists today? Why is this important?
being able to open links directly in private mode is extremely convinient, but having it be an all or nothing option makes it inconvinient enough that often it feels like you would be better off just not turning that option on at all, which defeats the purpose of it.

### Who will benefit from it?
Anybody who wants to keep control of their privacy options

**Comment by s-ankur** [comment]
Similar to #14405, #14424, #12452

**Comment by liuche** [comment]
Thanks for filing this issue! We originally tried this back in October using app-aliases, but ran into problems with Android 5 & 6 not being able to use "Default Browser" functionality. We may revisit this later, because it's clearly a great feature to have! but for now, please take a look at the linked issues #5742 and #5972.
