### ISSUE TITLE
FNX2-15259 ⁃ [Bug] Private Mode screenshots possible via Tab Tray Overviews

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12453]
## Steps to reproduce
Disable screenshots in private tabs
Open a private tab 
Switch to normal tab
Open tab tray
Open private mode tab tray

### Expected behavior
You cant see the private mode tab overview

### Actual behavior
You can see it and take a screenshot
![Screenshot](https://user-images.githubusercontent.com/33252312/87179903-0a986600-c2cf-11ea-8641-39d0b759e4b1.png)UNITO-UNDERSCORE!20200710-222816!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: ?
* Fenix version: ?

**Comment by sheikh-azharuddin** [comment]
Works fine as expected in latest nightly... Not allowing to take screenshot in tab tray...

**Comment by s-ankur** [comment]
@sheikh-azharuddin 
You need to follow the steps precisely. It is reproducible on


 Nightly 200710 06:01 (Build #21920613)
AC: 50.0.20200709130100, 432c0a58c
GV: 80.0a1-20200708094217
AS: 61.0.7

**Comment by sheikh-azharuddin** [comment]
Yes true... Able to take screenshot of the preview...

**Comment by ekager** [comment]
UX - should we also stop screenshots while not _IN_ PBM, but just viewing the tabs previews of PBM?

**Comment by Dunexus** [comment]
In my opinion, when you switch to PBM tab in tab tray, it *should* be considered as having the browser in PBM.
All you interact with from this tab is PBM-related, private tabs, open new private tab, etc.
It is like switching from "normal" window to private window on desktop.

**Comment by AmyYLee** [comment]
> UX - should we also stop screenshots while not _IN_ PBM, but just viewing the tabs previews of PBM?

Hi, 

I think this would still be a privacy concern so yes we shouldn't allow screenshots in this scenario if the user has it set to not allow screenshots in PBM.

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on the latest Nightly 200720 (Build 22020611) with Sony Xperia Z5 (Android 7), Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9).

<details><summary>Samsung GIF</summary>

![20200720-112925](https://user-images.githubusercontent.com/49859863/87916818-9f902180-ca7c-11ea-912e-8b6d7472e187.gif)
</details>

Note:
- With the STR from description the issue is not reproducible
- When the app is in recent app and the private tabs tray is opened, there won't be any information displayed.
- In case of wanting to make a screenshot it will display an informative message: Can't take screenshot due to security policy.
- With Sony Xperia Z5 (Android 7) the issue is not reproduce able but after putting the app in recent apps for the first time, the second time it will display the normal tab tray info, which is different outcome from Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9)-i'll create a new issue for this
