### ISSUE TITLE
FNX-4901 ⁃ Create Fenix Session prototype for evaluative user research

### ISSUE THREAD

**Issue by hmcgaw** [mozilla-mobile/fenix#125]
### Purpose
We need to verify a set of critical hypothesis around sessions that require a functioning prototype. 

### Hypothesis to evaluate
1. The notion of Sessions fits in people’s existing workflows (task continuity,....).
1. People appreciate that open tabs are collapsed after a session and that they can start from a fresh slate.

### User stories prototype must cover
1. Barbara wants to see a list of currently open tabs so that she can switch between her open tabs, or close one of them.

* Is able to navigate to webpages via search
* Is able to create new tabs 
* Open tabs are listed on home screen under “Current Session”
* Reference screen: https://mozilla.invisionapp.com/share/PEPPH7NUTRX#/334398019_Full_01-_Tab_Viewer_-Current_Session-

1. When opening Fenix, Vesta wants to start from a clean slate so that she is not distracted by open tabs

* After Fenix is closed for 2 minutes (tbd), open tabs are collapsed into a session
* Collapsed tabs keep their state (question is for how long)
* Sessions are displayed on the home screen, listed in chronological order (newest to oldest)
* Older sessions appear or replace the “Current session” sections when tapped on
* Reference screen: https://mozilla.invisionapp.com/share/7JPPHJ4BXMT#/335575284_-Screen_-_Home_-Default-
* Reference screen 2 (on scroll): 
https://mozilla.invisionapp.com/share/6FPPHKTYNPV#/335575287_-Screen_-_Home_-Show_All_Sessions-

Alternative implementation, if quicker:

* Instead of collapsing tabs into sessions, we just display a flat list, that looks like web history with the following structure: today, yesterday, last 7 days, older.
* Reference screen: https://mozilla.invisionapp.com/share/DAPPHLKSWR2
* Reference screen 2 (home, on scroll):  https://mozilla.invisionapp.com/share/GXPPHM84WBN#/337299616_-Screen_-_Session_Simplified_For_Dev_-2-

**Comment by bbinto** [comment]
@boek to break down issues by Monday Jan 14, and we'll readjust sprint 1 

https://github.com/mozilla-mobile/fenix/milestone/9

**Comment by boek** [comment]
- [ ] Create example sessions UI
- [ ] Archive session after a certain period of time
- [ ] Provide a way to manage multiple archived sessions
- [ ] Present archived session

**Comment by topotropic** [comment]
@boek 
- When are open tabs collapsed into a session? After x min or just after killing the app?

I'd also like to discuss the following change:
- Can we merge tab view and home so that we list open tabs on home?
([Ref. screen](https://mozilla.invisionapp.com/share/GFQ4EM2CMVN#/335064762_Full_01-_Tab_Viewer_-Scrolling-)). The tab icon on a page would link to home then.
- When someone taps on a collapsed session on home, it's unfolded and displayed on home under "Current session" 
- When someone has already tabs open and taps on a collapsed session, we merge the old session and the current one.

Thoughts?

A minor thing, I noticed that when I archive a session and start a new one, the just archived one gets overwritten.

**Comment by boek** [comment]
Hey @topotropic,

Currently it never _ends_. We start a new fresh session on a fresh app launch.

I think those are all good changes. Let me see if I can whip it together today.

I will also investigate that bug! It should definitely be starting a new one, not re-using the old one.
