### ISSUE TITLE
Add Wi-Fi location "stumbler" service (for Mozilla Location Service, MLS)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1253]
### Why/User Benefit/User Problem
Fennec's Wi-Fi location "stumbler" service is the primary source of Wi-Fi location data for [Mozilla's Location Service](https://location.services.mozilla.com/) (MLS). We need Wi-Fi location data from contributors to keep the MLS database fresh. We should add a Wi-Fi stumbler to Fenix after we retire Fennec. The Wi-Fi stumbler probably doesn't need to block the Fennec/Fenix migration, but we should add it soon after.

### What / Requirements
Fenix users can opt into sharing anonymous Wi-Fi location data with MLS. The stumbler service would probably be best implemented as an AC component that can be also plugged into other Mozilla apps.

Here is the Fennec meta bug that originally integrated the standalone [MozStumbler](https://github.com/mozilla/MozStumbler/) app's code into Fennec:

https://bugzilla.mozilla.org/show_bug.cgi?id=1032506

https://searchfox.org/mozilla-central/source/mobile/android/stumbler

**Comment by Djfe** [comment]
If people are working on integrating it anyways, then maybe there is some time to freshen up the client code anyways. Nobody has worked on it for a few years. Client and Server don't support 5g, yet. While opencellid just added support.
https://github.com/mozilla/ichnaea/issues/525

Not entirely related but the same client codebase:
The native client app (Mozilla Stumbler) never worked on Android 10 due to an SDK change that makes the client crash when trying to upload reports (removed ssl cipher which the client tries to use).
There is a pull request from someone that attempts to fix it, but nobody seems to maintain the repo anymore sadly.
https://github.com/mozilla/MozStumbler/pull/1864

**Comment by madb1lly** [comment]
Hi @Djfe,

I think the Stumbler app was retired a few years ago, it can no longer be installed from play store (unless one already had it). So I don't think the app will be updated or fixed.

The Mozilla location service on the other hand is alive and well, as far as I know, and if Fenix isn't keeping it up to date then I don't know what is because as far as I know Fennec is the only way of gathering data for it.

Cheers 🙂

**Comment by Djfe** [comment]
thanks for your answer :)
I'm looking forward to the added stumbling support in Fenix, even if it takes months to rollout. (5g is just a nice to have)

Another thing that the new Fenix code should account for: Android throttles wifi scans now.
https://www.xda-developers.com/android-pie-throttling-wi-fi-scans-crippling-apps/

I can still open the play store page (even in a private tab), so while the Mozstumbler app might be retired, it's still available to new users on the play store.
https://play.google.com/store/apps/details?id=org.mozilla.mozstumbler
(you can find it with Google if you search for it)

**Comment by madb1lly** [comment]
Hi @Djfe,

Then I was mistaken about the play store, please excuse me. I should have checked before writing it - I must have got mixed up with another retired Mozilla app, of which there are many!

Good point about throttling wifi scans. I don't have any idea when the Fenix team plan to add this to Fenix but when they do your comments will definitely be useful.

Cheers 🙂

**Comment by cpeterso** [comment]
> I can still open the play store page (even in a private tab), so while the Mozstumbler app might be retired, it's still available to new users on the play store.
> https://play.google.com/store/apps/details?id=org.mozilla.mozstumbler

The Mozilla Stumbler app is still in the Play Store, but it isn't compatible with recent versions of Android and isn't actively maintained.

**Comment by madb1lly** [comment]
Hi @pocmo,
Why is it closed? I know that Stumbler is no longer maintained but what about the backend Mozilla Location Service? Is that also defunct now?
Cheers 🙂

**Comment by pocmo** [comment]
The location service is still there and being used. But there's currently no plan to fill it with data from Fenix (stumbler integration).

**Comment by madb1lly** [comment]
Hi @pocmo,
So how does MLS get kept up to date, e.g. with changing Wifi hotspot names? I'm quite surprised that Mozilla don't want to use their premier mobile product to maintain MLS.
Cheers 🙂

**Comment by Djfe** [comment]
me too, this could literally be the end, if Mozilla doesn't help fill the service with fresh data. Of course it will get some data from third parties like tower collector and Open Cell ID but those are only collecting cell towers. No wifi access points or Bluetooth beacons which allow a more accurate position estimation.

**Comment by Djfe** [comment]
![Screenshot of https://location.services.mozilla.com/stats](https://i.imgur.com/0Ja0FrD.png)
You can literally see the kink in August 2020, where the curve flattens.
For WiFi it seems to be less pronounced since there is a number of magnitude more wifi access points, but it still seems to be there.

Sure the reason could be something else, but it's evidence. And due to 5g lots of new cells should pop up around the world.
