### ISSUE TITLE
FNX-4906 ⁃ [Bug] Reporting Fenix webcompat issues in app goes to Fennec team, then gets closed

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1256]
## Steps to reproduce
Open an issue using the "Report an issue" link.

### Expected behavior
The issue is appropriately checked against Fenix.

### Actual behavior
The issue is incorrectly checked against Fennec and Focus.

### Device information
* Android device: Android Pie
* Fenix version: Build #10851633

**Comment by colintheshots** [comment]
I think we need to identify Fenix issues in some way. It would be great if we could pass flags to send the build number and browser app_id with the report.

**Comment by ekager** [comment]
Did you talk to webcompat about this?
We are adding a label here to try to pass Fenix identity on to webcompat, but could add more identifiers if they want/support it on their end.
 https://github.com/mozilla-mobile/fenix/blob/c5205b62367aecb024215a6854f3b49092c30adb/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L428

**Comment by boek** [comment]
@colintheshots do you have an example of an issue that got closed? I checked with the web compat team and they’ve been triaging fenix issues and if one got closed it might have been a mistake or a bug

**Comment by colintheshots** [comment]
https://github.com/webcompat/web-bugs/issues/27257#issuecomment-477997979

The issue got sent from Webcompat to Fennec.

**Comment by denschub** [comment]
Hey there! @colintheshots did you report the issue you linked via Fenix' embedded Report Site Issue thingie?

**Comment by colintheshots** [comment]
Yes, that's exactly how I reported the issue.

**Comment by denschub** [comment]
Ah, nevermind. I just tested the reporting, see https://github.com/webcompat/web-bugs/issues/28961 - and it worked fine, so I was confused. However, as it turns out, we didn't add support for that on our side right away (we have to whitelist labels that can be set via URL parameters to avoid abuse). We did that in https://github.com/webcompat/webcompat.com/pull/2820, which got deployed on 2019-03-14 - so all reports after that will be tagged with a Fenix tag.

I have reopened the web-bug mentioned here, and I didn't find any other issues reported by you. If there are more issues that got closed, please let us know (#webcompat on IRC or Slack), and we will reopen those! Sorry for the confusion.

**Comment by boek** [comment]
Thanks @denschub !
