### ISSUE TITLE
FNX-4908 ⁃ Investigate how Doorhanger should look like in custom tabs

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1258]
@brampitoyo Do we have some mock-ups for the Doorhanger interaction with custom tabs?
Should it has the same functionality ?

![image](https://user-images.githubusercontent.com/773158/55241235-0eef5b80-5211-11e9-83cf-1688396cf3dc.png)

**Comment by Amejia481** [comment]
cc: @jonalmeida

**Comment by pocmo** [comment]
@brampitoyo I think your Custom Tabs mocks showed a top toolbar. Curious if the "doorhanger" will have the same layout and are just going to be attached to the top?

**Comment by brampitoyo** [comment]
@ameija wrote:
> Do we have some mock-ups for the Doorhanger interaction with custom tabs?
> Should it has the same functionality?

@pocmo wrote:
> I think your Custom Tabs mocks showed a top toolbar. Curious if the "doorhanger" will have the same layout and are just going to be attached to the top?

Thanks a lot for asking this question, because I haven’t thought of it.

Yes. @pocmo was exactly right. The doorhanger will be attached to the top, but the order of items in the doorhanger won’t change.

So if our custom tab looks like this:

<img width="360" src="https://user-images.githubusercontent.com/51007/55391973-936d1180-5564-11e9-9a3c-d36b7e5cd19c.png">

Then our site information panel doorhanger will look like this:

<img width="360" src="https://user-images.githubusercontent.com/51007/55391999-a1229700-5564-11e9-80ea-3eb36dbdb105.png">

**Comment by Amejia481** [comment]
Thanks @brampitoyo !
