### ISSUE TITLE
Tabs sent from another Firefox open in app even with "Open links in app" set to "No"

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#12627]
## Steps to reproduce
Set "Open links in app" to "No"
Send a tab from another Firefox instance using the same Firefox account to the Fenix instance
Click on the notification received by Fenix on the phone

### Expected behavior
The tab should open in Fenix

### Actual behavior
The tab opens in the app (tested with links to Github and with the Github app)

### Device information
* Android device: Redmi Note 7 Android 9
* Fenix version: #21960614

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3530)

**Comment by ShatteredPixel** [comment]
Hi, I have tested this with "Open links in apps" both enabled and disabled and I get promt to open either in Firefox or GitHub app. Can you tell me if the preference of Android's "Open by default" is set to "ask every time" or something else?

**Comment by klint** [comment]
Yes, that was it I have the same behaviour after setting Open by default to "ask every time". The OS is dealing with the shared link before it reaches Fenix itself.

**Comment by ShatteredPixel** [comment]
@klint 

>The OS is dealing with the shared link before it reaches Fenix itself. 

Thanks for making that clear. I sensed something _was_ unusual with the way it was behaving.


But, here's what going on with the sent link;

For example, let's take GitHub links. I send them from my laptop and I open them on my phone.

The behaviour when Fenix is backgrounded and I'm at the Android's homescreen; 

I tap the link that's in the Android's notification tray then the Android system suggest me to open that link in the GitHub or Fenix

The behaviour when I'm using Fenix;

I tap the link that's in the Android's notification tray and Fenix opens them in the browser. 

This is the same behaviour even when the Fenix's "Open links in app" is enabled or disabled.


I mean, isn't this behaviour best of both worlds.

___

Let's say, if Fenix's behaviour is modified and Fenix ends handling all the links in itself when "Open links in apps" is disabled then;


In both cases when I'm at the homescreen and using Fenix, If Fenix ends up handling the links and then users will lose the choice to open that link in the app or GitHub.

And users will always have the choice to select the default behaviour to open the link in either the app or browser through Android's "Just once" and "always" buttons and currently I think that is not working due to this bug https://github.com/mozilla-mobile/fenix/issues/12624

___

Currently I'm in a bit of confusion as if the users who have disabled the Fenix's "Open in app preference" strictly want _evey_ link to be opened in Fenix and want to bypass the even Android system preferences or they want it to be _a little_ more flexible. As the link is currently not yet in the Fenix itself but in the Android's notification tray and I think we should let the Android system handle that link with its own preference and UX behaviour and If we modify it, it may cause confusions to users; even for the users who have disabled "Open links in app" preference in Fenix. 


@rocketsroger please let me know your thoughts on this. And sorry for the continuous tags since yesterday as I think the bug/comment may get lost in all other comments/issues and I want my thoughts to it reach the developers when they are developing and designing it. 

Thanks! :)

**Comment by Diana-Rus** [comment]
Reproduced the issue from description on Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) with Firefox Beta 80.0.0-beta.2 and Firefox Nightly 7/30.

1. Sent a youtube tab from desktop or a different phone to another one.
2. Tap on the notification with the received tab to the dedicated browser.

Result: Instead of having the browser open the tab. The youtube app will open.

**Comment by jonalmeida** [comment]
This was the [original intended behaviour](https://github.com/mozilla-mobile/fenix/blob/2059156193ba35d78064e1e8d2d55f6caeae29e4/app/src/main/java/org/mozilla/fenix/components/NotificationManager.kt#L57-L59) when we setup notification support for Send Tab so that you could allow the default app to handle the send tab notification.

IIRC, this was the same fennec behaviour too.

I'm going to convert this into a feature request for that reason to see how we feel about this first. Note that, not all URIs sent from send tab can be handled by the browser.

**Comment by Whisprin** [comment]
> Note that, not all URIs sent from send tab can be handled by the browser.

Could you please elaborate on why this is the case? In my case I'm sending Google Play store URLs from desktop to mobile and I want them to be opened in the browser - that's why I disabled "open links in apps".
So the expectation is that no link will be opened in an app, unless I manually select "Open in app" from the settings menu.

Maybe, with "open links in apps" disabled Firefox mobile could rewrite all received URIs to something like `firefox://https://...`. (In case that's even necessary for "open links in apps" to work as expected)

**Comment by mailinglists35** [comment]
>I'm going to convert this into a feature request

If the intended behaviour was this, then the intended behaviour is the bug itself.

When I send a tab to Fenix, it is meant for Fenix not for Focus, period. Anything else is a bug in design.

See my frustrating experience in duplicate issue #17173
