### ISSUE TITLE
Add time remaining text to download notification

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#12734]
![resim](https://user-images.githubusercontent.com/17825767/87959049-00d6e580-cabb-11ea-8555-5edb042edbb3.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3678)

**Comment by Amejia481** [comment]
Is there any specific reason why we are closing this ticket ? :)

**Comment by Amejia481** [comment]
cc @hakkikaancaliskan

**Comment by hakkikaancaliskan** [comment]
I just think this is unnecessary feature and requires unnecessarily eng time 🤷
Devs could work on other stuff :)

**Comment by Amejia481** [comment]
It's still good to have it open for pick it after, it could be even  ticket for [hacktoberfest](https://hacktoberfest.digitalocean.com/)  🎃  :)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@hkaancaliskan, https://user-images.githubusercontent.com/17825767/87959049-00d6e580-cabb-11ea-8555-5edb042edbb3.png confuses me, because it does not appear to depict what the title describes. Is the difference between presentation of the percentage versus actual amount relevant, or solely that the “7m” beside the previous text is absent from Firefox's notifications?

**Comment by hkaancaliskan** [comment]
@BEEDELLROKEJULIANLOCKHART Fenix currently just says "7m" and it can be confusing for people because is it "time" left or the "time started ago". By changing it to "7m left", Fenix can avoid this confusion.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I agree,

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812808

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
