### ISSUE TITLE
FNX-4918 ⁃ String updates needed for first Fenix string export

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#1274]
I've gone through the batch of strings for Fenix, and found a few things that will need to be updated in the batch of strings we got.

You can find my full review in our quarantine export here:
https://github.com/mozilla-l10n/android-l10n/pull/11#

Original string file here: https://github.com/mozilla-l10n/android-l10n/blob/14055d82f2d8c88ecbc573f2e6fccd42ad705ae3/mozilla-mobile/fenix/app/src/main/res/values/strings.xml

@sblatz: It seems you may be the right person for making these changes?

(also, CC @mheubusch and @Pike so they can follow this)

**Comment by sblatz** [comment]
Thanks for filing this, @Delphine 😄 

We'll need to get this prioritized in a sprint. cc: @vesta0, @bbinto.

**Comment by Delphine** [comment]
Seems like work has started in #1341, so calling that out here in case.

**Comment by Pike** [comment]
I've updated the PR over in android-l10n with the latest landings in Fenix, including 1341. As D mentioned, there's a bit more work to do.

Notably:
* [ ] The "Fenix" brand string should move to a separate file
* [ ] All occurrences of "Fenix" need to be replaced with a parameter passing in the brand from above
* [ ] LeakCanary should go into a developer-only file. This could be the same as the brand one, or not
* [ ] Are there better comments to explain "Quick Action sheet"?
* [ ] `about_content` was changed in 1341, verify with @mheubusch that that's the version we expose to l10n. Otherwise move into a non-ready-strings file
* [ ] Comments for remaining placeables that are not yet explained. Right now, there are two left

**Comment by bifleming** [comment]
@sblatz can you fix these?

**Comment by boek** [comment]
I got it

**Comment by Pike** [comment]
Thanks for your help here.
