### ISSUE TITLE
[Feedback] Why doesn't the 'new tab' button create a new tab?

### ISSUE THREAD

**Issue by fellowish** [mozilla-mobile/fenix#12774]
### What is the user problem or growth opportunity you want to see solved?
I'm confused by the new tab button, and the '+' button as well. When I press it, I expect a new tab to be created and added to the tab count, but this isn't the case. Is home screen a website? Why isn't it actually a tab? 

It actually makes it a little difficult to use. 

### How do you know that this problem exists today? Why is this important?
Quite literally the big '+' button only takes you to another menu. My brain is confused by a button meant to create a new tab bringing me to... Not a tab? 

The problem is it **looks** like a website. It doesn't look like a menu. There aren't tabs to select within it, nor much else besides collections. But why is the new tab button bringing me to my collections? _Is it a tab, or is it not?_

I would recommend either making the home screen reside within a tab, _or_ having the home screen and the new tab button be different buttons entirely.

**Comment by vesta0** [comment]
@brampitoyo FYI since you are working on this.

**Comment by s-ankur** [comment]
What's even more interesting is that the tab tray opened on the home screen gives you a + button but that button just returns you to the home screen. It is very jarring when the + button and the back button have the same effect!

**Comment by brampitoyo** [comment]
Thanks @vesta0 for tagging me here.

We’re in the process of submitting a proposal that will specifically address this problem:

- The “+” button will no longer “Return you to the New Tab Page”, where it’s unclear whether it’s a new tab, a current tab or… something else
- Instead, the “+” button will always open a fresh new tab. You will notice that the number of tab have gone up by 1. Inside this fresh tab, the New Tab Page will open.

By doing this, what happens when you tap the back button/gesture becomes very clear: we will simply close the fresh new tab (you will notice that the number of tab have gone down by 1) and return you to the last tab you have opened.

Lastly, what happens if you’re on a fresh new tab with the New Tab Page initially open, and then tap the “+” button? On this, I’m not so sure, and I’d love @topotropic to write an opinion.

- Should we open yet another tab and increase the number of tab by 1?
- Or, should we recognise the fact that the “+” is probably a mistake, so the number of tab shouldn’t increase? We should simply close the tab tray.

**Comment by fellowish** [comment]
Have you though of scrapping the + button for something more akin to a home button like in #12301 , @brampitoyo ?

**Comment by Cheap-Skate** [comment]
@brampitoyo 
> Lastly, what happens if you’re on a fresh new tab with the New Tab Page initially open, and then tap the “+” button? On this, I’m not so sure, and I’d love @topotropic to write an opinion.
> 
>     * Should we open yet another tab and increase the number of tab by 1?
> 
>     * Or, should we recognise the fact that the “+” is probably a mistake, so the number of tab shouldn’t increase? We should simply close the tab tray.

I would suggest the former, it's more consistent and would make Fenix work like most other browsers where repeated taps on the + button opens ever more tabs each on about:home.

(Now if at the same time you could call it about:home instead of the New Tab Page and then give me a way to get to about:home from an already open tab as well as a new one.... I'd be a very happy person!  https://github.com/mozilla-mobile/fenix/issues/11296#issuecomment-653470097)

**Comment by Cheap-Skate** [comment]
See also #10368

**Comment by AmyYLee** [comment]
@topotropic for follow-up

**Comment by topotropic** [comment]
I agree that this is confusing and we hope to mitigate it a little with the new search flow (tap plus, go back to home with keyboard up). Counting up the open tab number and moving from a home/hub to a new tab model would require a bigger refactoring as far as I understand it. 

@liuche @vesta0 maybe we should get an estimate for this and then consider it in comparison to everything else that's going on

**Comment by liuche** [comment]
That's a good point - our current flow is homescreen-focused rather than new-tab focused, which definitely causes some of these. This is a good question though, and I do think the search flow will improve it.

**Comment by Poopooracoocoo** [comment]
and when you open fenix it opens the a new tab/the homescreen which can result in a lot of tabs

**Comment by Poopooracoocoo** [comment]
@stale EXCUSEMOI. u bish.

Things have gone stale here because no one from Mozilla has said anything. There is no _discussion_ to be had here. It's pretty clear cut: make Fenix more like Firefox for desktop and like other browsers.
