### ISSUE TITLE
FNX2-15467 ⁃ [Bug] Can't interact toolbar after closing private tab until "Private tab closed" disappears

### ISSUE THREAD

**Issue by Augures01** [mozilla-mobile/fenix#12793]
## Steps to reproduce
1. Close private tab
1. "Private tab closed" message appears
1. Tap on urlbar / tabs / three dot menu

### Expected behavior
Can interact with urlbar/tab tray/menu any time

### Actual behavior
Can't interact with urlbar/tab tray/menu until "Private tab closed" message disappears

### Device information
* Android device: Samsung S6 Edge / Android 7.0
* Fenix version: Nightly 200721 13:47

**Comment by Augures01** [comment]
@sblatz 
Fixed in Nightly 200724 19:15

**Comment by Diana-Rus** [comment]
Hi verified this ad fixed with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9), when snack-bar is present the user can interact with the rest of the elements (urlbar / tabs / three dot menu).
- Having only one private tab opened and snackbar is present ✔️
- Having multiple private tabs opened and snackbar is present (tabs tray options are available for use: normal browsing button, "+"/"+ Private" and ⋮ "More options" button) ✔️
