### ISSUE TITLE
[Bug] Add Create Account on the the Sign In page on Fenix

### ISSUE THREAD

**Issue by AnaMedinac** [mozilla-mobile/fenix#12829]
@davismtl noticed that we are seeing a steady decrease in FxA registrations on iOS since we implemented the QR pairing flow. We figured that Fenix might be seeing a similar problem since the current UX has no clear call to action for registering as it's very sign in focused: 

![](https://user-images.githubusercontent.com/22782298/88195941-9c2c9f80-cc0e-11ea-81ba-2a1264def06b.png)

@j19s84 On the FxA side has mocked up a proposal for the UX to include a third button - `Create account`: 

![](https://user-images.githubusercontent.com/22782298/88197390-6d172d80-cc10-11ea-9bca-b785ce21dbcd.png)

The `Create account` button would redirect the user to the same web page as the `Use email instead flow`. The addition of this button should help users easily register for a Firefox Account on mobile too.

We also increased the font size for the URL as it went since it sometimes went un-noticed by users.

**Comment by davismtl** [comment]
This may be redundant but hoping it adds some additional clarity:
We expect the pairing flow to help drive logins when Fenix lands in the release channel but since iOS had before/after data in regards to the roll-out of the pairing experience (unlike Fenix), we observed that it hurt their registration numbers. Fenix and Fx iOS have the same pairing UX so we believe that the Android release channel will suffer the same fate when Fenix replaces Fennec.

We also tried to stick to the most minimal UX change to resolve this problem to avoid the Fenix team more work in what is likely a very busy time.

For reference, here is the mirror bug on the iOS side:
https://github.com/mozilla-mobile/firefox-ios/issues/7016

**Comment by AnaMedinac** [comment]
After talking to @betsymi and @j19s84, this is the proposed design: 

<img width="377" alt="image" src="https://user-images.githubusercontent.com/22782298/88957581-0ecff780-d26d-11ea-851b-65b6fee051d4.png">

Where the `Create one` button leads to the same webpage as `Use Email instead` button.

**Comment by mcarare** [comment]
@mozilla-mobile/ux  Can UX specify the color to be used for the "create account" text, in dark/light theme? Thank you!

**Comment by apbitner** [comment]
@mcarare I don't believe we change the color of inline text links, we just add an underline.

Also just to clarify, the last screenshot above is for iOS, so the only change needed for Fenix is the addition of the "No account? .... " sentence.

**Comment by mcarare** [comment]
@apbitner It will be helpful to have an Android screenshot then. It's really confusing not having complete specs. Thank you!

**Comment by apbitner** [comment]
@mcarare here's what the updated screen would look like in Fenix - https://share.goabstract.com/634f7381-3cae-47e9-b686-5b8e8a21786b?mode=design&sha=8f8eb8c8cfb464937f96392eed3bc239750fc840

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build 9/21 with **Google Pixel 4 XL (11).**
Note that I was able to create a new account without problems.
I added this bug regarding the position of the new text. https://github.com/mozilla-mobile/fenix/issues/15262
