### ISSUE TITLE
FNX-13954 ⁃ [Bug] Breaking interaction between PiP and PWAs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12825]
## Steps to reproduce
1. Install a PWA: twitter.com
1. Open a youtube video in fullscreen, tap the home button to switch to PiP.
1. Open the PWA
1. On the PiP view, tap the expand/full-screen button.
1. Check the app.
    1. Expected behavior
You can browse the PWA in portrait mode(if possible?)
Going back from PiP to full-screen opens the app correctly.
    1. Actual behavior
The PWA is opened in landscape and can't rotate it.
Expanding the video puts the whole app in PiP (maybe the same issue as https://github.com/mozilla-mobile/fenix/issues/10555)
![1595423335078](https://user-images.githubusercontent.com/4037709/88181278-4cae9980-cc37-11ea-9291-70cbdfe3d37a.JPEG)

### Device information
* Android device: Huawei P20 (Android 9)
* Fenix version: 79.0.0, Nightly 7/22

**Comment by Mugurell** [comment]
This should be fixed in the next nighty.

(the portrait/landscape visual artefacts are already happening, probably because of us forcing orientations, not in the scope of this issue)

![FixedMediaFullscreenOrientation](https://user-images.githubusercontent.com/11428869/89310363-424fbf00-d67d-11ea-9c76-8b8836b3c7f0.gif)
[Video](https://drive.google.com/file/d/1r9embT7mZxdcK7ecoagraw--zhYvpqix/view?usp=sharing)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200810 from 8/10`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)

► Video
![20200810-114811](https://user-images.githubusercontent.com/51314259/89766147-56257600-db00-11ea-97df-cf094f3fffdf.gif)

**Comment by data-sync-user** [comment]
➤ Petru Lingurar commented:

Should be fixed in AC by https://github.com/mozilla-mobile/android-components/issues/7964 ( https://github.com/mozilla-mobile/android-components/issues/7964 )

**Comment by Mugurell** [comment]
Closing as per https://github.com/mozilla-mobile/fenix/issues/12825#event-3637830575
