### ISSUE TITLE
[Bug] Visual bug on opening Wikipedia citations

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12908]
## Steps to reproduce
Got to a Wikipedia page
Click on a citation while the bottom bar is hidden

### Expected behavior
Citation is visible 

### Actual behavior
It is half blocked by a white band
![Screenshot](https://user-images.githubusercontent.com/33252312/88414108-f6d61f00-cdf9-11ea-9d29-90006244a8ca.png)UNITO-UNDERSCORE!20200724-220339!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3887)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that the issue is reproducible on Firefox Preview Nightly 200729 (Build #22110610).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by NotAFile** [comment]
Can confirm this affects 81.1.1-beta.5 (Build #2015763955) on Android 10

**Comment by RachitKeertiDas** [comment]
So, I think this happens only when the bottom toolbar is minimized.
When the bottom toolbar is visible, the citation is visible.

Swiping up to reveal the bottom toolbar causes the citation to move up and the toolbar to appear properly below it

Nightly( Build #2015765747) on Android 10

**Comment by s-ankur** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/14660

**Comment by anotherus3r** [comment]
Yes, this is still happening on Nightly 201222 17:01 (Build #2015782923), with a dark grey overlay blocking half of the citation when Fenix is set to dark theme. Scrolling the page a bit so that the address bar fully appears makes the citation pop-up jump above it, revealing the previously hidden information.

**Comment by NotAFile** [comment]
I can confirm this is still broken

**Comment by NotAFile** [comment]
I can confirm this is still broken on Fenix Beta 96.0.0-beta.3

**Comment by delia-pop** [comment]
Hi, @s-ankur , on my end this issue is no longer reproducible in the latest Firefox 107.1.0, Beta 108.0b6 and Nightly 108.0a1 from 11/09. The citations are properly displayed even when the toolbar was hidden prior to opening the citation. Tested with Google Pixel 6 (Android 13).
Are you still able to reproduce it? Please feel free to re-open the ticket should the issue re-occur. 

https://user-images.githubusercontent.com/89388888/200803615-1da8ac2c-8ed8-42c0-a06a-c6cba43a91bb.mp4

**Comment by NotAFile** [comment]
Can not reproduce, seems to be fixed indeed!
