### ISSUE TITLE
FNX2-15547 ⁃ [Bug] Privacy possum currently seems to be unmaintained

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12913]
I noticed on https://github.com/cowlicks/privacypossum/issues that the extension seems to be unmaintained and the last release was about a year ago. Maybe mozilla can adopt the project? Still there are a lot of known unfixed bugs in the software. I feel like keeping this addon might be harmful especially as it is added to a pre selected list of addons.

**Comment by hakkikaancaliskan** [comment]
Agreed. I think there should be a limit for unmaintained time like if there is no release for 1 year, add on should be removed because they could cause some real privacy, security problems.

**Comment by cadeyrn** [comment]
I do not agree at all with the statement that an add-on is "unmaintened" or could cause "privacy" oder "security" problems only because there was no update for one year. I already developed at least 15 add-ons for Firefox and some of my add-ons didn't get updates for a year or longer, too. It doesn't mean at all that they are abandoned or have serious issues. That's not true. Sometimes there is just no reason to publish an update for such a long time.

Sure, if Privacy Possum is unmaintained then it's a valid discussion whether it makes sense to bundle Fenix with it or not to do this. But please don't argue with the time since the last update. Instead the developer of the add-on should be asked about the current state.

**Comment by hwinnemoe** [comment]
Also, the developer shows activity in this branch from 21 May 2020: https://github.com/cowlicks/privacypossum/commits/design-from-firefox and this PR https://github.com/cowlicks/privacypossum/pull/237

**Comment by ShatteredPixel** [comment]
Can somebody tell me if this extension meets the criteria for including it in the recommended extensions since it got recommended in Fenix due to being a "Recommend Extension": https://support.mozilla.org/en-US/kb/recommended-extensions-program

In some of the points to be included in the recommended extentions program Mozilla says: 

>* Is the extension actively developed? Developers of Recommended extensions must actively maintain their content to ensure it evolves with the needs of Firefox users. 

>* Does the extension offer an exceptional user experience? Recommended extensions should be delightful to use. Curators look for content that’s intuitive to manage and well designed. 

Currently I think both of these points do not check out. Though, the info in the https://github.com/mozilla-mobile/fenix/issues/12913#issuecomment-663827864 does give some hope.


I don't use Privacy Possum. But as its name is suggesting it has something to do with privacy and since user tracking technics evolve very frequently and in a very unique way regularly the extension should keep up with them. Otherwise, users might get a false sense of privacy and security, I think.

**Comment by cadeyrn** [comment]
> Can somebody tell me if this extension meets the criteria for including it in the recommended extensions

It wouldn't be part of the recommended extensions programm if it wouldn't meet the criteria…

> Currently I think both of these points do not check out.

It was already proven in the previous comment that the extension is still being actively developed (last commit two months ago, that's fairly recent) and regarding the second point: That's your personal opinion. But as you can also see in the same PR: This PR is about a better design so the result should be more "delightful to use".

> But as its name is suggesting it has something to do with privacy and since user tracking technics evolve very frequently and in a very unique way regularly the extension should keep up with them.

This is very generally speaking, but not specifically with regard to Privacy Possum. If you know something that Privacy Possum could do better then you should report this to the developer of Privacy Possum. But to be clear: The fact that Pricacy Possum is a privacy add-on does not mean at all that Privacy Possum has to change every aspect of the user's privacy. So even if it doesn't do all it could do it's no reason to exclude the add-on from Fenix.

**Comment by s-ankur** [comment]
Hi everyone, I opened this issue because I noticed this issue (https://github.com/cowlicks/privacypossum/issues/222) as well as several other extremely high priority bugs (e.g.. not able to sign in to google) which have not been addressed for quite some time. I understand that some extensions don't really require that many updates but privacy possum is not one of them. So while I'm not sure whether a compulsory update schedule is necessary for all Addons, in this case I feel that some intervention is required.

**Comment by ShatteredPixel** [comment]
I agree with you buddy some people just want to argue for the arguments' sake. It's not like we are passing our time by complaining here. 

The extension is not maintained for a long time now. It's been over a year. It's a fact that everybody need to accept. If you don't keep up with the software environment it's running in then it'll age and so much so that there comes a point in time that Iit just won't work.


There's reason why companies like Google [force](https://www.xda-developers.com/developers-new-app-play-store-api-level-26/) the developers to [target their apps to the higher API levels](https://developer.android.com/distribute/best-practices/develop/target-sdk) of [Android API every year](https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html?m=1). I think something like this should be made mandatory to AMO's recommended add-ons as well. Well, I have also heard from Mozilla that as long as the extensions work on the recent versions of Firefox they won't remove it from the Recommended Extentions program. But as you said, Google sign in doesn't work when this extension is installed. This is why I said technology evolves _really_ fast and the developers should adapt and maintain their software with it. A year in the technology world is an insane amount of time period that I don't think I need to explain. Things just change really fast! Everyone needs to accept this reality.


You can see that what's become of this extension. It's design is outdated, its UX is something that I cannot understand very well. It has critical bugs as you say. This is what happens when you don't update your softwares regularly to adopt with the environment it's running in (in this case it's a Browser). And not to mention if the add-on has security issues then it'll open up the attack vectors in the browser itself. 


As you have linked to the issue, you can see that there's no sign of the developer responding to user issues. It's looks like it's been months like that. And in another comment even the Mozilla's UX designers are waiting to get an update to the add-on to test it. And they haven't seemed to have replied to them as well. 



I think, we as end users should move on when the developers are not maintaining the software thay have built. Instead of wasting our time in asking questions that they'll probably never answer.

**Comment by s-ankur** [comment]
It seems the maintainer came back, closing as no longer relevant
