### ISSUE TITLE
The "What's New" article has the Fenix release date as "Summer 2020". Change it to use months instead of seasons

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12942]
Article link: https://support.mozilla.org/en-US/kb/firefox-android-upgrade-faqs?redirectslug=firefox-preview-upgrade-faqs&redirectlocale=en-US

![Screenshot](https://user-images.githubusercontent.com/68282543/88459441-36ad0d00-ceb3-11ea-8ecc-adff3b858579.jpg)UNITO-UNDERSCORE!20200725!UNITO-UNDERSCORE!200115.jpg!

_Okay, this is something that I had filed a few months ago but I think that issue was completely ignored! And the issue has been repeated again! I couldn't find the issue link since I had delete my previous GitHub account. GitHub is so hard or has become so hard to search!_ :wink:

Mozilla, I want you to answer one question: Are you a global organization? or do you officially operate in only one country? Or only in a particular geographical area?

If you say yes to the question for "Global organization" then please I request you to change the article to state the dates in months not in seasons. 

I don't need to say this but you must already know that [due to Earth being tilted at an angle of 23.5 degrees relative to the orbital plane, Earth has 4 seasons](https://earthsky.org/earth/can-you-explain-why-earth-has-four-seasons). So think about it, which "Summer 2020" are you talking about when these seasons vary when they happen across the globe? Somewhere on Earth, the Summer has already begun or half way through and somewhere on Earth the Summer is already over! It's not like you have done it for the first time, previously a few months ago the article stated "Spring 2020", at least in `en_US` language.

So, change your point of view and use something else; like you could use months instead of "seasons'" names, for example. :grinning:

P.S. No matter how many times you ignore me, I'll be there to remind you again and again! :wink:

Thank you! :grinning:

**Comment by s-ankur** [comment]
Perhaps this issue is better suited for https://github.com/mozilla/bedrock/issues. It is the repo for mozilla.org

**Comment by kbrosnan** [comment]
This copy is correct. Bedrock is not the correct place to discuss SUMO documentation. I would start with the SUMO contributor support Forums. https://support.mozilla.org/en-US/forums

**Comment by ShatteredPixel** [comment]
@kbrosnan which copy is correct? I'm a bit out of context on this. 

But, I have highlighted the issue. Now it's up to Mozilla to figure out whether to solve this issue or not. I'm sorry to have reported this issue in the wrong place. But I don't know a lot about where, how, when, to whom, to report issues. I'm just a somewhat normal user turned issue and bug reporter overnight. ;)

For me, it's straight; I have some concerns regarding the software I'm using and there's a place I can easily tell them that there are problems, and it's called GitHub and let them know. And I'm already helping the developers and your users a lot by whatever means I can (really a lot, please believe me!), just because I appreciate what Mozilla is doing. 


Mozilla can keep things however they want since I don't have any problems with "Spring 2020", "Summer 2020" since I have already figured out which " Spring 2020" or "Summer 2020" Mozilla is talking about. I have figured that out just like those _several_ versions of Firefox that were available on the Play Store a few weeks ago (well, I have to admit that I too was confused a lot at one point especially at the ending of this situation or has it ended in reality? don't know how many general avarage users are/were in how much confusion and installed who knows which and what versions and who knows are now on which versions thinking something like this: I was on a version which didn't have that many bugs I don't know why but I'm experiencing bugs very frequently nowadays 🤔 or somebody said Firefox supported a lot of add-ons but I don't know why there are just only a few countable add-ons available and it also lacking in several features ,I wonder if it is Firefox or some Malware app masquerading as Firefox 🤔 or there are two versions looking exactly the same, I wonder which one is Stable or which one is Beta 🤔 or for that matter which one is _real_ Nightly; may be I'll install this "Mozilla Firefox Android...." and are now on Beta version thinking that it is a Release version, or oh! I tested their browser but they ended up leaving me in the middle of nowhere; what about my data; I'll have to lose it now; I shouldn't have helped them testing this thing! Or I don't know why but I'm getting updates on the Play Store daily instead of one in every few weeks 🤔 or someone was helping me on Reddit telling me which versions to install and helping me solve my problems; may be I should ask them but I wonder where they are now since I haven't seen them writing any articles or replying to comments from users facing problems that much 🤔 And worst yet, they might have installed some Malware app thinking it was Fenix as you know Play Store has them and several apps try to mimic each other even the icons themselves regularly. But you kept justifying whatever you did. I again tried to point what you might be doing wrong but I was cast aside as if...)! As I previously said this not for I,  Me, and myself and all that... It's about the other users, other people... I don't know if all them will figure out what it is.  

I have highlighted the issue and I think my work is done here. Now it's up to Mozilla to redirect this issue to correct place and get this corrected. Or keep it as it is. It's Mozilla's choice now. And I'll try to respect their choice.

I have a lot of pending Anime to watch, I cannot waste my time arguing here... Bye...bye... ;)
