### ISSUE TITLE
[Bug] Link autofill in search bar also fill non links in some cases

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12993]
## Steps to reproduce
(As an example) Copy the fenix version given below to clipboard 
Go to search bar

### Expected behavior
I have not copied a link so nothing should be recommended

### Actual behavior
It recommended this
![Screenshot](https://user-images.githubusercontent.com/33252312/88576512-2b98df00-d063-11ea-907a-2a0631590c06.png)UNITO-UNDERSCORE!20200727-234442!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus zenfone
* Fenix version: 
Nightly 200727 06:00 (Build #22090608)
AC: 52.0.20200725130253, f41b7fbbc
GV: 80.0a1-20200724093206
AS: 61.0.10

**Comment by TrianguloY** [comment]
When searching you can enter any text, and this option is a reminder of what you have in your clipboard, so it is still useful to search for arbitrary content.

The current behaviour is nice, but the text is misleading.
Probably the best option is to change the message to "Paste content from clipboard" (instead of "Fill link from clipboard").
