### ISSUE TITLE
FNX-14231 ⁃ [ADD-ON] Make "Redirect AMP to HTML" available as an add-on within Fenix

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#13058]
### What is the user problem or growth opportunity you want to see solved?
From the add-on description page:

> When you see an AMP page, you’re likely seeing a page served directly by Bing or Google who can suck in information about what you do on that page. Keep the web decentralized and say “No!” to search engines that want to take control over the web.

### How do you know that this problem exists today? Why is this important?
This add-on was available for Fennec at https://addons.mozilla.org/en-US/android/addon/amp2html/, and is not available in Fenix now.

### Who will benefit from it?
Users receiving or clicking links to AMP versions of websites, which is probably the majority.

**Comment by da2x** [comment]
I’m the developer behind AMP2HTML. Just let me know if you need anything from my side. AFAIK, there’s no process or documentation for making extensions Fenix-ready.

**Comment by andreicristianpetcu** [comment]
There are 2 issues here 1) running it in Fenix in order to see that it works on a dev machine and 2) publishing it for others

I tried 1) here but I failed. This used to work.
https://github.com/mozilla-mobile/fenix/issues/11308#issuecomment-669347733

For 2)  An extension needs to be part of the recommended extensions program. They only take recommended extensions as builtin extensions.
As a side note they might allow "side loading" in Nightly and Beta before they allow full access to addons.mozilla.org in stable.

**Comment by teohhanhui** [comment]
Why this is important: AMP is bad for the Web. This extension fixes that.

**Comment by liuche** [comment]
We would like to expand our support to other add-ons. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

**Comment by sheikh-azharuddin** [comment]
This option should be inbuilt in the browser rather than mozilla suggesting users to try a 3rd party extension! 😑
