### ISSUE TITLE
FNX2-15644 ⁃ Install any Android extension from AMO

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#13059]
First of all sorry if this was already reported, I did not find anything and I also asked on Matrix

### What is the user problem or growth opportunity you want to see solved?
there are lots of extensions on addons.mozilla.org that cannot be installed

### How do you know that this problem exists today? Why is this important?
this used to work in fennec

### Who will benefit from it?
users who used addons

**Comment by creesch** [comment]
[Unfortunally they seem to have decided months ago that this is not a priority](https://github.com/mozilla-mobile/fenix/issues/5315) the best I could gather is that maybe, possibly at some point they might support this in some capacity. Meanwhile I am stuck using a version of firefox that will not be updated or be forced to not use the extensions I want. Not to mention that for the users of a extension I am a dev of we also have to tell them the same disappointing news.

**Comment by andreicristianpetcu** [comment]
are you a contributor @creesch ?

**Comment by creesch** [comment]
Nope, if I was I wouldn't have said "they". I am simply sharing what my experience has been so far in trying to get an answer if this will be possible at some point in the future. And so far the answer is that a vague "possibly in some capacity".

**Comment by andreicristianpetcu** [comment]
None of the other issues tackes AMO install. Now Fenix is replacing Fennec. I want an official answer, not opinions and interpretations of other issues. Sorry if I'm too blunt.

**Comment by creesch** [comment]
> None of the other issues tackes AMO install.

They do, as it is the same issue technically speaking. The way it works before fenix is that you can only install extensions that have been signed through AMO. So the installation mechanism for AMO hosted extensions or other extensions is technically identical. 

> I want an official answer, not opinions and interpretations of other issues. 

I understand, the statements I linked however are from a product owner at mozilla and really do comment on the same matter. In any case I do understand is that if not the sort of answer you are looking for. 

> Sorry if I'm too blunt.

No you just being clear, I'd also like na actual official answer that is clear on the matter.

**Comment by yoasif** [comment]
At the very least, it would be good to have this for beta/nightly, even if it is not released to production until later. That way, we could at least help the team validate which add-ons could conceivably even be added to recommended extensions, allowing the team to follow the "letter of the law" in production.

**Comment by andreicristianpetcu** [comment]
you can test extensions with web-ext run

**Comment by liuche** [comment]
Duping to #11308

**Comment by andreicristianpetcu** [comment]
Sideloading sounds like a hacky way to bypass Mozilla's extension verification. That is why I reported a different issue. @liuche

**Comment by liuche** [comment]
We would like to expand our support to other add-ons. At this time, we don’t have details on enabling support for extensions not part of the Recommended Extensions program in the new Firefox for Android. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

**Comment by Juraj-Masiar** [comment]
@liuche So why did you started rollout without any way to enable addons?
If the API didn't changed and addon creators can upgrade and test their addons with [web-ext](https://github.com/mozilla/web-ext/releases), then why disable them all?
Who is deciding this? And are you personally ok with this?

I've put a lot of effort into making my addons compatible with Android and I use some of them daily, so you can imagine how frustrated I feel right now...

**Comment by creesch** [comment]
@liuche 

> We would like to expand our support to other add-ons.

That is the exact same line I have seen several times. The problem is that without context it doesn't mean much at all. Does it mean more extensions are going to get verified or does it mean that at some point it will be made possible to install any signed extension like was possible before?

**Comment by andreicristianpetcu** [comment]
this should be closed

**Comment by drwetter** [comment]
[CAD](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete) is also affected, despite it seems a _Recommended Extension_. 

I don't get why this hasn't been solved since February, at least for the recommended extensions. That wouldn't hurt if the update of Fenix wasn't forced recently. See also here: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/758

Okok, there's ublock origin which works, but other than it reminds me a bit on mobile Chrome browsers -- excuse my sarcasm ;-)

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/12655

https://github.com/mozilla-mobile/fenix/issues/13059
https://github.com/mozilla-mobile/fenix/issues/14339
https://github.com/mozilla-mobile/fenix/issues/14452
https://github.com/mozilla-mobile/fenix/issues/14489
https://github.com/mozilla-mobile/fenix/issues/15154

**Comment by 89z** [comment]
So I see here: https://github.com/mozilla-mobile/fenix/issues/13059#issuecomment-666455286

That supposedly this is a dup of #11308. If you go there, that one is closed too, as a dup of #14034. Finally, that one has been closed and locked, with a solution supposedly as this:

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly

Well, I followed those instructions, got the "Debug menu enabled", but no "Custom Add-on collection" option showed up. @liuche @kbrosnan @caitmuenster do you care to comment on why you are shutting down conversation, when the issue is not resolved, and people are asking for this over, and over and over again, as can be seen in the linked issues here?

As a workaround, I have rolled myself back to Firefox Android 68:

https://apkmirror.com/apk/mozilla/firefox

and will be staying firmly there until this is sorted.

**Comment by 89z** [comment]
https://github.com/openstyles/stylus/issues/647

**Comment by jesus2099** [comment]
You can download Firefox for Android 68.11.0 from official place, IMO is safer: https://archive.mozilla.org/pub/mobile/releases/68.11.0/

Check your copy architecture (ABI), to know which APK to download with: https://play.google.com/store/apps/details?id=com.kgurgul.cpuinfo

Everything still works great with 68.11.0.

**Comment by drwetter** [comment]
Security wise it's not a good idea to install an old, unmaintained browser -- at least not for me.

Wonder though whether there's a will to get this running or whether it's just a lack of resources.

**Comment by caitmuenster** [comment]
@89z Can you post a screenshot of your settings menu after you have enabled Debug mode? That might help us troubleshoot the problem.

**Comment by 89z** [comment]
@caitmuenster I was able to get the "Custom Add-on collection" to come up, I stand corrected. In my case, I want to install a popular addon, Stylus. It should be a trusted addon, it has over 3,000 stars on GitHub:

https://github.com/openstyles/stylus

I want to share with you the flow of the old process, with Firefox 68:

1. visit https://addons.mozilla.org/firefox/addon/styl-us
2. touch Download file
3. touch ADD

Now here is the process with new Firefox:

1. touch Play Store
2. search Firefox Nightly (as normal Firefox doesnt work anymore)
3. touch Firefox Nightly
4. touch install
5. touch Open
6. touch three dot menu
7. touch Settings
8. touch About Firefox Nightly
9. touch NIGHTLY logo five times
10. touch back
11. touch Custom Add-on collection
12. realize that I have to register on AMO to continue
13. scream interally

Honestly what is this, lets see how much we can torture our users?

**Comment by 89z** [comment]
@caitmuenster its been 4 months, do you really have nothing to say? Do you really think the flow I detailed above is an acceptable process?

**Comment by caitmuenster** [comment]
Hi @89z, I'm sorry to hear about your frustration. We do not have any immediate plans to fix this issue. If that changes, it will be announced on the [Add-ons Community Blog](https://blog.mozilla.org/addons/).

**Comment by jesus2099** [comment]
> you can test extensions with web-ext run

What is it exactly?
It's it a way to use latest Firefox for Android with any extensions (Violent monkey, stylus)?
https://duckduckgo.com/?q=web-ext+run+Firefox&t=fpas&iax=images&ia=images

Still using v68, here untill either Vivaldi or Firefox for Android provides extensions again.

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/11292

**Comment by dbenjaminmiller** [comment]
If you want to use an extension from AMO, just use Fennec F-Droid (the F-Droid build of the current version of Fenix).

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/11292

https://github.com/mozilla-mobile/fenix/issues/13059
https://github.com/mozilla-mobile/fenix/issues/18477

**Comment by drwetter** [comment]
It says last version is from 2 months ago. :-(

**Comment by dbenjaminmiller** [comment]
> It says last version is from 2 months ago. :-(

Maybe you need to update your repository. I have 90.1.1, which was released only a few weeks ago.

**Comment by 89z** [comment]
@dbenjaminmiller the F-Droid site is garbage, 40 seconds just to load the page:

~~~
PS C:\> curl -I https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 41408    0     0    0     0      0      0 --:--:--  0:00:42 --:--:--     0
~~~

**Comment by dbenjaminmiller** [comment]
> @dbenjaminmiller the F-Droid site is garbage, 40 seconds just to load the page:
> 
> ```
> PS C:\> curl -I https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0 41408    0     0    0     0      0      0 --:--:--  0:00:42 --:--:--     0
> ```

Unfortunately, they are having some server issues now. With the F-Droid app you can download the app from a mirror and this is much faster.  Once you have the F-Droid build installed, you can enable custom add-ons from a collection on AMO in exactly the same way you would on Firefox Nightly.

**Comment by 89z** [comment]
> Once you have the F-Droid build installed, you can enable custom add-ons from a collection on AMO in exactly the same way you would on Firefox Nightly.

@dbenjaminmiller what is the point of using F-Droid for this, when by your own admission Firefox Nightly can already do this? Custom Add-on collections require registration with AMO, so this is not an acceptable suggestion.

**Comment by dbenjaminmiller** [comment]
> > Once you have the F-Droid build installed, you can enable custom add-ons from a collection on AMO in exactly the same way you would on Firefox Nightly.
> 
> @dbenjaminmiller what is the point of using F-Droid for this, when by your own admission Firefox Nightly can already do this? Custom Add-on collections require registration with AMO, so this is not an acceptable suggestion.

The F-Droid build is the stable version, which may be preferable to the nightly version of the browser (which is, of course, buggier). It's true that you need an AMO account to make a collection. It's also true that you can only persistently install XPIs from AMO. (I've mentioned this in an issue myself, for those of us who want to install XPIs from elsewhere for persistent testing, for instance.)

If you are adverse to making your own Mozilla Firefox account, even with a dummy email, you can use one of the comprehensive collections such as this without creating an account. https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/

I agree that installing add-ons from outside AMO would be good. My personal experience is that I happen not to need any add-ons from outside AMO for normal use, and I've been using Fennec F-Droid with a custom collection to use whatever add-ons I want ever since last year. It's not necessarily ideal, but the original issue asks for the ability to install any extension from AMO. This is how it's possible. I'm just trying to help anyone who wants to know.

**Comment by drwetter** [comment]
@dbenjaminmiller : you're right. Now it's only 2 weeks. It seems maintained.

When coming from Mozilla fenix - I probably loose bookmarks et al unless I save them, right?

**Comment by 89z** [comment]
> If you are adverse to making your own Mozilla Firefox account, even with a dummy email, you can use one of the comprehensive collections such as this without creating an account. https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/

This isnt acceptable. The question isnt "how can I install add-ons that Mozilla has approved", or "how can I install add-ons that Adam Novak thinks are cool" [1]. The issue is, how to install an arbitrary XPI file. Yes this comes with risks, but if a user is using Nightly, and/or a user change changed some setting to allow this, and/or user is giving explicit informed consent, then it should be possible.

As it currently stands, I dont think its possible, which makes current Firefox basically a clone of Google Chrome, a "fake browser" with training wheels that you are not allowed to remove, as Mozilla is not willing to trust its own users.

1. https://addons.mozilla.org/firefox/collections/16201230/What-I-want-on-Fenix

**Comment by dbenjaminmiller** [comment]
> > If you are adverse to making your own Mozilla Firefox account, even with a dummy email, you can use one of the comprehensive collections such as this without creating an account. https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/
> 
> @dbenjaminmiller this isnt acceptable. The question isnt "how can I install add-ons that Mozilla has approved", or "how can I install add-ons that Adam Novak thinks are cool" [1]. The issue is, how to install an arbitrary XPI file. Yes this comes with risks, but if a user is using Nightly, and/or a user change changed some setting to allow this, and/or user is giving explicit informed consent, then it should be possible.
> 
> As it currently stands, I dont think its possible, which makes current Firefox basically a clone of Google Chrome, a "fake browser" with training wheels that you are not allowed to remove, as Mozilla is not willing to trust its own users.
> 
>     1. https://addons.mozilla.org/firefox/collections/16201230/What-I-want-on-Fenix

Yes, I do absolutely agree with you that the user should be able to install an arbitrary XPI file. The question in this issue was (how to) "Install any Android extension from AMO". I answered that. I already have an issue open about installing XPIs from outside. I too am disappointed that this has not been added to Fenix. I think it would good perhaps if one of the Fenix forkers (such as Mull, for instance) were to add this in a patch. But that's off-topic in this repo. Mozilla should undoubtedly add this.

**Comment by dbenjaminmiller** [comment]
> @dbenjaminmiller : you're right. Now it's only 2 weeks. It seems maintained.
> 
> When coming from Mozilla fenix - I probably loose bookmarks et al unless I save them, right?

That's right, unless you sync it, you'll lose your bookmarks.

**Comment by jesus2099** [comment]
@andreicristianpetcu, what is web-ext run?
@dbenjaminmiller, I have just installed Fennec F-Droid, but now how do we install extensions?
I see the same limited list as on official Firefox.
If I go directly to [an add-on page](https://addons.mozilla.org/fr/firefox/addon/violentmonkey/), I cannot install.

**Comment by dbenjaminmiller** [comment]
> @andreicristianpetcu, what is web-ext run?
> @dbenjaminmiller, I have just installed Fennec F-Droid, but now how do we install extensions?
> I see the same limited list as on official Firefox.
> If I go directly to [an add-on page](https://addons.mozilla.org/fr/firefox/addon/violentmonkey/), I cannot install.

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
Same steps as for Nightly

**Comment by 89z** [comment]
@jesus2099 please dont listen to @dbenjaminmiller as installing Fennec F-Droid is pointless. It doesnt give you any powers beyond the normal Android Firefox, IE you cant install arbitrary XPI, only Mozilla approved XPI, or from a registered AMO account.

**Comment by dbenjaminmiller** [comment]
> @jesus2099 please dont listen to @dbenjaminmiller as installing Fennec F-Droid is pointless. It doesnt give you any powers beyond the normal Android Firefox, IE you cant install arbitrary XPI, only Mozilla approved XPI, or from a registered AMO account.

It's not pointless. It's literally the answer to the original question about installing any extension *from AMO*. It gives the power to install any extension in AMO, as opposed to only the ones in the specific collection Mozilla sets as the default. You CAN'T change the collection in vanilla Firefox. Here you can. That is to say, the vanilla build does not even give you access to all of AMO, whereas this does.

What you CAN'T do with either is install an arbitrary XPI from outside AMO. I agree that's a perfectly legitimate thing that should be possible. But that's not what the original title of this issue covers.

**Comment by 89z** [comment]
> You CAN'T change the collection in vanilla Firefox.

Yeah, you can. Its funny you would even make a comment like this, as you literally are contradicting yourself from you previous comment:

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by dbenjaminmiller** [comment]
> > You CAN'T change the collection in vanilla Firefox.
> 
> Yeah, you can. Its funny you would even make a comment like this, as you literally are contradicting yourself from you previous comment:
> 
> https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

You can do it in nightly builds from Mozilla. You can't do it in stable vanilla builds. They disable the flag for the non-nightly releases. So a user who wants to be able to change the collection without using the unstable nightly release can't use the vanilla Mozilla build.

**Comment by 89z** [comment]
> You can do it in nightly builds from Mozilla. You can't do it in stable vanilla builds. They disable the flag for the non-nightly releases.

Who cares? If you can do it with Nightly, then installing Fennec F-Droid is pointless. The only benefit of Fennec F-Droid, would be if it could install an arbitrary XPI, which youve already admitted it cant.

**Comment by dbenjaminmiller** [comment]
> Who cares? If you can do it with Nightly, then installing Fennec F-Droid is pointless. The only benefit of Fennec F-Droid, would be if it could install an arbitrary XPI, which youve already admitted it cant.

Well, it might not matter either way for your use case, but many of us do prefer to use a stable version as our daily driver instead of updating nightly to test the latest commits.

**Comment by 89z** [comment]
> Well, it might not matter either way for your use case, but many of us do prefer to use a stable version as our daily driver instead of updating nightly to test the latest commits.

@dbenjaminmiller and there it is. No one cares what you favorite mobile browser it. It doesnt help the cause. The issue here, is how to install an arbitrary XPI, or the best workaround to that end. You fanboying some random brower only helps to distract and confuse the ultimate goal, please stop.

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/20647

**Comment by PolicyPuma4** [comment]
Make sure to express your opinions here https://connect.mozilla.org/t5/ideas/expand-add-on-compatibility-in-firefox-for-android/idi-p/191.

**Comment by 89z** [comment]
@PolicyPuma4 Mozilla doesn't care. They have made it very clear that they just want to be a Google Chrome clone, and remove any possibility of users installing custom extensions. They only want Firefox to be "baby play time" with approved apps only. They don't trust their own users, otherwise this requirement of registering would never have had even the chance of becoming policy.
