### ISSUE TITLE
FNX2-15651 ⁃ [Bug] translate release locales to android locale codes

### ISSUE THREAD

**Issue by Pike** [mozilla-mobile/fenix#13066]
## Steps to reproduce
Create a release build

### Expected behavior
Hebrew and Indonesian files should be kept, in `values-iw` and `values-in`.

### Actual behavior
The files are removed.

**Comment by person808** [comment]
Note for QA: Similar to #7104 we need to check if Hebrew and Indonesian files are present in `fennec-production` builds. I updated the `releases/v79.0.0`, `releases/v79.1.0` and `master` branch so I'm not sure if you can check apks built from each branch?

**Comment by Pike** [comment]
Looking at the v80 branch build, https://firefox-ci-tc.services.mozilla.com/tasks/VAmXWrKwRIaahs5KBC_GOQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FVAmXWrKwRIaahs5KBC_GOQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log, I see

```
REMOVE: bg, uz
```

which matches @Delphine 's list, given that `ms`, `ne-NP`, and `nv` don't have files in Fenix at all yet, so they don't show up in the available locales (it's listing files, not l10n.toml).

I wasn't able to find v79.* builds.

**Comment by sflorean** [comment]
@Delphine @Pike 
Tested on 80.0.0 build and Hebrew and Indonesian languages are displayed in the app, currently, 86 languages are being listed. 

> Note for QA: Similar to #7104 we need to check if Hebrew and Indonesian files are present in `fennec-production` builds. I updated the `releases/v79.0.0`, `releases/v79.1.0` and `master` branch so I'm not sure if you can check apks built from each branch?

@person808 I think we will need signed apks/other builds in order to check. on 79.0.0 We checked the existing builds but the languages aren't updated.
We will check to see if we can build local.

**Comment by sflorean** [comment]
@person808 We tried to make a local build for 79.0.0 with the recent changes but we don't have languages displayed in the app (maybe because it built en) and we don't know how to add them. If there is another way to test this, or someone could provide us a build, we are happy to check.

**Comment by person808** [comment]
If its working for the 80.0.0 builds it should be working for all of them since we already verified the script is run in #7104. Just to be safe I ran `python2 ./automation/taskcluster/l10n/filter-release-translations.py` locally on all three branches and we are not removing Hebrew or Indonesian resource files anymore.
