### ISSUE TITLE
Add new bookmarks to the top of the bookmarks list

### ISSUE THREAD

**Issue by 12sunflowers** [mozilla-mobile/fenix#13079]
New bookmarks adds at bottom of main list of others bookmarks

New bookmarks must be at top over old bookmarks list not at bottom like now

Lenovo 7304F
Android 7
Fenix 79.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4161)

**Comment by 12sunflowers** [comment]
Can i ask, then it will be fixed?

**Comment by CrustyNpl** [comment]
I experienced the same issue and I hope they do implement sorting functions for Firefox Mobile.
It would make things a lot easier for people after the latest updates.
The only way I found to fix the issue was shown here.[Link](https://www.reddit.com/r/firefox/comments/i6eq6z/new_firefox_issue_bookmarks_dont_export_properly/)
Good luck if you don't have access to a PC/desktop Firefox and Sync.
Another Reddit post linking to this post [Link](https://www.reddit.com/r/firefox/comments/i4rref/firefox_android_bookmark_sort_function_new_update/)
I wish they could have customized/improved this feature with those updates.

**Comment by 12sunflowers** [comment]
Can we hope that bookmark sorting feature will be added or fixed near future?

**Comment by boek** [comment]
Closing as a dup #13426
