### ISSUE TITLE
Compact tabs (like Fennec)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13098]
### What is the user problem or growth opportunity you want to see solved?
User feedback; people miss this (see Play Store reviews).

### How do you know that this problem exists today? Why is this important?
Play store reviews, other bugs: https://github.com/mozilla-mobile/fenix/issues/955#issuecomment-597324854, https://github.com/mozilla-mobile/fenix/issues/5805#issuecomment-625417740

### Who will benefit from it?
People who prefer a compact tab layout.

**Comment by SergeiFranco** [comment]
Yes please!!!

**Comment by U-B-Glade** [comment]
Support that Request, please realise that.

**Comment by smhmore** [comment]
Tab view tile option is missed.
As is the ability to sort tabs.
And 'recently closed tabs' in History

**Comment by OsadebamwenEvbuomwan** [comment]
![Uploading Screenshot_20200901-091734.png…]()
This I a very good implementation of compact tabs in fenix UI. This is the fork [iceweasle](https://github.com/interfect/fenix/releases/)

**Comment by OsadebamwenEvbuomwan** [comment]
If this is ever implemented pls leave it as an option cause I slightly prefer the current one than compact tabs

**Comment by cadeyrn** [comment]
> This I a very good implementation of compact tabs in fenix UI. This is the fork iceweasle

This is not compact all. It shows less (!) tabs than the current implementation in Firefox and will be even more true if Mozilla decides to allow two lines for the page title.

**Comment by TheRealOsas** [comment]
It's not perfect but I think it is a starting point

**Comment by madb1lly** [comment]
Hi all,

Compact tabs in Fennec could show 8 tabs in the tab switcher (on my phone) whereas Fenix can only show 7. One tab difference doesn't sound like much, but it is about 15% more, which is a lot.

If the tabs list actually extended to the top of the screen I think we could actually see 8 in Fenix.

Cheers 🙂

Cheers 🙂

**Comment by Matth7878** [comment]
IMHO tab tray should use all screen and homepage should be a third tab like the list of private tabs.
So we would have : homepage / tabs / private tabs.

**Comment by R2R29** [comment]
> ### What is the user problem or growth opportunity you want to see solved?
> 
> User feedback; people miss this (see Play Store reviews).
> ### How do you know that this problem exists today? Why is this important?
> 
> Play store reviews, other bugs: [#955 (comment)](https://github.com/mozilla-mobile/fenix/issues/955#issuecomment-597324854), [#5805 (comment)](https://github.com/mozilla-mobile/fenix/issues/5805#issuecomment-625417740)
> ### Who will benefit from it?
> 
> People who prefer a compact tab layout.

My suggestion was to give us the option to have it like it is or to have other ways to use it, including a compact one like you mentioned.

**Comment by abhijitvalluri** [comment]
@TheRealOsas thank you for the shout out! I implemented the "compact tabs" layout in the forked version of Fenix. In fact I made a lot more tweaks to it since then, and here is my latest changes: https://github.com/interfect/fenix/pull/65

I tried to make it as compact as feasible without being too small and weird. My layout seems to be about as compact as the old Fennec style layout, at least on my 1080p Pixel 2 phone screen. I have some screenshots of the old browser and my fork for comparison, with the same websites open. I still use the old Fennec browser due to its tab layout and add-ons support, but I am happy with the forked Fenix as well as it fills the holes I felt.

Here are the screenshots:

#### Old Fennec
<img src="https://user-images.githubusercontent.com/17151327/92184489-4112dd00-ee49-11ea-8e38-3a5bf57a36ae.png" width="350" />

#### Forked Fenix with compact tabs
<img src="https://user-images.githubusercontent.com/17151327/92184532-6273c900-ee49-11ea-8410-34ada11bd4b0.png" width="350" />

#### Forked Fenix with (mostly) unmodified layout
<img src="https://user-images.githubusercontent.com/17151327/92184540-69024080-ee49-11ea-9e7f-540b223b814a.png" width="350" />

As you can see, the old Fennec could show 6 full tabs + 2 partial tabs. The forked Fenix with my compact tabs layout can also show 6 full + 2 partial tabs. It could show even more if the BottomSheet popup could occupy more screen space. The (mostly) unmodified Fenix layout can only show 6 tabs.

The advantage of this compact layout is even more prominent in large screens which can show more than 2 tabs in a row, and also in landscape mode. As you can see the old Fennec can show 6 tabs in landscape mode, and similarly the forked Fenix with the compact tabs layout can also show 6 tabs. The Fenix without compact tabs can only show 3 and a very tiny portion of the 4th. 

#### Old Fennec
<img src="https://user-images.githubusercontent.com/17151327/92184986-871c7080-ee4a-11ea-9d67-737f618f9b97.png" height="350" />

#### Forked Fenix with compact tabs
<img src="https://user-images.githubusercontent.com/17151327/92185004-8f74ab80-ee4a-11ea-8fcf-3e8b307dee42.png" height="350" />

#### Forked Fenix with (mostly) unmodified layout
<img src="https://user-images.githubusercontent.com/17151327/92185014-94395f80-ee4a-11ea-9a05-d96af0ff7b49.png" height="350" />

**Comment by TheRealOsas** [comment]
@abhijitvalluri thanks for all your hard work. I and others like me appreciate your efforts 😘. 
Keep on the food work 👍

**Comment by TheRealOsas** [comment]
and for any jealous fenix dev. we appriciate your efforts too 👍

**Comment by Poopooracoocoo** [comment]
There's one thing - fenix uses a sheet so you cant quickly open a new tab by double tapping on the tab switcher

**Comment by yoasif** [comment]
@abhijitvalluri would you be willing to upstream this to Fenix?

**Comment by cadeyrn** [comment]
Also the latest screenshots show that it's not compact at all and misses the point of this issue. It shows less tabs than the default layout. If it's not about a compact layout the issue should be renamed to avoid confusion.

**Comment by ekager** [comment]
We've added grid view as an option. Closing
