### ISSUE TITLE
FNX2-18816 ⁃ [Bug]Bookmark selection checks not displayed after deleting an item VIA edit mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#13156]
## Prerequisites
Have a couple of bookmarks

## Steps to reproduce
1. Open the Bookmarks section
2. Tap the  ⋮ button next to a Bookmark and select Edit
3. Delete the Bookmark
4. Tap to multi-select the remaining bookmarked items

### Expected behavior
Check signs should be displayed for the selected items

### Actual behavior
The check signs aren't displayed

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200731
• Fenix Beta 80.0.0-beta.2 from 7/31

### Notes

► Video
![20200731-123240](https://user-images.githubusercontent.com/51314259/89022644-05a56000-d32b-11ea-977a-489dd8c86199.gif)

**Comment by person808** [comment]
What seems to be happening is that on [this](https://github.com/mozilla-mobile/fenix/blob/cd2532349d8059b2ad23b399bc631e191b714f81/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkAdapter.kt#L62) line `new[newItemPosition] in newMode.selectedItems` is returning false. The only difference that I can see is that the `position` field for `new[newItemPosition]` and the item in the selected items is different.

**Comment by person808** [comment]
Hm so because our DiffUtil callback only checks the bookmark's title and url, we don't rebind the viewholder after returning to the Bookmarks screen. This is resulting in a mismatch between the actual bookmark in the tree and the one the viewholder is bound to. I'm going to try checking all properties of the bookmark in our DiffUtil callback and use change payloads so we can be smart about not updating viewholders when properties like `position` are changed. As a bonus this might fix #13280 as well.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build 8/19** with **Google Pixel 4 XL (11).**
![20200819-140756](https://user-images.githubusercontent.com/42831109/90629705-7fdd4c00-e228-11ea-81ca-fa177463a08c.gif)
