### ISSUE TITLE
[Bug] Cannot scroll to submit button on Bugzilla

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#13198]
## Steps to reproduce

Go to bug page, type comment, try to submit. 

![Screenshot_20200801-162812.png](https://user-images.githubusercontent.com/158471/89103728-475e0580-d414-11ea-9c71-29d2a094c682.png)

### Expected behavior

Can scroll down to submit button. 

### Actual behavior

Impossible to scroll down to bottom of the page, cannot hit Submit. 

### Device information

* Android device: Pixel 2
* Fenix version: current Nightly

**Comment by TheW0LVERIN3** [comment]
This also happens when toolbar is at the bottom Same on ublock origin setup page and about:config page and possibly others. It is like the sites are rendered underneath the toolbar when it is at the bottom. This makes it so that the last part of the page is not visible or interactable. I am on the latest nightly btw.

**Comment by kbrosnan** [comment]
Duplicate #13055
