### ISSUE TITLE
[Bug] With ETP disabled the trackers are still displayed as blocked

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#13221]
## Steps to reproduce
1. Open any page from https://senglehardt.com/test/trackingprotection/test_pages/
2. Tap on the ETP shield - Protection Settings.
3. Disable the ETP.
4. Go back to the opened tab from step 1.
5. Reload the page, and observe the elements from the page.

### Expected behavior
All the elements from the page are displayed as NOT blocked.

### Actual behavior
All the elements from the page are displayed as blocked.

### Device information
* Android device: all
* Fenix version: 8/3 Nightly build, 79.0.2 RC

<img src="https://user-images.githubusercontent.com/40694158/89177932-2e309280-d595-11ea-9489-12e5e45d8abb.gif" width="300" height="550" />

**Comment by ekager** [comment]
@Amejia481 it looks like this is a possible regression from https://github.com/mozilla-mobile/android-components/issues/6917 (reverting this change shows correct behavior when ETP is off).

**Comment by Amejia481** [comment]
Thanks for the report I'm taking a look at it!

**Comment by Amejia481** [comment]
@ekager I think when we are switching off the "Enhanced Tracking Protection" switch, we are passing `TrackingProtectionPolicy.recommended() ` to  the [settingsUseCases.updateTrackingProtection(policy)](https://github.com/mozilla-mobile/fenix/blob/9612c3f16d6ce11a32eae4c01b8ac0fb6008fc7f/app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt#L72) instead of passing `TrackingProtectionPolicy.none()`, see https://github.com/mozilla-mobile/fenix/blob/78c6ee43c33e4adadf43e512d08738f5836811d6/app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt#L33

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Firefox Nightly build from 8/5 with Sony Xperia Z5 Premium (Android 7.1.1), OnePlus 5T (Android 9), Samsung Galaxy Tab S6 (Android 9), and Google Pixel (Android 10).
