### ISSUE TITLE
Allow users to not remember history

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#13227]
### What is the user problem or growth opportunity you want to see solved?
I would like the same menu for history options as there is on desktop (see image). This way users can choose whether to keep their history, cookies, etc.
![ff](https://user-images.githubusercontent.com/66154603/89205223-adcf5900-d5b7-11ea-9480-8fdc73aa1254.png)

### How do you know that this problem exists today? Why is this important?
At the moment there is a "Delete browsing history on quit" option in the settings, but I doubt many people would use the quit button from the menu rather than just closing the app directly. These settings would provide an alternative.

### Who will benefit from it?
Users who use the "Delete browsing history on quit" option.

**Comment by cadeyrn** [comment]
As you already noticed there is already a "Delete browsing history on quit" option that covers the "Allow users to not remember history" use case. If it's about not using the "quit" button please note the following comment of #5865:

> Swiping close the app does not return a unique signal to the app. To the App it looks like it has been killed in the background. To have the feature function in a consistent manner it requires some user action. Either something like Focus where there is a persistent notification or a button in the app is needed.

**Comment by mobd** [comment]
After reading through that issue I think implementing this feature would allow the quit option to be removed, while still covering everyone's use cases and providing a more natural UI.

**Comment by yoasif** [comment]
Discussed this briefly with the team on Matrix. Takeaways:

* Fenix doesn't want to close your tabs automatically because we can't reliably detect whether closing the app was a user directed action. 
* the option existed in Fennec
* people liked the option and miss it
* competing browsers have it

Fennec:

![image](https://user-images.githubusercontent.com/152493/91340147-811cf480-e7a5-11ea-8215-19dbe833e7aa.png)

Edge:

![image](https://user-images.githubusercontent.com/152493/91340184-8d08b680-e7a5-11ea-9ca4-3281cb7436db.png)

I have seen a decent amount of user feedback for this, and it is distinct from both private browsing modes and "quit" options and it'd be great if we could take another look at this, especially since user expectations may be more forgiving than we expect for this option - it worked for people in Fennec and works (presumably) for Edge users.

**Comment by mobd** [comment]
Thanks for your update on this. On desktop, there is a distinction between browsing and download history, and open tabs, cookies etc.

For the first case there could be a simple checkbox whether to remember them or not. For the rest it needs to be persisted throughout a session. This could be done by having a persistent notification in case a user chooses to clear data on quit, like mentioned before. I think this would be less of a bother to people than having to quit the app through the menu.

Do you think the team would agree to an implementation like this?

**Comment by liuche** [comment]
Having a persistent notification (like Focus does) could be a good solution. I'll copy this comment to the other issue #5865, and dupe this issue.

Also, have you tried using Focus for Android? It covers your exact request, in the way you asked!
