### ISSUE TITLE
[Bug] Multicodec widevine video can't be played

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13243]
## Prerequisites
- Have media.eme.enabled set to true in about:config
- Have media.eme.require-app-approval - false in about:config
### Steps to reproduce
1.  Go to https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016
2. From DRM drop down choose Widevine DRM.
3. Tap on Play button for video file named **"Sintel 4k (multicodec, Widevine)"**. (Should be the 4th video from the list)
### Expected behavior
The video can be played.
### Actual behavior
Error message is displayed.
Error description https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016
### Device information

* Android device: Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 8/4, Firefox Preview Beta 80.0.0-beta.2

Note:
- It's reproducible with both mentioned builds and devices.
- The same video can be played in Chrome.
- Issue is related to feature request #1175
- The same error message is displayed for 5th video from the widevine DRm list - named **Sintel 4k (multicodec, Widevine, ads)** - but the ad is going to be played only the video is affected
**Screen**
![Screenshot_20200729-194906](https://user-images.githubusercontent.com/49859863/89264268-4bb83780-d63b-11ea-8461-4cc3a81bde1e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4321)

**Comment by Diana-Rus** [comment]
I'll be closing this issue based on comment: https://github.com/mozilla-mobile/fenix/issues/1175#issuecomment-666102554
> > ```
>3. Should the video eme keys be displayed when media.eme.require-app-approval is set to false, or in case from permission >level, the user denies the api's request?
>
>If the approval is set to false, or the user does not approve the api request, then I do not believe the key should show.
>'''

**Comment by Diana-Rus** [comment]
Reopening the issue as this still reproduces Nightly with:
- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)
- Google Pixel 3XL (Android 9)
The videos with settings from description's prerequisites should be played (comment from issue [13461](https://github.com/mozilla-mobile/fenix/issues/13461#issuecomment-671751514))

**Comment by cpeterso** [comment]
Reopening because I can still reproduce this bugs when trying to play the "Sintel" Widevine video here:

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=debug_compiled

I get the following error:

> Shaka Error MEDIA_VIDEO_ERROR (3,,NS_ERROR_DOM_MEDIA_FATAL_ERR (0x86e0005): Error creating decoder for audio/opus)

**Comment by cpeterso** [comment]
Reopening because I can still reproduce this bugs when trying to play the "Sintel" Widevine video here:

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=debug_compiled

I get the following error:

> Shaka Error MEDIA_VIDEO_ERROR (3,,NS_ERROR_DOM_MEDIA_FATAL_ERR (0x86e0005): Error creating decoder for audio/opus)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813909

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
