### ISSUE TITLE
FNX2-18892 ⁃ SPIKE: Add LeanPlum instrumentation for in-product user feedback

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#13289]
We would like to build a non-intrusive way of asking for user feedback (rating/reviews) within the browser (preferably without taking the user out of the app)

### Acceptance Criteria
- Asking for feedback once every 4 months (if dismissed)
- Shown to active users (e.g. users opened the app at least 5 times and completed a meaningful action (creating a collection, switching to reader mode, installing an add-on, or looking at ETP or Private Browsing settings.
- Prompt should include deeplink to play store review page.
- If a user says no to the prompt 3 times, we should stop asking them.

Also see: https://developer.android.com/guide/playcore/in-app-review

**Comment by bifleming** [comment]
Timebox to 5 points

**Comment by liuche** [comment]
The first step would be to meet w/ the Mobile engagement team to determine the requirements for this.

The goals we're aiming for would be:
- have an idea of what the Leanplum work would be from talking to the team
- recommend the Google API vs the Leanplum as an option

**Comment by person808** [comment]
From a brief reading of the API guide:

1. The actual code to launch the review popup looks fairly simple. Something like this (basically copied from the docs):

```kotlin
val request = manager.requestReviewFlow()
request.addOnCompleteListener { request ->
    if (request.isSuccessful) {
        // We got the ReviewInfo object
        val reviewInfo = request.result
        val flow = manager.launchReviewFlow(activity, reviewInfo)
        flow.addOnCompleteListener { _ ->
            // The flow has finished. The API does not indicate whether the user
            // reviewed or not, or even whether the review dialog was shown. Thus, no
            // matter the result, we continue our app flow.
        }
    } else {
        // There was some problem, continue regardless of the result.
    }
}
```

The docs say we should request the `reviewInfo` ahead of time, but only when we know we want to show the review dialog which is what most of the work on our end would be.

2. The API comes with some strict requirements on its usage listed in the overview linked in comment 0. No prompting the user to trigger the review dialog and theres a quota to how often this dialog can be triggered. If we exceed the quota, this API will silently fail, which is why we should not trigger the review dialog through explicit user action (such as a dialog asking them to rate our app).

3. There is a page on testing the API (https://developer.android.com/guide/playcore/in-app-review/test). This is getting into an area I'm not familiar with so just read the page I guess? I might whip up a small test app to try out the API if I have the time.

**Comment by person808** [comment]
So there are actually undocumented suspending versions of the functions. So the code might even look like this:

```kotlin
lifecycleScope.launch {
    val manager = ReviewManagerFactory.create(this@MainActivity)
    val reviewInfo = manager.requestReview()
    manager.launchReview(this@MainActivity, reviewInfo)
}
```

Do these functions throw exceptions when they fail? Or do they just fail silently? I have no idea.

I think one way we could handle the limitations of the API is to trigger the dialog when the user takes an action that already results in a UI change. That way if the API silently fails due to the quota or some other reason the UX doesn't appear broken.

**Comment by person808** [comment]
> This seems like the perfect example of where this API would be used. When the user selects "Yes" you request the review dialog and hopefully they leave a positive review. If they've exceeded their quota and nothing appears it doesn't break the user experience because they weren't expecting a call to action anyways. Either way the prompt closes when they press "Yes" but ideally they'll also get a review dialog to follow.
> Where this wouldn't work is if you have a dedicated "review our app" button since you can't guarantee the review API will provide a dialog successfully and users clicking it with nothing happening is a broken experience.

https://www.reddit.com/r/androiddev/comments/i450fh/leverage_the_inapp_review_api_for_your_google/

**Comment by liuche** [comment]
This is done, so we can close it. Follow along in #13507
