### ISSUE TITLE
In Reader Mode, tapping the address bar should expose the actual moz-extension URL

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#13398]
Currently, the address bar shows the original page's URL even if you tap on it. There is no way to view or fetch the Reader Mode URL from there. There is a workaround: bookmark the page, edit the bookmark, view/copy the URL from there. Quite tedious.

If the user wants to share a Reader Mode URL with someone for whatever reason (like the page is full of ads and other irrelevant stuff), they should be able to do that without using the workaround I mentioned above.

- The menu options like Share can continue working with the original URL.
- But simply by tapping the address bar and copying the moz-extension URL from there, a user should be able to copy/share the Reader Mode URL.

(I think desktop Firefox should also show the full about:reader URL in the address bar, if the domain name at the top is changed to show the full URL of the original page instead.)

**Comment by csadilek** [comment]
> In Reader Mode, tapping the address bar should expose the actual moz-extension URL.

`moz-extension://` URLs are not shareable and only stable per device. So, the current behaviour is intentional. When sharing via the share menu, we already use the original URL instead. The `moz-extension` URL will not work for anyone else you share it with.

We have https://github.com/mozilla-mobile/android-components/issues/2879 on file to use a custom protocol similar to `about:reader`.

**Comment by opusforlife2** [comment]
Is there any issue tracking this functionality in _this_ repo, though? If not, shouldn't there be one?
