### ISSUE TITLE
Delay when loading top site

### ISSUE THREAD

**Issue by SlowNicoFish** [mozilla-mobile/fenix#13400]
## Steps to reproduce
* Fresh start Firefox
* Tap any most visited site

### Expected behavior
Load in as fast as typing in the address bar or maybe faster
### Actual behavior
Several second delay when tapping a site
### Device information
Android 10
* Android device: Pixel 3 XL
* Fenix version: 80.0.0-beta.4 (Build #2015756491)
Have also tried other versions and the same thing happens.

**Comment by jonalmeida** [comment]
> Tap any most visited site

@SlowNicoFish what are you tapping on exactly? A top site or a tab in the tabs tray?

**Comment by SlowNicoFish** [comment]
> > Tap any most visited site
> 
> @SlowNicoFish what are you tapping on exactly? A top site or a tab in the tabs tray?

![Screenshot_20200807-190935~2](https://user-images.githubusercontent.com/19305293/89670542-af638e80-d8e1-11ea-93a3-db16a74aec06.png)
A top site

**Comment by SlowNicoFish** [comment]
I'm starting to think that Unlock origin is to blame here. I can relate to the problems in #8251

**Comment by liuche** [comment]
@SlowNicoFish does this happen when you have ublock origin disabled? This is still a bad experience but would be helpful to have more specific context.

**Comment by SlowNicoFish** [comment]
@liuche No it seems like it doesn’t. It’s even faster with tracker protection on strict which blocks ads too.
So now I’m using only the built in adblocker because Ublock is a little bit too slow for me

**Comment by liuche** [comment]
Thanks! I'm going to dupe this to #8251.

**Comment by GottHeit** [comment]
Have this too, but not only on most visted pages/favorites. 

Before I found this thread I was wondering about the promise of a faster Firefox, because older versions were much faster in my opinion. Because of this and other problems like not sortable tabs, favorites not opening in existent tabs, no bookmarks on homescreen, senseless collections - which are not even syncing, etc... is gave Vivaldi a try and was really suprised that Vivaldi was soooo much faster. 

So I started a little testing:

With activated ublock every tab loads slowly when opening one. And every link a selected page loads slowly too. 
It starts loading and after 1-3 seconds on a blank screen page is shown. After disabling ublock firefox is much faster, instantly loading and showing pages. 

And it seems to me that this is likely reproducible with other add-ons, like ghostery and noscript (only one activated while testing - but doesn´t make a difference if just one oder all three of em are activated). 

Looks like it is conlicting with the internal Tracking protection. Turning that off and after activating ublock again surfing is much smoother and faster, but not as fast as only using internal tracking protection without any add-on.

**Comment by GottHeit** [comment]
Have this too, but not only on most visted pages/favorites.

Before I found this thread I was wondering about the promise of a faster Firefox, because older versions were much faster in my opinion. Because of this and other problems like not sortable tabs, favorites not opening in existent tabs, no bookmarks on homescreen, senseless collections - which are not even syncing, etc... is gave Vivaldi a try and was really suprised that Vivaldi was soooo much faster.

So I started a little testing:

With activated ublock every tab loads slowly when opening one. And every link a selected page loads slowly too.
It starts loading and after 1-3 seconds on a blank screen page is shown. After disabling ublock firefox is much faster, instantly loading and showing pages.

And it seems to me that this is likely reproducible with other add-ons, like ghostery and noscript (only one activated while testing - but doesn´t make a difference if just one oder all three of em are activated).

Looks like it is conlicting with the internal Tracking protection. Turning that off and after activating ublock again surfing is much smoother and faster, but not as fast as only using internal tracking protection without any add-on.
