### ISSUE TITLE
FNX-14608 ⁃ [Bug ]Collections: UI shows selected tab but isn't selected

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#13427]
## Steps to reproduce
1. Open few tabs
2. go to home (+ button)
3. Click on save as collection (screenshot 1)
### Expected behavior
No tab is selected, or all tabs or selected?
### Actual behavior
One tab is shown as selected but isn't really selected as you can't save it (screenshot 2)

You need to click again to select it (screenshot 3)
### Device information

* Android device: Android 9, Pocophone F1
* Fenix version: Nightly 200809 06:01

### Screenshots
1. 
<img src="https://user-images.githubusercontent.com/58657617/89733361-4c930400-da55-11ea-9a62-edcd40d5f3f7.png" width="300">
2. 
<img src="https://user-images.githubusercontent.com/58657617/89733368-5583d580-da55-11ea-80e6-de3cc22c3dfc.png" width="300">

3. 
<img src="https://user-images.githubusercontent.com/58657617/89733378-69c7d280-da55-11ea-873e-0ff6f971ca9d.png" width="300">

**Comment by yoasif** [comment]
The STR could be simplified as:

1. load 1 or more pages in tabs
2. open a new tab (hold on tab switcher button and select new tab)
3. tab tab switcher icon

What happens:

A tab shows a "selected" highlight (which seems to be what Fenix shows in the tab tray when *within* a tab to show which tab will be shown if a user taps back or into the content area behind the tab tray)

Expected result:

Nothing should show as highlighted because no tab is open (or make it so tabs are created that appear as separate tabs in the tab tray [this is preferable and matches other browsers, including Fennec and Chrome).

**Comment by liuche** [comment]
Since we just added this feature, @topotropic do you have any thoughts on the initial state when opening tab collections multi-select?

**Comment by yoasif** [comment]
@liuche @topotropic this doesn't just apply with multi-select - the highlight doesn't seem to be related to a selection.

**Comment by topotropic** [comment]
The highlight indicates which tab was last visited;

As for multi-select, I agree that it can be confusing to have a highlighted tab in there. If it's feasible we should not highlight anything in multi-select mode. Thanks!

**Comment by Mugurell** [comment]
Waiting on https://github.com/mozilla-mobile/fenix/issues/15968 to have a common solution to both the list based and the grid based tab trays layouts.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 12/11 Nightly build with Samsung Galaxy Tab S6 (Android 10).
No tab is highlighted in multi-select mode.
