### ISSUE TITLE
FNX-14622 ⁃ Allow disabling the "swipe to switch tabs" gesture

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#13442]
As a continuation of https://github.com/mozilla-mobile/fenix/issues/10240 we need new toggles allowing users turn on/off the new tabs gestures implemented in
- https://github.com/mozilla-mobile/fenix/issues/11862 - Swipe up the bottom bar to see the tab menu
- https://github.com/mozilla-mobile/fenix/issues/3481 - Switch Tabs via Swiping Address Bar

### What/Requirements
New toggles for the above features.
UX directions:
- These new toggles should only be available if the respective feature is enabled (not turned off because of feature flags)
- Toggle names - **UX pending**
- They should stay in a new "Gestures" section inside the "Settings -> Customize" menu
<img src="https://user-images.githubusercontent.com/11428869/88888703-7a9f6980-d247-11ea-85f0-dc591ea0e379.png" width="270" height="480">

**Comment by Mugurell** [comment]
Tagging @betsymi for the toggle names 
and @person808 for visibility since he worked on these features.

**Comment by betsymi** [comment]
Here are strings for all four gestures. Can you confirm that the first two will be what will be implemented? The ones from the mock are outdated. 

- Touch and pull to refresh
- Scroll to hide toolbar
- Swipe toolbar sideways to switch tabs
- Swipe toolbar up to open tabs

**Comment by Mugurell** [comment]
@betsymi wrote:
> Here are strings for all four gestures. Can you confirm that the first two will be what will be implemented? The ones from the mock are outdated.
> 
> * Touch and pull to refresh
> * Scroll to hide toolbar

Yes, these are features that depend on gestures and which users may want to disable.
They are both activated by vertical swipes
- when the page is at top and user swipes down the pull to refresh throbber should appear, if enough distance swiped, when releasing the throbber the page will be refreshed. 
About the string, not sure "touch and" is needed. Normally the feature is referred to as "swipe to refresh / pull to refresh"
- when the user swipes up the toolbar will be animated out of the view, and reverse.


The result should be seen here
![SwipeToRefreshAndHideToolbar](https://user-images.githubusercontent.com/11428869/91532207-a67d4000-e916-11ea-9e7e-015d8998e943.gif)
[video](https://drive.google.com/file/d/1-A19AVosPFrKJkgBp0VyK4F5scBHBDkd/view?usp=sharing)
[apks to test](https://drive.google.com/drive/u/2/folders/1cvrpb_nS1z5dbJ4IfD58esB73qd0yUMm)

**Comment by betsymi** [comment]
> @betsymi wrote:
> 
> > Here are strings for all four gestures. Can you confirm that the first two will be what will be implemented? The ones from the mock are outdated.
> > 
> > * Touch and pull to refresh
> > * Scroll to hide toolbar
> 
> Yes, these are features that depend on gestures and which users may want to disable.
> They are both activated by vertical swipes
> 
>     * when the page is at top and user swipes down the pull to refresh throbber should appear, if enough distance swiped, when releasing the throbber the page will be refreshed.
>       About the string, not sure "touch and" is needed. Normally the feature is referred to as "swipe to refresh / pull to refresh"
> 
>     * when the user swipes up the toolbar will be animated out of the view, and reverse.
> 
> 
> The result should be seen here
> ![SwipeToRefreshAndHideToolbar](https://user-images.githubusercontent.com/11428869/91532207-a67d4000-e916-11ea-9e7e-015d8998e943.gif)
> [video](https://drive.google.com/file/d/1-A19AVosPFrKJkgBp0VyK4F5scBHBDkd/view?usp=sharing)
> [apks to test](https://drive.google.com/drive/u/2/folders/1cvrpb_nS1z5dbJ4IfD58esB73qd0yUMm)

Ok, we can lose the "touch and". Could you post a screenshot when the strings are in so I can QA the strings?

- Pull to refresh
- Scroll to hide toolbar
- Swipe toolbar sideways to switch tabs
- Swipe toolbar up to open tabs

**Comment by Mugurell** [comment]
A setting for toggling `#3481 - Switch Tabs via Swiping Address Bar` is implemented in https://github.com/mozilla-mobile/fenix/issues/10240.
This ticket can remain open to track addind a new setting for toggling `#11862 - Swipe up the bottom bar to see the tab menu` when that feature fill be ready.

**Comment by liuche** [comment]
An update from UX on this from @mheubusch:
1. Pull to refresh: when it is ready it can go to release, NO setting to control it
Pull to refresh is a default for many Android browsers. Here, we are shipping something to catch up to their feature set. Because it’s shipped with so many browsers, we think that people would not only expect pull to refresh to be a default behaviour. We also think that they don’t want to turn it off. So we should ship this gesture to Release, and not create a setting for it.

2. Dynamic/Pinned toolbar: when this is ready it can go to Release, with a setting under "Toolbar" section
Hide address bar on scroll is a default for us and many other Android browsers. Some contributors wanted the address bar to always show, independent of scrolling. That’s fine. We can ship it on release, but we won’t make this persistent toolbar behaviour a default. It will be controllable under Toolbar Settings.

3. Swipe toolbar up for Tabs Tray #11862: this feature should stay on Nightly, but we can include a setting
Other gestures control more advanced features. For example: swipe left/right on address bar to switch tabs. So far, we only received a signal that people want this feature through our contributors. But they’re not our general audience. So let’s hold off on shipping these other gestures, and keep them only in Nightly.

4. Swipe toolbar left/right to switch tabs: TBD (since it is already in release)

**Comment by cadeyrn** [comment]
@liuche

> Swipe toolbar up for Tabs Tray #11862: this feature should stay on Nightly, but we can include a setting
Other gestures control more advanced features. For example: swipe left/right on address bar to switch tabs. So far, we only received a signal that people want this feature through our contributors. But they’re not our general audience. So let’s hold off on shipping these other gestures, and keep them only in Nightly.

To be clear: Do you mean a) enable these features only by default on Nightly or b) not to ship these features at all to other release channels, so no way for users to enable it?

**Comment by Mugurell** [comment]
I created https://github.com/mozilla-mobile/fenix/issues/15629 for phasing out the gestures settings which would have contained these settings also.

Looks like `Swipe toolbar up for Tabs Tray` will need a new setting in a different location.
If `Swipe toolbar left/right to switch tabs` will have a setting or not is TBD.

**Comment by apbitner** [comment]
@betsymi @mheubusch are you able to help @Mugurell with the above request?
