### ISSUE TITLE
FNX-14659 ⁃ [Bug] HomeActivity doOnPreDraw Runnable memory leak

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#13479]
/cc @mcomella

### Steps to reproduce

Unfortunately no STR.

### Expected behavior

No leak.

### Actual behavior

Leak pattern: instance field android.os.Message#next

┬───
│ GC Root: System class
│
├─ android.app.ActivityThread class
│    Leaking: NO (MessageQueue↓ is not leaking and a class is never leaking)
│    ↓ static ActivityThread.sMainThreadHandler
├─ android.app.ActivityThread$H instance
│    Leaking: NO (MessageQueue↓ is not leaking)
│    ↓ ActivityThread$H.mQueue
├─ android.os.MessageQueue instance
│    Leaking: NO (MessageQueue#mQuitting is false)
│    ↓ MessageQueue.mMessages
│                   ~~~~~~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.next
│              ~~~~
├─ android.os.Message instance
│    Leaking: UNKNOWN
│    ↓ Message.callback
│              ~~~~~~~~
├─ org.mozilla.fenix.HomeActivity$onCreate$$inlined$doOnPreDraw$1$lambda$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing java.lang.Runnable
│    ↓ HomeActivity$onCreate$$inlined$doOnPreDraw$1$lambda$1.this$0
│                                                            ~~~~~~
├─ org.mozilla.fenix.HomeActivity$onCreate$$inlined$doOnPreDraw$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing java.lang.Runnable
│    ↓ HomeActivity$onCreate$$inlined$doOnPreDraw$1.this$0
│                                                   ~~~~~~
╰→ org.mozilla.fenix.HomeActivity instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.fenix.HomeActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = 1e93f34f-d98e-4e77-97e6-2516665827a4
​     watchDurationMillis = 3473
​     retainedDurationMillis = -1

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 6397 ms

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 841d19e8be8b0d85e207524073c1ce2a10b3b670

**Comment by mcomella** [comment]
The culprit is this `doOnPreDraw`: https://searchfox.org/mozilla-mobile/rev/7a6438e589bd0f020e0429c072ea966973f228ef/fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#164

If the view is detached from the window, `doOnPreDraw` is expected remove the listener from the view. However, it's unclear if this happens before or after the Activity is destroyed (from a theory perspective, the view hierarchy lifecycle should be less than the Activity's because it is created by the Activity so it _should_ be safe). There is an `Activity.onDetachedFromWindow` call so we can verify this behavior.

However, the Runnable that is created inside `doOnPreDraw` captures the Activity via `this` to use the `visualCompletenessQueue`, an Activity member variable. Assuming this is the problem (but we should verify doOnPreDraw is not), traditional solutions would be to not create an anonymous Runnable (since they may easily be modified to capture `this`) and:
- Use a `WeakReference` for the activity or VC queue (maybe preferred so we can avoid changing too much right now?)
- Move the VC queue to Application (I think we put it in HomeActivity to handle the case that there are multiple HomeActivities though – is that safe?)

---

We also call `doOnPreDraw` here: https://searchfox.org/mozilla-mobile/rev/7a6438e589bd0f020e0429c072ea966973f228ef/fenix/app/src/main/java/org/mozilla/fenix/perf/StartupReportFullyDrawn.kt#68 If we don't have a leak from that line, it's likely the issue is in the Runnable, not the pre draw listener.
