### ISSUE TITLE
FNX-14664 ⁃ Add Search Engines to search

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#13484]
Depends on #13482

We'll have to rethink how we do this compared to the current search implementation. I think we may be able to use the new `ConcatAdapter` we brought in for TabsTray `TabsTrayView:141`

**Comment by jorsn** [comment]
Is this a pure UI problem? I don't understand why a feature that always existed in firefox and is so simple is removed in the new version.

This is an important issue, because for normal users it's not feasible to find out the search string and enter manually, e.g. for startpage, which doesn't display the search URL because their search form uses a POST request by default.

Another suggestion: Enable changing the order of search engines. Because the engines later in the list are only usable if you scroll, hence inconveniently.
