### ISSUE TITLE
[Bug] Autofill dont show any saved logins at all

### ISSUE THREAD

**Issue by PhpMadman** [mozilla-mobile/fenix#13515]
### Expected behavior
Login info should be autofilled, for example github.

### Actual behavior
No site display either list of saved logins or autofill the logins. Even when I type in a username it wont show the autofil.

### Device information

Firefox Sync signed in
* Android device: Galaxy S10+ Android 10
* Fenix version: 
79.0.3 (Build #2015757147)
80.0.0-beta.5 (Build #2015757139)

**Comment by sheikh-azharuddin** [comment]
Correct I am also facing same issue.. Auto fill is not working.... .

**Comment by sv-ohorvath** [comment]
@PhpMadman if you have multiple logins saved for the same website, that is: https://github.com/mozilla-mobile/fenix/issues/5551
If that's not the case, then you could add info to this bug: https://github.com/mozilla-mobile/fenix/issues/12498
I'll close this as a duplicate, because the other one has a bit more info and history.
