### ISSUE TITLE
[Bug] CJK font not using correct Android fonts resulting in characters displaying weirdly

### ISSUE THREAD

**Issue by dotjaz** [mozilla-mobile/fenix#13863]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1660369 for more information

## Steps to reproduce
Open any website containing Chinese characters
e.g. https://m.mydrivers.com/newsview/706709.html
http://en.m.wiktionary.org/wiki/%E9%97%A8
### Expected behavior
Show characters using correct font
### Actual behavior
Show characters using fallback font, resulting in weird shapes and non-uniform width

 "复" is narrower, (amongst other subtle shape issues)
![Screenshot_20200816-090052_Firefox](https://user-images.githubusercontent.com/5112407/90323244-02080f00-dfa2-11ea-9510-20aa2e380c80.png)

门 is using completely wrong shape, using Japanese shape instead of Chinese

![Screenshot_20200816-092549_Firefox](https://user-images.githubusercontent.com/5112407/90323387-e9005d80-dfa3-11ea-9b91-37842301d724.png)
![Screenshot_20200816-092601_Chrome](https://user-images.githubusercontent.com/5112407/90323388-eaca2100-dfa3-11ea-9406-f1b51635f86a.png)

### Device information

* Android device: Galaxy S20 Ultra, P20 Plus (any device)
* Fenix version: Any version to date including any Fennc and Fenix

**Comment by makotokato** [comment]
@dotjaz , I have the questions since I cannot reproduce on Chrome.

- What your default locale setting of Fenix and System?  Some code points are shared with Simplified Chinese, Traditional  Chinese and Japanese, so we select default font from these settings and content lang attribute. This site has no lang attribute, so it is import for you locale setting.  I think that content should use lang attribute for this situation.
- If you change system setting to Traditional Chinese (zh-TW) or Simplified Chinese (zh-CN) and Fenix UI lang is system default, is your issue resolved?

**Comment by dotjaz** [comment]
> @dotjaz , I have the questions since I cannot reproduce on Chrome.
> 
>     * What your default locale setting of Fenix and System?  
I use en-AU as my system locale. Chromium-based browser does not have the issue. 


> 
>     * If you change system setting to Traditional Chinese (zh-TW) or Simplified Chinese (zh-CN) and Fenix UI lang is system default, is your issue resolved?
No, changing locale doesn't fix anything. Fenix still uses incorrect font. Any webpage that has the characters "复","关","门" etc has the issue. As you can see while I'm typing. The first 2 characters appears narrower than the 3rd, and the 3rd character has the wrong shape (locale zh-CN).

![Screenshot_20200826-114918_Firefox](https://user-images.githubusercontent.com/5112407/91246023-4362a080-e792-11ea-8d7a-aab0d4987599.png)

**Comment by kbrosnan** [comment]
@dotjaz if you could add the font info from your phone to bug [1660369](https://bugzilla.mozilla.org/show_bug.cgi?id=1660369#c1). That would be helpful.

**Comment by makotokato** [comment]
@dotjaz
I guess that Chrome's font priority for Kanji is that zh-CH is higher than ja-JP. But Firefox's priority is different due to some historical reason. Since this code point is shared with some locales and glyph design is different per locale unfornunately, this occurs.
To resolve this, Android 6+ has system setting for language.  [System] App has `[System]` - `[Language & Input]` - `[Language]` to allow multiple locale support and it can set priority. (Firefox won't update this settings immediately, so restart Firefox after this change).

If this list is the following, this result is expected result for you.
1. English (United States)
2. 简体中文 (中国)
3. 繁體中文 (台湾)

If this list is the following, this result is your report.
1. English (United States)
2. 繁體中文 (台湾)
3. 日本語 (日本)
4. 简体中文 (中国)

This root cause is that web content doesn't have lang attribute. Browser cannot detect whether language we should use. So Android 6+ has this multiple locale support.

**Comment by dotjaz** [comment]
> @dotjaz
> I guess that Chrome's font priority for Kanji is that zh-CH is higher than ja-JP. But Firefox's priority is different due to some historical reason

Nope

> restart

I restarted the phone, if that's not enough I don't know what is.

> 
> If this list is the following, this result is expected result for you.
> 
>     1. English (United States)
> 
>     2. 简体中文 (中国)
> 
>     3. 繁體中文 (台湾)
> 
> 

Nope. Already told you I set the default language to zh-rCN, that's the only language on the list btw. Still wrong. How is adding a few other languages gonna help? I tested it just to humour the impossible, as expected, impossible.


> This root cause is that web content doesn't have lang attribute. Browser cannot detect whether language we should use. So Android 7+ has this multiple locale support.

Every other browser can detect it correctly, just not Firefox. It's clearly a bug not the system.

**Comment by KrasnayaPloshchad** [comment]
See:
http://www.google.com/get/noto/help/cjk

**Comment by makotokato** [comment]
I guess that I make sense this details. This issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1673155.

**Comment by makotokato** [comment]
@dotjaz 
Although we have land a fix to nightly, could you still reproduce this?
