### ISSUE TITLE
[Bug] AssertionErrorandroid.hardware.camera2.CameraManager in getOrCreateDeviceIdListLocked Expected to get non-empty characteristics

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#13956]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/9417864/?query=release%3Aorg.mozilla.firefox_beta-80.0.1-beta.2

Showing up in beta with a few crashes.

Could this be related to some recent camera changes such as https://github.com/mozilla-mobile/android-components/issues/7893 (and maybe could be handled in in-progress #13037 ) ?

**Comment by mcarare** [comment]
@liuche As far as I could gather from the info available, this is a device / Android version specific issue. The device **has a camera**, but there is an error when trying to get camera info, and our extension `hasCamera` calls a method that eventually throws that assertion error, probably due to the camera identifier on that Samsung device not starting with 0 as the code asserts:
` // Non-removable cameras use integers starting at 0 for their identifiers`.

It is a OS version specific issue, since `CameraManager` code has changed since SDK 23 and it no longer checks camera availability the same way.

IMO we could improve the `hasCamera` check by returning false when an exception is thrown by the `cameraManager`. This however will make Fenix treat devices with cameras as devices without cameras, if inconsistencies arrise, but maybe it is desired as it is not likely that the camera could be used reliably without other crashes.

Also cc @csadilek for thoughts on this. TY!

**Comment by csadilek** [comment]
> IMO we could improve the hasCamera check by returning false when an exception is thrown by the cameraManager. This however will make Fenix treat devices with cameras as devices without cameras, if inconsistencies arrise, but maybe it is desired as it is not likely that the camera could be used reliably without other crashes.

@mcarare Yes, I agree. I've already done that in https://github.com/mozilla-mobile/android-components/pull/8010

The problem here is that the device threw an https://docs.oracle.com/javase/7/docs/api/java/lang/AssertionError.html, not an exception type! It's only on user though so far according to Sentry.

**Comment by mcarare** [comment]
@csadilek Great, I haven't seen the PR. It is rather unusual, but maybe we could also catch `AssertionError`.

**Comment by csadilek** [comment]
We're catching this now as well in A-C. Closing.
