### ISSUE TITLE
[Bug] Downloaded files are listed in Downloads after being deleted from the device storage

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#13979]
## Steps to reproduce
1. Download 2-3 files.
2. Go to the device file manager and delete the files downloaded at step 1.
3. Go to Fenix  - Downloads.

### Expected behavior
The files aren't listed anymore and "No downloads here" is displayed.

### Actual behavior
The files are listed.

### Device information
* Android device: Samsung Galaxy Note 10 Android 10), Google Pixel 3 (Android 11).
* Fenix version: Nightly 8/20

cc @kglazko

**Comment by kglazko** [comment]
Right now, files in the Android Components list of downloads aren't correlated to the downloads you have on your system. There are considerations we need to think about in terms of what our Downloads list is responsible for. We can certainly choose to not display downloads that are deleted through a simple check to see if a file exists in the file path. 

Renamed or moved files would then disappear from our list as well, because we aren't tracking how files change/update once they are downloaded. For the future, I'm not sure how much we should be checking up on changes to downloaded files and accurately portraying them in our downloads manager. There could be some privacy implications there.

For the scope of this PR though, I will just ensure that downloads that aren't found from the existing file path will not be displayed in the Downloads view. But we will need to think deeply about any "offshoots" of this issue before implementing in the future.

**Comment by apbitner** [comment]
@kglazko I agree, I think for now at least we should remove the file from the download list if the file is deleted externally. If/when we account for additional states (such as paused, cancelled, etc.), we could revisit having a state that might address this issue better.

**Comment by Dunexus** [comment]
On desktop, when a downloaded file is moved or deleted, Firefox doesn't remove it from the download list but displays something like "File moved or missing" under filename.
This allows to keep track of previously downloaded files even if there are moved or deleted.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 8/26 with Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
