### ISSUE TITLE
[Bug] Firefox crashes Android on LineageOS 15

### ISSUE THREAD

**Issue by jtdev** [mozilla-mobile/fenix#14008]
Since yesterday, starting Firefox results in a short freeze of Android within seconds, followed by a reboot within seconds. This also happens when Firefox runs in the background, which can results in a boot crash loop. The problem doesn't happen when Internet is disabled. It also doesn't happen when Firefox is uninstalled. Chrome and other app don't cause this problem.

Disabling Internet (Wifi and 4G) does allow me to use Firefox without problems, but as soon as Wifi is enabled, it crashes within seconds. Re-installing Firefox Fenix or Firefox Focus (without addons) results in the same problem.

I have used Firefox at Android for years, but this is the first time that I experience this problem.

### Device information

* Android device: Samsung S5 (SM-G900F), LineageOS 15.1 (Android 8.1.0)
* Fenix version: 79.0.5 (Build #2015758617)
  AC: 48.0.15
  GV: 79.0.1-2020813192915

**Comment by SammysHP** [comment]
Same issue here, Lineage OS 15.1 is the latest version available for this phone.

**Comment by Naklarsuper** [comment]
Same issue here. There are devices out there with Lineage OS 15.1 being last updated last year. And devices / OS are not that old. 
I don't quite buy that the "problem and solution lies within the OS" - all other browsers are working fine, and indeed I feel forced to use another browser until this issue is resolved.

**Comment by SammysHP** [comment]
Of course it is a (rather serious) bug in LineageOS. Other apps implemented workarounds or don't rely on calls to other OS programs (`ip` in this case) at all.

Although such old systems have several security vulnerabilities and should not be used anymore or explicitly promoted, LineageOS is used on several older models which would have stopped being updated many years ago. IMHO Mozilla should implement a workaround so that these users can still use a modern browser.

Btw. this is even more serious because it is the first known (to me) case that an app calls `up route get` to cause a reboot loop.

**Comment by Naklarsuper** [comment]
Yes, would be good then if Firefox made a workaround. Unfortunately there are no newer releases for my tablet, but the one I have is just a few months old, so not seriously outdated.

**Comment by kbrosnan** [comment]
This is a duplicate of #5663. The OS has a bug that Firefox triggers. There is no way for us to fix the OS behavior.

**Comment by Naklarsuper** [comment]
> This is a duplicate of #5663. The OS has a bug that Firefox triggers. There is no way for us to fix the OS behavior.

One could wonder why Firefox needs to trigger that function then when it didn't need to yesterday, and no other browser needs to. I know too little to judge, though.

**Comment by micw** [comment]
Great, you are excluding all users of older hardware which have no newer after-market firmware available. On the other hand, you always promote "inclusion". I feel discriminated and excluded as a user of older hardware!
