### ISSUE TITLE
[Bug] Startpage-text is Misaligned.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#14011]
![fire2](https://user-images.githubusercontent.com/59611881/90877862-47f31780-e394-11ea-8fb1-7be957516832.jpeg)

**Comment by Delphine** [comment]
Maybe @brampitoyo can help with this (or help point to someone who can)? This is happening in many of our top tier languages, and I agree it's not a great onboarding experience

**Comment by mcarare** [comment]
@Delphine this is caused by the original English string having a `newline` character that led to the string being translated with some additional `spaces` between the `newline` character and the following text (this is the case for German, at least.)
The fix would be to either recreate a correct string resource without the additional characters and that resource to be translated again or just to edit the translations in Pontoon (already did that for German, it is waiting for translation approval).

As a rule, `newline` characters or `spaces` should not be included in translations, as it is highly unlikely we would use these intentionally in strings.

**Comment by Delphine** [comment]
@mcarare Thanks for looking into this. It will be very difficult to scale if we have to change this manually in Pontoon for all locales. The best thing would be to recreate a correct string. There is translation memory in Pontoon, so that should help localizers get to it quickly/easily. Thank you!

**Comment by mcarare** [comment]
This issue was fixed for the text in the original report.
