### ISSUE TITLE
[Bug] Webpage position not remembered after reload

### ISSUE THREAD

**Issue by Kwasow** [mozilla-mobile/fenix#14072]
## Steps to reproduce
I'm using this page https://startreklist.blogspot.com/2011/04/list-of-all-star-trek-episodes-sorted_05.html?m=1 an average once a day. The tab stays inactive for the rest of the time but is not closed.

### Expected behavior
On Firefox mobile 68.0.11 and older the tab would remember my position and after it was opened again after some time and reloaded scroll back to where I left the previous time.

### Actual behavior
In the new Firefox I'm presented with the top of the page after it finishes reloading.

### Device information

* Android device: Redmi Note 9 Pro (joyeuse)
* Fenix version: 79.0.5

**Comment by madb1lly** [comment]
Hi @Kwasow,

I think that Fenix used to behave as you suggest that it should (and like Fennec does), but now it doesn't - I say this because I noticed this recently and I feel that I would have reported it before if it existed (maybe not though).

In any case it's very frustrating to have to rescroll when a page is long, especially with the way that Fenix seems to reload tabs every time, whereas Fennec can keep many in memory.

Cheers 🙂

**Comment by dannycolin** [comment]
Interesting use case from a review I saw on respond.mozilla.community

![image](https://user-images.githubusercontent.com/7339076/95930235-f5cae300-0d93-11eb-9a2a-ce34527d2d43.png)

**Comment by Kwasow** [comment]
I've been using 83.1.0 and I'm not experiencing this bug anymore.
