### ISSUE TITLE
Non-default background autoplay

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#14105]
Brave browser has such a feature that is not default, users can activate this feature in the settings. So youtube runs in the background without violating play store rules

![Screenshot_20200824-104717_Trebuchet_1](https://user-images.githubusercontent.com/60405617/91018300-15e1ef80-e5f8-11ea-853c-840ce289eced.png)
![Screenshot_20200824-104615_Brave_1](https://user-images.githubusercontent.com/60405617/91018328-1d08fd80-e5f8-11ea-8ba4-77cb351ce829.png)

**Comment by Dunexus** [comment]
See https://github.com/mozilla-mobile/fenix/issues/7238

TLDR; background is already implemented but Youtube uses Page Visibility API to disable background video.

**Comment by Djfe** [comment]
there was an add-on that isn't compatible with the current version, yet.
https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix/

It blocks YouTube from using this webstandard so the video keeps playing.
Maybe it'll soon be updated so you can use it.

**Comment by survivor303** [comment]
They added that addon to nightly \o/, i'm not sure if it is available for stable too because nightly is the way how i run ;)

**Comment by Djfe** [comment]
nice,
I only run nightly on desktop.
Mobile was too instable until recently, back during Fennec times nightlies didn't have an advantage. in a couple of months nightly might become viable, but I don't think I can transfer my tabs (using Firefox sync, can I? ^^)

**Comment by survivor303** [comment]
@Djfe Nightly work as stable, and about how unstable nightly is, well not very. You really can use it as a your default browser. I doing it on every platform.

Surely there is always that "danger" that it broke something but really, if you have sync and profile backup tools put in place, you are safe.

But yes, this going to go offtopic, so perhaps this issue is resolved and devs can close it. :+1:

**Comment by Djfe** [comment]
good to know ^^

"safe", well there was a bug that made it into release 1 or 2 years ago that deleted all open tabs on second restart after the update. (all tabs from before the update)
all due to changes for a feature that was then never introduced, I think.

sync didn't help at all

ok a Firefox backup helps and my device is rooted, but not everyone can do that.

It's nice to see Firefox for Android being reworked and supported again, after release being neglected for over 2 years.

I know offtopic, whatever this has been clarified anyways.

**Comment by softvision-miralobontiu** [comment]
It is possible to play videos in background from youtube, vimeo, on the 1/13 Nightly build.
I'll close this issue. Feel free to open a new one, if necessary.
