### ISSUE TITLE
Crash in [@ mozilla.appservices.places.UrlParseFailed: at mozilla.appservices.places.RustError.intoException(RustError.kt:13)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#14177]
### STR

In Fenix, ask to visit http://1234.56.78.91 - Fenix will fail to display the page, but logcat will show the exact exception from the comment above (ie, it's trying to record it as a visit even though it's an error page). 

Crash report: https://crash-stats.mozilla.org/report/index/cf7846b7-f131-49e5-9bc7-8ded60200825

Java stack trace:
```
mozilla.appservices.places.UrlParseFailed
	at mozilla.appservices.places.RustError.intoException(RustError.kt:13)
	at mozilla.appservices.places.PlacesReaderConnection.searchBookmarks(PlacesConnection.kt:16)
	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$searchBookmarks$2.invokeSuspend(PlacesBookmarksStorage.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by kbrosnan** [comment]
Reported from https://www.reddit.com/r/firefox/comments/igd8ah/firefox_crashes_when_i_type_mi_in_location_bar/

**Comment by st3fan** [comment]
@grigoryk is this one of the crashes you are covering? we ended up not landing that in 79 right?

**Comment by grigoryk** [comment]
@st3fan this is different. We swallow these crashes for history interactions, but not for bookmarks currently. For `searchBookmarks` we can swallow it as well, I think. However there are lots of similar crashes coming out every other bookmarks API as well, and these are trickier to just swallow since they're usually connected to a specific user action (like creating a bookmark) (https://crash-stats.mozilla.org/signature/?product=Fenix&signature=mozilla.appservices.places.UrlParseFailed%3A%20at%20mozilla.appservices.places.RustError.intoException%28RustError.kt%3A13%29&date=%3E%3D2020-08-18T17%3A09%3A00.000Z&date=%3C2020-08-25T17%3A09%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports)

**Comment by grigoryk** [comment]
Filed https://github.com/mozilla/application-services/issues/3536 to discuss this more generally.

**Comment by larrykoch680** [comment]
Filed mozilla/application-services#3536 to discuss a great idea.If someone has a deep thoughts [here](url=https://cuteplushies.net/) about  kawaii plushies feel free to discuss.
