### ISSUE TITLE
[Bug] [New search] autocomplete does not take history into account

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#14212]
## Steps to reproduce
0. Have the new search expereince enabled
1. Visit mozilla.org
2. Type "m" into the toolbar.

### Expected behavior
It autocompletes **m**ozilla.org, because it's the page I have visited most often that starts with "m"

### Actual behavior
It autocompletes something else, **m**ail.ru

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: nightly

**Comment by hsivonen** [comment]
Notably, the suggestions in the location field itself are sites that I've never visited. They look like a prepopulated list of top sites.

**Comment by Djfe** [comment]
interestingly enough I get results from my history, but a lot later. It takes a couple of seconds to load them.
I'm using the German fenix (in-case that this matters for the prepopulated list)

**Comment by miDeb** [comment]
Due to this bug, autocomplete is currently only provided by [the domains component](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/domains/README.md).
@Djfe are you sure there are results from history **inside** the address bar (not below/above it, next to search suggestions, but inside the text box)? Also, which version are you using?

**Comment by Djfe** [comment]
ah so that's what this is about, I thought this was about the results below the address bar, regardless:
I get autocomplete IN the address bar
![Screenshot_20200909-145212_Firefox](https://user-images.githubusercontent.com/5685512/92600730-3bcfeb00-f2ac-11ea-9505-6376bddab028.png)

I'm on release v80.1.2

If this bug was introduced in nightly while it works fine in release, then pls ignore my comment.
I was following this issue because history results below the address bar load slowly for me (slower than fennec).

**Comment by miDeb** [comment]
Yes, this bug was introduced in nightly with the new search experience, but is currently also in beta. Here's my pr that would fix it: https://github.com/mozilla-mobile/fenix/pull/14292

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly and Beta 81.1.1.
