### ISSUE TITLE
[Bug] New search experience - Elements jump abruptly when starting a search

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#14246]
## Steps to reproduce
1. Tap the toolbar's search input element

### Expected behavior
The animation is smooth.

### Actual behavior
The animation has some abrupt elements, it seems to stop halfway and then continues, missing smoothing steps in between. The main culprit is the panel for the scan shortcut and search engines button as it first appears at the bottom and then jumps to its final position, see the slow motion gif, also attached in normal speed. Also, the placeholder text in the toolbar performs a small jump and the toolbar text input expands.

Old search experience - video and profile:
[old_search_experience.zip](https://github.com/mozilla-mobile/fenix/files/5132837/old_search_experience.zip) - https://share.firefox.dev/2QpArcr

New search experience - video and profile:
[new_search_experience.zip](https://github.com/mozilla-mobile/fenix/files/5132839/new_search_experience.zip) - https://share.firefox.dev/3jixA1j

![new_search_slowdown](https://user-images.githubusercontent.com/42788925/91358823-ca943080-e7f3-11ea-9317-9a12b4b16337.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200827 06:01 (Build #2015760369)
AC: 57.0.20200826190111, c93fc20af
GV: 81.0a1-20200820093209
AS: 61.0.13

**Comment by mcomella** [comment]
Triage: this doesn't feel great – let's bring it up for the fenix team. We want to highlight that this is a regression and doesn't occur in the old experience.

**Comment by Mugurell** [comment]
This doesn't feel great but it's the expected behavior for the current layout.
When the keyboard opens whatever elements we want placed on top of it will snap to their expected location and then the app just waits for an unspecified amount of time for the keyboard to animate to that position also.
We don't have much control over this (over when the keyboard will appear. We just ask for it.)

Android 11 finally introduced something to fix this specific issue - https://medium.com/androiddevelopers/animating-your-keyboard-reacting-to-inset-animations-839be3d4c31b but for the older Android versions there is no fix.

Talked about this in planning.
Maybe the design team can suggest a new UX?

**Comment by hwinnemoe** [comment]
Since there are plans to integrate the search engine picker (#16659) and the QR scanner (#16658), this might just get resolved by these design changes.

**Comment by hwinnemoe** [comment]
This is still valid on 93.0a1 (Build #2015828905)
AC: 93.0.20210817143149, 609c425e1e
GV: 93.0a1-20210817094606
AS: 82.1.0
2021-08-19T05:09:47.445098
