### ISSUE TITLE
Bring back DNS over HTTPS to Firefox Android for privacy

### ISSUE THREAD

**Issue by pathbreak** [mozilla-mobile/fenix#14261]
### What is the user problem or growth opportunity you want to see solved?

Until versions < 79.0.5, Firefox for Android supported DNS-over-HTTPS for better privacy.
In 79.0.5, this feature has been removed. 
All DNS requests from Firefox go out unencrypted via ISPs in older Android versions which don't support device-wide DNS settings.
This has actually reduced privacy of Firefox (although the PR announcements for this release claim the opposite).
Although I have filed this as a feature request, I feel this is actually a regression bug.

### How do you know that this problem exists today? Why is this important?

DNS over HTTPS improves privacy. See this [article by Mozilla](https://blog.nightly.mozilla.org/2018/06/01/improving-dns-privacy-in-firefox/).

### Who will benefit from it?

DNS over HTTPS improves privacy for all. See this [article by Mozilla](https://blog.nightly.mozilla.org/2018/06/01/improving-dns-privacy-in-firefox/).
For users living in internet censoring regimes, it's a simple user-friendly solution to access blocked websites and has helped  improve adoption of Firefox.

**Comment by kbrosnan** [comment]
Duplicate #4584

**Comment by andrew-aitchison** [comment]
This is not a duplicate of #4584 - that bug was about adding a user interface.
This bug is a **regression** in Android v80; before that tDNS-over-HTTPS functionality was available via about:config, but that feature has been removed, so there is no way to enable DNS-over-HTTPS in v80.

For what is is worth, the  UK ISP _TalkTalk_ has a parental controls option _KidSafe_ which blocks DNS requests to *.mozilla.org. Thus this bug means I cannot access mozilla sites from Android unless I open up the entire internet to my children ...

**Comment by cadeyrn** [comment]
> This is not a duplicate of #4584 - that bug was about adding a user interface.
> This bug is a regression in Android v80; before that tDNS-over-HTTPS functionality was available via about:config, but that > feature has been removed, so there is no way to enable DNS-over-HTTPS in v80.

So, in fact, it _is_ a duplicate of #4584.

**Comment by andrew-aitchison** [comment]
???
Sorry I don't see a feature request as a plausible duplicate of a regression bug. If https://github.com/mozilla-mobile/fenix/issues/4584 can be marked as a regression, I would find that a suitable response.

Otherwise, your reply is pretty much using up what little goodwill I have left for Mozilla, after the disappearence of about:config and https://twitter.com/EmilyKager/status/1289308930972278789

I *chose* to use the previous Firefox for Android on my phone and tablet. I cannot use the new Firefox for Android to do the things I used to do (like submit bug-reports to mozilla :-)  and I will switch to another browser when I can find a less unsatisfactory alternative.

---
Oh, and your suggestion https://github.com/mozilla-mobile/fenix/issues/7865#issuecomment-679351305_ of adding options for every useful feature previously in about:config sounds like causing a lot of code and binary bloat. Many tweaks that power-users enjoy justify an about:config option but writing a gui interface seems like overkill. If that is no longer what firefox is about, it is no longer the browser I have used and loved since it took over from the original Mozilla browser.

**Comment by cadeyrn** [comment]
> ???

I don't understand your question.

It's a feature request because it's not a bug but a not yet implemented feature but it doesn't matter at all if you call it a feature request or a regression because it doesn't change the fact that you want to configure DoH and that #4584 is exactly about this.

> Oh, and your suggestion #7865 (comment)_ of adding options for every useful feature previously in about:config sounds like causing a lot of code and binary bloat

No. I didn't suggested adding options for everything. But my comment in a totally different issue has nothing to do with your feature request.
