### ISSUE TITLE
[Spike] Review your release process

### ISSUE THREAD

**Issue by liar666** [mozilla-mobile/fenix#14274]
## Title

I'm a FF for Android user for some years. I was pretty happy, apart for the impossibility 1) to save the page as HTML 2) to save links (to mp3, pdf, etc) to filesystem.

I recently upgraded my apps, and discovered a totally new version of FF for Android.

This new FF for Android is a **pure regression**: essential functions have disappeared (like "Save as PDF"), most extensions can't be installed (even most basic security/privacy ones - UA Switcher, Hide Fixed Elements, YT downloader -, all alternative "Save as PDF" solutions are incompatible, etc.), extensions cannot be listed if you are not online, UX choices are difficult to understand (when menu is set to top and you want to create a new tab, the "+" button - that as a different style from the rest of the menu - is at the bottom ; tabs cannot be moved from incognito/non-incognito mode...), etc.

In the end, the app is totally useless apart for simply viewing pages. It has less functionalities than the default chrome browser or even the intentionally (very) restricted DDG Browser!

## Description

You should really rethink your releasing process and make User Satisfaction tests before replacing a functioning app that users are happy with by a all-modern but non-funtional app that will disappoint your whole user-base.

At least, such important and functionality-breaking releases should be in a separated distribution channel...

## Deliverables

A clever releasing process.

**Comment by Auhrii** [comment]
Hear, hear. All my plugins bar one (uBlock Origin) have disappeared, about:config has been blocked and the settings I messed with to fix display scaling on my device are now ignored entirely, so webpages now look like they're made for toddlers.

The auto-hiding search bar has no option, as far as I can tell, so turn off the auto-hiding - this "feature" causes issues on every page I visit because the change in viewport size makes webpages go absolutely insane and jump around.

The new tab UI is dreadful and only fits half the number of tabs on screen, the entire browser performs far worse for me (contrary to how the update's touted), and the file download system notifications can't be swiped away (why?).

To top it all off, it seems that Mozilla is whitelisting add-ons instead of allowing developers to flag them as compatible. Not only does this scream "walled garden", but it's also not doing any favours in regards to replacing all the add-ons we lost literally overnight. I can't name even a single improvement in this update and it should have stayed a non-mainstream release for a good while longer.

**Comment by liar666** [comment]
I can also and that the app crashes almost every time I try to share a link. See https://github.com/mozilla-mobile/fenix/issues/14296

How can such a bad app be released to the public?

**Comment by liuche** [comment]
Closing as unproductive
