### ISSUE TITLE
[Bug] When in new search experience, the rest of the content on the New Tab page is not selectable

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14288]
## Steps to reproduce
1. Launch Fenix Nightly with the new search experience;
2. Tap the homescreen search bar;
3. Observe the area above the keyboard;
### Expected behavior
The area above the keyboard is not covered by a scrim and is selectable, as mentioned in https://github.com/mozilla-mobile/fenix/issues/13052#issue-667539374.
### Actual behavior
The area above the keyboard is not selectable when in New Tab page.
### Notes
![20200827_150737](https://user-images.githubusercontent.com/48799384/91440677-9f532500-e877-11ea-964b-451d8c4c7059.gif)

### Device information

* Android device: Pixel 2 (Android 9), Nexus 5 (Android 6.0.1).
* Fenix version: Nightly 200827 07:01 (Build #2015760377) GV 81.0a1 from 8/27
cc @brampitoyo

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).

**Comment by brampitoyo** [comment]
@ebalazs-sv Correct. The spec did say that the scrim shouldn’t exist, and the items underneath should be directly selectable.

@boek has confirmed that this isn’t so easy to accomplish. Until the fix is possible, we’re keeping the scrim on.

Ultimately, it’s not a big deal if it takes one extra tap to dismiss the scrim. The tap area is relatively large (ie. anywhere above the keyboard and the address bar), and is clearly marked with a darkened colour.

**Comment by madb1lly** [comment]
Think this is working as intended now isn't it?
