### ISSUE TITLE
'Copy to Clipboard' option not present when 'Share' is clicked

### ISSUE THREAD

**Issue by axeltrinidade** [mozilla-mobile/fenix#14313]
## Steps to reproduce
Click on 'Share' option in the three dot menu when on a webpage

### Expected behavior
Apps that can share as an action appear along with 'Copy to Clipboard' https://bit.ly/3aZs1Sw

### Actual behavior
Recent apps appear, all actions appear, but 'Copy to Clipboard' does not. https://i.imgur.com/UO2PpyN.jpg

### Device & build information
* Device: Oneplus 7 / OxygenOS 10.3.4 / Android 10
* Build version: 80.0.1-beta.2 (Build #2015758611) and 79.0.5 (Build #2015758619)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-818)

**Comment by NotWoods** [comment]
Usually devices supply a copy action in the share sheet, perhaps OnePlus is an exception? We can coordinate with QA to test for the presence of the option on devices, and potentially add the option manually if it doesn't show up.

**Comment by Trigger-92** [comment]
I have the same issue. My phone is the Nokia 7 Plus running Android 10 (stock).

**Comment by aschrijver** [comment]
Samsung S7, I reported to Discourse asking for workaround: [Firefox Android new v80+ release makes Share button unusable](https://meta.discourse.org/t/firefox-android-new-v80-release-makes-share-button-unusable/163163).

**Comment by mikelward** [comment]
No copy you clipboard on Pixel 4a running Android 11 either.

Are you sure Android adds this by default? Are you sure this applies if you're showing a custom share sheet?

**Comment by MarianoRD** [comment]
Huawei Mate 20 Pro, Android 10. I can confirm this issue is happening and is really annoying.

**Comment by axeltrinidade** [comment]
Seems like a manual addition of the copy action is required

**Comment by brianazick** [comment]
I'm enccountering this issue on a Galaxy S10e running Android 10.0 and FireFox version 80.1.3

**Comment by re-hub** [comment]
when you press long on url bar, you can copy the url in my device. 
Device: Lineage os 16

**Comment by axeltrinidade** [comment]
I think that is a good option to go around. But isn't this still considered a Bug if it's not consistent with every device?

**Comment by axeltrinidade** [comment]
[Suggestion/Feature request] Since the alternative to this is to hold the URL bar to copy - is it possible to add a 'share' button to the menu that opens when you hold the URL bar?

**Comment by john-parton** [comment]
Copying the URL from the URL bar is not the same as the old Copy Link feature.

Address bar: https://m.youtube.com/watch?v=ICLNbP5iXUg

Share menu: https://youtu.be/ICLNbP5iXUg

**Comment by mcarare** [comment]
From Android 10 there are some clipboard access restrictions, that is the reason the "copy to clipboard" is not available. There are some workarounds possible, having another app that provides this, or add a _copy button_ like Focus has. But UX should give the go ahead for that, as well as specs.

**Comment by codrut-topliceanu** [comment]
@brampitoyo Hey, sorry for the ping on an old issue but is there any chance of seeing this approved for fixing/implementation? 

I actually use "_Copy URL to Clipboard_" a lot as some of my most used chat apps have messy share options so I just prefer to paste the URL in a conversation.

**Comment by duerra** [comment]
Hey Mozilla team - would really love to see this resolved.  Adnroid Chrome doesn't have any issues here, just FF.

**Comment by brampitoyo** [comment]
@codrut-topliceanu @duerra I’m really sorry for the long overdue reply on this issue!

I don’t see any problem adding “Copy URL” to the share tray UI.

Would it be possible to put this action under the “Recently used” section?

**Comment by codrut-topliceanu** [comment]
@brampitoyo @duerra We do have a somewhat similar feature on long pressing the address bar, it's actually a lot handier than Share->Copy URL would be.

![image](https://user-images.githubusercontent.com/60002907/115196019-1d5e8780-a0f8-11eb-994a-78dddaac4cdf.png)

**Comment by Trigger-92** [comment]
@codrut-topliceanu That's what I've been doing, it's one less step, but I would point out that this may not be obvious to the user since FF is the only browser that does it like this (to my knowledge).

**Comment by GracefulGideon** [comment]
![Screenshot_20210518-220707](https://user-images.githubusercontent.com/84427833/118746064-80415c80-b825-11eb-91bb-e68df6f97b5a.png)

And then after clicking the clipboard:

![Screenshot_20210518-220736](https://user-images.githubusercontent.com/84427833/118746140-a49d3900-b825-11eb-81a2-f2205a6106ef.png)


This issue is still occuring for me as well on my Pixel 5 running android 11

**Comment by old486whizz** [comment]
Since the 'share' menu is different to every other android app, this seems like a custom share menu from Mozilla (probably using a tool which is cross-platform)..
Ie: crippled due to Apple.

The problem isn't that there's an easier way (long-press on address bar), it's inconsistency with the rest of the platform.
Here are two screenshots: one from Firefox, one from *any* other app (pixel 5, android 11).
![Screenshot_20210610-105309~2](https://user-images.githubusercontent.com/1090208/121505179-85379d00-c9da-11eb-8a6d-3e035c9ff804.png)
![Screenshot_20210610-105234](https://user-images.githubusercontent.com/1090208/121505182-85d03380-c9da-11eb-8fe1-4a51929f2c4c.png)

**Comment by pavi2410** [comment]
A copy to clipboard button is very important when sharing a link to any topic/post in Discourse forums.

![Screenshot_2021_0707_173613](https://user-images.githubusercontent.com/28837746/124756905-a395a780-df4a-11eb-9152-4554ca3e49d2.jpg)

**Comment by Compvictor** [comment]
Same issue on Moto Edge 20 pro, Android 11, it doesn't show the Copy to clipboard option in any app (even some that has no url bar). I've read that this function is enabled by Google Drive app (weird), installing (or reinstalling, cleaning cache, etc) it should enable the option, but didn't work in my case.

**Comment by thevoiceless** [comment]
"Copy to Clipboard" isn't showing up for me, even with the Drive app installed. Firefox really should use the native share sheet (at least on recent versions of Android), or *at the very least* provide a way to get to it.

For example, Brave has a custom sheet but includes a "More" button that launches the native one.

**Comment by michel-slm** [comment]
Same on Pixel 6, Android 12. Please use the native share sheet on Android 10+

**Comment by ronaldpoi** [comment]
The real problem is Firefox forcing a custom share sheet instead of using the OS-level standard one. We're facing not only the "copy to clipboard" issue, but the lack-of-consistency issue across the platform.

**Comment by corobin** [comment]
So the initial reports on this issue date back over a year ago, but I actually *had* a "copy" option until very recently. I'm not sure exactly when it started but as of right now, on the current stable version of Firefox for android, I *no longer* see a "Copy" option in the Share menu.

How I noticed:

1. go to any youtube video
2. click the "Share" button that is in the webpage right under the video
3. Share menu does not show a clipboard icon

If I manually trigger the share menu from the Firefox UI (kebab menu > share), it also does not show a clipboard option.

**temporary** workaround: https://github.com/tengusw/share_to_clipboard

I would really like to see Firefox natively support sharing to clipboard, like I had seen before. I'm not sure why this issue appears to be inconsistent among the user base (some people have a share to clipboard, some don't, over different time periods) but at least on my [Firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox) 96 on Android 12 on Pixel at the time of this post, it does not currently have the option.

**Comment by jonalmeida** [comment]
For UX:

These are examples of other apps that also have custom share sheets which delegating the complexity of different actions like 'Copy to clipboard' or 'Share with' to the **native share sheet**. 

From left to right: Google Photos, Google Maps, Strava, and Spotify.

![out](https://user-images.githubusercontent.com/1370580/155482707-080da632-a5f5-4454-8d80-a8a37e726985.png)

These "More" buttons eventually show the native share sheet. Most of which already support the 'Copy' mechanism (notice the Google Photos custom share sheet above vs the native sheet after clicking on the 'More' button):

<img src=https://user-images.githubusercontent.com/1370580/155483975-c715f183-a5d1-4d03-b7b6-8a19a68cb044.png width=320 />


What you also see is that some apps do prioritize a specific 'Copy to clipboard' button which we could do too, however I recommend we still add the "More" delegate button so that we can reduce the work needed to support other requests e.g. Direct Share support in our custom share sheet.

**Comment by corobin** [comment]
v100 has brought the clipboard button to the share panel!

i noticed though that the "copy" option never goes into the "recently used" box, even after using it a lot. it keeps stayin in the "all actions" part. anyone else seeing this?

**Comment by jonalmeida** [comment]
> i noticed though that the "copy" option never goes into the "recently used" box, even after using it a lot. it keeps stayin in the "all actions" part. anyone else seeing this?

This is by design.

**Comment by corobin** [comment]
> > i noticed though that the "copy" option never goes into the "recently used" box, even after using it a lot. it keeps stayin in the "all actions" part. anyone else seeing this?
> 
> This is by design.

oh. thanks for clarifying. 

that's a weird design decision, considering that bluetooth and nearby share are both in the recently used box even though i've never used them, ever.

i'd like to request that 'copy' be allowed in the recently used area. should i make a new issue since this one is closed? thanks.

**Comment by jonalmeida** [comment]
Sorry, to clarify: this is by design because 'Copy to clipboard' is a "sticky" action. It will always be in the first position. Moving it into Recently used would have the implication that it may move out of that section, hence why we kept it sticky in the 'All actions' section.

> i'd like to request that 'copy' be allowed in the recently used area. should i make a new issue since this one is closed? thanks.

Yes, you can file a new issue.

**Comment by corobin** [comment]
> Sorry, to clarify: this is by design because 'Copy to clipboard' is a "sticky" action. It will always be in the first position. Moving it into Recently used would have the implication that it may move out of that section, hence why we kept it sticky in the 'All actions' section.

oh, thanks that explains the rationale. do you know whether nearby share and bluetooth are also treated specially? are those allowed to move out of recently used? they have always been the two top suggestions for me. thanks again!

**Comment by corobin** [comment]
thank you for the helpful comments!
