### ISSUE TITLE
uBlock Origin is not showing up.

### ISSUE THREAD

**Issue by PNO-LOCKDOWN** [mozilla-mobile/fenix#14324]
Hi 

In the last version of Firefox mobile app uBlock Origin did show up in the drop down list how ever in the new version of Firefox mobile app uBlock Origin doesn't show up so you can't make a fast pop block can you please add this to the next update maybe you can have a shield next to the tab button or next to the address bar thank you

**Comment by kbrosnan** [comment]
uBlock will show up in the addons sub-menu when enabled.

* Open Firefox
* Tap 3 dot menu
* Tap Add-ons
* (only needed if you have an enabled addon) Tap Add-ons Manager
* Tap the plus button on the right hand side of the add-on you want to add
* Agree to the permissions it needs to fuction

To use the addon
* Visit a website (the add-on will not be functional on the home view)
* Tap the 3 dot menu
* Tap Add-ons 
* uBlock should be listed
* You can tap the icon to interact with it in a similar manner to desktop Firefox.


Closing because ublock is already available to Firefox users.
