### ISSUE TITLE
[Spike] Investigate AC APIs for exposing bookmark keywords in urlbar

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#14327]
## Bookmarks keywords
For #12099 there is some AC work that needs to be done to expose the APIs to be used in the urlbar

## Description
Identify what APIs would need to be added, and how much work it would be.

## Deliverables
Description of deliverables, including:
Identify what APIs are needed to use bookmark keywords in urlbar
Estimate amount of work it would take to be exposed in AC
Estimate size of #12099 based on findings (and if it is a huge amount of work, like a full sprint, revisit with Product owner.

**Comment by evilpie** [comment]
From the Firefox desktop side there are some changes planned around bookmark keywords: https://bugzilla.mozilla.org/show_bug.cgi?id=1650874

**Comment by j-s-a-m** [comment]
The two tickets (#12099, #14327) linked by @hwinnemoe to #14570 are less explicit than #14337 ("[Bug] Smart keywords no longer work"), #14570 ("Firefox for Android 79.0.5 : Keyword searches are broken / Make keyword searches have highest priority again") and #14571 ("[Bug] 79 removed the "keyword" functionality from bookmarks - I would like it back"),

because they do not mention that Firefox for Android 79.0.5 has broken a functionality that has been working perfectly before. #12099 is in fact a **feature request** about editing keywords, #14327 is an **investigation ticket** about exposing APIs.

The linked tickets may be about a relating topic (keyword searches), but I do not consider them to be real duplicates of the aforementioned **bug tickets**.

I add this comment because I hope that this bug gets the priority it deserves.

**Comment by Mugurell** [comment]
Investigated what's needed.
Have the patches ready, they will be posted for https://github.com/mozilla-mobile/fenix/issues/12099 and the accompanying AC ticket.
