### ISSUE TITLE
Open in new foreground tab

### ISSUE THREAD

**Issue by wedgerage** [mozilla-mobile/fenix#14414]
### What is the user problem or growth opportunity you want to see solved?

When long pressing a link, an option to open in new foreground tab would be appreciated.

### How do you know that this problem exists today? Why is this important?

When long pressing a link, Samsung Internet Beta gives an option "Open in new tab" and "Open in background". First opens the link in new foreground tab, the latter in new background tab. Firefox is missing the first behaviour.

### Who will benefit from it?

When I want to open multiple links in new background tabs, say from a search result page, the current way of opening links in new background tabs is useful. How ever you may want to open and immediately go to a link. Right now to do this you have to touch Open link in new tab, then touch Switch. This option will get rid of the extra step needed.

**Comment by liuche** [comment]
Unfortunately we cannot support every kind flow for opening tabs - we already show a snackbar with "Switch" to tab in it, which is Fenix's solution for opening a tab and immediately switching to it.

**Comment by HubKing** [comment]
> 
> 
> Unfortunately we cannot support every kind flow for opening tabs - we already show a snackbar with "Switch" to tab in it, which is Fenix's solution for opening a tab and immediately switching to it.

And what is the reason for this? If there can be only one option, shouldn't it be "opening the link in the foreground tab" so that the user can actually see it? Why would anyone want to open a link in the background tab on a mobile device, which can only show (and often, load) one tab at a time, and leave it in the background?

The reason why I am trying to open a link in a new tab, instead of just clicking it, is that when I go back to the previous page, I want it to be exactly the same before I opened the link. On some famous mobile websites, if I click a link on a long page, and go back, the page gets reloaded or the scrolling position gets reset (to the top). But with this ForeFox's implementation,  I have to tap "Switch" every time, which is annoying, and I could mis-tap something else on the page whilst trying to tap "Switch" which is disastrous.

Some browsers like Samsung Browser has both options in the context menu (foreground, background). Or FireFox could have an option in the preferences whether to open a new tab in the background or in the foreground by default.
