### ISSUE TITLE
Use old (legacy?) tab menu

### ISSUE THREAD

**Issue by thepooptoob** [mozilla-mobile/fenix#14417]
In my opinion, the new tab menu is garbage and awful to use. A setting to switch back would be great.

**Comment by DavidJCobb** [comment]
Existing reports for this issue include #2487 and #955 / #13098.

**Comment by KryptonicDragon** [comment]
There are three main complaints I have about it:
-Creating a new tab can no longer be quickly done by tapping the tab tray button twice (since the first tap would open the tab tray, and the second tap would hit the "new tab" button that would show up in the previous button's place)
-The tab tray doesn't even take up the whole screen, for whatever reason. The huge "normal tab / private tab" buttons take up enough space on their own that another tab could fit in the list without them.
-The double-column "grid" view is... gone.

There's various already-open issues floating in here about those problems, so I'm just commenting on this issue to say "I agree with the issue"

**Comment by ekager** [comment]
@thepooptoob this is your final warning that issues like this that are not constructive are not welcome in this repo. 

See our participation guidelines here https://www.mozilla.org/en-US/about/governance/policies/participation/
