### ISSUE TITLE
Add setting to Trigger Authentication before Autofill

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14428]
### What is the user problem or growth opportunity you want to see solved?
Saved logins has biometric authentication for viewing all logins. But you can fill in the logins without any sort of authentication. If you want to have authentication then it should be there for all entry points. Otherwise there is no use for it

### How do you know that this problem exists today? Why is this important?
People can easily log in using my credentials if if leave my browser open. Granted this is an unlikely scenario but the current feature ( #5547) gives an undue impression of security when that is not the case

### Who will benefit from it?
Anyone who stores passwords in firefox password manager (securely)/people who were asking for a master password . Also users who are aware of bitwarden and other password managers which ask for authentication before autofill

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-5892)

**Comment by cadeyrn** [comment]
> People can easily log in using my credentials if if leave my browser open.

Why do people this? I would argue that if you really leave your smartphone unattended and without any authentication then you have much bigger problems than the access to Firefox data. 😉

But back to your request: There were already a few reports for a master password in the last past days. These issues were closed as "already implemented" since the _direct access_ too the logins is already protected in the settings. I guess what these people really meant was exactly what you explain in your request. But it was not explained well in the other issues. The master password is only a tool and doesn't need to be re-implemted. The same authentication method that is already used in the settings could be used here as well. I agree with your proposal that it makes sense to expand the protection for all entry points.

**Comment by s-ankur** [comment]
The current protection is more or less an inconvenience than a feature. Without authentication for all entry points, it will not provide security, just security theatre. As you note, the security it could in theory provide really overshadows bigger problems ( unless people are using the "delete browsing data on quit" feature.)

**Comment by liuche** [comment]
We did consider this originally, but left it off of v1 of logins because it seemed too onerous for the everyday user. Could add a setting for it though.

**Comment by madb1lly** [comment]
Hi all,
This is no more onerous than having to enter my master password every time I open Firefox on Desktop for the first time. I'm dubious of the real security utility which that provides, but it does at least provide some.
Cheers 🙂

**Comment by s-ankur** [comment]
Just to reiterate, my issue is not with having more security but actually completing the security that you have right now via #5547

The protection introduced by https://github.com/mozilla-mobile/fenix/issues/5547 can be easily circumvented currently:

 Suppose you save a login for google.com
 The authentication in saved logins will prevent anyone from seeing that login via settings
But you can easily use that login by directly going to google.com and clicking on suggested logins (which are unprotected)

 This issue addresses this security loophole. If this loophole is not addressed then there is no point to having #5547 as far as I understand. Onerous or not, if you have #5547 then you need to have this feature as well.

**Comment by s-ankur** [comment]
You don't have to authenticate for each autofill btw. Just copy bitwarden behaviour and authenticate after a timeout or app session

**Comment by Rodze** [comment]
Even Lockwise devs already recognized this issue and fixed this problem so you have to unlock it again after the time out.  

Firefox for Android just has to copy the same behavior for its built-in password manager. 

Mozilla already knows the appropriate answer...

**Comment by fblampe** [comment]
It gets even worse with websites that let you tap a little eye button to show the autofilled password in plain text! This totally circumvents the authentication implemented in #5547.

I suppose that plain text feature might be considered a security flaw on those websites, but since it's becoming more common, I would say it's one more reason for Firefox for Android to address this by adding the previously proposed authentication on autofill with a timeout/session, similar to how it's done on desktop.

**Comment by kekkc** [comment]
I don't see why this is different to Windows or Linux. Both OS have internal capabilities to store files encrypted and both use authentification techniques to recognize the same user that unlocks the screen (even biometrical). Exactly the same as on Android. Nevertheless noone would get the idea to simply rely on those and not use a primary password on windows (and if so the shitstorm would be even bigger). Exactly because of the usecase that someone else needs your work PC for a second. So that usecase if valid but if someone else needs your phone to look sth. up is sth. that is no valid usecase?

Questionable decision at best, if some part of the old security feature can be re-enabled by this workaround here, this would be mandatory (how ironic that the minimum security on desktop browsers was implemented on mobile, then actively stripped there because of questionable assumptions of a very small group and is no listed here as feature request to re-enable a small part on mobile to get somehow on par with desktop security again).

"We've decided that on Fenix, master password does not provide any additional meaningful security, and won't be adding support for it." https://github.com/mozilla-mobile/fenix/issues/14501#issuecomment-683888369

**Comment by kekkc** [comment]
BTW: this setting "Enable Passcode for Logins" is available for Firefox for iOS https://support.mozilla.org/en-US/kb/set-passcode-and-touch-id-firefox , Apple is replacing all passwords with this FIDO standard in newer iOS versions.

The corresponding API on Android is FIDO2: 
https://developers.google.com/identity/fido/android/native-apps
Explanation: https://developers.google.com/identity/fido?hl=en

I guess that updates the comment from the parallel bug: https://github.com/mozilla-mobile/fenix/issues/14501#issuecomment-683888369

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807454

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
