### ISSUE TITLE
[Bug] Close tab in tab tray causes visual glitch

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14454]
## Steps to reproduce
Open tab tray
Close a tab
### Expected behavior
It moves smoothly
### Actual behavior
It moves with a glitch
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by s-ankur** [comment]
https://drive.google.com/file/d/1BTstiHUtiorD9wd2Tm3aCVx4MKFhRgNc/view?usp=drivesdk

**Comment by mcomella** [comment]
Triage: this is a visual polish issue, not a a performance problem.

**Comment by cadeyrn** [comment]
While it's not a real performance problem it affects the perceived performance at least. Could this please be bumped in priority? It's a very annoying visual issue. And I see that you're already working on a second tabs layout. I appreciate that you want to provide options for the user but I also feel that it's more important to get the default layout finished before adding more features to this component. 😊

Tabs are really one of the most basic and important feature of every browser (well, maybe with exception of Firefox Focus 😉). That's why I think that this should be fixed rather sooner than later.

**Comment by s-ankur** [comment]
Seems to be fixed now, @cadeyrn could you confirm?

**Comment by cadeyrn** [comment]
I only tested Firefox Nightly and can confirm that it looks much better now.

**Comment by sflorean** [comment]
Wasn't able to reproduce this issue on latest Nightly with different devices.  Based on this and the above comment, I will close this issue.
