### ISSUE TITLE
[Bug] Can not go onto any insecure website

### ISSUE THREAD

**Issue by eggiye** [mozilla-mobile/fenix#14551]
## Steps to reproduce
1.Go to a unsecure website (it should say unsecure connection)
2.Click Advanced...
3.Then click continue

### Expected behavior
It will let me continue to the website.

### Actual behavior
It went back thinking I pressed go back.

### Device information
Android Version: 9

* Android device: Galaxy note8
* Fenix version: Nightly 200831 06:01

**Comment by jawz101** [comment]
I have no idea where the advanced is mentioned

I tried http://llreptile.com and I just go to it

**Comment by clientenq** [comment]
It is probably the "Secure Connection Failed" screen. However I can not reproduce the  described actual behaviour on several insecure sites. The expected behaviour is actual behaviour here.

@eggiye can you reproduce this issue on several sites and screen layouts like horizontal view? (place dot after domain name of most https site will trigger this warning)
