### ISSUE TITLE
[Bug] Go back on website with an invalid security certificate fails when there is no tab history

### ISSUE THREAD

**Issue by eggiye** [mozilla-mobile/fenix#14552]
## Steps to reproduce
1. Go to a site with an invalid certificate
2. Click advanced on the warning
3. Click go back

### Expected behavior
To go back to the last website

### Actual behavior
It just goes to the same page and
doesn't go to the last page.

### Device information
Android Version:9

* Android device: Galaxy Note8
* Fenix version: Nightly 200831 06:01

**Comment by kbrosnan** [comment]
This works for me using an up to date nightly on a Galaxy Note 9. Is there a specific page that you see this on?

**Comment by eggiye** [comment]
> This works for me using an up to date nightly on a Galaxy Note 9. Is there a specific page that you see this on?

Let me try to do a different unsecure page

**Comment by kbrosnan** [comment]
Er. I was going to a insecure website as in a `http` site instead of `https`. You are describing a site with an invalid security certificate. The behavior will depend on the exact certificate that is presented.

**Comment by kbrosnan** [comment]
Clear STR:

* Open a new tab
* visit https://untrusted-root.badssl.com/ or any other untrusted cert page
* tap `Advanced`
* tap `Go back`

Expected behavior: Unclear. We have two options close the tab and go back to the previously focused tab or go to the home screen. @mozilla-mobile/ux

**Comment by brampitoyo** [comment]
@kbrosnan Since the page that the user sees prior to the website is the new tab page (or the homescreen), we should go back to it.

**Comment by kbrosnan** [comment]
@brampitoyo I am a little surprised by that

* Home screen -> tap in address bar -> https://untrusted-root.badssl.com/ -> `Go back` -> Homescreen
* tab with https://www.wikipedia.org -> new tab  -> home screen search view -> paste in https://untrusted-root.badssl.com/ -> `Go back` -> should take you to https://www.wikipedia.org?

**Comment by brampitoyo** [comment]
@kbrosnan On the first scenario, since the page that you see prior to badssl.com is the new tab page, we should return to the NTP when you tap `Go back`. Makes sense.

On the second scenario, since the page that you see prior to visiting badssl.com is also the new tab page (and not wikipedia.org), shouldn’t we also go back to the NTP, without closing the tab that you just opened? This would match desktop’s behaviour.

I heard, though, that the NTP isn’t really considered an “entity”. Meaning: it might not really exist in the history stack. If that’s the case, then maybe returning to wikipedia.org makes sense. But on the other hand, it doesn’t feel right to close the tab that the user has manually opened.

**Comment by kbrosnan** [comment]
I was thinking we would go back to the default home screen view since it is a known safe location in both cases.

**Comment by brampitoyo** [comment]
@kbrosnan Agreed. That’s also what I’m thinking. Sorry if I refer to the default home screen view as the New Tab Page!

Let’s clarify the decision: **we should always go back to the home screen**. This applies both when you visit the cert error page directly, and when you visit it after opening a fresh new tab.

**Comment by Mugurell** [comment]
Talked with Sebastian about this.
There doesn't seem to be an easy solution to intercept that action on a webpage button to act on Fenix afterwards.
His proposal was to just hide the back button if there is no tab history.
@brampitoyo Does this seem ok with you?

**Comment by brampitoyo** [comment]
@Mugurell If we have to hide the Back button, I wonder whether we’re able to replace it with a button that says “Go Home”?

Instead of going back, this “Go Home” button would “go forward in history” and replace the error page with the New Tab Page.

If replacing by going forward is impossible, then hiding the back button without a replacement is fine. But can we ensure that people will still have “a way out” of the error page? For instance:

- They can tap the address bar and enter a new keyword or URL
- They can tap the Tab Tray icon, close that tab, and/or open a fresh new one

**Comment by mcarare** [comment]
@brampitoyo  Yes they do have a way out. Pressing the android back button would do the same as the action previously desired to be performed by the back button. They can also interact with the address bar and tab tray same as in any other page.
As the "home page" is not actually a tab, but an Android screen, we can navigate to it using just JavaScript.

As a note, if error pages would be rendered by an extension (like reader mode does) maybe we could have more control. But, for the moment, hiding the button when there is no history to go back to is the only non-trivial and direct fix.

**Comment by brampitoyo** [comment]
@mcarare Great. All the behaviours you’ve proposed makes sense to me. 

 think preserving “back” as an action – whether through button tap or gesture – is so important, because it’s what most people will instinctively do. I’m glad to hear that system back will continue to work.

r+ from me. Thanks!

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201103 05:01 (Build #2015773417) GV 84 from 11/3 with the devices: 

- Motorola Moto G6 (Android 8);
- Pixel 2 (Android 9).

following the steps from comment https://github.com/mozilla-mobile/fenix/issues/14552#issuecomment-684110925, the results are:
- when there is no previously visited page, before accessing https://untrusted-root.badssl.com/, the "Go Back (Recommended)" button is not available, but the device back button will take the user to the home screen and the tab remains opened in tabs tray.
- when there is a previously visited page, before accessing https://untrusted-root.badssl.com/, the "Go Back (Recommended)" button is available and when tapped, will take the user to the previously visited page.

I will remove the qa:needed label and close this issue.
