### ISSUE TITLE
[Bug] No popup menu for text selected with mouse

### ISSUE THREAD

**Issue by grmblgrmbl** [mozilla-mobile/fenix#14568]
## Steps to reproduce

Select text **with a mouse**.

### Expected behavior

Floating menu for selected text ("copy", "search", etc) should pop up.

### Actual behavior

No menu for selected text. The menu only pops up when selecting text with the touch screen.

### Device information

* Android device: Samsung Galaxy Tab S4, Android 10

**Comment by makotokato** [comment]
@grmblgrmbl
Although I don't have test environment now (today), what behaviour of Google Chrome (and iPadOS if possbile) when using your step? Even if mouse operation, is context menu shown on Chrome (and iPadOS)?

**Comment by grmblgrmbl** [comment]
I don't know. It just makes no sense to me to not show the menu just because I selected the text with a different device. Selected text is selected text, and earlier FF for Android versions did not treat them differently.

**Comment by grmblgrmbl** [comment]
Also, when selecting text with a mouse, the selected text can not be copied to the clipboard using a keyboard. So if you use FF with a mouse and keyboard you can not use the clipboard.

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30.

> Also, when selecting text with a mouse, the selected text can not be copied to the clipboard using a keyboard. So if you use FF with a mouse and keyboard you can not use the clipboard.

I paired an apple magic mouse and keyboard to my device via bluetooth. I selected the text with the mouse after which I pressed the up arrow on the physical keyboard and the contextual menu for the copy/paste actions showed up.

> Although I don't have test environment now (today), what behaviour of Google Chrome (and iPadOS if possbile) when using your step? Even if mouse operation, is context menu shown on Chrome (and iPadOS)?

I checked on chrome and there seems to be the same functionality as firefox nightly (93.0a1) the difference being that on chrome the cursor has more cursor icons (hovering above text, dragging the screen, etc.). Can't speak for iPad since I don't have one at hand.
