### ISSUE TITLE
Collections "open tabs" opens cached pages instead of current pages

### ISSUE THREAD

**Issue by winslow-c** [mozilla-mobile/fenix#14576]
When opening a set of pages with the Collections feature, the last-opened pages appear, requiring a manual refresh of each page. This effectively cancels any convenience offered by the Collections feature.

**Comment by cadeyrn** [comment]
This is the expected behavoiur with the current implementation since collections contain tabs, not bookmarks. I know that there are plans to improve collections but I don't know the details yet and if this aspect of collections will be part of any changes. There is already a lot of discussion in #10417 so this issue could be considered as a duplicate of #10417.
