### ISSUE TITLE
 Provide an easy way to  dismiss the suggested logins prompt

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14585]
## Steps to reproduce
Go to a website where there is a suggested login
Click on any of the password feild (a keyboard and a suggested login prompt appears)
Dismiss keyboard
### Expected behavior
Dismissing Keyboard will dismiss the suggested prompt. There should be some way to dismiss this prompt and this seems most natural. Otherwise the prompt will stick around forever and needlessly take up screen space

### Actual behavior
It does not

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by apbitner** [comment]
@s-ankur Want to make sure I understand the issue here. 

> Otherwise the prompt will stick around forever and needlessly take up screen space

Once you login, doesn't the prompt go away?

**Comment by s-ankur** [comment]
@apbitner no, this is about when you don't login to a page. I'll give you an example to better illustrate

Go to https://bugs.kde.org/
Click on login (assuming that you already have a saved login for the site)
Let's say you decide not to login and dismiss the keyboard
The page has lots of other, non login related information for you to brows but now you are stuck with a suggested login prompt at the bottom of your screen that won't go away


In my opinion since the prompt appears with the keyboard it should go away with the keyboard to avoid such scenarios

**Comment by s-ankur** [comment]
This same problem is also visible on GitHub by the way.

**Comment by apbitner** [comment]
@ekager what is the trigger for displaying the 'Saved logins' panel, and is there any event for hiding it? I'm wondering if the user taps on a login/password field, but changes their mind and doesn't want to log in, if they tap outside of the form field or reload the page could we hide the panel?

**Comment by ekager** [comment]
@apbitner see my questions here about adding a UI way to dismiss the prompt on the original mocks: https://share.goabstract.com/22761c92-0ba2-4ecb-8a50-c89e1937382e?commentId=46136487-33b5-4fbe-93bc-46cd3e29573c&sha=7642013d6c1a3249098688f9300fcefc606532ba

For now I will make sure it dismisses on reload because that is definitely a bug. https://github.com/mozilla-mobile/android-components/pull/8403

**Comment by apbitner** [comment]
@ekager Thanks, I think fixing that bug will help address this edge case. Instead of adding any more UI to the panel, would it be feasible to dismiss the prompt if the user closes the keyboard per @s-ankur 's recommendation? If the user wanted to bring the prompt back, I presume they could just reload the page.

**Comment by yoasif** [comment]
I don't think reloading the page should be the only way to get the prompt back - tapping into the form should be enough.

**Comment by ekager** [comment]
As the original mocks had it clicking on the dropdown icon of the select login bar closes the keyboard so users can see the list of logins without the keyboard blocking half the screen.

I'm not sure I understand how this would work with dismissing the login selection on keyboard dismiss.

**Comment by yoasif** [comment]
@ekager What about if focus leaves the form (not simply dismissing the keyboard)?

**Comment by ekager** [comment]
That would make more sense conceptually to me, but I'm not sure that's possible.

This is already a pretty messy interaction because we're getting the message from GV that we need to show the select login dropdown through the "prompts" feature. All other prompts are shown above the web content as dialogs, so this is already a special case with a lot of custom logic. I'm not sure we could do this as it stands and it would probably require GV work.

We could add an X on the bar to dismiss the prompt if we think users need a way to dismiss it easily.

**Comment by yoasif** [comment]
FWIW, I tried this in Chrome, and the login suggestion there appears as a autofill form suggestion attached to the input. Switching away from the form makes the suggestion disappear. 

I think the drawer concept in Fenix is better because it is more "stable", but in this case, it is too stable in the sense that there is no obvious way to dismiss it.

My personal take is that it makes sense to add the X, but that feels like a temporary solution, and I'd rather file the GV work to make it work in the conceptually correct way @ekager.

**Comment by apbitner** [comment]
I don't think we should add an 'x' because 1) it's a bandaid, 2) fixing the reload bug will hide it, and 3) having an 'x' on an expand/collapse panel is an odd pattern.

Reloading the page to hide the prompt will help, but it would be great if we could get this to work when a login form loses focus as well.

**Comment by s-ankur** [comment]
Hi this is still an issue
