### ISSUE TITLE
8 suggestion/requests that are missing

### ISSUE THREAD

**Issue by R2R29** [mozilla-mobile/fenix#14658]
### What is the user problem or growth opportunity you want to see solved?

1- Save to PDF; 

2- Print option; 

3- Manage downloads; 

4- Refresh page pulling down

5- Choose how FF shows opened tabs; 

6- Change the order of opened tabs, and the same for our main sites list (above "Collections"); 

7- Edit the URL from each website stored on the "main sites list"; 

8- When we have several tabs opened, we're seeing a new website and we open another (present on the one we're at) to a new background tab, then we go to the tab list and we have to pull it up to see the most recent one. 

9- Reduce the size of the apk which is extremely big

### Device information

* Android device: OnePlus 7 Pro, Android 10, stock
* Fenix version: 80.1.2

### How do you know that this problem exists today? Why is this important?

Because i tested and i think it would contribute to the app be a lot better

### Who will benefit from it?

All the users!

**Comment by jawz101** [comment]
If this was my repo I would delete this issue.  Slapping a bunch of non-descriptive, low priority requests in one ticket right after a rollout is selfish.  There I said it

**Comment by cadeyrn** [comment]
@jawz101 

> If this was my repo I would delete this issue. Slapping a bunch of non-descriptive, low priority requests in one ticket right after a rollout is selfish.

Why do the requests have a low priority? Because you do not need them? 🤔 We should agree on the fact that feature requests have a different priority for different people.

There is also no reason to delete the issue. The issue will probably be closed because there are many feature requests in one issue but there is really no reason to delete it.

> "Change the order of opened tabs.". Really? This is a tiny phone screen.

Yes, really. It's not my issue but it's a feature that is wanted by some and not only by one user, me included. See #2487, there are really many positive reactions. I don't get your point how the screen size should affect the demand to change the order of tabs. 🤔

@R2R29 

Please open one issue per feature requests, otherwise it's not possible for Mozilla to label your individual feature requests. Much appreciated if you use the search before opening your issues because most requests are already filed.

1- Save to PDF;

#3709

2- Print option;

#10217

3- Manage downloads;

Already implemented in Firefox Nightly - if you miss something please test Firefox Nightly and file issues for the missing features.

4- Refresh page pulling down

#9766

5- Choose how FF shows opened tabs;

#13098, I guess. This description is not clear.

6- Change the order of opened tabs, and the same for our main sites list (above "Collections");

#2487 for tabs, #8141 for collections.

7- Edit the URL from each website stored on the "main sites list";

I am not sure what you mean. To you mean the top sites with the website icon and the text below the icon?

#9548

8- When we have several tabs opened, we're seeing a new website and we open another (present on the one we're at) to a new background tab, then we go to the tab list and we have to pull it up to see the most recent one.

I don't understand this request.

9- Reduce the size of the apk which is extremely big

It's not really that big. You have to consider that Firefox comes with his own rendering engine. Most other browser don't include a rendering engine, they use the Chromium WebView that is already bundled with Android.

**Comment by R2R29** [comment]
> If this was my repo I would delete this issue. Slapping a bunch of non-descriptive, low priority requests in one ticket right after a rollout is selfish. There I said it
> 
> Did you see the 2,400 other issues and think this was productive?
> 
> "Choose how FF shows open tabs.". I don't know what that means
> 
> "Change the order of opened tabs.". Really? This is a tiny phone screen. If anything, tabs need to go away after a while. It sounds overengineered- whatever it is

If you don't know what that means, it's not me who will drawing it for you.

Yes, "change the order of opened tabs"! Unless you still use a Nokia 8310, it was good if we could do it and the tabs (/opened webpages) are big enough to press it for, let's say 2 seconds, and change the order.

I never mentioned priorities; the numbers are just to keep it organised and easier to read. Also, the title is not "8 issues" and not even "8 requests"; it's "8 SUGGESTIONS/requests".
Again, drawing is not my strong...

Fortunately it's not your repo.

**Comment by R2R29** [comment]
@cadeyrn 

`Please open one issue per feature requests, otherwise it's not possible for Mozilla to label your individual feature requests. Much appreciated if you use the search before opening your issues because most requests are already filed.`

I thought that was easier to have all in just one instead opening 8 different ones.
And your completely right: I should have searched before.
I'm not used to GitHub.

Regarding the requeste:

`3- Manage downloads;

Already implemented in Firefox Nightly - if you miss something please test Firefox Nightly and file issues for the missing features.`

Don't like using beta versions; i start to think on the possibility of getting some issues precisely when i need it to work well 😄

`5- Choose how FF shows opened tabs;

#13098, I guess. This description is not clear.`

Yes, that's pretty much that.
Basically for us to have options on how we want to see all the tabs opened: like now (list), like Chrome etc, and any other way. Like we can choose between having the address bar at the top or at the bottom. Only to give us options.

`7- Edit the URL from each website stored on the "main sites list";

I am not sure what you mean. To you mean the top sites with the website icon and the text below the icon?`

Yes. Mine is in Portuguese so probably i didn't used the best translation 😁
I have it on a specific order but i saw that the URL of the 1st one changed so i would like to have the possibility to change the URL instead of creating another one and loose that order because the new one goes to the end (or the possibility to change precisely the order).

`8- When we have several tabs opened, we're seeing a new website and we open another (present on the one we're at) to a new background tab, then we go to the tab list and we have to pull it up to see the most recent one.

I don't understand this request.`

I was expecting that because i think i was not very clear.

Imagine that you have 10 tabs/websites opened on background. Then you open another, for example an article that have links to others that are from your interest and you want to read after the one you're reading; that when you go to the list of opened tabs, you have to pull the list down to see that new one you opened.
What happens at the moment is that the first one shown on the list is what your reading (and all others you opened); it doesn't go to the top of the list.

(Hum, don't know if i explained that right, again 😄)

`9- Reduce the size of the apk which is extremely big

It's not really that big. You have to consider that Firefox comes with his own rendering engine. Most other browser don't include a rendering engine, they use the Chromium WebView that is already bundled with Android.`

Well that was my minor request and the one that have me more doubts on mentioning.
Probably you're right; i don't know.

To make it clear, my intention was to show to Mozilla what would be good to see implemented. Of course not everything are suggestions that everyone wants but it's kind of difficult to please everyone.

Sorry and thanks for your kindness and work (giving the links to features already asked).

Cheers

**Comment by liuche** [comment]
Thanks for filing this, and providing more details. Since these are handled by the issues linked, I'm going to close this - you can revisit this issue again to check on those linked issues, but the good news is that you'll see we're actively working on (or have already fixed) most of these!

**Comment by R2R29** [comment]
> Thanks for filing this, and providing more details. Since these are handled by the issues linked, I'm going to close this - you can revisit this issue again to check on those linked issues, but the good news is that you'll see we're actively working on (or have already fixed) most of these!

Ok, thanks!
