### ISSUE TITLE
Adding "https by default" as a built in feature.

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14682]
From about:config on the nightly and beta versions, if **dom.security.https_only_mode** is set to ***true***, all websites use https by default.

If this feature was built into settings under privacy sub-menu, it'd be great!

Users can turn https by default on or off as per desire.

**Comment by samiuljoy** [comment]
This feature could bypass general firewall rules, and xould cause a havoc for parents if they have a firewall set up.

**Comment by clientenq** [comment]
Make sure this will not conflict with the https everywhere addon.
Since this addon was selected as one of the few to be included, please find out how users can make the best decision how to configure enforcing https. Currently the addon resolves some issues the browser option does not and vice versa.
For daily use only providing the option to enforce https without a per site opt out may not be the solution regular users are looking for.

**Comment by samiuljoy** [comment]
Good catch! Since https_by_default ruleset uses forced https, causing http only sites to show "address not found". Even with " https everywhere" add-on. Perhaps this feature could be more suitable for Firefox Focus.

**Comment by Amejia481** [comment]
Closed in favour of https://github.com/mozilla-mobile/fenix/issues/16952
