### ISSUE TITLE
Misleading "Install" option on menubar

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14747]
![Screenshot_২০২০-০৯-০৪-১৪-৩২-৪৭](https://user-images.githubusercontent.com/51329626/92284170-06647f80-eef1-11ea-8f8c-d0fe9a091800.png)

Visit to a site eg; https://virustotal.com An option saying "Install" can be seen on the side menu bar. Tap on it, and it'll create a shortcut to your homescreen of virustotal. 

The "Install" word can be misleading in this case. First time I saw that, I thought a new update was available, instead it created a shortcut to home screen of the site I was currently on. 
The word "Install" can be replaced with "Add to home" or "Create Shortcut"

**Comment by clientenq** [comment]
The text depends per site. Default add to home  screen function is for unknown reasons renamed on this site. Site has add to home screen script that is triggered on nightly when visiting. Cant investigate further since some unwise firefox developers thought it is a good idea to remove the view source function from firefox for android  and expect us to carry an additional system for debugging only to view the source of a website.

**Comment by samiuljoy** [comment]
Yes! On some sites, yes it does.

![Screenshot_২০২০-০৯-০৪-২৩-২৯-৫৮](https://user-images.githubusercontent.com/51329626/92298556-8b738700-ef39-11ea-97f0-9496243eff8e.png)

**Comment by liuche** [comment]
This is the text that we're using for Progressive Web Apps, which are meant to be able to run as "local apps". They are considered "installable", hence the install term. Clicking on it will show that you can "install" the page as a local "app".

Add to Homescreen is present for non-PWAs.

Going to close this.
