### ISSUE TITLE
Top Sites Privacy Issues

### ISSUE THREAD

**Issue by nigelh747** [mozilla-mobile/fenix#14754]
The Top Sites functionality has to respect and respond to user privacy.

This means it must not include (unless the user explicitly agrees) 
1) any sites used in Private Browsing
2) any sites bookmarked (as the user may only access in private browsing)

The user must be able, 
1) on demand to remove (not hide) any sites shown in top sites
2) clear all top sites on demand and when closing the browser

These issues are Defects (bugs) with the implementation and are not feature requests

**Comment by nigelh747** [comment]
This is a security issue in my opinion, but I can't see how to mark this accordingly

**Comment by yump** [comment]
Assuming private browsing works as intended, visiting pages in private browsing mode, bookmarked or otherwise, should not modify the frecency statistic.  So if you are seeing sites used in private browsing in Top Sites, then either:

1. Private browsing is not fully blocking modification of local state (correctness problem).

2. You are visiting them in normal browsing mode and not realizing it (UI problem, given heroic responsibility).

The ability to "remove" (hide) Top Sites individually already exists.  It *must* be hiding, and not removal, because you have to store the user's preference not to have that page show up in Top Sites again.  Otherwise it would tend come back when they visited the page again, and helping the user curate the list of Top Sites is the entire point.

The use cases for "Clear all top sites on demand and when closing the browser" are better served by:

1. Clear recent history (hour, day, session, etc.), which should revert all changes to frecency statistics due to browsing during that time.

2. Always open in Private Browsing mode.

Both of these may or may not already exist.  I don't know.

But essentially, I am saying that what you want is not connected to Top Sites, specifically, and if Private Browsing and history clearing are implemented correctly, the behavior you want should just drop out.

**Comment by nigelh747** [comment]
> 
> 
> Assuming private browsing works as intended, visiting pages in private browsing mode, bookmarked or otherwise, should not modify the frecency statistic. So if you are seeing sites used in private browsing in Top Sites, then either:
> 
>     1. Private browsing is not fully blocking modification of local state (correctness problem).
> 
>     2. You are visiting them in normal browsing mode and not realizing it (UI problem, given heroic responsibility).
>

I believe that the issue is via option 1 - regardless of being option 2 I should have the ability to reset (not hide) any data stored by Firefox 
> 
> The ability to "remove" (hide) Top Sites individually already exists. It _must_ be hiding, and not removal, because you have to store the user's preference not to have that page show up in Top Sites again. Otherwise it would tend come back when they visited the page again, and helping the user curate the list of Top Sites is the entire point.
> 
While I understand your view, there MUST be a way to remove any history about any visit to any website,  The clear functions within Firefox Android must provide the ability to remove top sites or any data, but they do not.  The only solution is to remove all Firefox Data via the Android App settings, then you have to add your account, wait for the synchronisation and do all the manual set ups that you have.  Its honestly NOT a realistic solution.  Putting the functionality for Top Sites has to be in my opinion, an option for someone to have not a mandatory feature that it currently is

> The use cases for "Clear all top sites on demand and when closing the browser" are better served by these features:
> 
>     1. Clear recent history (hour, day, session, etc.), which should revert all changes to frecency statistics due to browsing during that time.
> 
>     2. A setting to always open in Private Browsing mode.
> 
> 
> Both of these may or may not already exist. I don't know.
> 
Neither of these cases appear to exist, which is why I have raised this bug

> But essentially, I am saying that what you want is not connected to Top Sites, specifically, and if Private Browsing and history clearing are implemented correctly, the behavior you want should just drop out.
- agreed - but its not implemented properly and therefore Firefox does not provide the users with the Privacy that is announced!

**Comment by jawz101** [comment]
I don't want to see any history on my homepage.  Only items I explicitly choose to pin there

**Comment by cadeyrn** [comment]
@jawz101 You don't have to have this feature be enabled, it's optional.

**Comment by jawz101** [comment]
> @jawz101 You don't have to have this feature be enabled, it's optional.

How do I disable it?

**Comment by liuche** [comment]
Private browsing is not included in top sites frecency, only history items. Bookmarks are not explicitly excluded (and wouldn't make sense to do that - plenty of people visit their bookmarks frequently).

You can turn this off in settings.

**Comment by nigelh747** [comment]
There is no option to switch off top sites in the released code.

Please reopen this request or I simply will clone this ticket every day

**Comment by liuche** [comment]
Github is not a forum to try to coerce this developers into doing things.

We've tried to provide helpful information (and recommend that you update your app, because there is no channel where the top sites and the setting are not both present in the most recent build). I believe your issue is solved, and others have also agreed with that.

Consider this a warning, and if you re-clone issues you will be removed from being able to access this repo.

Please read the contributor guidelines here: https://bugzilla.mozilla.org/page.cgi?id=etiquette.html

**Comment by nigelh747** [comment]
> Github is not a forum to try to coerce this developers into doing things.
> 
> We've tried to provide helpful information (and recommend that you update your app, because there is no channel where the top sites and the setting are not both present in the most recent build). I believe your issue is solved, and others have also agreed with that.
> 
> Consider this a warning, and if you re-clone issues you will be removed from being able to access this repo.
> 
> Please read the contributor guidelines here: https://bugzilla.mozilla.org/page.cgi?id=etiquette.html

I am using the latest version from the PlayStore and what you say is not there.

Therefore this ticket should remain open

**Comment by Dunexus** [comment]
@nigelh747 
In nightly, in Settings > Customize, you have a switch to turn off "Show most visited sites" on homescreen.
If it is not in the release version yet, it will be soon.
