### ISSUE TITLE
Should DarkReader inform users about impact on perceived Firefox performance?

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#14788]
## Steps to reproduce
Install DarkReader

### Expected behavior
DarkReader should get acknowledgement from user that he's aware of the possible impact on performance for complex sites
Or at least a disclaimer about the impact on navigation... or whatever other solution (setting "Enable by default" (...on all websites) set to off at installation???)

### Actual behavior
DarkReader is installed without further warning.
But some complex yet popular sites may suffer from bad performance because of DarkReader, while the user may think that Firefox itself is slow.

This actually is true about any other performance-impacting addon, especially the popular ones that may be installed by any type of user, not only those already aware of such impact with addons.

**Comment by cadeyrn** [comment]
You should suggest it to the developer of Dark Reader because it's an add-on issue. I don't see how it should work in practice that Firefox shows a warning for specific add-ons. They can't measure the impact of every available add-on, especially not if all add-ons will be allowed, and then show an individual warning for every add-on. Not only that it needs a really big effort it's also bad for the add-on developers if one add-on gets a warning and another one not.

**Comment by klint** [comment]
You are right, but the very short current list of available add-ons is curated by Mozilla, not by the add-on authors. And the one who will get bad press because is it slow allegedly is Mozilla, not the add-on authors. Especially as the list is short, so Mozilla is more expected to have checked performance, and especially with popular non-power-users-dedidacted add-ons like DarkReader.

Imho, it is Mozilla who should handle performance directly with authors of the addons they place on their curated list. Now, whether Mozilla rejects an addon from the list, or asks for a disclaimer to be added and/or a change to be done by the author, or does it by itsef, that is not my decision :).

For the time being, I now have chosen to deactivate DarkReader for all sites, and only activate it site per site for my most visited sites where it does not hinder performance. :)

**Comment by clientenq** [comment]
I expect any performance issues related to user choice to enable one or more addons to be acceptable risk. Even if these issues are positive.
Firefox does also not warn or explain different browser versions can cause performance issues unless caused by bugs or expected to be promotional information.
Otherwise the best place would probably be to start explaining performance issues related to addons in the disclaimer.

**Comment by MarcLeclair** [comment]
@liuche What do you think about this?

**Comment by liuche** [comment]
Hey @MarcLeclair I chatted with Vesta about this, and since addons are known to slow down the browser (including Fennec) we won't do anything about it.

However, @amedyne will take a talk to the addons team on Desktop do, and maybe come back with some information about any suggestions they have for Mobile.

In the future, we may try to get some kind of notification for slow sites #14959

**Comment by amedyne** [comment]
- There is already a way to inform a user that "the page is slowing down". It is working for both Firefox desktop and on Fenix. There is nothing specifically implemented for addOns/extensions.
-  Desktop has an abuse report (https://sql.telemetry.mozilla.org/dashboard/add-on-abuse-reports) where Performance is one of the categories. 
-     To implement the equivalent abuse reports for Fenix will be a mobile team priority call. I think this is something size and to bring up for prioritization.

**Comment by liuche** [comment]
@MarcLeclair could you take a look at the options that amedyne mentioned above, and if they would help Perf testing infrastructure? (and if so, summarize how? so we can decide how prioritize)

**Comment by MarcLeclair** [comment]
@liuche Could you clarify what you mean by helping the Perf testing infrastructure?  

Also, as for the "The page is slowing down",  there's currently some research into having long-running script notifications (or how to notify the users).

**Comment by liuche** [comment]
Hmm, I was thinking that the abuse report was something automated that could be included to send proportions of what was causing problems on addons, but it looks like it might be a survey? not SDK/telemetry probes - so nevermind.

**Comment by mcomella** [comment]
Triage: ecsmyth will talk to the add-ons team to move this forward.

**Comment by jvillalobos** [comment]
We want to implement abuse reporting in Fenix eventually, but I don't think it'll happen this year. And, as mentioned, it's a form sent by users, it's not automatic. We can use that data to inform developers about it and help them improve their mobile performance. However, the best way to improve add-ons is to send these reports to their developers.
