### ISSUE TITLE
[Bug] White Splash on Quit

### ISSUE THREAD

**Issue by mackeev** [mozilla-mobile/fenix#14801]
## Steps to reproduce
Tap Quit on any opened page (but Top sites)
### Expected behavior
No spash or black spash if your theme is Dark
### Actual behavior
Pretty long-lasting eyes-hurting white splash
### Device information

* Android device: xiaomi note 5 pro
* Fenix version: any

**Comment by Diana-Rus** [comment]
Hi, reproduced the issue on Nightly 9/7 with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

<details closed><summary>GIF Nightly-Samsung</summary>

![20200907-143512](https://user-images.githubusercontent.com/49859863/92384208-53766a80-f118-11ea-8a4a-be0fd3a61607.gif)
</details>

Note: With Google Pixel 3XL (A9) the issue is not that  obvious.

**Comment by mackeev** [comment]
Seems fixed in the latest Nightly. But...
There is a new one: white splash when entering Reader View.

**Comment by amedyne** [comment]
@mackeev Can you check if this is still a problem for you? Thanks!

**Comment by mackeev** [comment]
It's no longer a problem.

**Comment by amedyne** [comment]
Thank you for checking @mackeev !
