### ISSUE TITLE
font inflation issue on old.reddit.com

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#14806]
As reported on https://github.com/webcompat/web-bugs/issues/57375

>  Description: in chrome, text is formatted big enough to be readable. in Firefox the font is -tiny- ...I wish there was an option to set a minimum font size that would still reflow into appropriate width on mobile screen.

Steps: 
1. Go to https://old.reddit.com/r/worldnews/

Expected: bigger font
actual: small font

Compare to chrome

Device: Pixel 2
Browser: 82.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6489)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 200907 (Build #2015762483)
### Devices used:
- OnePlus 6T (Android 9)
- Huawei P Smart (Android 9)

**Comment by MicroBeast** [comment]
I'm wondering; how small the font look in this issue.

All my devices are far older, Android <9 too. But with ``Automatic font sizing`` in Accessibility, the font size look same like in Chrome Screenshot (from linked issue).

From Firefox 82.0a1 Nightly 200906 18:01 (Build #2015762385)

**Comment by kuro68k** [comment]
Can confirm on Pixel 5.

Chrome:

![Screenshot_20210106-161240](https://user-images.githubusercontent.com/2674466/103791192-0eb4fe80-503a-11eb-87f2-ceb9bd280d48.png)

Firefox:

![Screenshot_20210106-161245](https://user-images.githubusercontent.com/2674466/103791208-14aadf80-503a-11eb-8a58-9f2071c163c9.png)

Firefox is unreadable at that size. Zooming to make it readable makes me have to scroll left and right for every line.

![Screenshot_20210106-161347](https://user-images.githubusercontent.com/2674466/103791333-3c01ac80-503a-11eb-9485-09a27c89bf59.png)

**Comment by kuro68k** [comment]
Some progress: https://bugzilla.mozilla.org/show_bug.cgi?id=1685756

**Comment by kuro68k** [comment]
Can confirm it's still there in 98.0a1 build #2015861643 (nightly). Affects many other sites too.

Font size is more reasonable if Accessibility->Automatic font sizing is enabled. When disabled and the font size setting set to maximum, the text on some web pages is still too small to read comfortably and the setting appears not to work on Pixel devices (confirmed on Pixel 5 and Pixel XL).

**Comment by Javi** [comment]
This would be fixed when https://github.com/mozilla-mobile/fenix/issues/808 lands

**Comment by buttercookie42** [comment]
> Font size is more reasonable if Accessibility->Automatic font sizing is enabled. When disabled and the font size setting set to maximum, the text on some web pages is still too small to read comfortably and the setting appears not to work on Pixel devices (confirmed on Pixel 5 and Pixel XL).

If I remember correctly, font inflation is currently only turned on when "Automatic font sizing" is enabled. So if you turn auto mode off, font inflation is turned off, too, and desktop-style pages like old.reddit.com once again start out with an effectively much smaller font size than pages with responsive layout.

Having a separate toggle for font inflation might help so it could be turned on and off independently, as would just leaving it on permanently. I think a very similar discussion already happend even during Fennec days, and the problems were:
- Leaving it turned on permanently (as it originally used to be in Fennec): While it also tremendously improves readability on lots of non-mobile/non-responsive pages, font inflation can also cause noticeable layout breakage on some pages, so some escape hatch was considered required, i.e. the ability to turn it off again. (At that time, the sentiment was such that for a little while it was even considered to instead permanently get rid of font inflation, nevermind what that would mean for the readbility of older, non-responsive pages…) Since that discussion happened, I did land a few small bug fixes which I think have improved the situation somewhat, but I have to admit that our implementation is probably still a little buggier than Chrome's implementation (and Safari's, I guess, if it still exists?).
So I've got no idea how well or not permanently turning it on again would work. Enabling desktop mode for a page still works for turning off font inflation locally for the current page, but I'm not sure a) how discoverable that feature is and b) whether a global on/off might still be desirable anyway.
- Having a separate option/toggle switch for font inflation: Within the space-limited context of the settings panel, nobody came up with a good way of how to succintly explain what font inflation does and why a user would want to turn it off/on, so a separate toggle for it was discarded on grounds of it being too confusing. Maybe somebody has a better idea this time around?

**Comment by kuro68k** [comment]
I'd suggest that a very large number of sites being unreadable or extremely awkward to use is probably worse than a small number of sites having layout issues. It would be useful to have some statistics to see if that is the case.

In Chrome the setting is described as "minimum font size", and it appears that it works by looking at paragraphs of text and wrapping them such that when zoomed to fit the screen the minimum font size is observed.

As for the settings issue, I'd suggest it's just a case of adding some logic for certain devices where the user's preference in the settings does not match what is rendered in the browser. It seems to work for some people, but not on Pixel phones.

**Comment by Javi** [comment]
This is very much still an issue, plaguing every single Android browser except Opera. Getting it would immediately improve Firefox on Android, there's tons of people who are trapped because of this problem.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813274

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
