### ISSUE TITLE
[Bug] Fenix opens Play Store url instead of Play Store app

### ISSUE THREAD

**Issue by GuillaumeBourge** [mozilla-mobile/fenix#14811]
## Steps to reproduce
Clic on a Firebase Dynamic Link from an App or web page

### Expected behavior
The Link should open the app (if installed), or the PlayStore on the app page, or the fallback url if the app do not exists on the playstore.

### Actual behavior
When i clic on the Firebase Dynamic Link from an app, that open the Firefox internal browser, with the playstore page of the app

### Device information

* Android device: Xiaomi 9t on Android 10 // Samsung A40 on Android 9
* Fenix version: last release from PlayStore : 80.1.2

On chrome it works fine, anyone encounter this issue ?

**Comment by PaulWoitaschek** [comment]
This is the same issue as https://github.com/mozilla-mobile/fenix/issues/14811
Once you enable "Open links in apps", the deep links start working again.

This is a big issue because opening links in apps should be the default. For example we use the link to our app to authenticate the user with several services and all of this is broken with "open links in apps" disabled.

**Comment by maxxx** [comment]
Hi guys, the issue is still reproducible on firefox 86.1.1, ".page.link" app (deep) links can't be opened. Toggling "Open links in apps" solves it, but why it's not enabled by default? 

Also, is there any way to enable it automatically without user actions? On rooted device or with device manager, I mean maybe it's possible to edit config (if have file access).
