### ISSUE TITLE
FNX-45 ⁃ [Meta] Containers support

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#1481]
### Why/User Benefit/User Problem
Being able to contain different websites to different containers to improve privacy and usability.

### What / Requirements
Feature parity with desktop Firefox

### Acceptance Criteria (how do I know when I’m done?)
Feature parity with desktop Firefox as well as ability to user Web Extensions that makes use of container feature

**Comment by NatoBoram** [comment]
As I understand it, this could be resolved by #574 and [multi-account containers](https://addons.mozilla.org/addon/multi-account-containers/).

**Comment by andreicristianpetcu** [comment]
@NatoBoram not necesarily. Fennec supports WebExtensions but not the ones with Containers. Hope Fenix will not have this limitation.

**Comment by NatoBoram** [comment]
Oh, that would be the Container API. I hope they support it, otherwise they wouldn't have full WebExtensions support.

**Comment by kostrse** [comment]
This should be implemented into the core browser design.

The "private tab" is just a subset of the "container" feature, that container just not permanent.
It would be great if all internet surfing would be in always in containers by design, one of them would be just "default". So, deleting cookies/data would be just deleting one container (e.g. the default one) and making another.

**Comment by philippemorin123** [comment]
As a end-user with no background in coding (except for the MIT App Inventor 😅), I want to say I would love to have this feature, especially since I just got a notification from Firefox 73.0 for Windows about containers being now synced between devices.
Please! :D

**Comment by liuche** [comment]
Duping to #10581
