### ISSUE TITLE
[UX] UI for all recommened mobile WebExtensions

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14918]
## User Story
- As a user, I want to easily view and sort through all recommended mobile WebExtensions in the browser and find what I am looking for. 

## User Problem
The current UI only supports 10-15 WebExtensions. After that it will become difficult for user to sort through the available add-ons and find what they are looking for. 

### Acceptance Criteria
- I can find the add-on I am looking for either by searching, sorting, or another intuitive way.

**Comment by amkcpu** [comment]
I would suggest doing something aligned with FF on desktop, where `about:addons` shows your currently installed add-ons on top and features some recommended extensions below (for me, four extensions are recommended). Below that, there is a link pointing to `addons.mozilla.org` (AMO).
I believe users expect to find and load add-ons from AMO, because that's what they do on desktop and how it used to be on Fennec. Also, one is much more flexible with the website and does not have to code a new experience from scratch.

**Comment by Poopooracoocoo** [comment]
@vesta0 here's a collection of some related issues: #15791

**Comment by vesta0** [comment]
Thank you @Poopooracoocoo 

@brampitoyo FYI
