### ISSUE TITLE
[Bug] Site notifications may not be working for some sites 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14924]
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1664180

## Steps to reproduce
- Open a new tab and navigate to www.ricardocuisine.com

### Expected behavior
- You will see a prompt for site permissions (see example from Fennec and Chrome below) 

### Actual behavior
- There is no prompt. 

### Device information

* Android device: Pixel 4
* Fenix version: Nightly 200909 06:00 (Build #2015762867)

![Screenshot_20200823-020515](https://user-images.githubusercontent.com/42752644/92686126-0efcf180-f307-11ea-882c-7c57cdf96859.png)
![Screenshot_20200823-020501](https://user-images.githubusercontent.com/42752644/92686144-191ef000-f307-11ea-9a77-725c7cc8fd43.png)

**Comment by Amejia481** [comment]
We are not getting the notification request from GV I filed a bug on for the team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1664180

**Comment by liuche** [comment]
This is possibly an edge case, because notifications should be working on other sites.

**Comment by yoasif** [comment]
Does not work on https://webpushdemo.azurewebsites.net/ -- tested on Pixel 2 on release, beta and nightly.

**Comment by wurstsemmel** [comment]
On my Samsung Galaxy S9 with Android 10 / One UI 2.5 and Firefox 85.1.3 the notifications from https://webpushdemo.azurewebsites.net/ do not work. After granting permission nothing happens when hitting the button on the test website.

Notifications also do not work on a self-hosted Discourse instance.

In both cases notifications work on Chrome for Android.
