### ISSUE TITLE
mobile_versions.json reporting outdated Android version

### ISSUE THREAD

**Issue by ray10011** [mozilla-mobile/fenix#14928]
Hi team,
We rely on this data retrieved from: https://product-details.mozilla.org/1.0/mobile_versions.json to check what the latest version of Firefox on Android is. 
It is currently reporting "version": "68.11.0", last July's release when the latest version is "80.1.2".
Will this info be updated and will it be a reliable source in the future?

Cheers

**Comment by liuche** [comment]
@JohanLorenzo is there a better place where we are uploading this? Or are we not uploading this at all due to releases being done through Github? Not sure about the priority, but wanted to check in case we are actually publishing this (but to a different location).

**Comment by JohanLorenzo** [comment]
Hi @ranasr! 

Thank you very much for filing this issue. It's fallout of the Fennec to Fenix migration. You pointed the right thing out, @liuche! We'll be able to update that endpoint once https://bugzilla.mozilla.org/show_bug.cgi?id=1568466 is done. I made some progress earlier this week. I'll keep you all tuned!

**Comment by ray10011** [comment]
Hi Johan, any update on this? Unfortunately I don't have access to https://bugzilla.mozilla.org/show_bug.cgi?id=1568466 so I'm unable to see the progress. Thanks!

**Comment by JohanLorenzo** [comment]
Hey @ray10011! 

Thanks for pointing this out! I don't think [bug 1568466](https://bugzilla.mozilla.org/show_bug.cgi?id=1568466) should be hidden anymore. I opened it up! 

@camd and I have been working on this issue since last week. It's taking longer than I originally thought but at least, we put some time on it. I'll circle back on this issue once this is done.
