### ISSUE TITLE
[Bug] Pull to refresh not triggered when iframes are present in the top of a webpage

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14942]
## Steps to reproduce
1. Go to https://www.w3schools.com/html/tryit.asp?filename=tryhtml_iframe_height_width
2. Tap inside the iframe.
3. Scroll down.

### Actual behavior
At the moment the pull to refresh action is not triggered when iframes and textboxes are present at the top of the wepage
![image](https://user-images.githubusercontent.com/49859863/92730708-d5ff6400-f37c-11ea-9f0e-6c298fba75e9.png) and executes the refresh functionality

Should the iframe, textboxes or other elements from a page impact in anyway the pull to refresh functionality?

### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: Local build created that contained the pull to refresh functionality enabled
Issue related to #10241

**Comment by Mugurell** [comment]
Looked into this a bit since it is related to the pull to refresh functionality.

It looks to me like we have the correct behavior.
As in the case of the bottom toolbar we will not respond to scrolls happening in iframes, scrollable divs or on webpages with their own apz-aware listeners, this information coming to us from GV [here](https://github.com/mozilla-mobile/android-components/blob/800b465772f2faa0a48ecafd2e93c05a24e9d4ea/components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt#L66)

As such I will close this.
If there are situation where the same gesture animates the bottom toolbar but would not trigger pull to refresh we can reopen/file a new ticket.
