### ISSUE TITLE
Reinstate the ability to open hyperlinks in either private or normal tabs via the android share menu.

### ISSUE THREAD

**Issue by thomasstani** [mozilla-mobile/fenix#14995]
### What is the user problem or growth opportunity you want to see solved?

As a user I want to be able to open links from the share menu directly into private browsing mode or standard browsing mode on a link by link basis.

### How do you know that this problem exists today? Why is this important?

A while ago, in the alpha builds of Fenix (perhaps pre play store?) It was possible to use androids share menu to either open a link in a private tab or a normal tab. This feature has since disappeared. It would be ideal if it could be reinstated.

### Who will benefit from it?

People who apreciate the choice to open links either privately or in normal browsing modes on a link by link basis.

**Comment by liuche** [comment]
Thanks for filing this issue! We originally tried this back in October using app-aliases, but ran into problems with Android 5 & 6 not being able to use "Default Browser" functionality. We may revisit this later, because it's clearly a great feature to have! but for now, please take a look at the linked issues #5742 and #5972.
