### ISSUE TITLE
Make swipe to delete bookmarks nightly only

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#15007]
Talked with Vesta and there are some valid concerns about swipe to delete bookmarks being dangerous. The main problem being that once the snackbar disappears we don't have any other way to recover the user's data. From desktop studies we have found that users care a lot about their bookmarks. 

This needs to be uplifted to the 81 branch.

**Comment by Poopooracoocoo** [comment]
thank you! 🥰 always found swipe to delete bookmarks annoying

**Comment by sflorean** [comment]
Verified as fixed on 81.1.1-beta.4 with the following devices: Samsung Galaxy Note 10 (Android 10), Google Pixel 3 (Android 11), LG G7 Fit (Android 8.0).
Bookmarks and folders can't be deleted using swipe.

**Comment by cadeyrn** [comment]
@kbrosnan Since the feature was not removed but made Nightly only I guess the plan is to bring it back in a better way (whatever it looks like, maybe an option like for the other gestures). Is there already an issue for that (even if it's only investigation and not implementation)? Otherwise it would be a good idea to create one and leave a link in this issue, even if it is not worked on immediately, so that it's documented where people can follow the future of this feature. What do you think?

**Comment by kbrosnan** [comment]
opened https://github.com/mozilla-mobile/fenix/issues/15362
