### ISSUE TITLE
FNX-5067 ⁃ [QA Request] A-S team would like help validating the new networking stack

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-mobile/fenix#1501]
Owner: Quality Team

## Context
* Application Services team recently [updated the rust networking stack](https://docs.google.com/document/d/1nIcIqY0_-ElgPE4s1DQBRJHYBqZvi3kHrbvwr2HvYGc/edit#) to use Necko instead of rust libraries.  We want to be sure that the rust components we deliver in support of history and bookmarks syncing, FxA and Send tab / push network calls are functioning as expected.

## Dependencies
* Update to application-services 0.24.0 (currently blocked, will update when unblocked)

### Acceptance Criteria
* Syncing – with various network conditions (stable fast, stable slow, spotty, disabled), result in no crashes
* Send tab – with various network conditions (stable fast, stable slow, spotty, disabled), result is no crashes
* Two (or more) different devices syncing at the same time on the same account results in no crashes (Note: one device may fail to sync, but a subsequent sync should succeed)

cc @st3fan

**Comment by npark-mozilla** [comment]
@st3fan just to double check, since I'm assigned now, the story is ready to be tested now? (sorry, learning new process)

**Comment by jdragojevic** [comment]
@npark-mozilla  - this is likely my mistake.  Testing it blocked until application-services 0.24.0 is built.  I may be messing up the process as I thought I was suppose to make a QA bug and assign you.

**Comment by thomcc** [comment]
There's a known issue with the 0.24.0 build (recognized late yesterday) and we'll be cutting a 0.24.1 as soon as it's fixed. https://github.com/mozilla/application-services/issues/939

**Comment by kbrosnan** [comment]
Is this ready for work?

**Comment by kbrosnan** [comment]
Removing QA needed as there is no info on if this is ready to test. Please add it back when it is ready.

**Comment by vesta0** [comment]
This is ready to test :)

**Comment by abodea** [comment]
Verified as fixed in the latest version **`1.0.1921(Build #11400615 68.0a1-20190508111321)`**.
Note that I was able to test the following scenarios also mentioned in the description.
- Syncing with various network conditions **(stable fast, stable slow, spotty, disabled)**
  - Stable Fast using **`Wi-Fi connection`**:
    1. Download and Install Fenix.
                                 -

**Comment by abodea** [comment]
Verified as fixed in the latest version **`1.0.1921(Build #1142060 68.0a1-20190508111321).`**
Note that I was able to test the following scenarios also mentioned in the description.
**`Devices used: Google Pixel 3(Android 9) and Samsung Galaxy S8+(Android 8)`**.
### Syncing with various network conditions (stable fast, stable slow, spotty)
* Launch Fenix, connect with an FF account, while the connection is **`Stable Fast`** perform at least 5 syncs.
* Launch Fenix, connect with an FF account, while the connection is **`Stable Slow`** here I went away from **`Wi-Fi until I had like 1/2 lines`** and also, I tried this with a **`HOTSPOT`** - at least 10 syncs.

Regarding the **`HOTSPOT`** I limited the connection to the following: 
- LTE/3G/2G -- this option is the strongest one resulting in 4G - no crash after sync
- 3G/2G -- this option is much slower then the previous one - no crash after sync.
- 3G only -- No crash after syncing.
- 2G only -- No crash after syncing.
### Send Tab with various network conditions (stable fast, stable slow, spotty, disabled)
The only way to share a tab right now is with the apps from the same phone and not between others.
I've tested the share option to Nightly for this case with the following connections:
- Wi-Fi -- high and low connection - no crash after sending the tab.
- LTE/3G/2G -- this option is the strongest one resulting in 4G - no crash.
- 3G/2G -- this option is much slower then the previous one - no crash.
- 3G only -- No crash.
- 2G only -- No crash.
### Syncing two different devices at the same time on the same account
- I connected with the same account to a Google Pixel 3(Android 9) and Samsung Galaxy S8+(Android 8.0.0) and synced at least 10 times in the same time -- no crash after the sync.
Also, I tried the sync between 2 devices(how I mentioned above) + syncing on the desktop in the same time -- no crash.

### Notes
The part with the Hotspot was the only one where I could improvise and create a real case-scenario with lower internet connection.
