### ISSUE TITLE
When opening multiple bookmarks, the order opened should be the order selected

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15036]
## Steps to reproduce

Select the bookmarks menu and select mutiple bookmarks, not in the order displayed

### Expected behavior

Bookmarks when opened should be in the order selected to be opened

### Actual behavior

Bookmarks open in the order of the list 
### Device information

* Fenix version: 80.1.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6854)

**Comment by clientenq** [comment]
This is probably a feature request.

The bookmark selection is currently a selection list without order priority. Thus the ordered bookmarks open in order of the position in the bookmark list.

As a user I would welcome a feature that focuses on user actions instead of current bookmark list order to prioritize the tab order.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812710

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
