### ISSUE TITLE
[Bug][downloads] "Try again" doesn't work after the connection is reestablished

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15069]
## Steps to reproduce
1. Start the download of a larger file and turn off/disconnect the WiFi.
2. Reconnect the device to the WiFi network. 
3. Tap Try again on the app notification.

### Expected behavior
The download is restarted. The failed notifications are dismissed.

### Actual behavior
The download is not started. The notification is displayed again after tapping on "Try again".

### Device information
* Android device: Xiaomi Mi Pad 2 (Android 5.1), OnePlus 6T (Android 9), Sony Xperia Z5 (Android 7).
* Fenix version: 81.1.1-beta.4 &3, Nightly 9/14.

### Notes
Not reproducible on Samsung Galaxy Tab S3 (Android 8), Google Pixel 4XL (Android 10).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6911)

**Comment by AndiAJ** [comment]
Reproducible on **`Firefox 88.0.0 Beta 1`** using a OnePlus A3 (Android 6.0.1)

**Comment by delia-pop** [comment]
A similar issue is encountered on the latest Nightly build (100.0a1) and latest RC build (98.3.0).

STR:
1. Visit a page with downable content.
2. Interrupt the network connection.
3. Tap on the downable file. 
4. Reestablish the network connection from the error screen.
5. Tap on the "Try again"/"Reload" option from the error screen.
6. Tap the Reload icon from the 3-dot menu.
7. Observe the result.

Expected behavior
The Error screen is dismissed, and the user is returned on the page from Step 1. 

Actual behavior
The Error screen remains displayed, and a prompt to download the file selected in Step 3 pops up every time after tapping the "Try again"/"Reload" option or the Reload option from the 3-dot menu.

https://user-images.githubusercontent.com/89388888/160422917-9889395f-4e66-4169-b94d-def66ed9a3ae.mp4

https://user-images.githubusercontent.com/89388888/160422959-2944bfca-b184-4fe5-a61a-ed0a6f5713c6.mp4
