### ISSUE TITLE
[Bug] Recently Closed does not open tabs in PB

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15084]
## Steps to reproduce
In private browsing go to History/recently closed
Click on a tab
### Expected behavior
Tab opens in PB. This is how other tabs in history behave

### Actual behavior
Open in normal mode
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by ekager** [comment]
The recently closed tabs are being restored (with the state of when they were saved including backstack, private/nonprivate state, etc). Since we are only saving tabs from non-private mode, all of them will be non-privately restored, so this is not necessarily a bug, but perhaps we need UX feedback.

**Comment by s-ankur** [comment]
Unless it can be made explicitly clear that this is restoration, I think it would be best to just open the url, like history items do

**Comment by yoasif** [comment]
Tab restore means tab restore - which to me does not mean opening recently closed tabs in a different browsing context. 

The bigger issue with closed tabs is that there is no indication that it is anything *other* than a history entry - tabs contain more than just the last page visited in the tab, but the current UI does not show that in any way.

**Comment by ekager** [comment]
I think restoring the state of the tab is valuable if we are assuming people use recently closed tabs as a way to access tabs they didn't mean to close.

I see 2 options that could improve understanding as the feature exists:
1. Be more clear about the "restore" - ie something like "Restore Recently Closed Tabs" in the menu/toolbar instead of "Recently Closed Tabs"
2. Hide Recently Closed Tabs section while in PBM because they will always be normal tabs and won't be saved/restored in PBM anyway.

cc @topotropic for UX feedback on the issue

**Comment by yoasif** [comment]
> Hide Recently Closed Tabs section while in PBM because they will always be normal tabs and won't be saved/restored in PBM anyway.

@ekager this helps (and should happen), but the bug @s-ankur referenced shows up in history. Should we simply file a bug for this?  

I opened https://github.com/mozilla-mobile/fenix/issues/15088 for some ideas on how to differentiate closed tabs from pages in the UI as well.

**Comment by ekager** [comment]
@yoasif I think history entries on tap just open in the current mode, right?

**Comment by yoasif** [comment]
> @yoasif I think history entries on tap just open in the current mode, right?

Yes.

**Comment by topotropic** [comment]
Thanks for the feedback! I agree with Emily:

> The recently closed tabs are being restored (with the state of when they were saved including backstack, private/nonprivate state, etc). Since we are only saving tabs from non-private mode, all of them will be non-privately restored

I'll close this issue and we can look at the other topics that were brought up separately.
