### ISSUE TITLE
Delete browsing data should clear recently closed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15092]
## Steps to reproduce
Go to settings delete browsing data and delete current tabs by selecting only the open tabs option
### Expected behavior
The tabs do not appear in recently closed. Otherwise there would be no point to having that option. 
### Actual behavior
They do appear in recently closed. Feels like a privacy violation
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6947)

**Comment by ekager** [comment]
All that "delete current tabs" does is close all tabs. Do you have a different expectation?

**Comment by jothki** [comment]
> 
> 
> All that "delete current tabs" does is close all tabs. Do you have a different expectation?

Presumably something stronger, in the same way that deleting a file is stronger than closing it. Using "delete" for closing open tabs doesn't track with how many people view tabs as temporary contexts that only exist as long as the user needs them.

**Comment by s-ankur** [comment]
On a related note, I don't want to delete all my user data, so can anyone tell me what happens when you delete all user data? Do current tabs show up in recently closed when you delete all browsing data?

**Comment by eliserichards** [comment]
Related to #15112

**Comment by s-ankur** [comment]
@eliserichards I think the renaming is incorrect. Currently delete browsing data does clear recently closed as they are considered part of the "Browsing data and history item"
I made this issue to request that the "Open Tabs" option in delete browsing data should not just append the deleted tabs to recently closed list.

**Comment by jothki** [comment]
Is there a use case for deleting information on only the tabs that are currently open, but not ones that have been recently closed? If you just want to destroy everything from your current session once you're done with it, private browsing is already an option.

If anything, I don't think that that option should exist in that particular menu at all, since it's not tied into actually erasing data, and is apparently causing user confusion as to what it's doing. I'd much rather have it set up like in Fennec where keeping or closing open tabs is an entirely separate option on the menu.

**Comment by ekager** [comment]
UX - I think there's some confusion we've uncovered around "delete current tabs" in the the delete browsing data setting. In implementation "delete current tabs" just closes the current tabs. Should we either remove this item from "delete browsing data" or modify the strings to reflect that it's not actually "deleting" anything?

**Comment by s-ankur** [comment]
Please also consider the third possibility: having the option actually delete the tabs

**Comment by yoasif** [comment]
FWIW, Desktop Firefox does not close tabs in the Clear Recent History dialog:

![image](https://user-images.githubusercontent.com/152493/93510014-92fa3f00-f8ee-11ea-9e14-cb10ef3edb44.png)

**Comment by topotropic** [comment]
> "Open Tabs" option in delete browsing data should actually delete the open tabs instead of just closing them and appending them to recently closed list.

Yes, sounds good. Thanks!

**Comment by ekager** [comment]
I'm not sure what "deleting tabs" means. History (URL) storage is completely independent of the concept of a "tab" and we can't currently remove certain history entries based on which tabs we have closed. If you just mean that it shouldn't add to recently closed when closing tabs with "delete browsing data", then we could try to figure that out but it would require AC work. We should acknowledge this could _also_ confuse users though because they could expect to be able to fetch these closed tabs from recently closed...

FTR selecting to delete "Browsing history and site data" _will_ clear history AND recently closed tabs.

I think we could make this interaction more clear by adding a new description string to the "Open tabs" option for "Will close X open tabs" so that users clearly understand we are *just closing* all current tabs.

**Comment by yoasif** [comment]
@ekager I agree with your last comment.

**Comment by s-ankur** [comment]
If my suggestion will be difficult to implement, then I guess it makes sense to be explicit about what the option does

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807122

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
