### ISSUE TITLE
[Bug] Can't open a downloaded PDF from the new Downloads section

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15119]
## Steps to reproduce
- Download a PDF file (tried this twice, that's why there are 2 files in the screenshot)
- Open the new Downloads section in the browser and tap to open the file

### Expected behavior
- File opens

### Actual behavior
- Receive an error message (see screenshot) 

### Notes
 
- **The file can be successfully opened through Android default file manager. So it was not a case of a failed/corrupt download. When opening from the Android default file manager, the files can be opened successfully using the default file browser, adobe, google drive, and kindle.**

### Device information

* Android device: Pixel 4
* Fenix version: 81.1.0-beta.2 (Build #2015761659)

**This is what happens when I tap on a downloaded file** 
<img width="325" src="https://user-images.githubusercontent.com/42752644/93246484-de7be400-f75a-11ea-9e32-39ea1108dc8b.png">

**This is what happens when I choose Adobe to open the file with** 
<img width="325" src="https://user-images.githubusercontent.com/42752644/93246503-e5a2f200-f75a-11ea-87a0-3e1a7044ef4f.png">

**This is what happens when I choose Google drive to open the file with** 
![image](https://user-images.githubusercontent.com/42752644/93267380-9cae6600-f779-11ea-9c88-09467473b976.png)

**Comment by eliserichards** [comment]
@kglazko @Amejia481

**Comment by Amejia481** [comment]
@vesta0 it looks like the app that you are using for opening the PDF file doesn't support a file name that long. The message in the [second screenshot is from the app](https://user-images.githubusercontent.com/42752644/93246503-e5a2f200-f75a-11ea-87a0-3e1a7044ef4f.png). Can you open the file with another app?

**Comment by vesta0** [comment]
When I locate the file in the Android file browser (see the third screenshot) I can open it in the Adobe reader, Google drive, and even in my Kindle app. These are the same options that are presented by Fenix download manager but neither work when initiated from Fenix.

**Comment by Amejia481** [comment]
Maybe the Android file browser is shortening the file name 🤔 . Is this a public source(link) where we can test? If not could you please share the full name of the file?

**Comment by vesta0** [comment]
I just did a demo of the issue with @kglazko 

Full file name: agreement_to_receive_notices_electronically.pdf

When opening from the Android default file manager, the files can be opened successfully using the default file browser, adobe, google drive, and kindle.

It seems to be a permissions issue?

**Comment by kglazko** [comment]
Upon some investigation, I don't know if this has to do with the file name. I created a very, very long-named file seen here: [](https://drive.google.com/file/d/1eKFYmnuylBLht5C46ohLLIPCFNvDlhfi/view?usp=sharing) Downloading and opening the file worked with no issue. 

An interesting thing to note though is that in Vesta's screenshot, the file icon is a rectangle instead of a document as in my screenshot. That means even though the file is a PDF, it isn't getting categorized as one. Here is an example of the long-named file I used and it was able to open from the prompt seamlessly.
<img width="419" alt="Screen Shot 2020-09-15 at 2 40 56 PM" src="https://user-images.githubusercontent.com/1676235/93268398-f3a84100-f761-11ea-9fa7-4a7e5b7f5066.png">
<img width="430" alt="Screen Shot 2020-09-15 at 2 40 13 PM" src="https://user-images.githubusercontent.com/1676235/93268454-0d498880-f762-11ea-8500-388b9c8e0444.png">

**Comment by Willt125** [comment]
Seconding this from Daylight, except the file *is* recognized as a document; either the OS or the browser isn't recognizing itself as an option!

83.1.0 (Build #2015776401)
AC: 63.0.9, fc54c566e
GV: 83.0-20201112153044
AS: 63.0.0

Samsung Galaxy A11
Android 10


![20201216_151312](https://user-images.githubusercontent.com/8618797/102401971-1987f080-3fb2-11eb-8253-eb949934979f.jpg)
![20201216_151840](https://user-images.githubusercontent.com/8618797/102401974-1ab91d80-3fb2-11eb-8170-6c74eae7c59f.jpg)

**Comment by Amejia481** [comment]
Very likely to be fixed after https://github.com/mozilla-mobile/android-components/pull/9558 lands similar to https://github.com/mozilla-mobile/fenix/issues/17502

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 2/19 and Beta 86.0.0-beta.5 from 2/15 with Pixel 2 (Android 9).
I will close this issue and remove the qa:needed label.

**Comment by Amejia481** [comment]
Thanks @ebalazs-sv !
