### ISSUE TITLE
[Bug] Custom urls linked to an app will open automatically outside private mode in some websites despite "open links in app" setting being disabled.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15266]
## Steps to reproduce
(Make sure open links in app is disabled)
Open [imgur.com](imgur.com).
Press "Get app".
### Expected behavior
Ask me whether to open google play or not.
### Actual behavior
Open google play without asking me.
### Device information

* Android device: 10
* Fenix version: 80.1.3

PS: In this case I pressed the button because I want to open google play, but some rude websites will open custom url automatically although I don't want to. So I think firefox should at least ask me before opening the link. (Or the way firefox handle custom links should be improved.)

**Comment by test8421** [comment]
To make it more clear:
Some websites will automatically open a custom url (such as "something://something") which is linked to an app.
In private mode, firefox will give me a notification whether to leave the private mode to open in an app or stay in firefox, but in regular mode there's no notifications (even if I disabled the "open in apps" setting), therefore an app will automatically open, which is very very annoying to me.
I expect to have a setting to prevent all of these links from opening a linked app or just give me a notification whether to open an app every time.

**Comment by test8421** [comment]
It is surely a server-side problem, but I think firefox should be able to address it on a browser level.
And it is really a very common problem in some Chinese websites.
If it isn't addressed, I have to open every link in private mode, which is rather inconvenient.
So I'm looking forward to the devs' reply!

**Comment by test8421** [comment]
A more exact and clear example:
[https://baidu.com](https://baidu.com)
In the first situation, if I haven't installed the Baidu app, I don't want to get a notification if I can open in an app (in private mode).
![Screenshot_20201017-092841__01](https://user-images.githubusercontent.com/60219535/96325892-a23fea00-105e-11eb-97ea-f10bcdd0e4fb.jpg)
(If I press the "open" button, nothing happens. If I open it as a regular tab, there's no notification and nothing happens.)
It's no use to notify me to open a custom link in an app that isn't installed.
(PS: There's no notification for Firefox Focus neither, which means the problem is addressable.)

In the second situation, if I have an app installed, I want to have a setting which can control whether to notify me in the regular mode, similar to the one in private mode, in case a website would open automatically causing inconvenience.
Currently, firefox opens a custom link automatically in the regular mode, so there always won't be a notification.
