### ISSUE TITLE
Top site old

### ISSUE THREAD

**Issue by Leviafan83** [mozilla-mobile/fenix#15304]
make the top sites as in the old version
![Screenshot_20200921-152812](https://user-images.githubusercontent.com/71683096/93880465-3203aa00-fce6-11ea-92a2-d17107532587.png)

**Comment by yoasif** [comment]
It is not clear what you are looking for.

**Comment by LinAGKar** [comment]
Can't say exactly what OP meant, but in the previous, version, Firefox would show all your top sites directly on the new tab screen. In the new version however, it's limited to 2 rows of 4 items each, and to see the rest of the sites you need to scroll sideways (made harder by the fact that the scroll often doesn't register), and the majority of the new tab screen is just blank, if you don't use collections. Instead, it should show all the top sites without requiring you to scroll, like it used to.

Also, it now inserts random sites you've visited, like Fennec did, but there is an option for that, so whatever.

**Comment by gabrielluong** [comment]
Hi all, I am pretty certain this is related to limiting the number of top sites in the home screen and having the pager. I want to direct these concerns and hopes to this issue https://github.com/mozilla-mobile/fenix/issues/12065. There are designs and UX exploration for top sites to not be limited as evidence by:

<img width="2009" alt="homescreenmvp3" src="https://user-images.githubusercontent.com/1190888/93936249-dd672b80-fcf3-11ea-865d-f8e187ddc04a.png">

All of this will take some time to implement, but you can definitely expect the team are approaching the design, functionality and user experience of Fenix as openly as possible and tackling these challenges. 

I am closing this issue to redirect the conversation towards https://github.com/mozilla-mobile/fenix/issues/12065 because I believe in part that some part of the issue will be addressed there and that issue will be the best way forward to provide feedback.
