### ISSUE TITLE
[UX] Optimize the order and messages of onboarding cards

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15372]
## User Story
- As a NEW user, I want to quickly learn about the most interest or useful features, so I know if this browser is the right one for me and how to customize it to fit my needs. 

### Acceptance Criteria
- Onboarding cards appear in order of most interesting/useful.
- ONLY highlights unique/useful features that are also actionable
- Highlight what's unique about Firefox
- Copy is clear, precise, and impactful
- FxA sign in/sign up is not presented to me as the most important option

### UX Spec
- [Figma](https://www.figma.com/file/HvCGhaudYuBq3yPgwAWOVO/Onboarding?node-id=0%3A1)

**Comment by betsymi** [comment]
Here is the new order on onboarding cards

1. Theme picker
2. Address bar location picker
3. Enhanced Tracking Protection settings
4. Sync Firefox between devices
5. Privacy notice
6. Start browsing call to action 

Note, we are removing: See what's new and Private tabs cards.

Here are the string changes. 


Current String ❌ | New String ✅ | Notes ✍️
-- | -- | --
Welcome to %s | No change | l10n note: Substitute %s for long browser name.
Choose your theme | No change |  
Save some battery and your eyesight by enabling order | Save some battery and your eyesight with dark mode. |  
Get to know %s | REMOVE STRING | No string replacement; Remove
Light theme | No change |  
Dark theme | No change |  
Automatic Adapts to your device settings | No change |  
Take a position | Pick your toolbar placement |  
Try one-handed browsing with the bottom toolbar or move it to the top. | Put the toolbar within easy reach. Keep it on the bottom, or move it to the top. |  
Top |   | Swap order. Bottom should be first, since it is the default.
Bottom |   | Swap order. Bottom should be first, since it is the default.
Automatic privacy | Always On Privacy | Remove toggle
Privacy and security settings block trackers, malware, and companies that follow you. | Firefox automatically stops companies from secretly following you around the web. |  
Standard (default) | No change |  
Blocks fewer trackers. Pages will load normally. | Balanced for privacy and performance. Pages load normally. |  
Strict | No change |  
Blocks more trackers, ads, and popups. Pages load faster, but some functionality might not work. | Blocks more trackers so pages load faster, but some on-page functionally may break. |  
  | Sync Firefox between devices |  
Start syncing bookmarks, passwords, and even more with your Firefox account. | Bring bookmarks, history, and passwords to Firefox on this device. |  
Sign in to Firefox | Sign up |  
Your privacy | No change |  
We've designed %s to give you control over what you share online and what you share with us. | No change | l10n note: Substitute %s for long browser name.
Start browsing | No change |

**Comment by betsymi** [comment]
A visual update to the FxA card is coming, per #15373

**Comment by liuche** [comment]
@vesta0 will combine the tickets.

**Comment by eliserichards** [comment]
Current onboarding flow: 
https://user-images.githubusercontent.com/43795363/111184843-5d719e00-857f-11eb-99cd-252b5e666537.mp4

**Comment by Amejia481** [comment]
@betsymi I would like to confirm what **"l10n note: Substitute %s for long browser name."** means, would you mind helping met to understand what should be done here?  Or an example of **"long browser name."**
<img width="913" alt="image" src="https://user-images.githubusercontent.com/773158/111674613-936a8880-87f2-11eb-9ffd-0876e9313639.png">

**Comment by lobontiumira** [comment]
Verified that all the string changes were implemented, on the 3/26 Nightly build with Samsung Galaxy Note 8 (Android 9):

![light theme](https://user-images.githubusercontent.com/40694158/112641236-db208e00-8e4a-11eb-8424-953909c87935.png)

![dark theme](https://user-images.githubusercontent.com/40694158/112641250-df4cab80-8e4a-11eb-8a1e-b06917dbed29.png)

**Comment by Amejia481** [comment]
Thanks @lobontiumira !

**Comment by lobontiumira** [comment]
Verified that all the string changes were implemented on the Beta 89.0.0-beta.1 build with Samsung Galaxy Note 8 (Android 9).
