### ISSUE TITLE
[Bug] Our most visited sites are gone in the latest updates. We see you have added an option to show them again but it looks like it's starting from scratch. How can we restore the sites that were listed there? Thanks. 

### ISSUE THREAD

**Issue by Brendajjq** [mozilla-mobile/fenix#15384]
### Device information

* Android device: ?
* Fenix version: ?

**Comment by cadeyrn** [comment]
This is an issue tracker, not a support forum. You can get support for Firefox here:
https://support.mozilla.org/en-US/questions/firefox-preview

If you want to report a bug then please fill out all fields in the template (they are there for a reason!) and don't write everything in the issue title.

**Comment by Brendajjq** [comment]
No need to get nasty, cadryrn.

**Comment by Brendajjq** [comment]
😥

**Comment by clientenq** [comment]
Issue: Our most visited sites are gone in the latest updates. We see you have added an option to show them again but it looks like it's starting from scratch.

Expected behaviour: show collected top sites from previous (pre fenix builds) to user. As a user we expect Firefox developers to not break previous functionality users relied on for years of builds.

Solution:
Provide easy to use or automated function to restore the sites that were listed as top sites.
For future: do not remove functionality just because the developers like to start from scratch. Functionality should only be removed when proven not to be valuable to users. Access to user data should not be made inaccassible with an upgrade.

**Comment by Brendajjq** [comment]
Thank you for stating so articulately what I was trying to say. I appreciate it.
    On Thursday, September 24, 2020, 09:23:51 PM EDT, clientenq <notifications@github.com> wrote:  
 
 


Issue: Our most visited sites are gone in the latest updates. We see you have added an option to show them again but it looks like it's starting from scratch.

Expected behaviour: show collected top sites from previous (pre fenix builds) to user. As a user we expect Firefox developers to not break previous functionality users relied on for years of builds.

Solution:
Provide easy to use or automated function to restore the sites that were listed as top sites.
For future: do not remove functionality just because the developers like to start from scratch. Functionality should only be removed when proven not to be valuable to users. Access to user data should not be made inaccassible with an upgrade.

**Comment by liuche** [comment]
You can enable most visited sites by going to Settings > Customize > Show most visited sites.
