### ISSUE TITLE
FNX-5090 ⁃ Tab Counter looks cramped when I have 14 tabs open

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1541]
## Steps to reproduce
1. Open 14 tabs
1. Look at tab counter

### Expected behavior
The tab counter shouldn't look cramped, like in Fennec. 

### Actual behavior
Tab counter looks cramped. 

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1915 build id 11001743

![signal-attachment-2019-04-10-194207](https://user-images.githubusercontent.com/152493/55920972-cea4bb80-5bc8-11e9-86fe-6414d110e5cf.png)UNITO-UNDERSCORE!002!

Fennec:

![signal-attachment-2019-04-10-194207](https://user-images.githubusercontent.com/152493/55920981-d5333300-5bc8-11e9-97d2-505414c2af63.png)UNITO-UNDERSCORE!001!

**Comment by AmyYLee** [comment]
This should be vertically and horizontally centered to the square around it.

**Comment by ekager** [comment]
@AmyYLee because the square around the tab number is an off centered square inside of another square, it's difficult to "vertically and horizontally center" the numbers. I added a commit that adjusts the margin and text size dynamically depenending on if the number is single or double digits, and can make tiny adjustments with you to get it as perfect as possible. The other option, of course, would be to use a true square svg (like reference browser, Fenix, etc), and then the centering would be simple.

**Comment by AmyYLee** [comment]
> @AmyYLee because the square around the tab number is an off centered square inside of another square, it's difficult to "vertically and horizontally center" the numbers. I added a commit that adjusts the margin and text size dynamically depenending on if the number is single or double digits, and can make tiny adjustments with you to get it as perfect as possible. The other option, of course, would be to use a true square svg (like reference browser, Fenix, etc), and then the centering would be simple.

Yes I understand the challenge. If we run into future issues with this, we can revisit the design of the icon with Stephen. Thank you!

**Comment by sblatz** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/60468378-43a6f080-9c0e-11e9-9591-f4875b1fa0c6.png">

This is the current implementation. I think it looks much less "cramped" as it's centered now with @ekager's fix. I'm going to close this for now, and we can re-open if UX feels we should change it in the future!
