### ISSUE TITLE
Feature to increase/decrease text size (zoom) and remember it per domain (like desktop)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15445]
Like Safari on iOS:

![Safari-FontSize](https://user-images.githubusercontent.com/25581533/94321712-ee2bd180-ff7f-11ea-836a-5510c458d866.png)
[Refer Image](https://mcmw.abilitynet.org.uk/making-text-larger-safari-ios-13-iphone-ipad-and-ipod-touch)

### What is the user problem or growth opportunity you want to see solved?

Users may like their default text size in general, especially for well designed mobile sites. However, it is cumbersome to pinch to zoom into text to read it (requires constant panning) if the page has a text size that is smaller than most pages. Desktop browsers have already solved this by allowing users to zoom the entire page and have it reflow as normal. Firefox even remembers this per domain. 

This is good for accessibility, convenience, and working around non-optimal design without needing to set a global zoom value that applies to all sites and is cumbersome to get to within settings. 

### How do you know that this problem exists today? Why is this important?

I have experienced this problem. It is important because readability is important. Other browsers (Safari, as seen below) include it. 

### Who will benefit from it?

Any user who browses sites that are less than ideally built, that would like to revisit them without needing to modify a global zoom that make other pages' text too small, or their designs too cramped. 

_Originally posted by @black7375 in https://github.com/mozilla-mobile/fenix/issues/14923#issuecomment-699204407_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7498)

**Comment by HubKing** [comment]
I think that there are 3 types of zoom in web browsers. I do not know their official terms, so I will just name them arbitrarily for the sake of argument.

- Z1: The smooth zoom that increases everything in the exact same ratio and does not change the layout. After zooming in, it only shows a portion of the page, and you would have to pan to see other parts.
- Z2: The zoom that can be invoked by Ctrl+wheel/Ctrl+plus and changes the page layout so that the page still fits in the screen horizontally after zooming in.
- Z3: The zoom that increases only the font size. This was the only zoom in old web browsers like Internet Explorer 6.

On Android FireFox/Chrome, Z1 seems to be the only zoom that can be invoked without having a physical keyboard (I do not have a physical keyboard on my phone, so I am not sure if Ctrl+plus works or not, so I am just assuming it works). On desktop FireFox/Chrome, Z2 is the only zoom that can be invoked without having a touch screen or a touch pad. Android FireFox/Chrome have text size settings in the accessibility category, and I suspect that that is Z3. I have tried setting a big font size there, but that resulted in clipped-out texts, probably because the size of the HTML element did not get bigger but only the size of the font.

I do not have an iPhone now, so I am not sure what the OP wants is Z2 or Z3. But if it is Z2, I think this is needed two, and urgently, for the sake of accessibility. Unlike what the OP says "Users may like their default text size in general, especially for well designed mobile sites", I find that the font sizes of almost ALL mobile web sites are very small and difficult to use for me. I could pinch to zoom, but then I would have to keep panning left and right to read the text, which makes it impractical. So, I am currently relying on the reader mode, but you know, reader mode does not work well at all times. So, I think that Android FireFox should have a menu for Z2, just like the desktop FireFox.

The accessibility text size setting (Z3) that is currently available on Android is USELESS. As I mentioned above, If I increase the text size, text often overflows out of its element and gets clipped out (invisible), and I cannot adjust it per site (only one monolithic value for all sites that is not easy to change dynamically because I would have to navigate deep into the settings).

Please add Z2 to Android FireFox; I think this is more urgent than other niche features for a lot of people for accessibility reasons.

**Comment by black7375** [comment]
I know it's Z3 and it's for low vision.

**Comment by HubKing** [comment]
> I know it's Z3 and it's for low vision.

But Z3 makes text clipped out.
![Screenshot_20210324-171306](https://user-images.githubusercontent.com/10900489/112276866-86530b00-8cc4-11eb-8e76-743f7830caeb.png)

**Comment by black7375** [comment]
I think we should fix the layout breaking.
It's good to have the Z2 implementation as an option.

**Comment by willfs84** [comment]
This should be renamed to "webpage zoom" instead of "text zoom" because that's what this actually is. Only scaling/zooming text usually causes issues (layout etc.), we need webpage zoom just like all the desktop browsers have and Safari for iPhone and Chrome for Android too (it's still in development in Chrome for Android, you have to enable a flag). I often find myself just wanting to zoom a webpage because everything is a bit too small on it, it's not just about text.

And apparently the lack of page zoom might even be considered a violation of UAAG 1.0 Checkpoint 4.1 (according to comments in this bug https://bugs.chromium.org/p/chromium/issues/detail?id=779409 )

Since this is also an accessibility issue, can this please be bumped in priority?

**Comment by willfs84** [comment]
This was also discussed on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1540809

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807123

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by willfs84** [comment]
It was already on bugzilla, it was filed 4 years ago! 🤣 Literally 1 post above. Now someone has to set 1540809 and 1807123 as duplicates on bugzilla 😂 

> This was also discussed on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1540809
