### ISSUE TITLE
[Bug] Tab tray background animation starts from bottom of screen instead of the top of the Android navigation toolbar

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15469]
## Steps to reproduce

1. Tap tab tab switcher button in toolbar.

### Expected behavior

The tab tray animation starts from the top of the Android navigation toolbar. 

### Actual behavior

Tab tray animation starts from the bottom of the screen, causing the Android navigation toolbar to white-out briefly while it appears. On slower hardware, this looks sloppy. 

![recording-20200927-012919](https://user-images.githubusercontent.com/152493/94357113-f52c1000-0063-11eb-9dac-d3446e66d0fd.gif)

This does *not* happen on my Pixel 2, so it is likely specific to older versions of Android. 

### Device information

* Android device: Moto G XT1031
* Fenix version: latest nightly

**Comment by JohannVII** [comment]
Interesting; I was going to say this doesn't happen on my phone, but I realized it's only noticeable because the navigation bar isn't matching the app theme. I get a dark bar for FF dark theme and a light bar for FF light theme, irrespective of system setting, so I can't confirm. IIRC, I could manually set the nav bar color in the version of Android (Samsung flavor) that shipped with my phone, but it's contextual in the current version, so this is a function of the Android system version.

Does you Pixel 2 match the navigation bar color to the app theme?

**Comment by yoasif** [comment]
> Does you Pixel 2 match the navigation bar color to the app theme?

Yes, it does.
