### ISSUE TITLE
[Bug] swiping down on snackbars should dismiss them, not swiping them to the right 

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15479]
## Steps to reproduce
1. Open Fenix
2. Navigate to Mozilla.org
3. Open menu
4. Tap on bookmark
5. Swipe down on snackbar to dismiss

### Expected behavior
Snackbar would be dismissed

### Actual behavior
You need to swipe right to dismiss it

### Device information

* Android device: ?
* Fenix version: 
Nightly 200927 06:04 (Build #2015766323)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.0

I'm not exactly sure if this is a bug but it's certainly not a feature request.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7562)

**Comment by JohannVII** [comment]
This is a feature request IMO - the feature you're requesting is a different gesture for dismissing the notifications. The current behavior is intended as far as I can tell, possibly to mitigate confusion with the tab shade close gesture (swipe down at the bottom of the screen).

That aside, the title should also be changed because not all snackbar notifications can be dismissed in the first place. As far as I can tell, only addition notifications can be dismissed (I just confirmed that the add to top sites confirmation behaves the same way as the bookmark confirmation), while deletion notifications cannot be swiped away at all and persist until they time out (tested with deleting a bookmark and deleting a search engine; I assume this is to provide time to hit undo without accidental dismissal, though they still disappear quickly enough that if one isn't EXPECTING the notification, one may have difficulty reading and then clicking it before it's gone).

**Comment by Poopooracoocoo** [comment]
@JohannVII Have you used the snackbars in other apps? I made sure to check out the snackbars in Google Play and Google Keep before creating this issue ;)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807056

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
