### ISSUE TITLE
Configuring about:config parameters with USB debugging

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15493]
### What is the user problem or growth opportunity you want to see solved?
Although the about:config can’t be access, if you allow users to configure with USB debugging, you’ll still achieve greatness on Android.
### How do you know that this problem exists today? Why is this important?
I can’t access and configure the page after I updated to Firefox Daylight
### Who will benefit from it?
Any advanced users would be allowed to enable or disable experimental features to test, and help you better.

**Comment by cadeyrn** [comment]
If there are reasons to prevent that people use about:config in stable release builds then there is really no point in implementing a workaround for that because the same reasons still apply. I only see two realistic options:

1. Mozilla enables about:config in stable release builds (that's #7865). Then this proposal is obsolete.
2. Mozilla won't allow it. Then this proposal should be a WONTFIX.

**Comment by KrasnayaPloshchad** [comment]
So I have to seek the way to turn around, for example:
1. Root the device
2. Find the prefs at the data storage
3. Find the file that store the configuration
4. Modify it

**Comment by kbrosnan** [comment]
Closing as a duplicate
