### ISSUE TITLE
AuthException: Missing key info

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15501]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6336621/?referrer=github_plugin

```
AuthException: Missing key info
    at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:23)
    at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
...
(2 additional frame(s) were not displayed)

Missing key info
```

**Comment by grigoryk** [comment]
This is the new version of the old exception.

Sentry issue: [FIREFOX-NIGHTLY-7ZV](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9659200/?referrer=github_plugin)

**Comment by grigoryk** [comment]
Socorro link for this: https://crash-stats.mozilla.org/signature/?signature=java.lang.IllegalStateException%3A%20at%20mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache%28FxaAccountManager.kt%3A24%29&date=%3E%3D2020-10-02T16%3A49%3A00.000Z&date=%3C2020-10-09T16%3A49%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#graphs

**Comment by Amejia481** [comment]
We are still seeing reports[on newer versions](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9659200/events/)

**Comment by grigoryk** [comment]
Let's move the discussion to the corresponding A-C ticket: https://github.com/mozilla-mobile/android-components/issues/8527#issuecomment-958613507

**Comment by pocmo** [comment]
(This crash is one of our top crashes in Nightly currently)

**Comment by bendk** [comment]
The first step of my plan to address this one is to update the `samples-sync` app so that it can trigger this state.  However I haven't been able to figure out how everything is linked together.

  - I have rust code that will change the state internally to trigger the issue.  I believe that function should be available from the `PersistedFirefoxAccount` class
  - The `MainActivity` class in `samples-sync` has a `FxaAccountManager` instance.
  - @pocmo @grigoryk  How can I get access to `PersistedFirefoxAccount` from `FxaAccountManager`?

**Comment by mhammond** [comment]
> (This crash is one of our top crashes in Nightly currently)

I'm still trying to thread this together, but best I can tell, this particular exception isn't happening any more - there's exactly 1 event with "missing key info" on Nightly.

> Let's move the discussion to the corresponding A-C ticket: [mozilla-mobile/android-components#8527 (comment)](https://github.com/mozilla-mobile/android-components/issues/8527#issuecomment-958613507)

In that ticket, Grisha notes that due to a refactor, the exception is now "missing OAuthScopedKey" - but Nightly "only" has 2.4k events for 433 users - which is still important, but seems a long way from being one of the "top crashers" - it's not even one of the "top fxa crashers" - eg, "MissingExpectedAccountAfterStartup" has 130k events and a number of others are larger. @pocmo what am I missing here?

(and as Grisha requests, we should move to that a-c issue - I'm only asking about the crash rate here because I'm replying to a comment here :)

**Comment by pocmo** [comment]
> In that ticket, Grisha notes that due to a refactor, the exception is now "missing OAuthScopedKey" - but Nightly "only" has 2.4k events for 433 users - which is still important, but seems a long way from being one of the "top crashers" - it's not even one of the "top fxa crashers" - eg, "MissingExpectedAccountAfterStartup" has 130k events and a number of others are larger. @pocmo what am I missing here?

I came here via crash-stats, which listed this exception at rank 3 for Nightly 96.0a1:
https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=96.0a1

**Comment by kbrosnan** [comment]
Not seeing any recent crashes mentioning [OAuthScopedKey](https://crash-stats.mozilla.org/search/?java_stack_trace_raw=~OAuthScopedKey&product=Fenix&date=%3E%3D2022-02-02T21%3A14%3A00.000Z&date=%3C2022-02-09T21%3A14%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature). Everything seems to be 95 or earlier.
