### ISSUE TITLE
Intent sent with ACTION_VIEW to FF Android does not open url [Bug]

### ISSUE THREAD

**Issue by francescom** [mozilla-mobile/fenix#15513]
## Steps to reproduce

I wwill use the Termux Android App to send intents with the command line

1 open a termux terminal
2 type command to send intent:

am start --user 0 -a android.intent.action.VIEW -n org.mozilla.firefox/.App -d http://www.pangoo.it/coronavirus/

### Expected behavior

FireFox comes to.the foreground and opens given url

### Actual behavior

FireFox comes to.the foreground but does nothing

### Device information

* Android device: Huawei Mate 10 pro
* Fenix version: 
81.1.1 (Build #2015764547)
AC: 57.0.6, bdbd5ccfd
GV: 81.0-20200917005511
AS: 61.0.13

**Comment by s-ankur** [comment]
Related  #15423

**Comment by liuche** [comment]
@rocketsroger do you know if anything changed in fenix regarding intent handling? This seems like a problem, can you repro it?

**Comment by Kamuno** [comment]
@francescom This is probably not relevant for you anymore but for anyone else searching for the solution:

The problem is, that you are trying to send the data to the launcher activity instead of the activity that handles this intent normally.

Use: `org.mozilla.firefox/org.mozilla.fenix.IntentReceiverActivity` as the component and it will work. 👍
