### ISSUE TITLE
[Bug] Tab tray collapsed / expanded issues

### ISSUE THREAD

**Issue by Anutrix** [mozilla-mobile/fenix#15543]
# Issue 1 - scrolling in a collapsed tab tray will close it
## Steps to reproduce
1. Open 8-10 normal tabs.
2. Stay on 6th tab. (Or any last few tabs).
3. Now, click private browsing section. (have anything between 0 - 3 tabs opened as private)
4. Go back normal tabs section. Don't click any normal tabs yet.
5. Try scrolling to top of the normal tab list.

### Expected behavior
We should be able to scroll to the top tabs. For this the tab tray should be expanded.

### Actual behavior
Tab list closes as soon as we try to scroll to first tab.

&nbsp;
# Issue 2 - changing orientation landscape -> portrait will keep the tab tray expanded even with 0 tabs
## Steps to reproduce
1. Have less than 3 tabs (even none) in tab tray
2. Put the device in landscape if not already
3. Change the orientation to portrait.

### Expected behavior
Tab tray should be collapsed, not edging to the top of the screen since we have few tabs to show and otherwise there would be a lot of empty space.
This is the behavior seen when opening the tab tray for <=3 tabs while in portrait.

### Actual behavior
The tab tray is expanded, edging the top of the screen, occupying unneeded space.

### Device information

* Android device: 9
* Fenix version: 81.1,1(Build #2015764547)

**Comment by liuche** [comment]
@kbrosnan if you haven't found the dupe to this, I think we could still pass this off to @Mugurell and the team.

**Comment by kbrosnan** [comment]
Seems similar to #14980 and #13777 but not quite the same problem.

**Comment by Mugurell** [comment]
> Seems similar to #14980 and #13777 but not quite the same problem.

Yes, these are a different issue that I wanted to resolve.

**Comment by Mugurell** [comment]
It had come up in review that we don't have ux feedback for the following change that would fix the issues described here:
We were already setting the tab tray to occupy full height or half height of the screen.

The proposed solution would have the tab tray check whether to be shown as expanded or collapsed (full / half scrren) not just when it is first shown but also whenever the user changes from private to normal tabs & vice versa and when changing orientation.
The result would be:
![maybeFixedTabsTray](https://user-images.githubusercontent.com/11428869/95848412-af0ac800-0d56-11eb-8dce-d6a5882c323a.gif)
[video](https://drive.google.com/file/d/1z2KZcbLRwfSaGhk1lLbUKLDYI7mpCSbY/view?usp=sharing)

Asking UX if the above seems ok or what should the behavior be.

**Comment by topotropic** [comment]
@Mugurell would it be possible to keep the height consistent and use the mode with the most tabs as reference? So when it is fully expanded in normal mode, we keep it fully expanded even if there are less then 3 tabs in private mode.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201022 05:00 (Build #2015771115) GV 83.0a1 from 10/22 with Pixel 2 (Android 9).
Scenarios tested:
1. when there are more than 3 tabs is normal tabs tray and 3 or less tabs in private tabs tray, the Tabs tray will be expanded (full screen) and the tabs can be scrolled;
2. when there are more than 3 tabs is private tabs tray and 3 or less tabs in normal tabs tray, the Tabs tray will be expanded (full screen) and the tabs can be scrolled;
3. when there are less than 3 or less tabs in normal tabs tray and private tabs tray, the Tabs tray will be collapsed (half screen);
4. when Tabs tray is collapsed (half screen) in normal or private and the device is switched to landscape mode and back to portrait mode, the Tabs tray remains collapsed (half screen).
On Beta 83.0.0-beta.1 GV 83.0 from 10/21 this is partially fixed because scenario 4 is not fixed.

**Comment by Mugurell** [comment]
Thank you Eliza!
Just checked, this is not in beta yet - https://github.com/mozilla-mobile/fenix/compare/v82.1.0...v83.0.0-beta.1
so I think we can consider it as fixed for Nightly, pending upstream merges.

**Comment by Poopooracoocoo** [comment]
that change sounds like the tab tray will basically always be expanded now. doesn't that defeat the point of a tray/drawer: reachability? (<- should this be a colon, semicolon or comma?)

and i don't see my issue, #14204, mentioned here :/ I don't have private browsing in my repro steps.

**Comment by Mugurell** [comment]
> that change sounds like the tab tray will basically always be expanded now. doesn't that defeat the point of a tray/drawer: reachability? (<- should this be a colon, semicolon or comma?)
> 
> and i don't see my issue, #14204, mentioned here :/ I don't have private browsing in my repro steps.

I think the intent here is to have the tabs tray have a height best accommodating the list of opened tabs.
With just few tabs the tray is collapsed - small, after a certain threshold the tray is expanded.
This was the original behavior also, this ticket just comes to resolve some small quirks.

The situation described in #14204 seems to not be an issue, left a comment there.

**Comment by Poopooracoocoo** [comment]
I've gotta test out my issue on an older version. I ought to make a recording. Other people have run into the same issue that I did and agreed.

I understand your intent of changing it. You're making it fit the tabs. It used to be a fixed height though and was more reachable. The intent of the other behaviour was reachability. It's something that requires some input from UX or whatever because it might as well be a screen instead of a tray/sheet
