### ISSUE TITLE
Home Button on address bar, and scroll side bar for long web pages.

### ISSUE THREAD

**Issue by Throb1** [mozilla-mobile/fenix#15558]
### What is the user problem or growth opportunity you want to see solved?
There is no option to quickly go to home from the opened page. Currently we have to close that tab or open a new tab to go to home. Also when scrolling a long page no side bar option for accurate and fast scrolling also no button  to reach at the top of page directly.

### How do you know that this problem exists today? Why is this important?
By using Firefox android. It makes browsing more easier and efficient.

### Who will benefit from it?
All the users.

**Comment by gsterwadkar** [comment]
Good suggestion

**Comment by weijarz** [comment]
I suggest clicking on the address bar to bring up the navigation page (contains address bar input, top sites, bookmarks...)

**Comment by liuche** [comment]
Thanks for filing this issue! If you're using the bottom toolbar, you can double tap on the tab icon to go to the homescreen. You can also see some of the ideas that we're exploring in #12065. For now, I'm going to close this issue because this is intentionally designed this way.

For scrolling the urlbar, we have #11074 on file.
