### ISSUE TITLE
[Bug] It's not possible to change browser.display.use_documents_fonts in about:config

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15604]
## Steps to reproduce
Open Firefox Nightly and write about:config
Change string browser.display.use_documents_fonts from 1 to 0
Restart browser. Value is 1 again.
### Expected behavior
That value should be 0
### Actual behavior
The value doesn't change. It's a very common fingerprinting value. Some people could see interesting changing that value.
### Device information
Android device: 
* Android device: Lenovo P2 with LineageOS based on Android 10
* Fenix version: 201001 17:02

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1668841

**Comment by snorp** [comment]
This pref is managed by a [GeckoRuntimeSetting](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.Builder.html#webFontsEnabled-boolean-), which is why it gets reset. The value comes from the setting the app (Fenix) gives. If we want people to be able to control this, Fenix will need to expose it in the UI and put the appropriate value in the setting.

**Comment by jawz101** [comment]
After ad blocking, downloading web fonts is the largest file transfers to view web pages.  I'll have a few hundred kilobytes of fonts download for a textual webpage because the web designer wanted a particular font.
