### ISSUE TITLE
Optimize gesture settings

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#15629]
As a followup up to #10240 and #13442, based on UX feedback the `Gestures` settings group should be phased out.

https://github.com/mozilla-mobile/fenix/issues/13442#issuecomment-693027043:
> An update from UX on this from @mheubusch:
> 1. **Pull to refresh**: when it is ready it can go to release, NO setting to control it
Pull to refresh is a default for many Android browsers. Here, we are shipping something to catch up to their feature set. Because it’s shipped with so many browsers, we think that people would not only expect pull to refresh to be a default behaviour. We also think that they don’t want to turn it off. So we should ship this gesture to Release, and not create a setting for it.
>
> 2. **Dynamic/Pinned toolbar**: when this is ready it can go to Release, with a setting under "Toolbar" section
Hide address bar on scroll is a default for us and many other Android browsers. Some contributors wanted the address bar to always show, independent of scrolling. That’s fine. We can ship it on release, but we won’t make this persistent toolbar behaviour a default. It will be controllable under Toolbar Settings.
> 
> 3. **Swipe toolbar up for Tabs Tray** #11862: this feature should stay on Nightly, but we can include a setting
Other gestures control more advanced features. For example: swipe left/right on address bar to switch tabs. So far, we only received a signal that people want this feature through our contributors. But they’re not our general audience. So let’s hold off on shipping these other gestures, and keep them only in Nightly.
> 
> 4. **Swipe toolbar left/right to switch tabs**: TBD (since it is already in release)

**Comment by Mugurell** [comment]
I'm not quite sure about the timeline for this changes regarding release channels .
Should the changes be implemented right away and then depending on feature availability be uplifted to Release? 

Currently Release doesn't have the new `Gestures` settings group. I understand we should hold it off of Release.

**Comment by Mugurell** [comment]
Regarding
> 3. **Swipe toolbar up for Tabs Tray** #11862: this feature should stay on Nightly, but we can include a setting
Other gestures control more advanced features. For example: swipe left/right on address bar to switch tabs.

Can we get a mockup & strings?
@betsymi @mheubusch

**Comment by apbitner** [comment]
@betsymi Let me know if any mocks are needed, happy to help.

**Comment by betsymi** [comment]
For Nightly only, this can go under **Gestures** on the Customize screen and the string is: _Swipe toolbar up to view tabs_ 

Attached the screenshot of our current Customize screen for reference. 
![Screenshot_20201015-151126](https://user-images.githubusercontent.com/43555492/96181707-0b5a1d00-0efa-11eb-8f3f-e4fd9a013cc9.png)

**Comment by maxstarkenburg** [comment]
Please forgive that I'm not familiar enough with the mozilla-mobile ecosystem to know why, for example, this issue is open, #10240 is closed, and in any case, I still don't see a setting to pin my toolbar in my Android Firefox (apparently I'm on 81.1.4). Do I need to instead be using one of the non-stable Android FF apps to be able to enable this?? (I _hate_ the moving toolbar, and it's the reason that for the past couple of months I've made another browser my default (Brave, where it's also somewhat dynamic, but is less obnoxious about how quickly the disappearance/reappearance comes into effect after scrolling starts).)

I also feel a need to express my dismay at some of the quotes I'm reading in this issue's OP. Please remember that "other browsers do it, so we should do it to" is the exact opposite of why some of us have always loved and used Firefox. Please stop trying to be Chrome/Google. Please let users continue to customize/improve/extend and otherwise have some control over our browsing experience. Thanks.

**Comment by liuche** [comment]
Hi @maxstarkenburg, thanks for comment, we're working this bug, and you can see the code commits linked within this bug.

We land our changes on Nightly, but sometimes, in the case of #10240 we find that there are unexpected side effects, so additional work is needed.

The feature to prevent dynamic scrolling of the toolbar is a little complicated because of all the ways that the toolbar can be customized and also interact with the web content - rest assured, we're actively working on this and please be patient.

**Comment by B0pol** [comment]
Yeah I agree with @maxstarkenburg, it's not a valid reason

> Because it’s shipped with so many browsers, we think that people would not only expect pull to refresh to be a default behaviour. **We also think that they don’t want to turn it off.**

No, you are Firefox and your browsers are known to be customizable. And you still advertise Firefox for Android as customizable:

https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en_US&gl=US

This version of the Firefox web browser is dramatically redesigned to be faster, easy to use, **customizable** and private.

**Comment by andreicristianpetcu** [comment]
Pull to refresh always gets in the way of scrolling on all browsers. I'm forcing myself to use it until it gets removed but I constantly trgger a refresh by mistake.
I know Chrome users want it but it's going to be another round of bad reviews in Play store 😞

**Comment by B0pol** [comment]
Last time I argued about customisation, but I was a bit off-topic because your rationale is:

> We also think that they don’t want to turn it off.

Please have a look at this google support thread, when the preference to disable it was removed in Chrome 75

https://support.google.com/chrome/thread/8152831

This clearly shows you are wrong, there is 1771 upvotes and 223 comments to this date. And this is only the google support thread, not mentioning duplicate, other forums…

Some users even mentioned switching to Firefox because of this

> Thank you Google for giving me the push needed to move over to Mozilla.

https://support.google.com/chrome/thread/8152831?msgid=8911501

> […] Removing Chrome and using Firefox


https://support.google.com/chrome/thread/8152831?msgid=8982682

https://support.google.com/chrome/thread/8152831?msgid=9402830


You car read the full thread and find other examples.

Also, [Bromite](https://www.bromite.org), a popular chromium fork [added it back](https://github.com/bromite/bromite/blob/master/build/patches/Revert-flags-remove-disable-pull-to-refresh-effect.patch)
