### ISSUE TITLE
[Bug] Custom search providers deleted after upgrade to 81.1.12 Build 2015767043

### ISSUE THREAD

**Issue by lordgurke** [mozilla-mobile/fenix#15711]
## Steps to reproduce
* Configure custom search providers in Firefox
* Upgrade to Firefox 81.1.12 (Build 2015767043) via Google Play Store

### Expected behavior
* Custom search providers are retained

### Actual behavior
* The default search provider is kept, all other search providers are gone without any trace

### Device information
* Android device: HTC 10, Android 8
* Fenix version: 81.1.2, Build 2015767043.
Previous version unknwon.

**Comment by ysooqe** [comment]
They are not gone "without any trace". I do not see them anymore aswell, but when I try to add a custom search provider with the same name as one that I know I had added already, it says that I can't add it because a provider with the same name already exists.
Also, adding an entirely new custom provider does not work, as soon as you hit the confirm action when trying to add a new provider, it does not show up under search providers.

**Comment by sflorean** [comment]
@mcarare I made an update from Nightly 10/08 to Nightly 10/09 and the custom search engines Youtube and Reddit weren't displayed after the update.  The only engines still listed was CNN - set as default on Nightly 10/08.

Verified also #15741 and it is fixed on Nightly 10/09.

**Comment by mcarare** [comment]
@sflorean Those are not custom (not added by the user), do they appear on the list when you click on add search engine?

**Comment by sflorean** [comment]
@mcarare yes, they appear but an update should keep them on the main list if they were previously added. I will check again, on Monday 10/12, and file a new issue if the result is the same.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta 82.0.0-beta.6 (Build #2015769931) GV 82.0 and Release 82.1.0-rc.1 (Build #2015769955) GV 82.0 from 10/16 with Pixel 2 (Android 9), Xiaomi Mi Pad 2 (Android 5.1), OnePlus A3 (Android 6.0.1).
