### ISSUE TITLE
[Grid View] Update the thumbnail card size in the grid view

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#15777]
Update the card design so that the thumbnails are 1:1  and the bar with the title is 30dp high

**Comment by Mugurell** [comment]
@topotropic 
Currently the 1:1 ratio is not respected because
- we have a fixed item height: 186dp. If we enforce the 1:1 ratio we'll have a fixed item width
- we have a fixed item spacing - 16dp

So with a fixed item width and fixed spacing we'll have a fix width for the layout/
Which might be an issue on different devices with different screen sizes and display densities.
That's why we currently only respect the item height and the spacing constraints while the width of the item is dynamic, being a little bit smaller / bigger depending on the available screen width.

If the current UI looks off I think we'll need another priority for the height / width / spacing values as all 3 cannot be respected at the same time.

**Comment by topotropic** [comment]
Thanks for the explanation, sounds like a meaningful trade off to make here.
