### ISSUE TITLE
Add-ons UI Improvements

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#15791]
Made an entire list of things other users made to improve the add-ons UI

- #15661 
- #15659
- #15658 
- #15657 
- #15656 
- #15655 
- #15492

**Comment by cadeyrn** [comment]
I am not sure if it's really useful to have this issue since it's only a link list without any new information and incomplete anyway. I didn't search for issues related to the add-ons UI but I know at least that my issues are missing:

#9711
#10002

I am sure much more issues are missing since your list only contains issues from the last few days.

**Comment by csadilek** [comment]
Yes, let's close this. We use labels to categorize tickets. All the linked issues already have the Feature:WebExtensions label. Thanks!
