### ISSUE TITLE
Back on a new tab (from existing tab) should go back to existing tab, not close the app

### ISSUE THREAD

**Issue by LinAGKar** [mozilla-mobile/fenix#15792]
Currently, if you open the new tab page, and you then press the back button to close the keyboard, and then press the back button again, it will close the app. It would better if the back button took you back to the tab you were on.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8013)

**Comment by ale82to** [comment]
totally agree is so annoying

**Comment by Poopooracoocoo** [comment]
This is also suggesting that new tabs be new tabs, just as they are on Firefox for desktop, instead of new tabs being sort of like a homescreen, separate to the tab switcher. This is still a holdover from when Mozilla was experimenting with Fenix's UI. At the moment it's incredibly confusing as the "add" button is actually a home button.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814182

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
