### ISSUE TITLE
Consider making grid view the default for new installs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15831]
### What is the user problem or growth opportunity you want to see solved?
After all the kinks and perf issues are solved, I think the grid view should be made the default for new installs. It feels much more compact and familiar, and mostly conveys the same info. Of course users would be free to chose list view if they want
### How do you know that this problem exists today? Why is this important?
It is important because users coming from chrome/other browsers would find it more familiar than list view. From a usability perspective it feels better as well. 
### Who will benefit from it?
New users of firefox

**Comment by cadeyrn** [comment]
I couldn't disagree more. It shows less tabs and has much less space for tab titles and shows no URLs at all. It is definitely **not true** that it is more compact, it is definitely **not true** that it conveys the same info and it is definitely **not true** that "users coming from chrome/other browsers would find it more familiar" because the tabs layout of Chrome is a totally different one than both layouts of Firefox.

It's great that there is an option for users who like the grid view but I see zero reasons why it should be the default.

**Comment by jawz101** [comment]
There are almost 2700 issues open right now.  Why does commentary stay open?

**Comment by Matth7878** [comment]
As much as I would prefer to use grid view I won't. Right now you can only see 6 tabs in grid vs 8 from list.

**Comment by s-ankur** [comment]
I see, closing as unnecessary
