### ISSUE TITLE
Select All Tabs into a Collection

### ISSUE THREAD

**Issue by pidus** [mozilla-mobile/fenix#15865]
### What is the user problem or growth opportunity you want to see solved?
Let's say an user opens many (~50) tabs. Then they wants to save all of them in a collection. To achieve this, they would need to manually select all 50 tabs. 
I want to see a select all button. 

### How do you know that this problem exists today? Why is this important?
There is no select all tabs method to put all tabs in a collection. 

### Who will benefit from it?
Anyone who uses lots of tabs and uses the collection feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8119)

**Comment by nyanpasu64** [comment]
I recall that "select all tabs" used to be possible, either when selecting tabs in the tab list, or when selecting tabs after beginning to create a collection. But the feature was removed at one point, probably before this bug was filed. I don't know how to bisect old Fenix versions, and I don't know if it will be reinstated or not.

**Comment by eliserichards** [comment]
<img width="323" src="https://user-images.githubusercontent.com/43795363/114077830-d35ee180-986d-11eb-8f36-f0a5d8ca1e4e.png">

Looks like we have **share** all tabs, but not **select** for all tabs.

**Comment by boek** [comment]
Dup of #18797
