### ISSUE TITLE
FNX-5119 ⁃ Behaviour when adding a duplicate bookmark

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#1586]
As a user, I want to see the bookmark edit snackbar if I add a duplicate bookmark, so I can delete it, rename it, or move it to a different location. @topotropic please confirm that I have captured the UX feedback correctly. 

### Acceptance Criteria:
-I see the edit bookmark snackbar when I add a duplicate bookmark

**Comment by colintheshots** [comment]
Good question.

**Comment by topotropic** [comment]
I can see cases where bookmarking the same site multiple times is ok, for example when people organize content into folders and want the same site in different folders. It's a problem when people are not aware that the site has been bookmarked already though. 
This is related https://github.com/mozilla-mobile/fenix/issues/1601 – I think @AmyYLee is going to look into it.

**Comment by AmyYLee** [comment]
@topotropic I added a spec for bookmarked and non-bookmarked states in bug #1601.

**Comment by vesta0** [comment]
@ekager @AmyYLee  in a scenario when user can see that a page has already been bookmarked (#1601) will they still be able to re-bookmark it if they choose to?

**Comment by AmyYLee** [comment]
@vesta0 We currently don't offer the ability to have duplicate bookmarks in Fennec. I'm not sure how common the use case would be that the user wants to have multiple instances of a bookmark. Now that we have collections as another ability to save tabs I don't think it's needed but I'll let @topotropic make the final call since she worked on the bookmark flow.

**Comment by vesta0** [comment]
@AmyYLee that is not what I was asking. I was asking for clarification on the user flow. I saw that you provided specs for bookmarked and non-bookmarked states in #1601. My question is: what happens if a user navigates to a page that's already been bookmarked, sees the bookmarked state of the icon, and still decides to tap on it? Does the bookmark get removed (1), does a second bookmark get added regardless (2), does the user receive a notification indicating that they have already bookmarked that page (3), or does nothing happen (4)?

**Comment by topotropic** [comment]
@vesta0 we show the bookmark edit view where they can delete the bookmark, rename it or move it to a different location.

**Comment by yoasif** [comment]
@topotropic Elegant solution, and pretty much what happens in Firefox desktop! :smile:

**Comment by vesta0** [comment]
Thanks @topotropic I will create a user story for it.

**Comment by sv-ohorvath** [comment]
Verified that now we can't add duplicate bookmarks, just edit the existing ones. Remaining known issue: #2068.
