### ISSUE TITLE
Remove the search widget discoverability experiment from Nightly

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15929]
We were running an experiment in nightly to display an in-product prompt to help users learn about the Search Widget and install it. The experiment ended back in July but we haven't removed the experiment from Nightly.

**Comment by liuche** [comment]
related PR: #11614 (though there were probably other parts of this) and original issue #9488.

**Comment by mcarare** [comment]
@liuche Does this mean removing the entire CFR? Or should we just adjust the booleans in order to never show it?
The answer is also relevant to this: https://github.com/mozilla-mobile/fenix/issues/12901 if it should be fixed or it does not make sense to do it. Thank you!

**Comment by liuche** [comment]
Thanks for linking that issue! We should remove this specific CFR (and strings) so that it doesn't show anymore. We also should remove any place where this is querying Experimenter to determine what branch to be in, because that experiment is being sent in telemetry (and we've finished with it).

I haven't looked at the code but if it's a new CFR type, we probably want to keep the CFR type/class so that we could show a similar tip to this. However, if it's hard-coded but this full-screen CFR is simple enough, might be worthwhile to remove it.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201103 05:01 (Build #2015773417) GV 84 from 11/3 with

- Motorola Moto G6 (Android 8);
- Pixel 2 (Android 9);
- Samsung Galaxy Tab S3 (Android 8).

I will remove the qa:needed label and close this issue.
