### ISSUE TITLE
[Grid View] Make sure the close button has the right margins

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15962]
We want to make sure the close button has the right margin and aligns with the designs.

**Comment by Mugurell** [comment]
As per the specs here https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=168%3A713 the close button should be `10dp x 10dp` in size with `11dp` margins (actually also 10dp because it should be in the center of a 30 dp height parent).

Currently we are using for it [`mozac_ic_close`](https://github.com/mozilla-mobile/android-components/blob/master/components/ui/icons/src/main/res/drawable/mozac_ic_close.xml) which is a svg with a `24dp x 24dp` set height and also contains some padding
(the drawn out **X** is around 12dp in size with around 6dp all around padding).

@topotropic If we are to fully follow the specs (10dp x 10dp size with 10dp all around margin) we'll need a new resource for the close button (preferably with no padding so we can set the needed one in code)
But maybe the current design looks good?
<img src="https://user-images.githubusercontent.com/11428869/98274909-ae9fce80-1f9c-11eb-9258-3666837ca5a5.png" width="50%">

**Comment by topotropic** [comment]
We should definitely re-use existing components. I'll close this issue. Thanks!
