### ISSUE TITLE
Remove GS(Google Service)from Fenix

### ISSUE THREAD

**Issue by minutesinch** [mozilla-mobile/fenix#16006]
### What is the user problem or growth opportunity you want to see solved?
Google Service Bring Good Features but it has problems for Users, One and Big One is Privacy Compromising and Others are huge app size.
### How do you know that this problem exists today? Why is this important?
when i try update google service fenix restart
### Who will benefit from it?
every one, special how want more and more Privacy also avoid google to log history and etc

**Comment by cadeyrn** [comment]
>  also avoid google to log history and etc

Mozilla is not sending your browsing history to third parties…

**Comment by minutesinch** [comment]
mozilla not send history but google service send

**Comment by KrasnayaPloshchad** [comment]
Is there any code or feature relying on that?

**Comment by grravity** [comment]
Classyshark is showing multiple built in trackers, I +1 heavily that these should and need to be removed.

Adjust
Google AdMob
LeanPlum

*Adjust
5com.adjust.sdk.

*Google AdMob
2com.google.android.gms.ads.

*LeanPlum
1com.leanplum.


file:///data/app/org.mozilla.fennec_fdroid-0mV5JQsbxytxKHdXEf_8dA%3D%3D/base.apk

**Comment by cadeyrn** [comment]
@grravity This issue is about something from Google, not about Adjust or Leanplum. Please read this comment why these libraries are needed / how they are used:

https://github.com/mozilla-mobile/fenix/issues/12809#issuecomment-662199501

**Comment by grravity** [comment]
I have read that, also the issue of this issue was not entirely clear.
However conversation in that issue is closed, so it was not possible to express concerns there.

>Adjust is used to coordinate marketing campaigns and to evaluate the cost of running such campaigns.

This is not an excuse for using Adjust as a service in my opinion. More specifically, the F-Droid build should not have Adjust.

>As far as I know Admob is not directly used by Fenix. It may be pulled in as part of the Adjust SDK where I see a mention of Admob in their source code and/or Google Firebase.

Again, if this is true this is not an excuse for it in my opinion. At the very least it should not be in the F-Droid build.

>Firebase is used for Google Cloud Messaging. The only way to reliably receive push notifications on Android. 

I know there have been many foss applications that do not utilize Firebase and have achieved notifications to almost full reliability, however I understand not perfect and at the cost of some battery life generally.
However, this again in my opinion is not an excuse for having Firebase in the F-Droid variant.

>Leanplum is used to show contextual recommendations while using Fenix. 

This only applies to users who choose to use these features, however there is no easy way for users who do not wish to utilize these features to truly opt out in a way that any of these services are actually removed which is my major concern. At the very least, having two F-Droid builds, one stripped of all these components at the possible expense of some notification unreliability and battery usage is perfectly reasonable for users who do not wish to use these services. This has been a very frustrating thing, and it is simple to understand that these services do not help out privacy in any way. If there was a true care about privacy, these services would not be present. However that is clearly not the case, we really need a build that is stripped of this bs. 

Anyways I understand this isn't the exact issue for this, however again that issue was closed. I'll refrain from conversing about this issue here if need be.

**Comment by cadeyrn** [comment]
Again: This issue is not about Adjust and Leanplum. I don't understand why you "hijack" this issue. It's also not the right place to discuss the F-Droid builds. Please follow the already linked issue #12809 for "Support a build variant that limits or turns off tracking".

**Comment by minutesinch** [comment]
like @grravity say its drain battery too

**Comment by liuche** [comment]
There's nothing we can do about google tracking you if you search using google.com. This is not the place to file F-Droid issues.
