### ISSUE TITLE
[Bug] "Click" is used in mobile strings

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#16033]
We've found a few instances where the word "click" appears in Fenix strings: https://transvision.mozfr.org/?recherche=click&repo=android_l10n&sourcelocale=en-US&locale=fr&search_type=strings

Seems like another word should be used since this is for mobile? "Press" maybe?

**Comment by kbrosnan** [comment]
1. `Click the @ icon when you’re on a page to add it to your bookmarks.`  is a Fx Reality string. It does not show up in Fenix
2. `Debug menu: %1$d click(s) left to enable` is a Fenix string. It can be encountered by opening the Settings > About Firefox > tap on the logo > string will show up as a toast at the bottom of the screen
3. `Click for more details` I think this is screen reader text when tracking protection shield is hovered over
4. `Some ads track site visits, even if you don’t click the ads` is a Firefox TV string. It does not show up in Fenix.

@betsymi what is our preferred string for activating a link or button? Touch? Tap? Something else?

**Comment by betsymi** [comment]
Broadly speaking, we prefer to use the verb `Select` or `Choose` on both desktop and mobile, as it is device agnostic and speaks to users’ cognitive processes instead of their tactile ones.

We may make different decisions on a case-by-case basis on individual strings, depending on the context of that string and where it appears. On desktop, we may use the term "right-click," whereas on mobile "touch and hold" would be more appropriate. In these specific strings, I would have to spend some time with the context to make the appropriate decisions.
