### ISSUE TITLE
Are shourcut icons adaptive?

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#16038]
It doesn't look like adaptive:
![image](https://user-images.githubusercontent.com/14617699/96518580-df30fa00-1273-11eb-8dc9-986185dc31d2.png)

Known apps with adaptive shortcut icons:
[Element](https://github.com/vector-im/element-android), [Orgzly](https://github.com/orgzly/orgzly-android), [Calendar](https://github.com/LineageOS/android_packages_apps_Etar), [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger), SoundCloud
![image](https://user-images.githubusercontent.com/14617699/96517260-4ef1b580-1271-11eb-8723-448ca6413dc2.png)

All of these shortcuts are created the same way, via long press from the main icon and dragging it to the desktop.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8348)

**Comment by cadeyrn** [comment]
I don't see a difference: It has the same shape, it has a solid background color (white like the "30" icon) with a icon in the middle, there is a small overlayed shape with the app icon. Maybe you could explain why the Firefox shourtcut doesn't look adaptive to you but all other icons do? Thanks.

**Comment by 532910** [comment]
1. An icon too small.
2. Usually adaptive icons are inverted.

Should not they look something like this:
![image](https://user-images.githubusercontent.com/14617699/96569884-5bf2c100-12d2-11eb-983c-8fd712c3de09.png)

**Comment by cadeyrn** [comment]
Why is the icon too small? The magnifier and the plus icon in your examples are not larger than the mask icon of Firefox. The lock icon is maybe a bit larger but not a lot. Your proposal looks wrong because there is no spacing at all around the icon. From your examples the Element icon is the only one that has no spacing around the icon but this doesn't work with the mask icon of Firefox. By the way: The example in Google's documentation about adaptive icons _shows_ spacing around the icon.

I am not sure what you mean by "inverted" because it's not clear to me why purple/white should be correct and white/purple should not be correct. How do you define the expected colors? Even if the colors could be swapped I doubt that this makes the difference between adaptive or non adaptive.

**Comment by Poopooracoocoo** [comment]
Google's own icons for shortcuts have a black or coloured icon on a white background. 

And reading through https://developer.android.com/guide/topics/ui/shortcuts and https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive leads me to believe that Fenix already uses adaptive icons but have set the background to white, to answer the question in your title.

**Comment by 532910** [comment]
OK, they are adptive, but shouldn't they be updated?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807102

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
