### ISSUE TITLE
Enable pull to refresh in Nightly and Debug builds

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#16054]
With all the big issues from https://github.com/mozilla-mobile/fenix/issues/9766 being solved pull to refresh should be enabled again in Nightly.

### What is the user problem or growth opportunity you want to see solved?
An easier, more enjoyable UX.

### How do you know that this problem exists today? Why is this important?
User requested feature usually found in many Android apps.

### Who will benefit from it?
All users.
We tentatively added a setting to enable/disable this feature but as per https://github.com/mozilla-mobile/fenix/issues/15629 it should not be used.

**Comment by liuche** [comment]
We discussed this and there is still one outstanding issue on Google Maps (see meta #9766, and #16055) but this should be good try again on Nightly!

**Comment by abodea** [comment]
**Verified** as fixed on the latest **Nightly build 10/21** with **Google Pixel 4 XL (11), Samsung Galaxy S7 (7), Google Pixel 4 (10), Nexus 9 (7), Huawei P20 (9), OnePlus A3 (6.0.1).**

Please note that many websites were checked and here are few examples: **bing.com/covidtwitter.com, uBlock settings page, phonearena.com, pinterest.com, ifehacker.com.**

Note that this is working as expecting but because of the large number of websites there can still be issues and we will keep testing/investigating this but we will add all the information to the **[Meta bug.
](https://github.com/mozilla-mobile/fenix/issues/9766)** 
As mentioned above there are still issues that are present in the **[Meta bug](https://github.com/mozilla-mobile/fenix/issues/9766)** and the **[Google Issue.](https://github.com/mozilla-mobile/fenix/issues/16055)**
