### ISSUE TITLE
[UX] Should starting point on cold start be behind a pref?

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#16061]
Pulling out of https://github.com/mozilla-mobile/fenix/issues/12062

"I can choose where my starting point is when re-launching the browser."

**Comment by liuche** [comment]
We need strings for this pref, and also knowing where this radio button should be.

@topotropic will add the strings and mocks.

Once we add this we'll also remove the Nightly feature flag.

**Comment by apbitner** [comment]
@ekager to provide input on technical feasibility re: Nicole's email on the topic. Could you also provide the technical definition of a "cold start"?

**Comment by ekager** [comment]
We decided to ship this feature to Beta without adding a pref and we can come back to this later if needed.

**Comment by michrogit** [comment]
Hi all, I don't know if this is the right place for my message. If not, please, forgive me ;-)
On the Italian support forum (Mozilla Italia) several users asked us how to choose the starting point when re-launching the browser because they would like to start with a new tab (Home) instead of the last tab of the previous session. 
As always happens in these cases, other users like the new beaviour (last tab on start)... I think that the possibility to choose the starting point is a "must" (a radio button or a toggle in Settings) so users can set their default start screen. 
I don't know if and how could be realized, but maybe the users could find the option in Settings > Customize > Home section. A toggle or two radio buttons "Open/Show last tab on start"  and "Open/Show a new tab on start".

**Comment by jawz101** [comment]
I think it would be the same thing as the Fennec Advanced option to close open tabs on browser restart

I have a little UI suggestion on this issue
https://github.com/mozilla-mobile/fenix/issues/5865

specifically https://github.com/mozilla-mobile/fenix/issues/5865#issuecomment-760533345

It would just be to check the tabs tabs to clean on cold start (or kinda like whatever Firefox Focus does to wipe on exit)

**Comment by bifleming** [comment]
@ekager @lime124 I believe Vesta wanted a pref on this, so is there still an open question?
