### ISSUE TITLE
[Pull To Refresh][Bug] Pull to refresh doesn't work properly on pinterest.com

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16089]
## Prerequisites
Have a fresh install or a clean profile

## Steps to reproduce
1. Navigate to pinterest.com
2. Use the pull to refresh gesture 
3. Close the tab 
4. Navigate again to pinterest.com
5. Swipe down and up 
6. Use the pull to refresh gesture 

### Expected behavior
Pull to refresh work each time

### Actual behavior
Step 2 The Pull to refresh icon remains stuck on the screen. 
Step 6 Pull to refresh doesn't work at all.

### Device information

* Android device: 
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly 201021
 
### Notes
✔️ Works on Chrome
Related to #16054 and #9766  

► Video
![20201021-162247](https://user-images.githubusercontent.com/51314259/96726265-73a57480-13ba-11eb-9f03-0de830f186df.gif)

**Comment by liuche** [comment]
Linking to #9766

**Comment by Mugurell** [comment]
I see here more separate issues:
- For `Step 2 The Pull to refresh icon remains stuck on the screen.`
Before the site is fully loaded / we receive a response from GV about how the touch was handled 
based on the default `INPUT_RESULT_UNHANDLED` the pull to refresh throbber will appear.
This is different than what happens for the dynamic toolbar that is not animated for this case.
- For `Step 6 Pull to refresh doesn't work at all.`
After the page is loaded GV returns `INPUT_RESULT_HANDLED_CONTENT` for how the touch is handled.
This results in not animating the dynamic toolbar / pull to refresh throbber.
A behavior different than on Chrome which shows the refresh spinner but also doesn't animate the toolbar.
- Scrolling at the bottom of the page gets first a few `INPUT_RESULT_HANDLED` returns from GV followed by `INPUT_RESULT_UNHANDLED` based on which we animate the pull to refresh throbber.
Like above, not showing the refresh throbber for `INPUT_RESULT_UNHANDLED` would fix this.
- An interesting issue also happening when scrolling at the bottom of the page:
A continuous scroll up -> scroll down event will not actually scroll the page. GV returns `INPUT_RESULT_HANDLED`.
[video](https://drive.google.com/file/d/1VRCYiB1ZYXa-xFssUa0fUfSD_z3-7TYF/view?usp=sharing)
Since this is happening also on Chrome(which also shows a overscroll shadows, the bottom one not aligned to the bottom) maybe it's a webcompat issue.

Not showing the pull to refresh throbber for `INPUT_RESULT_UNHANDLED` is probably something we want to address on Fenix/AC.

Asking @hiikezoe if
- not showing pull to refresh is the expected behavior
- the scroll issue at the bottom of the page is a webcompat issue
or something we should fix.

**Comment by hiikezoe** [comment]
In the pinterest case the root element is not scrolled basically, there is a child element which is able to scroll.

So, using `INPUT_RESULT_UNHANDLED` to trigger pull-to-refresh looks clearly wrong to me. It's returns in the case touch-action:none, that the browser should do nothing.

Anyway, as far as I can tell, in the pinterest case, a nested scrollable element case, we need https://bugzilla.mozilla.org/show_bug.cgi?id=1678505

As for the scroll issue at the bottom, I don't quite understand it. `INPUT_RESULT_HANDLED` is the expected result since https://bugzilla.mozilla.org/show_bug.cgi?id=1663000.  The root element height is 100vh, which is bit taller than the visibile area's height (i.e. not including the dynamic toolbar height), thus when the child scrollable element reaches at the bottom of the scroller, GeckoView needs to return `INPUT_RESULT_HANDLED` (rather than `INPUT_RESULT_HANDLED_CONTENT`) to move the dynamic toolbar.

**Comment by Mugurell** [comment]
Thank you!
Than maybe we can keep this as sort of a meta for all the issues talked about issues. Since we have a website on which the fixes can easily be tested?
I'll open a new ticket to ensure pull to refresh is not triggered for `INPUT_RESULT_UNHANDLED`.

Regarding scrolling at the bottom, I agree `INPUT_RESULT_HANDLED` is expected.
The issue there is that the user is trapped in that bottom section of the page 
(if doing a continuous gesture. If a new gesture starts scrolling works).
The page is not panned although the user is doing a scroll gesture.
Giving that this is not always happening makes me think it's an issue with the browser but because this is also happening on Chrome maybe it's an issue with the webpage.
Showing this issue on GVE - [video](https://drive.google.com/file/d/1fQpUEdr2DyDzW_m08JOkZco6WvkJNMRr/view?usp=sharing)

**Comment by Mugurell** [comment]
This is still an issue.
