### ISSUE TITLE
Create a custom add-ons collection for Mozilla Online

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#16093]
The Mozilla Online team has indicated they would like to ship their Fenix build (separate build variant) with a curated list of add-ons (web extensions) specifically for the China region.

Looping in @jvillalobos and @kewisch to ask for help on how to proceed. Product owner from Mozilla Online is @bli-mozbj - if GitHub is not the correct way to coordinate this then we can also create a doc or bugzilla bug.

**Comment by jvillalobos** [comment]
The long term plan is to move away from collections. We should set up a meeting with @atsay to discuss their requirements.

**Comment by muffinresearch** [comment]
Speaking to @diox (Tech lead on AMO) about this, the API result for a collection and the search results should nearly identical by design (There are very minimal differences e.g. avatar of author not available in a search). 

Assuming Fenix moves to using search result and there needs to be a curated collection for Mozilla Online, as long as Mozilla Online can control the URL for their data this may be a possible way address the need for customized data. The only other issue that might come up is if the difference in content would require different labeling in the UI.

**Comment by rxumoz** [comment]
We raised up a new proposal about add-ons instead of creating a different add-on collection, see #17522
