### ISSUE TITLE
[Bug] "Font size" option is aligned to the left on tablets

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#16128]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to Settings-Accessibility;
2. Disable "Automatic font sizing'';
3. Check Font size alignment to the left. 

### Expected behavior
All options are aligned without visual issues.

### Actual behavior
"Font size" is aligned to the left. 

### Device information
* Android device: tablets
* Fenix version: Nightly 10/22, Beta 83.0.0-beta.1.
 
<img src=https://user-images.githubusercontent.com/58466444/96909049-256d9f80-14a6-11eb-8f45-741aa09842bb.png width="300" height="550" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8456)

**Comment by mcarare** [comment]
This is due to the fact that we have many margins or padding values that are hardcoded to fit default OS margins and/ or padding. Whereas in values-sw600dp some of the values are different than the ones for mobile devices.

This issue is present in almost all settings screen, where items do not align to non-custom preferences or even with the action bar and will require a refactoring of preference custom layouts to not use hardcoded values for padding and margins.

**Comment by sflorean** [comment]
This is still reproducible on latest Fenix builds.
