### ISSUE TITLE
Add an option for select a preferred encoding for webpages

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#16121]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Prior to Fenix, Firefox for Android provided an option to set preferred encoding for webpages, although it was hidden by default, and users are able to enable it in the Settings. But since Firefox Daylight is released, this feature is disappeared. However there are still have some websites have neither specific locale language nor content encoding on their webpages and HTTP headers.
### How do you know that this problem exists today? Why is this important?
Without this feature, some websites are unable to display correctly with specified encoding, and display as mojibake.
### Who will benefit from it?
Anyone who encountered such pages on Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8451)

**Comment by KrasnayaPloshchad** [comment]
For me, this page got affected:
https://www.fotw.info/flags/vn-49%5E.html

**Comment by KrasnayaPloshchad** [comment]
Let’s see what happened to me.
![Screenshot_20201226-162415](https://user-images.githubusercontent.com/10364351/103148079-ec4bf700-4796-11eb-8bd7-ac6b3ebe6803.png)

**Comment by Multipanda** [comment]
Yes, it's one of two essential features that made me stop using Firefox on my android tablet. The other being a tab bar. 
Using Kiwi now, but still looking for an alternative with the encoding options, or an extension that works in Kiwi. 
Right now I'm forced to just read such pages on my PC.

**Comment by KrasnayaPloshchad** [comment]
This page also becomes mojibake to me due to this bug:
https://fineartamerica.com/featured/fly-dc-jets-heidi-smith.html

**Comment by Multipanda** [comment]
I actually found a working extension. It's a Chrome extension called Charset by jinliming2 that gives you the option of selecting another encoding.
Works fine with Kiwi also. So just install any chrome based browser on android instead of Firefox, and get that extension.

**Comment by hsivonen** [comment]
> https://www.fotw.info/flags/vn-49%5E.html

This page would actually be fixable via the menu in desktop Firefox.

> https://fineartamerica.com/featured/fly-dc-jets-heidi-smith.html

In this case, the data loss has happened on the server side and is not recoverable on the browser side.

**Comment by Multipanda** [comment]
Any browser with a charset selector would fix the mojibake, doesn't help that desktop Firefox has the option when the android version doesn't anymore.
So the OP will need to use another browser like I suggested, maybe the fenix devs will re-add it at some point, but don't expect it to be anytime soon..

**Comment by hsivonen** [comment]
> Any browser with a charset selector would fix the mojibake,

No, in the second case, data loss has happened on the server side and no browser-side encoding choice could fix it.

> doesn't help that desktop Firefox has the option when the android version doesn't anymore.

I agree. My point was to check whether the reported cases would be fixed by providing a UI entry point. The result is that one would and the other wouldn't.

In any case, Fenix shouldn't introduce the kind of submenu that desktop Firefox has. That's in the [process of being replaced](https://bugzilla.mozilla.org/show_bug.cgi?id=1687635) with a single menu item corresponding to the item "Automatic" in the current submenu.

As for the decision to introduce a single UI action to Fenix corresponding to the menu item "Automatic" in the current submenu of desktop Firefox, the [desktop telemetry](https://bugzilla.mozilla.org/show_bug.cgi?id=1702914#c14) in the bug about whether the Photon app menu should have such an item may be of interest.

**Comment by hsivonen** [comment]
[SUMO question asking the menu back](https://support.mozilla.org/en-US/questions/1302116)

**Comment by hsivonen** [comment]
The desktop side of this has now settled down.

I think this issue as titled (configurability of the fallback encoding) is a clear WONTFIX. However, I think it could be reasonable to offer the same functionality that's available on desktop. It seems that I'm not allowed to re-title this issue.

Some notes about replicating the desktop feature (in the View menu and available as a toolbar button via Customize Toolbar…):

* It doesn't make sense to decide whether to offer the feature by taking a global look at telemetry: When Latin-script locales participate in telemetry, the global result is that feature usage is extremely rare. The relevant thing to observe is that on desktop, looking at what proportion of distinct telemetry submitters use the feature at least once over a given time period, Japan totally stands out with Taiwan up next. The decision should be whether the Japan use case is worth addressing and, if it is, letting other locales, at least non-Latin-script ones, have the feature, too.
* On desktop, I don't have any particular telemetry number threshold for considering the Japan use case worth addressing. Telemetry shows that Japan stands out, and instead of having a particular threshold, I'm observing that people really care about reporting bugs about this topic in the Japan/Japanese context.
* The menu item should be called "Repair Text Encoding".
* When the page is loading, the menu item should be disabled.
* When the page load completes, the menu item should be enabled if, and only if, the `mayEnableCharacterEncodingMenu` property of the frontmost top-level docshell is true.
* Invoking the menu item (when enabled) should call `forceEncodingDetection()` on the frontmost top-level docshell and then immediately tell it to reload via `nsIWebNavigation.reload(nsIWebNavigation.LOAD_FLAGS_CHARSET_CHANGE)`.

**Comment by Multipanda** [comment]
Oh, was the encoding option gone in Proton at some point? I turned off Proton immediately in about:config when it deployed since I didn't like how the tabs looked, can't remember whether the encoding options was there or not.

Regarding the second link btw. I just don't have the option to change encoding when browsing it with desktop FIrefox, some sites seems to lock it, but you might be right about database corruption being a possibility, I have come across a few old sites where changing encoding didn't fix it fully.

**Comment by hsivonen** [comment]
> Oh, was the encoding option gone in Proton at some point?

Prior to Proton, there were three entry points for the feature. Starting with Proton, there are [two entry points](https://support.mozilla.org/en-US/kb/text-encoding-no-longer-available-firefox-menu). The [bug to restore](https://bugzilla.mozilla.org/show_bug.cgi?id=1702914) the third entry point remains open.

**Comment by KrasnayaPloshchad** [comment]
The desktop version is still able to access this option via menu bar, which is accessible via Alt key.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813217

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
