### ISSUE TITLE
FNX-5133 ⁃ [Bug] It's difficult (if not impossible) to distinguish new tabs opened from the same website

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1613]
## Steps to reproduce
Open a website (The Guardian for example) and then open several pages from this website in new tabs. Check the tabs and try to distinguish them visually.

### Expected behavior
It's possible to distinguish the tabs.

### Actual behavior
As the tab previews show the page's URL instead of the page's title, and as the thumbnails are not loaded until the page is loaded in the foreground, it's not possible to distinguish the tabs.
![Screenshot](https://user-images.githubusercontent.com/32398857/56070734-fed29280-5d5f-11e9-90a8-c84ee8d8168b.jpg)UNITO-UNDERSCORE!20190412-193822!UNITO-UNDERSCORE!Fenix!

### Device information
* Android device: Galaxy A5 (2017) with Android 8.0
* Fenix version: 1.0.1915

**Comment by Cheap-Skate** [comment]
I have this problem too.
(1) the tab preview shows the URL not the tab title. The URL often looks identical for different pages from the same site
(2) the tab preview is wide and short so it only shows the top ~20 mm of the page. Often this looks the same for all pages on the same site.

IMHO for (2) you need to zoom out the tab preview & make it narrower so that it shows more of the page enough to get easy at-a-glance distinction of tabs. Like reference-browser now does in its tab tray.

Example below, this is two different pages from the same site www.bbc.co.uk/news. But I can't tell which one is which [hint, in the top one the URL fades out at the right so I can tell it has a longer URL and so is a sub-page of the main page :) :) ]
My issue is really the same as #1017

![Screenshot_20190414-072711_Fenix](https://user-images.githubusercontent.com/40568887/56091197-634a3a80-5ea3-11e9-9200-532df64c38b2.jpg)

**Comment by yoasif** [comment]
Expected behavior is that the page title is used instead of page URL to differentiate between tabs in a session. 

This is the case in Fennec, Reference Browser, Kiwi, Brave, Edge and Samsung Internet in my brief research.

**Comment by Lululalu** [comment]
I also believe that the size of the font on the tab previews could be made smaller, this way more information can fit, and it will be easier to distinguish between tabs.

**Comment by ekager** [comment]
Thanks everyone for your ideas and research! We will need to get UX feedback on the current tab design before we can make any changes.

**Comment by ekager** [comment]
We actually have confirmed new UX for this and it is being worked on, follow along in https://github.com/mozilla-mobile/fenix/issues/1830
