### ISSUE TITLE
[UX] Show prompt for user to enable permissions in Settings for denied permissions by a site (like maps.google.com location)

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#16189]
Currently, for our in-app permission prompt for QR code scanning, the following happens:

1. Click on "Scan" to trigger the permission request
2. Android camera permission pops up
3. Click "Deny"
4. Again, click "scan", and again "Deny" the camera permission
5. Click "Scan"
6. We will show the in-app prompt directing user to go to Settings to enable the Camera.

We should share this behavior across the app, for all "Always Deny" permission states. Specifically, we should make sure that if the user clicks on something like "location" in maps.google.com, and deny the permission multiple times, that subsequent clicks on the "location" button will show the dialog explaining that they need to enable the permission in Settings (similar to QR camera permissions).

See this [comment](https://github.com/mozilla-mobile/fenix/issues/14239#issuecomment-716733192) for context.

**Comment by liuche** [comment]
![photo4951779164516624548](https://user-images.githubusercontent.com/1082253/97236590-a4165580-17a2-11eb-8af0-0cff2af732fc.jpg)

If we need a string for a site-triggered permission, should we just say something like:

"This site is requesting %s access. To grant access, go to Android settings, tap permissions, and tap allow."

where %s is the permission type (Camera, Microphone, Location) that we should be able to get from Android.

**Comment by liuche** [comment]
cc @betsymi (from our thread yesterday). 
We'll want to show this when users have "denied" a permission (like mic) multiple times and Android no longer prompts them - but we need to show something so that clicking on some part of a site's UI (like a mic icon on a webpage) doesn't look broken (but shows the dialog to change enable the permission from settings if they want to use that site).

(to be clear, we're not necessarily recommending that they enable it, but showing it if they a) want to use the site's capabilities, b) don't remember that they've rejected the preference so need some explanation why nothing is happening)

**Comment by st3fan** [comment]
Before we rush into adding another prompt or dialog - can we please look at how we handle this situation on Desktop?

There, the app asking for the permission after the user has denied it does not trigger anything. Instead we make it clear in the location bar that a permission was asked for and if you click on that, you will see what specifically was asked for:

![Screen Shot 2020-10-27 at 11 14 23 AM](https://user-images.githubusercontent.com/28052/97322072-d1680f80-1845-11eb-9744-d8721b82e87b.png)

I want to make sure that we don't rush into a fix here because getting this right is core to our browser.

**Comment by st3fan** [comment]
In the screenshot below you can see that we do let the user know that the permission was previously denied, You can even tap on that "Blocked" link in the doorhanger which will either prompt (if blocked at the system level) or allow when tapped.

Maybe the real problem here is that the doorhanger with this additional information is not discoverable?


![Screenshot_20201027-112509](https://user-images.githubusercontent.com/28052/97323577-543d9a00-1847-11eb-8a8f-b73706083934.png)

**Comment by betsymi** [comment]
Thanks for raising these concerns @st3fan. I agree that introducing more dialogs is likely a Band-Aid solution to a different problem around permissions, mainly how discoverable they are and how people access them, when they need to.

**Comment by liuche** [comment]
Chatted about this in standup, and it's worthwhile to pull into our current sprint to get started, especially if this is going to be become a larger issue.

**Comment by apbitner** [comment]
I'm looking into this issue and was just re-reading the feedback we received from Google through @lwa-moz. It says:

> we need to reserve sending a user to the app settings until the app has detected that the 'Always deny' option has been selected

This appears to be in reference to the camera permission for QR code scanning. When the user taps on 'Scan' for the first time, they see this system prompt:

![Screenshot_20201029-092624](https://user-images.githubusercontent.com/22176302/97595251-8549d600-19d1-11eb-9a62-0035b278158b.jpg)

There is no 'Always deny' option, but it seems 'Deny' has the same effect, so I'm not clear how exactly we're violating their guidelines?

It seems the issue around discoverability of previously denied permissions is a separate, but related topic, and isn't required to get us featured in GPS, correct? As @st3fan pointed out, it is handled much better on desktop, but we just don't have the same amount of screen real estate. Do we have user feedback indicating users don't know how to change previously denied permissions?

**Comment by liuche** [comment]
@apbitner the "always deny" string is on an older version of android but their docs say if a user denies twice, that's implicitly an "always deny" action.

The situation with this bug is not about the QR code usage (which is the correct behavior), but about other places where Fenix needs to get user permissions. Since Fenix is a web browser, there are lots of places where a site might request a permission (camera + audio, for a web conference site, or location for a maps site), where they are bringing up the issue of how we handle permissions.

I think there are two main questions that we want to answer:
- How should we respond to the general situation in Fenix where a permission is required, to use a site? And what if that permission has already been denied (twice)? (e.g. multiple sites might request location but a user might not associate denying permission to one site as denying the same permission to other sites)
- How can we protect against bad behavior in sites that spam permission requests? (what do other browsers do?)

A few notes:
- There are a two levels of permission: 1) Android allowing Fenix to use a permission, contingent on the user's approval, 2) Fenix allowing sites to use a permission (which we provide controls to in Site Settings) - either can be revoked by the user.

**Comment by apbitner** [comment]
@lwa-moz 

@liuche and I chatted a bit today and compared Fenix's flow for site permissions to Chrome's, and we're having trouble seeing where the big discrepancy is between the two that led to Google flagging our app. I took screenshots in both browsers of a flow involving denying darksky.net permission to my location. Overall the flows are very similar in regards to how a user can change a denied permission, but they're not identical. Fenix does show an OS dialog that Chrome does not, and Chrome has its own site settings section within their app settings, but I don't know if either of these are related to the issue that Google brought up. Take a look at the flows below, and feel free to share with your contact, so that we can better understand exactly what needs to be addressed. Thanks!

**Permission Flows:** https://www.figma.com/file/zcD07bV3139cgvjaGDhPuq/Site-Permissions?node-id=6%3A2

**Comment by liuche** [comment]
Thank you for the in-depth research @apbitner! I passed this on and it was very helpful in the conversation and justifying our position. I heard back that we are satisfying the Android requirements about [permission denial and messaging](https://developer.android.com/training/permissions/requesting). 

I'm going to resolve this as closed.
