### ISSUE TITLE
[Bug][secret settings] "Synced tabs" label & the refresh option from tabs tray are below the synced tabs 

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16427]
## Steps to reproduce 
1. Enable the secret settings (tap 5 times on the Firefox logo from About Firefox).
2. Enable the "Show Grid View in Tabs Settings", and "Show Synced Tabs in the tabs tray".
3. Set the tabs view in grid view from Tab settings.
4. Sign in with the same FxA account on mobile and desktop, or on two mobile devices.
5. Open the tabs tray and observe the position of the "Synced tabs" title/label and the refresh button.

### Expected behavior
The "Synced tabs" title/label and the refresh button are positioned under the "Save to collection" button and on top of the synced tabs list.

### Actual behavior
The "Synced tabs" title/label and the refresh button are positioned under the synced tabs list.

### Device information
* Android device: all
* Fenix version: 11/6 Nightly

### Note
Setting the tabs in list view, displays the synced title and list on top of the opened tabs.
 
<img src="https://user-images.githubusercontent.com/40694158/98382973-92f7ff00-2054-11eb-8715-134595a53586.png" width="300" height="550" />

**Comment by Poopooracoocoo** [comment]
They're aware of this and will be making a tab for synced tabs in the tab tray.

Speaking of the tab tray, in today's nightly I noticed that they made a change. The direction that new tabs are opened has been reversed. The change doesn't change currently opened tabs! This is an annoying decision because it makes the tab tray useless, which is similar to another issue where they removed the state where it took up a third of the screen. The toolbar gestures still don't make sense either. And wow. Typing is still sluggish bit yay, at least it works. Scrolling this very comment text box causes the toolbar to appear... The toolbar still doesn't autohide on add-on pages and there are like a million other issues and missing features. But the scrolling is great thanks to Markus but zooming is sluggish. 

Argh.

**Comment by Poopooracoocoo** [comment]
see https://github.com/mozilla-mobile/fenix/issues/15798#issuecomment-709632492 (similar main issue)
