### ISSUE TITLE
[Bug] fotomac.com.tr - missing information line

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16446]
## Steps to reproduce
1. Open firefox beta
2. Go to the site "fotomac.com.tr"
### Expected behavior
The information bar should be displayed in the result
### Actual behavior
In fact, the Information bar is not displayed. I attached a screenshot as it should be in reality.
### Device information
 Huawei Y6 Pro - Android 5.1
Vestel Venüs v3 - Android 6.0.1
* Android device: yes
* Fenix version: firefox beta 82.0.0
 
![image](https://user-images.githubusercontent.com/66958331/98447938-d5473c00-2139-11eb-8d7c-540da1dec1e0.png)

**Comment by AndiAJ** [comment]
It's caused by the ETP setting.
The Ads are properly displayed having ETP set to Standard
The Ads will not be displayed having ETP set to Strict

Checked this matter on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

✔️  Same behavior on Chrome as well.
