### ISSUE TITLE
FNX-467 ⁃ [Bug] Drawable ripple for lock icon in toolbar is wrong

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1648]
Related Android Components issue: mozilla-mobile/android-components#4673

The drawable ripple for the lock icon (when pressed) appears behind the toolbar instead of in front of it.

## Demo
![icon 2019-04-15 13](https://user-images.githubusercontent.com/4400286/56162622-484df800-5f81-11e9-8f1f-124873eef00c.gif)UNITO-UNDERSCORE!19!UNITO-UNDERSCORE!55!

**Comment by julKali** [comment]
I'll see what I can do for you...

**Comment by julKali** [comment]
Update: most of the elements inside the toolbar are defined not in fenix but in [mozac](https://github.com/mozilla-mobile/android-components).

In this specific case one would need to tinker with the siteSecurityIconView AppCompatImageView defined in the [DisplayToolbar class](https://github.com/mozilla-mobile/android-components/blob/4a3c853bbe3c7d41d819b9e825314216143cfabb/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#L77).

As changes to mozac would impact more than just fenix, I would suggest postponing this issue, as I also do not see much urgency. Personally, I don't mind the ripple being below the URL bar. 

PS: @sblatz, if I'm not mistaken, this issue is not very suitable for beginners. Please consider removing the "good first issue" label.

**Comment by sblatz** [comment]
Other ripple issues seen here: 

![Button presses look weird on toolbar 2019-10-07 09_46_08](https://user-images.githubusercontent.com/4400286/66331432-63257780-e8e7-11e9-9979-ef5aa47cfb47.gif)

**Comment by sblatz** [comment]
I will file this in AC as well.

**Comment by miladmaz12** [comment]
Bug for the 3-dot menu (square instead of circular ripple effect) still present on 2.2.0

**Comment by NotWoods** [comment]
Fixed by @sblatz
