### ISSUE TITLE
[Telemetry] Media Playback

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16494]
## Description & Product Manager / Data Scientist User Story

As a product manager, I want to know if our users can successfully play media and interact with playback functions, so we can focus on removing barriers to an uninterrupted media playback experience. 

## What questions will you answer with this data?
- How often does media on a site fail to play (after being initiated by user)? What types of media files fail to play?
- How often does media playback stop unexpectedly and cause the user to refresh or abandon the site?
- What type of media files are most often played in Fenix? 
- What is the average length of audio playback?
- What is the average length of video playback?
- Two more questions related to PiP #15368

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by mcarare** [comment]
@vesta0 I have some questions regarding this: 

- "types of media files" is in reference to file types (audio-video file formats) or to media type: Audio/ Video?

-  "average length of playback" references the times between the play and pause/ stop events tracked here: https://github.com/mozilla-mobile/fenix/issues/5705? Should adding timestamps (and maybe media type) to those events be enough, or should we send a different metric with playback time? 

- for the first two points it would need investigation if we can catch media failing to play (AFAIK we do not show any message, but gecko maybe does). And we should consider the fact that some media failing to play could be caused by web-compat issues.

**Comment by vesta0** [comment]
Thanks for the questions @mcarare :) See responses below.

> @vesta0 I have some questions regarding this:

>     * "types of media files" is in reference to file types (audio-video file formats) or to media type: Audio/ Video?

File types (so we know which bugs to prioritize when a site is not playing an audio/video)

>     * "average length of playback" references the times between the play and pause/ stop events tracked here: #5705? Should adding timestamps (and maybe media type) to those events be enough, or should we send a different metric with playback time?

Sounds like adding timestamps should be good enough but please check with Data Science to make sure!

>     * for the first two points it would need investigation if we can catch media failing to play (AFAIK we do not show any message, but gecko maybe does). And we should consider the fact that some media failing to play could be caused by web-compat issues.

Sounds good, it would be good to investigate this while keeping in mind that a percentage of those failures could be due to web compat issues (or even site issues).

**Comment by mcarare** [comment]
@vesta0 Thank you for the clarifications. I will submit a ticket to DS for the second issue. We already have timestamps by default on those pings.
As for the second and third issue, I asked because I think this will need GV work, as there are no API's in AC/ Gecko we can use to get file format. (https://developer.mozilla.org/en-US/docs/Web/API/MediaSession). If this is important data we need, I can open a ticket in Bugzilla, and see about the work needed and its priority.

**Comment by bifleming** [comment]
@mcarare did we get a Bugzilla item opened for this?

**Comment by amedyne** [comment]
Here's the bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1672747
