### ISSUE TITLE
Gradle: Task caching not working

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#16551]
When running a task like the `test` task a second time, without any code changes, then this task should complete without actually running any tests because Gradle sees their are no changes. This can be observed in AC when running the tests for a component twice. However something seems to break that in Fenix, running the `test` task a second time will run all the tests again.

**Comment by mawen7** [comment]
@pocmo Build cache is not enabled on fenix, see #11621.

#17627 might help a bit, if you want to take a look.

**Comment by pocmo** [comment]
Afaik the build cache is independent from that - for keeping backups of `build/` state even when code changes. But in this case here running the task twice without changing any code should not cause a rerun of everything afaik.

**Comment by mawen7** [comment]
@pocmo You're right it works on AC even with build cache disabled (beside modules using updateExtensionVersion). Sorry for confusion I mixed things up.

Output for `test -i` with static `BUILD_DATE` and #17627:
`Task ':app:testReleaseUnitTest' is not up-to-date because:
  Task.upToDateWhen is false.` (same output for all variants)

Seems like like AGP or Gradle set `upToDateWhen` to false.
Same behavior can be observed on AC if running `testDebugUnitTest` while `testReleaseUnitTest` is up-to-date.

Nevertheless `BUILD_DATE` breaks up-to-date checks for non-debug variants and without #17627 up-to-date checks are broken for every variant.

Maybe `BUILD_DATE` should be replaced with git hash like in AC?

**Comment by grigoryk** [comment]
I can't replicate this anymore. Perhaps this got fixed via https://github.com/mozilla-mobile/fenix/pull/22601
