### ISSUE TITLE
Investigate why CI is passing for PRs that should fail on build tasks

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#16565]
Twice this week PRs landed after a full green CI suite that should have failed at least one task (since master shouldn't have built) and then needed reverts. 

The two PRs:
https://github.com/mozilla-mobile/fenix/pull/16535
https://github.com/mozilla-mobile/fenix/pull/16536

**Comment by JohanLorenzo** [comment]
Hi @ekager!

Thank your for bringing my attention to this issue. I looked into both PRs and there are 2 different problems, in my opinion. 

 #16535 is a human error to me. Even though the PR was indeed created an hour after #16466 was merged on master[1], the branch it was based upon did not contain #16466[2]. CI genuinely showed a green build because it was able to compile what's on that branch. An autoland bot like bors is the perfect way to detect such errors before they reach master, since it rebases patches on top of that branch.

Speaking of bors, #16536 is a configuration bug. If I'm not mistaken, bors waits for the job called `complete-push` on android-components[3]. On Fenix, bors for nothing:

https://github.com/mozilla-mobile/fenix/blob/2c4f0624fd806cde5334add2e761e623d7039660/bors.toml#L1

I guess bors says it succeeded when it has nothing to wait for. That would be how we ended up with this misleading comment https://github.com/mozilla-mobile/fenix/pull/16536#issuecomment-726451715, even though the commit just above shows red and the build tasks are busted[4].

@pocmo Do we just need to change the decision to expose a `complete-push` task on Fenix and let bors wait for it? Or is there anything else we should do beforehand? 

[1] https://treeherder.mozilla.org/jobs?repo=fenix&revision=ebadbdb3522fc777e388ca1241e0287e89fec111
[2] https://github.com/gabrielluong/fenix/commits/3283e0bf2feb9c13c260c6555fe642b7f95f1679
[3] https://github.com/mozilla-mobile/android-components/blob/447c177b0eedf6224f8504ac0e09058477196995/bors.toml#L1-L3
[4] https://firefox-ci-tc.services.mozilla.com/tasks/groups/e-osx4u9TJSfDOl7wzU9fQ

**Comment by pocmo** [comment]
> @pocmo Do we just need to change the decision to expose a complete-push task on Fenix and let bors wait for it? Or is there anything else we should do beforehand?

Yeah, that would be enough.

If we go with mergify then the already existing `pr-complete` should be good enough.
