### ISSUE TITLE
FNX-5164 ⁃ [Bug] Page contend does not automatically changed based on selected theme.

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1658]
## Steps to reproduce
1. Go to https://kevinchen.co/blog/support-macos-mojave-dark-mode-on-websites/
1. Tap on the 3dot menu > Settings > Theme and select Dark.
1. Go back to the webpage.

### Expected behavior
The page content is updated accordingly to reflect the change in the settings.

### Actual behavior
The page content does not change into dark mode.

### Device information
* Android device:
  * Nexus 5 (Android 6.0.1)
  * Google Pixel (Android 9)
* Fenix version: 1.0.1916 (#11061212)

**Comment by yoasif** [comment]
@ekager saw that you committed a change to refresh a session when the theme changes - does this mean that the tab also reloads? 

Curious about this because changing my desktop theme on desktop updates the prefers color scheme on pages without having to refresh. 

It would be nice if this didn't require a refresh if so.

**Comment by bsurd** [comment]
@yoasif this does do a page refresh when switching between light and dark mode.

There still seems to be an issue with this if using the option to auto switch the theme based on the battery saver/device theme. The page does not update in that case.

**Comment by ekager** [comment]
Just added a check that should update the page content when the theme auto changes

**Comment by kbrosnan** [comment]
Verified on a Pixel 2 XL by enabling the battery saver option.
