### ISSUE TITLE
[webcontent] Invalid resolving of the relative paths in CSS

### ISSUE THREAD

**Issue by xrogers** [mozilla-mobile/fenix#16586]
## Site with issue and any steps to reproduce
Minimal test case: https://znpd.pl/test-error.php
While loading site on Firefox Mobile, I'm getting two requests to the image:
`https://znpd.pl/gfx/layout/logo.png`
and
`https://znpd.pl/static/gfx/layout/logo.png`
where the latter one is correct.

See `https://znpd.pl/static/css/test-error.css `
linking to:
`h1 { background: url("../gfx/layout/logo.png") no-repeat; `}

### Expected behavior
Browser should resolve paths in CSS file relative to the path of CSS file itself, not to the original document.

### Actual behavior
Firefox first tries wrong path of the image defined in the CSS file.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No,

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No, no error in Chrome, nor in Firefox Desktop.
### Device information

* Android device: POCO F2 Pro
* Fenix version: 82.1.3

**Comment by Mugurell** [comment]
This seems like a GV issue.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1690288

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by emilio** [comment]
@xrogers hey, thanks for reporting this. I couldn't reproduce the issue (see the screenshot I attached to the bugzilla bug), can you comment how can I see the extra request?

**Comment by kbrosnan** [comment]
This is probably the [A-C icons library](https://github.com/mozilla-mobile/android-components/tree/master/components/browser/icons/src/main/java/mozilla/components/browser/icons).

**Comment by emilio** [comment]
Ok, so should this be reopened then? How is that URL getting to that library?

**Comment by Mugurell** [comment]
I can check if actually the app makes that call.

**Comment by Mugurell** [comment]
With a simple log [here](https://github.com/mozilla-mobile/android-components/blob/4982e9ba1b1a72a149f4137ebaa828ba19ebf214/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt#L290) I see no calls to the website being made by the Icons code.

Tried using Burp Suite to see the calls being made by the app but while Chrome loads websites just fine using that external CA Fenix refuses to do so, so I wasn't able to confirm the calls made.

That being said, this seems to require more investigation on the Fenix/AC side first.

**Comment by Mugurell** [comment]
Looked into this more but saw that the app doesn't use any url for the icons (in fact we'll use a generated icon because we don't have a favicon to show).
We are relying on a webExtension - [`icons.js`](https://github.com/mozilla-mobile/android-components/blob/4c4e20dac915d28c83aa6a26b7cfc4207b47c1f3/components/browser/icons/src/main/assets/extensions/browser-icons/icons.js) that queries the entire dom for what could possibly be an icon and then send all those links to our icons code that will download the appropriate resource but saw that for this website there are no inferred icons links (as expected) and so the app will not actually download any resource to use as a favicon.

Also using CharlesProxy I saw no calls made to those resources.

@xrogers Do you still see this issue?

**Comment by Mugurell** [comment]
@xrogers Is this still an issue for you?

**Comment by Mugurell** [comment]
Since this was reported as an issue for a specific website and is unclear whether is reproducing or not I'll close the ticket.
@xrogers Please reopen if this is still an issue and have steps to reproduce.
