### ISSUE TITLE
[Bug] [Pull to refresh] If beforeunload cancels the refresh the spinner remains (affects music.youtube.com).

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#16598]
## Steps to reproduce

 * Go to https://crisal.io/tmp/android-pull-to-refresh-beforeunload.html
 * Click the button (does nothing) so that beforeunload fires.
 * Pull to refresh.
 * An "Are you sure?" dialog should pop up, tap on "stay". 

### Expected behavior

I'd expect the spinner to go away.

### Actual behavior

Spinner remains on the page.

### Device information

* Android device: N/A (repros on emulator too)
* Fenix version: Latest nightly.

**Comment by emilio** [comment]
cc @hiikezoe

**Comment by opusforlife2** [comment]
You can see this on Startpage when using POST as well. If you cancel the prompt that asks you to resend info upon refreshing, the spinner stays there.

**Comment by hiikezoe** [comment]
[This change](https://github.com/hiikezoe/android-components/commit/56d7681865a7d295541657bc23c2f5c38d203342) should fix this issue.

@Mugurell can you please use this change as a reference to fix this issue? I don't know how we can run a single unit test there so that I haven't run the unit test in the change, and also I am not sure whether we need to change all GeckoPromptDelegate.kt(s) in engine-gecko, engine-gecko-beta and I don't want to learn about the role/rules now. :)

**Comment by Mugurell** [comment]
@hiikezoe Sure. Thank you for helping with this!

**Comment by Mugurell** [comment]
Put up https://github.com/mozilla-mobile/android-components/pull/9044 to resolve this in AC.

**Comment by emilio** [comment]
Thanks for fixing this @Mugurell!

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 25/11** with **Google Pixel 4 XL (11), Samsung Galaxy S10+ (10), Samsung Galaxy S7 (7).**
Note that the spinner disappeared without problems.

**Comment by hiikezoe** [comment]
\o/ Thank you @Mugurell!

**Comment by Mugurell** [comment]
@hiikezoe Thank you!
