### ISSUE TITLE
[Pull To Refresh][Bug] Avoid accidental refreshes by forcing a cooldown period after the last scroll gesture

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#16661]
### Steps to reproduce

 1. On a scrollable page, scroll down.
 2. Scroll up to the top with a series of quick pans / flings.

### Expected behavior

No pull refresh should be triggered during gestures that were intended to only scroll.

### Actual behavior

As soon as the top edge of the page is hit, the next gesture instantly triggers pull to refresh.

This does not happen in Chrome. Chrome seems to enforce a cooldown period before pull to refresh is triggered. See this video for a comparison: [quick-consecutive-flings.mp4](https://bugzilla.mozilla.org/attachment.cgi?id=9189010)

From experimenting, it feels like the cooldown period is somewhere between 300 and 500ms.

### Device information

* Android device: Moto G5
* Fenix version: Firefox Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8837)

**Comment by Mugurell** [comment]
Judging from the video and a quick test in Chrome,
There is no cooldown per se.
What happens on Chrome is that a swipe up and then down will trigger the overscroll effect instead of the pulll to refresh throbber like it happens on Fenix.
Then if you continue to swipe down while the edge effect hasn't finished the gesture will trigger again the overscroll effect and if would be possible to keep this behavior with such swipes for a loong time.

That being said, we should probably do the same. Thank you for filing this!

**Comment by etmatrix** [comment]
I have a similar issue on div with scrollable layout (site without mobile layout), everytime I try to scroll down the content of div I got a refresh and not a scroll.
I use the tricks scroll down and to right. but not always works.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807072

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
