### ISSUE TITLE
[Bug] Freezing / Disappearing Search Text

### ISSUE THREAD

**Issue by BrokenShoeLace** [mozilla-mobile/fenix#16736]
I use Bing.com and when I search for something, click to change search tabs from all to images etc, the browser is frozen. Click in the search box does nothing not even show the keyboard. The only action is to use gestures to close Firefox and try again. The same happens with Google and has been present for the past two versions.

Secondly, type something in the address field, click in there to copy the text or to append the text for it to disappear and having to type it in again. This even happens if you had just searched for the text.

**Comment by ebalazs-sv** [comment]
I can reproduce this issue on the latest Nightly 11/26 with Pixel 2 (Android 9).

### Steps to reproduce
1. Launch Fenix;
2. Set the default search engine to Bing;
3. Type the URL bar and search for a term;
4. Tap Images or Videos or News;
5. Tap the search box;

### Expected behavior:
The buttons and the search box are actionable.

### Actual behavior:
The buttons and the search box are not actionable.

### Video:
![20201126_144328](https://user-images.githubusercontent.com/48799384/100352998-7ff2a200-2ff6-11eb-9625-f97bd5e27c07.gif)

### Notes
This is not reproducible with other default search engines.

**Comment by kbrosnan** [comment]
Tracked by bz-1686002, closing
