### ISSUE TITLE
incorrect placement when loading the site

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#16765]
2 text that should be in the middle just below the iphone picture in the firefox browser are on the left for 1 week. this issue exists for both desktop and mobile fenix

https://www.apple.com/tr/

https://resimag.com/p1/1ffda1c842e9.jpeg
Firefox Fenix ss
![Screenshot_20201128-224601_Firefox_Nightly](https://user-images.githubusercontent.com/60405617/100524731-cc86da80-31ba-11eb-9013-80562bfcb354.png)

Chrome SS
![Screenshot_20201128-224615_Kiwi_Browser](https://user-images.githubusercontent.com/60405617/100524737-db6d8d00-31ba-11eb-83b1-5dba131bd1c2.png)

**Comment by reyis4402** [comment]
Firefox Desktop
![En6l28CWEAIo8WJ](https://user-images.githubusercontent.com/60405617/100524834-bdecf300-31bb-11eb-8c29-50184de27d26.jpg)

**Comment by SoftVision-LorandJanos** [comment]
Hi @reyis4402 ! Thank you for your report! This issue is no longer reproducible as described, on the latest Nightly (210331 05:02 - GV89) and on Latest Release (87.0.0-rc.1) as the text you mentioned is displayed in the middle. Verified, using a Motorola Nexus 6 (Android 7.1.1).
![Screenshot_20210331-175136](https://user-images.githubusercontent.com/48829350/113165787-df81e800-924a-11eb-8b25-443d27a136ee.png)

**Comment by reyis4402** [comment]
The problem has improved thanks

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Verified as fixed on the latest Nightly (94.0a1 - 2021-10-04T05:10:50.531272).

Now there's the iPhone 13, and is displayed as exected.

Devices used:

Samsung Galaxy Tab S3 (Android 9).
Huawei P30 (Android 10).
Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
