### ISSUE TITLE
Open new tab upon swiping left of the last/latest tab

### ISSUE THREAD

**Issue by angriness-sleek** [mozilla-mobile/fenix#16819]
Currently we can't swipe (when scrolling on the url bar) left to the topmost/leftmost tab in the queue, an option to just open a new tab instead of not being able to swipe at all should improve the ux

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8946)

**Comment by ebalazs-sv** [comment]
Since this is a feature request, I have added the required label. Thanks!

**Comment by CombeeMike** [comment]
I really love this idea!

Some additional thoughts:

* Right now, the URL bar shows the number of open tabs at one glance. To me it would be really useful to also see the "position" of the currently open tab. E.g. show `2/5` instead of just `5`
  * (Pro) Gives a clear visual indicator when scroll left/right is not working anymore (reached first & last tab)
  * (Pro) Sometimes I open a few links in background during reading something. After reading the "initial piece", I go through the newly opened tabs. During this process, this would give me some kind of "progress indicator". Probably kind of a "niche use case"...
  * (Con) Probably a little clumsy & "space consuming"...
* Alternative to the above: Show some "visual clue" when reaching first or last tab.
  E.g. change color or border of "number of open tabs" to yellow (first tab) and orange (last tab). Those are obviously just some wild ideas and could be designed in many different ways...
* When swiping left on last tab, FF could show some prompt to ask the user whether he wants to create a new tab or not. Could be useful to prevent creation of new tabs by mistake...

**Comment by Sum1Random** [comment]
@CombeeMike I like your visual cue idea. I could definitely envision a little angle bracket appear on either side of the tab number to indicate that there are more tabs in that direction. 
e.g. <|5|>

In saying that, I'm not too keen on the original idea as I often swipe to try to switch to the next tab at the end, specifically to confirm that I am at the end.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812889

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
