### ISSUE TITLE
Please add Swipe Up/Down Gesture on Urlbar and Tab Icon

### ISSUE THREAD

**Issue by gihucom** [mozilla-mobile/fenix#16848]
Hi,

could you please add gesture functions to swipe up/down on urlbar and tab icon, depending on their position (top or bottom)

For example:
Swipe up/down on urlbar to refresh the website
Swipe up/down on tab icon to close tab

Thank you

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8965)

**Comment by cadeyrn** [comment]
> Swipe up/down on urlbar to refresh the website

Pull to refresh is already implemented in Firefox Nightly. It's not an address bar gesture, instead you have to pull down in the content area but this is how it works in other browsers as well. I don't know when this feature will be ready for Beta and stable releases but it's already worked on.

Since Pull to Refresh is already making progress and because it's always a good idea to have only one request per issue I suggest to focus in this issue on you other feature request (swipe up/down on tab icon to close tab).

**Comment by ebalazs-sv** [comment]
Since this is a feature request, I will add the according tag.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812888

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
