### ISSUE TITLE
Disable jetifier

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#16855]
Android Components was just able to disable jetifier. Fenix may be able to follow now.

AC: https://github.com/mozilla-mobile/android-components/issues/8459

**Comment by mcomella** [comment]
robolectric relies on annotations from the support library so compilation fails (I'm not sure why ac doesn't run into this issue - maybe their version of robolectric doesn't use annotations). Unfortunately, it isn't as simple as upgrading robolectric because other tests start to fail so this is growing in scope beyond what time I can put into it. See https://github.com/mozilla-mobile/fenix/pull/17528#issuecomment-763008962 and later comments for details. I'll have to unassign.

**Comment by mcomella** [comment]
I tried to fix this again today but it still doesn't work:
```
[task 2021-07-23T18:09:23.845Z] * What went wrong:
[task 2021-07-23T18:09:23.845Z] Could not determine the dependencies of task ':app:lintDebug'.
[task 2021-07-23T18:09:23.845Z] > Could not resolve all artifacts for configuration ':app:debugUnitTestCompileClasspath'.
[task 2021-07-23T18:09:23.845Z]    > Could not find com.android.support:support-annotations:28.0.0.
[task 2021-07-23T18:09:23.845Z]      Required by:
[task 2021-07-23T18:09:23.845Z]          project :app > org.robolectric:shadows-framework:4.3.1
```

**Comment by pocmo** [comment]
> project :app > org.robolectric:shadows-framework:4.3.1

I am going to update Robolectric (and other things) in PR #19665. Maybe that will unblock this here too. 🤞

**Comment by pocmo** [comment]
The upgrade landed! :)
