### ISSUE TITLE
On Android 5.1.1 - Unable to dismiss the quick tab actions menu (tab counter long press)

### ISSUE THREAD

**Issue by sivaraam** [mozilla-mobile/fenix#17104]
## Steps to reproduce
1. Long press on the tab count indicator to open the quick tab actions menu.
2. Try tapping somewhere outside the menu to dismiss it.

### Expected behavior
The menu is dismissed it.

### Actual behavior
The menu is not dismissed. I honestly find no way to dismiss the menu apart from choosing one of the options in it. It would be nice if it were dismissable.

### Device information
* Android device: 5.1.1
* Fenix version: 83.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9148)

**Comment by ekager** [comment]
Would you mind trying Nightly to see if you can still reproduce the problem there? You can download it here https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by rhendric** [comment]
I still see this issue in 89.1.1-armeabi-v7a.

**Comment by Siva981** [comment]
All 3 issues are reporting the same defect.

#19664 
#17104 (this issue)
#22312

**Comment by Siva981** [comment]
I can confirm that this is still happening in my device.

### Related Issue: 
Also, the same issue happens when I tap on the 3 dot options-icon next to any of the items inside the Bookmarks tab. Meaning, be it a bookmark or a folder, if I tap on the 3 dot icon next to it, there is no real way of dismissing the window that pops up, other than selecting one of the options listed inside the pop-up window. In other words, the pop-up window does not get dismissed when I click anywhere outside of that pop-up window. 

### Android: 
5.0.2
### Device: 
Swipe Elite Plus 
### Country: 
India 

## Firefox For Android: 
95.1.0 (Build #2015848803)
AC: 95.0.13, 58539f17f6
GV: 95.0-20211129150630
AS: 86.0.1

**Comment by rhendric** [comment]
Still an issue with 107.1.0-armeabi-v7a.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812832

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
