### ISSUE TITLE
[Bug] Occassional Font Rendering Issue

### ISSUE THREAD

**Issue by jmargathe** [mozilla-mobile/fenix#17139]
## Steps to reproduce
Go to any text-heavy web page, and scroll up and down few times. Occassionally the font will go out of whack resulting in gibberish text being shown.

On my device I've managed to reproduce consistently every time I am typing or filling in a text area (comment box, reply box, etc). The issue will persist until the page refreshes, or the text being scrolled out of view and then scrolled back in again.

I have tried disabling all of the addons, but the issue still persist. The image below is one of the "mild" ones, sometimes it shows a lot more gibberish.

![Screenshot_20201219-125454_Firefox Beta](https://user-images.githubusercontent.com/2161128/102678498-0b79e000-41fd-11eb-8683-15cea1b2067d.jpg)

### Expected behavior
Font should be rendered as per normal.

### Actual behavior
Font seems to be rendering randomly, resulting in a gibberish text being shown.

### Device information
* Android device: Samsung Galaxy S20+ 5G (Exynos) Android 11 with December 2020 patch, but the bug appeared even on Android 10 after the latest Fenix update.
* Fenix version: 84.0.0-beta.4 (Build #2015780083)
* Addons installed and enabled: 
  * uBlock Origin
  * Dark Reader
  * Privacy Badger
  * HTTPS Everywhere

**Comment by kbrosnan** [comment]
Looks like  #13153 but that should be fixed on 84.1.0 @jamienicol is the S20's Mali-G77 MP11 on the deny list?

**Comment by jamienicol** [comment]
Yes, the G77 is on the deny list. This looks like a different issue to me, that bug was initially about black squares appearing, with the latest comment being about a partial present bug (which was the same as #16469).

This one looks like it's probably the GPU cache being corrupted, maybe when it is resized? It is wonderful how many different Mali driver bugs we have encountered 😀

@jmargathe can you reproduce this in Firefox nightly? Could you try going to about:config, searching for gfx.webrender.debug.gpu-cache and setting it to true, then take a screen recording of reproducing this bug? Thanks!

**Comment by jmargathe** [comment]
I've tried reproducing this on both the latest Fenix 85.0.0-beta2 and Nightly 201221 and the issue no longer appears.

Have also tried setting the gfx.webrender.debug.gpu-cache to true on both, and no more issues.

I'll close the bug report and will reopen/file another if it happens again :)
