### ISSUE TITLE
[Bug] Tapping on PWA shortcut opens custom tab with last opened tab instead

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/fenix#17199]
## Steps to reproduce

This is only approximate, I see this from time to time (it might be related to the PWA startup crash that was fixed recently)

- Have some tabs opened and a PWA launcher on the home screen (e.g. twitter)
- Leave the browser alone for a little bit
- Launch PWA from home shortcut

### Expected behavior

The PWA website opens

### Actual behavior

A custom tab browser opens, and from what it looks like it's the most recent tab from Fenix, also the title is incorrectly taken from the PWA website.

### Device information

* Android device: Samsung S10e
* Fenix version: Latest from playstore
 
Notice the title says "Compose new Tweet":

<img src="https://user-images.githubusercontent.com/69051186/103031704-358c1480-4513-11eb-816b-360f000f7d3c.jpg" width="400">

**Comment by fbertsch** [comment]
I think I'm seeing a version of this behavior, and it's very reproducible:

1. Open both PWA "app" and Firefox Nightly
2. Navigate to new web page in Firefox Nightly (e.g. `google.com`)
3. Firefox nightly doesn't navigate to new page, but the PWA page does

Expected behavior: PWA page stays the same, Firefox Nightly navigates to new page

Note: This does _not_ happen with searching, just when navigating to a new site. @agi let me know if you'd like me to instead open a new issue.

**Comment by agi** [comment]
@fbertsch Thanks! I think that's the same bug.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 1/18 with Samsung Note10(Android 10).
