### ISSUE TITLE
problems with Facebook

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#17277]
Hello, I'm using Firefox on Android but there are problems.  The first problem: on Facebook, when entering from the application, you have to refresh from time to time because it freezes (in other browsers it is not).  Second problem: on a page like "zapytaj onet pl" (I didn't use punctuation marks: zapytaj.onet.pl ) it doesn't work properly because I can't access the profile.  Third problem: on a page like gsmmaniak pl, in dark mode, the whole page is white and the text cannot be seen.  Can you help?

**Comment by cadeyrn** [comment]
Hello,

please open one issue per problem and give your issues a meaningful title. There are more than 2,500 open issues and all these issues are about "Firefox for Android". Please also provide relevant information like your Firefox version, Android version and device vendor / model name - there is a bug template for a reason. You should fill out these fields instead of removing these fields. These things are asked to help the developers to understand and fix your problems.

**Comment by kbrosnan** [comment]
Closing as there is not enough information for this to be a useful issue.
