### ISSUE TITLE
FNX-5215 ⁃ [UX] Browser Toolbar

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#173]
**User Story:**
As a user I want to quickly be able to access search, view my current session, and also access other important browser functionality.

**Current Design Status:**

* In Good Shape
* Foundational Design Done
* Requires detailed interaction work (E.g. button tab visual feedback)

**Design Priority:**
P1

**Mockups:**
https://mozilla.invisionapp.com/share/UBQ1OA5HQWY#/341659105_Primary_Browser_Toolbar

**Comment by pocmo** [comment]
Potentially interesting feedback we got for the reference browser:

> Now that the toolbar is at the bottom, please move the menu icons to the bottom of the 3 dot menu and make the reload/stop button sit where the 3 dot menu button is ... so I can go tap tap on the 3 dot menu button to reload page without moving my finger. Like Fennec.
> https://github.com/mozilla-mobile/reference-browser/issues/198#issuecomment-457848399

**Comment by pocmo** [comment]
Toolbar Slack discussion: https://mozilla.slack.com/archives/CA4QR1M2R/p1547557530138200?thread_ts=1547557530.138200

**Comment by Cheap-Skate** [comment]
Fenix toolbar feedback from "me" :)

URL bar wastes space
- move URL text closer to padlock icon and home button, gets more URL text
- make 3 dot menu button narrower horizontally to make gray roundrect larger, more URL text
could easily have 25% more URL text without cluttering toolbar

Need to think about adding tabs tray button and reader button and PWA button and "open in app" button  ... and .... Toolbar could get very cluttered & URL text very short. Fennec toolbar already cluttered, Fenix should be "better".

Supplementary nits

- toolbar uses too much vertical space, eg several px above and below gray roundrect I would prefer more vertical px for content and fewer px for toolbar (this was also a complaint when Fennec moved to Quantum design, toolbar got bigger causing low grade bitching). Take a look at Samsung Internet, toolbar is about 8 mm high on my Galaxy S7 vs 10 mm for Fenix. And Samsung Internet looks just fine to me.

- home icon bigger than padlock icon & 3 dot menu icon. Looks unbalanced

**Comment by TitanNano** [comment]
Some feeback from me:
Please provide a fast way to hide the toolbar without scrolling. Maybe something like taping on empty space inside the toolbar or inside the web content.

**Comment by lime124** [comment]
GH issues from the reference browser repo containing feedback for ux to consider. 
- x in the address bar - https://github.com/mozilla-mobile/reference-browser/issues/503
- progress bar not shown when URL is collapsed - https://github.com/mozilla-mobile/reference-browser/issues/501
- UI feedback from reddit - https://github.com/mozilla-mobile/reference-browser/issues/489
- copy/paste issues - https://github.com/mozilla-mobile/reference-browser/issues/481
- primary button placement - https://github.com/mozilla-mobile/reference-browser/issues/476
- about:blank in the URL - https://github.com/mozilla-mobile/reference-browser/issues/474
- menu selection interaction - https://github.com/mozilla-mobile/reference-browser/issues/420

@st3fan how do you want to handle the process of getting those issues closed?

**Comment by yoasif** [comment]
Unfortunately can't see the mockups (would be nice if those were open).

Some quick feedback on the toolbar:

* the home button next to the menu looks weird; in Bromite, Fennec, and Reference browser, this is where the tab switcher appears. 
* the home button should be on the opposite side of the hamburger menu, to the left of the location bar
* the home button should be removable; in Bromite, long pressing the home button allows users to remove it

I can open these as separate issues if you would prefer, but I was unsure if it made sense since these may already be covered by the mockups.

**Comment by Cheap-Skate** [comment]
Is there actually going to be a home button? I prefer Fennec's approach where the whole URL is the home button and tapping on the URL takes me to Top Sites, History, Pocket, AwesomeScreen etc. I think this is a great differentiator for Firefox. It also saves some space in the toolbar since no Home icon is necessary. And it gives me a big target, any point on the URL.

I think your toolbar is going to get very busy with padlock icon, home button, tab button, 3 dot menu button, plus maybe "open in reader", "open in app" buttons, etc. Could get rid of Home button???? !

**Comment by yoasif** [comment]
>I prefer Fennec's approach where the whole URL is the home button and tapping on the URL takes me to Top Sites, History, Pocket, AwesomeScreen etc. I think this is a great differentiator for Firefox.

I like this a lot too, but I am not sure that there is a plan to bring back about:home in Fennec.

>I think this is a great differentiator for Firefox. It also saves some space in the toolbar since no Home icon is necessary.

Kind of. In Fennec, there is no home button as far as I can tell, so users have to open a new tab and set their home page as their new tab page as well; this is pretty easy by basically double tapping the tab switcher to open their home page, but necessarily opens a new tab (instead of navigating to their home page in the existing tab).

>I think your toolbar is going to get very busy with padlock icon, home button, tab button, 3 dot menu button, plus maybe "open in reader", "open in app" buttons, etc. Could get rid of Home button???? !

Personally, I 100% agree with you -- I don't really see the utility of the home button if Fenix simply replicates Fennec's behavior around the location bar and new tabs - the default home page in competing browsers seem to be similar to about:home as it is, and the version of about:home that appears in Fennec upon tapping the location bar is basically equivalent to opening the home page, since tapping "X" to close the overlay is much like tapping "back" in the browser to go back to the previous page. 

I think if we were to integrate #425, it would feel fast to open a new tab with the user's home page, but would leave behind the old tab - which is a downside vs. a home button, but I don't really think the home button is all that used or useful - an experiment/data might be useful here.

**Comment by lime124** [comment]
closing - this is done.
