### ISSUE TITLE
customize number of rows in top sites

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17438]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
As compared to collections people are using top sites more as they are easy to access with a single click.. Current problem is the number of rows is restricted to just two.. So in a single view one can have max 8 icons.. Now what if I want more top sites in homepage and I don't want to use collection.. User have no choice! The home screen also has blank space but cannot be utilized/customized as per user need.. 
So please add option to customize number of rows of top sites 
### How do you know that this problem exists today? Why is this important?
Top site is limited to 8 icons in a single view.. Please allow the users to customize number of rows in top sites

### Who will benefit from it?
All users

**Comment by ubrainlessgit** [comment]
Opera browser for mobile has a wonderful top sites/ speed dial  UI which firefox should copy.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/16414

**Comment by eternalbit** [comment]
Maybe the people who decided that 8 top sites on one screen and then swiping to the side for another 8 is the best UI ... maybe these people should be asked to limit the number of apps on one Android homescreen to 8 and be required to swipe to the side all the time ... then maybe they'd be annoyed as well by having such an unnecessary arbitrary limit on an otherwise useful feature.
It's a bit funny/sad how a feature has been needlessly crippled in such a way.
