### ISSUE TITLE
[Bug] The webpage is reloading when clicking the security lock icon 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17457]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open any webpage
Click security lock icon
Page is refreshing or reloading

### Expected behavior
Page should not reload

### Actual behavior
Page is reloading. Probably this bug is introduced after implementation of autoplay option under security lock icon

### Device information

* Android device: ? Rog3
* Fenix version: ? Latest nightly

**Comment by sheikh-azharuddin** [comment]
@Amejia481
Please check this....

**Comment by abodea** [comment]
I was able to reproduce this issue for more details check the following:
The only way to reproduce this issue was to tap on the `security lock` button, the secure connection prompt is displayed, and then lock the device. When unlocking the device the prompt is still displayed but the page in the background is refreshed.
@sheikh-azharuddin is this your issue? 
Note that I tried on: Google Pixel 4 XL (11), Asus Rog 2 (10), Samsung Galaxy S7 (7),  Samsung Galaxy Tab S3 (Android 8) but I couldn't reproduce the issue you mentioned in the description by only tapping on the lock icon. 
@Amejia481 this looks like a very specific issue and somehow intended after unlocking the device.

![20210114_105811](https://user-images.githubusercontent.com/42831109/104574755-0fafe680-565f-11eb-930d-3ed1bf1d1ced.gif)

**Comment by sheikh-azharuddin** [comment]
Nope not just unlocking... On clicking the lock icon it is reloading
It is very much evident in outlook.. In other webpage you will see a flickering.. 

![2021-01-14-16-08-24](https://user-images.githubusercontent.com/58127841/104580411-44ce3000-5683-11eb-92de-58a45bdb3c5f.gif)

**Comment by Amejia481** [comment]
Thanks for the details, @sheikh-azharuddin could you share an screenshot with the about Firefox nightly page?

**Comment by Amejia481** [comment]
@sheikh-azharuddin could you share more details about your devices? Like, brand and Android OS version.

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin could you share more details about your devices? Like, brand and Android OS version.

Attaching the screenshot
Device : Asus Rog phone 3
OS : android 10

![Screenshot_20210114-175114919](https://user-images.githubusercontent.com/58127841/104590321-2a02b800-5691-11eb-9afb-f4d6cce68afe.jpg)

**Comment by abodea** [comment]
I also tried with yesterday's build and on the outlook website, but I couldn't reproduce it.

**Comment by Amejia481** [comment]
The fix has been merged 🎉  in master, lets wait for the QA review.

**Comment by sheikh-azharuddin** [comment]
Issue fixed in latest nightly.... Thanks

**Comment by sflorean** [comment]
@sheikh-azharuddin thanks for the update! I didn't encounter any issue on latest Nightly, as well.
