### ISSUE TITLE
[Bug] Text does not stick in the title

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#17499]
## Steps to reproduce
go to https://mkorostoff.github.io/1-pixel-wealth/
scroll to the right

### Expected behavior
When an informative text appears it should stick for a while here is how it is in Chromium
![Screenshot_20210116-123611_Chromium](https://user-images.githubusercontent.com/922368/104809711-d78fdb80-57f7-11eb-890a-482e7a409557.png)

### Actual behavior
Same scroll pozition in Firefox
![Screenshot_20210116-123602_Firefox_Nightly](https://user-images.githubusercontent.com/922368/104809725-eaa2ab80-57f7-11eb-991a-966745920a17.png)
200 Billion is not visible.

This is a Fenix Nightly regression. It works on Firefox stable, beta and in Firefox desktop.

### Device information

* Android device: OnePlus 5t
* Fenix version: Nightly

**Comment by sflorean** [comment]
@andreicristianpetcu this is still reproducible for you?
Tested on Nightly and Chrome with Samsung Note 10 (Android 11) and wasn't able to reproduce.

**Comment by andreicristianpetcu** [comment]
@sflorean Yes in Nightly but not in Beta or Stable 

https://user-images.githubusercontent.com/922368/120549138-d7395b00-c3fb-11eb-9c82-ea1de1892354.mp4

**Comment by andreicristianpetcu** [comment]
I really don't care about this site and this bug. My concern was that it was going to move to stable and mess up who knows what major sites. Strange that it's not in beta by now. Maybe it's some about:config issue I have.

**Comment by andreicristianpetcu** [comment]
I don't want to mess up my Nightly profile. I was thinking to test with a vanilla ff debug so I can try in a ffresh profile. If it does not reproduce in a ffresh profile, we can close this.

Where can I get a recent debug build? This is 2 months old https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.debug.latest/arm64-v8a

**Comment by SoftVision-LorandJanos** [comment]
This is not reproducible as described, instead there's another issue which is not Firefox specific, as it is the same on Chrome also: a "$200" is displayed with the bottom part cut:
![Screenshot_2021-12-03-08-58-45-551_org mozilla fenix](https://user-images.githubusercontent.com/48829350/144559674-d6b2c366-9981-4bb6-8b7e-e12cc3803951.jpg)

As this issue is not reproducible as described, I will close the ticket.
Verified on the latest Nightly (2021-12-03).
Device used: Xiaomi Mi11 Lite (Android 11).
