### ISSUE TITLE
[Feature China]Requirement of add-on list in China

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#17522]
There's an issue before about this topic #16093
However, we've found that creating a different add-on collection is not the best choice, since we hope that users are able to install and use all the add-ons even if some of them are not in our recommendation list. What we truly care about is we **cannot recommend** some of the add-ons due to some legal reason and we don't want to interfere with users more than that.
So our goal is not creating  a totally different collection with global builds, but just using the same collection and not recommending some of them.
It may involve some modification of android-components. I have modified a-c locally to build a fenix reaching this goal, this can be a start of our discussion: [Filter recommendation add-on list for Mozilla Online builds](https://github.com/MozillaOnline/android-components/commit/d22bd48379155e0db4db44bd036812d79b17b1ea)

**Comment by rxumoz** [comment]
Have updated the example commit according to some suggestions.

**Comment by csadilek** [comment]
@rxumoz Hi, Can you help us understand your requirement a little better? We have a few questions:

- If you filter those specific add-ons from the UI in Fenix (as you did in your commit above), how would users install those other add-ons? Via the AMO website? Note that, on the AMO website, those other installable add-ons are also listed under "Recommended". Only add-ons from the official recommended list can be installed via AMO.

- Where would you want to configure the list of add-ons that are not recommeded but still supported? As part of a build config? Or would you want to fetch them from the server?

- Would it be sufficient to change the name of the section in Fenix instead. So all supported add-ons are not listed under "Recommended", but "Supported" or similar instead?

**Comment by rxumoz** [comment]
@csadilek Hi Christian, we Beijing office now sign and distribute Fenix apks by ourselves using a "MozillaOnline" signature. Thus, we cannot make those add-ons displayed directly in product, no matter what the title called, "Recommended" or "Supported".
We have less concern for now about AMO because it is a website which is not run directly by "MozillaOnline".
So that will basically answer your question 1 & 3.
For question 2, in the long term I think fetch the config from server is a better and agile choice. However, if that is hard to implement in the short run, making it a build config is also good for me.

**Comment by csadilek** [comment]
@rxumoz OK, thanks. Yes, if this is the requirement I agree that filtering some add-ons from the UI in Fenix is the best option short-term. We can't filter from the collection as otherwise AMO installation also wouldn't work.

We'd have to add a `buildConfigField` to `app/build.gradle` that specifies a string array of add-on IDs to exclude e.g. `MOZILLA_ONLINE_ADDON_EXCLUSIONS`, see: https://github.com/mozilla-mobile/fenix/blob/master/app/build.gradle#L29

The change in A-Cs `AddonsManagerAdapter` I would keep generic and instead of passing in a `mozOnline` list, I would pass in a filter function or a generic exclusions lists so this can be re-used.

/cc @st3fan

**Comment by rxumoz** [comment]
Thanks! That will be nice.

**Comment by csadilek** [comment]
@rxumoz OK I've filed a ticket for the required A-C work: https://github.com/mozilla-mobile/android-components/issues/9521 

Since you pretty much already did this in your commit above, would you like to submit a PR for us? The Fenix side (this ticket) is then simply adding the new `buildConfigField` and passing the value to the adapter.

**Comment by rxumoz** [comment]
@csadilek Yes I would like to try to submit the PR next week. Since I don't have the developer access in A-C, I would probably submit the PR from a fork repo.
