### ISSUE TITLE
[Bug] Top address bar unhides when zooming and scrolls page

### ISSUE THREAD

**Issue by Nate-Hawk** [mozilla-mobile/fenix#17595]
Steps to reproduce: Load a website with the top address bar enabled (I tried on GitHub.com, but really just about any website should work). Scroll down so the top address bar auto-hides. Zoom in with a pinch and let go. Zoom out and let go. Repeat several times. Issue should be easily reproducible.

Expected behavior: In the Fennec Firefox Android browser, the address bar would never show when zooming. This is expected as only a scroll up should "pull-down" the address bar.

Actual behavior: Address bar pops down when zooming. This also frequently induces scrolling in the page which should not happen on a zoom operation **(the scrolling is actually the least desirable part of this bug)**.

Device: Samsung Galaxy S10e
Android version: Android 10
Fenix version: 84.1.4

**Comment by Susko3** [comment]
The scrolling probably happens because you release the two fingers used for zooming at different times, thereby performing a scroll gesture (you can see the scrolling in a more controlled way if you zoom, release one finger and then move the other finger that's still touching the screen)

I've tesed raising the two fingers used for zoom at different times in other products to see how it's handled. Chome seems to suffer from the same problem as Firefox, Google Maps just contunes the zoom, but it has fling-like zooming (letting go of the screen continues the zoom, akin to how you can fling to scroll; in Chrome and Firefox, zoom will immediately stop as soon as the fingers are off the screen). Gallery apps seem to suffer from the same fate as Chrome and Firefox.

@Nate-Hawk please try to relase the fingers used for zooming more syncronously and report back.

As for a possible fix, I think adding a slight delay to when fling-scrolling is accepted after performing a zoom gesture is the best way. We don't want to break the current zoom->scroll seamless transition: if you zoom, release one finger, and then try to use your other finger for scrolling, there shouldn't be an arbitrary delay preventing that. With a perfect fix, if you zoom and release the fingers at different times, it should still scroll, but it should scroll for the distance that the late-relase finger was on the screen, and **not** perform a fling scroll (it currently performs a fling scroll). The perfect fix would have the fling scroll on a slight activation delay: eg. allow scrolling, but if the finger leaves the screen within 100ms, don't do a fling.

**Comment by Nate-Hawk** [comment]
I believe this issue has been resolved.
