### ISSUE TITLE
When a tab is selected in Tabs Tray, the content is not entirely visible in RTL

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17616]
## Steps to reproduce
1. Launch Fenix and change the language to RTL (i.e. Arabic);
2. Open 1 or more tabs;
3. Go to Tabs Tray and select 1 or more tabs;
4. Observe the opened tabs after selection;
### Expected behavior
When a tab is selected in Tabs Tray, the content is entirely visible in RTL.
### Actual behavior
When a tab is selected in Tabs Tray, the content is not entirely visible in RTL. Also reproducible in landscape mode.

![20210125_114639](https://user-images.githubusercontent.com/48799384/105689406-650fb180-5f03-11eb-91d8-5c4058b90d18.gif)

### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 1/25, Beta 85.0.0-beta.9, Release 85.1.0-RC.2;

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9495)

**Comment by ItielMaN** [comment]
This isn't strictly an RTL issue, as the same can happen on LTR if the page title is RTL. The solution that I think should be used is to set the alignment of the page title based on the app directionality (but retain the text auto directionalily), if this makes sense.

**Comment by ebalazs-sv** [comment]
I had tested this on Nightly 2/5 with Pixel 2 (Android 9) and on LTR with the page title in RTL, for example https://ar.m.wikipedia.org, the issue is also reproducible.

**Comment by Delphine** [comment]
Perhaps @brampitoyo has an idea or can help redirect this?

**Comment by brampitoyo** [comment]
@Delphine @ebalazs-sv @ItielMaN It seems, on LTR languages, that spacing on the left-hand side are not being applied correctly on some elements. The fix is to apply margin/padding using the dimensions recommended below.

For tab title and address, the left margin/padding should be equal to the right side. (Our value is 16dp).

<img width="360" src="https://user-images.githubusercontent.com/51007/109084461-b2827700-776c-11eb-9353-280fd75a4f84.png">

In the address bar, the left margin/padding between the start of the address bar and the address text, should be equal to the margin/padding between the lock and the address text on LTR languages. (Our value is 8dp).

<img width="720" src="https://user-images.githubusercontent.com/51007/109085553-c7f8a080-776e-11eb-85a4-f8a1b882fa98.png">

What do you think?

**Comment by ItielMaN** [comment]
LGTM!

**Comment by Delphine** [comment]
LGTM too :) thanks!

**Comment by ebalazs-sv** [comment]
This issue is reproducible on RC 87.0.0-rc.1 from 3/17 with Pixel 2 (Android 9).

**Comment by ItielMaN** [comment]
This Is still an issue.

**Comment by ItielMaN** [comment]
The tabs issue is fixed, the URL text isn't.

**Comment by ItielMaN** [comment]
My last comment is still relevant.

**Comment by Delphine** [comment]
RTL behavior has been "broken" here for a while...
This issue has never been looked into although [a solution](https://github.com/mozilla-mobile/fenix/issues/17616#issuecomment-785490687) was suggested.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812885

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
