### ISSUE TITLE
[Bug][L10n] "Select tabs" is not translated in Arabic and Hindi

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17617]
## Steps to reproduce
1. Launch Fenix and change the language to Arabic/Hindi;
2. Open 1 or more tabs;
3. Tap the tab counter;
4. Observe the "Select tabs" from Tabs Tray;
### Expected behavior
"Select tabs" is translated in Arabic/Hindi, both the button and the option from the three dot menu;
### Actual behavior
"Select tabs" is not translated in Arabic/Hindi, both the button and the option from the three dot menu;
![20210125_121055](https://user-images.githubusercontent.com/48799384/105692205-cc7b3080-5f06-11eb-8737-4469f3c0a7c3.gif)
### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 1/25, Beta 85.0.0-beta.9, Release 85.1.0-RC.2;

**Comment by Delphine** [comment]
I wonder if this is related to #17619 🧐

**Comment by Delphine** [comment]
I just checked Arabic and they have localized everything e[xcept a few words on Pontoon](https://pontoon.mozilla.org/ar/android-l10n/all-resources/?tag=fenix&status=missing&string=220223) - and "Select tabs" is not part of them.
I'm not sure what the reason is for this.
Other 100% complete locales have that string translated on device. I asked RelEng if perhaps there had been an issue in automation, but it's not the case.
Perhaps @mcarare might be able to help with this? I honestly have no clue (and this seems related to #17619)

**Comment by mcarare** [comment]
@Delphine I see the string `tabs_tray_select_tabs`  is now translated in Arabic, but not in Hindi. 

If I also look into the strings.xml for Hindi, I do not see the string translated. And it is not translated in Pontoon either, so that is the problem:

Hindi:
https://pontoon.mozilla.org/hi-IN/android-l10n/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=tabs_tray_select_tabs&string=216621

Gujarati:
https://pontoon.mozilla.org/gu-IN/android-l10n/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=tabs_tray_select_tabs&string=216621

**Comment by Delphine** [comment]
Thanks for checking! I couldn't see it translated yesterday :) thanks!
