### ISSUE TITLE
[Bug] "Trackers blocked" dialog shown while ETP off and not aligned

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#17724]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open some sites with trackers while ETP OFF

### Expected behavior
This dialog button aligned with shield and text talks about right thing.
Because of ETP off, this dialog shouldn't shown.
### Actual behavior
Dialog not aligned, text says "shield is purple"
Dialog shown while ETP off.
### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: 86.0.0-beta.1

<img src="https://user-images.githubusercontent.com/17825767/106427503-9266dd00-6478-11eb-978f-ff968b55be41.png" width="33%"/>
<img src="https://user-images.githubusercontent.com/17825767/106427747-f2f61a00-6478-11eb-9532-54fa9e468e85.png" width="33%"/>

**Comment by hakkikaancaliskan** [comment]
I'm using firefox beta frequently but that's shown now, I've never used ETP, just turned on and off on first install. Idk why it's shown now.

**Comment by Mugurell** [comment]
The location looks wrong because the position of the shield actually moves in the layout in the time from the tab and toolbar being created and the page loaded to the page actually being displayed.
To wait just a little bit more and avoid this issue we can replace this line
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionOverlay.kt#L80
`        if (!tab.content.loading && shouldShowTrackingProtectionOnboarding(tab)) {`
to
`        if (shouldShowTrackingProtectionOnboarding(tab) && tab.content.progress == 100 ) {`

Then to not show this popup if etp is off `context.settings().shouldUseTrackingProtection` can be used.

**Comment by sflorean** [comment]
No issues on latest Nightly when ETP is displayed, I will update the labels.
