### ISSUE TITLE
[Feature] Three-dot menu item reordering

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17771]
Meta: #17796

UX point of contact: @violasong (Victoria)

Figma designs (bottom right, labeled "new tab menu"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

## Acceptance criteria
**This work should be behind a feature flag**

* The initial `DefaultToolbarMenu` should be truncated (with the last item partially hidden), with the ability to scroll down to see all menu items
* The menu should be scrollable (followup to expand menu: #17772)
* The menu should include the following items (top to bottom):
  * 🆕 New tab
  * Bookmarks (followup with Add/Edit ⭐ button: #17797)
  * History
  * Downloads
  * Extensions (this should take them to the addons list. Followup: #17799)
  * Sign in to sync OR Synced tabs (followup: #17798)
  * Find in page
  * Desktop site
  * Add to Home screen
  * Add to top sites
  * Save to collection
  * Settings
* The menu should have separating lines in the correct places (see designs)

---

**Old design** (left) vs **new design** (right)
<img width="302" alt="image" src="https://user-images.githubusercontent.com/43795363/106947041-833d9480-66ef-11eb-99b5-898c3e5e5f3c.png">  <img width="302" alt="image" src="https://user-images.githubusercontent.com/43795363/106665120-8c9df400-656b-11eb-896b-2b430c1e787f.png"> <img width="302" alt="image" src="https://user-images.githubusercontent.com/43795363/106947292-ca2b8a00-66ef-11eb-8687-05d4a7bda1dc.png">

**Comment by mailinglists35** [comment]
I need the navigation button instead of the site tracking protection button.

I tap the navigation button every day, but never the site protection button.

Please move out the site protection button into the menu and place the navigation buttons (at least back and reload) straight into the bottom bar.

I don't think Mozilla is going in the right direction, look at how giants like Google, Microsoft and Apple have designed their back navigation bottom button in Chrome, Safari and Edge. I don't think they just all happen to do it similarly by coincidence, did they?

It would be much much more useful to have the back, reload, find in page and addons buttons in the bottom bar, since I use them most frequently - Noscript addon is an absolute must in this world of continuous spying on personal data so using it is a pain in the current design with one difficult tap to hit the three dots menu then a painful tap to access the addons menu far far away from the reach of my hand.

**Comment by mailinglists35** [comment]
also wasted space between the padlock and the url. 
![Screenshot_20210210-024722~2](https://user-images.githubusercontent.com/2054302/107448513-7800c380-6b4a-11eb-87c9-fcdebcc7f8d0.png)

**Comment by eliserichards** [comment]
This does not need QA as it is only a piece of the whole change. We should test when the full feature is done.
