### ISSUE TITLE
Mobile: Dark Reader extension lags loading pages

### ISSUE THREAD

**Issue by phillipkramer** [mozilla-mobile/fenix#17882]
## Steps to reproduce
Turn on Dark Reader extension, open 5 tabs on various websites, search a site on a 6th tab, click on link
### Expected behavior
The page should load like normal
### Actual behavior
The page lags, does not load, or goes back to search page
### Device information
Galaxy J3 Luna Pro
* Android device: Yes
* Fenix version: Nightly 210205 17:58

**Comment by mpaunovic** [comment]
It happens with the stable Fenix version too. Pages load 3-4 times slower if Dark Reader is enabled.

I cannot wait for Dark Background and Light Text to be included in Fenix, it's far less resource intensive and it doesn't slow page loading.

**Comment by mcomella** [comment]
Triage: we've previously investigated our add-ons infrastructure https://github.com/mozilla-mobile/fenix/issues/17448#issuecomment-764875262 and have noticed no performance problems with our code. Unfortunately, if a specific add-on has a performance issue, they may slow down the browser but we have little control over it because it's not our code. We believe that's what's happening here so **please refile this issue against the Dark Reader repository**. Since there's nothing for us to do here, I'm going to close the issue. If you believe this is an error, please reopen.

Somewhat related, see also https://github.com/mozilla-mobile/fenix/issues/16473 where we discovered performance issues with ublock on first page load.

**Comment by mcomella** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/14788 – we've known about Dark Reader performance issues for a little while so we're considering notifying users when an add-on is behaving poorly.
