### ISSUE TITLE
[Bug] Captions not showing in fullscreen mode. 

### ISSUE THREAD

**Issue by Japeskie** [mozilla-mobile/fenix#17895]
Re-opening because I think this is not the same as issue #8252. Attached a video to show that the **video is still at the same aspect ratio and not zoomed in** prior to entering fullscreen mode and yet the captions are disappearing everytime I enter fullscreen mode.

https://user-images.githubusercontent.com/73644544/107177570-17b83780-6a0d-11eb-9d26-1c51b5bfaf81.mp4

You can see the same line at the foot on the bottom part of the video and same the creases at the top part of the video on both fullscreen mode and not.

## Steps to reproduce

1. Watch any video and enable captions.
2. Go fullscreen mode.

### Expected behavior

Captions will still show in fullscreen mode.

### Actual behavior

Captions disappearing in fullscreen mode, but will show when you exit fullscreen mode.

### Device information

* Device vendor / model and Android version: Mi 9T Pro / MIUI 12
* Firefox for Android version: Nightly (Build #2015791019)

**Comment by Mugurell** [comment]
Thank you for the report!
After testing a bit this seems to be related to the screen ration.
On a Pixel3 with a 18:9 ratio the captions appear as expected but on a OnePlus7T with a 20:9 ration I don't see the captions.
I see your device also having a 19.5:9 ratio so this might explain it.
Moving the ticket to Bugzilla since this is about video playing in the browser.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1691334

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
This should be fixed in the current Nightly.
