### ISSUE TITLE
[Bug] Firefox does not appear as option on "View on Web" from Flipboard

### ISSUE THREAD

**Issue by billbeckner8** [mozilla-mobile/fenix#17963]
I am a happy user of Firefox on my Android phone.  Firefox is set as my default browser.  However, until recently, when I am using Flipboard and I want to view the page in my browser, Chrome pops up instead of Firefox.   This does not occur within other Apps (Reddit, etc.) - FireFox pops up as expected.

I reported this issue to the Flipboard developers and they believe that a recent change to Firefox broke this functionality. Can you please help resolve this issue?

Thanks in advance for your help!
Bill Beckner 

* Device vendor / model and Android version: LG V40 ThinQ Android 10
* Firefox for Android version: 85.1.3 (Build #2015792283)

**Comment by effinG123** [comment]
Thought it was just me.  Clearing defaults didn't help.  It's as though flipboard doesn't recognise Firefox as a browser (chrome and Edge are the only options that show up)

**Comment by amedyne** [comment]
Tried experimenting and setting different browsers.
From Flipboard, select "View on Web", 
- For following browsers: Chrome, Opera, Brave, the user is prompted to select a browser instead of opening the article with the users default browser.
- For Firefox, DuckduckGo, the option/prompt to select a browser doesn't even appear. It opens Chrome by default.

**Comment by Mugurell** [comment]
We'd have to get more data about what Intent Flipboard uses.

**Comment by Mugurell** [comment]
I see the Flipboard Intent having the following structure:
> action: "android.intenit.action.MAIN"
categories: ["android.intent.category.LAUNCHER"]
selector: 
>   - action: "android.intent.action.MAIN"
>   - categories: ["android.intent.category.APP_BROWSER"]
>
> data: <uri_to_load>

The important part here being the category used in the selector. We don't have any activity with this category set.

**Comment by ebalazs-sv** [comment]
This issue is still reproducible with the following builds installed:
- Nightly 3/4;
- Beta 87.0.0-beta.2 from 3/1;
- Release 86.1.1 from 2/23.

On Flipboard, when going to "View on Web", only the following browsers are displayed: Chrome, Chrome Canary and Opera.

Installed apps: Chrome, Chrome Canary, Opera, Firefox Nightly, Firefox Preview, Firefox, Firefox Beta, Firefox Focus.

Uninstalling Opera, only Chrome, Chrome Canary are displayed when using "View on Web". Furthermore, disabling Chrome and uninstalling Chrome Canary, when using "View on Web", the error message "No application found to complete this action." is displayed.

I tested this with no default browser and with Firefox Nightly set as default.
Device: Pixel 2 (Android 9).

**Comment by Mugurell** [comment]
Thank you Eliza and sorry for the false alarm.
This was not really ready for test.
I just now merged the patch for it so it should be ready to test only in the next Nightly.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 3/7 with LG G7 Fit (Android 8.1).
