### ISSUE TITLE
Add more detail to Ad Click Metrics

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#18036]
In `AdsTelemetry` we currently recognize clicked ads and reports those all as `SearchAdClicked` event that just have the `providerName`.

https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/main/java/org/mozilla/fenix/search/telemetry/ads/AdsTelemetry.kt#L37

We need to add more detail to these metrics, in a similar way that is done as in `InContentTelemetry`:

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/search/telemetry/incontent/InContentTelemetry.kt#L51

This should also include the `channel` that we introduced for Top Site Tile work.

The exact format of the event is TBD and needs to be worked out with Data Science.

**Comment by st3fan** [comment]
Asking @Standard8 for feedback.

**Comment by mconnormoz** [comment]
Chiming in here, the full, specific ask here would be to construct the same TrackKeyInfo (name/type/code/channel) as the in-content search probes.   We want to be able to compare searches/ads/clicks by the same set of attributes, including organic.

**Comment by Standard8** [comment]
Here's what we use for desktop: https://firefox-source-docs.mozilla.org/browser/search/telemetry.html#search-probes-relevant-to-front-end-searches

The `SEARCH_COUNTS` histogram records visits to pages, with key format `<provider>.in-content:[sap|sap-follow-on|organic]:[code|none]`
`browser.search.withads.*` and `browser.search.adclicks.*` scalars record the pages with ads and their associated clicks.

Note for the new scalars, we went with `<provider>:<tagged|organic>` for the key - i.e. using `tagged` rather than `sap`. This is different to `SEARCH_COUNTS` but we considered it clearer for engineering purposes.

The `browser.search.withads.*` scalars are split into search access point (SAP). You could possibly do something similar here with the top site tile being a SAP?

**Comment by lobontiumira** [comment]
I tried verifying this ticket but didn't get to any results generating metrics on the 3/16 Nightly build using a Google Pixel (Android 10). I've asked @gabrielluong for more details, and I will get back to testing as soons as I have them.
Untill further notice, I'll remove the qa:needed label.

**Comment by sflorean** [comment]
@gabrielluong any updates here? Thank you!

**Comment by AndiAJ** [comment]
Hi @gabrielluong , I've just checked this matter having **Google** set as my default search engine on the latest **`Nightly 91.0a1 from 5/10`** using a Google Pixel 3a (Android 11)

Metrics Ping: **fa6ad9cb-7e86-4f41-9d7b-87b53723c458**

```
"labeled_counter": {
          "browser.search.ad_clicks": {
            "google.in-content.organic.none": 1,
            "google.in-content.sap-follow-on.firefox-b-m": 1,
            "google.in-content.sap.firefox-b-m": 1
          }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t10050)
[Logcat](https://github.com/mozilla-mobile/fenix/files/6450986/mtrx.txt)

Please review and share your thoughts. ☺️ 

Also, please let me know if I should also check for the other search providers as well ?
If yes, could you please confirm if we record the **`search.ad_clicks`** only for these 3 search providers? 
• Google
• Bing
• Duckduckgo

Noticed that only these 3 were used in [#6558](https://github.com/mozilla-mobile/fenix/issues/6558#issuecomment-621316431)
