### ISSUE TITLE
Use AwesomeBarFacts for AwesomeBar Telemetry

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#18068]
Collect Awesome Bar facts to be included in the Glean report.

**Comment by rocketsroger** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/14866

**Comment by lobontiumira** [comment]
Hi all!
I've verified on the 3/15 Nightly build with Google Pixel (Android 10), and here are my findings:
* ping: e022beea-dba6-4d52-b870-1e505ad01ba8
* bookmark_suggestion_clicked event was generated:
 ```
 {
          "category": "awesomebar",
          "name": "bookmark_suggestion_clicked",
          "timestamp": 13776
        }
```
* opened_tab_suggestion_clicked event was generated:
```
 {
          "category": "awesomebar",
          "name": "opened_tab_suggestion_clicked",
          "timestamp": 28030
        }
```
* and history_suggestion_clicked was generated:
```
{
          "category": "awesomebar",
          "name": "history_suggestion_clicked",
          "timestamp": 18918
        }
```
* search_action_clicked was generated when tapping on the mirrored searched term:
```
 {
          "category": "awesomebar",
          "name": "search_action_clicked",
          "timestamp": 3170
        }
```
I was not able to generate the following events:
* clipboard_suggestion_clicked,
* search_suggestion_clicked.

However, @Mugurell has more details about why these events are not generated. Thank you so much!

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/6141209/logcat.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-210315005)

**Comment by Mugurell** [comment]
I looked with Mira over those two facts, why they are not logged and found:
- `clipboard_suggestion_clicked` is not logged because Fenix used it's own "fill with clipboard" functionality (not from AC) that will [not result in any telemetry event](https://github.com/mozilla-mobile/fenix/blob/a4691675a1e3a8c8ac049012d974a1f595a073e6/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#L272-L281)
- `search_suggestion_clicked` is not logged because this Fact is emitted only from [singleSearchSuggestion](https://github.com/mozilla-mobile/android-components/blob/0526597602dea330ac28f6539ee95f3894b1bffd/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt#L201-L227) and Fenix uses another implementation  configured with `SearchSuggestionProvider.Mode.MULTIPLE_SUGGESTIONS` [here](https://github.com/mozilla-mobile/fenix/blob/a4691675a1e3a8c8ac049012d974a1f595a073e6/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt#L152-L163) and [here](https://github.com/mozilla-mobile/fenix/blob/a4691675a1e3a8c8ac049012d974a1f595a073e6/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt#L338-L347) so using [`multipleSearchSuggestions`](https://github.com/mozilla-mobile/android-components/blob/0526597602dea330ac28f6539ee95f3894b1bffd/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt#L129-L139).

**Comment by rocketsroger** [comment]
@Mugurell Thanks for the investigation.  I'll look into this.

**Comment by rocketsroger** [comment]
@Mugurell Thanks for spending time on this.  I've confirmed both your observation is correct.  I'll add changes so the missing events are tracked correctly.

**Comment by rocketsroger** [comment]
Waiting for https://github.com/mozilla-mobile/android-components/pull/10031 to merge.

**Comment by rocketsroger** [comment]
Nightly have the latest fix.  Please verify, Thanks!

**Comment by abodea** [comment]
Hello verified as fixed on the latest **Nightly 4/19** with **Google Pixel 4 XL (11).**
 ```
 {
          "category": "awesomebar",
          "name": "bookmark_suggestion_clicked",
          "timestamp": 13776
        }
```
* opened_tab_suggestion_clicked event was generated:
```
 {
          "category": "awesomebar",
          "name": "opened_tab_suggestion_clicked",
          "timestamp": 28030
        }
```
* and history_suggestion_clicked was generated:
```
{
          "category": "awesomebar",
          "name": "history_suggestion_clicked",
          "timestamp": 18918
        }
```
* search_action_clicked was generated when tapping on the mirrored searched term:
```
 {
          "category": "awesomebar",
          "name": "search_action_clicked",
          "timestamp": 3170
        }
```
* clipboard_suggestion_clicked was generated when tapping on a copied suggestion:
```
 {
          "category": "awesomebar",
          "name": "clipboard_suggestion_clicked",
          "timestamp": 106950
        }
````
*search_suggestion_clicked was generated when tapping on a search suggestion:
```
{
          "category": "awesomebar",
          "name": "search_suggestion_clicked",
          "timestamp": 13029
        }
```
