### ISSUE TITLE
[Bug] "Save file to device" option is not available in custom tab for mp4 & webm videos

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18075]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Set Fenix as default browser.
2.  Open https://file-examples.com/index.php/sample-video-files/sample-webm-files-download/ in a custom tab.
3. Select a video and perform a long press (on the video) in order for the context menu to be displayed.
4. Select "Save file to device" from the context menu.

### Expected behavior
The file is downloaded after the option is selected.

### Actual behavior
The option is not available.

### Device information
* Device vendor / model and Android version: Pixel 3 (Android 11), Samsung Note 10 (Android 11), LG G7 FIT (Android 8.1.0).
* Firefox for Android version: Nightly 2/19, Beta 86.0.0-b5, Fenix 86.1.0.
 
<img src="https://user-images.githubusercontent.com/58466444/108490845-de54b700-72ab-11eb-94de-49cb68bae2dc.jpg" width="300" height="550" />

**Comment by mcarare** [comment]
This would be a simple fix: https://github.com/mozilla-mobile/fenix/pull/18077, but I am wondering why the context menu is so different in custom tabs. Is it just overlooking adding new candidates or is this intentional?

I do not see any mention of custom tabs in the original issue: https://github.com/mozilla-mobile/fenix/issues/3703.

@rocketsroger or @Amejia481 Do you have more info on this specific issue or in general for the context menu in custom tabs?
Is this something UX or product should look into?

**Comment by sflorean** [comment]
Verified as fixed on 87.0.0-beta.1 and latest Nightly build. Save file to device option, is displayed when using custom tab.
