### ISSUE TITLE
Handle locale changes for all notifications

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18117]
Currently, Fenix is handling the creation of every notification in a different way. _Insert PR here for #17190_ implements an interface in AC in order to register for locale updates. This should be implemented by every notification in the app so that we are consistently handling locale changes.

CC: @Amejia481 for more context

**Comment by Amejia481** [comment]
As we create notifications in many different components and parts of Fenix and AC, we need a generic way to observe language changes and notify to components that notifications need to be refreshed for the new language. 


We could introduce a global state [BrowserState](https://github.com/mozilla-mobile/android-components/blob/1e1b2162a9046ffae3ce776c74d0e0b5f8c75e28/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt#L31) for the application locale.


```kotlin
data class BrowserState(
    val tabs: List<TabSessionState> = emptyList(),
    val closedTabs: List<RecoverableTab> = emptyList(),
    val selectedTabId: String? = null,
    val customTabs: List<CustomTabSessionState> = emptyList(),
    val containers: Map<String, ContainerState> = emptyMap(),
    val extensions: Map<String, WebExtensionState> = emptyMap(),
    val activeWebExtensionTabId: String? = null,
    val downloads: Map<String, DownloadState> = emptyMap(),
    val search: SearchState = SearchState(),
    val undoHistory: UndoHistoryState = UndoHistoryState(),
    val restoreComplete: Boolean = false,
    val local: Locale? = null
) : State 
```

And every component or feature that usage notifications could observe that property and every time it changes then they should update notifications.

**Comment by Amejia481** [comment]
You will also need to update `LocaleManager` to dispatch an action the global value

**Comment by Mugurell** [comment]
@Amejia481 I would argue that application locales - used for the app ux, notifications etc don't really have to do with the browser state where I see tabs, extensions, etc. and we should strive to have a clear separation between app and browser state.

I think we already have the currently selected language in AC:
- Whenever the system language changes the AC `LocaleManager` gets called to update the configuration (following the app receiving `onConfigurationChanged`)
- Whenever app language is changed (from app settings) the AC `LocaleManager` gets called to update the configuration (following Fenix - `DefaultLocaleSettingsController` -> `handleLocaleSelected`)

So the current language (from the system / overriden by the app) is already available in the LocaleManager object which can allow for a list of listeners..? Or if it wants to update a State that can be observed maybe AC would need to have a new `AppState` that would include `LocaleState` and `BrowserState` for the start.

**Comment by Amejia481** [comment]
> So the current language (from the system / overriden by the app) is already available in the LocaleManager object which can allow for a list of listeners for changes..? Or if it wants to update a State that can be observed maybe AC would need to have a new AppState that would include LocaleState and BrowserState for the start, with other particular states to be added later?

Thanks for your comment, the idea is to expose the locale that we have on `LocaleManager` via `BrowserState` (AppState) to ease sharing with other components or other parts of the app. We want to keep in sync the value on `LocaleManager` with `BrowserState` (AppState) every time that the value change on `LocaleManager` it will get updated on `BrowserState` this way other parts of the app that maybe interested on language changes just have to observe the `BrowserState` as this is the same pattern that we use to share data across component and other parts of the app.

To clarify, everything that is on the top of `BrowserState` object is considered `AppState`, as this info is per application.

**Comment by Amejia481** [comment]
Basically you will need to do four changes:

* Add a locale property on the [BrowserState](https://github.com/mozilla-mobile/android-components/blob/1e1b2162a9046ffae3ce776c74d0e0b5f8c75e28/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt#L31), this way you will have a centralized point, for components and other parts of the app that are interesting in observing locale changes (For refreshing notifications).  
* Update the [LocaleManager.setNewLocale](https://github.com/mozilla-mobile/android-components/blob/69a800e47330561f11addad4db6da010694c5ee6/components/support/locale/src/main/java/mozilla/components/support/locale/LocaleManager.kt#L33) to have the store a parameter, then you could dispatch an action to update the `locale` value in the store.
* You will need to create a feature to observer system OS locale level changes and update the locale property on the [BrowserState](https://github.com/mozilla-mobile/android-components/blob/1e1b2162a9046ffae3ce776c74d0e0b5f8c75e28/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt#L31). Keep in mind that changes to the OS level only can be only apply when a `LocaleManager` is following the system default, otherwise these changes should be ignored.
* Observe the locale property on the [BrowserState](https://github.com/mozilla-mobile/android-components/blob/1e1b2162a9046ffae3ce776c74d0e0b5f8c75e28/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt#L31) to refresh notifications when it changes,  [here](https://github.com/mozilla-mobile/android-components/blob/1e1b2162a9046ffae3ce776c74d0e0b5f8c75e28/components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationService.kt#L94) you could find an example of observing store properties.
