### ISSUE TITLE
FNX-5265 ⁃ [UX] Quick Action Bar

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#182]
Update 3/21 - Need to remove Screenshots from QAB and Library and notify engineering

**User Story:**
As a user I want easy access to common functionality for using the information I find on the web.

**Current Design Status:**

* In Good Shape
* Foundational Design Done
* Needs more design detail work

**Design Priority:**
P1

**Mockups:**
https://mozilla.invisionapp.com/share/Y5Q1NM7VMN9#/341653120_Quck_Action_Bar

**Comment by shorlander** [comment]
**User Story:**
As a user I want easy access to common functionality for using the information I find on the web.

**Current Design Status:**
- In Good Shape
- Foundational Design Done
- Needs more design detail work

**Design Priority:**
P1

**Mockups:**
https://mozilla.invisionapp.com/share/Y5Q1NM7VMN9#/341653120_Quck_Action_Bar

**Comment by bbinto** [comment]
This is only the animation and UI, no functionality for screenshots etc needed.

@colintheshots can this be pulled into milestone 1?

**Comment by sblatz** [comment]
Eitan mentioned an accessibility note (for when we implement this--just don't have an engineering ticket right now):

The custom gesture we use to activate the quick action menu will require some extra work to support TalkBack since all gestures are redirected when it is enabled.

**Comment by boek** [comment]
@colintheshots Do we still want to talk about a single actionsheet?

**Comment by colintheshots** [comment]
Yes, I like the idea of a single actionsheet. I have mixed feelings about leaving half of the buttons revealed with a tiny drawer handle. If it were me, I'd make the handle bigger, use a touch delegate to make it bigger still, and bounce the sheet briefly so the user knows the buttons are there. Affordances aren't usually easy or obvious and I won't pretend to have the answers.

**Comment by shorlander** [comment]
> Yes, I like the idea of a single actionsheet. I have mixed feelings about leaving half of the buttons revealed with a tiny drawer handle. If it were me, I'd make the handle bigger, use a touch delegate to make it bigger still, and bounce the sheet briefly so the user knows the buttons are there. Affordances aren't usually easy or obvious and I won't pretend to have the answers.

@boek @colintheshots do you mean having the browser toolbar and the quick actions on the same sheet?

**Comment by boek** [comment]
@shorlander Yep! I I think the main concern with how many touch targets there would be at the bottom of the phone. I have no problem problem implementing the current design so we can test it out and iterate based on feedback :)

**Comment by colintheshots** [comment]
FYI, we now have an experimentation setup to A/B test layouts. We can even try multiple versions.

**Comment by shorlander** [comment]
That sounds great! There are several different versions we could try. If we can start with this one I can also post some of the other ideas. Is that a enough to get started and for me to close this?

**Comment by shorlander** [comment]
[share-and-readermode-svg.zip](https://github.com/mozilla-mobile/fenix/files/2985998/share-and-readermode-svg.zip)

**Comment by mheubusch** [comment]
@lime124 note that we need to reopen this, update designs to remove Screenshots from QAB and Library and notify engineering

**Comment by sblatz** [comment]
For reference, this is what I have implemented right now:

Notes: 
1) I took the liberty of adding a fun "bounce" animation. This automatically plays the first **two times** a user enters the browser view to give the user some idea what's behind the pull tab. 
2) A shorter, less pronounced "bounce" animation plays when a user **taps** the grab handle to indicate to them that they must swipe up in order to activate it.
3) The pull tab itself does not have to be touched in order to pull up the sheet. Instead, a user can swipe anywhere from beneath the tab to start revealing the quick action sheet, this makes it so that users don't have to press a tiny touch target in order to get the menu.
4) If a user has a screen reader active, the quick action bar will always stay open and will not collapse even when the user scrolls (just like is the behavior of the toolbar currently)

Let me know if we don't want the animation as a discoverability tool or if you'd like me to change any of the design.

![tab grab](https://user-images.githubusercontent.com/4400286/54765642-1b433b00-4bb7-11e9-9cb6-a2f5c3c24679.gif)

**Comment by eeejay** [comment]
>     4. If a user has a screen reader active, the quick action bar will always stay open and will not collapse even when the user scrolls (just like is the behavior of the toolbar currently)

I don't think that would be the desired behavior. It takes up an nontrivial amount of screen space.

I think this should work similar to the app drawer in the home screen. There is a little arrow that appears when TalkBack is on. It becomes focusable with the cursor. Double tapping it opens the app drawer. We don't even need to add a special widget for TalkBack users since it looks like we have a little pull tab already.

![image](https://user-images.githubusercontent.com/5764/54768496-817e8c80-4bbc-11e9-992e-f78fa9d01c7f.png)

Note, a TalkBack user can use a two finger swipe which passes through to the app as a one finger swipe. So in the app drawer case, a familiar user would know they can do a two finger swipe in the bottom fourth of the screen as a shortcut. This should be considered a power-move and not be the expected way for users to do this, since it requires dexterity and is not discoverable.

Here is an example:

![image](https://user-images.githubusercontent.com/5764/54768857-59dbf400-4bbd-11e9-8914-ba2809a5e912.png)

**Comment by sblatz** [comment]
Thanks for raising these points, @eeejay! I am addressing them [here](https://github.com/mozilla-mobile/fenix/issues/1127)

**Comment by colintheshots** [comment]
I like the concept and I'm glad to see it working.

In practice though, the handle while collapsed is too small and very difficult to swipe up properly. It's even worse when the URL bar is offscreen because newer Android versions have the task manager on swipe up and it's really not possible to tell that there's a quick action bar there. On Focus multitasking v2, we used a small handle tab in the middle of the screen to increase the touch area and the user's knowledge that it was there. There must be a number of ways to solve the issue.

**Comment by sblatz** [comment]
@shorlander @lime124 do we want this show in custom tabs as well?

**Comment by lime124** [comment]
@brampitoyo ^

**Comment by brampitoyo** [comment]
@sblatz @shorlander @lime124 
> do we want this show in custom tabs as well?

Sorry for the overdue reply!

Yes. I think that the Quick Action Bar should appear on the Custom Tabs, because “Share”, “Favorite” and “Read” are all helpful actions to have when you open a third-party website.

I think that “Download” also has a place if you want to save pieces of information on the page to access later.

Custom tab app bar will be shown on top of the screen, so we’ll show the Quick Action Bar below it.

Thoughts, @shorlander?

**Comment by shorlander** [comment]
> Thoughts, @shorlander?

Yes, I agree. It's one of the pieces we discussed bringing into Custom Tabs to make it easier to access this functionality without leaving the Custom Tab.

**Comment by yoasif** [comment]
>I think that “Download” also has a place if you want to save pieces of information on the page to access later.

This is really weird - I thought "Download" was going to be a list of downloads (which I guess doesn't make a hell of a lot of sense to appear as a quick action on every page, but...).

The way you make it sound, Download is something more like a "take a screenshot" on desktop or "Save". 

Either of those would be far less confusing if the "Download" button isn't just a list of Downloads.

**Comment by yoasif** [comment]
@sblatz Okay well in that case, I'm not sure that "Download" is really the right label for this button then -- it isn't like the corresponding feature in Firefox desktop is called that (it is called "Save" or "Take a Screenshot" if that is the feature). In Fennec, it is called "Save as PDF" (not sure what format the save will save as). 

Is "Downloads" in the Library meant to show these saved pages, or is it meant to show traditional file downloads (or both?)? 

Fennec and Firefox desktop both show all downloads (saved pages, links, and other files) in the download lists. 

Just wondering what this feature ultimately looks like and whether Downloads is the best label - the Firefox screenshotter in desktop ran into some amusing controversy with a button labeled "Save" that uploaded to the cloud, upending notions of what "Save" meant, so I think labels matter.

**Comment by lime124** [comment]
reopening to cover the work @apbitner is doing for the usability testing.

**Comment by lime124** [comment]
blocked - we need #1718 fixed to proceed with our study

**Comment by apbitner** [comment]
QAB UserTest Analysis: https://docs.google.com/document/d/1vnP-ts8l6IAyTtWi99ukRi0ho6TkZlyrQMlHuIr57eg/edit?usp=sharing

**Comment by vesta0** [comment]
@apbitner thank you for sharing the QAB research! I just reviewed and saw your recommendations:

_Consider having share and bookmark functionality only in the QAB once discoverability is improved; or, have share and bookmark functionality in both the QAB and toolbar menu, until users get accustomed to the QAB_ ==> have we improved QAB discoverability enough to remove Share from 3 dot menu, or are you recommending to add bookmark to the 3 dot menu? 

cc @mheubusch @shorlander

**Comment by apbitner** [comment]
We did make some small adjustments to how we display the sneak peek of the QAB in hopes of making it more discoverable. I think we should keep an eye on Telemetry data to determine whether further testing is needed. Also, as noted in the analysis, participants really struggled with adding a bookmark, however, I haven't been seeing complaints in the Google Group feedback so hopefully that means they are indeed using the QAB to add a bookmark.

**Comment by vesta0** [comment]
I really worry that even with the adjustments in the QAB sneak peak, bookmarks add button is still hidden. Users may not remember seeing the QAB until they need to add a bookmarks and then they will search in settings. I agree with @apbitner 's suggestions of monitoring this for MVP but I recommend starting to think about an alternative solution so we can act fast once we need it.
