### ISSUE TITLE
[Bug] getpocket German reading suggestions never came back under fenix

### ISSUE THREAD

**Issue by sonora** [mozilla-mobile/fenix#18215]
After the cutover to fenix with Firefox for Android version 79, the former fennec getpocket reading suggestions have never come back under fenix, not even as an Add-in, I think.

I believe the **German language** pocket reading suggestions were once somehow loaded via https://getpocket.com/explore?de.

But now it seema to me that there is currently no way at all to receive the reading suggestions in German language under fenix, as even the above link seems to produce only English content?

**Comment by kbrosnan** [comment]
Checked with the Pocket people and they don't have a way to tailor the Explore page by language. Though it is something that they have interest exploring in the future.

On the Fenix side we have https://github.com/mozilla-mobile/fenix/issues/6416 for bringing back a fennec style explore page. That issue is on hold until we sort out the home page behaviors and interactions with new tabs.

**Comment by sonora** [comment]
@kbrosnan Thanks for your research!

It seems hard to believe  Pocket cannot provide a language-specific URL pointing to their content, which would provide an interim workaround for so many users suffering from this issue. (And/or could even pave the way to create a rudimentary fenix Add-on.)

Maybe if they do ever get around to publish such a URL someone could publish it hee as a temporary solution for this issue.
