### ISSUE TITLE
[Bug][l10n] Some menu options are not translated to Frysk - Western Frisian

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18233]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Change language to Frysk - Western Frisian.
2. Open a page and check the menu. 

### Expected behavior
The strings is translated to Frysk - Western Frisian. 

### Actual behavior
All the entries are translated, including Downloads, Add-ons, Report site issue. 

### Device information
* Device vendor / model and Android version: Samsung Note 10 (Android 10)
* Firefox for Android version: Nightly 3/1, 87.0.0-beta.2
 
<img src="https://user-images.githubusercontent.com/58466444/109525696-775cac80-7aba-11eb-8d68-1ab74a7686b5.jpg" width="300" height="550" />

**Comment by Delphine** [comment]
@escapewindow: I see both strings "add-ons" and "downloads" could either be in android-components or Fenix (can't tell from the issue) - but either way, both strings have been localized for many months now in Frisian (fy-NL).
(I know "report site issue" is ok to see in English, because it's not part of release)
Do you have any idea if there is an issue somewhere getting a-c or Fenix strings for that locale into Nightly? They are at 100% completion so I don't understand where this could be coming from 🤔

**Comment by escapewindow** [comment]
Aiui the update-projects hook should get all missing strings into Fenis and Android-Components. I reran the [update-projects hook](https://firefox-ci-tc.services.mozilla.com/hooks/project-releng/cron-task-mozilla-l10n-android-l10n-tooling%2Fupdate-projects), which created https://github.com/mozilla-mobile/android-components/pull/9842 and https://github.com/mozilla-mobile/fenix/pull/18374 . Neither appear to have new fy-NL strings, so I'm not sure what's going on here.

**Comment by Delphine** [comment]
So I checked on Pontoon how these were translated, and I realized that they have decided to keep those words in English (Dutch apparently often re-uses English terms).
Therefore closing this bug.
