### ISSUE TITLE
Handle duplicates when adding or updating a credit card

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18275]
When an user is adding or updating a credit card, we should handle the case where the entered credit card to be saved turns out to be a duplicate. 

This issue is to handle any error messaging to display when the entered credit card to be added turns out to be a duplicate. 

<img width="353" alt="Screen Shot 2021-03-02 at 4 14 41 PM" src="https://user-images.githubusercontent.com/1190888/109717762-7be59b80-7b74-11eb-9a02-7b4181bbf913.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9894)

**Comment by violasong** [comment]
Just checked and it appears Desktop doesn't handle this. I agree it's important though :) 

I think after the user enters the full duplicate number, we can show this error with the same placement as in the mockup: "This card number has already been added."

**Comment by mcarare** [comment]
@violasong, @vesta0 While implementing this, a comment about an edge case with syncing cards made me wonder if we really want to not allow duplicate card numbers. 
The point is that if we allow duplicate numbers to be saved on desktop and then we sync cards between devices, what would be the point of not allowing duplicates to be saved from mobile, because we would already have duplicates in the card list. 
There also is the point of aligning with desktop behavior. 

Note: In other mobile browsers that I tested they allow adding duplicate card numbers, the only constraint is not adding a card that has all the fields the same as an existing one (name, nickname, etc).

**Comment by mhammond** [comment]
For better or worse, I think it is important we have the same restrictions as desktop. Otherwise we will end up in the situation where a card synced from desktop can't be edited on Fenix, which would be very confusing for the user. I wasn't aware desktop allowed that - assuming we go ahead with this, I think we will need an application-services issue to help relax things.

**Comment by gabrielluong** [comment]
@mcarare pushing this to 91.

**Comment by mcarare** [comment]
Waiting for a decision for choosing if we still want to implement this, considering the comments above. Thanks to @mhammond for also pointing out potential issues.

**Comment by gabrielluong** [comment]
From our discussions, we're in a product requirement scoping phase around handling duplicates. When product determines how this should behave, we will look to see how we should go about it between AS and Fenix since there has been some thoughts about AS implementing the functionality to check for duplicates. 

I will remove this from the kanban board for now since it's not ready.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813626

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
