### ISSUE TITLE
Try to reproduce tab unloading behavior with ublock

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18321]
In https://github.com/mozilla-mobile/fenix/issues/17005#issuecomment-790178643, we said we should check to see if ublock can be the trigger for that bug. Let's find out.

**Comment by ebalazs-sv** [comment]
I had tested this issue on the latest Nightly 3/10 with Motorola Moto G6 (Android 8) and could not reproduce it with the steps from https://github.com/mozilla-mobile/fenix/issues/17005.

This issue is reproducible after closing and reopening the app, with or without add-ons installed, the tabs are reloading.

**Comment by mcomella** [comment]
Thanks ebalazs-sv! I'm going to close this as a dupe to #17005 now.
