### ISSUE TITLE
[Bug] install/add to homescreen sometimes fails

### ISSUE THREAD

**Issue by jeannenot** [mozilla-mobile/fenix#18377]
Firefox pour Android version 86.1.1
Mobile : Xiaomi 9T pro modèle M1903F11G
Version Android : 10QKQ1.190825.002
Je sollicite votre aide votre menu propose l'option d'ajouter un site web sur l'écran d'accueil ou parfois simplement installer avec le symbole de l'écran de mobile. 
Or c'est toujours en échec, sans message d'erreur.
Avec Chrome et le navigateur MI, cette option fonctionne.
Est-ce uniquement mon mobile, alors que dois-je faire, sinon est-ce tous les Android, alors pourquoi la proposer comme option ?
Je n'ai pas trouvé ce sujet dans l'assistance en ligne.
J'aimerais pouvoir me dispenser des navigateurs ci-dessus mentionnés.
Désolé de vous déranger et merci par avance.
Cordialement.
René JEANNENOT

From a translation service
> I ask for your help your menu offers the option to add a website on the home screen or sometimes just install with the mobile screen symbol.
However, it is still in failure, without an error message.
With Chrome and the MI browser, this option works.
Is it only my mobile, so what should I do, if not is it all Android, so why offer it as an option?
I could not find this topic in the online support.
I would like to be able to dispense with the browsers mentioned above.
Sorry to bother you and thank you in advance.

**Comment by abodea** [comment]
Bonjour et merci pour ce rapport!
Notez que j'ai essayé de reproduire ce problème sur le RC 86.1.1 (votre version) et le dernier Nightly de 3/10 avec Google Pixel 4 XL (Android 11) mais je n'ai rencontré aucun problème.
J'ai pu ajouter des sites Web à l'écran d'accueil sans problème et j'ai également pu y accéder.

Que se passe-t-il lorsque vous appuyez sur l'icône nouvellement ajoutée sur l'écran d'accueil?
Votre problème est uniquement visuel ou ne fonctionne pas du tout?
Pouvez-vous s'il vous plaît fournir une vidéo / image?

>Hello and thank you for this report!
Note that I tried to reproduce this issue on the **RC 86.1.1** (your version) and latest Nightly from 3/10 with **Google Pixel 4 XL (Android 11)** but I didn't encounter any issues.
I was able to add to the home screen websites without issues and I also was able to access them.
What happens when you tap on the newly added icon on the home screen? 
Your problem is only visual or it is not working at all? 
Can you please provide a video/image?

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1343504
