### ISSUE TITLE
Disabled ContextMenusTests 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#18421]
Due to intermittent test failures encountered in the past, the following ContextMenu Automated tests are currently disabled:
► `verifyContextCopyLink`
► `verifyContextOpenImageNewTab`
► `verifyContextCopyImageLocation`
► `verifyContextSaveImage`
► `verifyContextMixedVariations`
► `verifyContextShareLink`
► `verifyContextOpenLinkNewTab`
► `verifyContextOpenLinkPrivateTab`

Based on my research, 

The **main reason** behind the these failures is that **the page elements aren't identified properly** 
Because of this, we can't perform long clicks (`longClickMatchingText`) on the featured links/images

Other potential reasons behind these failures are caused by the fact that:
► In some cases the incorrect URL remains displayed in the navigation toolbar when performing `verifyUrl` 
► Sometimes the fill link from clipboard (`visitLinkFromClipboard`) doesn't work properly

**Comment by sv-ohorvath** [comment]
verifyContextShareLink, verifyContextOpenLinkNewTab, verifyContextOpenLinkPrivateTab started failing on 3/29, with this commit on Master: https://github.com/mozilla-mobile/fenix/commit/02d70d38373d19c977f20a942ee20ca164f02ec4, but seems more likely to be caused by the AC 75.0.20210328204653 update (previous commit)
- https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5777990874670391260
- https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5467489900846752731
- https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8336955909045279848

Disabling the whole class until we find a fix: https://github.com/mozilla-mobile/fenix/pull/18700

**Comment by AndiAJ** [comment]
Re-enabled the remaining 3 tests in #22199
`verifyContextOpenImageNewTab`
`verifyContextOpenLinkNewTab`
`verifyContextOpenLinkPrivateTab`
