### ISSUE TITLE
[Bug] user agent for tablets is not correct, sends mobile UA

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1848]
## Steps to reproduce
Open Fenix on a tablet and check the user agent

### Expected behavior
User agent conforms to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Mobile_and_Tablet_indicators

### Actual behavior
Mobile user agent is sent

### Device information
* Android device: Nexus 10
* Fenix version: April 19th

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10046)

**Comment by miketaylr** [comment]
This affects the experience on Bing, probably on a lot of other sites.

**Comment by kbrosnan** [comment]
Linking the GV bug [1555035](https://bugzilla.mozilla.org/show_bug.cgi?id=1555035)

**Comment by Rashidwi** [comment]
Could there a short term fix for this?  I've seen suggestions about about:config general.useragent.override but it does not appear to work. 

The problem means that Firefox is effectively unusable on Android tablets due to having to change the desktop setting for _**each and every**_  website visited.

**Comment by kbrosnan** [comment]
Closing as a duplicate of bz-1555035
