### ISSUE TITLE
"Don't track me Google" add-on not available to install for me on Nightly

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#18511]
## Steps to reproduce
In Fenix go to add-ons and search for "Don't track me Google" add-on.

### Expected behaviour
The add-on is recommended for Fenix https://addons.mozilla.org/en-GB/android/addon/dont-track-me-google1/ so it should be available to install in app.

### Actual behaviour
The list of available add-ons does not show "Don't track me Google".

### Device information
* Device vendor / model and Android version: Nokia 8 on Android 9
* Firefox for Android version: 
* Nightly 210316 17:01 (Build #2015799051)
AC: 74.0.20210313190118, 05dcfd7b3
GV: 88.0a1-20210313094300
AS: 73.0.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10060)

**Comment by kbrosnan** [comment]
I don't believe Android recommend extensions have been updated since Fennec. Next step is to figure out what APIs are needed for it to work.

**Comment by madb1lly** [comment]
Hi @kbrosnan,
I thought this page _had_ been updated to be for Fenix, not for Fennec: https://addons.mozilla.org/en-GB/android/search/?promoted=recommended&sort=random&type=extension

There used to be many many many addons listed for Fennec - many didn't even work! Now for Android there are **only** these addons listed, ergo a user would expect to be able to install them.

Cheers :slightly_smiling_face:

**Comment by Rob--W** [comment]
I have recently published an update (unrelated to Android), but explicitly unchecked the "compatible for Android" option at submission, because the add-on cannot be installed despite having been marked as compatible.

That's because on Fenix, users can only enable add-ons that are part of the collection of add-ons that are available to Fenix. This list is different from the set of "recommended add-ons".

If you want to install more add-ons, then you need to use Nightly with a custom configuration, as explained at https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814144

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
