### ISSUE TITLE
Browser menu should always show the navbar

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18591]
Meta: #17796 

🔴 Depends on https://github.com/mozilla-mobile/android-components/issues/9932

UX Figma designs (bottom right, labeled "Final designs"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

The bottom margin on the menu navigation is not correct because the navigation footer is scrollable (see comment below). This card should integrate the sticky footer that will be implemented in https://github.com/mozilla-mobile/android-components/issues/9932.

<img width="323" src="https://user-images.githubusercontent.com/43795363/112070303-65ab7980-8b3b-11eb-934c-652f25d4823b.png">

**Comment by Mugurell** [comment]
@eliserichards I think in your case the list of menu options overflows the screen and is scrollable like here?

https://user-images.githubusercontent.com/11428869/112141787-6d702a00-8bde-11eb-8c95-7ad35189a064.mp4

The margins are right but the item may seem clipped because the menu does not fit the screen and is turned scrollable.
So the above behavior is expected.

I proposed here - https://github.com/mozilla-mobile/android-components/issues/9932 a sticky footer list that can be used for the menu to ensure that that navigation bar is always displayed exactly as intended.
But even with that, the menu would still not fit and other items may seem clipped.

**Comment by eliserichards** [comment]
Closing in favor of https://github.com/mozilla-mobile/android-components/issues/9932

**Comment by Mugurell** [comment]
Reopening this for adding the navbar configuration for having it sticky following https://github.com/mozilla-mobile/android-components/issues/9932

**Comment by Mugurell** [comment]
Would be nice to confirm on multiple devices that the navbar is always displayed at the very top/bottom of the menu.
In portrait and in landscape.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducing on some devices. Reproducible on Motorola Nexus 6 with Android 7.1.1. with the latest Nightly (90.0a1 - 5/10 @ 5:07AM), and on the latest Beta (89.0.0-beta.5). Not reproducible on HTC Nexus 9 with Android 7.1.1. using the latest Nightly (90.0a1 - 5/10 @ 5:07AM), on the latest Beta (89.0.0-beta.5) and on the latest Release (88.1.3). Not reproducible on the Motorola Nexus 6 with Android 7.1.1 with on the latest Release (88.1.3).

Devices used: HTC Nexus 9 with Android 7.1.1 and Motorola Nexus 6 with Android 7.1.1.


https://user-images.githubusercontent.com/48829350/117643942-a0bc4780-b191-11eb-81b9-3b1a3f0216c3.mp4

**Comment by Mugurell** [comment]
Thank you @SoftVision-LorandJanos 
I understand the issue you are seeing is that after "expanding" the menu it is still scrollable.
That is the expected behavior if not all menu items fit on the screen - the user must be able to scroll to see and interact with all of them.

The way the menu functions:
- opening the bottom menu will show the menu first as collapsed - showing only the menu items from the first to "Add to homescreen" (following https://github.com/mozilla-mobile/fenix/pull/18499)
- a swipe up is needed to show the menu as "expanded" - showing all menu items
   - if they fit on the screen the menu "expanded" menu should not be scrollable anymore
   - if the menu has full heigh but not all menu options fit on the screen, we still need to let users interact with all of them so the menu will be scrollable.
   
(the menu starts as "collapsed" and the first swipe up will expand the menu only if all items including "Add to homescreen" fit on the screen. That may not be the case while in landscape or on tablets. In this case if there's no point in starting as collapsed the menu will be considered expanded form the start - the first swipe up will scroll the menu, not expand it.)
   
What was done in this ticket (with the help if https://github.com/mozilla-mobile/android-components/issues/9932) is ensuring one specific menu item will always be on the screen - even when it/not all items fit the screen.
(That item always shown on the bottom of the menu item may be referred to as the sticky footer).
And that menu item is the navbar (menu item containing the back, forward, share refresh options).

**Comment by SoftVision-LorandJanos** [comment]
According to @Mugurell's latest comment, the menu has the expected behavior on smaller screens.
In this case the issue is verified as fixed.
Verified on the latest Nightly (90.0a1 - 5/10 @ 5:07AM), on the latest Beta (89.0.0-beta.5) and on the latest Release (88.1.3).
Devices used: HTC Nexus 9 with Android 7.1.1 and Motorola Nexus 6 with Android 7.1.1.

**Comment by eliserichards** [comment]
Closing as fixed 🎉
