### ISSUE TITLE
[Bug] top url bar removed during search

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#18616]
In nightly: when selecting search on page the url bar, tabs and menu are removed until search close. This happens when the url bar is placed at the top. Also the removed items are not filled, thus leave empty space at top.

## Steps to reproduce
Use nightly 
Place url bar at top
Open random url
Select search on page
Search bar displays at bottom
Url bar, tabs and menu disapear
Space of url bar, tabs, menu remains empty
No features of Url bar, tabs, menu can not be used
Close search option
Url bar, tabs, menu are displayed and can be used

### Expected behavior
Opening search should not affect display or usability of url bar, tabs, menu.
To compensate less page display due to find bar, keep url bar, tabs, menu available by scroll feature instead of just removing and not compensating.

Fenix nighly march 2021

https://user-images.githubusercontent.com/11428869/112489291-fcb84180-8d86-11eb-9d8b-bf85e9ada049.mp4

**Comment by Mugurell** [comment]
This is happening because we are explicitly removing the top toolbar [here](https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/main/java/org/mozilla/fenix/components/FindInPageIntegration.kt#L36) and the browser does not follow-up to cover the now empty space.

We could either update [EngineViewBrowserToolbarBehavior](https://github.com/mozilla-mobile/android-components/blob/acb4ca9687a70542f7f39cf1db747e73dcfe5967/components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehavior.kt) to check for toolbar's visibility also or we could use add new APIs to the toolbar to be used instead of relying on modifying the visibility.

I would propose focusing on new APIs for the toolbar as a general solution for when the toolbar needs to be hidden, something also needed for when entering fullscreen which right now is handled by a [pretty brittle code](https://github.com/mozilla-mobile/fenix/blob/43c54b7006d0d28f852bf1b93b75dcbbba004b7d/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L1197).

**Comment by Mugurell** [comment]
Looked into offering better upstream support for this (in BrowserToolbar / it's / EngineViews behavior) but it seems like a lot of changes needed to support very specific scenarios:

- top toolbar, not dynamic:
  - toolbar must disappear
  - browser must keep it's size but move up
- top toolbar, dynamic:
  - toolbar must disappear
  - browser must become smaller with the height of the find in page bar and move up
- bottom toolbar, not dynamic:
  - toolbar must disappear
  - no change needed for the browser
- bottom toolbar, dynamic:
  - toolbar must disappear
  - browser must become smaller with the height of the find in page bar and move up
  
All the data needed to infer this scenarios is available in `BaseBrowserFragment` and `FindInPageIntegration` and so probably we should use it in place, with no upstream changes.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 4/13 with Samsung Galaxy Tab S3 (Android 8).
When using Find in page and the toolbar is set at the top, the toolbar and the occupied space disappear.
