### ISSUE TITLE
Scrolling is bad

### ISSUE THREAD

**Issue by ADV357** [mozilla-mobile/fenix#18640]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10142)

**Comment by ADV357** [comment]
Please make the web pages scrolling smoother and faster

**Comment by Mikaka27** [comment]
Hi, it would be helpful if you would add some examples, which websites are scrolling bad for you.
And also adding information about your device would be helpful.

**Comment by SoftVision-LorandJanos** [comment]
Hi @ADV357  ! Thank you for the report! As mentioned above, it would help us if you could give us some information about your device, the Android version, the browser version and the websites you noticed this behavior on. Thank you!

**Comment by VfBFan** [comment]
I too have a really choppy behavior when scrolling on some web pages. It is caused by WebRender.
If I disable WebRender under about:config "gfx.webrender.force-disabled = true" the scrolling behaviour is normal.
e.g. https://uebermedien.de/

Fairphone 3 (Adreno 506)
Android 10
Firefox 87.0.0-rc.1 (Fennec F-Droid)

**Comment by SoftVision-LorandJanos** [comment]
Hi @VfBFan ! Thanks for you comment! I tried scrolling on the website mentioned by you with and without WebRender disabled, and I didn't notice any difference, using a HTC Nexus 9, with Android 7.1.1, using the build mentioned above (Firefox 87.0.0-rc.1) and the latest Nightly, but it might be device and/or Android version dependent.

**Comment by lobontiumira** [comment]
I cannot reproduce this bad scrolling experience either. I've tested several pages, including https://uebermedien.de/ with OnePlus 5T (Android 10), and Google Pixel (Android 10).
@ADV357 or @VfBFan could you provide a short video?

**Comment by VfBFan** [comment]
Since with version 92 WebRender can no longer be turned off and the scrolling behavior is still very jerky on several websites here now a video of the problem.
@lobontiumira [https://filehorst.de/d/dnnuInqB](url) (27.8 MB)

**Comment by djdisodo** [comment]
i had sluggish scrolling issue on twitter
but it actually solved when i disabled images using about:config

**Comment by Palloxin** [comment]
I also known a website where the scrolling becomes sluggish when there is a specific kind of image in my view. The problem is that this website is NSFW and requires an user to sign up to see the link i will send, basically a forum. Please keep in mind this is a nsfw website and if it is not okay to send it, please just deleted comment instead of banning me please. i just want to fix this problem universally (definitely on all websites) on fenix, so if another example can help i will send it.
https://www.phica.eu/forums/threads/tetteen-solo-giovani-tettone-megaraccolta.128664/q
remember you need an account to see the page an the content
once you are done with the account, scroll down until you see images in a row in this format (heavely censored)
![dddds](https://user-images.githubusercontent.com/75091899/202908440-59963e80-a3cb-462d-8f9d-05e7c84d2c93.png)


android 8 Miui 8
huawei p8 lite 2017
fenix ver 106.1.0

**Comment by Epicalert** [comment]
Still occurs on my device:

SM-J260Y
SoC: Samsung Exynos 7570
CPU: ARM Cortex-A53
GPU: ARM Mali-T720

Firefox: 109.1.1

Stuttering happens on all websites as far as I'm aware, scrolling feels much better on Chromium-based browsers.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811592

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
