### ISSUE TITLE
Intermittent UI test failure - Failing UI tests closePrivateTabsNotificationTest & testDownloadNotification

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18644]
Seen in all recent PRs.

Failing tests:
- [closePrivateTabsNotificationTest](https://github.com/mozilla-mobile/fenix/blob/23cc3522aa1e5b4a85ae708ac5c4c2f79e7922b0/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt#L222) - [FB link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.a7cdfbf9b2e72fc7/testcases/3/test-cases)
- [testDownloadNotification](https://github.com/mozilla-mobile/fenix/blob/7ac4af46bcd4baf56d1de15d421090965bddd195/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt#L77) - [FB link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.117fc38ef098bd52/testcases/1/test-cases)
- [verifyExpandedCollectionItemsTest](https://github.com/mozilla-mobile/fenix/blob/869c99afaa71da969be39d4f04efda77146fa6b8/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt#L891) - [FB link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.abbb5506f70abd6f/testcases/2/test-cases)
- [closeAllTabsTest](https://github.com/mozilla-mobile/fenix/blob/23cc3522aa1e5b4a85ae708ac5c4c2f79e7922b0/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt#L106) - [FB result](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.abbb5506f70abd6f/testcases/3/test-cases)

**Comment by AndiAJ** [comment]
Hi, just checked the 6 PR's that are failing due to `ui-test-x86-debug`

The failures are caused by these tests:
► `closePrivateTabsNotificationTest`
► `testDownloadNotification`
► `verifyExpandedCollectionItemsTest`
► `closeAllTabsTest`
► `testStrictVisitSheetDetails`
► `verifyBasicNavigationToolbarFunctionality`


## • PR [Import strings from android-l10n.](https://github.com/mozilla-mobile/fenix/pull/18634)

► closePrivateTabsNotificationTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.df6bb7e991b433f/testcases/3/test-cases
)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.2873b3391edc6752/testcases/3/test-cases )

► testDownloadNotification
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.cb42879e9f0ed11b/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.9c3a5801ede90bc0/testcases/1/test-cases)

► verifyExpandedCollectionItemsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.cb42879e9f0ed11b/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.9c3a5801ede90bc0/testcases/2/test-cases)

► closeAllTabsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.cb42879e9f0ed11b/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797601574500246389/executions/bs.9c3a5801ede90bc0/testcases/3/test-cases)

## • PR [Update Android Components version](https://github.com/mozilla-mobile/fenix/pull/18637)

► closePrivateTabsNotificationTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.77d31c0ffd8f0/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.fb2ac8cbfa149ae0/testcases/3/test-cases)

► testDownloadNotification
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.1a41816b1a2663d5/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.ab4bd0bdf27de911/testcases/1/test-cases)

► verifyExpandedCollectionItemsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.1a41816b1a2663d5/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.ab4bd0bdf27de911/testcases/2/test-cases)

► closeAllTabsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.1a41816b1a2663d5/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4618992182158277637/executions/bs.ab4bd0bdf27de911/testcases/3/test-cases)

## • PR [Closes #18535: Re-add grid layout to tabs tray](https://github.com/mozilla-mobile/fenix/pull/18638)

► closePrivateTabsNotificationTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.79e38039afc4a894/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.178a8de2f9799a6e/testcases/3/test-cases)

► testDownloadNotification
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.f4f3e44f0bf414a4/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.df9b5787a57633d6/testcases/1/test-cases)

► verifyExpandedCollectionItemsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.f4f3e44f0bf414a4/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.df9b5787a57633d6/testcases/2/test-cases)

► closeAllTabsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.f4f3e44f0bf414a4/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677508086319739592/executions/bs.df9b5787a57633d6/testcases/3/test-case)s

## • PR [For #15372 Improve onboarding strings](https://github.com/mozilla-mobile/fenix/pull/18639)

► closePrivateTabsNotificationTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.74a27fb7488d6b5b/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.5f86a29bac558579/testcases/3/test-cases)

► testDownloadNotification
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.1970c844ef5af99e/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.f7689acbe0850e94/testcases/1/test-cases)

► verifyExpandedCollectionItemsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.1970c844ef5af99e/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.f7689acbe0850e94/testcases/2/test-cases)

► closeAllTabsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.1970c844ef5af99e/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7293426098117438054/executions/bs.f7689acbe0850e94/testcases/3/test-cases)

## • PR [Update to Android-Components 74.0.2.](https://github.com/mozilla-mobile/fenix/pull/18642)

► closePrivateTabsNotificationTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.5e130fa4c0721297/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.1e99573a02d54fa9/testcases/3/test-cases)

► testDownloadNotification
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.d6f6ac87740d8ecb/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.1cf75af4a90d8b52/testcases/1/test-cases)

► testStrictVisitSheetDetails
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.d6f6ac87740d8ecb/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.1cf75af4a90d8b52/testcases/2/test-cases)

► verifyBasicNavigationToolbarFunctionality
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.d6f6ac87740d8ecb/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6005180226274456470/executions/bs.1cf75af4a90d8b52/testcases/3/test-cases
)
## • PR [Run ci for18628](https://github.com/mozilla-mobile/fenix/pull/18643)

► closePrivateTabsNotificationTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.a7cdfbf9b2e72fc7/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.a79fec5f41c6579c/testcases/3/test-cases)

► testDownloadNotification
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.117fc38ef098bd52/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.abbb5506f70abd6f/testcases/1/test-cases)

► verifyExpandedCollectionItemsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.117fc38ef098bd52/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.abbb5506f70abd6f/testcases/2/test-cases)

► closeAllTabsTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.117fc38ef098bd52/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4829818326930680924/executions/bs.abbb5506f70abd6f/testcases/3/test-cases)

**Comment by Mugurell** [comment]
Looked into this, I don't see any recent modifications that could've caused these fails.
When trying to run the ui tests locally I get more failing, @mcarare has all them passing so it's hard to even start working on them.
Talked with @sv-ohorvath which recommended disabling these tests to unblock PR merging.

**Comment by sv-ohorvath** [comment]
The cause are the 2 tests involving the notification shade: closePrivateTabsNotificationTest & testDownloadNotification. They are failing to match the notification, so they don't reach the step where they close the notification shade. Thus, the notification shade still covers the tests that follow them in the same shard.

**Comment by Mugurell** [comment]
In https://github.com/mozilla-mobile/fenix/pull/18637 I also see `https://github.com/mozilla-mobile/fenix/pull/18637` failing.

**Comment by sv-ohorvath** [comment]
> In #18637 I also see `customTrackingProtectionSettingsTest` failing: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5139698417276636554/executions/bs.4bfd91bea31715ff/test-cases

This case seems unrelated. Is either caused by the AC update, or is flaky.

**Comment by isabelrios** [comment]
I think there is one more test affected as per this [PR](https://github.com/mozilla-mobile/fenix/pull/18675) reported by ryanvm: 

- manageDownloadsInDownloadsMenuTest

**Comment by sv-ohorvath** [comment]
> I think there is one more test affected as per this [PR](https://github.com/mozilla-mobile/fenix/pull/18675) reported by ryanvm:
> 
> * manageDownloadsInDownloadsMenuTest

The test is known to be flaky, not PR blocking, we'll leave it as it is for now: https://github.com/mozilla-mobile/fenix/issues/17485

**Comment by codrut-topliceanu** [comment]
Needed to uplift https://github.com/mozilla-mobile/fenix/pull/18703 to fix failing tests for https://github.com/mozilla-mobile/fenix/pull/18699. I spoke with @pocmo on Slack about it 😄
