### ISSUE TITLE
Provide a way to move or organize bookmarks

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1869]
### Why/User Benefit/User Problem
As a user with bookmarks, I can move my bookmarks so that I can organize them in a way that makes sense to me.

I should be able to do this without editing the bookmarks, like I can in most Chromium based browsers.

### What / Requirements
New context menu item labeled "Move" beside folders and bookmarks.

### Acceptance Criteria (how do I know when I’m done?)
I can select a bookmark and move it into another folder
I can select a bookmark that is in another folder and move it into a different folder
I can select multiple bookmarks and move them into another folder (this is done via a toolbar icon in other browsers)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10172)

**Comment by vesta0** [comment]
@topotropic for your consideration.

**Comment by distantkay** [comment]
Very, very much support.  Please implement the ability to move bookmarks and bookmark folders.

I created a similar thread on Reddit and was recommended to write here. 
Just in case, I will duplicate what I wrote there:


**Working with bookmarks in mobile and desktop versions of Firefox**

_I really like the browser Firefox, which is the only actively developing island of freedom, among proprietary browsers. But it is very difficult to switch to it because of the complexity of working with bookmarks, which is especially evident in the mobile version, where it is actually impossible to organize bookmarks properly.

By impossible organization, I mean that it is impossible to arbitrarily move bookmark folders and bookmarks themselves.

The example of ideal way of work with bookmarks in my opinion is Opera browser, both mobile and desktop versions.

I think that Firefox without exaggeration would be the best browser if the developers realize this feature in this way.

I apologize in advance for any mistakes in the text, because I do not know English well and use a translator.

And thank you for being there_

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811652

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
