### ISSUE TITLE
FNX-5298 ⁃ [UX] Settings

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#187]
GH issue to track design work. Bram is wrapping this up before transitioning off. 

**Fenix Flows WIP**
https://docs.google.com/drawings/d/11Kj7OAvit6bE6QQt_ven0xnHGhmwu4Jc_N_oazdryAo/edit

**Comment by lime124** [comment]
@brampitoyo can you provide an update when you're back? @st3fan has some questions I believe. Thanks!

**Comment by brampitoyo** [comment]
@colintheshots This issue is ready for your feedback, and to estimate.

**Comment by sblatz** [comment]
@brampitoyo Love the designs, awesome work on these 😄  

Just wanted to point out in regards to the default browser setting: we tried doing this with Focus but were unable to find a solution that wasn't really hacky as this is not the intended method of setting a default. I'd recommend we use the [accepted method](https://github.com/mozilla-mobile/focus-android/blob/6e5a9e684b7fb1fd5e813ef2fee69e5cc27faa78/app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.kt) like we used resorted to in Focus.

**Comment by vesta0** [comment]
@brampitoyo can this issue be closed? It's already been broken down by engineering and in progress.

**Comment by shorlander** [comment]
Two things I noticed on this:
- Not everything listed in the mockups is going to be in MVP
- The accounts section has its own issue (https://github.com/mozilla-mobile/fenix/issues/169)
- We should use "native" Android radio buttons with the right color accent

**Comment by lime124** [comment]
reopen - we're going to have to do some rework based on some changes to the features (e.g removing battery saving)

**Comment by brampitoyo** [comment]
I’ve reworked the Settings page to take into account all the features that we’re shipping in MVP. As a result, a lot of sub-pages were taken out.

The only notable thing here is the inclusion of a new instruction for setting default browser, because Fenix will send users to Android System Settings.

The canonical link to the latest mockup, which is just up above, is this: https://github.com/mozilla-mobile/fenix/issues/187#issuecomment-458372653
