### ISSUE TITLE
[Bug] Disable failing UI Tests | <NavigationToolbarTest.goForwardTest> | <NavigationToolbarTest.refreshPageTest> |  <NoNetworkAccessStartupTests.testPageReloadAfterNetworkInterrupted> | <SmokeTest.mainMenuShareButtonTest> |  <SmokeTest.mainMenuRefreshButtonTest> | <ShareButtonTest.ShareButtonAppearanceTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#18720]
Due to intermittent test failures in #18619 the following tests will be disabled:
<NavigationToolbarTest.goForwardTest>
<NavigationToolbarTest.refreshPageTest>
<NoNetworkAccessStartupTests.testPageReloadAfterNetworkInterrupted>
<SmokeTest.mainMenuShareButtonTest>
<SmokeTest.mainMenuRefreshButtonTest>
<ShareButtonTest.ShareButtonAppearanceTest>

**Comment by Mugurell** [comment]
This tests will need to be updated to support the new menu which right now has those options initially scrolled off-screen.

**Comment by Mugurell** [comment]
Thank you @Andi for disabling these tests and help unblock merging.
Didn't think of this because nothing should've changed regarding the menus in my PR but looking at the videos from Firebase it seems like for that PR the new menu was used (which doesn't fit the screen and had the options tests needed scrolled off) while for other PRs the old menu is used (with fewer menu items, all available in tests)
Even though a [isDebug feature flag](https://github.com/mozilla-mobile/fenix/blob/6f7b911c117fd8c502a3347cd43a7246d83b8562/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L37-L40) is used so I think all PRs should've used the new menu already.

**Comment by sv-ohorvath** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/issues/17979
