### ISSUE TITLE
[Bug] Page reloading spinner stucks if webpage uses it's own spinner and if reloaded before page fully loaded

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#18740]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open Twitter and before fully loaded swipe down to reload

### Expected behavior
Actually it should show spinner and reload page 
### Actual behavior
spinner stucking and not reloading

https://user-images.githubusercontent.com/17825767/113216271-bed68400-9284-11eb-82be-93fc503439cc.mp4

### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: 3/31 nightly

**Comment by hakkikaancaliskan** [comment]
Probably @Mugurell is the right person to cc here :)

**Comment by Mugurell** [comment]
Thank you @hakkikaancaliskan !

So I'm seeing that previously app's pull to refresh would've been triggered every time for a swipe down.
- While the page was loading.
- While the page is fully loaded and Twitter scrolled to the top.

Both of these scenarios are something we'd want to avoid.
- Pull to refresh shouldn't be triggered while the page is loading.
- App's pull to refresh shouldn't be triggered in Twitter's case (and other similar websites) since it has it's own touch listener and pull to refresh functionality.

**Comment by abodea** [comment]
Thank you for this report @hakkikaancaliskan!
Note that I was able to reproduce this issue right before twitter was loaded with a pull-refresh-down.
IMO this is not really a normal user behavior as you don't really wanna refresh a page while opening it because you wait for it to load.
I reproduced the issue on the latest nightly 4/1/21 with Google Pixel 4 XL (11).
While being in the home screen or on a tweet I cannot reproduce this issue, I only can reproduce it while I visit a profile.

**Comment by DiegoARL38** [comment]
While on an unstable network, like cellular data, it's quite useful being able to reload the page if it hasn't finished loading the first time.

**Comment by abodea** [comment]
> While on an unstable network, like cellular data, it's quite useful being able to reload the page if it hasn't finished loading the first time.

Thank you, but I was referring to how the reporter said, before the page loads, not after the page is loaded.
Ofc is useful for mobile data, but even that is strong nowadays.
