### ISSUE TITLE
FNX-5306 ⁃ [UX] Site Permissions Management

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#188]
GH issue to track design work. Bram is wrapping this up before transitioning off.

**Comment by bbinto** [comment]
Any ETA from @brampitoyo on that?

**Comment by brampitoyo** [comment]
# Mockups
https://mozilla.invisionapp.com/share/ZJPJYMJPQ6F

# Walkthrough

Here’s a Setting sub-page that shows and lets users control practically every site features and permissions in one interface, using a consistent UI.

<img width="360" src="https://user-images.githubusercontent.com/51007/52030811-71fca300-257e-11e9-86c9-6f1d9db8be8b.png">

## Optimize

This is one of the places where you can turn the battery saver feature on and off.

## Exceptions

Inevitably, some sites will want access to your camera, location, microphone, etc. When any of that happens, we’ll list those sites here.

<img width="360" src="https://user-images.githubusercontent.com/51007/52030996-25fe2e00-257f-11e9-8642-275d2f92ac9c.png">

Listing those sites allow you to block or unblock access to specific permissions on a specific site. You can also clear/reset those permissions if you like. Here’s the “permission table” for an example site.

<img width="360" src="https://user-images.githubusercontent.com/51007/52031015-3c0bee80-257f-11e9-9a29-f5fc958e26ca.png">

## Recommended settings

On recommended setting, Fenix will allow and block site features/permissions in an effort to balance:

* Maximum site compatibility (so most sites will just work)
* Minimum annoyance (so users won’t get annoyed and slowed down by trackers, pop-ups, redirects, autoplaying video, and maybe even ads)

<img width="360" src="https://user-images.githubusercontent.com/51007/52031330-d0c31c00-2580-11e9-9b23-32e5a819f7a9.png">

## Custom settings

This allows you to specify what to allow or block globally (ie. it applies to all sites).

Site features/permissions are further broken down into 3 sub-categories, to make scanning and navigating through the page easier.

### Web content and behaviours

These features will only impact things inside the Fenix.app browser chrome.

* Ads
* Autoplay sound and video
* Cookies
* DRM sound and video
* Pop-ups
* Trackers
* Website redirects

<img width="360" src="https://user-images.githubusercontent.com/51007/52031382-15e74e00-2581-11e9-92e4-7475329ea982.png">

### Phone features

When allowed, these features may impact things outside of Fenix.app. For example, a website may track your location or send you notification even when Fenix is running in the background.

* Camera
* Location
* Microphone
* Notifications

<img width="360" src="https://user-images.githubusercontent.com/51007/52031390-1ed81f80-2581-11e9-850e-f47e1e0dc238.png">

### Advanced

As the name imply, you probably don’t want to modify the items here, because it may cause things to behave unexpectedly. For example, most sites won’t look or work properly if you block JavaScript, images, and copy/paste from clipboard.

Because of this, “Advanced” is further hidden inside an arrow that you must tap to expand.

* Cache and site data
* Clipboard
* JavaScript
* USB
* Images

<img width="360" src="https://user-images.githubusercontent.com/51007/52031396-25ff2d80-2581-11e9-922d-e4c4eb14f519.png">

## Managing individual feature/permission

Some features/permissions can be controlled by a simple toggle. Example: DRM, pop-ups, redirects.

<img width="220" src="https://user-images.githubusercontent.com/51007/52031485-aa51b080-2581-11e9-991f-8e1aa55b8281.png"><img width="220" src="https://user-images.githubusercontent.com/51007/52031489-acb40a80-2581-11e9-8faa-704ac778a697.png"><img width="220" src="https://user-images.githubusercontent.com/51007/52031490-ade53780-2581-11e9-860b-d7c072223544.png">

Other features/permissions are controlled by radio buttons, either because they contain more than two options, or the options inside need more explanations. Example: autoplay, cookies, trackers.

<img width="220" src="https://user-images.githubusercontent.com/51007/52031548-f7ce1d80-2581-11e9-81a4-1e23c79adebd.png"><img width="220" src="https://user-images.githubusercontent.com/51007/52031550-f8ff4a80-2581-11e9-82f3-c499e116a32b.png"><img width="220" src="https://user-images.githubusercontent.com/51007/52031552-fa307780-2581-11e9-849e-b0d8c3411d60.png">

**Special mentions**: camera, location, microphone and location permissions (and I think a few other permissions, like USB) are controlled **firstly by Android System**, then by Fenix.app. So if it’s blocked by the system, we can’t even give users any control.

When this happens, we show an explanatory message that directs users to Settings.app and instructs them to turn on the necessary permission under Fenix.app.

Either way, our default value for these features/permissions is “Ask to allow”.

Here’s the camera permission page, for example:

<img width="220" src="https://user-images.githubusercontent.com/51007/52031764-f6e9bb80-2582-11e9-89b2-532384694cfd.png">

# Questions

1. Does this way of managing site permissions/features make sense?
2. Does the sub-category grouping make sense (web content, phone features, advanced)?
3. Is this UI feasible, given our timeline?

**Comment by brampitoyo** [comment]
cc @bbinto @lime124 to put this issue into a sprint/milestone.

@colintheshots This issue is now also ready for estimation and feedback.

**Comment by pocmo** [comment]
@bram Thank you for those mocks! That's great.

We'll also need a way to handle requests (e.g. camera, microphone, location, notification, ..) from websites while browsing (or is that a different issue?). For the AC team it would be helpful to know if we want to use a doorhanger approach like in Fennec for that. :)

**Comment by bbinto** [comment]
Thanks @brampitoyo - I'll close this issue and linked it in the Site Permissions Meta for the eng to breakdown.

**Comment by bbinto** [comment]
@brampitoyo - as @pocmo pointed out, the "site controls" meta is supposed to cover the doorhanger UI. Let's reopen the "site controls" again and tackle the work in that issue.

**Comment by st3fan** [comment]
@brampitoyo I filed https://github.com/mozilla-mobile/fenix/issues/332 for the prompts, so this one can be about management of permissions

**Comment by mheubusch** [comment]
@brampitoyo note that we are confused by website redirect setting and it is not on the roadmap for MVP and am asking that we remove it from the designs

**Comment by mheubusch** [comment]
@brampitoyo verify that designs support users on Android 5
