### ISSUE TITLE
[crash] IllegalArgumentException in SaveLoginDialogFragment PromptFeature

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18877]
Crash stats: https://crash-stats.mozilla.org/signature/?product=Fenix&version=87.0.0&signature=java.lang.IllegalArgumentException%3A%20at%20mozilla.components.feature.prompts.PromptFeature%24onConfirm%241.invoke%28PromptFeature.kt%3A39%29&date=%3E%3D2021-04-01T16%3A14%3A00.000Z&date=%3C2021-04-08T16%3A14%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#summary

```
java.lang.IllegalArgumentException
	at mozilla.components.feature.prompts.PromptFeature$onConfirm$1.invoke(PromptFeature.kt:39)
	at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
	at mozilla.components.feature.prompts.PromptFeature.onConfirm(PromptFeature.kt:1)
	at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment.access$onPositiveClickAction(SaveLoginDialogFragment.kt:10)
	at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment$onViewCreated$1.onClick(SaveLoginDialogFragment.kt:1)
	at android.view.View.performClick(View.java:6659)
	at android.view.View.performClickInternal(View.java:6631)
	at android.view.View.access$3100(View.java:790)
	at android.view.View$PerformClick.run(View.java:26187)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by Mugurell** [comment]
Based on the stacktraces this is not just an incorrect cast that can be dropped off.
I all reports I see
> Caused by: java.lang.ClassCastException: mozilla.components.concept.storage.Login cannot be cast to java.lang.Boolean
> Caused by: java.lang.ClassCastException: kotlin.Pair cannot be cast to java.lang.Boolean

Possibilities for this that I think of: 
- maybe some apis changed and need to be better supported or more probably 
- an alert came after showing an initial prompt and replaced the active prompt but for example the `SaveLoginDialogFragment` is still on screen and when the user confirm the login that reponse gets to the Alert which came in the meantime.

**Comment by Amejia481** [comment]
Sentry issue: [FIREFOX-NIGHTLY-85P](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9731032/?referrer=github_plugin)

**Comment by Mugurell** [comment]
This issue can be resproduced with the help of http://jsfiddle.net/pahund/e9fv3j1m
with which we can get to show more different prompts at the same time:

<img src="https://user-images.githubusercontent.com/11428869/116558717-67b9e280-a908-11eb-89a9-4ecb70ee207e.png" width="33%" />


And then a delay [here](https://github.com/mozilla-mobile/android-components/blob/695405d8d77a73f13e6053984d0c22c56844768d/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L379) that will get us this edgecase scenario (and exception / crash) that is though possible in the real world:
- one prompt is shown. SaveLogin / or [others](https://crash-stats.mozilla.org/report/index/d000d4ff-4acf-415b-95c3-254a80210428).
- user interacts with it - terminal operation, let's say it confirms adding the login.
- [onConfirm](https://github.com/mozilla-mobile/android-components/blob/695405d8d77a73f13e6053984d0c22c56844768d/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L378) starts executing but in the meantime another prompt is to be shown for that tab - a new alert seems to happen pretty often.
- When the normal code execution flow gets to [consume the current prompt](https://github.com/mozilla-mobile/android-components/blob/695405d8d77a73f13e6053984d0c22c56844768d/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L724) (which in the meantime is an Alert) bad things can happen:
   - unsafe casts of the payload parameter of `onConfirm`. The payload may be specific to the first prompt (that the user actually acted upon) but which is different from the one of the currently showing prompt -> the exception we are seeing.
   - catching this cast exception will have the app user choices for both prompts. 
      - First user choice (for the initial SaveLogin prompt) is lost because of the cast exception
      - Second choice (for the Alert / other prompt) is lost because after "consuming" the first prompt [we null the current prompt request](https://github.com/mozilla-mobile/android-components/blob/695405d8d77a73f13e6053984d0c22c56844768d/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L726) but which is actually the Alert prompt / or maybe anoother which the user hasn't yet had the chance to interact with. But when she will we will not do anything because at that time the current prompt is already null, there is nothing to consume.
      
Based on this analysis it seems to me that the only real solution to this is for our ContentState to contain a list of `PromptRequest`, not just one because on Android and on desktop we can show more prompts at the same time (and then of course refactor all code to account for this - each PromptDialog could receive a hash or even better - it's `PromptRequest` (from which the Dialog could get all needed configuration data) to ensure a strong 1-1 relation between them).
Haven't found the code executed on desktop but from just manual testing it seems that on desktop there is a queue of prompts. Acting on them in order works okay, acting on the last one consumes in one way the ones below also.

Going with this means important changes so first I'd ask for @csadilek 's opinion.

**Comment by csadilek** [comment]
@Mugurell Yes, I agree about introducing a list/queue of `PromptRequests`. We recently discussed this with @pocmo and @Amejia481 as well. It's currently possible that the wrong prompt request is being consumed, leading to the invalid cast you found and other problems.

**Comment by Amejia481** [comment]
Yes, we filed https://github.com/mozilla-mobile/android-components/issues/8989 some time ago but I never brought it back, it looks like we have to start working on it soon.

**Comment by Mugurell** [comment]
We'll have to recheck for future occurrences of this crash (and maybe other related to prompts) but in the meantime it would be good to get a confirmation from QA that all prompts works the same as before.

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/9 Nightly build with Sony Xperia z5 Premium (Android 7.1.1), Samsung Galaxy Note 8 (Android 9), and HTC 10 (Android 8).
I opened http://jsfiddle.net/pahund/e9fv3j1m/show page, with which I got more different prompts at the same time, and no crashes occurred.
