### ISSUE TITLE
[Bug] Dynamic toolbar isn't working on yr.no timetable

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18897]
## Steps to reproduce
1. Open yr.no, and select a location.
2. Go to one of the days, in order to see the weather hourly.
3. scroll the opened timetable.

### Expected behavior
The timetable is scrollable, and the toolbar is dynamic.

### Actual behavior
The timetable is scrollable, but the toolbar is fixed.

### Device information
* Devices: Samsung Galaxy Note 8 (Android 9), Xiaomi Mi4i (Android 5.0.2)
* Firefox for Android version: 4/9 Nightly, Beta 88.0.0-beta.5, RC 87.0.0

https://user-images.githubusercontent.com/40694158/114185508-7850eb80-994e-11eb-932d-5d40be8619c6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10301)

**Comment by lobontiumira** [comment]
Reproducible on beta 89.0.0-beta.10 with HTC 10 (Android 8).

**Comment by lobontiumira** [comment]
Reproducible on Beta 90.0.0-beta.5 with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on 6/25 Nightly with Samsung Galaxy Note 8 (Android 9(.

**Comment by lobontiumira** [comment]
Reproducible on 90.1.0 with OnePlus 5T (Android 10).

**Comment by delia-pop** [comment]
Note that this issue was also observed on https://www.tmall.com. The toolbar is not animated when scrolling the website. 
Build: Nightly GV 97.0a1 01/07, RC 96.1.1.
Devices used: Google Pixel 6 (Android 12), Samsung S10E (Android 10).

https://user-images.githubusercontent.com/89388888/148554500-fbdd5527-1e31-451a-a617-66aef45b4d2d.mp4
