### ISSUE TITLE
[Bug] Options panel does not respond to taps when swyped up

### ISSUE THREAD

**Issue by Mattex92** [mozilla-mobile/fenix#18920]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Actual behavior
When there is a tab open and a website is loaded, the options panel (opened with a tap on three dots) responds to taps, but when you swype up to display further options it no longer responds to taps.

### Device information

Samsung Galaxy S8 Android 9

Firefox for Android version: Nightly 210410

**Comment by soren121** [comment]
I'm having this issue as well. I'm using Nightly 210410 too, on a Samsung Galaxy S20 with Android 11. I think this is a high-priority bug because all of the options below the fold are now inaccessible.

Attached is a screen recording of the bug. I've enabled "pointer taps" in developer options to illustrate the issue.

https://user-images.githubusercontent.com/295939/114282936-ddaee600-99fb-11eb-891c-26cf253d0d5e.mp4

**Comment by drannex42** [comment]
+1 to this, and the swipe up is user hostile for quick access, unsure if this was on purpose or related to the overall bug.

**Comment by JoGarWeb** [comment]
I have the same problem. Nokia 5.3 Android 10 
Its fucking frustrating. 




https://user-images.githubusercontent.com/7904563/114293364-1a5dfa00-9a5b-11eb-8a63-e83b3d50a1bf.mp4

**Comment by nandryshak** [comment]
Same for me, Galaxy Note9, android 10. Having to swipe the menu up in the first place is awfully silly when my screen can already display all the items on one screen without scrolling.

I'm able to tap the options in a new tab page though. But I can't refresh tabs without turning on pull to refresh.

**Comment by metronightly** [comment]
Yeah, facing the same issue on my Android 10 phone running Nightly 210411 version. Unable to add top sites, go to settings because the options are unresponsive. It takes around 10 taps for the options to work. 

Although I like that opening the three button menu shows only 2/3rd of the menu from top, hence easier to acces add-ons..I'm not ready for this kind of unresponsive consequences, lol.

**Comment by metronightly** [comment]
> I'm able to tap the options in a new tab page though. But I can't refresh tabs without turning on pull to refresh.

Is there any issue with pull to refresh other than unwanted refreshes, like more memory use or something. I have noticed that using pull to refresh limits my tabs on memory. Normally I'd be able to keep 5-7 tabs on memory without any reloading but turning it on reduces it to 3-5.

**Comment by Mugurell** [comment]
Thank you all for the reports and sorry for any issues.
This seems to be https://github.com/mozilla-mobile/fenix/issues/18814 which should be fixed in tomorrow's Nightly.

**Comment by Mugurell** [comment]
Not closing the ticket as a dupe it to keep it easily visible in the list of new issues and prevent others opening similar tickets.

**Comment by MicroBeast** [comment]
Fixed per Nightly 210412 13:58 (Build #2015804211) GPlay.

Thank you.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 4/13 with Samsung Galaxy Tab S3 (Android 8).
