### ISSUE TITLE
Remove unneeded animations in toolbar controller

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18971]
Followup to #18859, #18806

## Acceptance criteria
* Remove `browserAnimator` calls in `BrowserToolbarMenuController.kt` ([example](https://github.com/mozilla-mobile/fenix/blob/b41082ac637f382785da76e608807af21ab6f341/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt#L318)) and replace with normal `.nav` (note: make sure there is no change to the animations when you remove it) 

## Context

Looking at the docs for the method, it says:
>     /**
>      * Makes the swipeRefresh background a screenshot of the engineView in its current state.
>      * This allows us to "animate" the engineView.
>      */

That sounds rather confusing and unhelpful; we should update this.

Let's look at [the code](https://github.com/mozilla-mobile/fenix/blob/b3f5e557cce658abb20e482e85c755abd544f1b2/app/src/main/java/org/mozilla/fenix/browser/BrowserAnimator.kt#L48-L72) instead.

From what I can read, we're taking the EngineView and retrieving a thumbnail image from it to set as the background for the swipe-to-refresh layout.

So it seems like the idea of it is to show a thumbnail of the page, during an animation, when we navigate away from the browser.

Playing around with this code, I removed the method around settings to see what it looks like without this change compared to 'Addons' which also has the method wrapper:

https://user-images.githubusercontent.com/1370580/114457412-ffe76600-9bab-11eb-8a8f-1a1b50a80695.mp4

What I noticed is that with or without this change we see no change in the animations! My guess is, by also looking at the git history, this animator was used at a time when we did have animation and that bit of code was removed, where as this bit was not.

_Originally posted by @jonalmeida in https://github.com/mozilla-mobile/fenix/pull/18859#discussion_r611934459_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10354)

**Comment by gabrielluong** [comment]
I don't think this is a good first issue. I think we would want someone to investigate this thoroughly and present what is the state of our animations and really understands the code and make a call about it. If we do want to remove it, I think we should do this intentionally understanding the original intentions and what we are removing.

**Comment by eliserichards** [comment]
|  this animator was used at a time when we did have animation and that bit of code was removed, where as this bit was not.

Do you think there is more here that we're missing @gabrielluong?

**Comment by jonalmeida** [comment]
The code _removal_ is a good first issue. Confirming that we can remove this without regressions, probably isn't.

I only looked at that code while reviewing a menu PR. It's a bit narly, so I can't be sure that there isn't anything else this effects.

**Comment by gabrielluong** [comment]
> The code _removal_ is a good first issue. Confirming that we can remove this without regressions, probably isn't.
> 

@eliserichards Ya, I think it's latter part of this point that I would rather have someone on our team figure out -- the history bit of the Fenix animation, what was attempted and removed, and where is it now (did we just give up on animation completely because of perf? what was the PR which determined that and animation code removed? from that PR can we determine why we still have BrowserAnimator or was this code that did not get delete? Do we still need BrowserAnimator?). This is similar to how we were hunting for dead codepath in the toolbar navigation. For me, it is a theme of having someone on the team learn more deeply about the code and then determining its fate by being able to present about it and then making a proposal about what we should do. What we don't want is to simply remove the code, but still leave remanent that no one knows anything about.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813639

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
