### ISSUE TITLE
Scrollable full-height three-dot menu

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#18989]
#17772 was a mistake. I've read the ticket and there is no logical justification to force a reduced display height of the menu when the current orientation allows the complete menu to be shown. By the ticket's own logic, this would mean that an app, any app, should only utilise the maximum height based on the minimum height of the device's possible orientations! Seriously, the correct solution would, and should be, that the menu is always rendered to its full height even if the current orientation doesn't fit it and that the menu is scrollable, just like a webpage. That is the correct solution, and not what the ticket describes and implements.

**Comment by cadeyrn** [comment]
> mistake […] there is no logical justification […] Seriously […] the correct solution […] That is the correct solution, and not what the ticket describes and implements

This is not true, there is a logical justification. It is certainly fair to say that not everyone likes it. But it's not true to say that your preferred implementation is the only correct solution and everything else is wrong.

The expandable menu is easier to use for people who prefer to use their smartphone with only one hand. In fact I am not the only one who is interested in improvements for the one-hand usage, you will find other people in other issues in this issues tracker as well who advocated for one-hand usage improvements. So please respect that your opinion is not everyone's opinion.

By the way, Firefox is not the first application doing something like that. For example Oxygen OS, the operating system for OnePlus smartphones. It does something very similar in their apps like settings, messages or contacts: It does not use the full height in the first view so that you can reach everything with one hand. And they were also not the first…

**Comment by andreicristianpetcu** [comment]
My most common buttons are by default hidden: back, share, refresh and forward. Am I using it wrong? :)

![Screenshot_20210414-221133_Firefox_Nightly](https://user-images.githubusercontent.com/922368/114766539-315c5f00-9d6f-11eb-85c5-6d4b46afb898.png)
![Screenshot_20210414-221137_Firefox_Nightly](https://user-images.githubusercontent.com/922368/114766547-33beb900-9d6f-11eb-993d-ff05b1459a02.png)

I never click downloads, history, report site issue or sync.

**Comment by andreicristianpetcu** [comment]
Long press on the triangular back button is not the same as long press on the arrow button. The arrow button shows tab history on long press. The triangular button used to do this also but not anymore.
![Screenshot_20210414-222314_Firefox_Nightly](https://user-images.githubusercontent.com/922368/114767366-34a41a80-9d70-11eb-9820-c28e84f1619c.png)

**Comment by cadeyrn** [comment]
> My most common buttons are by default hidden: back, share, refresh and forward. Am I using it wrong? :)

This is #18591 and almost there.

> Long press on the triangular back button is not the same as long press on the arrow button. The arrow button shows tab history on long press. The triangular button used to do this also but not anymore.

Works for me. You should open a separate issue for that.

**Comment by eliserichards** [comment]
@andreicristianpetcu the sticky footer for the nav buttons has landed in Android Components and we are waiting for the version to be updated in Fenix. Your buttons will be back soon! 👍 

Closing this issue in favor of #18591
