### ISSUE TITLE
[Bug] Last opened tab hidden due to un-expanded tabTray

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#19023]
## Steps to reproduce
1. Have 10-15 tabs open, have the last tab selected as current tab
2. Open tabs tray
### Expected behavior
Scrolling through the list you should be able to see the last opened tab in list. Or the tabTray should have expanded to allow it to be visible.

### Actual behavior
Latest tab nowhere to be seen.

### Device information

* Device vendor / model and Android version: Pixel 3XL (Android 10)
* Firefox for Android version: Master (go to Settings -> About Firefox)

https://user-images.githubusercontent.com/60002907/114710331-410b8180-9d36-11eb-86c1-9053f203ac56.mp4

**Comment by jonalmeida** [comment]
Our RecyclerView seems to be a fixed sized, even if the amount visible is different. That might be at least part of the problem if not the entire thing.


https://user-images.githubusercontent.com/1370580/114741067-6be6dd00-9d18-11eb-9252-d9f5894b545d.mp4

Notice in the video above that the RecyclerView lines at the bottom do not alter after we've expanded it (because it's fixed to being the full length of the tray).
