### ISSUE TITLE
[Bug] New 3-dots menu: menu is not shrinkable by swiping down after being expanded

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#19075]
## Steps to reproduce
Note that this is in the case where the screen is larger than the expanded 3-dots menu.
Also, navbar&menu are set at bottom
Open a page
Expand the 3-dots menu by swiping up 
The menu is expanded
Swipe down on the menu (next logical move if the user changed his mind about what he wanted to do)

### Expected behavior
The menu goes back to non-expanded state

### Actual behavior
Nothing happens
You have to click elsewhere on the left side of the page, possibly needing to use another finger.
Not handy at all

### Device information
Redmi Note 7

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox) #2015804891

**Comment by Mugurell** [comment]
This is similar to https://github.com/mozilla-mobile/fenix/issues/19076, copying the same comment.

This is the expected behavior. Nothing changed regarding how the menu is closed.
After expanding the menu it might not fit the screen and needs to be scrolled up / down so there's no way to know if the user wants to scroll it or close it.
