### ISSUE TITLE
After setting Delete browsing data on quit, the Recently closed tabs can still be restored

### ISSUE THREAD

**Issue by xuyuehang** [mozilla-mobile/fenix#19073]
Nightly 210416 Build #2015804891

Have enable Delete browsing data on quit in setting, and checked all option. Then quit firefox in menu, and open it. Can still restore last open tabs in Recently closed tabs.

I want to know whether this design is intentional or a loophole. Because Recently closed tabs also belong Open tabs.
![Screenshot_20210416-144648_Firefox Nightly](https://user-images.githubusercontent.com/17559985/114983311-0be06a00-9ec3-11eb-9dda-87b1b536a666.jpg)

**Comment by jscher2000** [comment]
This also came up on SUMO. Seems like a bug to me. https://support.mozilla.org/questions/1333037

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview 88.1.2 and Nightly 4/29. However the issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/17986. I will close this issue as it will be handled there.

### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)
