### ISSUE TITLE
[Bug] Popping/crackling sounds when playing audio via bluetooth in fast forward mode

### ISSUE THREAD

**Issue by oratosquilla-oratoria** [mozilla-mobile/fenix#19102]
### Steps to reproduce
Play any audio (or video with sound) via bluetooth in the fast forward mode (Youtube, Vimeo, ...). E.g. [this video](https://www.youtube.com/watch?v=64D5g6Q6qR0) with x1.25, x1.5, x1.75, x2 speed.

When Chrome or Samsung Internet is used, everything is fine.

### Expected behavior
No popping/crackling sounds like when listening via wired head phones, speakers, ...

### Actual behavior
Popping/crackling sounds when playing audio via bluetooth.

### Device information
* Device vendor / model and Android version: Samsung A40 / Android 11
* Firefox for Android version: 87.0.0-rc.1

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1706131

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
From the Gecko Audo/Video team

Possibly, but could be underruns or a bug in playbackRate handling for 16-bit audio also. I wonder if the issue recovers immediately after reverting playbackRate to 1.0. We'll need to gather more detail to narrow the cause down. I don't have access a suitable device to test with, but if someone can reproduce this I have a few suggestions:

1. Try setting the pref media.cubeb.backend to aaudio, restarting, and retesting. If this helps, likely suggests an issue with the default (opensl) backend. Otherwise, if the issue is still reproducible with aaudio, please revert the pref change.
2. Grab a profile via https://profiler.firefox.com/docs/#/./guide-remote-profiling using the Media preset while the issue is occurring.
3. Enable logging (MOZ_LOG=AudioStream:5,cubeb:5) and reproduce the issue, attaching the resulting logs for analysis.
