### ISSUE TITLE
[Bug]No snackbar is displayed when sharing tabs from Tabs Tray

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19182]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open 2-3 tabs.
2. Open Tabs Tray.
3. Open the 3dot menu -> Share all tabs/ or Select Tabs.
4. Send the tabs to the connected devices.

### Expected behavior
A snackbar is displayed informing the user that the tabs were sent.

### Actual behavior
Nothing is displayed.

### Device information
* Device vendor / model and Android version: Huawei MediaPad M2	(Android 5.1.1), LG G7 Fit (Android 8.1).
* Firefox for Android version: ? (go to Settings -> About Firefox), Nightly 4/22, 89.0.0-beta.1

**Comment by jonalmeida** [comment]
@sflorean did your tabs tray have Synced Tabs in it (indicating that it's the new version)?

I didn't see the snackbar previously, so didn't spend time investigating if we needed one after sharing.

**Comment by Mugurell** [comment]
I remember a similar issue with the old implementation - https://github.com/mozilla-mobile/fenix/issues/15077

**Comment by jonalmeida** [comment]
> I remember a similar issue with the old implementation - #15077

Nice find, in that case, the toast was visually not seen. In the new impl, we aren't sending a toast at all.

**Comment by Mugurell** [comment]
I think it's the same issue.
The snackbar does appear but because [it's shown from the ShareFragment](https://github.com/mozilla-mobile/fenix/blob/0455cc3cd4b47a7d6153caa794cc2eb8a99a98aa/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt#L75), anchored to the activity, it will appear behind the Dialog (which has it's own Window).
Coming up with a clean solution will not be easy.
We'll also need to support the fab moving to not overlap the snackbar, as shown [here](https://github.com/mozilla-mobile/fenix/issues/15077#issuecomment-707687261).

Video showing the "Tabs sent" snackbar behind the tray in the current Nightly:


https://user-images.githubusercontent.com/11428869/120758663-c6cbd200-c51a-11eb-9efa-7cb014e332ac.mp4

**Comment by jonalmeida** [comment]
Ah yes, thanks for clarifying! Maybe dismissing the tabs tray after opening the share fragment would be a good UX fix for it?

**Comment by rocketsroger** [comment]
I'll be updating the fragment dependency through https://github.com/mozilla-mobile/fenix/issues/19921.

**Comment by lobontiumira** [comment]
Verified as fixed on the 91.0a1 Nightly from 6/24 with Google Pixel (Android 10), Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
