### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by marusc1** [mozilla-mobile/fenix#19222]
After last update screen content bacame unreadable. Looks kind like coded video. 

* Device vendor: Android 5.1 / Phone model: Ulefone Paris, same behavior on 2 phones.
* Firefox for Android version: 88.1.1

**Comment by mcarare** [comment]
@marusc1 Thank you for your report. This will be tracked in https://github.com/mozilla-mobile/fenix/issues/19230.

**Comment by jamienicol** [comment]
Hi @marusc1. I think I may know what the issue is. I've made a couple of APKs, if you could test them for me and let me know whether you still see the issue, that would be really helpful.

The first *should* reproduce the issue, and the second hopefully should fix it. Let me know if that is the case! Thanks!

1. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/JWka-2RuRvmpa7pCXs4YNw/runs/0/artifacts/public/build/geckoview_example.apk
2. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/WHnBdzWGS4GTuAIXp-WBCg/runs/0/artifacts/public/build/geckoview_example.apk
