### ISSUE TITLE
[Bug] Account creation at Germany's tax reporting page elster.de using AusweisApp2 fails, tries to open localhost (127.0.0.1) address in browser

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#19224]
## Steps to reproduce
1. Install Firefox.
2. Install the [AusweisApp2](https://play.google.com/store/apps/details?id=com.governikus.ausweisapp2) used for authentication.
3. In the browser, open the [account creation page](https://www.elster.de/eportal/wizard/seq/registrierungauswahl-1/kontotypauswahl-eop) for Germany's tax service.
4. Tap on the second option "Personalausweis (Komfortzugang)". (Click "Weiter" in case it open the previous page.)
5. Tap onto "Login mit AusweisApp2".

### Expected behavior
AusweisApp2 opened.

### Actual behavior
127.0.0.1:24727/... url loaded after message 'Login wird vorbereitet...' got shown.

### Device information

* Device vendor / model and Android version: Xperia XZ2 Compact with Android 10
* Firefox for Android version: 88.1.1 (build #2015804891), Nightly (90)
 
The "fix": The user opens the app's menu and requests to open the page in an app (would not expect a user to know that, also because this manual action is not required in Chrome).

**Comment by Sinsanga** [comment]
This is most likely a bug on elster.de, the tax website, not Firefox.

Connecting to 127.0.0.1:24727, which is the port AusweisApp2 is listening on, seems to be the way authentication is supposed to work from a desktop browser, see https://www.ausweisapp.bund.de/sdk/desktop.html 

The only way for a generic browser to open another app on a mobile device is to call a URL with a protocol previously registered by that other app. AusweisApp2 registers "eid" for this purpose; elster.de in turn needs to open "eid://127.0.0.1" instead of "http://127.0.0.1:24727" to start AusweisApp2.

At least Apple's iPads seem to have a similar problem as you have, see https://www.ausweisapp.bund.de/hilfe-und-support/haeufig-gestellte-fragen/#c3823  Safari opens websites in Desktop mode by default, resulting in a link to http://127.0.0.1 being used instead of eid://127.0.0.1, which would start AusweisApp2. The fix there is to let Safari open elster.de in Mobile mode.

Looks like elster.de is "optimized for Chrome" and thus fails to detect that your Firefox runs on Android, thus showing you the wrong link.
