### ISSUE TITLE
Tab list scroll position starts from the oldest instead of the newest (Regression)

### ISSUE THREAD

**Issue by krokofant** [mozilla-mobile/fenix#19231]
## Steps to reproduce
1. Open 100+ tabs (might be visible with less as well)
2. Open your newest normal tab
3. Switch to incognito and open a new tab
4. Switch back to the normal tab list

### Expected behavior
The tab list scroll position should start from the newest, at the bottom, as previous versions.

### Actual behavior
The tab list scroll position starts from the oldest, at the top.
This means i need to scroll a long way down to get to my newest tabs.

### Device information

* Device vendor / model and Android version: LGV30 Android 9
* Firefox for Android version: Nightly 210424 17:00 (Build #2015806539)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10523)

**Comment by SoftVision-LorandJanos** [comment]
Hi @krokofant  ! Thank you for your report! I can reproduce this issue on latest Nightly (210426 05:02 - GV90) and Nightly (210424 17:00). Opened over 100 tabs and observed the behavior after taking the steps described above. Actual result at my end was the 100th tab going to the top each time I do the steps.
Device used: Motorola Nexus 6 with Android 7.1.1.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01

**Comment by marcel263** [comment]
This is reproducable at least with tab grid.

Having interacted with private tabs, after which returning to normal tab tray, the last known scroll position i.e. selected tab is lost. Always scrolls to the top.

This behavior of forgetting the normal tab inconveniences common workflow for private tabs that were created from normal tabs ("open link in private tab" long-press menu option), e.g. a quick link check for untrusted domains, reading paywalled sites. Alas, a user might spend more time scrolling back to their last normal tab than they spent interacting with private tab, only becoming more impractical as one's tab count grows.

In short, normal tab position is always reset to the top after opening/creating private tabs while returning to normal tab tray. This behavior is inconsistent from the behavior when user merely switches between modes without any interaction, in that case normal tab tray position is remembered. Remembering last tab position (perhaps without selecting/opening, just scrolling) is beneficial for quick switching between modes.

edit: for reference, tested in chromium 89 this workflow of creating private tab from normal tab and returning to its 'parent' normal tab. Chromium remembers tab list scroll position in this case. Unfortunately no screencast due to security policy.

**Comment by chartmix** [comment]
Position sometimes gets also lost when in normal mode. Goes up to the top instead of the last position.

**Comment by chartmix** [comment]
Is there any update.
It is annoying to scroll so much because of the bug.

**Comment by bigConifer** [comment]
Looks like this is related to #23584.

See https://github.com/mozilla-mobile/fenix/issues/23584#issuecomment-1039030740.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812879

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
