### ISSUE TITLE
Change the default Android back button by a custom icon in all sub pages

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19258]
For the icons fresh we want to replace the default Android back navigation button  in all sub-pages (Settings, Bookmarks, History, Downloads, etc.) see https://github.com/mozilla-mobile/fenix/pull/19044#issuecomment-826465106 for more details

**Comment by mcarare** [comment]
@brampitoyo is the custom icon the "Large/Back" icon in this icon set: https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-(WIP)?node-id=2326%3A4?

If so, I do not see any difference from the one Android uses. Maybe the arrow shaft is longer?
Changing this is not trivial because the Android framework makes it hard to change even simple things, and in addition to that, we have some screens  (like History or Bookmarks) where we use custom support action bars.

If the arrow style is still the same and we just want to make the arrow shaft or the arrowhead bigger is it ok to do just does adjustments and not add a new drawable?


For exemplification (the arrow in red is the one with new icon specs) :
![Screenshot_20210507_120303_org mozilla fenix debug](https://user-images.githubusercontent.com/48995920/117426784-f93edb00-af2c-11eb-8fc9-964d48efaf56.jpg)
![Screenshot_20210507_120706_org mozilla fenix debug](https://user-images.githubusercontent.com/48995920/117426789-fa700800-af2c-11eb-9d47-41cd5bb62289.jpg)

Note: another parameter besides color that can be changed is thickness, but vissually I do not see any difference, nor can I see from Figma what is the value.

**Comment by brampitoyo** [comment]
Hi @mcarare, you’re right. That is indeed the correct asset to use.

Here’s our asset and Android system Material, side by side. Ours is on the left:

<img width="1664" alt="Screen Shot 2021-05-10 at 2 10 22 PM" src="https://user-images.githubusercontent.com/51007/117597340-7a020f00-b199-11eb-9012-35ad1388aa7e.png">

Ours is:

- 2px longer (1px to the left + 1px to the right)
- 0.5px thinner (1.5px line thickness, not 2px)
- Not vertically centred (0.25px closer to the bottom, so the arrow shaft aligns with the pixel boundary)

Is there a way for us to customise the Android default arrow shaft, head and line thickness, so it looks more similar to ours? If that’s the case, then we could pursue that approach instead of adding a new drawable.

What do you think?

**Comment by mcarare** [comment]
@brampitoyo Unfortunately those aspects are not customizable, so I will add the new drawable and make the changes programmatically. Thank you for your feedback and help!

**Comment by sheikh-azharuddin** [comment]
The forward button now seems inconsistent.. It is slightly thinner...
![Screenshot_20210513-085733523 (1)](https://user-images.githubusercontent.com/58127841/118073373-545b4c80-b3c9-11eb-9ab6-583bd647a22b.jpg)

**Comment by mcarare** [comment]
@sheikh-azharuddin That is not the back button that has changed, but the back navigation in the app bar. Those buttons are the same as they ever were.

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin That is not the back button that has changed, but the back navigation in the app bar. Those buttons are the same as they ever were.

My mistake.... Thanks for clarifying👍

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (90.0a1 - Thursday 5/13 @ 5:08).

Devices used: HTC Nexus 9 and Motorola Nexus 6.
