### ISSUE TITLE
Webpage is not scrolled when using Talkback' s "Read from next item" command

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#19268]
I'm able to duplicate this on a Pixel 4A 5G with all updates applied, 
Nightly as of yesterday, and the absolute latest TalkBack. I can find 
the exact version if needed. Here are my steps:

1. Visit https://www.kxan.com/weather/forecast/todays-forecast/

2. Find the title h1.

3. Use TalkBack's "Read from next item" command. I think the quickest 
way to do this is to swipe up/right, then tap "Read from next item." I 
have a custom shortcut defined for this and don't recall the default.

Firefox reads a bit, then says "Loading" and stops.

I don't think this is tied to highly specific component versions. I 
stopped using Firefox a few months back because of this bug. It doesn't 
happen with Brave, so it isn't a) a recent regression and b) something 
TalkBack does universally.

Thanks. Please let me know if I can provide further details.

_Originally posted by @ndarilek in https://github.com/mozilla-mobile/fenix/issues/17080#issuecomment-827731274_

**Comment by mcarare** [comment]
Aside from the STR provided by @ndarilek, if you select text from the bottom of the webpage and then use the "Read from next item" command you will notice that Talkback scrolls just to the next item directly below the last visible item, and after that, it just stops. This can be reproduced with both the bottom toolbar and the top toolbar.

**Comment by eliserichards** [comment]
@neha-b2001 and I have been investigating this. 

* The website in question is a local news station, and it seems like a good example of a common US-based news website, so this problem may be happening on others as well (this is probably a common use case in the US)
* The website has a lot of popup ads, which load as you scroll
* There are a lot of videos on the page, and while scrolling they seem to be loading only as they come into view
* Is the "Loading" that we are hearing from Talkback _actually_ the website loading things? (ads/videos?)
* This seems to be consistently reproducible on **Pixels**, but we are not able to reproduce it consistently on **Redmi Note 8 Pro**

Since the website is very busy (with a lot of videos and ads) and other browsers seem to handle this website correctly for Talkback, we are wondering if this is a GV issue?
