### ISSUE TITLE
Add second batch of icons

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19290]
See this https://github.com/mozilla-mobile/fenix/issues/18132#issuecomment-827315774 for context

Icons to update:

- [x] QR
- [x] lightbulb (`Report site issue` menu item)
- [x] pin outline (the new icon for `Add to top site` menu item; when a site has been pinned, this icon changes into a pin-fill)
- [x] bookmark-fill (after a page has been added to bookmark, we change the outline bookmark star into a fill)
- [x] more-vertical
- [x] chevron-right (next to `Add-ons` menu item)
- [x] chevron-up (inside `Find in page`)
- [x] chevron-down (within `Find in page` and `Saved logins`)
- [x] lock-blocked
- [x] avatar-signed-in-fill
- [x] avatar-signed-out (the new icon for `Sign in to sync` menu item – replacing
- [x] avatar-confirm-email
- [x] avatar-alert (icon to be finalised very soon)

**Comment by brampitoyo** [comment]
Hi Arturo, happy to report that most of these icons have been correctly replaced and looks good to go!

There are 5 icons in this batch, that has issues.

> `lightbulb` (`Report site issue` menu item)

The icon itself is correct; but for some reason, it doesn’t get colourised correctly on dark theme.

<img width="360" src="https://user-images.githubusercontent.com/51007/117091351-12ba1880-adaf-11eb-9e58-bc83be0064e6.png">

-----

> `chevron-right` (next to `Add-ons` menu item)

This icon looks thinner and smaller than it’s supposed to. Below is the current screenshot, compared to a proposed design where the icon has been sized at 24x24.

I wonder if we need to adjust the size of the current icon? Let me know, and I can generate a special version for this purpose!

| Current | Proposed |
| --- | --- |
| <img width="360" src="https://user-images.githubusercontent.com/51007/117091484-878d5280-adaf-11eb-9675-d723c659630a.png"> | <img width="360" src="https://user-images.githubusercontent.com/51007/117091490-8bb97000-adaf-11eb-87dd-155baa2abb73.png"> |

-----

> `lock-blocked`

This one will require a red line. My mistake for not colouring it correctly!

The right colour has now been added on the [icon’s Figma artboard](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=2326%3A74).

Let me know if you’d like me to create a separate light and dark versions.

-----

> `avatar-confirm-email`

This icon has been recently redrawn. Would you mind updating it to this new version?

Instead of an email symbol, it now contains the letter `i` inside a circle shape. See this [icon’s Figma artboard](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=2326%3A78).

-----

> `avatar-alert`

This icon is already correct. Just making sure that it has an exclamation mark symbol inside a triangle shape? See [this icon’s Figma artboard](https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=2326%3A86).

**Comment by scheinercc** [comment]
Is `lock-blocked` the one used for insecure HTTP connections? I saw that the "plain" lock (HTTPS) and the lock with a dot (HTTPS + site specific permissions) have been updated already. The crossed-out lock, e.g. from visiting http://example.org (without HTTPS only mode), is still the old one.

**Comment by cadeyrn** [comment]
> The crossed-out lock, e.g. from visiting http://example.org (without HTTPS only mode), is still the old one.

https://github.com/mozilla-mobile/fenix/pull/19355 and https://github.com/mozilla-mobile/android-components/pull/10196 have not yet been merged. None of the icons from the first comment are already in Firefox Nightly.

**Comment by Amejia481** [comment]
* The **lightbulb color** is a known issue, and it's getting tracked on https://github.com/mozilla-mobile/fenix/issues/11367
* The **chevron-right**, I updated it :)
<img width="274" alt="image" src="https://user-images.githubusercontent.com/773158/117162277-a16b6d00-ad90-11eb-9453-218c286b2d6b.png">
* The **lock-blocked** icon will require some extra work for the red line as we are changing the color for the whole asset, and it's changing the color line this will be covered here https://github.com/mozilla-mobile/android-components/issues/10225. 


https://user-images.githubusercontent.com/773158/117171975-5dc93100-ad99-11eb-8c36-150df8167857.mp4


 
* The **avatar-confirm-email**, it's already updated. I added as part of the project, but we never used it before we have to added as followup.  
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/773158/117159306-2acd7000-ad8e-11eb-9567-1da19a14b691.png">

* The **avatar-alert**, yeah this one is using the acclamation mark

<img width="726" alt="image" src="https://user-images.githubusercontent.com/773158/117161734-2c983300-ad90-11eb-8448-90bd11d94b13.png">

**Comment by brampitoyo** [comment]
Thanks heaps, @Amejia481, for your comments.

They all look good to me!
