### ISSUE TITLE
[Bug] Click to chat using api.whatsapp.com does not work in Firefox Mobile

### ISSUE THREAD

**Issue by EKanadily** [mozilla-mobile/fenix#19378]
Using CHROME on ANDROID:

Go to website  https://api.whatsapp.com/send?phone=<fill a phone number in internationl format>

>> please fill the phone number in the above url <<

Click on "continue to chat"

Whatsapp application opens and I can chat directly with the Whatsapp Account

----------------

Using FIREFOX on ANDROID:

Go to website  https://api.whatsapp.com/send?phone=<fill a phone number in internationl format>

>> please fill the phone number in the above url <<

Click on "continue to chat"

Actual results:

the page says : Looks like you don't have WhatsApp installed!
there is a download button on the page , when i click the download button it redirect me to the url :

https://play.google.com/store/apps/details?id=com.whatsapp

where I am supposed to download WhatsApp.

I am not on the US store. will that make a difference?

expected results:
WhatsApp app should open with immediate ability to chat with the said number

### Device information

* Device vendor / model and Android version: ?
galaxy s10e (SM-G970F/DS)
android 11

* Firefox for Android version: 
*88.1.2 (Build #2015806939)
AC: 74.0.12, cad1e5a98
GV: 88.0.1-20210426133657
AS: 74.0.1

**Comment by jonalmeida** [comment]
> Whatsapp application opens and I can chat directly with the Whatsapp Account

I followed these steps but I don't get to this result on Chrome Canary (92) and Beta (91). Instead, I'm taken to the Play Store for the Whatsapp listing where I have to click the 'Open' button there to open the app.

On Firefox, with the same steps, I have the Play Store open up in the browser itself. If you go to Settings > Open link in apps and enable it, then the functionality matches what I'm seeing on Chrome as well.

**Comment by EKanadily** [comment]
i didn't know about the 'open in app' option. the chance is : visitors don't know too.

I think the browser should fire a pop up asking the user if he want to open the link in app. some other applications in android does that.

**Comment by jonalmeida** [comment]
The option is available in the three-dot menu as 'Open in app' when we detect that an external app can handle the intent, but we don't leave the page unless explicitly requested to, or the user has set the 'Open links in apps'.

This is done by design to avoid apps trying to hijack web browsing sessions from users.

**Comment by amitay87** [comment]
@jonalmeida 
I think that most users don't know they should click the "Open links in apps" in order  to open a whatsapp link. I think that the feeling is that Firefox is behind Chrome and I think we should not allow this to happen because it is our common interest to keep Firefox popular and relevant among "regular people"
I think we should add some kind of a toast or tooltip that will explain that if the user wants to open the link in external app and he trust this link after he understood why this type of link should not be opened automatically, then he can click the "Open links in apps" button
