### ISSUE TITLE
[Bug] The name on the Card is not mandatory and a card can be saved without a name

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19495]
## Steps to reproduce
1. Access the credit cards section.
2. Tap on the Add credit card button.
3. Add a correct credit card number but let the name field empty.
### Expected behavior
An error should be displayed, asking for the name on the card, in order for the card to be saved.
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**
 
https://user-images.githubusercontent.com/42831109/118135881-2f3bfd80-b40c-11eb-81a5-14e794816a3c.mp4

**Comment by gabrielluong** [comment]
Checking with @topotropic if the name should be mandatory.

**Comment by kbrosnan** [comment]
Desktop does require at least a single character.

**Comment by amedyne** [comment]
@topotropic need your input on this one. Thanks!

**Comment by gabrielluong** [comment]
@topotropic This is currently what we're doing for credit card validations https://github.com/mozilla-mobile/fenix/pull/19267. 

<img src = https://user-images.githubusercontent.com/48995920/117116546-29ed0c00-ad97-11eb-9cd4-003073df6c13.png width = 45%>

We will need a string assuming we do the same thing.

**Comment by topotropic** [comment]
This could work w/o entering a name at least on mobile from a user point of view, it just adds friction every time you want to autofill it; not sure what happens when you enter a credit card w/o name on mobile and then sync it to FX desktop though. 

That said, the goal is to make it quicker for people to autofill their credit card, and name on card is required for validation. Let's make the name field mandatory and we can use the same string we use on FX desktop "Please fill out this field". Thanks!

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 6/9 with Google Pixel 4 XL (11).
Note that the `Please fill out this field` text was displayed when I tried to save a card without a name.
