### ISSUE TITLE
FNX-5345 ⁃ [Bug] Bookmark separators aren't handled well visually

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#1949]
See screenshot:

![Screenshot](https://user-images.githubusercontent.com/465422/56615980-35ff3a00-65d1-11e9-9679-d47056cd3838.png)UNITO-UNDERSCORE!1556053116!

**Comment by colintheshots** [comment]
This has definitely improved visually from where it was. We can look at more improvements post-MVP.
![device-2019-06-04-164225](https://user-images.githubusercontent.com/626405/58976715-c06cb900-878d-11e9-8a23-6cbf609b1e07.png)

**Comment by bifleming** [comment]
@colintheshots do you know if we still need UX help with this? @mheubusch

**Comment by mheubusch** [comment]
@AmyYLee another bookmark visual design issue - I think Colin is asking that you review and approve the current implementation or point back to the implementation checklist issues that still remain.

**Comment by AmyYLee** [comment]
Assigning to @topotropic since she worked on bookmarks.

**Comment by topotropic** [comment]
It looks better now, agreed. 

If we want to improve this, we could remove the 3-dot menu which adds visual noise and since we don't support adding a separator we could also not support removing separators. Visually we would have a 1dp separator with 16dp spacing on each side. But, maybe let's ignore this for now and close the issue? @vesta0 
![Copy 2](https://user-images.githubusercontent.com/353960/60668444-4868e000-9e6c-11e9-964f-6eeb59d4aa9b.png)

**Comment by vesta0** [comment]
Thanks @topotropic ! Is this Eng ready or do we need @shorlander approval?

**Comment by topotropic** [comment]
Talked quickly to Stephen, it's alright.

**Comment by topotropic** [comment]
test CC @mozilla-mobile/ux

**Comment by softvision-miralobontiu** [comment]
Verified on a today debug build 1.0.1928 GV 68.0-20190612114833 with Motorola Moto G6 (Android 8), and Nexus 6 (Android 7.1.1).
