### ISSUE TITLE
Password / Logins Autofill function fails with Dashlane

### ISSUE THREAD

**Issue by Udayanithig** [mozilla-mobile/fenix#19599]
Most of the time autofill function by using password managers simply fails or half baked. But on the other hand, the chromium-based browser doesn't have this issue. I have replicated this issue through video by comparing firefox mobile and brave. 

[Comparing firefox and brave](https://www.dropbox.com/s/ql4yh9boom2gga1/Autofill%20Function%20.mp4?dl=0) 

Version : 88.1.4
Device : Motorola One Fusion Plus
OS : Android 10

**Comment by smithed** [comment]
I was just looking at this issue below and wanted to see if there were any other related ones and...yours happened to be right here.

The problem was identified here:
https://github.com/mozilla-mobile/fenix/issues/16583
and put into bugzilla here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1693152

In the issue 16583 thread it was identified as a few lines of code (https://github.com/mozilla-mobile/android-components/commit/7899ed6bbd64acbdc347d5ae6d50624551d944b8) , but at this point its been about 6 months since the regression was introduced and a little over 3 months since being identified. Bugzilla shows that it has been repeatedly deferred. I am not personally expecting a resolution in the near term. I'm currently on the fence about just switching back to chromium on mobile (bromite, not brave), but I like sync'd bookmarks and tabs.

**Comment by Udayanithig** [comment]
Yeah, chromium-based browsers don't have these issues.  But interestingly When I switched to NordPass, the password/logins auto-filling worked as great as a chromium-based browser. But I'm still curious to know from what end the problem raised.

**Comment by Udayanithig** [comment]
I still have issues with password manager autofills on firefox. Even with NordPass

**Comment by Udayanithig** [comment]
Hoping it will be fixed. It is annoying and frustrating.

**Comment by Udayanithig** [comment]
Please fix this issue asap.
