### ISSUE TITLE
"Cancel" and "Save" buttons are cut off the screen in landscape when adding a new card

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19636]
## Steps to reproduce
1. Reach the credit cards section and access `Add credit card`
2. Rotate the device in landscape mode.
### Expected behavior
The elements from the screen in landscape mode should be resized in order to have full access to all buttons.
### Actual behavior
 "Cancel" and "Save" buttons are cut off the screen in the landscape when adding a new card
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/25.**

 ### Notes
Note that the section is scrollable but there are many big spaces and it can be resized in order to have everything on the screen without scrolling.

![20210525_113655](https://user-images.githubusercontent.com/42831109/119467064-df373200-bd4d-11eb-9f0b-656ca7d1944e.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10775)

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on the:
- latest Nightly 96.0a1 (2021-11-22).
- latest Beta (95.0.0 beta4).
- latest Release 94.1.2.
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 110.0a1 (2023-01-17) with the following detail to add:
Both "Save" and "Cancel" buttons are hidden entirely and needs scrolling to display them.
Device used: Oppo Find X5 (Android 12).
![PXL_20230117_115121414](https://user-images.githubusercontent.com/48829350/212892532-1ac1370a-1bb2-46f5-b855-5273e4673db2.jpg)

Reopening the ticket.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814140

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
