### ISSUE TITLE
[Bug] "Sync Firefox between devices" padding issue

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19661]
## Steps to reproduce
1. Launch Firefox 
2. Check the "Sync Firefox between devices" onboarding card

### Expected behavior
Same padding of the  "Sync Firefox between devices" heading as on the other onboarding cards

### Actual behavior
No padding between the "Sync Firefox between devices" heading and the description

### Device information
* Device vendor / model and Android version: 
• OnePlus A3 (Android 6.0.1)

* Firefox for Android version:
• Nightly 90.0a1 from 5/26
• RC 89.1.0 from 5/26

### Notes
► Screenshot
![image](https://user-images.githubusercontent.com/51314259/119617899-f556f800-be0a-11eb-8ddb-2e078dad0ff8.png)

**Comment by Nickoriginal** [comment]
Also for Russian locale

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20219

**Comment by Nickoriginal** [comment]
Fixed in Nightly **91.0a1 2021-07-05T17:06:08.350**
<img src = https://user-images.githubusercontent.com/85299944/124509235-424ec680-ddda-11eb-83e5-ba5707095d0b.jpg width = 45%> <img src = https://user-images.githubusercontent.com/85299944/124509590-f3edf780-ddda-11eb-84bc-c2cb76038410.jpg width = 45%>
Now it have the same padding 
between heading and the description as on the other onboarding cards in Russian and English.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 7/9/21 with Google Pixel 4 XL (11).
Note that I verified in EN, RU, DE and the padding was correct.
