### ISSUE TITLE
Using <img srcset> doesn't work to serve different images to mobile devices.

### ISSUE THREAD

**Issue by spercy16** [mozilla-mobile/fenix#19725]
I am using the <img> element with "srcset" and "sizes" attributes to serve different images to mobile devices depending on the display's resolution. This method works correctly on the desktop version of Firefox, as well as Chrome on Android, however Firefox for Android displays the desktop image instead of mobile. The basic code I'm using is this:

`<img src="/images/mobile-image.jpg" srcset="images/desktop-image.jpg 1920w, images/mobile-image.jpg 800w" sizes="(min-width: 800px) 1920px, 100vw" />`

This is the simplest way I've found to accomplish this task without using (more complicated) javascript, and without loading the other image unnecessarily. If someone at Mozilla could look into the issue I would greatly appreciate it, as it's making a couple of my elements (that have text on top of them) display incorrectly in Firefox on Android. Thank you!

**Comment by Amejia481** [comment]
Hi @spercy16  thanks for filing the ticket, the rendering and parsing of web content is done on [GeckoView](https://mozilla.github.io/geckoview/) library,  I filed a ticket the team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1713611. Please add the GeckoView version to help the team, you can find it under `Settings` -> `About Firefox`.

![image](https://user-images.githubusercontent.com/773158/120201695-bbfbff00-c1f3-11eb-88e6-bc482d8c632a.png)


Additionally, if you haven't try it yet you could see if the issue is reproducible on [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix).

Please let continue the discussion on the [Bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1713611), for  helping the team gather all the related information.
