### ISSUE TITLE
[Bug] Improperly displayed open links in apps banner in landscape view

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19760]
## Prerequisites
• Have a fresh install or a clean profile
• The Youtube app should be installed on the device

## Steps to reproduce
1. Navigate to youtube.com
2. Wait for the open links in apps banner to be displayed
3. Rotate the device to landscape mode

### Expected behavior
Properly displayed banner

### Actual behavior
Improperly displayed banner.
Doesn't align with the width of the view in landscape mode 

### Device information

* Device vendor / model and Android version: OnePlus A3 (Android 6.0.1)
* Firefox for Android version: 
• Beta 90.0.0-beta.1 from 6/2
• Nightly 90.0a1 from 6/2
 
### Notes
► Video
![20210602-111444](https://user-images.githubusercontent.com/51314259/120455040-16848f00-c39d-11eb-9681-6aed03f9665a.gif)

**Comment by lobontiumira** [comment]
On Samsung Galaxy Tab A6 (Android 5.1.1), the banner is displayed improperly in portrait mode also:
![IMG_20210604_054029](https://user-images.githubusercontent.com/40694158/120496613-60359f80-c3c6-11eb-82e6-fb2fb1a27140.jpg)

**Comment by sflorean** [comment]
See also #19288.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest builds with the following devices:
- Google Pixel 4 (Android 12).
- Oppo Reno 6 (Android 11).
- Samsung Galaxy Tab S3 (Android 9).
- LG Nexus 5 (Android 6.0.1).


Verified on the following builds:
- latest Nightly 98.0a1 (2022-02-07).
- latest Beta (97.0.0-beta6).
- latest Release (97.1.0).

Closing the tiket as fixed.
