### ISSUE TITLE
[Bug] tab navigation is not working in home page

### ISSUE THREAD

**Issue by RadhakrishnanKandasamy** [mozilla-mobile/fenix#19839]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Enable "swipe toolbar to change tabs" option from settings -> customize
Open a website in a tab. (Ex: www.google.com)
Open another tab and open one website
Open new tab (firefox home page)
On firefox homepage when you swipe the toolbar nothing happens
But when you swipe in any of the other two tabs navigation is working fine
### Expected behavior
Navigation should work
### Actual behavior
Navigation is not working
### Device information
Realme U1 / Android version 9
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)
 Firefox version 89.1.1

**Comment by Dunexus** [comment]
I think this is because homepage isn't treated as a real tab.

Turning homepage into a real tab has been discussed in several issues but i'm not sure why it ended up being closed.

See https://github.com/mozilla-mobile/fenix/issues/18607, https://github.com/mozilla-mobile/fenix/issues/12774, https://github.com/mozilla-mobile/fenix/issues/11633

Cc @topotropic for UX feedback

**Comment by kbrosnan** [comment]
This is expected behavior currently.
