### ISSUE TITLE
[Bug] Private mode: Cookies / cookie settings are deleted when tab changes to background

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#19850]
## Steps to reproduce
Open a new tab in private mode. Cookies or cookie settings (e.g. rejection) are set after a query.

Switch to another private tab, go to standard mode or switch completely to another app (multitasking).

Return to the private tab from the beginning.

### Expected behavior
Set cookies and settings are retained as long as the private tab is open.
### Actual behavior
Instead, cookies or cookie settings are often deleted. Result: Sessions are ended, e.g. logouts follow. Cookie queries pop up again.
### Device
* Samsung Galaxy XCover 4s, Android 10
* Firefox for Android version: 89.1.1

**Comment by kbrosnan** [comment]
Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1709483

**Comment by WebworkrNet** [comment]
I agree.

What will happen now?
Referenced Bugzilla ticket is closed.
But the problem still exists.

**Comment by cadeyrn** [comment]
Did you test in Firefox Nightly? The Bugzilla ticket is closed as a duplicate of another one that was closed as fixed two days ago. This means the fix of this ticket is in Firefox Nightly and not yet in Firefox Beta or the stable release of Firefox.

**Comment by cadeyrn** [comment]
The Bugzilla ticket is closed as a duplicate of another one that was closed as fixed two days ago. I can't say if the fix is already included in Firefox Nightly but since a new GeckoView version has to made its way into the Android Components and then a new version of the Android Components has to be integrated in Firefox it can take a few days until the bugfix arrives in Firefox Nightly.

**Comment by WebworkrNet** [comment]
Ah, I see, thank you for the clarification. :-)

Where can I look up in which Nightly version the bug is fixed?
