### ISSUE TITLE
Multiple store bindings cause visual delay in animations on tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19894]
As to where that delay comes from: all the bindings set on that same store.
Saw that commenting them fixes this issue with the tray hiccup. Nothing to be done about them but something to keep in mind for later such uses.

_Originally posted by @Mugurell in https://github.com/mozilla-mobile/fenix/pull/19812#discussion_r647562378_

**Comment by Mugurell** [comment]
About the animations delay in tabs tray, since this issue was seen in an open PR I'll just workaround to not depend on store updates for immediate UI changes.

I feel it's important to keep in mind though that it is possible to have multiple `AbstractBinding`s or just multiple listeners for the same store updates and this will have an impact on the delay with which updates will be received, something may prove to be an issue in various scenarios.

**Comment by mcomella** [comment]
I spoke with @jonalmeida about this and iirc we thought creating a benchmark 1) to understand the size of the perf impact and 2) to prevent regressions could be helpful here. I'm opened a PR to intergrate Jetpack Benchmark (microbenchmark) in https://github.com/mozilla-mobile/fenix/issues/19901 – perhaps that'll be helpful for this.

**Comment by mcomella** [comment]
Triage: we're unclear how large this delay is in order to prioritize. @jonalmeida can you provide a profile or a video of this behavior, preferably on a low-end device?

**Comment by jonalmeida** [comment]
In the last triage I mentioned that we can close this since it's no longer an issue any more. I believe it was an outcome from how we were initially connecting the store's flow to a bit of UI that was blocked on the async result.

We can re-open if you feel strongly about it.
