### ISSUE TITLE
FNX-5383 ⁃ [UX] Find in Page

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#199]
**User Story:**
As a user, I want to be able to search for a work on a site and quickly find it so I can have a fast browsing experience. 

**Current Design Status:**

* Copy designs from Focus

**Comment by sblatz** [comment]
@shorlander there is a newly created component found [here](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/findinpage/README.md) which I am integrating. I agree with not needing to reinvent the wheel on this feature!

**Comment by sblatz** [comment]
Here is the current implementation. The colors can easily be swapped as needed. Currently the background is "off-white," and the count as well as buttons are "primary-color."

<img width=250 src=https://user-images.githubusercontent.com/4400286/52006045-0c29f180-2480-11e9-8621-fb9f2bea0bef.png>

**Comment by yoasif** [comment]
Find in page looks super weird as compared to every other Android browser I have tried as it stacks the find bar above the location bar instead of appearing in the same place. 

In other browsers (Edge, Kiwi, Opera, Bromite), the find box appears in the same place as the location bar/toolbar. Since the toolbar is visible when a user opens the find in page toolbar, the location bar/toolbar remains visible if the user clicks the "x" to dismiss the find bar. 

Focus is the unusual one here, since it opens the find bar at the bottom of the screen *and hides* the location toolbar. Dismissing the find bar doesn't show the location bar again. 

I prefer the Edge, Kiwi, Opera, Bromite behavior, as it feels seamless and fluid, and doesn't look as weird as stacked toolbars.

**Comment by rituraj22** [comment]
For find in page, I think a highlight for matching strings which are not focused (similar to that in chrome and other browsers) would be nice.

**Comment by yoasif** [comment]
>For find in page, I think a highlight for matching strings which are not focused (similar to that in chrome and other browsers) would be nice.

This works in Focus today, so I would expect for it to make it over in Fenix.

**Comment by bbinto** [comment]
Find in Page is already working (via existing a-c component), do we need to update the UX based on some comments here, or is UX ok with the implementation?

@lime124?

**Comment by brampitoyo** [comment]
@bbinto I notice a couple of small issues with our Find in Page implementations, that needs to be fixed.

1. As @yoasif has pointed out, the find bar should appear in the same place as the address bar, not stacked on top of it.
    * As a result, when the find bar is open, it must first be closed (either by tapping “x” or tapping the system back button) to show the address bar again.
2. When the find bar highlights a match, all the other matches on the page should also be highlighted, as in this example:

<img width="360" src="https://user-images.githubusercontent.com/51007/54732883-215b0b00-4bfb-11e9-9d73-6bbfb5c2435f.png">

In the example above, currently highlighted text has the colour `green-60` `#2ac3a2`, and all the other highlights have the colour `yellow-20` `#ffea80`.
