### ISSUE TITLE
Investigate whether top sites should be opened in the existing tab when navigated through the home screen

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#19930]
I totally understand the new home button is just landed in nighlty but I just discovered that if I M on a website and then I tap home button and finally a top site, the top site is opened in a new tab, so the home button right now is totally useless!
it 's nothing but like "opening a new tab"
please fix it!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10977)

**Comment by LittleAngelwings** [comment]
This behavior is just right for me and more intuitive. If I press the "+"-button I get the keyboard for typing a new URL manually. Sure I can touch also a top site icon directly, but with the new Home-button I see the homescreen without an open keyboard.

**Comment by ale82to** [comment]
by definition home button must open top sites or search in its own tab not creating a new tab (see Samsung internet, chrome, yandex and so on). there re already plenty of way to open a new tab in fenix (ex long press tab switcher) there e no need for a renduntan behavior

**Comment by cadeyrn** [comment]
I agree with LittleAngelwings.

> by definition 

There is no such "definition".

**Comment by AlaaGoma** [comment]
،،،،،،.........زن
ظوة،،🤔🤔🤔🤔

**Comment by ale82to** [comment]
in Firefox desktop home button PRESERVE history and does not open a new tab so for many years Firefox desktop behaved bad? , come on!

**Comment by cadeyrn** [comment]
The home button didn't change the behaviour of the home screen at all.

**Comment by azerto11** [comment]
I don't think it's _wrong behaviour_ , it's just different than most other browsers (including Firefox Desktop). But personally, I feel that it slows down my browsing. As a user, I expect the home button to take me to home page, and open the _top sites_ that I click on in the same tab. Because, I have a faster way of opening a new tab (_long pressing the tab button_) if I need.
If after pressing the home button, top sites are opened in new tab, I have to open the tabs menu, and then manually close the previous tab I came from. This seems more of _home screen_ issue than of _home button_ as mentioned in #20012. Please take a look at this.

**Comment by M-Reimer** [comment]
This issue still exists and still makes the "home site" very annoying to use. And 🎉surprise🎉 marking it "wontfix" just because of the issue being not handled doesn't solve the actual problem.

**Comment by ishanjain28** [comment]
Where is this issue being tracked exactly? There are 2-3 threads open for this. 

This is quite obviously not how a home button is supposed to work!? When I press home, Switch to another tab and come back to it, It should still be on home? Why does the tab remain open? 


This makes browsing an extremely annoying experience because I use it for 5 minutes and suddenly I have 20 tabs open that I then have to close manually. 


The "Close tabs automatically after X" option is not a solution for this. 
Please fix this behavior.



https://user-images.githubusercontent.com/7921368/179382432-c1da89fd-c2a0-4fe8-baf3-45777a55b07c.mp4

**Comment by M-Reimer** [comment]
Still an issue. Probably already handled elsewhere but someone has to check.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813665

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
