### ISSUE TITLE
[Bug] Video playing as black with only Audio

### ISSUE THREAD

**Issue by ragavendranbala** [mozilla-mobile/fenix#19986]
## Steps to reproduce
visit this link 
https://threejs.org/examples/?q=video#webgl_video_panorama_equirectangular

and this link  
https://threejs.org/examples/?q=video#webxr_vr_video

On firefox mobile

### Expected behavior
Both videos should play correctly

### Actual behavior
Video is playing in background but it's black

### Device information
Oneplus 9, 7T, Nord
* Device vendor / model and Android version: ?
Android 11
* Firefox for Android version: ? (go to Settings -> About Firefox)
 91.0.a1
 89.1.1

I have checked on other browsers like brave, chrome for mobile and even on desktop firefox. All are working as expected but not working on Firefox Mobile

**Comment by SoftVision-LorandJanos** [comment]
Hi @ragavendranbala ! Thank you for your report! I was able to reproduce the issue you described.
Tested on the latest Nightly (Monday 6/14 @ 5:07 AM).
Verified it on Desktop version of the latest Nightly and Release and on Chrome mobile where this issue is not reproducible.
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by ragavendranbala** [comment]
@SoftVision-LorandJanos great! hoping a fix or steps to fix soon!

**Comment by marcusx2** [comment]
Any ETA to fix this? This bug happens on Mac too. Basically, it works on Windows with hardware acceleration disabled, it works on iPhone, but fails on Mac and Android.

**Comment by ispysoftware** [comment]
this is still broken

**Comment by Juriyx** [comment]
The author hasn't specified that this is not a problem with videos but with VR videos only

**Comment by kbrosnan** [comment]
Pretty sure this is bz-1709661. It will be handled there.

**Comment by amzamzamzamz** [comment]
Both works fine
