### ISSUE TITLE
[Bug] Going from private tabs straight to homescreen doesn't show the "Jump back in" section

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#20046]
## Steps to reproduce
- have some normal tabs opened so the "Jump back in" section would appear
- open a new private tab
- open tabs tray from that private tab
- scroll the tray to normal tabs but don't click on any
- click the "+" fab to go to homescreen

### Expected behavior
The "Jump back in" section would appear allowing to view and quickly jump to the normal tabs.

### Actual behavior
No "Jump back in" section.

### Device information
Any device.
Current Nightly.

https://user-images.githubusercontent.com/11428869/122227285-6dbb5100-cebf-11eb-80fa-068fb58d23f8.mp4

**Comment by Mugurell** [comment]
This happens because when browsing in private tabs the `selectedTabId` is of a private tab and when the recent tabs are to be shown on homescreen [we only iterate through normal tabs](https://github.com/mozilla-mobile/fenix/blob/15df06b294018103f7ca4179925d2ffa7695ee52/app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt#L35) searching for the selected one to show.

I remember an older issue about the same "bug" affecting now the tabs tray in which Sebastian proposed to postpone adding support for separate selected tab ids - normal/private tabs https://github.com/mozilla-mobile/fenix/issues/5877#issuecomment-627325679 .
Not sure there've been developments around this area that we can use. @pocmo ?

In the interim because I think it's more important to show that "Jump back in" section I propose showing [the last accessed normal tab](https://github.com/mozilla-mobile/android-components/blob/e535713ea8eca6528c4c0d44fea9c829ff7a3989/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt#L28).
(Curious if there would be any difference between this and using the `selectedTabId`. Guess this property exists only as an easy way to get the id without having to iterate through all tabs?)

**Comment by pocmo** [comment]
> I remember an older issue about the same "bug" affecting now the tabs tray in which Sebastian proposed to postpone adding support for separate selected tab ids - normal/private tabs [#5877 (comment)](https://github.com/mozilla-mobile/fenix/issues/5877#issuecomment-627325679) .
> Not sure there've been developments around this area that we can use. @pocmo ?

Yeah, I still think we should not change the semantic meaning of "selected tab". It's the active tab we would show whenever you go to the browser and it's in sync with concepts like the "current tab" in the webextension APIs.

> I propose showing the last accessed normal tab.

I think that is a great solution and makes more sense to me for a "jump back in" section: Show the last (normal) tab (or even multiple!) the user interacted with. I would even consider always using this instead of "selected tab"? And we could even add an extension function for this [to A-C](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt).

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/24 Nightly 91.0a1 build with Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Note 8 (Android 9), and Google Pixel (Android 10).
