### ISSUE TITLE
Fix Async NavGraph after update to AppCompat 1.3

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#20077]
After updating to AppCompat 1.3 (https://github.com/mozilla-mobile/fenix/issues/19921) , we had to revert the asynchronous changes we made to the navgraph inflation (https://github.com/mozilla-mobile/fenix/pull/18889).

**Comment by mcomella** [comment]
In debugging this issue in the PR #20176, we've hit a challenging situation. The async nav graph changes break with the following STR (which is represented in the test, `SettingsPrivacyTest.launchLinksInPrivateToggleOffStateDoesntChangeTest`):
- Clear app data
- Launch app
- Enable Settings -> Private Browsing -> Open links in a private tab
- Hit back to return to browser homescreen
- Load a website (e.g. apple.com)
- Add a homescreen shortcut for it in the 3-dot menu. Add the shortcut automatically
- Click the homescreen shortcut

Expected: opens existing website tab (note: I personally think this should open a new private tab with the website but that's a separate issue)
Actual: opens homescreen

This issue cannot be reproduced before the async nav graph changes and occur on an Pixel 2 API 28 emulator but not my Pixel 2 API 30 physical device.

The cause of the issue seems to be related to how we recreate the activity to switch into private browsing mode. We've noticed some strange behaviors and discrepancies in this code:
- Strange: `activity.recreate` gets called twice
- Discrepancy
  - physical device: `HomeActivity.onCreate` called once; normal browsing tab reopened (test passes)
  - emulator: `HomeActivity.onCreate` called twice; homescreen opened (test fails)

More strangeness with this code is described in https://github.com/mozilla-mobile/fenix/issues/20579#issue-956256796.

Because of these challenges with the code, I think we should stop working on this issue for now as we have other priorities.

**Comment by mcomella** [comment]
Spoke with jonalmeida: there are two possible refactoring initiatives in the future that could address this:
- don't use NavGraph
- change themes without `activity.recreate()`

We don't have a clear path forward without these refactors so we're going to put in low impact and perhaps revisit if one of these refactors happens.
