### ISSUE TITLE
FNX-5395 ⁃ [UX] Search Widget

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#201]
**User Story:**

As a user I want to be able to quickly search the web by typing into a search box on my homescreen so I can save time and have all my search history in one place

**Current Design Status:**
~~Experiment implementation in progress: https://docs.google.com/document/d/1Rk7e~~3Tz1t0tYO33hQCGQ4goMt3BaSZnECDKcnsvgTM/edit

**Design Priority:**
P1 (blocked by Experiment)

**Comment by lime124** [comment]
Verdi is working on this. I can post and comment on his behalf.

**Comment by lime124** [comment]
@vesta0 are we waiting on the fennec experiments before continuing work on this?

**Comment by jonohewitt** [comment]
Just wanted to ask if the Firefox logo is really necessary? The equivalent from Chrome does not include the logo which to me looks better as it avoids repeated logos on screen if, for example, you also have the Firefox app logo saved in the phone dock. I would expect most users, having installed the widget, to be aware of which app it is linked to, so I don't think the logo adds anything meaningful while contributing to screen clutter.

I've noticed existing Firefox widgets lagging significantly compared to other browser widgets, taking a second to open a new tab before the keyboard rises, while others provide instant access to the keyboard. They also, unlike Chrome, create a new tab on each widget launch, even when no query is entered - leading to excessive tab build up.

The Chrome widget also adapts to dark mode in the evenings, while DuckDuckGo provides both light or dark widgets to choose from. Both apps' widgets also have a degree of transparency which I find preferrable to the opaque Firefox ones. Offering multiple widget aethetic options would be great!

**Comment by cadeyrn** [comment]
> Just wanted to ask if the Firefox logo is really necessary?

In my opinion: yes. Or the text label has to be changed to include the browser name.

> you also have the Firefox app logo saved in the phone dock. I would expect most users, having installed the widget, to be aware of which app it is linked to, so I don't think the logo adds anything meaningful while contributing to screen clutter.

I disagree. I don't see this as clutter and the app icon has nothing to do with the search widget so this isn't a reason to remove the icon from the search widget. It has to be clear what happens if I use the widget. Also I have more than one browser installed, including three Firefox and two Fenix builds, all with different logos. Yes, I added the Firefox widget to my homescreen, but no, I couldn't say for which browser this widget is without the icon because I don't remember. But thanks to the icon it's clear.

**Comment by andreicristianpetcu** [comment]
It would be really cool if this search widget would have both a way to search in Fenix normally and in Fenix private tab. I would probably mostly use the private tab.
