### ISSUE TITLE
[Bug] "Jump back in": different font size and spacing for headline as for "Collections"

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#20117]
### Steps to reproduce

1. make sure that you have at least one collection so that you can compare the "Jump back in" with the "Collections" section.

### Expected behavior

The "Jump back in" and the "Collections" headlines uses the same font size.

### Actual behavior

Both headlines have a different font size.

![Screenshot_20210621-213522](https://user-images.githubusercontent.com/1100614/122818453-7e156680-d2d9-11eb-84f9-3f12c407f583.jpg)

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision 15df06b294018103f7ca4179925d2ffa7695ee52

**Comment by jonalmeida** [comment]
This is actually intentional and something I noticed as well when I saw the designs.

**Comment by SoftVision-LorandJanos** [comment]
Hi @cadeyrn ! Thank you for the report! I can reproduce this issue. According to the comment above it is intentional. We will wait for a feedback from UX regarding this.
Tested on the latest Nightly (91.0a1 Tuesday 6/22 @ 5:07 AM) and on Release 89.1.1 (Build #2015812947).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by amedyne** [comment]
Closing this to track #20119 .
