### ISSUE TITLE
Red lines appears in some webites[Bug]

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#20137]
## Steps to reproduce
Launch Fenix
Go to Github.com 
### Expected behavior
Website should look normal
### Actual behavior
![Screenshot_20210623-134836_Firefox](https://user-images.githubusercontent.com/48631694/123085071-88934580-d42a-11eb-87ff-c1f0f3ca4074.jpg)

![Screenshot_20210623-135505_Firefox](https://user-images.githubusercontent.com/48631694/123085326-c6906980-d42a-11eb-95a0-55dda10b269f.jpg)

### Device information
* Device vendor / model and Android version: Samsung A12 / Android  11
* Firefox for Android version: 89.1.1
 
Other Browsers Works fine like Vivaldi and Brave

**Comment by jawadalkassim** [comment]
![Screenshot_20210627-235350_Firefox Nightly](https://user-images.githubusercontent.com/48631694/123559477-e5815980-d7a4-11eb-92a9-bf21df3aff94.jpg)

**Comment by SoftVision-LorandJanos** [comment]
Hi @jawadalkassim  ! Thank you for your report! I am not able to reproduce the issue you described. Do you have webrender active? I know about a similar issue there. Maybe check if it still reproduces if you clear your data. Thank you!
Tested on the latest Nightly (91.0a1 2021-06-30T05:09:53.235) and on Release 89.1.1 (Build #2015812947).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by jawadalkassim** [comment]
Hi @SoftVision-LorandJanos 
It's Only happening with Firefox 
I tested Vivaldi and Brave And Samsung Internet
All good,
![Screenshot_20210630-151245_Firefox Nightly](https://user-images.githubusercontent.com/48631694/123958609-eb01be00-d9b5-11eb-9f3a-f8eacea97f24.jpg)
![Screenshot_20210630-151639_Firefox Nightly](https://user-images.githubusercontent.com/48631694/123958869-3916c180-d9b6-11eb-8c18-9f0de9bf18ce.jpg)

I think webrender is disabled by default

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1719345

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
@jawadalkassim could you please got to about:support, click "copy text to clipboard", and attach the text to this bug? Thanks.

**Comment by jawadalkassim** [comment]
@jamienicol 
https://pastebin.com/DhyQ7A7i

[firefox.txt](https://github.com/mozilla-mobile/fenix/files/6800728/firefox.txt)

**Comment by jamienicol** [comment]
I have been able to reproduce this on github, but not at all reliably. @jawadalkassim does this happen every single time you open github or fotmob.com? Have you noticed it on any other websites? If so, please let me know which ones! hopefully I'll have better luck with some other websites.

**Comment by jawadalkassim** [comment]
@jamienicol
Sometimes websites load normally,
Also with Apkmirror.com (Apps icon, sometimes doesn't load and show black and red instead)
Duckduckgo.com (with dark theme also Red line)
But it's not happening all the time

**Comment by jawadalkassim** [comment]
![Screenshot_20210715-175955_Firefox](https://user-images.githubusercontent.com/48631694/125810278-448e23a0-fd0d-40a8-ad6c-083bd75e2edb.jpg)

**Comment by jawadalkassim** [comment]
![Screenshot_20210715-175955_Firefox](https://user-images.githubusercontent.com/48631694/125810650-df425b87-c010-47d7-9448-6187bcc23185.jpg)

**Comment by jawadalkassim** [comment]
I hope this will be fixed soon, 
It's really annoying bug and force me to use other browsers that i don't like to use 😂

**Comment by jamienicol** [comment]
@jawadalkassim apologies for the long delay getting back to you on this one. It turned out to be very tricky to find out what the issue was. I'm still not 100% sure to be honest, but it's definitely a bug in the PowerVR GPU driver and I think I have a workaround.

If you're interested: Basically to render a page we store certain elements in offscreen texture caches, such as images and borders. Additionally, to render certain elements such as the rounded rectangles and circular images, we first have to render an alpha mask in the desired shape to a different offscreen texture, and then we use that to for example clip a square image so that it looks circular. Due to a bug in the PowerVR driver, when we render the clip mask it was incorrectly being written to the texture cache, overwriting the item that was supposed to be in there. This is why you see strange red rounded-corner shapes on top of some of the images. This was due to a function called `glInvalidateFramebuffer`, which tells the driver when we are finished with a texture so that it can free the memory. It seems as if the driver was incorrectly freeing the memory too early, and therefore writing the mask to the wrong place.

I have made a fix to avoid calling this function on PowerVR GPUs. It should make its way to Firefox Nightly in the next few days, and hopefully in to a beta release soon as well. I'd be grateful if you could check in a few days whether this has been fixed. Thanks!

**Comment by jawadalkassim** [comment]
@jamienicol Finally Fixed 😍😍
thank you
FF Nightly 93.0a1 (Build #2015827755)
