### ISSUE TITLE
[Bug] no way to open http://wap.huluxia.com

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#20237]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

open http://wap.huluxia.com

### Expected behavior

open

### Actual behavior

no open

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)  89.1.1

**Comment by Nickoriginal** [comment]
Your bug should be closed, because this (strict) restriction is a part of the normal Firefox protection for its users.
![Screenshot_20210703-120713_Firefox](https://user-images.githubusercontent.com/85299944/124349376-630af680-dbf7-11eb-998d-99eaa0002d8b.jpg)
In your case Firefox blocked site what potentially offers unwanted software and can be dangerous, in my opinion, it is right.
**Screenshot on Chrome**
![Screenshot_20210703-120644_Chrome](https://user-images.githubusercontent.com/85299944/124349426-99e10c80-dbf7-11eb-8e1a-dbd1e88ba647.jpg)

**Comment by SoftVision-LorandJanos** [comment]
Hi @lindongbin ! Thanks for your report!  I’ve checked the issue on other browsers as well, I got the not safe warning on them as well. I believe this was intended this way.
