### ISSUE TITLE
[Bug] Private Browsing, Close All tabs

### ISSUE THREAD

**Issue by 4rgh** [mozilla-mobile/fenix#20251]
To my horror, I lost a bunch of tabs pertaining to my business' interests due to a bug and decided I had to report it. Sometimes I can reproduce the bug, sometimes I can't. It has happened to me before and my recollections so far are as follows;

Steps to reproduce:
Close the oldest/bottom-right private tab in the private tab overview (possibly after viewing video content/youtube on the closing tab). Although the private tab overview may appear selected, the individual private tab windows might display the names/titles of your public tabs, despite the number of tabs open being the amount of the private session, the thumbnail images for a few tab windows may also be affected. Open up the alternatives menu in the private tab overview and tap close all tabs.

The amount of public tabs open was 50-60 and about 40-50 private tabs, at the time.

Expected behavior:
The browser should close the remainder of the open private tabs. The public tabs would be unaffected.

Actual behavior:
Closed and deleted any and all information of my public tabs, including history in the "Recently Closed Tabs"-list. The private tabs remained.

Device information:
Samsung Galaxy S10 
Android version 11
Firefox Nightly 
91.0a1 (Build #2015819979)
AC: 91.0.20210703143052, 50e9580e70
GV: 91.0a1-20210703092415
AS: 79.0.0

**Comment by SoftVision-LorandJanos** [comment]
Hi @4rgh ! Thank you for the report! I've tested on the latest Nightly (91.0a1 - 2021-07-06T05:07:23.106) by opening 60 tabs in normal mode and 50 in private, and I closed both in the bottom and from the top of the grid, all of them were tabs with videos, and tapped undo a few times, other times I didn't. I did not notice anything wrong, none of the tabs were deleted that weren't intended to be deleted, history remained only for the public tabs, including in the "Recently Closed Tabs"-list. Since it didn't happened every time at your end either, I suppose it's a circumstantial bug, so if you have any extra information that can raise the chance of being reproducible, please share it. Thank you!
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0)

**Comment by SoftVision-LorandJanos** [comment]
As this issue is still not reproducible, I will close the ticket.
If the issue happens again, please try to find out any extra information that might help us reproduce it as well. Thank you!
