### ISSUE TITLE
Add an option to disable the "Recently saved" section

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#20329]
### Steps to reproduce

1. Open a page and bookmark it.
2. Tap on the homescreen icon.
3. Observe the homescreen, and the "Recently saved" section.

### Expected behaviour

The user can observe the "Recently saved" section and can disable it/close it if needed.

### Actual behaviour

The user can observe the "Recently saved" section but cannot disable it/close it if needed.

### Device name

all

### Android version

all

### Firefox release type

Firefox Nightly

### Firefox version

91.0a1 from 7/12

**Comment by bjherbison** [comment]
Please add an option. I use bookmarks for things I want to reference later, not now. The most recent item bookmarked is highly unlikely to be what I want now. In fact, for my use Fenix since this annoyance was implemented I have been shown recently created Desktop bookmarks which I am even less likely to want to reference now.

An option to turn this off would make me more productive by removing a distraction from my home screen.

**Comment by SeburoSUMO** [comment]
User feedback https://support.mozilla.org/en-US/questions/1343909

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1343752

**Comment by asynchronous-sheep** [comment]
Agreed.

**Comment by bjherbison** [comment]
This issue should be closed. Recently Saved can be configured off in the current Nightly.

**Comment by csadilek** [comment]
@lobontiumira the home screen can now be customized and the section can be turned off. The three dot menu has a customise home item, the bottom of the home screen has a button that takes you to the setting as well.

I will close this, but please re-open if this doesn't seem to work for you.
