### ISSUE TITLE
[Bug]: UNDO button name is not translated in Spanish

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#20331]
### Steps to reproduce

1. Open a few pages to have items in History.
2. Open the Android "Language and Input" settings. Set the Language to Spanish.
3. Go to History, delete one item and check the notification.

### Expected behaviour

The notification is in Spanish with "UNDO" button also in Spanish (DESHACER).

### Actual behaviour

The notification is in Spanish but the "UNDO" button remains English.

### Device name

Google Pixel 4

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.1

![Screenshot_20210712-162429](https://user-images.githubusercontent.com/48829350/125296087-97389280-e32e-11eb-9f53-d04c6908dc96.png)

**Comment by Nickoriginal** [comment]
Hello! _Reproducible in_ Firefox 90.1.1 on:
**Samsung Galaxy A20s**, Android 10
**Samsung Galaxy J2 Prime**, Android 6.0.1
<img src = https://user-images.githubusercontent.com/85299944/125423999-58e17049-0da5-47c7-8bb0-619979e5ab58.jpg width = 45%>
Compared with expected behaviour (for example: closing tab in tabs tray)
<img src = https://user-images.githubusercontent.com/85299944/125424047-e8002b82-9641-43e5-879d-9946158c3c1b.jpg width = 45%>
Also @SoftVision-LorandJanos, maybe DESHACER string is too wide to insert it here?

**Comment by mcarare** [comment]
cc @Delphine https://pontoon.mozilla.org/es/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=bookmark_undo_deletion&string=198013

**Comment by Delphine** [comment]
Good catch! Approved now. Thanks to both!

**Comment by mcarare** [comment]
The change has been imported, this should be fixed in latest master.

**Comment by Nickoriginal** [comment]
It was imported in Spanish (Argentina) too? It is also affected.

**Comment by mcarare** [comment]
cc @Delphine https://pontoon.mozilla.org/es-AR/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=bookmark_undo_deletion&string=198013

**Comment by Nickoriginal** [comment]
Other Spanish languages (Chile, Spain and Mexico) correctly loads "DESHACER"

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-07-14.

### Device used:
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus 6T (Android 9)
