### ISSUE TITLE
[Bug]: shadows in "Recently saved" section on home screen are truncated

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#20334]
### Steps to reproduce

1. make sure you have bookmarks so that you can see the "Recently saved" section on your home screen.

### Expected behaviour

All shadows look good.

### Actual behaviour

The shadow of all boxes is truncated at top (compare with top sites and collections) and the shadow of the first box is truncated on the left side as well.

![Screenshot_20210712-163940](https://user-images.githubusercontent.com/1100614/125307361-47f36180-e330-11eb-9e6e-70a0d091b9a9.jpg)

### Device name

OnePlus 7T Pro McLaren Edition

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

master branch revision bbea03e27cb37e0227f434450b77a1bb0be76818

**Comment by jonalmeida** [comment]
Thanks for filing this! We noticed this during initial implementation, but the solution for the bug was outside the scope of the issue; we need to alter the homescreen's margin and use padding for each child item instead so that we can make the horizontal carousel enter from the absolute end of the screen.

**Comment by jonalmeida** [comment]
@cadeyrn Yeah, that would be helpful. Please include a screenshot for it as well.

**Comment by cadeyrn** [comment]
#21621 was opened for the Pocket issue a few moments ago. So I will close this issue.
