### ISSUE TITLE
[Bug] Can't select single word with double tap or long hold

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2038]
## Steps to reproduce
Try to select words by double taping them, or holding a finger on them.

### Expected behavior
The word is selected

### Actual behavior
It's like you are trying to select an empty space, the words are not selected (unless you select all, which is not what you want here).

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by yoasif** [comment]
While it does seem possible to select words inside a text field, it is definitely not as quick as on Chromium. You can test this pretty easily on bing.com

**Comment by domoritz** [comment]
Why is this not considered a bug?

**Comment by vesta0** [comment]
@cpeterso do we have a GV bug that corresponds to this issue? This is specifically about how long pressing to select a word inside some text fields (e.g. bing.com) takes a very long time and often appears to user as not working at all. It may fall under performance so I've tagged the performance team as well.

**Comment by cpeterso** [comment]
@Lululalu - What Android device are you using? Is word selection also slow in non-preview Firefox for Android?

I'm not able to reproduce with Fenix Nightly 190908 or Firefox 68.1 on my Moto G5. Word selection seems as fast in Fenix and Firefox as in Chrome. I tested on google.com because bing.com opens a text input popup that interfered with word selection.

**Comment by dholbert** [comment]
Could someone remove the `needs:performance` tag? This doesn't seem to be performance-related.

**Comment by dholbert** [comment]
> Thanks. I can reproduce the bug now. Using the "Search Wikipedia" text field on https://en.m.wikipedia.org, I can select individual words in Chrome, but not in Fenix Nightly 

It's working for me there, though I have to long-press for an unusually long time (~3 seconds).

@cpeterson, does it work for you if you long-press a word (in the search field) for ~3 seconds?

**Comment by eliserichards** [comment]
This still seems to be an issue.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/43795363/81113035-2e14ee00-8ee5-11ea-9006-1730519cacd1.png">

**Comment by SS1113** [comment]
This can still be reproduced on `Nightly 200611 06:01`. This is really quite frustrating!

**Comment by SS1113** [comment]
This This can still be reproduced on the `Nightly 200623 18:02`. 

I request you to please solve it as soon as possible this is really making it harder to select text!

**Comment by liuche** [comment]
This looks like #10618 which sounds like it will get a fix soon. Definitely a bug!

**Comment by VitasLoWang** [comment]
3 years later and this is still not fixed?? It is really difficult to type some longer text into facebook or any kind of forum if I cannot select words in order to fix typos and such!

**Comment by dholbert** [comment]
@VitasLoWang please file a new issue for what you're observing.  This bug here was indeed fixed (note that this is "closed as completed" in the comment before yours, which references #10618 , ["verified as fixed" 2 years ago](https://github.com/mozilla-mobile/fenix/issues/10618#issuecomment-686961314).

I just tested Facebook myself locally (in Firefox Nightly on Android).  If I e.g. type the word "Testing" into the Create Post UI (after tapping in the "What's on your mind" textfield at the top of my feed), I can long-press that text and select it.

So: whatever you're seeing is new & different from what was reported here (since this bug here had a patch land that was confirmed to fix it at the time); and I'm not sure I can reproduce what you're describing, so more details in a new issue would be helpful.  Thanks!

**Comment by VitasLoWang** [comment]
dholbert you seem to be talking about something else then what the first report from 2019 describes. I am talking about impossibility to select a word in the input form field/textarea by double tap! Yes you can tap and hold, then do select all and shrink the selection to select only that one word, but this is very impractical especially if you have already written a longer text. I have just tested it on m.facebook.com and on Microsoft answers.
As you can see user liuche closed this issue not because it was fixed, but in hope it will get fixed soon, but that was 3 years ago!

**Comment by dholbert** [comment]
Thanks for clarifying.

So to be fair, the original report from 2019 mentioned two things:
 - double-tapping a word in a textarea doesn't select it
 - long-pressing a word in a textarea doesn't select it (or just took a really long time, like several seconds, longer than you would reasonably wait)

These are two distinct things, and most of the comments in this github-issue have focusing on the latter long-press issue, and I think the scope was kinda narrowed to cover that in the first few followup comments.  And that long-press issue fixed, as far as I can tell. (I can long-press a word in a textarea and it'll get selected.  No need for the select-all dance that you alluded to, on my end...)

But you're right that the former double-tap approach is still broken; I can reproduce that not-selecting-anything and just popping up a select-all option.  I'll spin off a new bug for that problem, rather than resurrecting this old github ticket.  Plus: going forward, Firefox-for-Android bugs are moving to be tracked in Bugzilla, so I'll file it over there and I'll post a link here.

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1809060 for the double-tap issue.

**Comment by VitasLoWang** [comment]
Actually it never occurred to me that tap and hold selects a word :-] I am used to do things similar as on a PC and on PC you have to do a double click to select one word. If you do click and hold then nothing happens. I think the behavior should be similar as on a PC to make it more intuitive for common users.

**Comment by VitasLoWang** [comment]
tap and hold to select a word is STILL BROKEN and unreliable. I can select only some words and not other. [Check my video](https://photos.app.goo.gl/tFatwB9eRAnbsc8Y9)
