### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Vignesh1427** [mozilla-mobile/fenix#20423]
### Steps to reproduce

Comfortable for android

### Expected behaviour

A menu should open

### Actual behaviour

A app close suddenly

### Device name

Google Pixel 2

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

89.0.10

### Device logs

Tap setting 
Scroll to the bottom of the setting

**Comment by Nickoriginal** [comment]
@Vignesh1427 Please, concrete your issue.
> ### Firefox version
> 89.0.10

You are using Firefox 90.1.1? You can check your actual Firefox version following my video:

https://user-images.githubusercontent.com/85299944/126214544-e1e9c3c6-f0bf-4b55-9311-4d054a9af29f.mp4

> ### Expected behaviour
> A menu should open
> ### Actual behaviour
> A app close suddenly

You've encountered this problem here?
<img src = https://user-images.githubusercontent.com/85299944/126214977-14b1cf62-df2b-4ef6-99c0-e7ebba5dffcb.jpg width = 35%>

> Tap setting
> Scroll to the bottom of the setting

 Or here? 
<img src = https://user-images.githubusercontent.com/85299944/126215284-013c950e-bc16-4b18-90da-fe2e9b34af86.jpg width = 45%> <img src = https://user-images.githubusercontent.com/85299944/126215294-7f52cc85-799b-4d06-9bcb-3694bdd5e465.jpg width = 45%>

**Comment by kbrosnan** [comment]
This does not look like a useful report. If the person who opened this issue can provide crash IDs or a logcat of the crash then we can reopen.  https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information
