### ISSUE TITLE
FNX-74 ⁃ The download prompt is intrusive

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2047]
## Steps to reproduce
Try to download something

### Expected behavior
The download prompt should be discreet, and shouldn't disrupt the overall navigation

### Actual behavior
It pops up on the middle of the screen, and the user can't do anything until they have decided to download the file or not.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by yoasif** [comment]
I think what @Lululalu is asking for is a tab modal prompt instead of an app modal. Something like macOS sheets or what Kiwi Browser offers when a download location has previously been selected. 

![signal-attachment-2019-04-25-184106](https://user-images.githubusercontent.com/152493/56772868-bbc5e580-6789-11e9-813a-d60daf6fed96.png)

**Comment by lime124** [comment]
this seems related to #2630 and we should consider consistency here. please consider both issues together - @AmyYLee @topotropic . thanks!

**Comment by topotropic** [comment]
Let's look at it as part of the Download manager work referenced above.

**Comment by vesta0** [comment]
Thanks @Lululalu this will be addressed in #5582
