### ISSUE TITLE
No way to hide secure connection/tracking protection buttons on toolbar

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#20504]
There are two buttons showing the secure connection status and tracking protection that were recently added to the toolbar. They aren't useful to me, but I end up accidentally tapping them many times when trying to tap the address bar instead. However, I couldn't find a way to disable them and revert the toolbar to its previous version. It would be nice to have an option to make the toolbar unobstructed by the icons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17358)

**Comment by cadeyrn** [comment]
I don't know what you mean by "previous version" and "recently added" because it's not new at all that there is one button for the tracking protection and one button for the connection status. Maybe you are confusing this with the home button that was recently added. But they already work on combining the buttons for the tracking protection and the connection status into one button.

I don't think it makes sense to completely disable such an important button (that is also used for managing website permissions) and therefore vote against this proposal.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814149

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
