### ISSUE TITLE
[Bug]: Samsung Dex bar confuses FF when it calclates viewport size

### ISSUE THREAD

**Issue by mxmilkiib** [mozilla-mobile/fenix#20522]
### Steps to reproduce

Use Samsung Dex
Visit https://memeorandum.com in FF
Scroll to bottom of page

### Expected behaviour

The content should not be hidden.

### Actual behaviour

Content is hidden 

![Screenshot_20210726-213842_Firefox](https://user-images.githubusercontent.com/108225/127056325-9adad202-c089-447f-ba0f-34f90421e0fe.png)

### Device name

Samsung Note 9

### Android version

Android 10 

### Firefox release type

Firefox

### Firefox version

90.1.2

**Comment by Mugurell** [comment]
The issue is that you're already at the bottom of the page and the last article is covered by the bottom toolbar?
Cannot test on dex but the above can be reproduced on any device:


https://user-images.githubusercontent.com/11428869/127109588-9acd935b-9f7d-48be-97fb-057f02c60a64.mp4

Where I also see that a second scroll will hide the toolbar if not already hidden.

Is this the issue you're seeing?

**Comment by mxmilkiib** [comment]
It would be nice if this got fixed

**Comment by mxmilkiib** [comment]
Ugh, ok.
