### ISSUE TITLE
FNX-5421 ⁃ Persistent notification to close all private browsing tabs

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2053]
### Why/User Benefit/User Problem
As a user, I would like to be able to quickly close all private browsing tabs in Fenix. This exists today in Kiwi Browser, and I could have sworn it existed in Focus previously. 

### Acceptance Criteria (how do I know when I’m done?)
User is able to swipe down in notification area and tap a notification that allows them to close all private browsing tabs.

**Comment by yoasif** [comment]
Given the decision in https://github.com/mozilla-mobile/fenix/issues/1788#issuecomment-487076514 I think that this feature is also not required. 

It may be desirable for some, but there is a risk that it will be destructive to more people than desired, and it was presented as an alternative to the trash icon in the toolbar.

**Comment by buttercookie42** [comment]
How does private browsing handle OOM-kills at the moment? Fennec stores private tabs in memory using Android's _savedInstanceState_, so private tabs can still be recreated if Android OOM-kills the app while in background (but not if the user actively swiped the app away or otherwise explicitly killed/quit it).

If we don't want to do something comparable with Fenix, then a foreground notification together with an associated service would at least make Android more unlikely to kill the app unless the OS was desperately short of memory.
While private browsing tabs are intended to be ephemeral, OOM-kills seems a bit _too_ random to me, especially on low-end devices.

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by liuche** [comment]
Betty will follow up on final strings for @AmyYLee to update mocks.

**Comment by colintheshots** [comment]
> How does private browsing handle OOM-kills at the moment? Fennec stores private tabs in memory using Android's _savedInstanceState_, so private tabs can still be recreated if Android OOM-kills the app while in background (but not if the user actively swiped the app away or otherwise explicitly killed/quit it).
> 
> If we don't want to do something comparable with Fenix, then a foreground notification together with an associated service would at least make Android more unlikely to kill the app unless the OS was desperately short of memory.
> While private browsing tabs are intended to be ephemeral, OOM-kills seems a bit _too_ random to me, especially on low-end devices.

So it's not a great situation right now. If we're OOM killed or if the user swipes away our activity, we lose all tabs. OOM kills on an old, cheap phone can happen as easily by opening the Camera app and returning. We can't persist A-C Sessions to instance state because A-C wanted to handle all session storage and restoration and didn't want Sessions parcelable. This really needs to be a separate issue to solve.

**Comment by buttercookie42** [comment]
> or if the user swipes away our activity

That might actually be okay, wouldn't it (#3950 thinks so, too)? It would need a little more careful implementation than how Fennec currently works to always close the private session in that case (while swiping away the task for the browsing activity will likely always clear the savedInstanceState, it's not guaranteed to actually kill the app process if the app has any other activities open, a service running, etc.), but it would certainly at least correspond to an explicit user action to get rid of the Fenix activity for the moment.

OOM-kills are certainly a different matter, though. For that specifically there's also #2493 and #2387 is basically the same issue (the OS killing the app process in a way that the user doesn't control and/or expect).

**Comment by liuche** [comment]
@AmyYLee since string freeze is today, do the mocks have the most updated strings?

Are the updated strings:
"Firefox Preview (private)
Delete private tabs
Open       Delete and Open"

https://mozilla.invisionapp.com/share/DUTCUDLZ4MC#/screens

**Comment by softvision-miralobontiu** [comment]
Verified on the latest Nightly build190829 (#12410626) with Motorola Moto G6 (Android 8) that the notification is persistent. If "Delete and open" is tapped, all private tabs are closed and the app is opened, if "Open" is tapped, the app opens without closing the opened private tabs.

![Screenshot_20190829-175138](https://user-images.githubusercontent.com/40694158/63951148-e7354580-ca85-11e9-9c09-40872f493676.png)
