### ISSUE TITLE
Tabs and inactive tabs are not aligned in tabs tray

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#20617]
<img src="https://user-images.githubusercontent.com/11428869/127855730-d738b0d1-4317-4044-b69f-6980029fc5d3.png" width="50%" />

Not sure how these should be reconciled, whether the inactive tabs sestion to be wider or the tabs smaller.
@topotropic @jonalmeida ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17421)

**Comment by jonalmeida** [comment]
Looking at [the designs](https://www.figma.com/file/am9EJGg6ow29PXWkc9jcOH/MR2?node-id=708%3A7083), I'd say that the bug is that the tabs should be smaller to include the 16dp margin which seems to be missing in the grid layout.

<img width="108" alt="Screen Shot 2021-08-05 at 2 00 13 AM" src="https://user-images.githubusercontent.com/1370580/128299153-6e99d69a-6e05-477d-8c06-960bbdd95997.png">

**Comment by topotropic** [comment]
Inactive tabs and a unselected tab both have 16dp margin (the selected tab has less margin). It looks like the inactive tabs section has too much margin at the moment.

**Comment by cadeyrn** [comment]
> It will be closed if no further activity occurs.

It's still an issue.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812852

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
