### ISSUE TITLE
[webcontent]

### ISSUE THREAD

**Issue by Xashyar** [mozilla-mobile/fenix#20645]
## Site with issue and any steps to reproduce
github.com
### Expected behavior
The view branches/tags link is shown
### Actual behavior
The view branches/tags link is not shown
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?

This issue has been already confirmed and verified by https://github.com/softvision-oana-arbuzov on this thread:
But closed and "non-compat":
https://github.com/webcompat/web-bugs/issues/71738
### Device information

* Android device: *
* Fenix version: *

**Comment by cadeyrn** [comment]
> This issue has been already confirmed and verified by https://github.com/softvision-oana-arbuzov on this thread:
But closed and "non-compat":

It was **not** confirmed as a bug. The issue was closed because there is no webcompat issue. It's not even a bug at all. This link just not exists on GitHub's mobile website. If you want to see this link on GitHub's mobile website you should open a feature request at GitHub. Mozilla is not responsible for GitHub's website.

**Comment by Xashyar** [comment]
@cadeyrn, 

If you play around with it a bit, the browser, finally shows the link, I'm not sure how to give a step-by-step repro.

I haven't got to test this on iOS yet, and the reason it got closed was that, it was reproducible on chrome as well, so maybe it's a bug on both or limited to Android?

**Comment by cadeyrn** [comment]
> But closed and "non-compat":

The issue was closed because the result is the same in Chrome. It can also be reproduced in Samsung Internet so it probably affects every browser on Android. I can see the link only in Safari on iOS but there the whole menu is broken and it shows no branches at all.

As it's broken in every mobile browser it's clearly not a Firefox bug. You should report it to GitHub because they are responsible for fixing their website.
