### ISSUE TITLE
Add option to disable "inactive tabs" box

### ISSUE THREAD

**Issue by WesleyAC** [mozilla-mobile/fenix#20684]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

When I click on the "tabs" button, it opens to the bottom of the "inactive tabs" section, and I have to scroll through them to get to the tab that I actually want (which most of the time is the tab I was just looking at, so that I can close it).

I'm sure there are ways to improve this, but I'd rather just have a way to disable the "inactive tabs" box completely.

### How do you know that this problem exists today? Why is this important?

The inactive tabs feature exists, and it makes Firefox basically unusable for me, since I need to spend multiple seconds scrolling through inactive tabs in order to close the tab I was just looking at, or to get to another "active" tab. 

### Who will benefit from it?

People who have many tabs open, or otherwise preferred the previous tab list screen.

**Comment by LaurentiuApahideanSV** [comment]
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/20663. I will mark this issue as closed as it will be handled there.

**Comment by WesleyAC** [comment]
I don't think this is a duplicate — while #20663 will help with the symptoms I'm having, a separate "inactive tabs" box is fundamentally not something I want.

#20663 will make the symptom that closing tabs takes ~5 seconds of scrolling for me go away, but I'll then instead have the problem that when I go to look for a tab, I won't know whether to look for it in the active or inactive tabs, since tabs will move from the former to the latter at a essentially arbitrary time.

If you're not open to adding an option to disable this, would you be open to adding a option (even in about:config) to adjust the amount of time before tabs become inactive? That way I could set it to a high enough value that it wouldn't be a problem.

**Comment by clientenq** [comment]
This is not a duplicate. The issue linked to is a feature request, with no clear mention how this is related to this specific bug.
The feature request refers to inaccessible design specifications.

By handling this bug as a simple generic feature request it does not reflect the urgency of the users, nor does it provide any serious consideration regarding this specific issue with the sudden "inactive tabs" list thats bugging normal usability.

Please take specific bug more seriously instead of generalising a bug as a generic feature request.

Current situation: on opening any new tab devopers now force every user to first view and scroll through  a list of inactive tabs, while users open the tab to browse. This is plain ignorence of basic usability design.

**Comment by bb010g** [comment]
This issue shouldn't be marked as a duplicate of an issue that doesn't address the concerns here. The issue this has been marked as a duplicate of should already express a plan for the concerns in this issue, whether that's planning to move forward with ideas from this issue or explicitly not moving forward with ideas from this issue.

Collapsing a UI element & hiding its contents is not the same as disabling its whole feature & not filling the UI element with content in the first place.

**Comment by jonalmeida** [comment]
Re-opening as other comments already mentioned - I don't think we should consider this a default.

**Comment by jonalmeida** [comment]
> Please take specific bug more seriously instead of generalising a bug as a generic feature request.

Please be respectful in our issue tracker. Our [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) apply here too.

**Comment by Octoton** [comment]
Moreover the inactive tab doesn't really make seems when the user as selected manual removal of tab. If i want to be able to choose when and where to remove a tab why should the app move those tab in another space automatically.
Now all my tab order are messed up and i need to reopen every "old" tab to get back to were i was.

**Comment by clientenq** [comment]
> > Please take specific bug more seriously instead of generalising a bug as a generic feature request.
> 
> Please be respectful in our issue tracker. Our [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) apply here too.

Please specify why this is considered disrespectful. My goal is to address the cause and consequences of the issue and process. People can make mistakes in our community, this does not mean the process of addressing issues and users are  taken seriously when these bugs are clearly not addresse appropriately.
If comments regarding cause and consequences are not welcome here, please specify where to address these issues.

**Comment by filips123** [comment]
Maybe there could be another option "Move to inactive tabs" similar to "Close tabs" that allows users to choose when tabs are moved into "inactive tabs" section. And when user chooses "Never" or there are no inactive tabs, the section is simply hidden.

**Comment by klint** [comment]
I agree that the inactive tabs feature should really be an opt-in process for existing installations.
It is very disturbing to see the list of carefully curated tabs that I have built over time in the tab tray shrink day after day. My tab tray is now almost empty 
I'm even not sure that the tabs are really moved to inactive tabs, due to existing bugs when the feature was rolled out to the nightly fenix. 
I don't want to use that feature at all, actually. 
So please make it an option.
Thank you.

**Comment by mattcoz** [comment]
At the very least, the inactive tabs should be at the top along with the oldest tabs instead of the bottom.

**Comment by klint** [comment]
The is already a different issue filed for that.

**Comment by lorenzos** [comment]
I agree with @WesleyAC - And anyway, what's the point of inactive tabs? Or more precisely, their grouping UI? Honest question, I don't get why that change was introduced in the first place. I can't find any documentation or discussion about the problems it would solve or the benefits it would bring.

I totally understand unloading tabs from memory, I mean, from a system performance point of view. But why move them in a separate confusing UI? If something at all, why not simply graying out the title, or using a special icon in place of the page thumbnail, instead?

**Comment by SpandexWizard** [comment]
For mobile it's not even doing that much. My phone is constantly reloading tabs I was using when I switch between them. That tells me only a few tabs are loaded into memory anyway. And it's mobile where this inactive tabs thing is the most annoying. I really want it to go away, but I'm desperate for at least a toggle. Ive had certain tabs open for months, and this thing is culling tabs that I opened last week. Who thought this was a good idea? What's the point?

**Comment by BlackLotus** [comment]
Also the inactive  tabs seem to lose their ordering and even if I collapse them after firefox force quits and I open it it's expanded again.
Also normally if we go into the tab overview we are at the marked position (of your current tab) that behavior seems to be gone now completely.

**Comment by mgrandi** [comment]
its been weeks and its actively making my experience worse, if you have a lot of tabs, you have to constantly scroll the entire "inactive tabs" every time (even if you minimize it once!) this is happening multiple times a day and is causing me enough grief that i've switched away from firefox nightly. adding literally 5 seconds to every time i need to close a tab is mind boggling

**Comment by jaimeburnap** [comment]
This is very bad ux and should be opt in until it's fixed

**Comment by ssk97** [comment]
As a quick fix, I am looking into modifying the "close inactive tabs" option to add something like "Never Inactive". Is that a reasonable UI or does it have to be a fully separate option?

What is the process for adding a string like that? Do I have to add every translation myself or is there an automated process?

**Comment by aslom** [comment]
Add about:config option to restore previous behavior?

**Comment by cadeyrn** [comment]
> Add about:config option to restore previous behavior?

There is no about:config in stable releases of Firefox for Android so about:config cant't be the solution for this feature request.

**Comment by SpandexWizard** [comment]
What needs to exist is a toggle similar to automatically deleting tabs that says "how long until tabs are Inactive", with variable times, and most importantly a checkbox that says "never".

**Comment by noscript** [comment]
Mozilla doesn't use its own product. Otherwise it's hard to explain how such a sevear UX downgrade is being totally ignored for over a month.

**Comment by ssk97** [comment]
> There's got to be a line in the code that determines when to set a tab inactive and such, changing this behavior shouldn't be hard. I'd even do it myself if I was familiar with the code base...

It's actually a filter, built into the same code that separates normal and private tabs. You can change maxActiveTime (in NormalBrowserTrayList) to Long.MAX_VALUE and it'll be good for a few billion years. The problem for me is dealing with the settings UI (and then getting the pull request merged once that's done).

If you're compiling yourself you can also set FeatureFlags.inactiveTabs to false (rather than the current isNightlyOrDebug).

**Comment by cadeyrn** [comment]
An option to disable this feature is planned, see #21319.

**Comment by bew** [comment]
See #21319 that was just opened yesterday, check its acceptance criteria it looks like we have a winner here

**Comment by ssk97** [comment]
> You can use Beta or stable releases if it's not acceptable for you to wait so "long".

Right now I'm forced onto Nightly due to restricting non-recommended addons to Nightly only. I'd happily be on Beta if I could both have automatic updates (so no compiling manually) and the addons I want. (Presumably you want to keep them off of Stable the same reason about:config is disabled on Stable)

Well, actually, I'm forced onto either Nightly or the ~2 year old version of Stable. Which yes, I still have running, even though it's dangerously outdated. Hence why I'm trying to get the current Firefox to the point where I'd be able to switch without getting too annoyed.

**Comment by WesleyAC** [comment]
I made a PR #21375 to disable this feature, as a stopgap until a UI is built to disable it.

**Comment by ssk97** [comment]
Sorry for hijacking this thread, but it seems like most here have the same issue I do (android browser with addon support and some stability) and would find this information useful.

Since Mozilla doesn't consider my use case a priority I looked for alternatives. [F-droid's build](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/) seems reasonable. It is a slightly-outdated version of Stable Fenix with About:Config and Add-ons enabled. The build process seems to be located [here](https://gitlab.com/relan/fennecbuild). It loses a few important features that require Google integration, but works for my use cases. It has full support for Firefox Sync.

Kiwi Browser is a Chromium browser that supports addons as well, but I have not investigated them closely. They seem to be have just finished a major overhaul. Said overhaul will mean they constantly auto-update to the latest Chromium, which is better than F-droid's need for a manual metadata update. However, it can't easily sync with any desktop browsers.

**Comment by klint** [comment]
This has been discussed so many times in other threads, don't waste your time! 😊. I will stick with Fenix whatever happens to add-ons, the main ones being supported already. I prefer that Mozilla uses its resources to bring new built-in features and to polish them by listening nightly users.

**Comment by mgrandi** [comment]
The inactive tabs section seems to have gone away entirely with the latest update

**Comment by WesleyAC** [comment]
Hmmm, the inactive tabs box disappeared for me today as well. While I'm quite happy with that, I'm curious why — I don't see any commits that look immediately related, nor any action on this issue.

Anyway, I'm certainly not going to complain.

**Comment by noscript** [comment]
Indeed, "Inactive tabs" are gone in the latest update. :partying_face: 

>I'm curious why — I don't see any commits that look immediately related, nor any action on this issue.

I wonder if the Nightly builds are based on some private repository source.
