### ISSUE TITLE
[Bug] Sign In Fail on Firefox Mobile Nightly

### ISSUE THREAD

**Issue by jeedaiian** [mozilla-mobile/fenix#20710]
After clicking Sign in to Synchronise,
I scanned QR code on my Firefox Desktop
Then it says Confirm pairing
After confirming it says ready to use
Exit the ready to use screen, back in firefox mobile app, it still tells me to Sign in to Synchronise. 

Firefox Nightly 92.0a1 (Build #2015826379)
Android 8
Huawei Nova 2 Lite(LDN-LX2) 

![Screenshot from 2021-08-06 17-35-20](https://user-images.githubusercontent.com/73543350/128492064-1778a890-7735-4a65-956e-edabb27637c0.png)
I noticed in Manage devices on Firefox Desktop it shows the sign in from Firefox nightly mobile with icon of a globe, not a phone icon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17493)

**Comment by SoftVision-LorandJanos** [comment]
Hi @jeedaiian! There's a detail in your issue that I can reproduce on the latest Nightly 98.0a1 (2022-02-07), but it goes away with a workaround:
After confirming the pairing there's a step on desktop to approve the device.
After the approve the devices sync, but going back to menu, "Sign in to sync" is displayed as you described.
When you tap on that it shows you the sync was successful, and going back to menu from there, the account is displayed instead of "Sign in to sync".
Also, in the Manage devices on Firefox Desktop the phone icon was displayed:
![image](https://user-images.githubusercontent.com/48829350/152788351-cc91bdd9-4d16-479f-b7b6-d018e5e67379.png)
Could you confirm this on the latest builds? Thank you!
Device used: Oppo Reno 6 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on my end. The process is a bit different as well since.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as not planned.
