### ISSUE TITLE
FNX-5438 ⁃ Rename gradle build type "releaseRaptor" to "raptor"

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/fenix#2076]
`./gradlew assembleReleaseRaptor` doesn't actually create "release" apps, despite what the name implies - [there was already some confusion](https://mozilla.slack.com/archives/CA4QR1M2R/p1556293926088300).

We should rename `releaseRaptor` to `raptor`

**Comment by mitchhentges** [comment]
@JohanLorenzo if `releaseRaptor` is renamed to `raptor`, will this cause breakage within other teams/repositories? Or, is the gradle refactoring entirely local to this project?

**Comment by JohanLorenzo** [comment]
Excellent question! It would change TC's indexes. For instance: https://tools.taskcluster.net/index/project.mobile.fenix.v2.branch.master.latest.release-raptor/aarch64. That might be a fine deal, let's check with the consumers of that index.

My understanding of `release raptor` is: we want a release-like build which has all optimizations done, but it has raptor enabled. Having raptor enabled on real release builds would a problem because user could have their fennec remotely instrumented.

**Comment by mitchhentges** [comment]
I wonder if we should call the build type `raptor`, so consumers will do builds like: `./gradlew assembleRaptor`.
Of course, internally, we can make sure `gradle` still does all the optimizations.
The end goal is for performance-testing to have all the optimizations it depends on while not confusing people who interface with `gradle`

**Comment by sblatz** [comment]
This looks like it's done. @mitchhentges please re-open if you wanted to do more here.
