### ISSUE TITLE
[Bug]: User font size setting doesn't account for device DPI

### ISSUE THREAD

**Issue by kuro68k** [mozilla-mobile/fenix#20873]
### Steps to reproduce

1. Open www.slashdot.org on a Google Pixel XL or Google Pixel 5 (or the Android emulator using those phone's profiles). Other phones likely work but I have tested these two.

2. Go to Settings, Accessibility and turn off automatic font size.

3. Font size behaviour as per the below screenshots.

### Expected behaviour

100% should probably be larger. 200% is the maximum and not all that large on screen.  In fact it's about the same as the automatic setting. There is thus no way to make the font larger than automatic mode for ease of reading.

Also at 200% font size the layout breaks. It's fine in automatic with the same actual font size. Changing the system font size makes the automatic mode larger too, and the layout does not break.

### Actual behaviour

Automatic:
![Screenshot_20210816-205725](https://user-images.githubusercontent.com/2674466/129622744-30f68260-f9ff-4dc6-af6e-0c6a4f8649d3.png)

User 100%:
![Screenshot_20210816-205743](https://user-images.githubusercontent.com/2674466/129622802-92c35b06-7c95-4b51-b3cb-2c971b18ddb7.png)

User 200%:
![Screenshot_20210816-205803](https://user-images.githubusercontent.com/2674466/129622916-70f250ba-3d13-4ecf-9549-5387de87cc01.png)

### Device name

Google Pixel XL or Pixel 5

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 (Build #2015828235)

### Additional information

Possibly related to this recently fixed issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1685756

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17607)

**Comment by kbrosnan** [comment]
@buttercookie42 is the expert in this code.

**Comment by buttercookie42** [comment]
Currently, our behaviour is as follows:
Mobile-friendly pages (with a `<meta name="viewport" content="width=device-width>` tag or likewise) always get text zoom. In automatic mode the magnitude is controlled by the system font size setting, otherwise directly by the slider.

For non-mobile-friendly pages (pages with a desktop-sized viewport – Slashdot e.g. uses 1000px – or more commonly, no viewport tag at all) the behaviour is a little more complex:
In automatic mode, [font size inflation](https://www.jwir3.com/font-inflation-fennec-and-you/) is applied (Chrome does something similar), which tries to bring up only the main content of the page up to a readable size without breaking the rest of the page layout too much (with more or less success). The magnitude of font inflation in that case again is controlled by the system font size setting.
Note also (I think possibly as a compromise between making the font size readable and possibly breaking the page layout too much by radically increasing font sizes) that font inflation is based on the assumption *that you'll zoom in on the bit of text in question so it fills the full width of the screen* (e.g. by double-tapping on the text in question, which on a non-mobile page will zoom it to fit the width of the screen).

In manual mode on the other hand, font inflation is turned off and we revert to just doing a plain text zoom. For desktop pages this of course means that 100 % corresponds to a rather small font size, because we're squeezing ~1000 CSS px into the width of a phone screen.

> Also at 200% font size the layout breaks. It's fine in automatic with the same actual font size.

Yes, the problem is that a plain text zoom will zoom everything on the page, and any moderately complex page probably likely doesn't handle that amount of text zoom well.

I think the original idea behind the current behaviour in Firefox was to leave an escape hatch to turn off font inflation in case *that* breaks some page too much, too. Because it was thought that succinctly explaining what font inflation is, what kind of pages it applies to and what exactly it does to them would be too complicated within the context of the settings, though, only a single toggle with the combined behaviour as described above was provided.

As you've correctly noted, this does have the drawback that currently there's no way to change the magnitude of font inflation other than by changing the global font size setting of your phone.

**Comment by kuro68k** [comment]
Thanks for the detailed explanation @buttercookie42.

Might it not be better to always use font inflation on non-mobile pages? Then the UI could simply be a single slider, with 100% or "normal" being the system font size setting.

The current manual font size setting is kinda useless because the actual font size it results in varies wildly from site to site. In my testing the automatic setting with the system font size increased results in consistent results and doesn't break layouts.

**Comment by kuro68k** [comment]
Is there somewhere else I should post this or is this the best place?

**Comment by SoftVision-LorandJanos** [comment]
I've tested this on the build this issue was logged on (Nightly 93.0a1) and the current build (Nightly 99.0a1).
Also checked on Chrome where the actual result is the same as on Firefox.
Tested using:
- Oppo Reno 6 (Android 11).
- Google Pixel 4 (Android 12).

**Comment by kuro68k** [comment]
> I've tested this on the build this issue was logged on (Nightly 93.0a1) and the current build (Nightly 99.0a1). Also checked on Chrome where the actual result is the same as on Firefox. Tested using:
> 
> * Oppo Reno 6 (Android 11).
> * Google Pixel 4 (Android 12).

Oh, I just tested it on A Google Pixel 5 and the result is different in Chrome.

Note that there was a partial fix. If you have font sizing set to "automatic" in Firefox Nightly the scaling will be correct. If you set it to manual font size selection it will be wrong.

Whatever was done to fix the automatic sizing needs to be replicated for the manual size setting.

**Comment by kuro68k** [comment]
Firefox Nightly 99.0a1 build #2015864427

Setting:
![Screenshot_20220222-125924](https://user-images.githubusercontent.com/2674466/155137657-9624119c-05d4-42b6-9c7d-f71b053320c9.png)

BBC News, font size is correct for the page and the Translate add-on visible at the bottom.
![Screenshot_20220222-130001](https://user-images.githubusercontent.com/2674466/155137727-2e41e3c0-7946-4703-8a06-924e7ee82eef.png)

Slashdot.org in desktop mode in Firefox. Note that the Translate add-on UI is now also using a tiny font, as well as the web page.
![Screenshot_20220222-130032](https://user-images.githubusercontent.com/2674466/155137876-978cb2bc-8a8b-4a63-9216-583af3d61fe3.png)

Same site in Chrome.
![Screenshot_20220222-130040](https://user-images.githubusercontent.com/2674466/155137912-c8a2ed8c-ba06-4637-97d1-eff4fa82c128.png)

**Comment by kuro68k** [comment]
FWIW it's still broken, but I changed phone so it no longer affects me.
