### ISSUE TITLE
FNX-5448 ⁃ At homepage address bar, include options for "Paste" and "Paste and go".

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#2089]
### Why/User Benefit/User Problem
Currently, the user has to press the address bar (which takes them to the Search page--where the address bar is in a different location), long-press the address bar on the Search page, press "Paste", then finally hit enter. Sure would save a lot of taps if a "Paste and go" was an option.

### What / Requirements
If the address bar is long-pressed, include these two pop-ups.
"Paste and go" would probably be used way more often than just "Paste".
Also include "Clipboard" and "Autofill".
Maybe keep the last-used selection listed first.

**Comment by yoasif** [comment]
See https://github.com/mozilla-mobile/fenix/issues/2368#issuecomment-491237397

I think an auto-suggested fill link/paste and go is the way to go here. 

Currently, fill link pastes and goes, and I am fine with that behavior if it is available when a URL or text is present in the location bar. 

Kiwi uses an arrow to allow the user to simply paste instead of pasting and go, which I think neatly caters to the requested use case.

**Comment by vesta0** [comment]
This will be considered in #4155
