### ISSUE TITLE
[Bug]: Opening and closing a tab from a collection crashes with history metadata

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20901]
### Steps to reproduce

1. Enable history metadata feature flag.
2. Have a tab saved in collections.
3. Open the tab.
4. Open the tabs tray.
5. Close the opened tab (there is a bug where it shows up in the inactive section that will be fixed by https://github.com/mozilla-mobile/fenix/issues/20900).

### Expected behaviour

Not crash.

### Actual behaviour

💥 

### Device name

Pixel 3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Device logs

```
2021-08-17 23:53:35.941 21454-21607/org.mozilla.fenix.debug E/places::ffi: Unexpected error: SqlError(IntegralValueOutOfRange(5, 2266005280))
2021-08-17 23:53:35.948 21454-21607/org.mozilla.fenix.debug E/ExceptionHandler: Uncaught exception handled: 
    mozilla.appservices.places.PlacesException: Error executing SQL: Integer 2266005280 out of range at index 5
        at mozilla.appservices.places.RustError.intoException(RustError.kt:58)
        at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince$suspendImpl(PlacesConnection.kt:1732)
        at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince(Unknown Source:0)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince$suspendImpl(PlacesHistoryStorage.kt:251)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince(Unknown Source:0)
        at org.mozilla.fenix.historymetadata.HistoryMetadataFeature$start$1.invokeSuspend(HistoryMetadataFeature.kt:41)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Additional information

cc: @gabrielluong @grigoryk 

https://user-images.githubusercontent.com/1370580/129976813-de5819f5-7ca0-4672-af8d-950e30a2124f.mp4

**Comment by grigoryk** [comment]
Took me a while to repro, but after finally getting it to crash in an emulator:

```
08-18 15:32:28.233 11862 11906 E AndroidRuntime: mozilla.appservices.places.PlacesException: Error executing SQL: Integer 3066679774 out of range at index 5
08-18 15:32:28.233 11862 11906 E AndroidRuntime: 	at mozilla.appservices.places.RustError.intoException(RustError.kt:58)
08-18 15:32:28.233 11862 11906 E AndroidRuntime: 	at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince$suspendImpl(PlacesConnection.kt:1732)
08-18 15:32:28.233 11862 11906 E AndroidRuntime: 	at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince(Unknown Source:0)
08-18 15:32:28.233 11862 11906 E AndroidRuntime: 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince$suspendImpl(PlacesHistoryStorage.kt:251)
08-18 15:32:28.233 11862 11906 E AndroidRuntime: 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince(Unknown Source:0)
08-18 15:32:28.233 11862 11906 E AndroidRuntime: 	at org.mozilla.fenix.historymetadata.HistoryMetadataFeature$start$1.invokeSuspend(HistoryMetadataFeature.kt:41)
```

... we see that the offending value `3066679774` is actually present in the metadata table:
![Screen Shot 2021-08-18 at 3 33 48 PM](https://user-images.githubusercontent.com/465422/129980838-eb97d967-a71f-4eac-8dfa-8046f825c91b.png)

The column with a large value is `total_view_time`. 3066679774 will overflow i32, which is what `total_view_time` is typed as in the `HistoryMetadata` struct.

How did we get this number? `total_view_time` is incremented with a passed-in `viewTime` during a metadata observation. Adding some logging at the point of the increment, and going through STRs, I see the following observations being made:

```
08-18 18:03:48.064 15556 15602 W places::storage::history_metadata: gri observation - MetadataObservation { document_type: None, view_time: Some(1542422875) }
08-18 18:04:04.695 15556 15612 W places::storage::history_metadata: gri observation - MetadataObservation { document_type: None, view_time: Some(67771) }
08-18 18:04:05.740 15556 15614 W places::storage::history_metadata: gri observation - MetadataObservation { document_type: None, view_time: Some(1542440554) }
08-18 18:04:15.453 15556 15612 W places::storage::history_metadata: gri observation - MetadataObservation { document_type: None, view_time: Some(78520) }
```

In this case, the offending value in the db was `3084863429`, Which is the sum of two of the observations above (1542422875+1542440554).

So, this uncovered an edge case: the current API allows overflowing `total_view_time`, and which point we'll just always crash when trying to read that value back.

However, how did we get such large viewTime values in the observations themselves? In Fenix, when viewTime observations are recorded, they're basically are "now - lastAccessTime for a tab". In these STRs, the tab opened in background is never actually accessed, so its `lastAccessTime` is 0. So, we get a viewTime observation of `now`, which in ms is something like `1629335884983` (numbers from a diffect test run). This is then converted into an Int: `1629335884983L.toInt() = 1543279799`. Which is an odd result, e.g. it's not just a truncation down to 32 bits:
1629335884983 = 0b0b10111101101011011111111001001010010110111
0b0b1011110110101101111111100100101 = 1591148325

Anyway, the overflow here is an interesting edge case, but the real problem is that open tabs may not have a set `lastAccess` value. Our metadata code assumes that if a tab is open, it should have accessTime, which isn't the case for background tabs that were never interacted with.

Since there isn't any actual view time to record here, we should just do nothing here instead of recording.

**Comment by grigoryk** [comment]
Filed an A-S issue for the overflow: https://github.com/mozilla/application-services/issues/4391
