### ISSUE TITLE
Display name instead of e-mail in menu

### ISSUE THREAD

**Issue by bxtom** [mozilla-mobile/fenix#20974]
I'm on Firefox 91.3.0 on Android 11.

Please add option to display "display name" instead of e-mail address in menu when user is signed to sync.

Currently e-mail address is exposed. 

This change will benefit people interested in privacy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17662)

**Comment by jp9856** [comment]
Hi! I can take a look at this. Did you have in mind that when someone clicks their email on the menu and it takes them to the Account settings page, a little switch button appears at the bottom indicating whether the user wants their name or their email displayed on the menu?

**Comment by bxtom** [comment]
Yes, that should do it.

**Comment by jp9856** [comment]
Hey, sorry for the delayed repsonse. I've been looking into this and it doesn't seem there's an easy way to implement the logic to choose what to display on the menu because the attributes of the account object are read-only, so I can't just add a "hideEmail" boolean. If you want it to just display the name automatically that'll be much easier to implement. I can do a PR and see what happens, but I can't promise they'll merge it. The leads on the app might have a reason for displaying the email instead of the name.

**Comment by bxtom** [comment]
Thanks @jp9856 for your analysis, time and work put into this issue. I really appreciate this. Yeah, lets do this PR an look whats happens.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810631

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
