### ISSUE TITLE
[Bug]: Firefox for Android will not add an IPv6-only search engine

### ISSUE THREAD

**Issue by anders-bk** [mozilla-mobile/fenix#21080]
### Steps to reproduce

1. Go to "Add search engine"
2. Try to add a search engine whose domain name server points only to an IPv6 address. 

### Expected behaviour

Firefox should add a search engine whether or not the domain has IPv4 enabled.

### Actual behaviour

Firefox only adds a search engine which has IPv4 enabled. If the search engine is only IPv6 Firefox will not add it.

### Device name

Lenovo TB-X304F

### Android version

8.1.0

### Firefox release type

Firefox

### Firefox version

91.3.1

### Additional information

Also tested it in Android 11.

![Screenshot_2021-08-30-17-27-11-708](https://user-images.githubusercontent.com/89813553/131414553-684e68c6-29f2-42a0-a284-cb32b75a558c.jpeg)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issues is reproducible on Firefox RC 91.4.0 and Nigthly 2021-09-01. Might be related to https://github.com/mozilla-mobile/fenix/issues/4343.
### Device used:
- Oppo Find X3 Neo (Android 11)
- OnePlus 6T (Android 9)

**Comment by SoftVision-LorandJanos** [comment]
This issue is reproducible on the latest Nightly 99.0a1 (2022-02-28).

**Comment by jackyzy823** [comment]
Well this is **not** a bug of fenix.

It is because your specified site "https://search.asynchronousexchange.com/search?q=1"  returns `429 too many requests` due to  the request leaking of headers like `User-Agent` and `Accept-*` . see `searx`'s [protection mechanism](https://searx.github.io/searx/admin/filtron.html)

and fenix think that status code do not work.
https://github.com/mozilla-mobile/fenix/blob/35be05d59981c06f0033d53f9c052e7787fb512a/app/src/main/java/org/mozilla/fenix/settings/search/SearchStringValidator.kt#L32-L34

and
https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Response.kt#L140

**Comment by anders-bk** [comment]
Hi there!

Thanks for taking a look into it. Actually at the time of reporting the bug I had tested it without any kind of filter or protection, using IPv4-only and then IPv6-only in the same instance. Now without filter or protection it connects flawlessly, so I guess someone fixed something in the way.

Just tested the request headers, they seem quite complete. The only anomaly is «accept: */*». The filter is rejecting the «connection: close» header. Anyway, I agree that this is not anymore a bug of Firefox for Android.
