### ISSUE TITLE
Transfer bookmarks and user data from other browsers to Firefox for Android

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#21111]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

If a user has bookmarks in Chrome for Android, they need to sign into Chrome on desktop, import to Firefox then use Firefox Sync to bring them to Firefox for Android.  Would be good if this can be done directly - I believe that this may have been a feature of Fennec.

### How do you know that this problem exists today? Why is this important?

Users ask about this in SUMO and it will help users move from other browsers to Firefox for Android.

### Who will benefit from it?

Users wishing to move from other mobile browsers (primarily Chrome) to Firefox for Android.

**Comment by Barebackee** [comment]
This fix would be really helpful to those who do not run chrome on there PC's but who still have Chrome on their mobile device but want to delete it. 
I personally have already gotten rid of nasty Chrome on all of my devices but one. I am simply waiting to transfer my bookmarks and the like so that I can delete their ass and be rid of em forever. With a solution to this issue myself and countless others could finally be free of the evil axis that is that browser/search engine who's name we shan't not mention anymore.
Go Firefox!!

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1349476#answer-1440835

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/2080 and/or https://github.com/mozilla-mobile/fenix/issues/417

**Comment by plwt** [comment]
Those issues relate to exporting data from Fenix.  This issue is to help people wanting to move to Fenix.

User feedback: https://support.mozilla.org/en-US/questions/1362198
