### ISSUE TITLE
[Bug]: Selecting all tabs to add in a collection does not tick all the check boxes

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21169]
### Steps to reproduce

1. Open a few tabs and create a collection
2. Bring up the contextual menu for the collection
3. Tap on the Add tab button
4. Tap the Select all button
5. Observe the check boxes

### Expected behaviour

All the open tabs are selected

### Actual behaviour

Only one or two tabs are selected depending on how many are open

![241422201_1694162414102949_8107188869994230652_n](https://user-images.githubusercontent.com/89511597/132370889-8b57ab9a-aa5a-464f-aeb8-6b5982b1d1ac.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 2021-09-07

### Additional information

The issue only occurs on Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17795)

**Comment by SoftVision-LorandJanos** [comment]
I can confirm the issue is reproducible with the latest Nightly (94.0a1 - 2021-09-21) and latest Beta (93.0.0beta4) with the following details:
- When there is a scrollable amount of tabs, only the tabs that are not displayed are checked (on the top of the list), and after scrolling up and back down, most of the bottom ones are selected, excepting some in the middle.
- Same behavior when deselecting the selected tabs where unchecking is not complete.
- While the tabs appear unchecked when selecting all, the number of tabs selected is correct and after saving, they are correctly added to the collection.

Devices used:

Samsung Galaxy Tab S3 (Android 9).
Huawei P30 (Android 10).
Xiaomi Mi11 Lite (Android 11).

Video:

https://user-images.githubusercontent.com/48829350/134159969-bda7a038-0f26-4cef-9f4a-8c5b9b7a3697.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 110.0a1 (2023-01-09) build.
Device used: Oppo Find X5 (Android 12).
Marking the ticket as verified.
