### ISSUE TITLE
FNX-5466 ⁃ [Feedback] The homepage's 3-dots menu doesn't make sense, it's not necessary

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2117]
All the options in the homepage's 3-dots menu are already available in the main 3-dots menu on the address bar, so I don't see a point in having one more. It's like a duplicated feature, cluttered. Fenix already has many of these menus. It's confusing, I don't know if should go to the homepage before going to the library or if I should go to library directly from the address bar menu.

## ![Screenshot](https://user-images.githubusercontent.com/32398857/56902212-26b83a80-6a70-11e9-9488-15a2a0ebaca2.jpg)UNITO-UNDERSCORE!20190429-110825!UNITO-UNDERSCORE!Firefox Preview!
![Screenshot](https://user-images.githubusercontent.com/32398857/56902213-2750d100-6a70-11e9-9002-88304f5d1df1.jpg)UNITO-UNDERSCORE!20190429-110850!UNITO-UNDERSCORE!Firefox Preview!

**Comment by cadeyrn** [comment]
What you're requesting - either remove the menu button on the Fenix home screen or remove the menu items from the full menu - is an UX nightmare.

1) It doesn't make sense at all that I have to open a website if I want to change my settings or open the library. So it's no option to remove the menu icon from the Fenix home screen.

2) There is also no good reason that I have to switch to the Fenix home screen if want to change my settings or open the library after I viewed a website.

There is not really any duplication because these are different screens. Such important things like settings and the library have to be accessible from every screen. And by the way, it's the same in others browsers like Firefox and Chrome, too.

**Comment by Lululalu** [comment]
@cadeyrn it's your right to disagree and it's important part of a discussion. Regarding your number 1, I believe the address bar should be exhibited on the home screen, as it does happen on any browser, this way the 3 dots menu is right there close to your thumb. Having the address bar on the home screen allows the user to search by easily touching the address bar, making that enormous search bar redundant. In this scenario the search bar can be removed too, making the interface cleaner or opening space for new/upcoming features.

**Comment by vesta0** [comment]
@Lululalu thanks for your suggestion. At this time, this doesn't align with our concept but we will consider this during user testing.
