### ISSUE TITLE
The back arrow turns black when cancelling share tab

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21228]
### Steps to reproduce

1. Have at least one tab open 
2. Open 3-dot menu > History
3. Select the previously opened tab
4. Open and close the share menu
5. Observe the return button

### Expected behaviour

The UI color scheme is consistent in all menus.

### Actual behaviour

The color of the back arrow changes from white to black. Selecting the tab again reverts the arrow to its initial color.

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-10

### Additional information

Same behavior can be observed in Firefox Beta 93.0.0-beta.1 and RC 92.1.1 builds and also for recently closed tabs. This issue does not occur with dark theme selected.
![241675780_1714563332071328_6598907012419885125_n](https://user-images.githubusercontent.com/89511597/132823653-be5b9dbc-d140-46fa-9324-e81434291deb.jpg)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-17834)

**Comment by SoftVision-LorandJanos** [comment]
I can confirm the issue is reproducible as described. And as mentioned above, on dark theme it's not reproducible.

Firefox versions tested:
- Nightly (94.0a1 - 2021-09-21).
-  Beta (93.0.0beta4).
- RC 92.1.1.

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by delia-pop** [comment]
This is still reproducible on 101.0.0-beta.1. 
Also reproducible when after tapping on the 3 dot menu and selecting "Open in new tab".

**Comment by delia-pop** [comment]
Reproducible on the latest Nightly from 05/17 with Google Pixel 6 (Android 12).

**Comment by delia-pop** [comment]
This issue is still reproducible on the latest Nightly 106.0a1 from 09/12 with Google Pixel 6 (Android 13). When canceling the tab share from the Recently closed tabs, the back arrow is black.
<img src="https://user-images.githubusercontent.com/89388888/189657765-11d45b8f-2d1c-4a02-8603-24698ed038aa.JPEG" width="40%" />

**Comment by fice-t** [comment]
It seems that the tint of the toolbar's `navigationIcon` is reset when cancelling the share menu (I have no idea why).

Note that the underlying bug is actually present in dark mode, but the reset tint of the `navigationIcon` is still legible in dark mode. One can verify this by hardcoding the tint to some easily perceptible value in `LibraryPageView.kt`.

I think working around the bug is possible by calling `updateToolbar` after cancelling the share menu, but I don't know where to put that call.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813093

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
