### ISSUE TITLE
[Bug]: Closing bottom tab hides the next tab, not tappable until popup fades

### ISSUE THREAD

**Issue by OJFord** [mozilla-mobile/fenix#21232]
### Steps to reproduce

1. Have tabs configured in list view
2. Have enough tabs open that there's some vertical scroll
3. Close bottom tab

### Expected behaviour

1. Pop-up to undo close appears
2. Remaining tabs remain tappable to view or close

### Actual behaviour

1. Pop-up to undo close appears
2. Remaining tabs slide down behind it
3. Pop-up obscures bottom tab, so it has no tappable area to view or close

### Device name

Nokia 3.4

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

92.1.1

### Additional information

This is particularly annoying when trying to close multiple recent tabs, as it prevents the user from just tap-tap-tapping the area where each 'x' will be (as they slide down) since that's where 'undo' appears.

Possible fixes would be to not slide down behind the pop-up, so the tabs are listed above it, or to make it smaller so that it doesn't obscure the 'x' or all of the title (to tap to view).

**Comment by SoftVision-LorandJanos** [comment]
Hi @OJFord ! Thank you for your report!

I can reproduce the issue described by you. (With 92.1.1).
I remember a similar issue about the "New tab" button overlapping the "x" from the last tab in the list, but that was fixed.

On the latest Beta (93.0.0-beta3) and on the latest Nightly (94.0a1 - 2021-09-17T02:58:52.277509) this issue is not reproducible, as the list ends higher so there is no overlapping by the snackbar.

Device used: Xiaomi Redmi 11 Lite (Android 11).

**Comment by OJFord** [comment]
Thanks, yes I've just updated to 93.1.0 and it is indeed mostly fixed - in the first possible way I described, so when you've fully scrolled down the list stops a bit above, leaving space for what I now know is called a 'snackbar' (😉).

If you scroll up slightly so that you're looking into the middle of the list though, the list still fills the screen, so closing one there can still obscure middle-of-list close buttons.

This is not such a problem for me, so I'm happy to close anyway, just thought I'd mention it. Cheers!
