### ISSUE TITLE
enable about:config in stable release

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#21276]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
I'm aware there is an open issue but it's locked and it haven't had any progress since release. People in favor of this don't need to add comments only like this post so they realize it's an important feature.

### What is the user problem or growth opportunity you want to see solved?
Since the release of this abomination (fenix) there have been so many users complaining about how you ruined thier experience but non has been more important than this there have been so many people who either left ff or started using forks that often lag behind in updates and generally not very safe.

### How do you know that this problem exists today? Why is this important?
As i said many including myself left ff and are reluctant of using it on android for it's flaws but tbh i can tolerate them if only you hadn't removed this feature.
I understand ff has a smaller team than chromium and can't compete with them but please think this over, chromium (and forks) allow a lot of configuration through thier gui (managing cookies, java script, etc) and offer a supreme ux and while they are targeted at normal users they allow users to change many settings that can break the browser through chrome://flags without even a warning.

On the other hand firefox has both terrible ux and ui it dosen't allow many configuration in ui and all controls are hidden in about:config there is just no way you could dramatically allow users to enable them through gui (if you could you would have done that by now), also even if you could it would take alot more time to add them.

### Who will benefit from it?
Many users who want to configure thier browsers or use a feature that can be only enabled or configured through about:config.
Pelease respects your users freedom to control thier software this is supposedly an opensource project that respects users, taking thier right to control thier browser (which even google somehow respects in stable chrome) is just so much against what you advertise yourself.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17862)

**Comment by 0x391F** [comment]
Yes, I need to use 1.1.1.1 DoH server to encrypt the DNS traffic and avoid DNS pollution, but I couldn't enable it in Fenix

**Comment by 0x391F** [comment]
Besides, I need about:config to disable WebRTC (media.peerconnection.enabled=false), disable cache on disk (browser.cache.disk.enable=false) and so on, but I couldn't do them now.

**Comment by 0x391F** [comment]
One reason I don't want to use Fenix Nightly is, Fenix usually crash, even I'm using release version, Nightly must be worse.

**Comment by 0x391F** [comment]
One reason people (include me) like Firefox is, it's CUSTOMIZABLE, about:config is a very easy way to adjust it. I know one reason Fenix team disable about:config is, user maybe monkey the config, then Fenix go wrong, and they will complain Fenix is hard to use. But I think we can add a warning after user into about:config as same as Firefox desktop version.

**Comment by 0x391F** [comment]
And I think Fenix could add a feature so that user could easily reset the settings and about:config, and retain user data (history, bookmarks, etc).

**Comment by 0x391F** [comment]
And I think Fenix could add a feature so that user could easily reset the settings and about:config, but retain user data (history, bookmarks, etc).

**Comment by Nickoriginal** [comment]
> Since the release of this abomination (fenix)

Why you are even using Fenix or its forks if it is so abominate for you?
Sadly, it (closed about:config) became a philosophy for Fenix developers in a stable channel and there will be no changes. If it is critical enough to you, I propose the best solution - Fennec F-Droid, what have about:config enabled, syncs with the **stable** Fenix and fully open-source (checked by F-Droid). Also you can try Firefox Beta, what is less unstable than Nightly and change the major version number only when the second beta released (e.g. update to 93.0.0.-beta.**2** after last 92.0.0-beta.x) It will a little bit help you from losing your data.

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/21276#issuecomment-918979046
https://github.com/mozilla-mobile/fenix/issues/4584

**Comment by Yanjoi** [comment]
@Nickoriginal I didn't say i'm using ff on android let alone it's forks, forks are not maintained well the best version of ff is it's official stable release, you shouldn't encourage such behaviors if you have read my post you would have known i'm already aware of alternatives.
The problem here is as an old firefox user i left when they replaced fennec with fenix, since then i have came back every few months to check for improvements.
Sadly ff devs have given alot of promises that they make things better but they didn't, the only reason i perfer to use ff over chrome is all the control i get using about:config.
It's not reasonable saying since firefox devs made such a decision it cannot change, if we were to go by devs decisions and wouldn't have on effect on changing them, then why use ff we can just use chrome and let google decide for us. The whole point of using firefox is to take back control, but unfortunately fenix devs took that away with this decision.

**Comment by DrSensor** [comment]
I also need this to enable Screen Capture API for presentation. Does GeckoView support this?

(the API supported in chrome for android through chrome://flags where the default is disabled)

**Comment by plwt** [comment]
User feedback: https://discourse.mozilla.org/t/about-config-missing/66537/29

**Comment by wangwo** [comment]
I was just getting to like FF again  when it stopped searching keywords from address bar .  Trying to fix this one suggestion was check keyw setting in about:config. But that doesn't work either  . I am mot an advanced FF user, i just want to use ff but every time I try  it seems ff devs hate me  . So, thats it, I'm not using FF browser  ever again. Going to Brave  .

**Comment by codingepaduli** [comment]
I just want this feature on stable release for my customization. Why not? Lots of user don't even know the existence of that.

If you think about:config can make the browser seriously unstable, you can choose to let us enable it from the "debug menu", as explained in the chapter "Running the Sync server" [Run your own Sync-1.5 Server](https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html#running-the-server).

I extract the following sentences from the document: "**Firefox for Android (“Daylight”, versions 79 and later) does support using a non-Mozilla-hosted Sync server. Before logging in, go to App Menu > Settings > About Firefox and click the logo 5 times. You should see a “debug menu enabled” notification. Go back to the main menu and you will see two options for a custom account server and a custom Sync server**.

**Comment by yutayu** [comment]
I want to disable diskcache.
So I agree with this.

**Comment by JJRcop** [comment]
I would like to say I support about:config in stable, but think the original issue body is way too opinionated and negative.

Since the reporter is a ghost now, I hope the body can be edited to be more friendly and focus on the issue instead of purely subjective experience.

I want to access about:config on stable because I want a stable experience by default, while being given the option to reduce stability by my own choice.

Firefox Nightly for Developers is not suffucient, as it is an unstable experience by default, with an option to reduce stability further. This is not a good experience for a tech savvy end user who doesn't intend to develop anything new for Firefox.

I want the end-user polish and shine while being given the ability to ruin it and break it myself at my will.

**Comment by JJRcop** [comment]
I would like to say I support about:config in stable, but think the original issue body is way too opinionated and negative.

Since the reporter is a ghost now, I hope the body can be edited to be more friendly and focus on the issue instead of purely subjective experience.

I want to access about:config on stable because I want a stable experience by default, while being given the option to reduce stability by my own choice.

Firefox Nightly for Developers is not suffucient, as it is an unstable experience by default, with an option to reduce stability further. This is not a good experience for a tech savvy end user who doesn't intend to develop anything new for Firefox.

I want to have the end-user polish and shine, but also the ability to ruin it and break it myself at my will.

**Comment by Rexogamer** [comment]
I'm slightly surprised that it was removed from stable to be honesty - surely, as mentioned above, a warning (similar to the one on FF Desktop) would be sufficient?

**Comment by heham** [comment]
I want to support the tampermonkey or like this plugin.

**Comment by Krjal** [comment]
I need this option currently to use security certificates for my work intranet and https filtering at home. Currently I need to use either unstable versions, older (less secure) versions or Chromium browsers which work fine with system level installed certificates by default. 

Now restricting things by default to cut down on user errors and unstable, insecure situations is fine and understandable but removing the options as well goes against the whole reason I'm using Android and Firefox in the first place.  

I think the old boilerplate warning was more than enough. 

PS. Do any other users have suggestions for a 'stable' nightly release I could sit on for a bit until about:config gets restored?

**Comment by bigConifer** [comment]
@Krjal As mentioned above you could switch to [Fennec F-Droid](https://f-droid.org/packages/org.mozilla.fennec_fdroid/) where about:config was re-enabled by a [prebuild.sh](https://gitlab.com/relan/fennecbuild/-/blob/master/prebuild.sh) script.

PS: While proposing third party builds is an ugly workaround and not good practice in use of issue trackers, the developers will see that demand is still high for having this issue fixed.

**Comment by user8446** [comment]
There is a lot more demand for this than the Firefox team realizes because alternatives such as F-Droid Fennic and others that users are going to for this do not have telemetry.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@user8446, that's one of the problems of opting-out of telemetry, be it during compilation or not.

**Comment by nICEnnnnnnnLee** [comment]
Hmmm... The featrue's not really that important for me, at least.

I'm a user with no access to Google Play in my working or living network environment, so I install the app from Github Release.  

It's no different for me to download a Stable version or a Beta version nearby. 

For example, with **[Firefox 106.1.0](https://git.nicelee.top/mozilla-mobile/fenix/releases/tag/v106.1.0)** Released, and I want `about:config` enabled, I could select [Firefox Beta 107.0b1](https://git.nicelee.top/mozilla-mobile/fenix/releases/tag/v107.0b1) or [Firefox Beta 106.0b5](https://git.nicelee.top/mozilla-mobile/fenix/releases/tag/v106.0b5) to download

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/7865
