### ISSUE TITLE
Rename recently saved

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21337]
Tracking for https://mozilla-hub.atlassian.net/browse/FNXV2-17870

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-09-23T05:07:37.954955).

"Recently bookmarked" is displayed on home screen instead of "Recently saved".

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
