### ISSUE TITLE
Add setting for disabling (auto) tab grouping

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21360]
### Steps to reproduce

Search any item
Search any other item
Open any site from top site
It is creating 3 different sections...what's weird is swipe to close tab not working for search tabs

Please fix this bug

### Expected behaviour

All tabs arrangements should be same as before
New implementation is bad...pushing tabs bottom

### Actual behaviour

Each search term creating a new section moving other tabs bottom

Moreover swipe to close not applicable for search tabs

### Device name

rog3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Additional information

![Screenshot_20210917-215409136](https://user-images.githubusercontent.com/58127841/133822443-20fceb7e-c0a2-4bf5-855e-be73458c846c.png)

**Comment by eavesjump** [comment]
It sorted my tabs incorrectly, and I can't fix the order. This is driving me up the wall. How do I turn this off?

**Comment by klint** [comment]
Also, with the tab tray in list, adding a cross to close the tab induces yet another loss of information density! Swiping is working well and quite intuitive. What is the point in adding the useless button?

**Comment by klint** [comment]
i know this is work in progress, but what is the point of reminding the search that lead to a tab ?i find it useless, space consuming and dizclosing private informatiob. can there be a setting to turn the feature off ?thanks

**Comment by ListeningGarden** [comment]
these experiments should be opt-in, either by way of an option provided in the menu or through the secret dev menu where some other user studies have had features tucked away until they were more matured and also had a way to disable once they were integrated normally. i have found using firefox nightly increasingly more difficult over the past few months with additions like this and inactive tabs, neither of which are welcomed additions and only serve to confusingly shuffle my data away from where i want it to be.

**Comment by klint** [comment]
> Also, with the tab tray in list, adding a cross to close the tab induces yet another loss of information density! Swiping is working well and quite intuitive. What is the point in adding the useless button?

In addition to the loss of information density, I forgot to add that tabs can too easily be closed by pressing the cross icon by accident. Swiping is less hazardous IMHO. 
Thanks.

**Comment by Octoton** [comment]
> > Also, with the tab tray in list, adding a cross to close the tab induces yet another loss of information density! Swiping is working well and quite intuitive. What is the point in adding the useless button?
> 
> In addition to the loss of information density, I forgot to add that tabs can too easily be closed by pressing the cross icon by accident. Swiping is less hazardous IMHO.
> Thanks.

And when undoing a close event, the tab will not even go back where it was before. Which is quite frustrating as manual reordering is not there yet

**Comment by Cheap-Skate** [comment]
I agree with all these comments. Fenix keeps re-arranging my tabs which is driving me nuts.  Now we have searches at the top, opened tabs in the middle and inactive tabs at the bottom. 

With other browsers I know that eg my "News" tab is always third from the top. With Fenix it could be ... anywhere?? ... and its position changes depending on what else is going on. Gaaaah!

Please don't mess with my tab order! Fennec had manual tab re-ordering, it was really great. If you can't give us that, please just leave tabs in a fixed (eg chronological) order. 

Fenix's homescreen and tabs screen are IMHO far too complicated and counter-intuitive.

**Comment by WesleyAC** [comment]
I agree with everyone here. I was exited for a split-second when I saw that the tab screen had updated, since I thought it meant that #20684 was fixed, but instead it was a change that I can't find any evidence of anyone asking for that makes the experience even worse for me (and seemingly plenty of other people, given this issue).

Nearly 50 people have :+1:ed #20684, and they largely seem to be asking for the tab tray to be left alone, or for there to at least be an option to disable all the changes that are being made to it. Why are you instead doubling down on this? Are there a ton of people who actively want these changes who just are being quiet about it on GitHub?

I like Firefox Mobile, it's really a shame that every update seems to be making it worse to use these days. It's been a month and a half of the tab-switching experience being essentially broken. Are there any plans to fix it?

**Comment by WesleyAC** [comment]
CC @rocketsroger @jonalmeida

**Comment by SpandexWizard** [comment]
I thought the inactive tabs was bad but this grouping thing is madness. Look I keep almost a hundred tabs open. The only way to do that efficiently is to leave them in chronological order so you know where the hell everything is. It doesn't even make sense to group all these tabs under a search term, half of the results I opened where only vaguely related to my query and interested me. I'm not going to remember what I was searching for when I opened that tab! Leave the tabs alone, in chronological order like the should be!

**Comment by SpandexWizard** [comment]
> > Also, with the tab tray in list, adding a cross to close the tab induces yet another loss of information density! Swiping is working well and quite intuitive. What is the point in adding the useless button?
> 
> In addition to the loss of information density, I forgot to add that tabs can too easily be closed by pressing the cross icon by accident. Swiping is less hazardous IMHO.
> Thanks.

Personally I hate swiping. I'm more likely to accidently swipe a tab off screen while scrolling quickly than I am to press an X on accident. I'd prefer an option to disable swipe over the opposite.

**Comment by SpandexWizard** [comment]
Man I thought it was bad before but it's worse than I thought. Open a tab and search for something, open two or three tabs that seem relevant. Those tabs vanish up to the top of the stack (and not the bottom where they should be. -_-) under a new heading with the search query as it's box. Which is the bad behavior I was familiar with. But then go to one of those tabs and open a new tab by following a link? It goes in other. Now you have to find your tab again! What madness. How am I supposed to shop when opening a couple places to buy from creates it's own category of tabs but when I go and open something I want to buy on a new tab it puts that thing in the generic tabs??

**Comment by Octoton** [comment]
What kill me the most is that chrome found a better way to put tabs for a new search in its own world: fucking tab group ( "open new tab in group")
Firefox even have a partial tab group concept called collection, they just need to go all the way with it and open collection into groups of tab in the tab tray.

**Comment by bb010g** [comment]
I just want to be able to at least opt-in to the existing, boring, linear tabs view. I can't do that in multiple ways now, as the inactive tabs grouping cannot be disabled, and the search tabs grouping cannot be disabled. This functionality used to be the default. Fenix Nightly having no boring linear tab collection functionality at present is very strange.

Why aren't these new features effecting the core tab experience being implemented with enable/disable toggles from the start? Even if you want to enable these features by default on Nightly, let people disable them if they want.

Are there no disable options because these features are implemented in a way where the classic linear tab experience can no longer be reasonably offered by Fenix?

**Comment by bb010g** [comment]
@WesleyAC
> I was excited for a split-second when I saw that the tab screen had updated, since I thought it meant that #20684 was fixed, but instead it was a change that I can't find any evidence of anyone asking for that makes the experience even worse for me (and seemingly plenty of other people, given this issue).

There might be information for why the search term tab section feature request was proposed or implemented at <https://mozilla-hub.atlassian.net/browse/FNXV2-17383>, but this JIRA instance is unfortunately not readable by the community.

**Comment by USvsTHEM** [comment]
been telling devs bout the google type rearrangements started with that idiotic scroll menu when the most used buttons are hiding at the bottom which makes zero since but hey not much makes since these days they gotta keep up i guess told a dev and he basically said forget my opinion some shit Google would tell me he must be a opp infiltrating from inside every month firefox gets worse and worse

**Comment by USvsTHEM** [comment]
i been using fennec 88 ever since the design still makes logical since until otherwise that scrollable.menu is a no no desktop android or augmented reality its wack!!!!!!

**Comment by sheikh-azharuddin** [comment]
> i been using fennec 88 ever since the design still makes logical since until otherwise that scrollable.menu is a no no desktop android or augmented reality its wack!!!!!!

For that that they could have used samsung mobile browser implementation but no no no....

**Comment by pocmo** [comment]
Folks,

- Thank you for providing feedback for this feature. This feature will go through multiple iterations and feedback is needed to make it a good one. But please keep it constructive. I do understand that using pre-release features can be frustrating at times.
- Nightly is our vehicle for testing such changes. Besides other things, we need this channel to ship early versions of such features to test them in real life situations. As such Nightly will always be experimental. We always try to keep Nightly stable (with regards to crashes), but the feature set may change or derivative from the stable versions.

I will turn this issue into an issue about adding an option to disable auto grouping. This seems to be the major feature request here. Tab reordering was mentioned too, we have an issue for that already (#10344) and contributor @ssk97 has jumped in to do some groundwork for that (Thank you!). Please file separate issues for improvement suggestions that would make (auto) tab grouping a feature you'd consider using.

**Comment by WesleyAC** [comment]
Thanks for the response :)

> Nightly is our vehicle for testing such changes. Besides other things, we need this channel to ship early versions of such features to test them in real life situations. As such Nightly will always be experimental. We always try to keep Nightly stable (with regards to crashes), but the feature set may change or derivative from the stable versions.

As @ssk97 mentioned on #20684, the reason I'm using Nightly, along with many other people here is because it's the only way to get both arbitrary addons and auto-updates. I'm willing to accept some instability as a way to get those features, but it's frustrating that Mozilla is forcing anyone who wants that to endure months of core parts of the browsing experience being broken.

I'd be happy to use Beta or Stable if that let me have the addons I want. I'd also be happy to use a version of Nightly where undisableable features that break the browsing experience are only forced on me for a week or so before an option to disable them is built. Unfortunately, neither of those options are available to me.

I see @csadilek closed #21382, mentioning that input from the product and UX teams was needed to get addon support into Beta. Can we get that conversation be started? It's been four months since #19594 was filed, and yet there's been no response from Mozilla other than the qa-triaged label.

@cadeyrn / @csadilek: What is the process to get people a solution for arbitrary addon support that doesn't require opting into the amount of instability that Mozilla wants to exist in Nightly? It's hard for me to understand what the significant downsides of enabling support for this in Beta are (given that creating a collection on AMO, enabling Secret Settings, etc is already enough work to discourage most users who don't know what they're getting themselves into from doing this). Is there a specific reason you think that this *isn't* ready for Beta, or is it just that the product team has not discussed it? If it's the second, how can we make that discussion happen?

**Comment by WesleyAC** [comment]
> Please file separate issues for improvement suggestions that would make (auto) tab grouping a feature you'd consider using.

I went ahead and filed #21406 for the fact that opening links in new tabs doesn't always result in that tab being in the same group as the tab it was opened from. That, in combination with the features mentioned above (ability to collapse/expand, manually move tabs between groups, reorder groups, and open new tabs in a given group) would be enough for me to want to try out using this feature. #21406 alone makes me not want to use it, since it ends up being a guessing game as to whether any particular tab will end up in the group or the linear tab view.

**Comment by pocmo** [comment]
> Personally I think auto-tab grouping would be useful to me if the following features were in place
(1) manual tab grouping, so I can break up or amalgamate the auto-groups into a tab group of my own choosing
(2) manual tab ordering by drag and drop, so I can move stuff out of the group into the "ungrouped" list of tabs
(3) tab groups which take up less space in the tabs tray, the group can fold up & takes up 1 tab's worth of room

Thank you, these are all great suggestions!

> the reason I'm using Nightly, along with many other people here, is because it's the only way to get both arbitrary addons and auto-updates

Like the current iteration of the tabs tray, this is an experimental feature, in this case to have the option of testing various add-ons. In its current form its not something that can ship. That's why it's not in Beta. Valid discussion to have, but please not in this issue here.

> I went ahead and filed #21406 for the fact that opening links in new tabs doesn't always result in that tab being in the same group as the tab it was opened from.

Thank you! This is indeed a confusing behavior.

**Comment by WesleyAC** [comment]
> Like the current iteration of the tabs tray, this is an experimental feature, in this case to have the option of testing various add-ons. In its current form its not something that can ship. That's why it's not in Beta. Valid discussion to have, but please not in this issue here.

Where is the place to have that discussion, though? If #19594 had gotten any response from Mozilla, I would have it there, but as it is, I don't see much of a point in adding another comment to that thread saying basically the same thing as the initial issue.

**Comment by edwardgalligan** [comment]
> *Nightly is our vehicle for testing such changes. Besides other things, we need this channel to ship early versions of such features to test them in real life situations. As such Nightly will always be experimental. We always try to keep Nightly stable (with regards to crashes), but the feature set may change or derivative from the stable versions.*

To reiterate what others have said here, as a Nightly user I do appreciate this and am very willing to absorb a lot of change and instability into my daily browsing. But there needs to be a balance: making workflows that have been stable for years completely unusable is ok if it's an accident, but if it's planned feature rollout I don't think it's unreasonable to prioritize making it optional BEFORE enabling it, even for nightly users.

It's difficult to test a browser you can't use.

**Comment by notJerl** [comment]
My use case is definitely an edge case and I don't expect the devs to go out of their way to support it, but it gives a good example of how this feature can go very wrong for users. 

Most of my search engines aren't actually search engines. Instead, they format a link to a specific page, e.g. using a resource ID. I have a search engine to jump to pretty much any specific page in this workflow, but I usually only need to use it at the beginning of a task - once I've gotten to the first page in a task, I can click through to most of what I need to do.

However, *all* of these pages match search engines I have set up, so whenever I open a new tab, it gets put in a new group named after its parent. The end result is essentially that every tab I open is in its own separate group - usually by itself, sometimes with one or two separate tabs, but always separate from their parent, defeating the point. 

Again, I know this is an edge case. I promise I didn't deliberately manufacture a worst-case scenario - this is my actual workflow, but I also recognize that it isn't the norm. However, since search engines are intended to take the place of bookmark keyword searches, a lot of people who use them in their workflow are going to be annoyed by this at least occasionally.

**Comment by DableUTeeF** [comment]
> > Personally I think auto-tab grouping would be useful to me if the following features were in place
> > (1) manual tab grouping, so I can break up or amalgamate the auto-groups into a tab group of my own choosing
> > (2) manual tab ordering by drag and drop, so I can move stuff out of the group into the "ungrouped" list of tabs
> > (3) tab groups which take up less space in the tabs tray, the group can fold up & takes up 1 tab's worth of room
> 
> Thank you, these are all great suggestions!
> 
> > the reason I'm using Nightly, along with many other people here, is because it's the only way to get both arbitrary addons and auto-updates
> 
> Like the current iteration of the tabs tray, this is an experimental feature, in this case to have the option of testing various add-ons. In its current form its not something that can ship. That's why it's not in Beta. Valid discussion to have, but please not in this issue here.
> 
> > I went ahead and filed #21406 for the fact that opening links in new tabs doesn't always result in that tab being in the same group as the tab it was opened from.
> 
> Thank you! This is indeed a confusing behavior.

Honestly, all you need to do is make the option to turn off these "innovative" features. 

Or maybe focusing on making well proven features that are missing like Search in history.

At this point from user perpective, it felt like the custom Add-ons feature is kept here because everybody will run away otherwise.

**Comment by DableUTeeF** [comment]
Or maybe focusing on making well proven features that are missing like Search in history.

At this point from user perpective, it felt like the custom Add-ons feature is kept here because everybody will run away otherwise.

And these new features won't have the option to turn off for a month or so for more efficiency in bug reporting.

**Comment by Cheap-Skate** [comment]
@UX team

Is it possible you have under-estimated how much effort people put into organising their tabs tray and how much they want tabs to stay where they are put? IMHO a lot of people treat the tabs tray like their Android Home screen:- they want to arrange tabs as they see fit and then they want the arranged tabs to **stay where they are put**. An Android Home screen which did not allow manual app re-arrangement, or which from time to time re-arranged apps, would be grossly inconvenient. IMHO the same is true for a browser tabs tray.

I find Fenix incredibly inconvenient to use for this reason. And it seems to get worse with every iteration:-

1. _Fenix opens nearly everything in a new tab_. So the tabs tray gets very cluttered with stale and duplicate tabs. That's bad.

2. _Fenix sometimes re-arranges tabs in the tab tray according to its own rules (inactive tabs, auto-grouping)_. So it's hard to find my tabs, I can't reliably locate them spatially or using muscle memory. That's really bad.

3. _Fenix doesn't give me the tools (tab drag and drop, tab grouping) to manually fix the two problems above_. It **might** be OK for Fenix to re-arrange my tabs if I had the manual tools to put them back where I wanted and for them to **stay where they are put**. But it doesn't. That's really, really bad.

Re 1 several issues filed eg https://github.com/mozilla-mobile/fenix/issues/20012#issuecomment-865289619.

Re 2 moaning and groaning, see upthread here plus #20684, #21406

Re 3 that's #10344. I find it astonishing that Mozilla is focusing its own efforts on a fairly esoteric feature like auto-grouping, but a key feature like tab drag & drop is being left up to a volunteer (kudos to @ssk97). Does this mean that tab drag & drop is not on Mozilla's core roadmap, even though it's key for usability, feature parity with Fennec, Chrome, Samsung, etc etc?

IMHO Fenix needs to learn to walk before it runs. I think Fenix needs a boring, stable, manageable tabs tray offering feature parity with Fennec and Chrome before you move on to all this esoteric auto-grouping and inactive tabs stuff. So that means:- default chronological sorting; optional manual drag and drop; tabs stay where they are put; tabs can be grouped/ungrouped/regrouped in a Chromesque way.

I'm sorry for the harsh criticism but it's timely. I'm a long time Firefox/Fennec/Fenix user and have contributed a lot to the various projects. I really want Fenix to be a success. But I just don't use it any more because tab management is so awkward and slow. I've switched to Samsung Internet and it's miles better than Fenix. Everything tab related is just so much easier, quicker and more logical.

**Comment by klint** [comment]
Don't forget that this is still work in progress and that the production version still has a stable boring tray as you describe. I don't have a problem with the nightly looking for itself a bit for some time... But yes in the end it needs to be stable, preferably with deactivable new ux disrupting features like tab grouping or deactivation

**Comment by DableUTeeF** [comment]
> Don't forget that this is still work in progress in nighlies and that the production version still has a stable boring tray as you describe. I don't have a problem with the nightly looking for itself a bit for some time... But yes in the end it needs to be stable, preferably with deactivable new ux disrupting features like tab grouping or deactivation

Don't forget that stable doesn't have non approved add on support.

If the stable has the current nightly add on support this issue wouldn't be more than a single comment of bug report, since people can just switch to stable while waiting for the problem to be fixed.

**Comment by WesleyAC** [comment]
> Don't forget that this is still work in progress in nighlies and that the production version still has a stable boring tray as you describe.

I think that part of the trouble here is that pre-fenix, Firefox Mobile supported all these things — the tab tray worked, you could reorder tabs, and install addons. Now, the only way to get all that is to run a more than a year old fennec APK. I did that for probably around 6 months before eventually switching to fenix (since the security tradeoff there seemed bad), but... it still sucks that my Firefox Mobile experience now is worse than it was two years ago, regardless of whether I'm using nightly, beta, or stable.

I'm sympathetic to "don't run nightly if you don't want stuff breaking", but that doesn't really account for how much of a downgrade fenix is in general. I understand that people at Mozilla are putting in a lot of work, and that there are good reasons to have switched from fennec to fenix, and that it'll take time for fenix to get back to where fennec was. It's just frustrating when there are things that are making the experience significantly worse, which seem like they'd be easy to offer workarounds for, but those workarounds are not offered.

**Comment by Ruin0x11** [comment]
Just leaving this here, in case the mobile team will see it.

https://blog.nori.moe/firefox-for-android-is-a-mess/

**Comment by klint** [comment]
There is no point anymore in ranting again and again. It's been 2 years now. You may have noticed in the meantime that Mozilla has other priorities than yours, whether you like it or not. It's their own decision and they are entitled to it. 2 years...

**Comment by sheikh-azharuddin** [comment]
Offtopic: speaking of the basic/common issues, there are few features which are not well developed or absent in fenix but present in other apps/browsers since a decade!

1. **Media notification**: the notification lacks basic controls and thumbnails..mozilla is not considering this a priority issue. Whereas samsung mobile browser has taken this to next level by adding advance video controls beyond system ones.

2. **Push notification**: the push notification does not work in all sites example reddit...the sites where it works does not serve any purpose like on clicking the notification it does not open the page which generated it or it takes to home screen..really basic feature missing in fenix and not in mozilla's priority list

3. **Form data fill**: this feature present in chrome since their launch itself but yet after years mozilla is not interested to add !
4. **Addres autofil**l: kind of form data fill . Recently fenix has added it similar to desktop but interestingly unlike chromium browsers there is no actual UI in the setting to manage addresses.

5. **3 dot menu**: mozilla could have used samsung or edge browser horizontal implementation make it friendly for large devices with bottom address bar but no, to copy chrome they added a long list of menu items which sometimes goes longer than screen and requires extra scroll to access but remember chrome does not has bottom address bar so it justifies but not for fenix!  If you still need to use 2 hands to access menu items it does not make sense to have bottom address bar!


I feel these are basic features which must be considered on priority rather than bad design changes or experimental features! I have raised few cases also but some fanboy(cad***) has closed it stating we already have open issue which were opened years/months ago with no update..and don't forget they have a deployed a stale bot to close cases which cannot be attended by mozilla.

So the mozilla is not based on user feedback but what mozilla internal teams actually wants or probably controlled by Google!

If some fanboy or admin wants to ban me for speaking truth please feel free, will give me another valid reason to switch to another browser!

**Comment by kj** [comment]
I'm sympathetic to the frustration around a lot of the design decisions Mozilla has made lately, but if you know your comment is off topic, then don't post it here. I'm subscribed to this issue because I'm interested in discussion/progress on this issue.

**Comment by csadilek** [comment]
@sheikh-azharuddin Naming calling and insulting other community members is not acceptable so I had to delete your last comment. Please keep it constructive and have a look at our community participation guidelines: https://www.mozilla.org/en-US/about/governance/policies/participation/

We care deeply about our users and all the feedback shared with us. As you can see from the discussions above, there are a lot of different perspectives to consider, even just among the people reporting here on GitHub. Keep in mind that only a very small subset of our users report issues here, and not all interests are necessarily represented.

**Comment by SpandexWizard** [comment]
Like many people have said, I too am sympathetic to the fact nightly is a test bed and that it is /meant/ to be something of a mess. But when you roll out new "features" like inactive tabs or the auto grouping mess, and then at the same time take away what is considered default behavior, you set the impression that this is how it's going to be going forward. And not only is this not ok, and not only is this why everyone gets so very VERY animated about this, but history has proven that interpretation to be correct. Very rarely do I see an issue brought up here that people make a big fuss about that, if it isn't immediately addressed and fixed, ever changes. Either it's a "it's broken" problem, and it gets fixed right away, or it's a "that's how we want it to work but we aren't saying that out loud" problem and it never gets fixed. Inactive tabs and grouping might be fine for some people. Making it the default way to use Firefox might even be fine for some people. But making it the /only/ way to use Firefox is NOT ok.  Firefox should be customizable. Firefox should work the way /I/ want it to. Otherwise why am I even using it? And right now firefox is not working the way any of us want it to, and it's very distressing to see that become the only way it's going to work, seemingly forever.  

Like many people have said, when a new "feature" comes around, ESPECIALLY if the feature changes core functionality, it needs to be designed from the ground up with an on off toggle. If it isn't built that way from the start it may never have the functionality ever. Imo that should be rule number 1 ofdesign phosopby

**Comment by notverymoe** [comment]
Been trying to work with it for a while now and find it creates a lot of usability issues at the moment, which is fine, this is nightly ofc. I think most/all probably already being mentioned, but I'll still list my thoughts below:

- Groups reorder themselves when closing tabs, and the rhyme/reason isn't immediately obvious.

- Links opened from tabs that were themselves opened from the root "search" tab open into the misc section.

- I've noticed some delay from changing the search terms, to the groups rearranging/renaming/being created which extends to tabs being opened from the changed search if I don't open the tab tray first before opening them

- There's no method to move a tab(s) into the misc group, or otherwise close a group. Probably will be solved by the rearrange tabs issue already mentioned in this thread.

With my personal usage of browsers the feature also doesn't fit my workflow at all, though I'm sure it fits other people's just fine. I tend to open one link at a time from a search, go deeper within that link and once I'm done with that branch I'll close it and return to the search - maybe keeping that page or a subpage open if I need to cross-reference, though usually not. The result of this is that the groups create a significant amount of wasted space and require a lot of scrolling from me if I'm jumping around on topics.

Because of that I'd like the ability to disable the feature, but some other solutions I could see is making the groups into blocks (either wrapping, groups denoted by highlight, or blocks, so two groups could be arranged next to each other - though that sounds messy) or allowing the group's to collapse/auto-collapse. I'm sure there are many other solutions too, and better ones than I can come up with 😅

--- Slightly offtopic

I do also want to echo what's been said here with the reasons people are using unstable builds and people getting scared/uncomfortable/panic-ed when a WIP feature lands with no option to disable it, because it tells them this might be the *only* way going forward. The amount of incivility coming from the community is a pretty inexcusable though - hope I'm not adding too it too much with this comment, you're all doing amazing work

**Comment by pocmo** [comment]
The setting is now available in Nightly: Settings -> Tabs -> [x] Search groups"

Please keep filing separate issues for feature requests regarding grouping. :)
