### ISSUE TITLE
FNX-5480 ⁃ [Meta] Basic Download

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#214]
### Why/User Benefit/User Problem
Allow users to download web content, supported web files

### What / Requirements
As a user, I want to be able to access downloadable files linked on web pages so I can view their content

### Acceptance Criteria (how do I know when I’m done?)
* Retrieve downloaded file
* Open downloaded file
* Delete downloaded file

**Comment by st3fan** [comment]
The Reference Browser (via Android Components) integrates with the Android download manager and should be functional enough.

**Comment by pocmo** [comment]
Fenix has a "Downloads" list under "Library" as well. We'll need to investigate whether we can source this from Android's Download Manager or whether this is something we need to keep track of ourselves.

**Comment by boek** [comment]
> * List deletes
@bbinto How long do we want to keep the deleted files around?

**Comment by bbinto** [comment]
@boek - I don't think we need a list of deleted files - not sure why I wrote this in the AC list.

**Comment by cpeterso** [comment]
Fenix downloads will need either:
* a __GV API to get the user cookies for the download URL__ ([GV bug 1476364](https://bugzilla.mozilla.org/show_bug.cgi?id=1476364)). If the website requires the user to be logged in to download a file, Fenix will need to hand the user cookies to the Android download manager.
* or a __GV API for streaming downloads__ ([GV bug 1522705](https://bugzilla.mozilla.org/show_bug.cgi?id=1522705)) if Fenix is going to manage downloads itself instead of handing them off to the Android download manager.

@pocmo and @snorp discussed downloads last week. IIUC, @snorp's preference was for Fenix to use GV for downloads instead of handing off to the Android download manager. We prefer to use Gecko's network stack and certificate store instead of the system's.

However, the second approach above would be more work for Fenix. You would need to write code to deal with the downloaded file management and things that the Android download manager already does for you. Fenix would also need to write a new `GeckoWebExecutor` service to keep an in-progress GV download alive if the Fenix app is backgrounded.

The GV team needs to know which approach Fenix plans so we know which GV API to deliver for you in M2.

**Comment by pocmo** [comment]
Fenix is currently relying on the `feature-downloads` component which does forward downloads to Android's Download Manager. We anticipated supporting other download managers but have implemented none. I totally agree that the long-term solution should be to use a Gecko-based download manager implementation. However as mentioned that's a larger project.

**Comment by cpeterso** [comment]
I spoke with @pocmo this morning. He says that Fenix 1.0 can integrate with the Android download manager (like the RB/AC does), but without user cookies. After 1.0, Fenix can use GV's new streaming download API ([GV bug 1522705](https://bugzil.la/1522705)) to create its own download manager.

**Comment by buttercookie42** [comment]
> We prefer to use Gecko's network stack and certificate store instead of the system's.
And for servers that are allowing only a limited number of download attempts (in the most extreme case only one), handing off the download to the DownloadManager might already count as a second download.

**Comment by pocmo** [comment]
> I totally agree that the long-term solution should be to use a Gecko-based download manager implementation. However as mentioned that's a larger project.

I filed this as an A-C issue here:
https://github.com/mozilla-mobile/android-components/issues/1968
