### ISSUE TITLE
Don't see location bar when on site with bottom banner

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#21480]
### Steps to reproduce

1. go to https://news.google.com/topstories?hl=de&gl=DE&ceid=DE:de 
2. Select an article from "Welt"

### Expected behaviour

Bottom bar disappears on scroll and re-appears when I scroll up

### Actual behaviour

The bottom bar disappears on scroll, a bottom banner shows up and the bar doesn't show up again when I scroll up. 
![Screenshot (Sep 23, 2021 4 32 28 PM)](https://user-images.githubusercontent.com/353960/134527761-03e0a6bb-334a-4a21-b9a0-c06d0af4d357.png)

### Device name

Pixel 3 XL

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18003)

**Comment by SoftVision-LorandJanos** [comment]
Hi @topotropic ! I can confirm this issue is reproducible with an extra detail: Sometimes the bar stayed on even while scrolling (See videos below).
And aside from the latest Release, it's reproducible on the latest Beta and Nightly as well.

Firefox versions tested:

- latest Nightly (94.0a1 - 2021-09-24T05:10:09.860159).
- latest Beta (93.0.0beta4)
- latest Release (92.1.1).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

https://user-images.githubusercontent.com/48829350/134644733-9e5fc235-9ab1-40d4-9b7a-c004e76186e5.mp4


https://user-images.githubusercontent.com/48829350/134644740-2bd94403-5f40-4019-91f6-baa7eaa3c5ee.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 100.0a1 (2022-03-23).

Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 109.0a1 (2022-12-08) build.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813862

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
