### ISSUE TITLE
[Bug] URL bar disappears when content is not scrollable

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2154]
The URL bar disappears even when the content is not scrollable, this is really noticeable in websites like Google Maps

See video:

* Fenix: https://i.imgur.com/b8RPH6f.mp4
* Fennec: https://i.imgur.com/Tm60tqK.mp4

## Steps to reproduce
* Navigate to maps.google.com
* Move the map around

### Expected behavior
* The URL bar stays put

### Actual behavior
* The URL bar disappears if moving the map down

### Device information
* Android device: Samsung S10e
* Fenix version: Latest from playstore

Works in: Fennec, Chrome

**Comment by sblatz** [comment]
Blocked on https://github.com/mozilla-mobile/fenix/issues/552

**Comment by vesta0** [comment]
Blocked on #552

**Comment by vesta0** [comment]
Needs GV fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1507569

**Comment by snorp** [comment]
There's likely going to be a long tail of issues related to the dynamic toolbar. Can we consider disabling that for MVP, @vesta0?

**Comment by sblatz** [comment]
@snorp I feel like something got lost in translation here. This bugzilla was flagged as a P1 4 months ago, why are we not trying to fix it anymore? Is there an update that's not explained in the bugzilla?

We've put a lot of time into the dynamic behavior of the toolbar and I don't think fixing it for MVP is the right solution.

**Comment by vesta0** [comment]
@snorp the main [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1516048) was fixed and landed in RB and takes care of the all the reported cases (QA will verify) except for non-scrollable pages such as google maps which we hope [this ](https://bugzilla.mozilla.org/show_bug.cgi?id=1507569)will fix. If this fix doesn't land (or doesn't work) before MVP then we will consider having a fixed toolbar, otherwise we will consider it in a release ready shape and we will ship. This is an important feature and we won't be able to learn and iterate if we don't roll it out.

**Comment by cpeterso** [comment]
The GV bug was fixed in GV 68 five months ago, so I will remove the `needs:gv` label. I'll leave the `waiting` label because the fix can't be verified until Fenix re-enables its dynamic nav bar.

https://bugzilla.mozilla.org/show_bug.cgi?id=1516048#c21

**Comment by cpeterso** [comment]
This works correctly for me in R-B. We're still waiting for Fenix to re-enable the dynamic nav bar.

However, panning the map triggers R-B's pull-to-refresh. I filed a new R-B bug: https://github.com/mozilla-mobile/reference-browser/issues/943

**Comment by Mugurell** [comment]
This should be resolved by now.
