### ISSUE TITLE
Perceived performance of navigating from clicked thumbnail to the page is janky.

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#21549]
## Steps to reproduce
- Have the tab tray opened with multiple tabs 
- Click on a thumbnail

### Expected behavior
The animation of dismissing the dialog into the page is sequential and doesn't look janky

### Actual behavior
Our dialog dismisses while the webpage that is in the background (the previous one that was loaded) is shown. The previous webpage fades away as the dialog fades making it look like texts overlaps.

For example , looking at chrome, the thumbnail "grows" into the next page (I think the term is "hero animation"? I could be wrong). I don't think loading the page is faster but it just feels like it is since it is smoother.

### Device information

* Android device: Moto G5+
* Fenix version: Nightly 202

This video shows the behavior described above. When navigating from example.com in my tabs tray to CNN.com, we still see example.com once the tab tray is dismissed.
https://user-images.githubusercontent.com/16614353/136270867-c98ecef0-a890-4fcd-b010-bbe16ee5fd9b.mp4

1-09-22

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18054)

**Comment by jonalmeida** [comment]
Looking at this perceived perf issue, I think the comparison against Chrome isn't valid - our tabs tray is trying to show an active page in the background and chrome might have this bug if their tabs tray wasn't a full page UI to cover those few seconds it takes to re-render the page. The time it takes to paint the first layout of a new tab have increased since when this was first filed through various gfx/GV/AC changes but we can never fully remove it without a change in UX.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807339

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
