### ISSUE TITLE
FNX3-16102 ⁃ [Bug] regression: closing private tab switches from private to regular browsing mode

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2156]
### Steps to reproduce
1. switch to private mode
1. open a tab
1. go to homescreen
1. close the tab

### Expected behavior
You are still on the private mode home screen.

### Actual behavior
You are on the regular mode home screen.

It's a regression from #2099. \cc @ekager since you implemented #2099.

### Device information
* Android device: HTC U11 / Android 8.0
* Last good build: 29238d6e5f4be0c73ab5155c8ebe2fc6ad0128bf
* First bad build: b11a7554c2060270e723047521b1ad8d8bc759d1

**Comment by LittleAngelwings** [comment]
Yes, this issue struck me since, I mean, the two or three last nightlies from Taskcluster. The private mode is the only way to download nightlies from the download section at Taskcluster without wipe the Fenix (cache) data about Android Apps for me. See also this issue: https://github.com/mozilla-mobile/fenix/issues/1813
Thx for report them, so I haven't to do this :)
