### ISSUE TITLE
FNX-5490 ⁃ [Bug] The bottom bookmarks overflow menu is too tiny

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2162]
## Steps to reproduce
1. Make sure to have a long list of bookmarks, to reach the bottom of the screen.
1. Tap the menu button on one of the bottom items.
    1. Expected behavior
All menu items can be seen, the menu adapts to the screen position.
    1. Actual behavior
The menu is too small, can hardly see one item.
![Screenshot](https://user-images.githubusercontent.com/4037709/56964579-1c776880-6b64-11e9-9d86-04d963b9f505.png)UNITO-UNDERSCORE!20190430-162034!

### Device information
* Android device: Pixel, Galaxy Tab 3
* Fenix version: 4/30

**Comment by Rushi98** [comment]
IMO, this can be resolved by 3 ways
1. `determineVerticalOffset` [method](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt#L91) seems to be the root of problem. So it can be improved.
2. make the orientation of menu `UP` instead of current `DOWN`
3. choose the orientation depending on position of the item on screen. `components.browser.menu` does have a `determineMenuOrientation` [method](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/menu/src/main/java/mozilla/components/browser/menu/BrowserMenu.kt#L71). But it doesn't make decision based on position on screen OR for non CoordinatorLayout parents. So that method can be improved to consider position (at least for non-CoordinatorLayout parents).

**Comment by sblatz** [comment]
Blocked on [this a-c work](https://github.com/mozilla-mobile/android-components/issues/2916)

**Comment by Amejia481** [comment]
@sblatz Can using `orientation = BrowserMenu.Orientation.UP` be an alternative? I achieved this using it.

![Screenshot_20190531-170828](https://user-images.githubusercontent.com/773158/58734954-f3e2c880-83c6-11e9-9157-2d552a3540fb.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1923 (#11561806), with Motorola Nexus 6 (Android 7.1.1).
