### ISSUE TITLE
FNX-5494 ⁃ [Meta] Localization

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#217]
### Why/User Benefit/User Problem
* Allow users to use the app in their native/preferred language

### What / Requirements
* Hook up L10N to our L10N system

### Acceptance Criteria (how do I know when I’m done?)
* Strings are automatically sent for localization and updated
* App shows strings in the selected system language

Assuming we are using the existing L10N system.

### MUST
en-US
es-US
de-DE
en-GB
fr-FR
es-ES

### NOT must
fa-IR (RTL)
ru-RU
zh-CN
pt-BR

### NOT for MVP
RTL

**Comment by Delphine** [comment]
@bbinto: we're actually not using the existing l10n system, as discussed currently in: https://docs.google.com/document/d/19ntAPd5fdm7jaUhf-XHe4qFy3L0rn4Bb5WAR2jiAYdQ/edit#heading=h.wc40dmqfulog

Next step as I understand it per comments in this doc are for Susheel to file corresponding issues in order for us - and dependent teams - to put everything in place so we can kick-off actual translation - and so that we can properly define milestones for the upcoming needed work.
(also, FYI @Pike )

**Comment by vesta0** [comment]
@Delphine @mheubusch I recommend adding these steps as separate issues to each meta that needs localization instead of tracking them as generic items in this meta. Does that work better for you? Let me know and I can do that.

**Comment by mheubusch** [comment]
@vesta0 all strings for Fenix are in a single file that is used for all features and is the only thing that needs localization. it's called strings.xml  the other strings come from android components.  When we have changes to copy I have been updating the file directly here and in the relevant a-c files and requesting the developer update them. from there the process is automated

**Comment by vesta0** [comment]
@bifleming and @sarentz can we close this meta and the issues listed under it?
