### ISSUE TITLE
[Bug]: The application crashes when being idle on certain website

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#21767]
### Steps to reproduce

1. Go to https://get.webgl.org.
2. Leave the application idle for ~9 minutes.
3. Observe the crash.

### Expected behaviour

The application should remain stable at all times.

### Actual behaviour

After being idle for ~9 minutes, the application crashes.

### Device name

Huawei P9 Lite

### Android version

Android 8

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta.1 (Build 2015838099)

### Device logs

3ffc1c59-1d86-4288-8ef6-c3802e3bc335
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-b882089a-df0a-41d6-a5ac-11a7f0211007
----
<native crash>

a43d74ba-5bf3-470e-9acf-59d118c8917b
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-b96299ae-d3a8-437a-868d-5ee450211007
----
<native crash>

### Additional information

The issue was reproduced 2/2 tries. 

https://user-images.githubusercontent.com/89388888/136383476-a7ca16e3-f2a1-495d-a31e-cfaccdbb132b.mp4

**Comment by badboy** [comment]
Thanks, I'm able to reproduce the same way on a Samsung Galaxy Note 8 now. That will help me looking into this.

**Comment by badboy** [comment]
@delia-pop Hey, I found the underlying bug and am about to deploy that so we can get it fixed in Fenix too.
I'm wondering now how you identified this bug. I would not have come up with just leaving the browser running unattended.
Is leaving the browser opened & untouched on a single website part of regular testing? Where there other clues?
I'm asking in order to be able to look into similar crashes quicker in the future myself.

**Comment by badboy** [comment]
This was fixed a while ago.
