### ISSUE TITLE
[Meta] Save Page Offline

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#219]
### Why/User Benefit/User Problem
As a user, I want to be able to retrieve select websites when offline, so I can revisit the content without requiring a network connection. 

[Feature Brief](https://docs.google.com/document/d/1_lbVYHouBVqYBrt41MDA8L1PqUNJQNNyD2nRAu8o9oc/edit#)

### Acceptance Criteria (how do I know when I’m done?)
- I can choose to save a website to access later when I am offline (TBD: Need to determine use cases. e.g. how much of the website and which elements should be saved)
- I can retrieve my saved pages from within the browser
- I can delete my saved offline pages

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11230)

**Comment by cpeterso** [comment]
GV API to tell Gecko to enter offline browsing mode, though it doesn't save local copies of web pages:

https://bugzilla.mozilla.org/show_bug.cgi?id=1533271

**Comment by bbinto** [comment]
@mheubusch - I think we should move this out of MVP, thoughts?

**Comment by cpeterso** [comment]
@vesta0 - The GV team needs more details on how this Save Page Offline feature should work. Is this feature about taking a full page screenshot, saving a page's HTML and assets to a local file, or enabling Gecko's existing offline browsing mode (where Gecko will load files from the browser cache instead of from the network)?

**Comment by vesta0** [comment]
@cpeterso I've updated the description with more details. We can discuss further during the planning week.

**Comment by liuche** [comment]
We decided in Q4 planning that we would file a spike for this, I think that is @vesta0 or @bifleming?

**Comment by sblatz** [comment]
@liuche did you file one for this? :)

**Comment by Oymate** [comment]
Update?

**Comment by chphmh** [comment]
I want to express my support for this feature request, because I have used this regularly in the Fennec version of Firefox for Android. After I updated to Fenix, I was sad to see that my offline reading list from the old app version was converted to regular bookmarks.

Previously, I would switch to reading mode for longer articles and if I did not have time to read them right away, I would add a bookmark, which from the reading mode gave me an offline saved page. 
I also used this feature when I was on vacation abroad when I did not have a roaming data plan: so I would save a travel website or travel guide article offline while in the hotel wifi, and later could acess the offline version while outside.

I know there are some alternatives for this, but they do have disadvantages:

- "Save as pdf" is good when images are needed in the offline copy, but in many cases it is a waste of storage space as text is enough.
- Apps like Pocket are good for this, but to have an offline copy, you need to share the website from Firefox to Pocket, then open Pocket and let it load the website there again. (For some websites Firefox was even able to show reading mode & save offline when Pocket would only offer the web view, which it does not save offline as far as I know.)

**Comment by FunkyBrewster** [comment]
I'm missing the option to simply save the web page as html to a local file. Removing that, along with Save Page as PDF is a major feature loss. I open FF one day to find tons of features removed, and it makes no sense that you want to "assess how widely this feature is used before designing it." It was already designed, implemented, and functioning perfectly! FF is still better than Chromium in many ways but this last update is so incomplete it's actually a toss up over which is less worse right now.

**Comment by TheRealOsas** [comment]
I love this feature and I can't wait for it to land

**Comment by 360cid** [comment]
I would also like to express my support for this feature as like @chphmh, I am a regular user of offline content. In my case, I am frequently out in the wilderness with no phone service, actively using my phone as a navigation device. I often used the print to PDF function in Fennec to save offline information on backcountry hiking and climbing routes -- things like trip reports, route descriptions, and forum threads, which I use as a reference alongside GPS while navigating off-trail. I would frequently save to PDF directly from reader mode in order to focus on the text and image content I cared about.

I realize my use case is probably more niche than most, but the Fenix update has hampered this workflow and introduced additional friction by forcing me to go back to Chrome whenever I need to save content offline. Additionally, Chrome's lack of a streamlined reader mode or thorough ad blocking support has in some cases made the usability of the offline content worse, so I definitely miss having a feature like this readily available in Firefox.

**Comment by andreicristianpetcu** [comment]
@360cid if you are interested in an ugly workaround you can take full page screenshot. like so https://mobile.twitter.com/FirefoxPreview/status/1313361259656556545

Here is how to install https://mobile.twitter.com/FirefoxPreview/status/1311796843848835072

What extension were you using to save as pdf?

**Comment by 360cid** [comment]
@andreicristianpetcu I misspoke -- I was printing to PDF through the browser, not saving via an extension.

**Comment by B0pol** [comment]
Another "workaround":
You can search for a link to that page in another page, long press on the link, "download link". It will download the page as a .htm file 

But
- you need to find a link to this page
- it seems not to download some CSS and JavaScript.
- you can't open in Firefox (Android) but you can open Chrome (Android, Desktop) and Firefox desktop

**Comment by MicroBeast** [comment]
You could open local file in Firefox. Someone mentioned about using protocol ``file://`` somewhere around here (deep in conversations).

So, like ``file:///storage/emulated/0/local.ext``. Notice that triple ``/`` after ``:``.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1346292

**Comment by headbank** [comment]
Another one for the workaround pile, mentioned in #10217 : Nightly with [SingleFile addon](https://addons.mozilla.org/en-GB/firefox/addon/single-file/).

Disclaimer: I have not tested this, YMMV, don't blame me etc.

**Comment by csadilek** [comment]
Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1809311.

**Comment by headbank** [comment]
> Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1809311.

That doesn't really seem like the same feature at all to me TBH. That bug seems to describe an across-the-board behaviour whereas this is an on-demand action.

**Comment by vehosah** [comment]
> Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1809311.

Yeah this is described as a request for closing the browser and open it again and have all the tabs open?

**Comment by vehosah** [comment]
Or simply just use fennec

**Comment by vehosah** [comment]
> Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1809311.

Lol that's not the same thing at all

**Comment by SavSanta** [comment]
> Or simply just use fennec

Well actually it would have to be OG Fennec (aka Firefox 68.x). Some 'clever' worms package Fenix under the Fennec name unfortunately. So when you download it you still get the Alpha state missing a lot of features Fenix version. That being said I had OG Fennec not be able to load a couple of sites last I used it. So unfortunately. You'll be stuck with Alpha State Featureless Fenix at that rate.

Best Replacement is actually Microsoft Edge funnily enough and (unfortunate for those trying to use non-chromiums).

**Comment by vehosah** [comment]
> 

I'm using fennec f-droid, I have save pdf, i have html offline, i have custom add-ons, i have about config, i don't have anything alphaish

**Comment by vehosah** [comment]
> Best Replacement is actually Microsoft Edge funnily enough and (unfortunate for those trying to use non-chromiums).
Funnily enough it's bullshit enough

**Comment by SavSanta** [comment]
> > 
> 
> I'm using fennec f-droid, I have save pdf, i have html offline, i have custom add-ons, i have about config, i don't have anything alphaish

Theyre spelled similarly and pronounced similarly but if you will read again you should understand.

>Best Replacement is actually Microsoft Edge funnily enough and (unfortunate for those trying to use non-chromiums).
Edge is damn good. No BS. Microsoft did well. Once your Fennec gets too old to use and youre forced to use Fenix. You can try it and enjoy! Cheers

**Comment by vehosah** [comment]
> > > 
> > 
> > 
> > I'm using fennec f-droid, I have save pdf, i have html offline, i have custom add-ons, i have about config, i don't have anything alphaish
> 
> Theyre spelled similarly and pronounced similarly but if you will read again you should understand.
> 
> > Best Replacement is actually Microsoft Edge funnily enough and (unfortunate for those trying to use non-chromiums).
> 
> Edge is damn good. No BS. Microsoft did well. Once your Fennec gets too old to use and youre forced to use Fenix. You can try Edge and enjoy! Cheers

Don't worry I already tried it and it got instantly deleted, cheers

**Comment by SavSanta** [comment]
> Don't worry I already tried it and it got instantly deleted, cheers

No not then. Read again that once Fennec breaks completely and your add-ons dont work and if Fenix is still featureless and add-onless. That's when you should try it. Cheers!

**Comment by vehosah** [comment]
> > Don't worry I already tried it and it got instantly deleted, cheers
> 
> No not then. Read again that once Fennec breaks completely and your add-ons dont work and if Fenix is still featureless and add-onless. That's when you should try it. Cheers!

Why should I try this add-on less, data thief browser, cheers

**Comment by SavSanta** [comment]
> Why should I try this add-on less, data thief browser, cheers

Read above up again for the implications. Cheers

**Comment by vehosah** [comment]
> > Why should I try this add-on less, data thief browser, cheers
> 
> Read above up again for the implications. Cheers

I read the implications, and I'm not missing anything,neither my extensions, nor my save to pdf, nor my open to html, nor my about config cheers

**Comment by SavSanta** [comment]
>I read the implications, and I'm not missing anything,neither my extensions, nor my save to pdf, nor my open to html, nor my about config cheers

Nice all set for now. Cheers!

**Comment by Dunexus** [comment]
Please remember that every message posted sends a notification to several people. Try to keep it clean and avoid off topic discussions.

**Comment by SavSanta** [comment]
Sorry @Dunexus!
