### ISSUE TITLE
FNX-84 ⁃ Scroll to bottom/top of the page buttons

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#2190]
### Why/User Benefit/User Problem
Scroll to bottom/top of the page buttons

Useful when scrolling a long page and user wants to go to the bottom or return back to the top quickly

### What/Requirements
Easy to use scroll to bottom/top of the page buttons

### Acceptance Criteria (how do I know when I’m done?)
Easy to use scroll to bottom/top of the page buttons

**Comment by cadeyrn** [comment]
I am bit sceptical because a lot of websites have some kind fixed content which could be inaccessible if these buttons would be added to the content. And the toolbar is already very limited on a smartphone, adding two buttons takes a lot of that space.

Is there any browser which has a similar feature to see how it works in reality?

**Comment by sebast889** [comment]
There are other browsers with scroll back to top button on the page. Samsung browser is one.

I think it could still be done without wasting too much space with a single button with both top and bottom arrows.

**Comment by vesta0** [comment]
Closing for now and will re-open once we have validated this use case through user testing.
