### ISSUE TITLE
[Bug]: Inactive tabs section turns "incognito" dark after returning from private tab

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#22012]
### Steps to reproduce

1. Have the "Inactive section" enabled (tabs should be inactive for at least 14 days).
2. Open a private page.
3. Go to Tabs tray>Normal tabs and observe the "Inactive tabs" section.

### Expected behaviour

The "Inactive tabs" section remains white in light theme and dark grey in dark theme.

### Actual behaviour

The "Inactive tabs" section turns "incognito" dark.

### Device name

Xiaomi Mi11 Lite

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly (2021-10-19T07:38:48.338535)

### Additional information

After accessing one of the normal tabs, and returning to the "Inactive tabs" list, it is displayed as expected.

https://user-images.githubusercontent.com/48829350/157048724-7f4ed049-5f78-4f68-9e52-d7fa491f74af.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18370)

**Comment by Mugurell** [comment]
The issue here is that once entering private mode that is set across the app so all color resources and even app features will function as needed for private mode.
In this case we are seeing the colors used for the private theme which are applied all throughout the app, eg: for dialogs also.

https://user-images.githubusercontent.com/11428869/152823448-644b6a2e-1ed4-49eb-a8eb-494a6f6a3f12.mov

Showing the otherwise expected for normal mode colors would mean overriding the normal app functionality in code and add another layer to compute and set light mode/dark mode. This will mean high complexity and high maintenance costs in Fenix and AC.

As such I think our best approach would be to wait for the compose refactoring that would make overriding colors in smaller scopes (for smaller features / composables while keeping the defaults in app) straightforward and easy to do.

Asking for a second opinion from @Amejia481 who is working on the compose refactoring.

**Comment by Amejia481** [comment]
> The issue here is that once entering private mode that is set across the app so all color resources and even app features will function as needed for private mode. In this case we are seeing the colors used for the private theme which are applied all throughout the app, eg: for dialogs also.
> privateThemeColors.mov
> 
> Showing the otherwise expected for normal mode colors would mean overriding the normal app functionality in code and add another layer to compute and set light mode/dark mode. This will mean high complexity and high maintenance costs in Fenix and AC.
> 
> As such I think our best approach would be to wait for the compose refactoring that would make overriding colors in smaller scopes (for smaller features / composables while keeping the defaults in app) straightforward and easy to do.
> 
> Asking for a second opinion from @Amejia481 who is working on the compose refactoring.

Agree, after we migrated to compose we will have more control over themes per components.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest builds:
- latest Nightly 106.0a1 (2022-09-13).
- latest Beta (105.0b6).
- latest RC (105.1.0).
Device used: Oppo Find X5 (Android 12).
Closing the issue as fixed.
