### ISSUE TITLE
[Bug]: on New Tab, Page scroll requires extra tap

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#22019]
### Steps to reproduce

Open a new tab
Try scrolling through the home / new tab page, to e.g. load a collection

### Expected behaviour

User can scroll through the viewport without issue, such as when tapping the address bar on an existing tab

### Actual behaviour

User needs to perform an extra tap to bring focus onto the viewport, only then user can scroll. This is unlike the behavior when simply editing the address bar from an exisiting tab. In the latter case, user can scroll with one simple motion.

### Device name

Samsung Galaxy OneUI 3.1

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 2015840635

**Comment by xlog-null** [comment]
Before I make any changes - would it not be better UX if the keyboard was hidden as soon as the user starts scrolling, regardless if opening a new tab or coming from an existing one? I imagine if the user decides to scroll, it would make sense if he sees everything on the screen.

There is still a bug to be fixed here - the extra click required and I will get on that but I'm just wondering if the keyboard staying on screen is really a bug or an intentional feature.

**Comment by marcel263** [comment]
the bug seems fixed thank any responsible dev
