### ISSUE TITLE
Address bar: add "Copy Unescaped URL" feature

### ISSUE THREAD

**Issue by kirisakow** [mozilla-mobile/fenix#22042]
### Who will benefit from it?

Those like myself who deal with URLs having non-ANSI characters and need to copy those. 

Examples:

* https://uk.wikipedia.org/wiki/%D0%92%D1%96%D0%B4%D1%81%D0%BE%D1%82%D0%BA%D0%BE%D0%B2%D0%B5_%D0%BA%D0%BE%D0%B4%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F
* https://www.france24.com/fr/%C3%A9co-tech/20211005-facebook-la-lanceuse-d-alerte-frances-haugen-exhorte-le-congr%C3%A8s-%C3%A0-mieux-r%C3%A9guler-le-r%C3%A9seau-social

are prettier in their unescaped shape:

* https://uk.wikipedia.org/wiki/Відсоткове_кодування
* https://www.france24.com/fr/éco-tech/20211005-facebook-la-lanceuse-d-alerte-frances-haugen-exhorte-le-congrès-à-mieux-réguler-le-réseau-social

For the time being I have to unescape those manually either in console or via a web app like https://meyerweb.com/eric/tools/dencoder/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18392)

**Comment by kirisakow** [comment]
Forgive me if I was not clear. I was not talking about pasting — I meant _copying_.

I meant adding a, say, "Copy as unescaped" long-tap command allowing for returning the URL as an unescaped string, along with the existing command "Copy" (as is).

It might have seemed complex but it really is not when you do it [in Python](https://stackoverflow.com/a/8136831/4883320):

```python
>>> import urllib.parse
>>> urllib.parse.unquote('https://uk.wikipedia.org/wiki/%D0%92%D1%96%D0%B4%D1%81%D0%BE%D1%82%D0%BA%D0%BE%D0%B2%D0%B5_%D0%BA%D0%BE%D0%B4%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F')

'https://uk.wikipedia.org/wiki/Відсоткове_кодування'

>>> urllib.parse.unquote('https://www.france24.com/fr/%C3%A9co-tech/20211005-facebook-la-lanceuse-d-alerte-frances-haugen-exhorte-le-congr%C3%A8s-%C3%A0-mieux-r%C3%A9guler-le-r%C3%A9seau-social')

'https://www.france24.com/fr/éco-tech/20211005-facebook-la-lanceuse-d-alerte-frances-haugen-exhorte-le-congrès-à-mieux-réguler-le-réseau-social'
```

**Comment by kirisakow** [comment]
@amedyne Hey could you please remove the `bug` label? This issue is about a feature request, not a bug. Thanks

**Comment by jackyzy823** [comment]
Well if fenix support about:config ( not only in beta/nightly) and fenix about:config support "browser.urlbar.decodeURLsOnCopy" (just like desktop) this could be resolved easily.

However ...

**Comment by jackyzy823** [comment]
Since **someone** do not like my comment.

WELL TALK IS CHEAP. SO HERE'S THE CODE: [https://github.com/jackyzy823/fenix/tree/url-copy-unescape](https://github.com/jackyzy823/fenix/commit/145d8585affd046160aeeed5e7e1ac810168966a)


Some **nonsense** comments which **someone** may not like:

It would be better if it respect to about:config "browser.urlbar.decodeURLsOnCopy" . however `geckoview` do not expose APIs to get non-exposed about:config's settings (only allow some , like getEnterpriseRootsEnabled  -> security.enterprise_roots.enabled :  see https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.html) . 

The best solution is fenix (it self) related settings (like UI settings etc) go through andorid's pref. geckoview related settings go through geckoview's  pref.js (about:config).  and you can make some button/menu to make some geckoview's  common-use settings  to be set easily.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814153

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kirisakow** [comment]
> Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814153
> 
> Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

Wow, so that's a bug after all 😟
