### ISSUE TITLE
`SuggestionFetcher.fetch` is called on empty text when url bar is pressed

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22217]
## Steps to reproduce
- From the homescreen...
- Click url bar

### Expected behavior
`SuggestionFetcher.fetch` is not called, or short-circuits, because the url string is empty

### Actual behavior
After UI inflation, the search providers execute on presumably an empty string even though the search dialog is not shown by this point. I noticed this behavior from this profile: https://share.firefox.dev/2XYosdg This then results in an extra unseen measure/layout pass (clear the filter on the Marker Chart to see this).

This could affect users by:
- Delaying their interactions when typing real search results (e.g. because the main thread is blocked)
- Using unnecessary power

### Device information

* Android device: Moto G5
* Fenix version: up/main: 71d151ef18c703acde3c9104766eac368ab9d48a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18505)

**Comment by mcomella** [comment]
Triage: @Mugurell Do you know if this has been fixed?

**Comment by Mugurell** [comment]
> Triage: @Mugurell Do you know if this has been fixed?

Don't think so.
The goal here - https://github.com/mozilla-mobile/android-components/pull/12000/commits/806f97413755ad7390a3f4165e87688dae2b8c05 was to avoid a race (speculatively but seems that there is indeed an improvement) in updating what gets displayed. But the fetcher should function the same as before.
Probably a bigger refactoring is needed since the fetcher is instantiated and used [inside a Composable](https://github.com/Mugurell/android-components/blob/1d0457aad3a11a21c6bf6cd751f89a3f9af551c1/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt#L92-L97) which probably has to be measured even if it won't actually be drawn.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807343

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
