### ISSUE TITLE
FNX-5529 ⁃ [Bug] Deleting 2 bookmarks consecutively, the first will show for a second

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2226]
## Steps to reproduce
1. Create 2 bookmarks/ folders.
1. Delete one item.
1. Right after, delete the 2nd item.
    1. Expected behavior
Items deleted disappear immediately.
    1. Actual behavior
While deleting the 2nd item, the first will show up for a second, until the snackbar disappears.
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: master 5/2 build.

**Comment by isabelrios** [comment]
This is still repro on 5/23 build. And having more than two bookmarks (which may be the case after syncing a FxA) this issue is more noticeable and confusing. Please see video:
https://drive.google.com/open?id=1O4EmPXhF2IqzG7OQoGawGlKvxzzLv3In

@sv-ohorvath could you please confirm is that the same or if I should open a new one. Also please see how the delete banner shows incorrect name when deleting each bookmark (starting from the first one). Easier to see at the end of the video...Thanks!

**Comment by sv-ohorvath** [comment]
Yes, that's the same issue. 
For the bookmark titles in the snack bar, I talked with Isabel and she will create a new ticket.

**Comment by softvision-miralobontiu** [comment]
Reproducible when deleting bookmarks folders.
Tested on 1.0.0-rc.2 build (#11700147), with Google Pixel (Android Q).

**Comment by sblatz** [comment]
I believe @ekager fixed this
