### ISSUE TITLE
[Bug]: The Homepage submenu is not translated in Thai

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#22358]
### Steps to reproduce

1. Launch Fenix and set the language to Thai;
2. Navigate to the Homepage submenu.

### Expected behaviour

The Homepage submenu should be translated to Thai.

### Actual behaviour

The Homepage submenu is displayed in English.

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-beta.1

### Additional information

![Thai](https://user-images.githubusercontent.com/50983519/140720572-66269fff-0739-4a15-ba94-58d83565cda1.JPEG)

**Comment by Delphine** [comment]
seems like this might have missed a latest import on beta branch date.
Would be good to check on next testing cycle, it should get in. Thanks!

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the:
- latest Nightly 102.0a1 (2022-05-10).
- latest Beta (101.0.0-beta3).
- latest Release (RC 100.1.2).

Device used: Google Pixel 4 (Android 12).

![Screenshot_20220510-134541](https://user-images.githubusercontent.com/48829350/167611671-fe93a660-001a-4dc2-84ef-8901f8d6619f.png)

Closing the ticket as fixed.
