### ISSUE TITLE
[Bug][a11y]: Talkback reads "Button" twice for the "Show all" button on homescreen

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#22415]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on.
2. Have some items on the "Jump back in", "Recent bookmarks" and "Recent searches" sections.
3. Go to homescreen and tap on the available "Show all" buttons.

### Expected behaviour

The "button" is read once.

### Actual behaviour

The "button" is read twice.

https://user-images.githubusercontent.com/48829350/141304272-47445870-f3bc-4dd2-b240-5cfaef76ff84.mp4

### Device name

Xiaomi Mi11 Lite

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

95.0.0 beta2

**Comment by mcarare** [comment]
Note for QA: After https://github.com/mozilla-mobile/fenix/pull/22650/commits/a71622acaa9b71ef688aa4d65391d73855e9f5d9 the button announcment will not be read.

However, it is considered bad practice to add the state or type in a content description for an element. That is because the role announcement for elements is subject to change and it will provide a bad experience across the apps if we hardcode that role. 

Historically speaking, the button type announcement has been deprecated but kept for legacy support. The relevant announcement for a button or any other clickable element is "double tap to... ". This is the only announcement that is required for a clickable element and we should check for that after https://github.com/mozilla-mobile/fenix/pull/22938 lands.
