### ISSUE TITLE
[Bug]: inconsistent behaviour of hamburger menu

### ISSUE THREAD

**Issue by basings** [mozilla-mobile/fenix#22446]
### Steps to reproduce

1. Have home page open
2. Open hamburger menu

=== 

1. Have tab open
2. Open hamburger menu

### Expected behaviour

Both should behave consistently.

### Actual behaviour

- Hamburger menu on home page opens properly
- hamburger menu on tab opens only partly

### Device name

all devices

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

94

**Comment by Mugurell** [comment]
By design the menus have a different behavior and different options: The menu opened from a tab has more options specific to a tab - like navigation, adding as bookmark, etc while the menu from home is simpler, with more general options.

**Comment by basings** [comment]
13 vs 11 items. I don't understand why the menu should not open to the full screen height if there are 13 items vs if there are 11 items. And if there are 13 items (open tab), I only have 8 items left to choose before I need to make another user input.

**Comment by basings** [comment]
@Mugurell could you please reopen this issue? This doesn't seem to be resolved

**Comment by Mugurell** [comment]
@basings The reported issue - different menu options in home vs in browser and different menu behavior is the currently intended functionality.
The menus are intended to offer the most useful options depending on the app feature - home vs browser.
The browser menu having more options may be as tall as the screen and make it hard to reach the furthest options so that menu starts as collapsed, first offering the most used options, easy to reach then allowing the menu to be expanded for more.
