### ISSUE TITLE
Cannot prevent webpage from jumping into third party apps with NO fallback url 

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#22453]
### Steps to reproduce

1. Open fenix, with the default false value of "open links in apps" in setting.
2. Visit the webpages which try to call third party apps with no fallback urls, e.g. [m.jd.com](https://m.jd.com)
3. JD app will be opened if installed.

### Expected behaviour

When the setting of "open links in apps" is set to false, the call of third party app should be stopped.

### Actual behaviour

JD app will still be opened even though the setting of "open links in apps" is set to false.

### Device name

Huawei P50

### Android version

Harmony OS 2

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

I think this is related to [this part of AppLinksInterceptor.kt](https://github.com/mozilla-mobile/android-components/blob/6ba529f9538b8ea9ffba1846821a76cc80c3de17/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt#L121)
The webpage send an intent with no fallback url will not be stopped and still get to start the intent.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18641)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue and can reproduce it on the latest Nightly 2021-11-17, however it only happens the first time I access the page after a fresh install, the second time the page is accessed the application does not open.

### Device used:
- Oppo Find X3 (Android 11)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 102.0a1 (2022-05-19).
Device used: Google Pixel 4 (Android 12).

**Comment by hehe12301** [comment]
This issue is still reproducible with the latest Nightly 108.0a1 on Android 11. You can use "[test intent](http://mcomella.xyz/test/uri.html)" for further research.

Related Issues: #23102 #15202 #13090 [Bugzilla-1793208](https://bugzilla.mozilla.org/show_bug.cgi?id=1793208)

So, would there be any fix? Or I have to continue to use the old 68.0 version which doesn't has this bug... It's really disturbing.

Now, the related code was moved to [this part](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt#L125).

It seems that a quick fix would help, such as adding "return null" between line 125 and line 126. But I'm not sure.

**Comment by rocketsroger** [comment]
@rxumoz This behaviour was implemented on purpose.  If there is no fallback URL, we are expected to open the app if available.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809268

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
