### ISSUE TITLE
null as title / subject when sharing Youtube videos

### ISSUE THREAD

**Issue by celrm** [mozilla-mobile/fenix#22477]
This happened in my Firefox for Android, both Daylight and Nightly, when I tried to share a Youtube video. I reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1741168 and was told to report here.

### Steps to reproduce:

Open a Youtube video
Click on share button
Click on some apps to share the video (email, telegram, notes)

### Actual results:

As an email, the subject is null and not the video's title.
As a Google Keep note, it's the note's title.
As a telegram message, null is sent above the video.

### Expected results:

I believe the video's title should appear, instead of "null".

**Comment by mariansima** [comment]
I managed to reproduce this issue on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-18
95.0.0-beta.4 2021-11-15
RC 94.1.2 2021-11-08

**Comment by VitalyVPinchuk** [comment]
Hey @celrm @sflorean !
Google Chrome does the same but leaves empty space instead of 'null' in the title field.
If you click share menu item in the Fenix menu you'll get the expected result (managed by Fenix itself). But if you click share link under the video then it won't work (managed by Gecko engine).

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 98.0a1 (2022-01-20).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Google Pixel 4 (Android 12).

Closing the ticket as fixed.
