### ISSUE TITLE
Investigate removing Fennec -> Fenix migration code

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22489]
We are contemplating removing the "Fennec to Fenix" migration code from Fenix. We shipped the first Fenix release with migration code over a year ago (~ Summer 2020). Removing the code will reduce the maintenance burden, improve performance (#15581) and reduce the APK size.
We still need to go through the process of looking at data, getting approval etc. - but that doesn't stop us from investigating the engineering work already.

**Comment by cadeyrn** [comment]
> Removing the code will reduce the maintenance burden, improve performance (#15581) and reduce the APK size.

@pocmo: Also the migration of passwords for users with master password can cause a crash: #22279. Removing the migration code would make fixing this crash obsolete.

**Comment by pocmo** [comment]
@cadeyrn Great, thank you for mentioning that!

**Comment by philipwatmor** [comment]
What makes us unique is our solid ability, joined with an essential methodology, scrupulousness and severe working techniques. Our administrations stretch out to the gathering of kitchen furniture and furniture, all things considered, the selection of tones and the plan. We support you in all periods of get together, from key preparation and data design to execution and then some. Since for us, managing your furniture implies how managing you.[https://pimpmykitchen.at](url)
