### ISSUE TITLE
Duplicate tabs are sometimes opened

### ISSUE THREAD

**Issue by dmitryash** [mozilla-mobile/fenix#22525]
### Steps to reproduce

Duplicate tabs are opened when link is opened on new tab. Sometimes two or even three tabs are opened. duckduckgo is just an example.

1. Go to [duckduckgo](https://duckduckgo.com)
2. Go to settings and enable option to open links in new tab
3. Search something
4. Try to click on link, close tab if only one expected tab is opened
5. Repeat step 4 until two or three tabs are opened at the same time

### Expected behaviour

Only one new tab is opened for single click

### Actual behaviour

Sometimes several duplicate tabs are opened for one click/link. Moreover these two tabs may be tied to each other so that only the second is working but the first does not, renders nothing.

For example, two tabs opened by clicking link:

![double_tabs](https://user-images.githubusercontent.com/1093437/142760740-cce36ae3-af5b-4c55-804a-f8d71013423a.png)

### Device name

Asus ZB633KL

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

It is quite old issue, but since it's not been fixed yet, I decided to report it. It should be reproducible for 9x versions at least.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18687)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on the latest Firefox Preview Nightly 2021-11-24 but was unable to. The issue seems similar to https://github.com/mozilla-mobile/fenix/issues/22143. @dmitryash Is there any more information you can provide us that may help us reproduce the issue?
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by dmitryash** [comment]
@LaurentiuApahideanSV Do you know what I can gather from Firefox, maybe some debug information? I also saw issue #22143. Currently I see several tabs opened and they all working.

**Comment by PseudonymIII** [comment]
> I tried to reproduce the issue on the latest Firefox Preview Nightly 2021-11-24 but was unable to. The issue seems similar to #22143. @dmitryash Is there any more information you can provide us that may help us reproduce the issue?
> ### Devices used:
> 
>     * Oppo Find X3 (Android 11)
> 
>     * OnePlus 6T (Android 9)

why you using nightly version, we say stable one and also maybe beta and nightly affected too!

**Comment by LaurentiuApahideanSV** [comment]
I managed to reproduce the issue on both RC 95.1.0 and Nightly 2012-12-07. I could not find exact repro steps but managed to reproduce it reliably although rarely by opening a tab from a duckgogo search page, closing it very quickly and opening a new one (with the option to open pages in new tabs on).

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by doodhout** [comment]
I still have this issue on fenix v98.

Mind you, I used the setting in duckduckgo to open links in new tabs. I don't know if that is what @dmitryash meant in OP.

I then search for a subject in duckduckgo and instead of just tapping the results, I'd rather open a bunch of them before starting to read, by tap-and-hold a result and then choosing "open in new tab" in the context menu.

This cause the same tab to be opened twice or thrice.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807714

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
