### ISSUE TITLE
Optimize assets

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#22552]
Running `imageoptim` on the repo to optimize assets.

**Comment by gabrielluong** [comment]
Looking at imageoptim, I feel we want to do this at the figma or design library level for our icons. Doing so will mean that the SVG will optimize for both mobile and desktop. Since we are usually downloading assets (SVG) from figma nowadays, follow by converting it into an Android Image asset, which basically means we are taking in the existing SVG paths from the svg file. We wouldn't be able to run imageoptim on the Android image asset, but we can probably do so for any SVG/JPEG that we have.

**Comment by pocmo** [comment]
@gabrielluong SVG optimization is a good point, maybe less for size, but drawing performance? Let's file a separate issue for that. The intention here was to file some quick wins for reducing APK size and optimizing our small set of PNGs may reduce it a little bit.
