### ISSUE TITLE
Update inactive tabs colors on tab tray when in private browsing

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#22558]
### Steps to reproduce

Visit a site in private mode and switch to non-private mode

### Expected behaviour

Headlines and "inactive tabs" section have correct colors (what we currently have in non-private mode)

### Actual behaviour

Headlines are white, inactive tabs section has accent color background

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

96

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18715)

**Comment by rocketsroger** [comment]
This is dependent on https://github.com/mozilla-mobile/fenix/issues/21897

**Comment by delia-pop** [comment]
Verified as fixed on latest Nightly 105 from 08/10. The inactive tabs no longer display the private mode color. 
However, note that other items on the tabs tray are still affected: the collection prompt (issue https://github.com/mozilla-mobile/fenix/issues/22012) and new tabs thumbnail images (issues https://github.com/mozilla-mobile/fenix/issues/25977, https://github.com/mozilla-mobile/fenix/issues/19226).

I will remove the QA Needed label for now.
<img src="https://user-images.githubusercontent.com/89388888/184132847-dfe6918b-74df-4fb6-8c4f-b933f4af5a83.jpg" width="50%" />

**Comment by MozillaNoah** [comment]
Thanks @delia-pop for posting your findings! I'll close this specific issue now then since there are other issues already to track those separate visual bugs. The others will be deferred until the rest of the tabs tray has been converted over to Compose, our new UI system, where it will just be one top-level change to resolve any more private theming issues.
