### ISSUE TITLE
[Bug]: Keyboard opening when top site opens

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#22627]
### Steps to reproduce

Set https://www.theverge.com/ as a top site
Tap the top site to open it

### Expected behaviour

Site opens, ready to view

### Actual behaviour

Site opens with the keyboard opening, blocking the view

(user video at https://imgur.com/a/sHfYw3s)

### Device name

Google Pixel 6

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

94

### Additional information

SUMO Forum question:  https://support.mozilla.org/en-US/questions/1359388

**Comment by afurtak** [comment]
Can I work on this?

**Comment by eliserichards** [comment]
Yes, you can definitely work on this @afurtak! I will assign you to this issue. Make sure you add this issue number (#22627) to the title of your PR :)

**Comment by afurtak** [comment]
It happens, that the bug is no longer reproducible on current Main. I was able to reproduce it on commit from 7th September ("Set version to 94.0.0" by Roger Yang revision number: 494a9010).
Issue was reported for firefox 94, so I assume, that it was fixed somewhere along the way. 

Is it enough to close the issue?

**Comment by kbrosnan** [comment]
Yes this has been fixed in https://github.com/mozilla-mobile/android-components/issues/11252
