### ISSUE TITLE
Icons for addons are mixed up

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#22687]
### Steps to reproduce

This bug is not 100% reproducible, I only see this occasionally. I think these steps can reproduce the bug, although it does not occur most of the time(only about 40%).

1. Have about 6 addons installed(this is the number of addons I have, I think it'll also happen where there's more addons)
2. Open the tab switcher
3. Navigate to an old tab(about, or at least 1 week, I guess)
4. Immediately open the addons menu

This may not be the only way the bug occurs.

### Expected behaviour

The icons for each addon are displayed correctly.
![Screenshot_20211203-234442_Firefox](https://user-images.githubusercontent.com/58442255/144630951-904fe27e-dec8-4f7c-b66c-e765c0696169.jpg)

### Actual behaviour

The icons are jumbled up.
An example:
![Screenshot_20211203-200009_Firefox](https://user-images.githubusercontent.com/58442255/144631028-2a0fd9ba-ab9f-4b6b-b3ce-1367d39133b1.jpg)

### Device name

Samsung Galaxy S20 FE 5G

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

This bug is quite intermittent, and I have seen it occur several times that don't involve the abovementioned procedure(I experienced this even when writing this post). I do not know the root cause of this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18807)

**Comment by SoftVision-LorandJanos** [comment]
Hi @czlucius . Thank you for the report!
I tried to reproduce your issue first by installing exactly what I saw you had the issue with, on the latest RC (95.1.0) and I tried to fake and older than 1 week tab by setting the time in the future, and repeating this a few times without success.

I then installed 5 more addons and repeated the steps on the same build.

I also tried the same steps on the latest Nightly 96.0a1 (2021-12-07) build with the same result.

But since you've documented the description of your bug well, it could help a lot in determine the cause. Thank you!

Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by czlucius** [comment]
I think this issue happens in other scenarios as well, so the description above may not work well /may not be the way to reproduce the bug.

**Comment by willdurand** [comment]
This keeps happening, even with the default/official set of add-ons supported according to https://www.reddit.com/r/firefox/comments/y18yiq/are_there_more_addons_in_android_firefox_it_only/ (the screenshot, not the rest of the reddit post which discusses something else)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813916

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
