### ISSUE TITLE
[Bug]:  app-link (market://) is not trigerred on click.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#22717]
### Steps to reproduce

1. Go to https://m.okcashbag.com/frontTemplate/frontTemplateMobileGate.mocb?tplSeq=f8a9c6e319e089598f023e9d07a7dfe0
2. Click on ![Capture d’écran 2021-12-06 à 14 50 36](https://user-images.githubusercontent.com/505230/144794376-2cf0ae04-f4ec-49e0-b1cc-d79ac271ed00.png)

### Expected behaviour

Open Playstore or apps

### Actual behaviour

Nothing.

### Device name

Google Pixel 2

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18830)

**Comment by kbrosnan** [comment]
This works for me on a Pixel 2 XL using Nightly and Beta.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-02-22. The right button has no function when tapped.
![1645549387729](https://user-images.githubusercontent.com/50983519/155182053-8be59e89-573e-4365-8c41-a538886d9d02.JPEG)

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)
