### ISSUE TITLE
Improve homescreen rendering time

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22755]
We've recently added a lot of functionality to the homescreen and that has understandably slowed down the time to render its content (see https://github.com/mozilla-mobile/fenix/issues/21749 for details). Let's **investigate to see if there are optimizations we can make**.

csadilek suggested a general pattern to improve rendering of multiple views populated by async content: we could cache the data in memory, allowing us to fetch it synchronously while removing redundant layout/measure/draw computation.

See https://github.com/mozilla-mobile/fenix/issues/21749#issuecomment-936975793 for some profiles of the homescreen before and after the homescreen content was added.

Here are some sub-tickets for what we can optimize:
- https://github.com/mozilla-mobile/fenix/issues/14443
- https://github.com/mozilla-mobile/fenix/issues/14252

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/FNXV2-18864)

**Comment by csadilek** [comment]
Initially we want to solve the following two problems:
- The state needed to render the home screen is computed asynchronously _every time_ the home fragment is opened
- The sections on the screen are rendered whenever the corresponding state is available causing sections to appear non-deterministically (instead of from top to bottom).

We can solve this by storing the required state globally (and cache it) as opposed to computing it from an empty state every time the home fragment is needed. In https://github.com/mozilla-mobile/fenix/issues/20704 we have introduced a new `AppStore` that can hold state for the entire lifecycle of the app, which is exactly what we need here. So, the plan is to:
- Move all state needed from the home screen to the global `AppStore` and use it as a cache
- Render all sections from top to bottom based on the state in the `AppStore`
- Have the UI observe state changes on the `AppStore` so they can update automatically after the initial rendering

This will address the problems, except on cold start to HOME when the `AppStore` is not yet populated. This can be addressed in a follow-up by introduce a persistent cache, although it's likely that this trade-off is worth it i.e., reading from disc on cold start takes time too. Another option is an UI affordance e.g. a loading indicator for the home screen.

**Comment by gabrielluong** [comment]
Our first attempt to validate this approach and pattern will be from migrating Top Sites over to the AppStore in https://github.com/mozilla-mobile/fenix/issues/23306.

**Comment by Mugurell** [comment]
@gabrielluong @mcomella After talking with @csadilek about https://github.com/mozilla-mobile/fenix/issues/21854 he recommended migrating to compose each section separately and then add AppStore incrementally too.

Not sure whether in this process we should also simplify the `Interactor`s and `Controller`s such that for Composables we'd only have `Interactor`s with combined functionality.

**Comment by Mugurell** [comment]
@gabrielluong @csadilek  Not sure whether in this process we should also simplify the `Interactor`s and `Controller`s such that for Composables we'd only have `Interactor`s with combined functionality.

**Comment by gabrielluong** [comment]
> @gabrielluong @csadilek Not sure whether in this process we should also simplify the `Interactor`s and `Controller`s such that for Composables we'd only have `Interactor`s with combined functionality.

Our current views only calls the Interactor. I don't think we need to combine them in this process. We can decide to do this in the future, but definitely not overloading our PRs with refactors and adding compose in one-shot.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807346

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
