### ISSUE TITLE
When selecting multiple tabs to share with Pocket, only one page is saved to Pocket. 

### ISSUE THREAD

**Issue by OfficialMuffin** [mozilla-mobile/fenix#22814]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18906)

**Comment by kbrosnan** [comment]
Are you sharing them to the Pocket app? If so then this sounds like a feature/issue for the Pocket app. Some detailed steps to reproduce would be helpful.

**Comment by yoasif** [comment]
Per a comment [on reddit](https://www.reddit.com/r/firefox/comments/rj9hx4/how_to_save_multiple_posts_to_pocket_on_firefox/) multiple shares from other apps work.

I was able to reproduce the issue by navigating to the tab tray, selecting multiple tabs, then tapping the "Share" icon and tapping "Add to Pocket". I'm less sure how to make the expected behavior work.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible when sharing multiple pocket articles opened in Firefox Nightly 104.0a1 2022-07-14 to the Pocket app.
### Devices used:
- Google Pixel 6 (Android 13)
- Realme GT Master Edition (Android 11)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807374

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
