### ISSUE TITLE
FNX-89 ⁃ Support about:crashes for Fenix

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2295]
### Why/User Benefit/User Problem
It's really helpful to have a crash report attached to a bug report and not all users know how or want to get stacktraces from logcat (or even if they do they might not be near a laptop when the crash happens).

This also helps engineers make sure that their crashes are being reported correctly to the crash reporter.

### What/Requirements
Have a page (preferably `about:crashes`) that displays the list of crashes reported for the current profile with a link to the crash report.

**Comment by vesta0** [comment]
Thanks @agi90 ! This would be great, does it require GV work? cc @cpeterso

**Comment by cpeterso** [comment]
GV does have an about:crashes page, but it is incomplete (https://github.com/mozilla-mobile/fenix/issues/1221) because crash uploading (GV native crashes sent to Socorro and Fenix exceptions sent to Sentry) is delegated to the app (Fenix + AC's lib-crash component). We have a GV bug suggesting we disable GV's about:crashes in https://bugzilla.mozilla.org/show_bug.cgi?id=1541152

Fenix can implement its own about:crashes (that includes both GV native crashes and Fenix exceptions) because AC's lib-crash component knows about all crash reports that have been uploaded.

**Comment by djc** [comment]
I hope this will get some priority soon. As a longtime Nightly user, the current experience where I can not easily check if crashes are known and/or track progress of fixing them makes me feel rather powerless and frustrated when crashes occur (and over the past few days Fenix has been supercrashy for me in seemingly very common scenarios).

**Comment by agi90** [comment]
AC Issue: https://github.com/mozilla-mobile/android-components/issues/1705

**Comment by pocmo** [comment]
A replacement for `about:crashes` landed in Fenix and is available via "Settings > About > Crashes". For now it also opens if you type `about:crashes` into the toolbar (but not for other ways of navigating to that URL).
