### ISSUE TITLE
Tab is not being selected after switching form incognito mode

### ISSUE THREAD

**Issue by biozshock** [mozilla-mobile/fenix#23106]
### Steps to reproduce

1. Open 2 tabs in normal mode.
2. Open a tab in incognito mode.
3. Open a tab selector and close incognito mode tab, so no incognito mode tabs are opened.
4. Switch to one of normal tabs.

### Expected behaviour

A normal tab which was tapped is opened.

### Actual behaviour

Home screen is displayed.

### Device name

Huawei P20 Lite

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

95.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19077)

**Comment by Mugurell** [comment]
To me this seems like the expected behavior.
If the user is in private mode and closed all tabs
She will remain in private mode with the option then to open new private tabs / change to normal mode / tabs.
Entering private mode requires user action so maybe exiting private mode should require the same.

Asking UX about what the expected behavior is.

**Comment by mcarare** [comment]
@biozshock A video would be very helpful in describing the issue.

The bug, from what I understand and can also reproduce, is that after tapping on an existing non-private tab, after closing a private one from the tabs tray (tabs selector), instead of opening that tab the home screen is being shown.

**Comment by biozshock** [comment]
@mcarare Yes. That's what's the issue about.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812862

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
