### ISSUE TITLE
FNX-5585 ⁃ [Bug] Back and Close buttons on library's homepage do the same thing

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2313]
If two buttons do the same thing, only one should be enough, I suppose.
![20190507](https://user-images.githubusercontent.com/32398857/57274579-1573bd00-7072-11e9-8a45-5b1a4fde79f7.jpg)UNITO-UNDERSCORE!024414!

* Fenix version: 1.0.1919

**Comment by vesta0** [comment]
It seems like we added a back button but didn't remove the close button.

**Comment by vesta0** [comment]
@lime124 please confirm that we should remove the x from all library screens to stay consistent across the UI.

**Comment by yoasif** [comment]
While I don't think the close button looks _pretty_, it serves a purpose - and I think that maybe people are fooled because right now, there is no way to access desktop bookmarks, and it isn't *that* easy to create folders in bookmarks. 

If a user has bookmarks, especially if they are nested, it would be nice to simply be able to close the library, as the user doesn't have to tap back, back, for every layer inside of bookmarks they are. 

FWIW, Chromium based bookmark UIs have the same button in place. 

I see removal of the close button as a form over function move with real downsides.

**Comment by topotropic** [comment]
We should keep the x button to give people the option to quickly exit the Library w/o having to navigate one screen at a time out by using the arrow button.

I also don't see a huge issue with duplicating functionality on the Library start screen (back arrow and x to close) some people might prefer to use the arrow to back out of the Library, other are used to the x to close.

From UX point of view we can close this issue.

**Comment by ekager** [comment]
Thanks @topotropic ! Closing
