### ISSUE TITLE
[Bug]: Dark Mode event missed on OnePlus android

### ISSUE THREAD

**Issue by ikke-t** [mozilla-mobile/fenix#23475]
### Steps to reproduce

1. I have dark reader add-on in automatic mode, mobile is OnePlus 8
2. I change dark mode on/off from android system menu

### Expected behaviour

Firefox page to go dark/light based on the setting. This works on my other android, samsung s6 lite

### Actual behaviour

Dark reader won't get event, and doesn't change the mode. 

https://user-images.githubusercontent.com/1146409/151701160-0fb966fc-263f-434b-a52f-272a413fac57.mp4

### Device name

OnePlus 8

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.2.0

### Additional information

I first created an issue to dark reader, but got pointed to here instead: https://github.com/darkreader/darkreader/issues/8039#issuecomment-1025125103

**Comment by mcarare** [comment]
Tested this with help from @LaurentiuApahideanSV (thank you for this!). 

Setting dark reader to automatic appears to follow the Fenix theme rather than the device's theme. That is the reason it keeps being dark when you change the device theme.

To completely follow the device theme, you must also set the Fenix theme to "follow device theme." With that option enabled, the website theme will change in tandem with the device theme.

I'm closing this because it appears to be a problem with the add-on rather than Fenix. Although the current behavior of the add-on appears to be the correct and logical one (to follow the app theme rather than the device theme).

**Comment by Gusted** [comment]
> I'm closing this because it appears to be a problem with the add-on rather than Fenix. Although the current behavior of the add-on appears to be the correct and logical one (to follow the app theme rather than the device theme).

@mcarare It seems like you're suggesting that it's possible for a addon to follow the device's theme? I'd only know of one way to get any sort of theme `matchMedia('(prefers-color-scheme: dark)')` which to my understanding should report the device's theme. Is there a function or API that I don't know of which actually returns the device theme.

**Comment by mcarare** [comment]
@Gusted I am actually saying I think the current behavior is the expected one. 
I am not aware if something can be done in the add-on to follow the device theme instead of the app theme.

**Comment by Gusted** [comment]
@mcarare Thanks for the explanation, and for the debugging of the problem.

**Comment by ikke-t** [comment]
Thanks, that fixes it.
