### ISSUE TITLE
FNX-5612 ⁃ Open page in native app

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2355]
### Why/User Benefit/User Problem
If I visit a page that has a native app installed, I might be able to do more with the native app. Reddit app has a few features that the reddit site does not have.

### What/Requirements
Fennec has a small android icon in the url bar for sites that have apps installed. Fenix might do the same. Any other UX can be ok also.
![Screenshot](https://user-images.githubusercontent.com/922368/57401259-ee39fe80-71dd-11e9-889b-9c8c8cd9e280.png)UNITO-UNDERSCORE!20190508-220050!UNITO-UNDERSCORE!Firefox!

### Acceptance Criteria (how do I know when I’m done?)
Install a reddit app.
Visit reddit on Fenix. It DOES NOT automatically open the app like Chrome does for some sites.
The user has an option to open the app on the same page.

**Comment by yoasif** [comment]
FWIW, it is apparently a blocker for some users to *not* replicate the other Android browser behavior of opening links in native apps.

So it would be nice to have an option to replicate expected behavior of links to open in native apps without user action. This probably ought to be the default to match user expectations on Android. 

See also  #1570 and https://github.com/mozilla-mobile/android-components/issues/1132

**Comment by vesta0** [comment]
Thanks for the suggestion @andreicristianpetcu :) We are working on this in [#1132](mozilla-mobile/android-components#1132)

**Comment by andreicristianpetcu** [comment]
fixed the link https://github.com/mozilla-mobile/android-components/issues/1132#thread-subscription-status
