### ISSUE TITLE
Fenix shouldn't show "Set as default browser" button if it's already the default browser

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#23618]
When I started Fenix Nightly today, its homepage had a tile asking me to set it as my default browser ("Set as default browser"). But Fenix Nightly is already my default browser!

@jonalmeida says Fenix should be able to check whether it's already set as the default app.

AC has code to query the default browser, but it might require some legacy permissions: [[https://github.com/mozilla-mobile/android-components/blob/main/components/support/[…]tils/src/main/java/mozilla/components/support/utils/Browsers.kt](https://github.com/mozilla-mobile/android-components/blob/main/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt#L115).](https://github.com/mozilla-mobile/android-components/blob/ec0201897ae2b2d91ec36be41986dff1c3192501/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt#L112-L115)

**Comment by Amejia481** [comment]
Maybe this could be a regression from https://github.com/mozilla-mobile/fenix/commit/82a6f8cae411603ba5abced3b13fc43ca40f335e,  my nightly also shows the set to default browser banner on the home screen even though it's already the default browser.

cc @jhugman

**Comment by Amejia481** [comment]
This is what we use for checking on [Fenix](https://github.com/mozilla-mobile/fenix/blob/82a6f8cae411603ba5abced3b13fc43ca40f335e/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L334)  that internally uses [AC](https://github.com/mozilla-mobile/android-components/blob/main/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt#L135-L140).
But the value that we are using for `FIREFOX_NIGHTLY` is linked to fennec [`org.mozilla.fennec`](https://github.com/mozilla-mobile/android-components/blob/ec0201897ae2b2d91ec36be41986dff1c3192501/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt#L45
) instead of `org.mozilla.fenix`

**Comment by SoftVision-LorandJanos** [comment]
I managed to reproduce this issue with the Nightly 98.0a1 (2022-02-06).
The banner was displayed while being set as default browser.
On the latest Nightly 99.0a1 (2022-02-15) I wasn't able to reproduce this issue.
Verified as fixed on the above mentioned Nightly.
Closing the ticket.
