### ISSUE TITLE
[Bug]: the same page can be added to bookmarks from tabs tray multiple time (no snackbar/ message is displayed informing that the page is already a bookmark) 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#23671]
### Steps to reproduce

1. Open 1-2 pages.
2. Open tabs tray and select a tab.
3. Open 3dot menu and Bookmark the page.
4. Perform steps 2-3 again, for the same tab.

### Expected behaviour

"Bookmark already saved" snacknar should be displayed.
Or the "Bookmark" option shouldn't be available. 

### Actual behaviour

"Bookmark saved! View" snackbar is displayed. 

### Device name

Sony Xperia

### Android version

6.0.1

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.1

### Additional information

"Recent bookmarks" section is not updated, if steps 2-3 are performed for an old bookmark.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19448)

**Comment by jonalmeida** [comment]
We don't look at any [status result](https://github.com/mozilla-mobile/fenix/blob/40123882dc2372a6f25e5d0e8ce93f5283f99c76/app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt#L227) from the tabs tray when we show the snackbar from the tabs tray.

Since it's a multi-select action, we would need to see how that UX would work if one is saved and one wasn't, for example.
