### ISSUE TITLE
Redirect to 3rd party app if URL is coming from other apps

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#23681]
Currently we don't redirect to a 3rd party app when opening an URL is external triggered.  Investigate to see if we can redirect them to the 3rd party app if available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19456)

**Comment by markcellus** [comment]
Came here because enabling "open links in apps" in Settings doesn't work. Is that the issue described here?

**Comment by markcellus** [comment]
Not sure if this may help but I had to go to the settings of the app you'd like to open links in and manually enable them. It should be under the "Allow app to open supported links" option.

**Comment by Araly** [comment]
> Not sure if this may help but I had to go to the settings of the app you'd like to have links open in and manually enable all supported links. It should be under the "Allow app to open supported links" option. It worked after I did that.

I just enabled that for twidere (twitter client) and infinity (reddit client) and I was able to completely bypass firefox, opening the links directly in their relevant app.

This feels like it's not a firefox issue, but an android issue. I'm pretty sure it used to be that when you clicked on a link, android would bring up a little pop up that said "where do you want to open this link ?". You'd press "I want to open this link in twidere, always" or "I want to open this link in infinity, this time". If you pressed always, it would remember and not prompt you next time.

It feels backwards for android to suddendly just start opening everything in the browser, and then let the browser do what it wants there. It's especially bad when you click on a twitter link, firefox opens up with half the page taken up by cookie banners and one that says "we see you're on a mobile, please open this is the twitter app !". You click on it and get sent to the play store of the twitter app, or even sometimes you stay in firefox, and it opens up the play store page there.

Is there an android default that suddendly decided user probably don't want to go to apps when they click on links from other apps ?

---

I do think the firefox app has some fault in this though. firefox is the only browsers that I tried that have the "open link in app" button (which is mostly why I was using it). It also has the toggle to "open links in apps" in the settings. This to me tells me that firefox has the power to automatically open links in apps when I open them, *without needing me to press the 3 dots menu and pressing "open link in app"*.

This is however not the behavior everyone has been getting, and I think that people attribute this backwards behavior of "clicking on a link sends me to firefox, and then I need to press a button to go to the app" to a firefox bug, rather than android removing a feature.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809269

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
