### ISSUE TITLE
Vibration API doesn't work

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#2371]
## Steps to reproduce
1. visit https://www.audero.it/demo/vibration-api-demo.html
1. click any of the buttons (vibrate once, vibrate trice)

### Expected behavior
Fenix shows a permission prompt to use the API and if granted the device will vibrate.

### Actual behavior
Nothing happens.

### Device information
* Android device: 7.1.1
* Fenix version: 1.0.1919

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11368)

**Comment by kbrosnan** [comment]
[Gecko requires the user to accept a prompt for a website to vibrate the device](https://bugzilla.mozilla.org/show_bug.cgi?id=1243431). Fenix does not have this wired up right now.

**Comment by NotWoods** [comment]
Blocked by [Bug 1495036](https://bugzilla.mozilla.org/show_bug.cgi?id=1495036)

**Comment by ronCYA** [comment]
Alternative test page, as repro link is down/currently having Cloudflare issues: https://googlechrome.github.io/samples/vibration/

**Comment by JohnGlassmyer** [comment]
someone should fix this one.

**Comment by tamb** [comment]
This desperately needs to get fixed

**Comment by marcusx2** [comment]
So vibration doesn't currently work on Android Firefox?

**Comment by JohnGlassmyer** [comment]
> So vibration doesn't currently work on Android Firefox?

vibration doesn't work in Fenix, the current Android Firefox app that was launched in 2020. vibration was working in the last released version (68) of Fennec, the old Android Firefox app.

**Comment by marcusx2** [comment]
So...this bug was reported in 2019. It's been over 2 years...any ETA to fix this?

**Comment by JohnGlassmyer** [comment]
gee it sure is sad that no one's commented on this in months.

**Comment by trulycool** [comment]
Jeesh, how many web developers end up excited by PWAs, use Firefox Mobile, and then end up here?

FF renders the PWA better than Chrome; gets the theme color for app shortcut, and the top of screen. But my little applet really wants the haptic feedback (japa and/or other stuff counter):
https://trulycool.is/counting

So while FF Mobile is my daily driver, and many, many thanks to the devs who have brought it so far in the past year, sadly reverting to Chrome or Brave for PWA :(

Firefox Mobile is such a great browser now. This lack of Vibrate API support is such a shame.

Sadly while I am a developer, php/python/javascript, no C++, Kotlin, Rust (if that's even what mobile used). Otherwise, would enthusiastically pitch in.

**Comment by trulycool** [comment]
Cross posting on this same issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1591113

As a [mostly] web dev w/ 25+ years experience, I have been waiting years for PWA's to really arrive. Put up an example this weekend, and it's amazing, seems finally ready for prime time. However, my favorite mobile browser and daily driver falls a bit short.

Firefox Mobile doesn't support the Vibrate API (again, as of March 9, 2022). Not due to an actual technical issue, but because it was disabled due to abuse by shady websites.

FF Mobile renders the PWA much better as a "real" app, changing the android notification bar the theme color. And of course, FF is my daily driver, and I evangelize whenever possible. However, lack of vibration API support really skews that. The fact that FF has a worse PWA developer experience than all the chromium derivatives seems wrong on many levels.

Looked at the Fenix source, after tracing several other bug reports w/ patches, but clearly, nothing for current code base. Kotlin isn't too crazy different to at least poke around. Closest hackable section I found was the QR code section, which imported the Android vibrate API, and is clearly coded to vibrate, but doesn't. So the disabling is elsewhere that I couldn't track down...

My understanding from parsing bug reports here, on Github, and reddit, is that Fenix developers disabled this, and can't quite figure out how to properly surface a user permission prompt on a per site basis.

Seems like a test for "am I installed as a PWA" and "am I active" might be a workaround. This wouldn't solve the [apparently thorny] per site permission issue, but would give developers the FF powered mobile app we desire...

Reference for PWA check:
https://petelepage.com/blog/2019/07/is-my-pwa-installed/

**Comment by trulycool** [comment]
Updated PWA mode check:
https://web.dev/customize-install/#detect-launch-type

**Comment by JohnGlassmyer** [comment]
this still affects current Fenix.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810000

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
