### ISSUE TITLE
[Bug]: [L10N] The "Cancel" button is not translated to Welsh

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23719]
### Steps to reproduce

1. Set the device language to Welsh;
2. Have some bookmarks;
3. Go to the Bookmarks section;
4. Tap the 3 dot menu from a site and select edit option;
5. Tap the trash icon.

### Expected behaviour

The "Cancel" button must be translated to Welsh.

### Actual behaviour

The "Cancel" button is not translated to Welsh. Please see the screenshot attached for reference.

<img width="387" alt="Screenshot 2022-02-14 at 15 22 13" src="https://user-images.githubusercontent.com/96047134/153872141-82498555-6146-479b-81bf-c21cb3ed2e66.png">

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.1

### Additional information

The issue is reproducing on latest Nightly as well (99.0a1)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19484)

**Comment by Alexandru2909** [comment]
Hi, I observed that the word 'cancel' is mistranslated for Welsh wherever `android.R.string.cancel` is used instead of string resources (this is also the case for [21911](https://github.com/mozilla-mobile/fenix/issues/21911)). However, `mozilla-l10n-automation-bot` seems to [handle it well](https://github.com/mozilla-mobile/fenix/blob/19ea02077c521739865405dde0c7525442f20ceb/app/src/main/res/values-cy/strings.xml#L1128). We could add new string resources and use them instead of `android.R.string.cancel` for better localization.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 102.0a1 (2022-05-18) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
