### ISSUE TITLE
[Bug]: Don't post our "Make Firefox your default browser" notification late at night

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#23726]
### Steps to reproduce

My personal STR (not how to reliably trigger but I assume something along these lines):

1. Install Firefox for Android (or more-specifically Firefox Beta in my case, but I assume this happens with all versions)
2. Wait

### Expected behaviour

We shouldn't pop up notifications late at night, when they might annoy/disturb the user when they're trying to sleep.

Maybe 9am-9pm would be a good time-window for most users?

### Actual behaviour

As I was going to sleep (I can't remember if it was the same day I installed Firefox Beta or several days later), at around 11:18pm, my phone got a sudden notification, which caused my smart-watch to buzz and wake me back up. The notification was:
```
Firefox Beta
Firefox Beta is fast and Private
Make Firefox Beta your default browser
```

11pm (and later) is probably not a good time to be spamming "Wake up and make us your default browser!" notifications to the user.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

98.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19490)

**Comment by dholbert** [comment]
![screenshot](https://user-images.githubusercontent.com/426803/153927055-656fdfdf-3e22-43cb-9a51-da6c2fc5a482.png)

**Comment by laksh-21** [comment]
Hi! I could work on this!
I looked into the code and when the app is started, in the `onResume` function of `HomeActivity`, a `DefaultBrowserNotificationWorker` is started (already existing policy is set to keep so only one worker exists at a time). And the delay for this worker is set to 1 day. So if the user opens the app for the first time late at night, the notification will also be shown the next day at that time only. Could change it so that the time is edited to be more appropriate if it falls in that range.

**Comment by dholbert** [comment]
Looks like someone else filed this bug earlier in #20887 actually.  My report here should probably be closed as a duplicate of that older one.
