### ISSUE TITLE
Set the destructive text color for the credit card editor

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#23771]
When we display the error message from validating whether or not the entered credit card number is validate in "Add card". We aren't setting the error text color to attr/destructive. https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt#119

We should set the error text color for both `cardNumberLayout` and `nameOnCardTitle`.

**Comment by gabrielluong** [comment]
> Hello, is this issue still available ?

Yes

**Comment by tristan-jea** [comment]
I've looked into the issue and I have a question : I assumed you meant `nameOnCardLayout` instead of `nameOnCardTitle`. Is my assumption right?

**Comment by gabrielluong** [comment]
> I've looked into the code and I have a question : I assumed you meant `nameOnCardLayout` instead of `nameOnCardTitle`. Is my assumption right?

Yes, that's correct

**Comment by gabrielluong** [comment]
One way to reproduce the current issue would be to change the attr/destructive color and observe that the error text ("Please enter a valid credit card number") color does not match the title.

**Comment by tristan-jea** [comment]
Thank you for your answers. 
Now that the issue is almost fixed I have 2 new questions.

When I was testing the fix, I discovered that unlike the `cardNumberLayout` error message, `nameOnCardLayout`'s message does not clear when valid data is entered and the save button is pressed. It occurs when an invalid card number is used. This affect the fix because the `nameOnCard` field does not return to it's valid state (the error color is not replaced). What should I do for this issue's future pull request ?

Also, should I add tests in `CreditCardEditorViewTest` ?

**Comment by gabrielluong** [comment]
According to https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt#122, the error shouldn't be shown if name on card is not blank. I am not too sure beyond seeing your changes and testing it further to figure out a solution. 

Tests will always be appreciated if you think it's straight forward to add one to the existing test.

**Comment by tristan-jea** [comment]
Yes you are totally right, the if condition works as intended.
I think the bug comes from https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt#123 because it's not the `error` member of `nameOnCardInput` that is used but `nameOnCardLayout`'s one (https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt#128). Replacing line 123 by `binding.nameOnCardLayout.error = null` should fix it.

I've tested it on my side and it fixes the bug. Should I include it in the pull request or is it better to file a new issue like advised in the contributing guidelines?

**Comment by gabrielluong** [comment]
Let's fix it in a separate issue to avoid overloading the current issue.
