### ISSUE TITLE
Clear error message for nameOnCardLayout when valid name is submitted

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#23813]
Thank you for your answers. 
Now that the issue is almost fixed I have 2 new questions.

When I was testing the fix, I discovered that unlike the `cardNumberLayout` error message, `nameOnCardLayout`'s message does not clear when valid data is entered and the save button is pressed. It occurs when an invalid card number is used. This affect the fix because the `nameOnCard` field does not return to it's valid state (the error color is not replaced). What should I do for this issue's future pull request ?

Also, should I add tests in `CreditCardEditorViewTest` ?

_Originally posted by @tristan-jea in https://github.com/mozilla-mobile/fenix/issues/23771#issuecomment-1042107296_

**Comment by gabrielluong** [comment]
https://github.com/mozilla-mobile/fenix/issues/23771#issuecomment-1042301945

**Comment by gabrielluong** [comment]
@tristan-jea I filed this for you in case you wanted to take this.

**Comment by tristan-jea** [comment]
Thanks, I'll work on it

**Comment by tristan-jea** [comment]
I'm wondering if I should add a new method in `CreditCardEditorViewTest` to test that both `nameOnCardLayout`'s and `cardNumberLayout`'s error messages are cleared correctly ? These tests cannot be integrated inside existing ones because there is no test that set invalid values and then valid values.
What do you think about this ?

**Comment by gabrielluong** [comment]
Sure, go for it!
