### ISSUE TITLE
[Bug]: A white/grey flicker is displayed for a split second while the website loads or when switching tabs

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24106]
### Steps to reproduce

when enabling dark theme and opening website (mostly heavy like telegram or tinder )from home the annoying white flash is back(briefly let's say one second )!!!
can anyone confirm this ?🤢 
screenshot of the issue :
https://i.imgur.com/Em43qYX.jpg
🤢 

### Expected behaviour

withe flash must go away with dark theme enabled 

### Actual behaviour

Fenix shows white flash before site load 

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

99

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19735)

**Comment by DiegoARL38** [comment]
I can confirm it's back for me.
* Firefox Nightly 99.0a1 2022-03-03T17:37:19.103877.
* Xiaomi Redmi Note 8 with MIUI 12.5.1.0, Android 11.

It is inconsistent, but it happens regularly. Switching tabs via the tabs tray, loading top sites, and returning to an unloaded tab appear to be the most reliable methods of reproducing the issue.

I suspect, though don't have the knowledge to confirm, it might have been caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1756700

**Comment by ale82to** [comment]
I set gpu process to true using about:config and makes things defebitely lots worse so you might be right .
(for comparison setting gpu process to true in 3 day ago build ,Tuesday ,does not show any white flash at all )

**Comment by delia-pop** [comment]
Hi @ale82to, thank you for the report.
I could reproduce this issue on several devices and builds. A white/grey flicker and an empty toolbar are displayed for a split second when switching tabs.

This is reproducible on the following builds: 
- latest Nightly (99.0a1 from 03/07)
- RC 98.1.1
- RC 98.1.0
- 98.0.0-beta4

with the following devices:
- Motorola Moto G30 (Android 11)
- Google Pixel 4 (Android 12)
- Google Pixel 6 (Android 12) - only the empty toolbar issue is present when switching tabs.

Devices on which the issue is not encountered:

Samsung Galaxy Tab S3 (Android 9)
Sony Xperia (Android 6.0.1).

**Comment by paritosh9199** [comment]
Experiencing flickers when changing switching to FF from other app. https://user-images.githubusercontent.com/27616102/166134898-6cf5795d-1780-4b69-b630-db32c0b8f801.mp4
