### ISSUE TITLE
[Bug]: The pinned top sites and sponsored tiles are still available after disabling the "Shortcuts" option

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/fenix#24130]
### Prerequisites:
- Have at least one pinned top site available.
- Have at least one sponsored tile available.

### Steps to reproduce

1. Open the Nightly browser.
2. Tab the "Hamburger" menu.
3. Tap the "Customize homepage.
4. Disable the "Shortcuts" option.
5. Return to the homepage and observe the top sites section.

### Expected behaviour

- The top sites section is no longer displayed.

### Actual behaviour

- The pinned top sites and the Sponsored tiles are still available.

### Device name

One Plus 8 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

- Only the history tiles disappear after disabling the "Shortcuts" option.

https://user-images.githubusercontent.com/19226534/157014223-515ab30c-0abe-4a9b-b325-c779a3189863.mp4

**Comment by kbrosnan** [comment]
Talked with Verdi about the behavior. We want to change this to behave like desktop. The shortcut toggle will disable the entire top sites section. This pref should be reset for existing users, because this behavior is changing dramatically. Sponsored shortcuts only disables the sponsored shortcuts, not any default pined sites. Sponsored shortcuts checkbox would be disabled if the whole feature is disabled.
