### ISSUE TITLE
Improper transition for elements on homepage when changing the orientation

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#24163]
### Steps to reproduce

1. From Portrait mode, go to the "Thought-provoking stories" or other sections/elements on the homepage.
2. Rotate the device to Landscape mode.
3. Observe the section in step 1. 

### Expected behaviour

The sections/elements are correctly displayed when the orientation is changed.

### Actual behaviour

Half of the sections/elements is cutoff when the orientation is changed.
This is not happening all the time, but can be reproduced after sending the application in the background and re-opening it.

### Device name

Motorola Moto G30

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 100.0a1 from 03/09

### Additional information

The issue was also encountered on 99.0.0-beta.1., RC 98.1.1, RC 97.3.0.
Tagging @Mugurell for visibility.  

https://user-images.githubusercontent.com/89388888/157435906-82521525-e1d2-4bd3-80dd-3d161544a5f8.mp4

https://user-images.githubusercontent.com/89388888/193241451-985abec9-85c2-42b3-997c-91f8f9c8f585.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19772)

**Comment by Mugurell** [comment]
@delia-pop Only reproducing on one device makes this interesting.
Does the issue reproduces with other homescreen sections also like "Recent bookmarks" / "Recently visited" ?

**Comment by delia-pop** [comment]
Reproducible on RC 99.1.0 with LG G7 fit (Android 8.1.0).

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?
I can reproduce the issue as @delia-pop mentioned.
I can see the issue only when the app resumes from the background. The issue also affects Stories by topic . If we scroll the screen the issue is gone.

**Comment by Mugurell** [comment]
@indurs Sounds good, would be great to have a straightforward solution for this, thank you!

**Comment by indurs** [comment]
Sure. Thank You!

**Comment by indurs** [comment]
@Mugurell, the issue is happening sometimes even if the app is in foreground as @delia-pop mentioned. (rotating the device from portrait to landscape). 
Even though the onConfigurationChanged() method is called during the orientation change, I think the ViewHolder composables are not recomposed every time onConfigurationChanged() is invoked. 
I've posted this issue in Compose slack channel

I tried with a simple RecyclerView. (Fragment, RecyclerView with ComposeView viewholder). In the manifest I've set android:configChanges="orientation” 

https://user-images.githubusercontent.com/12825812/162120397-a25aab3d-b574-47ff-b382-6564696a7559.mp4



Possible solution
In the viewholder, I tried with DispossableEffect with LocalConfiguration.current as the key and called composeView.disposeComposition(). The issue is resolved but I'm not sure whether its an efficient way.

**Comment by Mugurell** [comment]
> Possible solution
In the viewholder, I tried with DispossableEffect with LocalConfiguration.current as the key and called composeView.disposeComposition(). The issue is resolved but I'm not sure whether its an efficient way.

Thank you for looking into this!

Seems like a solution we could adopt thinking that when the orientation changes apps are normally expected to recreate their layout.
In this case we'd create a new composition even though the data didn't change so I'm thinking that maybe we could skip composition and only go through the layout and drawing phases but for that we'd probably need to handle this on our own.

Since you already have a sample for demoing the issue could you open a new ticket on `issuetracker.google.com`?
We could get there a confirmation of the proposed "fix" and the issue would be easier to track for updates.

**Comment by indurs** [comment]
Sure @Mugurell . I will open a ticket on issuetracker.google.com. Thank You !

**Comment by indurs** [comment]
@Mugurell , I've created a ticket. https://issuetracker.google.com/issues/228418619

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807372

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
