### ISSUE TITLE
[Bug]: Default top sites can be re-added to the top sites list

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#24186]
### Steps to reproduce

1. Tap on any default top site from the Homepage (e.g: Google)
2. Tap on the 3dots menu and tap on "Add to top sites" option

### Expected behaviour

The default top sites must not have the **"Add to top sites"** option enabled and **"Remove from top sites"** option must be available for the sites which are already added to the top sites.

### Actual behaviour

The default top sites have **"Add to top sites"** option enabled and they are successfully added to the top site section. 

The following default top sites are impacted:
- Google
- Top Articles

**Notes:** Wikipedia (default top site) and the other random sites which are added as top sites are working as expected -> **"Add to top sites"** option is not enabled and **"Remove from top sites"** option is displayed instead.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

99.0.0-beta.1

### Additional information

The issue is reproducing on the latest Nightly build  as well (100.0a1).

https://user-images.githubusercontent.com/96047134/157630220-4c663711-9811-4457-9437-184133344be3.mp4

**Comment by indurs** [comment]
@Mugurell , can I look into this issue?

Going through these files

1. DefaultTopSitesStorage
2. DefaultBrowserToolbarMenuController
3. Core
4. DefaultToolbarMenu
5. BaseBrowserFragment
6. TopSitesUseCases

**Comment by Mugurell** [comment]
This seems like the expected behavior.
The default top sites (and all top sites) have a certain url. This is what differentiates them. 
That url when accessed may redirect to a new one. And this new url can be added as a separate top site.
This redirection is seen on the video for the "Top Articles" top site where the url changes from one to the other.
It doesn't seem feasible to merge all urls by domain and only allow one url for an etld domain. There may be valid usecases of users wanting to have different top sites for different pages on the same domain.

**Comment by indurs** [comment]
Ok. I now understand that this is the excepted behavior. Thank You

**Comment by delia-pop** [comment]
Closing this ticket based on the discussion above.
