### ISSUE TITLE
FNX3-16313 ⁃ [Bug] unexpected behaviour with disabled tracking protection and page toggle / exceptions

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2422]
### Steps to reproduce / Expected behavior / Actual behavior
THIS WORKS:

1. make sure tracking protection _is_ enabled
1. open a website
1. click on the padlock

=> You can see that tracking protection is enabled (as expected)

1. press the toggle to add an exception for this website
1. close the panel and click on the padlock again

=> The toggle is disabled and if you go to the tracking protection settings you can see the website in the exceptions (still as expeced)

… BUT THIS IS UNEXPECTED:

1. make sure tracking protection is _not_ enabled
1. open a website
1. click on the padlock

=> You can see that tracking protection is disabled (as expected)

1. press the toggle to add an exception for this website
1. close the panel and click on the padlock again

=> The tracking protection toggle is still disabled but should be enabled and if you go to the tracking protection settings the website is not on the exceptions list.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision e1cdeffe8c7168141a586b7c9126555df4c0fb53

**Comment by ekager** [comment]
I don't think exceptions are supposed to work the opposite direction. They are only to add ane exception for TP to be OFF for a specific domain always ie if the site breaks a lot (even when TP is ON globally). Having it do the opposite - be an exception for TP to be ON when TP is OFF globally seems wrong and confusing. 

We could add a visual state / disable the toggle when TP is OFF globally as an indicator to make it more clear that it only works in one direction because I agree that this interaction could be confusing overall.

CC @vesta0 and @AmyYLee for input

**Comment by yoasif** [comment]
FWIW, Brave works the way that @cadeyrn expects - individual sites can override a global preference to not block ads, for instance. 

Their UI for this is not as pleasant as what @cadeyrn is proposing, since it doesn't actually get logged as a visible permission in settings. 

I like the idea - while I think that if the Fenix default is enabling TP by default, it is certainly possible that some people would globally disable it and want to re-enable it for certain sites. 

The easy solve here, if PM and UX prefer to not cater to the above use case, is to disable the TP toggle on pages entirely if the global switch is disabled, imo. Otherwise, confusion abounds.

**Comment by topotropic** [comment]
(taking over for Amy, she's on PTO) 

I agree that "Tracking Protection: on" is the default and we allow exceptions to the default – similar to what happens on FF desktop. If we reverse this logic it's going to be confusing. 

The current implementation suggests that you can turn on tracking protection for a site although TP is globally turned off, this is misleading. We should disable the toggle when TP is off globally as @ekager mentioned above, add a brief explanation of why the toggle is disabled and how to enable it again.

![Site Information Panel - TP off in Settings@2x](https://user-images.githubusercontent.com/353960/57619994-c2c16600-7587-11e9-8d38-ae1df0c91f16.png)

**Comment by vesta0** [comment]
@AmyYLee @brampitoyo I'd like to hear your recommendation here. We had suspected that the exceptions behaviour may not be intuitive without some kind of messaging or prompt.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/16 build.
