### ISSUE TITLE
auto hide context menu after dictionary use

### ISSUE THREAD

**Issue by Juan-132** [mozilla-mobile/fenix#24244]
### Steps to reproduce

1.Long press a word you want translated
2.Select ... from context menu (extra options) 
3.Select dictionary
<<Read dictionary info>>
4.Select X on dictionary popup to close

Result: The context menu is still visible
Expected: The context menu was hidden after step 3

### Expected behaviour

Above

### Actual behaviour

![Screenshot_20220313-101018_Firefox](https://user-images.githubusercontent.com/59505296/158053080-ed3a5976-7e02-4c2e-8f2d-34b4ee6b48c8.jpg)

### Device name

Samsung A50

### Android version

Android 11 / OneUI3. 1

### Firefox release type

Firefox

### Firefox version

98.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19827)

**Comment by Juan-132** [comment]
Hi, thank you for validating the issue.
I just upgraded to 98.2.0, and the issue persists. Attached is a video that reproduces the issue on Android 11 / OneUI3. 1. 

https://user-images.githubusercontent.com/59505296/158629490-12fa2f79-52d7-48bf-bb7e-633547000a29.mp4

**Comment by Juan-132** [comment]
At the end of the video I closed the context manually by clicking on the text of the website.

**Comment by fice-t** [comment]
I think this is a GeckoView issue since Fenix uses Android Component's `DefaultSelectionActionDelegate`; the [`performAction` method](https://searchfox.org/mozilla-mobile/rev/060602fc5c11bde556ffdcf184ca33f2f74aeedd/android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegate.kt#80) doesn't handle items created using 3rd-party intents (the else branch is called), which I think is related to GeckoView's [`getProcessTextIntent`](https://searchfox.org/mozilla-central/rev/c5c002f81f08a73e04868e0c2bf0eb113f200b03/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/BasicSelectionActionDelegate.java#299).

The Dictionary context menu item in this issue is a result of one of those text intents (another one to try is the Dictionary.com app), in this case Samsung's dictionary app which opens above the content. This behaviour is different to 3rd-party dictionary apps that simply open their app when invoked. Perhaps GeckoView should dismiss the context menu on text intent-based actions instead of relying on the action to open a different app?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809308

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
