### ISSUE TITLE
[Bug]: Fenix shouldn't request camera permission

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/fenix#24260]
### Steps to reproduce

VPN active pointing to UK

1. Install fresh app.
2. Go to Settings Site permission and block camera permission
3. Navigate to https://www.gov.uk/report-covid19-result
4. Tap "Start now" button.
5. Proceed with the form without an account ("Continue without an account" > Myself > England > No > Another reason > Another reason (for example, to follow NHS advice or Government guidance) > Today, ).
6. Tap "Scan test strip QR code" button.
7. Camera android permission is requested.

### Expected behaviour

Camera android permission shouldn't be requested if camera is blocked from Settings Site permissions.

### Actual behaviour

 Camera android permission is requested.

### Device name

All devices 

### Android version

All versions

### Firefox release type

Firefox

### Firefox version

98

### Additional information

https://user-images.githubusercontent.com/8118371/158137789-e002a5e8-6491-4da7-959d-1b888faa628e.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19834)

**Comment by Amejia481** [comment]
Thanks for reporting this. What you are seeing it's not a permissions from a website, it's an app permissions to use the camera, [this happens because we are not checking](https://github.com/mozilla-mobile/android-components/blob/d9fdb1495fd7dd45c9d58fa0ec54c949bcb866aa/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt#L163) for `sitePermissionsRules` when app permissions are required, to address the issue we only need to not trigger  `onNeedToRequestPermissions` when the permission is marked as blocked.

**Comment by indurs** [comment]
@Amejia481, can I work on this issue?

**Comment by kbrosnan** [comment]
If we change this behavior we need to let the user know that the action is blocked and give them an option to enable video and/or audio for the site. Silently blocking when the user makes an action requesting video/audio would make Firefox look broken.

**Comment by indurs** [comment]
I think we need to check other permissions as well. I blocked the Microphone permission in "Site permissions",  but the app permission dialog is still displayed.

**Comment by Amejia481** [comment]
Thanks @indurs, for interesting on this :) 
Yeah, we will need to check for all permission that required an Android system permissions (Camera and microphone) 

> @Amejia481, can I work on this issue?

Let's wait on UX input on how we should proceed :)

**Comment by indurs** [comment]
Sure.
