### ISSUE TITLE
Add Bookmarks to the search engine menu

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24301]
https://mozilla-hub.atlassian.net/browse/FNXV2-19758

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19858)

**Comment by delia-pop** [comment]
Verified as fixed in the latest Nightly from 05/30 with Google Pixel 6 (Android 12).
![qq](https://user-images.githubusercontent.com/89388888/171010351-275a8d3d-d1b9-43e8-839d-244b4443268f.jpg)
![ss](https://user-images.githubusercontent.com/89388888/171010657-fb7eabc7-3b78-4df5-bdcd-b16f622c7279.JPG)

**Comment by Poopooracoocoo** [comment]
@sflorean Finally! Is there also an operator like there is on desktop? If you take a look at the issues I've opened you'll see my suggestion for it.
