### ISSUE TITLE
[Bug] Qr code scanner shows a distorted/stretched image.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2432]
## Steps to reproduce
Touch search bar on the home screen
Touch scan

### Expected behavior
The image is not distorted and perfectly fits the screen

### Actual behavior
The image is distorted and has black bars to the left and right. Leaving the app and returning triggers the keyboard. While the keyboard is enabled the image is not distorted.

### Device information
* Android device: Galaxy A5 2017 8.0
* Fenix version: 1.0.1919

**Comment by jonalmeida** [comment]
a-c issue: https://github.com/mozilla-mobile/android-components/issues/3149

**Comment by ekager** [comment]
This QR design is also being updated in https://github.com/mozilla-mobile/android-components/issues/4261

**Comment by liuche** [comment]
looks like @mcarare is looking at this in AC!

**Comment by mcarare** [comment]
The overlay change implemented in https://github.com/mozilla-mobile/android-components/issues/4261 does not touch the aspect ratio of the camera preview as it would imply reverting changes that added stability in QR code recognition and scan speed improvements. 

The only change that should be considered is adopting the new `CameraX` API instead of current `Camera2` an implementation that requires extensive QA testing to check it matches at least the previous implementation in terms of device / camera hardware coverage. Deferring that decision to @liuche and removing assigning until a decision can be taken.

Note: It is also worth considering that the QR scanning feature main purpose is to scan QR codes, and although the preview is sometimes distorted, the efficiency in achieving its purpose (scan QR code) should take precedence.
