### ISSUE TITLE
Migrate CollectionViewHolder to Compose

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24333]
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

This refers to:
- [CollectionViewHolder](https://github.com/mozilla-mobile/fenix/blob/f7d317fb4ea76428d4cc9578b76bd9ef6edf8ca0/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionViewHolder.kt) showing an individual collection. (maybe instead of adding individual composables to the homescreen for each collection we could wrap them all in a list)

The compose versions can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

**Comment by Mugurell** [comment]
Migrating this to compose allows us to also simplify the current approach of adding having collections and collection items as separate viewholders on screen. (`CollectionViewHolder` plus one or more `TabInCollectionViewHolder`).

Since [a collection contains a list of tabs](https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollection.kt#L25-L28) the migrated to compose `Collection` can also be an expandable list of `CollectionTabItem`s.
This would allow the expand/collapse animation be handled in the `Collection` composable and as such be smoother (and simpler), not having to sync the rounded corners like it's being done now (but buggy) between `CollectionViewHolder` and `TabInCollectionViewHolder` and also avoid [checking whether one tab item is the same as another](https://github.com/mozilla-mobile/fenix/blob/bfeceb562d9266b21090ec521a8b282fdf3756df/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt#L132-L134), a cumbersome check that is again buggy, all these seen in the following recording:

https://user-images.githubusercontent.com/11428869/160443340-70f3ea82-22c4-4000-85db-93d0f5089581.mp4

cc @gabrielluong

**Comment by gabrielluong** [comment]
I would prefer to see the migration to use a `LazyColumn` in https://github.com/mozilla-mobile/fenix/issues/24316. I think we want an incremental approach just focus on the CollectionViewHolder which only contains the expandable header first to evaluate what is the extent of UI test failures and how do we coordinate with the release schedule and QA testing team to mitigate risk. Converting CollectionViewHolder will already include quite a bit of functionality - share, menu, expand. 

This is not to say we shouldn't convert everything to Compose, but to do it in reasonable steps so we can review the code more easily and evaluate the risk.

**Comment by Mugurell** [comment]
@ QA: This was migrated to Compose but should look and behave the same as before.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed with the latest Nightly 102.0a1 (2022-05-18T17:12:12.001240).
Devices used:

Samsung Galaxy Tab S3 (Android 9).
Google Pixel 4 (Android 12).
