### ISSUE TITLE
Downloading files with the same name overwrites the old file

### ISSUE THREAD

**Issue by vaaas** [mozilla-mobile/fenix#24346]
### Steps to reproduce

1. Download a file, for example a picture named `001.jpg`
2. Move the file to a different folder. For example, I used [Simple Gallery](https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/) 
3. Download another file with the exact same name, in this case `001.jpg`

### Expected behaviour

The new file is saved in the Downloads folder. The original file is untouched.

### Actual behaviour

The original file is overwritten by the new file, silently clobbering user data.

### Device name

Moto G100

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19902)

**Comment by LaviniaL99** [comment]
Hello @vaaas 

Thanks for your report!

I retested the above flow on the latest Nightly build (100.0a1) and latest RC build (98.3.0) and i was able to reproduce the issue.

**Device used:**
- Samsung S10E - Android 10

**Comment by vaaas** [comment]
Because similar issues have been reported (and resolved) in the past, would it be possible to add a test to detect future regressions? IIRC, similar issues have been resolved twice.

**Comment by LaviniaL99** [comment]
@vaaas Yes, we will take it into consideration.

Thanks!

**Comment by xNul** [comment]
@LaviniaL99 Is there any update to this? It's a pretty significant bug and I have had many files overwritten because I didn't know about this. Now, I copy and paste URLs to Chrome before downloading and this annoyance might be enough to push me back.

**Comment by fice-t** [comment]
I can't reproduce this bug on the current Nightly on Android 12: the original file in the new location remained untouched.

**Comment by xNul** [comment]
@fice-t I just updated to the latest version of Nightly on Android 13 and was able to reproduce.

Steps:
1. Take a file you have downloaded (File A) and rename it to have the same name as the file that will be downloaded (File B)
2. Move File A out of the downloads folder into another folder (I created a new folder in the downloads folder and moved it there)
3. Download File B
4. Check File A and it will now have the contents of File B. The download overwrote an existing file.

**Comment by fice-t** [comment]
Sorry, I still can't seem to reproduce this on my physical device (A12 One UI 4.1) or emulators (A11/A13 Pixel OS) using those steps.

Perhaps you could include URLs for the files used and a screen recording?

**Comment by xNul** [comment]
@fice-t Here I've made a screen recording. Fresh install of Firefox Nightly, Pixel 3, Android 12. You can see me download sample.pdf, move it to another folder, rename it to dummy.pdf, and download dummy.pdf. The downloaded dummy.pdf overwrites the sample.pdf that was renamed to dummy.pdf and placed in the other folder.

https://user-images.githubusercontent.com/894305/197297327-5c196cc0-8101-49dc-9ac4-899ba812d2e1.mp4

**Comment by fice-t** [comment]
@xNul Sorry for the delay in responding.

I was able to reproduce this, but **_only_** with the file manager that you used in the screen recording: Mixplorer. I could not reproduce this using the default Google/Samsung file managers or the open-source Amaze file manager.

Chrome+Mixplorer combo seems to work, though I'm not sure why. Just before downloading `dummy.pdf`, the current filesystem tree under `/sdcard/Download` according to `adb` is simply: `New folder/dummy.pdf`, yet Chrome detects that there is going to be a rename (?) and downloads `dummy.pdf` as `dummy (1).pdf` into `Download`. This occurs even when `sample.pdf` is downloaded outside of Chrome (??).

My guess at this point: there exists a bug in Mixplorer and Chrome has a workaround for it (which Firefox should adopt for robustness).

@xNul (and @vaaas if applicable) Would you be willing to test this with other file managers to see if this is isolated to Mixplorer?

**Comment by fice-t** [comment]
Whoops, I forgot about @vaaas mentioning Simple Gallery. I can also confirm the bug using Simple File manager (which uses the same file-handling backend AFAIU). So that's at least 2 that don't work. There's still a decent chance of this being a bug on their ends, but still Firefox should work nicely with such apps.

**Comment by fice-t** [comment]
This only happens when using the Scoped Storage code path, so I figure it's a Uri/MediaStore-based bug.

Debugging [`useFileStreamScopedStorage`](https://github.com/mozilla-mobile/firefox-android/blob/883d71e28e651eb0f67ccf76adc3f39a15dc57e6/android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L887) I've found that with working file managers (e.g. Google/Samsung defaults) [using the recipe provided above](https://github.com/mozilla-mobile/fenix/issues/24346#issuecomment-1287495717):

| | file path | `queryDownloadMediaStore(applicationContext, download)` |
| ----| ---------| ---------------|
| **sample** | /storage/emulated/0/Download/.pending-1668009691-sample.pdf | `null` |
| **dummy** | /storage/emulated/0/Download/.pending-1668009743-dummy.pdf | `null` |

With broken file managers (e.g. Mixplorer, Simple File Manager):

| | file path | `queryDownloadMediaStore(applicationContext, download)` |
| ----| ---------| ---------------|
| **sample** | /storage/emulated/0/Download/.pending-1668009568-sample.pdf | `null` |
| **dummy** | /storage/emulated/0/Download/New folder/dummy.pdf  | non-`null` content URI (no clash with previous URI) |

The file path was found via:

<details>
<summary>file path code</summary>

```kotlin
    private fun getFilePathFromUri(resolver: ContentResolver, uri: Uri): String? {
        return resolver.query(uri, null, null, null, null)?.use {
            val index = it.getColumnIndex(MediaStore.Images.Media.DATA)
            it.moveToFirst()
            it.getString(index)
        }
    }
```
</details>

CC @Amejia481 @csadilek any ideas?

**Comment by nbmrjuhneibkr** [comment]
I'm also having this issue. Previously downloaded file gets overwritten _even if I move it to a different folder._ I can reproduce the issue consistently by following these steps:
1. Download **app-release.apk** from https://github.com/XiangRongLin/NewPipe-preuinified/releases (all releases of this app have the same file name).
2. Move **app-release.apk** from **/storage/emulated/0/Download/** to **/storage/emulated/0/APK/** with a file manager.
3. Download any of the **app-release.apk** files from the same page again.
4. Instead of being saved to **/storage/emulated/0/Download/** it will appear in **/storage/emulated/0/APK/** - overwriting existing file.

Android 13, Google Pixel
File managers: Solid Explorer, Google Files

**Comment by fice-t** [comment]
I can reproduce with the above steps as well with Google Files but not with the builtin Google file manager (`com.android.documentsui` I believe), so it's likely the same root issue.

**Comment by fice-t** [comment]
CC @Amejia481 @csadilek Why does [`useFileStreamScopedStorage`](https://github.com/mozilla-mobile/firefox-android/blob/883d71e28e651eb0f67ccf76adc3f39a15dc57e6/android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L887) try to use `queryDownloadMediaStore` if it returns non-null? So far I've only seen it return non-null for files that already exist, so opening its backing file results in overwriting the file.

There is a disconnect here between constructing the unique filename in `useFileStream` (which does not use scoped storage or the MediaStore) and then using it later in scoped-storage code. I think it would make sense to create a separate `uniqueFileNameScopedStorage` utility that uses code similar to `queryDownloadMediaStore`, and then use it in `useFileStreamScopedStorage` instead of the single query. WDYT?

**Comment by TheRealPizzamampf** [comment]
I can confirm this bug for current Android (V13, patchlevel 2022-11-05) on Google Pixel using current Firefox (107.1.0).
It doesn't matter if I move the downloaded file with "Google Files" or "Totalcommander". Only renaming or copying (instead of moving) the file prevents an unwanted overwrite.

If you need someone to test, I'm happy to help.

**Comment by siddhantkumarupmanyu** [comment]
it still exists. samsung file browser. android 13, s22 ultra. firefox nighty (110.0a1).
and idk, how many files have overwritten. issue is its not even consistent. many times it does overwrite when i don't want it to. and when expecting it doesn't. its not just firefox to blame here. but Andros saf, scoped storage and all that nasty stuff Googles putting. make life hell for developers as well as users.

someone mentioned that it happens only with moving and not with copying.
i really don't want switch, even if it means to copy and then delete instead of moving...

second issue is, to fix this, clear old indexes or something, somebody mentioned to clear the data.
i want to but firefox does not support syncing collections. this makes more hassle...

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812788

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
