### ISSUE TITLE
Addon forever asking for new permission

### ISSUE THREAD

**Issue by nu111** [mozilla-mobile/fenix#24546]
### What is the user problem or growth opportunity you want to see solved?
Addon asks for new permission, if I refuse, Firefox keeps asking me the same thing over and over.

I would like to say "don't ask again until the next addon version"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20021)

**Comment by Amejia481** [comment]
Thanks for reporting.
@nu111  could you provide more info about about the add-on?

**Comment by nu111** [comment]
This is the [addon](https://addons.mozilla.org/en-US/firefox/addon/search_by_image/) and this is the [github issue about the new permission](https://github.com/dessant/search-by-image/issues/114)

**Comment by Amejia481** [comment]
Thanks for the clarification!

**Comment by sflorean** [comment]
@Amejia481 I was able to reproduce this on Pixel 4XL (Android 12).
Steps to reproduce:
1. Install Search by Image addon. 
2. Wait for an addon update.

Actual results: A Firefox Nightly notification is displayed asking for permissions.
- tapping on allow does nothing, the notification is displayed again.
- tapping on deny, does nothing, the notification is displayed again.
- tapping on notification, the homepage is displayed. 

<img src="https://user-images.githubusercontent.com/58466444/161115911-54ce680d-fb99-411e-9b0d-acc1b5b1a2e0.png" width="300" height="550" />

**Comment by dessant** [comment]
Hi, maintainer here. So version 4.7.0 is not installed even if you tap Allow, or is the extension update installed, and the bug only affects the notification?

**Comment by Amejia481** [comment]
> Hi, maintainer here. So version 4.7.0 is not installed even if you tap Allow, or is the extension update installed, and the bug only affects the notification?

I have to do a further research, but maybe it could be the new permission API is not support on Firefox for Android and we are failing to update.

**Comment by sflorean** [comment]
The version is 4.7.0, last updated on March 30 and my guess is that only the notification is affected. This was displaed several times, even if "Deny" was taped.

**Comment by Amejia481** [comment]
> @sflorean could you please provide which build version of Android are using?

Is the issue always reprodusable ?

**Comment by Mugurell** [comment]
@Amejia481 Thought this may have something to do with clicking web notifications that I'm working on in https://github.com/mozilla-mobile/android-components/issues/7477 so I looked a bit into it.

Tried installing 4.6.0 to actually test the update but that didn't simply work.

Looking at the code is seems like this bug is indeed possible.
[Here](https://github.com/mozilla-mobile/android-components/blob/5eca21bb8e115f00dbfa1d8a635ab5830dcd6b85/components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt#L215-L219) is decided whether to show the notification or not.
Looks like we'll not show the notification if 
     - there are no new permissions in the update (in this case this check will be false every time) and
     - that update was previously allowed
     
If my understanding above is correct then because the update adds new permissions we'd indeed show the notification again.
In the "Deny" case because that [just removes the notification](https://github.com/mozilla-mobile/android-components/blob/5eca21bb8e115f00dbfa1d8a635ab5830dcd6b85/components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt#L435-L437).
In the "Allow" case maybe the initially allowed update didn't work and then the 4.7.0 update is tried again?
@sflorean If the notification still appears although you allowed the update I'm curious what is the currently installed version.

And coming to the notification click, the notification is a native one that we set [to indeed only open the app](https://github.com/mozilla-mobile/android-components/blob/5eca21bb8e115f00dbfa1d8a635ab5830dcd6b85/components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt#L324-L332). 
Maybe opening addon's homepage url would be just a bit nicer?

**Comment by sflorean** [comment]
@Amejia481 @Mugurell 
- the build was Nightly 3/31
- the version of the addon is 4.7.0 after I tapped on Allow
- I didn't received any notifications today, after  I tapped on Allow, maybe the notification is displayed repeatedly only when deny is used/ or the notification is tapped. 
- - this means that this scenario "_tapping on allow does nothing, the notification is displayed again."_ might not be valid after all, sorry for confusion there. 

I will keep an eye to see if it is displayed again.
