### ISSUE TITLE
Darker background images for new tabs?

### ISSUE THREAD

**Issue by KopfKrieg** [mozilla-mobile/fenix#24586]
In addition to #24189 we not only need the ability to set custom backgrounds, but also darker default backgrounds. The current choices are very bright, and the (white) text on those light backgrounds is barely readable.

**Comment by delia-pop** [comment]
Hello @KopfKrieg ,

Thank you for your report! Please note that I marked the ticket https://github.com/mozilla-mobile/fenix/issues/24189 as feature request. Since your ticket and suggestion is mentioned over there, you can follow up on the discussions over this topic. I will close this ticket for now.
