### ISSUE TITLE
[Meta] SendTab Feature

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#246]
Scope: Support Send Tab functionality: the ability to send a page to your other FxA-Connected browsers. (Firefox iOS, Android and Desktop). The engineering work also includes _receiving_ tabs from your other devices 

### Why/User Benefit/User Problem
* As a user, I want to share pages on the web to my other Fx connected devices so I can easily find them from the device I am using.

### What / Requirements
A-C board: https://github.com/orgs/mozilla-mobile/projects/19

* User needs to be signed into their FxA account in order to send a tab to their connected devices.
* The share function must have an accessible label.

### Acceptance Criteria (how do I know when I’m done?)
* Linked Devices: synced devices
* via Fenix, the user is able to tap on the share function and select a connected device to share/send a tab to
* if the user has not connected any devices show these action states

### Out of scope of MVP?
* Devices linked via QR code
* Nearby Devices: on your network (https://github.com/mozilla-mobile/fenix/issues/641)

<img src=https://user-images.githubusercontent.com/128755/57334721-8bb60500-70ee-11e9-92fb-bca32133f5ff.png width=200 />

**Comment by st3fan** [comment]
This ticket is about the integration of the components. The component work is sized in the A-C repository.

**Comment by st3fan** [comment]
@bbinto please take a look at the 'out of scope' section

**Comment by bbinto** [comment]
Need to check again with @jdragojevic when this can be made available, this might become a "could"

**Comment by jdragojevic** [comment]
@bbinto In terms of what we are currently working towards with respect to the delivery in Fenix, I would recommend the ticket description be updated to reflect this content, and you can reference the [Send Tab project plan](https://docs.google.com/document/d/1lfxGSeJXB1U0nN3POA8e6U5Z-s1FkL692GwP2G2RTis/edit#) for more details.

cc @st3fan 

### Why/User Benefit/User Problem

Share tool: Share information on the web

    * As a user, I want to share pages on the web to my other devices connected via my Firefox Account so I can easily find them from the device I am using.
 
### What / Requirements

User needs to be signed into their FxA account in order to send a tab to their connected devies.

The share function (e.g., button) must be in a color that has high contrast with its background.

The share function must have an accessible label.

### Acceptance Criteria (how do I know when I’m done?)

    * via Fenix, the user is able to click the share function and select a connected device to share the website.
    * if the user has not connected any devices the action is... tbd (inactive? hidden? prompts to connect?)


### Unclear - out of scope of MVP?

 * Any type of sharing websites that do not require a device linked via a Firefox Account.

**Comment by bifleming** [comment]
@bbinto @vesta0 I'm confused about this Meta.  There are no stories for the Fenix team to do?

**Comment by vesta0** [comment]
@bifleming I believe this hasn't been broken down since we are still waiting for Applications Services but here are the mocks: https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357472094

**Comment by bifleming** [comment]
@vesta0 ah, I see. And this is scoped for MVP?  If so, we really need to get the stories in and sized asap.

**Comment by jdragojevic** [comment]
The application services team current status for send-tab is:

_Send tab got merged on the Rust side and is being integrated by Android Components team._

According to the [SendTab project board](https://github.com/orgs/mozilla-mobile/projects/19) it's owned by @jonalmeida . I'm aware that @grigoryk and @eoger have been communicating around the UI. 

Correct me if I'm wrong, I don't believe this work is currently blocked and it seems well defined @bifleming @vesta0

**Comment by vesta0** [comment]
@jdragojevic thank you for the update!

@bifleming please see #331 for user story.

**Comment by jonalmeida** [comment]
I've also been working with @jrconlin to ensure the push side works end-to-end.

**Comment by jonalmeida** [comment]
Send Tab with Push support is ready for an MVP release.

cc: @vesta0 and @liuche for releasing (i.e. removing feature flag).

**Comment by liuche** [comment]
Send tab is in the product.
