### ISSUE TITLE
[Bug]: Clicking What's New in the Hebrew localized version of Fenix goes to a 404 page

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/fenix#24688]
### Steps to reproduce

1. Use the Hebrew localized version of Fenix
2. Open the main menu
3. Click What's New

### Expected behaviour

https://support.mozilla.org/he/kb/whats-new-firefox-android is opened

### Actual behaviour

https://support.mozilla.org/he/iw-IL/kb/whats-new-firefox-android?as=u&utm_source=inproduct is opened

See the difference in the language codes. iw-IL is the "old" language code of Hebrew.

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1

**Comment by kelimuttu** [comment]
There's somehow a mismatch between locale code from the inproduct link to the one we use in SUMO for Hebrew. Not sure if this is on product or SUMO's part.

**Comment by kbrosnan** [comment]
Informed the support team. Do not believe that this is something for the Fenix team to address.

**Comment by ItielMaN** [comment]
@kbrosnan For tracking purposes, is there a link somewhere for that discussion with the support team?

**Comment by abbyparise** [comment]
@kbrosnan @ItielMaN I've looped in our SUMO engineer to look into this and I'll report back when I have an update.

**Comment by youn1223** [comment]
11

**Comment by ItielMaN** [comment]
@abbyparise Any news since then? This is still an issue.

**Comment by escattone** [comment]
This seems to be due to the way that Java handles the three locales that have legacy codes, Hebrew (`iw`), Indonesian (`in`), and Yiddish (`ji`) (see https://developer.android.com/reference/java/util/Locale.html#legacy-language-codes). For example, it seems to map `he` to `iw` for backwards compatibility in the `Locale` constructor.

In any case, we can see that Fenix uses the SUMO "in-product" link https://support.mozilla.org/1/mobile/*/*/iw-IL/whats-new-firefox-android instead of https://support.mozilla.org/1/mobile/*/*/he/whats-new-firefox-android.

Here's an example request from the SUMO production logs on Sept. 26 (in this case requesting the topic `whats-new-firefox-preview` instead of `whats-new-firefox-android`, but it's the same issue):

```
10.141.190.4 - - [26/Sep/2022:04:17:55 -0700] "GET /1/mobile/105.1.0/Android/iw-IL/whats-new-firefox-preview HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Android 12; Mobile; rv:105.0) Gecko/105.0 Firefox/105.0" -"
```

I suppose that Fenix could be updated to avoid this, and perhaps later versions of Java will no longer do this, but it's easy for SUMO to fallback to `he` when `iw` or `iw-IL` is used, and `id` when `in` is used. We don't support Yiddish at all, so there's no sense in falling back to `yi` when using `ji`.

https://github.com/mozilla/kitsune/pull/5241

**Comment by kelimuttu** [comment]
Thanks for looking into this and for the PR, @escattone
