### ISSUE TITLE
[Bug] "Quit" menu option only shows if "Delete browser data on quit" is enabled

### ISSUE THREAD

**Issue by VikePetersson** [mozilla-mobile/fenix#24726]
Firefox for Android v. 99.1.1
Hi!
When i turn off "Delete browser data on quit", the "Quit" option from the
main menu disappears.
Any suggestions?
Thanks!

**Comment by Mugurell** [comment]
This is the expected behavior as it was implemented in https://github.com/mozilla-mobile/fenix/issues/3700.
The "Quit" option appears in the menu for allowing users to easily clear browsing data.
As for other apps users can leave the application by pressing back / home / recent apps button.
What are you trying to achieve?

**Comment by VikePetersson** [comment]
Multumesc!
If I made a wrong assumption 😊
Thank you!
