### ISSUE TITLE
Open recently closed tabs

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2486]
UX spec: https://share.goabstract.com/e43eb5b0-93d8-4fbc-bd93-c88b633a5979?mode=design&sha=168d3adc4b4cebd5f58bcebf1e564f589a5b874a

### Why/User Benefit/User Problem
At the moment there is only the snackbar immediately after closing a tab, but if you accidentally dismiss it or take too long to decide that you didn't actually want to close the tab, there's no way to restore it afterwards.

### What/Requirements
A new section for the library?

### Acceptance Criteria (how do I know when I’m done?)
I can view the last few (10/15/...?) tabs I've closed and restore them. Restoring a tab should restore its state as completely as possibly (i.e. similar to session restoring) and remove the respective tab from the list of recently closed tabs.

**Comment by yoasif** [comment]
"reopen closed tab" might be a way to do this in the home "open tabs" menu. 

Samsung Internet does this: https://github.com/mozilla-mobile/fenix/issues/1694#issuecomment-488438466

**Comment by ekager** [comment]
There is already a History section in the Library doesn't this work about the same way?

**Comment by buttercookie42** [comment]
@yoasif How does that work - is that actually a list of tabs, or just a menu item that is basically the equivalent of pressing Ctrl + Shift + T, i.e. it simply restores the most recently closed tab. For that use case, we already sort of have the snack bar, and beyond that I'd prefer also being able to chose *which* tab to restore.

@ekager No, history only shows the individual pages I've been visiting, but has nothing about *tabs*.

**Comment by yoasif** [comment]
@buttercookie42 In my brief testing, it reopens the last tab, but  the menu item remains, so the user can reopen the next recently opened tab until Samsung Internet doesn't know about previously closed tabs. 

There is no option to pick from a list of recently closed tabs - so it is very much like control-shift-t

**Comment by yoasif** [comment]
FWIW, Fennec has "recently closed" tabs inside of history, which feels closer to what you want @buttercookie42.

![signal-attachment-2019-05-14-172037](https://user-images.githubusercontent.com/152493/57733077-a3503900-766c-11e9-89ef-16725500d8fd.png)

This feature restores *tabs*, not pages (unlike history in Fenix).

**Comment by buttercookie42** [comment]
Exactly, that's the angle I'm coming from.

**Comment by buttercookie42** [comment]
> A new section for the library?

Although thinking some more about it, the library in Fenix is currently a bit more cumbersome to reach than in Fennec, where entering the URL bar's edit mode was enough to load the home panels.

**Comment by yoasif** [comment]
Vivaldi has a pretty nice way of doing this. 

They integrate a trash tab in their tab switcher, very much like the "open tabs vs. private tabs" tab switcher in Fennec. The recently closed tabs is a very basic list of tabs (basic Chromium), but it gets the job done in a way that is not currently possible in Fenix. 

Bromite makes it a top level menu in their meatball menu, and Opera hides it behind a meatball menu inside of their tab switcher. 

I think that the Vivaldi way is actually better than the Fennec way, since history isn't close to the tab switcher, and requires more work to get to. 

Vivaldi's tab switcher - normal, private, synced? and recently closed.

![signal-attachment-2020-01-24-010407](https://user-images.githubusercontent.com/152493/73047967-8ef04d00-3e45-11ea-8bd4-2715571357be.png)

Fennec's tab switcher: normal and private:

![signal-attachment-2020-01-24-010440](https://user-images.githubusercontent.com/152493/73048013-b0513900-3e45-11ea-94fa-82a1577f5a86.png)

**Comment by madb1lly** [comment]
Now I'm using Fenix Nightly as a daily driver I find the absence of the ability to reopen recently closed tabs feature quite frustrating, especially as this already exists in Fennec.

**Comment by vesta0** [comment]
@yoasif @madb1lly @buttercookie42 thanks for the great suggestions!

Can you help me think through common use cases of this? What are the different scenarios where you would need to go back and open your recently closed tabs? Is it just in case of accidentally closing a tab (as stated in the issue description above) or are there other use cases? Is it ever about wanting to keep your homescreen clean without having to actively save your tabs as a collection?

**Comment by yoasif** [comment]
@vesta0 I think that there is possibly an interesting way that this feature would interact with https://github.com/mozilla-mobile/fenix/issues/5865.

Right now, Fenix users must "Quit" the app in order to close open tabs.

If there was an easy way to restore their tabs after they were closed (if https://github.com/mozilla-mobile/fenix/issues/5865 were to be implemented) the risk of real data loss could be mitigated. 

Just one additional idea, but I think that the accidentally closed tab is valuable enough to implement alone - every other browser that I can think of (besides Focus) has this feature, and history is clearly not the same thing as tab restoration. 

As far as how it relates to collections - I think https://github.com/mozilla-mobile/fenix/issues/5652 continues to be relevant, and there isn't really much overlap between collections and reopening closed tabs - for example, I don't think closed tabs ought to "belong" to collections - because then I would have to reopen a collection to get access to a closed tab. 

The same would apply to history as well, FWIW -- it would be strange (imo) if opening a new collection modified my history such that history was a property of the collection, and that each collection had its own history and set of closed tabs.

I haven't used collections actively in a while (due to  https://github.com/mozilla-mobile/fenix/issues/5652) and more specifically because my tab list would end up being twice as large each time I opened a collection, but IIRC, collections *do* save "tabs" (and not links/bookmarks), so for less ephemeral tab storage, they certainly fit the bill, but this bug really seems to be more about the "forgotten" or accidental use cases, not of a user actively "saving" a tab to a recently closed tabs list. 

I know that on desktop at least, there is a limit to the amount of windows or tabs that can be restored - I have heard that this may actually be unlimited in some way in Chrome, but I haven't done the testing to verify that - in any case, I personally wouldn't use my browser for a few weeks and try to "reopen" a tab from a few weeks ago from this feature - I would definitely have preferred to save that in a collection.

**Comment by buttercookie42** [comment]
For me it's definitively about either having accidentally closed a tab but having missed the opportunity to use the immediate undo popup, or about tabs that I've deliberately closed because I thought I didn't need them any more, but then soon afterwards it turns out that there actually was something in that tab that I still require.

Especially the latter case is also the reason I'd prefer a **list** of closed tabs, because it isn't always the last tab I closed that I want to reopen, so I'd rather be able to restore the correct tab immediately instead of having to reopen them all one by one until hitting the correct one (though on Desktop with a keyboard the Ctrl + Shift + T shortcut is still handy regardless).

**Comment by madb1lly** [comment]
Hi @vesta0,
I'm not sure I made any suggestions, but thanks!

My use cases are the same as @buttercookie42 describes. I don't recall ever wanting to open a recently closed tab from a previous session, only the current session.

Cheers 🙂

**Comment by tallus** [comment]
This has accessibility implications. I often end up accidentally closing tabs due to problems with my fine motor skills (sometimes multiple tabs). For the same reason I find it hard to use the popup. In Fennec this was by far the most used section of history for me.

**Comment by regs01** [comment]
What we need is Undo closed tab in Tabs context menu. same as on desktop. And that will act same way as on desktop. So as Duplicate tabs and Close all other tabs. This menu has just 3 points, so there is plenty room for new items.
![Screenshot_20200831_055749_org mozilla firefox](https://user-images.githubusercontent.com/10468217/91678742-03fbd180-eb4f-11ea-8923-ae6f204f79a6.jpg)

**Comment by ekager** [comment]
Please file new issues for new feature requests with the info filled out!

**Comment by madb1lly** [comment]
Hello @ekager,
Just to clarify, the OP does appear to have followed the template, so are you replying directly to @regs01?
Thanks 🙂

**Comment by ekager** [comment]
QA please test: Behavior is to save the last closed 5 tabs in the recently closed tab menu with the back state ready to be restored. On restoration they are removed from the recently closed list. Clearing history will remove these tabs as well.

@topotropic let me know if you're happy with 5 saved or want more I couldn't find the discussions we had about it anymore 🤔 

Known issue: When a user presses the undo snackbar after deletion, the tab will still appear in recently closed (this needs the Undo function to be moved into AC which will happen at a later date)

**Comment by Poopooracoocoo** [comment]
personally a feature i find myself wishing for on chromium based browsers (as I had used them mainly for a long time), is for the last 5 tabs to show and for all tabs closed within the last x minutes to show. x could be 10 minutes. :)

**Comment by miDeb** [comment]
Closed private tabs are currently added to the list as well, they should probably be excluded.

**Comment by buttercookie42** [comment]
Desktop has recently closed private tabs for the duration of the current private browsing session for what it's worth, as did Fennec (i.e. closing the last open private clears recently closed private tabs). They should certainly be kept separately, though.

**Comment by ekager** [comment]
Yep that was a bug. We're filtering out private tabs when you "close all" tabs, but not singularly. Filed https://github.com/mozilla-mobile/android-components/issues/8390 and will be fixed by https://github.com/mozilla-mobile/android-components/pull/8391

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/17 and 9/16. Scenarios covered:
- accessing "Recently tabs closed" from tabs tray and History
- number of saved tabs and order
- closing private tabs 
- "Recently tabs closed" menu (open, copy, delete)
- dark and light theme for the page/menu
- deleting all history

I will close this as verified and we will follow separately the known/new issues.

**Comment by Poopooracoocoo** [comment]
does that mean that I should make a new issue about my comment above? @sflorean

**Comment by madb1lly** [comment]
Hi @ekager,

I'm just noting here (as I only just checked it) that Fennec kept track of the last 10 closed tabs and this list also persists between sessions which could be useful if the phone runs out of battery or something.

Cheers 🙂

**Comment by Poopooracoocoo** [comment]
#15503

**Comment by Poopooracoocoo** [comment]
> personally a feature i find myself wishing for on chromium based browsers (as I had used them mainly for a long time), is for the last 5 tabs to show and for all tabs closed within the last x minutes to show. x could be 10 minutes. :)

I did by the way, open #15505 last year

**Comment by madb1lly** [comment]
I find 10 tabs a bit limiting, I often can't find the tab I want. The 25 tabs on desktop is much more helpful, I can only remember not being able to find the tab I want once. I'll raise a new feature request.
Cheers 🙂

**Comment by Atemu** [comment]
Hi, I just accidentally closed >100 tabs and also find 10 tabs to be very limiting and the lack of a "restore all" extremely disappointing.
