### ISSUE TITLE
Ability to reorder tabs

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2487]
### Why/User Benefit/User Problem
Links opened in a new tab seem to appear next to their "parent" tabs in the tab list, which is an improvement over Fennec, but occasionally it would still be nice to further reorder tabs.

### Acceptance Criteria (how do I know when I’m done?)
I can reorder tabs in the tab list by holding and then dragging them.

**Comment by reinhart1010** [comment]
Duplicate: https://groups.google.com/forum/m/#!topic/fenix-nightly/ImcINWPjbB8

**Comment by topotropic** [comment]
@buttercookie42 thanks for your feedback, can you give me some context on when that would be useful to you? Thanks!

**Comment by Dunexus** [comment]
Use case example :

![image](https://user-images.githubusercontent.com/13906248/68945946-eb821c80-07b1-11ea-8177-4db29ecbdcc7.png)

I would like to move the first tab next to the last one because they are about the same topic.

**Comment by madb1lly** [comment]
Good example from @Dunexus. This is my typical use case as well; eventually (in Fenix) I may break out these tabs into their own collection but at this stage I'm not ready for that.

**Comment by Cheap-Skate** [comment]
I would also like to be able to re-arrange tabs, it's a nice feature of Fennec particularly with the "compact tabs" grid view.

**Comment by vesta0** [comment]
We will consider this as a possible solution for #10344

**Comment by madb1lly** [comment]
Hi @vesta0,

It's a different solution for a different problem, not the same solution for a different problem. This feature in this ticket is about reordering tabs - use Fennec again and you will see what we are referring to.

Cheers 🙂

**Comment by kj** [comment]
Can this be reopened? This is very important to me and I can't see how it relates to that issue.

**Comment by lpd-au** [comment]
@vesta0 can you provide a response please. Many users would like the ability to arbitrarily rearrange open tabs, regardless of whether the default position of newly opened tabs is configurable.

**Comment by vesta0** [comment]
Re-opening since there is a lot of support for this feature and adding it to UX triage.

**Comment by Octoton** [comment]
The tab tray selection mode could be used for this.
So that tab are not moved wrongfully

**Comment by elensar** [comment]
After you link all the new issues to this issue with duplicate and this issue is from 2019, I was wondering if this issue is on any road map or if it will die here?

**Comment by RebelLion420** [comment]
Just writing to request this feature be reimplemented, it was possible on the version prior to Firefox Daylight to hold on a tab and reorder them. Thanks for considering

**Comment by Poopooracoocoo** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/8376

**Comment by liuche** [comment]
Let's dupe to #10344

**Comment by Poopooracoocoo** [comment]
so i guess the idea behind closing issues like this is creating more "open ended" issues.

**Comment by cadeyrn** [comment]
@Poopooracoocoo 

> so i guess the idea behind closing issues like this is creating more "open ended" issues.

I don't understand your comment. 🤔 This issue was closed as a duplicate of #10344, as explained in the comment above yours. Since #10344 already has a mockup for the setting it makes sense to dupe this issue to #10344 even if this one is older. There is no point in having multiple issues for one and the same thing.

**Comment by elensar** [comment]
@cadeyrn I think @Poopooracoocoo is right. This ticket was the first one. You have already closed many other tickets because they where duplicated tickets of this one. So the normally right way to do this, would be to close #10344 because this ticked is duplicated to the original one (this one). 

So you have created an open end, for all the other tickets.

**Comment by cadeyrn** [comment]
> I think @Poopooracoocoo is right. This ticket was the first one.

Why do you think that it matters? This is not a competition. 🙄 As I already explained #10344 has already a mockup for the setting to allow manual ordering. That's relevant for the developers. "Fordward duping" is not unusual at all, it happens a lot, not only here but in different projects, too. And it doesn't change anything for the user. For the users it should only be important that something happens and that they know where they can follow if they're interested.

> You have already closed many other tickets

No, I didn't. I am a regular user and don't have the ability to close anything.

> Oh and you also lost all the upvotes and information of this and the child tickets of course.

I don't understand this comment. Nothing is "lost" at all. Especially since all mentioned issues are referenced. It's only one click from #10344 to this issue. You can trust that Mozilla's developers are smart enough to find related discussions and reactions.

**Comment by elensar** [comment]
@cadeyrn sorry I though you where one of the developer or GitHub maintainers. 

You are right if you say that this is no competition 👍 . The point is the history and that every one can follow the "main path". Now you have to switch the ticket to follow every information. This break can be cause, that other developer will miss things or the "new" main thicket will not have all the information ( e. g. all the upvotes). 

That's just some points why you shouldn't switch the main thicket.

Also everyone can ask why his ticket isn't the new main ticket now.

**Comment by Poopooracoocoo** [comment]
I never said that there should be duplicate issues. This issue could have been edited by Mozilla to include mockups. I was thinking that the other issue should have been closed in favour of this one. The word _duplicate_ isn't quite right either. 

And I thought you'd agree with me Soren. Aren't open ended issues what Mozilla wants? It's like "sharing should be easier to access" vs "move share to menu to allow for shortcuts". Why vs how.

And yeah, it's no competition. This is an issue tracker for the devs. It's simply easier to find information in one place, for both users and devs. I would upvote @cadeyrn's comment if I could.

**Comment by madb1lly** [comment]
Hi all,

Maybe the team at Mozilla only edit issues which they create, and that's why they cancelled this one in favour of the other (but the other has been open since May! so why now?)? Anyway, there is still a ticket open therefore the dev team still feel this is an important issue and (reading the other issue) it is clearly not a simple thing to implement.

Warning, off topic moment! ⚠
@cadeyrn I too have thought you might be part of the dev team in the past! But then I noticed you're not tagged as member, just contributor (thanks for your contributions 👏). Maybe people get confused because sometimes you act a bit like the "ticket police", defending the dev's decisions and reprimanding people for posting off-topic (well, here's another chance, I'm getting way off topic now). Maybe it would be simpler to leave the dev's to defend their own decisions, rather than counter the opinion of others and risk a debate that goes off topic. I appreciate the way you sometimes moderate the discussions when they get out of hand, like when you refer to the Mozilla code of conduct, although this does seem to be mainly when someone strongly (too strongly?) expresses their disagreement with your point of view.

I hope you didn't take my comments too harshly, it wasn't my intention, I just wanted to take this opportunity try and explain how things look from the point of view of others (we all need that sometimes, so please feel free to do the same to me if you wish, I won't be offended).

Cheers 🙂

**Comment by cadeyrn** [comment]
> Maybe people get confused because sometimes you act a bit like the "ticket police"

I don't understand what you mean by "police". Finding duplicate issues **helps** the team members to focus on the more important things because they don't have to do it.

> defending the dev's decisions

That's not true at all. I always represent my **personal opinions**. Sometimes I share the opinion of the team, sometimes not. You can find more than enough examples for both here on GitHub. 🙄 

> although this does seem to be mainly when someone strongly (too strongly?) expresses their disagreement with your point of view.

Than't another lie and not true at all. 😡

> I hope you didn't take my comments too harshly, it wasn't my intention

If it's not your intention, you shouldn't do it. Honestly, if you want to talk about me you should contact me. A discussion **about a user** doesn't belong to the issues tracker of Firefox. You call it "off-topic", for me it's "offending" because you spread things about me that are not true at all… 🙄

**Comment by madb1lly** [comment]
Hi @cadeyrn,

I presume you've reported or blocked me, which is why I can't tag you properly. Given that you're offended by what I wrote I think that's probably reasonable. Clearly we've had a misunderstanding. I certainly didn't intentionally offend you, I wrote what I wrote with good intention, but since you are offended I'll remove it.

Cheers 🙂

**Comment by liuche** [comment]
Hey everyone, I'm sorry to have caused some conflict, and so I'll explain a little more here.

I really appreciate all of you taking the time to link to dupe issues. Having a single issue makes it clear where to look. If I'm searching for an issue to update and there are 3-10 issues, it wastes a lot of time to figure out which one to update (especially if they are named similarly - Github search doesn't always return the best results). I close them so others won't be confused, and can follow the chain.

Sometimes the "one" issue that remains is the earliest issue, or maybe it's an issue that the product manager filed with specific criteria, or maybe it's the issue with some helpful screenshots, etc. If there are especially helpful STR in an issue that I'm closing, I will often copy them to the remaining issue.

I understand that it's a pain to have to move around following a chain of issues - but we do link to the issue numbers so that chain isn't broken.

I actually came across this issue when searching for "reorder tabs", so I figured that for anyone following this issue, they would appreciate seeing the issue that we're actually pulling into a sprint, where the work will be happening!

Please also note that there are 2.5k+ (open!) issues in this repo, and there are 4-5 of us who are handling a large load of the triaging (while doing other work). I appreciate y'all sharing your opinions and caring about Firefox and making it better - this is the process that seems to work for us. ❤️

**Comment by braham-snyder** [comment]
Just a note that if you've given this closed issue a thumbs up, you might want to also thumbs up its replacement issue #10344 so that devs see how many people want this feature re-implemented
