### ISSUE TITLE
Investigate why ublock origin loads first page faster after changing "Delete Browsing data on quit" settings

### ISSUE THREAD

**Issue by rsssxd** [mozilla-mobile/fenix#24871]
Using ad blockers like the uBlock Origin plugin slows down Fenix's startup speed.

I made some adjustments to "delete browsing data" when exiting. When I press the exit button and close Fenix ​​and open it again, websites load faster.

https://user-images.githubusercontent.com/60405617/164035554-109b85f6-13b7-48f8-a311-d17442e186ca.mp4

There are no settings

https://user-images.githubusercontent.com/60405617/164035633-a0652334-0c05-4600-b034-4a162107f8e6.mp4

Device: Mi 9T LineageOS - Android 10 

Firefox Nightly 100

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20220)

**Comment by rsssxd** [comment]
![Screenshot_20220419-180119_Firefox_Nightly](https://user-images.githubusercontent.com/60405617/164036362-6205f432-b644-4db1-8011-98000aca46b0.png)

**Comment by rsssxd** [comment]
Note: All uBlock filters and cosmetic filtering are active except language packs.

**Comment by mcomella** [comment]
@rsssxd Would you be able to provide two performance profiles of the behavior? One profile should include your changes and the other profile should not. You can find instructions to take performance profiles here: https://profiler.firefox.com/docs/#/./guide-remote-profiling

Triage: we've previously spent a lot of time investigating slow start ups with ublock origin enabled – see https://github.com/mozilla-mobile/fenix/issues/8251 and the linked issues – and discovered there was nothing we could do and that the responsibility was on ublock to make it faster. However, it's surprising that performance improves by deleting some browsing data on exit (perhaps some APIs ublock calls can return immediately instead of blocking for a disk read) so we should at least look at the profiles to see if there's a way all users can benefit from these changes.

**Comment by mcomella** [comment]
Triage: since we don't have profiles, we can only speculate. We speculate that there is no benefit to users without ublock (since things are already pretty fast for them) so this only impacts users with ublock installed. It seems like identifying the root cause has a low probability of improving start up performance (because it's likely caused by callbacks that can return instantly because the history/bookmarks/etc. DB don't need to do any reads since they were just deleted) so we're going to mark the investigation low priority.
