### ISSUE TITLE
1360929d-f657-484c-85d3-f2541e7a2dd6 <native crash> ---- <native crash>

### ISSUE THREAD

**Issue by Ansarmughal99** [mozilla-mobile/fenix#24983]
1360929d-f657-484c-85d3-f2541e7a2dd6
<native crash>
----
<native crash>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20296)

**Comment by cpeterso** [comment]
@Ansarmughal99 - `1360929d-f657-484c-85d3-f2541e7a2dd6` doesn't seem to be a valid crash ID. I don't see a crash report at URL https://crash-stats.mozilla.org/report/index/1360929d-f657-484c-85d3-f2541e7a2dd6

Can you share the page URL that opens after you click the "Socorro" link in your Firefox's Settings > About Firefox > Crashes page?

**Comment by Ansarmughal99** [comment]
https://crash-stats.mozilla.org/report/index/1f70e1d6-099e-460a-9b72-fcf6c0220427

https://crash-stats.mozilla.org/report/index/0fc7d20f-9db2-4308-b9f3-0e00a0220427

**Comment by cpeterso** [comment]
Thanks. Unfortunately, the crash stacks don't look very useful because they point to random code in an Android system library.

Crash report: https://crash-stats.mozilla.org/report/index/1f70e1d6-099e-460a-9b72-fcf6c0220427

Reason: ```SIGSEGV / SEGV_MAPERR```

Top 7 frames of crashing thread:
```
0 libandroid.so libandroid.so@0x000000000001f50c 
1 libandroid.so libandroid.so@0x000000000001f504 
2 libandroid.so libandroid.so@0x000000000001db7c 
3 libandroid.so libandroid.so@0x000000000001da0c 
4 libmozglue.so arena_t::Malloc memory/build/mozjemalloc.cpp:3057
5 None @0x746e6f662f6d6570 
6 libmozglue.so moz_xmalloc memory/mozalloc/mozalloc.cpp:52
```

Both crash reports are parent process crashes on startup. Uptime is just 1 second.

Fenix version is Release channel 100.1.0.

Interesting that Available Page File is 0 bytes. I looked at some unrelated Android crash reports and about half of them have Available Page File of 0 bytes, so I guess that is normal for some Android configurations.
