### ISSUE TITLE
As a user I want to be made aware of the Mozilla Privacy Notice when I install Fenix

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#2517]
## User Story
As a user I want to be notified of the Mozilla Privacy Notice when I install Fenix. I want to be able to read the privacy notice directly or be able to tap a button or link to open it up in a new tab.

### Acceptance Criteria
* The first time Fenix is installed (a _new_ install, not an upgrade/update) the privacy notice or a link to the privacy notice is clearly visible.

**Comment by Amejia481** [comment]
Related pr: on RB https://github.com/mozilla-mobile/reference-browser/pull/371

**Comment by sarentz** [comment]
Couple of options have been offered:

 - Open a new tab that contains the privacy notice
 - Show a notification (see previous comment)
 - Include it in the onboarding UI

None of these are challenging - my personal preference would be either a Notification or the Onboarding because I think opening a new tab is too confusing. I think we want people to start their browsing experience on the Home Screen?

cc @lime124

**Comment by vesta0** [comment]
@st3fan this is currently part of onboarding.

![image](https://user-images.githubusercontent.com/42752644/57795224-6c812e00-7713-11e9-81ed-1529a48de4e8.png)

**Comment by sarentz** [comment]
Fantastic that looks great.

**Comment by vesta0** [comment]
Part of onboarding flow
