### ISSUE TITLE
[Bug]: QR code is not recognized as a web address

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#25208]
### Steps to reproduce

1. Open Firefox, and use the QR code scanner button above the URL entry bar on the new tab page
2. Scan attached QR code
![DSC_0605](https://user-images.githubusercontent.com/485789/167862144-77707c65-3bba-4066-885a-7e1fa5fce213.JPG)

### Expected behaviour

Web page should open. The QR code is scanned by Vivaldi browser just fine. The [online decoder](https://zxing.org/w/decode.jspx) likewise decodes it to HTTPS://WWW.PROXYVOTE.COM/07379106402724405?&src=qr just fine.

### Actual behaviour

Firefox throws up a dialog saying "web address not valid"

### Device name

Sony Xperia XZ1C

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

100.1.1

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue and can confirm it occurs on RC 100.1.2 but not on Nightly 2022-05-11 and 101.0.0-beta.3. It was fixed by https://github.com/mozilla-mobile/fenix/issues/24692. I will close this issue as once the fix is uplifted the issue will no longer occur.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
