### ISSUE TITLE
Losing focus doesn't dismiss popup prompt for <select> element

### ISSUE THREAD

**Issue by makotokato** [mozilla-mobile/fenix#25262]
### Steps to reproduce

1. Open https://codepen.io/mkato/pen/VwQPOWj
2. Tap `<select>` element

### Expected behaviour

After 0.5sec, script calls `element.blur()`, so `<select>` popup should be dismissed. Firefox desktop and Chrome Android work well.

### Actual behaviour

`<select>` popup keeps open even if focus is lost.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

102

### Additional information

I guess that this is 2 issues.
- GeckoView doesn't call [PromptInstanceDelegate.onPromptDismiss](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.PromptDelegate.PromptInstanceDelegate.html) when focus is lost.
- Android-component won't handle onPromptDismiss for `<select>` popup.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20475)

**Comment by makotokato** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1769738.
Don't close this since I guess we need more work in android-component or Fenix.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 105.0a1 2022-08-08. The issue is partially fixed, after tapping the first select it is dismissed after 0.5 seconds, but after tapping the second select (the calendar) it will not be dismissed without user interaction.

https://user-images.githubusercontent.com/50983519/183669138-bd2499ea-dbb8-4baa-b114-d075d2d27fd7.mp4

### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813750

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
