### ISSUE TITLE
Investigate requirements on what search suggestions should be shown

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25285]
Currently search suggestions are shown for all search engines. However, we want to simplify this behaviour.  Work with UX to confirm what search suggestions should be shown for search engines.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20504)

**Comment by kbrosnan** [comment]
This seems like a good surface to suggest to the user to do a web search.

**Comment by gabrielluong** [comment]
@rocketsroger I was just checking our DMs since I know this was filed in response to me saying that we needed to better document our product requirements in the code because how we have a bunch of search engines flipping on/off depending on the search engine that is selected. We want to document in the code and align with what the product requirements are so that it is understood for the future why things are the way they are.

**Comment by csadilek** [comment]
@rocketsroger do you want to keep this issue? Not sure about the comment above.

**Comment by rocketsroger** [comment]
No need.  This can be close since https://github.com/mozilla-mobile/fenix/issues/25816 have all the information needed.  I'll close this, thanks.
