### ISSUE TITLE
FNX3-16391 ⁃ "report site issue" link with tracking protection exception

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2530]
### Steps to reproduce
1. open a website
1. press the padlock

### Actual behavior
* With tracking protection enabled there is a "report site issue" link.
* With tracking protection disabled there is no "report site issue" link.
* With tracking protection enabled and an exception for a website there is a "report site issue" link for this website.

![report-site-issue](https://user-images.githubusercontent.com/1100614/57802455-429d2b00-7756-11e9-80dc-507c207b15cb.png)

### Expected behavior
Since there is no "report site issue" link with tracking protection disabled this feature seems to be related to the tracking protection. If it's really only for reporting problems with the tracking protection the link should be hidden for websites on the exception list.

or…

If it's expected that the "report site issue" link appears for websites with tracking protection disabled then the link should also appear if tracking protection is globally disabled.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f84b7f10dd46a3c8e2f47f87e5bf1db5687277b7

**Comment by ekager** [comment]
This is the intended behavior see #2422 . 
The Settings Action should only be available when TP is off globally. 
CC @topotropic for verification of the middle behavior.

**Comment by cadeyrn** [comment]
#2422 was about the toggle, this issue is about the "report site issue" link.

**Comment by ekager** [comment]
New UX was linked in #2422 with the new action for when TP is globally disabled 
https://github.com/mozilla-mobile/fenix/issues/2422#issuecomment-491795225

**Comment by topotropic** [comment]
Good catch, @cadeyrn! Thanks! 

It depends on what we want to do, my initial thinking was that "Report site issue" is related to the tracking protection, if that's the case, I agree that we don't need to display it for exceptions. 

If "Report site issue" is independent of Tracking protection we could always show it, also when Tracking protection is disabled globally. 

@vesta0  I'm not sure what our goals here are, can you make a call?

**Comment by vesta0** [comment]
"Report site issue" is not related to tracking protection. It may be related to various webcompat issues and bugs submitted go to the webcompat repo. We should always show it.  @topotropic @ekager

**Comment by ekager** [comment]
So @vesta0 - remove the text that links to TP settings when TP is off globally? As defined in #2422

**Comment by vesta0** [comment]
@ekager can we only fit one of those texts? Would it be too crowded otherwise?

**Comment by ekager** [comment]
I think that's a question for @topotropic. I followed the new spec in #2422 to add the "TP is globally disabled text" under the toggle when globally disabled. "Report site issue" is already an option in the browser menu, maybe we don't need this link here at all. That or maybe it should be it's own item in the quick setting menu since it seems like this discussion is leading to it always being there.

**Comment by topotropic** [comment]
The site panel is a good place for the "Report site issue" link because that's where people eventually try to troubleshoot a page by turning TP off and if that doesn't help they can report an issue right from there.
And to stay consistent it makes sense to display the link to "Report site issue" even if TP is turned off globally. This is not critical and could be done post MVP (@vesta0)

![tp](https://user-images.githubusercontent.com/353960/58019074-eeeb6280-7b04-11e9-8c75-c7b8b11945c1.png)

**Comment by vesta0** [comment]
Thank you @ekager and @topotropic :)

**Comment by sv-ohorvath** [comment]
Verified on build 5/24 (#11440149)
