### ISSUE TITLE
Save password disappears before user can interact with it.

### ISSUE THREAD

**Issue by DDMFMH41** [mozilla-mobile/fenix#25354]
( Précédemment à : [firefox-android-feedback@mozilla.com] ) 
Bonjour. Lorsque je vais sur laposte•net via Firefox, que je tape une e-adresse (en @laposte•net) puis le mot de passe correspondant, apparaît en bas d'écran la proposition de Firefox d'enregistrer cette paire "e-adresse / mot de passe", mais trop vite pour que j'aie le temps de taper sur "Enregistrer" ! (Et je reste avec le précédent mot de passe enregistré correspondant à cette e-adresse !) Mardi 24 mai 2022.

> Hello. When I go to laposte.net via Firefox, type an e-address (in @LaPoste.net) then the corresponding password, the Firefox proposal to save this "e-address" pair appears at the bottom of the screen. /password", but too fast for me to hit "Save"! (And I remain with the previous saved password corresponding to this e-address!) 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20540)

**Comment by dep** [comment]
Same. Sometimes with Android Firefox the prompt to save my password will appear then quickly disappear before can click save [Android]. happens when create a new password on certain sites. Liberapay for example. Click submit after setting password, dialog to save appears, the browser goes to the next page and the dialog quickly disappears. Was only visible maybe 1000 msecs

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812426

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
