### ISSUE TITLE
[Telemetry] Record metrics for credit card save and update facts

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#25397]
Fenix counterpart of [10343](https://github.com/mozilla-mobile/android-components/issues/10343).

In [this PR](https://github.com/mozilla-mobile/android-components/pull/12176) we added facts that were emitted when a credit card was saved or updated using the autofill prompt. In this issue we should record these facts.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20572)

**Comment by delia-pop** [comment]
Verified as fixed in the latest Nightly from 05/30 with Google Pixel 6 (Android 12). 
The events generated for save and update credit card:
![save](https://user-images.githubusercontent.com/89388888/170970649-dd11a49f-b240-46d9-917c-5e8c17a8f8ab.JPG)
![update](https://user-images.githubusercontent.com/89388888/170970658-f742941f-14d6-4cef-b6bb-867a13b93d99.JPG)
