### ISSUE TITLE
Accessibility: Android zoom clicking incorrect elements

### ISSUE THREAD

**Issue by davidbtc2009** [mozilla-mobile/fenix#25454]
### Steps to reproduce

1. Enable magnification gestures in android settings > accessibility > Magnification shortcut swipe up with 2 fingers
2. Open firefox
3. Go to a website
4. 2 finger swipe up from the home bar and a green outline will appear along the border of the display
5. Tap with 1 finger to enable zoom
6. Swipe around with 2_fingers until an element (link, button, etc) you wish to click is in focus
7. Tap the desired element with 1 finger

### Expected behaviour

The element that was tapped should be activated

### Actual behaviour

A random element way down the page is activated instead of the desired one

### Device name

motorola One 5G Ace

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

Fenix 101.1.0 or lower (not fixed in 102.0.0-beta.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20602)

**Comment by kbrosnan** [comment]
@davidbtc2009 can you reproduce this behavior in our[ Geckoview example browser](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public%2Fbuild%2Fgeckoview_example.apk) this build should work with most modern phones. If it does not please let us know which phone you are using. The build will help us understand if the problem is with the core part of our browser or with the front end UI.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802826

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
@davidbtc2009 is this something that you still see in current versions of Firefox? Some developers have checked Android 12 and 13 and cannot reproduce.

**Comment by shortwavesurfer2009** [comment]
@kbrosnan yes, i still see this on Android 11 but haven't gotten to upgrade to Android 12. Hopefully i will be able to soon if its working in that version. I did discover a different app that does not like magnification gestures and requires me to switch back to three button navigation to use properly. I wonder if something about it is causing the issue as i think activating magnification in Android 12 requires a small chip to be clicked instead of a gesture. This is just an idea and i have not tested it as i literally just thought of it.

**Comment by shortwavesurfer2009** [comment]
Nope, just checked and that isn't it either.
