### ISSUE TITLE
FNX3-16407 ⁃ Bring back Top Sites

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#2557]
### Why/User Benefit/User Problem
I overwhelmingly visit only my top ~5 or so sites on mobile. The Top Sites widget on the page reached from the URL bar in Fennec is now replaced with what seems primarily focused around sites.

(This is probably my top regression from Fennec right now. #1161 is related but not quite the same, I think?)

### What/Requirements
Give me easy automatic access to frecent sites without having to do explicit maintenance (like Collections or Bookmarks).

**Comment by liuche** [comment]
@topotropic has been doing homescreen work, so she is the most reasonable person to take on this work (although she's also working on Secure Proxy).

If this can happen by Friday, that would be ideal so @bifleming can pull sizing, but if not, that's okay.
The goal/outcome of the first ask is to get a quick feasibility exploration, so that we could get started on early eng work.

**Comment by vesta0** [comment]
@djc thanks for filing this ticket. We will address this in #6190

**Comment by mfn** [comment]
FTR this isn't implemented yet, following https://github.com/mozilla-mobile/fenix/issues/6190 leads to https://github.com/mozilla-mobile/fenix/issues/10342 which is currently open.

Just to save others some time 😄
