### ISSUE TITLE
Customizable three-dot Menu

### ISSUE THREAD

**Issue by ActualDisaster2447** [mozilla-mobile/fenix#25647]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

To my knowledge, there is no open issue about this, so I am sorry in advance if my research was not adequate enough.

### What is the user problem or growth opportunity you want to see solved?
In Firefox for Android, the main three-dot menu seems unnecessarily cluttered and does not make sense in regards to the rest of the UI. It seems that it has options that are already present in the settings and/or do not need to be accessed by the user so frequently. Here is a picture for reference: 

![20220616_145954](https://user-images.githubusercontent.com/91388337/174075227-66ac4a71-7fd4-4aa3-a14d-404d39bb885a.jpg)

In my opinion, the user should have the choice to what options should be displayed there or not as that menu is there for easy access to features that are necessary (to them) in day-to-day browsing. Many other browsers such as Samsung Internet or Microsoft Edge allow for easy customization of their respective menus so that certain features that a user deems unnecessary for themselves can be moved out of sight, while Firefox does not offer that. A user does not need to know "What is new?" or "Sign in to sync" in Firefox every day, especially if they chose to not log into their Firefox account in the first place. After all, if they went into the settings, they would get a big prompt at the top of the screen to log in anyway.

Another issue is that Firefox keeps its "Add to shortcuts" feature in the menu, even if shortcuts are disabled from being displayed on the homepage. I think that is a very bad UX and is unnecessarily confusing. It kind of makes the software seem unpolished to me.

### How do you know that this problem exists today? Why is this important?
A lot of people, me included, like the simplicity of Firefox Focus/Klar, but find it a bit too underwhelming for certain tasks. In contrast, Focus has way less options in this menu, but still covers what most people need while browsing. To me, that is a much better approach, but unfortunately, Focus has other issues I cannot live with, while on the other hand I do not have the option of using two separate browsers to mitigate Focus's issues. 

### Who will benefit from it?
People who like the simplicity of Focus, but need a more powerful browser for their daily browsing needs.

### Suggestions
A simple menu customization section could be added to the settings, similarly to the one for the homepage that allows the user to check which features they want to expose at first glance.

### Other
Here is a post I made on Reddit regarding this issue and it seems I am not the only one pressed about it.
Link: https://www.reddit.com/r/firefox/comments/vdgb2a/is_there_a_way_to_get_rid_of_these_menu_items_the/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20729)

**Comment by NatoBoram** [comment]
Being able to remove some of these buttons via `about:config` would be appreciated

**Comment by ActualDisaster2447** [comment]
That would be a sufficient solution!

**Comment by helpthemfix** [comment]
Also being able to pin uBlock Origin on the bar or menu would be great. Clicking 3 times through sub-menus to get to uBlock origin is not time efficient.

**Comment by kbrosnan** [comment]
This is not something that we plan on doing. Supporting the exponential growth of combinations of menu items would be a massive maintenance burden.

`about:config` is not a solution for Fenix UI controls because `about:config` Geckoview does not provide an API to query values for arbitrary entries. Additionally the Fenix team does not want to have UI behavior depend on if Gecko is running or not. Depending on `about:config` would result in significant regressions in startup time and responsiveness.

**Comment by NatoBoram** [comment]
> Supporting the exponential growth of combinations of menu items would be a massive maintenance burden.

Can you expand a bit on this? As a software developer myself, I do not see how you were able to make the leap from "make menu items optional" to "exponential growth of combinations of menu items".

> A simple menu customization section could be added to the settings, similarly to the one for the homepage that allows the user to check which features they want to expose at first glance.

That's something that's pretty straightforward to implement, isn't it?

**Comment by helpthemfix** [comment]
> > Supporting the exponential growth of combinations of menu items would be a massive maintenance burden.
> 
> Can you expand a bit on this? As a software developer myself, I do not see how you were able to make the leap from "make menu items optional" to "exponential growth of combinations of menu items".
> 
> > A simple menu customization section could be added to the settings, similarly to the one for the homepage that allows the user to check which features they want to expose at first glance.
> 
> That's something that's pretty straightforward to implement, isn't it?

God forbid they do what the users actually want. No wonder Edge is taking over Firefox's market share. Wake up Mozilla...

**Comment by kbrosnan** [comment]
Disabling the appearance of the menu items would need to be accounted for in all existing and new features. There is the added question what behavior does disabling the menu item have. Does it remove the menu item or does it disable the whole feature? If it only removes the menu item how does a user interact or get to views that are no longer in the menu? These are just thought experiments, they are not going to be answered in this issue. The UX team would own any decisions on such behavior.

Using the menu with a website loaded as an example there are 13 menu items (discounting navigation). If you can toggle each of them then you end up with 8k (2^13) distinct combinations that the menu could have. This will result in odd edge cases and unexpected behavior. The real cost here is ongoing maintenance and complexity for both developers, testing teams, and designers.

**Comment by NatoBoram** [comment]
We can do the exercice if you want.

> There is the added question what behavior does disabling the menu item have.

* New tab: Nothing changes
* Bookmarks: Nothing changes
* History: Nothing changes
* Downloads: Nothing changes
* Add-ons: Nothing changes
* Sync: Nothing changes
* Find in page: Nothing changes
* Desktop site: Nothing changes
* Open in app: Nothing changes
* Report Site Issue: Nothing changes
* Add to home screen: Stop nagging people with the blue notification dot
* Add to shortcuts: Nothing changes
* Save to collection: Nothing changes
* What's new: Stop nagging people with the blue notification dot
* Help: Nothing changes
* Customize homepage: Nothing changes

Let's not pretend that hiding a menu item has far-reaching consequences.

> Does it remove the menu item or does it disable the whole feature?

* New tab: Remove the menu item
* Bookmarks: Remove the menu item
* History: Remove the menu item
* Downloads: Remove the menu item
* Add-ons: Remove the menu item
* Sync: Remove the menu item
* Find in page: Remove the menu item
* Desktop site: Remove the menu item
* Open in app: Remove the menu item
* Report Site Issue: Remove the menu item
* Add to home screen: Remove the menu item
* Add to shortcuts: Remove the menu item
* Save to collection: Remove the menu item
* What's new: Remove the menu item
* Help: Remove the menu item
* Customize homepage: Remove the menu item

> If it only removes the menu item how does a user interact or get to views that are no longer in the menu?

That's like saying "If a user doesn't want to access a view, how will they access that view?"

* New tab: Tabs, new tab
* Bookmarks: They don't
* History: They don't
* Downloads: They don't
* Add-ons: They don't
* Sync: Settings, Sync
* Find in page: They don't
* Desktop site: They don't
* Open in app: They don't
* Report Site Issue: They don't
* Add to home screen: They don't
* Add to shortcuts: They don't
* Save to collection: They don't
* What's new: Settings, about, what's new
* Help: Settings, about, support
* Customize homepage: Settings, homepage

Besides, that's completely irrelevant. People want to hide menu items. If they block themselves from accessing the "Save to collection" button, then it's because they want to.

> If you can toggle each of them then you end up with 8k (2^13) distinct combinations that the menu could have.

That seems very disingenuous. When I hide a menu item in code, I hide a menu item. Sometimes, there's separators to account for, but that's resolved by an `if` statement and a function. And that still gives *one* layout, not 8'192.

And the homepage supports 64 "permutations", but it's not like it's the end of the world either. It's still *one layout*.

[![Homepage-400](https://user-images.githubusercontent.com/10495562/174870676-9d4d2d02-8a51-4bb0-b614-83518701e7b0.png)](https://user-images.githubusercontent.com/10495562/174870222-d5d61ac8-f93b-42c7-85ba-ac2172682653.png) [![Options](https://user-images.githubusercontent.com/10495562/174870679-6d66068f-5e2e-4e90-9c18-9fbb3dfb542d.png)](https://user-images.githubusercontent.com/10495562/174870213-313eed5a-1b93-4099-9e5a-8b871bc43174.png)

I really don't understand the leap of faith you make from hiding menu items to this amount of complexity.

**Comment by ActualDisaster2447** [comment]
@NatoBoram It's literally that simple. I don't know why @kbrosnan is making it such a big endeavour like we are asking Mozilla to finally make Fission on by default in the stable Android version in the next release. Even if it would display a big maintenance burden, it makes sense to add this feature as the current state makes the menu way too crowded and sometimes even inaccessible. Either way, the grounds for it are already available (as @NatoBoram pointed out) in the form of the Homepage settings. Please, kindly reconsider your decision regarding this issue!

**Comment by 424344** [comment]
> The real cost here is ongoing maintenance and complexity for both developers, testing teams, and designers.

that's the problem with mozilla these days: you implement only what is convenient for you, not for the users.
that's bad management, and the result is that your marketshare is shrinking.. maybe you're doing it wrong?

in any case please reopen this issue.

**Comment by ActualDisaster2447** [comment]
Even though, there seems to be a lot of demand for more customization im Firefox for Android, users are only faced with hostility and ignorance which doesn't make sense, since customization and add-ons would make for a great reason to use Firefox over other browsers since Firefox is slower than Chromium, doesn't support site isolation and adds more attack surface since you can't use GeckoView as the default WebView, so you basically have two things to do one thing.

I'm slowly giving up on Firefox, honestly.

**Comment by ActualDisaster2447** [comment]
> I'm slowly giving up on Firefox, honestly.

Update: I've completely moved to Vivaldi now because of this, the horrible tablet UI and many, many other things. Enjoy losing users indefinitely, I guess.

**Comment by litLizard69** [comment]
> > > Supporting the exponential growth of combinations of menu items would be a massive maintenance burden.
> > 
> > 
> > Can you expand a bit on this? As a software developer myself, I do not see how you were able to make the leap from "make menu items optional" to "exponential growth of combinations of menu items".
> > > A simple menu customization section could be added to the settings, similarly to the one for the homepage that allows the user to check which features they want to expose at first glance.
> > 
> > 
> > That's something that's pretty straightforward to implement, isn't it?
> 
> God forbid they do what the users actually want. No wonder Edge is taking over Firefox's market share. Wake up Mozilla...

They are still sleeping I think. Somebody got an air horn?
