### ISSUE TITLE
Unified search tapping back to the toolbar should preserve the search term

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25812]
After user performs the search, if the user taps back into the toolbar right away, the search term should be displayed. (not the URL)  

Also, The cursor should be at the end of the search term and the search term should not be highlighted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20851)

**Comment by jonalmeida** [comment]
@Alexandru2909 note that we do this today already. However, we clear the search term on a new page load (clicking a link or a redirect).

With most search engines now, they redirect immediately to get to the search page and that's why the search term is cleared.

You can see this working with duckduckgo today.

So instead of finding a new place to store the search term, let's fix this logic instead.

**Comment by Alexandru2909** [comment]
Hi @jonalmeida ! thanks for adding these details. I found a fix for this which also maintains the behavior implemented for https://github.com/mozilla-mobile/android-components/issues/3451. I will open a PR on AC with it.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest nightly 110.0a1 (2023-01-05) build.
Device used: google Pixel 4 (Android 13).
Closing the ticket as verified.
