### ISSUE TITLE
[Bug]: SVG filter feColorMatrix's 5th column has no effect

### ISSUE THREAD

**Issue by squarecrow** [mozilla-mobile/fenix#25880]
### Steps to reproduce

1. In Firefox on mobile, display any SVG element where a `feColorMatrix` filter is manipulating another SVG element's RGBA channels.
2. Compare two versions of that manipulation, one where the matrix's 5th column[^footnote] values are all set at their default "`0`", and one where they are set to non-zero values, such as "`1`".
3. Compare with other, prior mobile Firefox versions, or Firefox on desktop.

I rarely submit issues or bug reports, and rarely use GitHub. I apologise for any missteps I may cause in my issue submission process. I might not be able to offer additional information if asked, but I will try.

[^footnote]: Sometimes called the "Offset" or "Multiplier", I think.

### Expected behaviour

The element should look different, between the filter where the 5th column values are all "`0`", and the filter where they are not all "`0`". Such as in the accompanying screenshot, using Firefox 96.0.3 for desktop.

I think this also looked correct in Chromium browsers, last time I checked too, and I think it looked correct on some previous version of Firefox on mobile too, but I don't know the exact number.

![fecolormatrix-example-correct_r1_g-1_b1_a1_og1](https://user-images.githubusercontent.com/29046071/177223858-b517b4b4-c1d7-4c5e-8920-d1b5faf625a8.png)

### Actual behaviour

In Firefox on mobile, the manipulated element looks the same with both filters, no matter what the 5th column values are set to.
![fecolormatrix-example-wrong_r1_g-1_b1_og1](https://user-images.githubusercontent.com/29046071/177225127-af5f1cf2-d2ef-4d3e-b247-ba21d3e6eeee.png)

### Device name

Neffos Y5, TP-Link

### Android version

Android 6.0.1

### Firefox release type

Firefox

### Firefox version

102.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20901)

**Comment by Dunexus** [comment]
I don't reproduce on OnePlus 5T using latest nightly. This may be graphics driver related.

@squarecrow could you go to `about:support`, click on "copy text to clipboard" and attach the information to this bug ?

cc @jamienicol from gfx team : Are there known issues with Qualcomm Adreno 304 drivers that may be related ?

**Comment by jamienicol** [comment]
I'm not aware of this issue specifically, but we have had many issues with the svg filter shader on older mobile drivers as they tend to be very buggy and it's a complex shader.

**Comment by jamienicol** [comment]
@squarecrow since you think this worked in previous versions of firefox, would you be able to use [mozregression](https://mozilla.github.io/mozregression/install.html) to help track down which change introduced the bug?

If your computer is running Linux or Macos, it's easiest to install mozregression from the command line, by running `pip install --user mozregression`. On windows, you can install mozregression-gui.exe from [here](https://github.com/mozilla/mozregression/releases).

Next you'll need to connect your phone to your computer, and ensure you have USB debugging enabled on your phone.

Then you can run mozregression. On the command line run `mozregression --app gve --good 100`. Or in the GUI, click the scissor icon to start a new bisection, on the first page select "gve" from the "Application" drop down menu then click "next". Click "next" again on the next page ("Profile selection"). Then on the final page ("Build selection"), For "last know good build" change "date" to "release" and enter 100. Then hit finish.

(If version 100 still has this bug then try an earlier version).

This will download and open a series of versions of firefox. For each one, enter "good" or "bad", and eventually it will tell you what change caused the issue. Please let me know if you need any help with that. Thanks!

**Comment by squarecrow** [comment]
> could you go to `about:support`, click on "copy text to clipboard" and attach the information to this bug ?

 @Dunexus: I have attached the results of `about:support`'s "copy text to clipboard" to this file: [firefoxclipboard.txt](https://github.com/mozilla-mobile/fenix/files/9047455/firefoxclipboard.txt).

If you or others would prefer the text dump to be embedded in this post, I can edit it in. I also think some line breaks and/or spaces, may not have been correctly copied, making some parts potentially hard to read. But I did not alter them, in case you needed them as unmodified as possible.

> since you think this worked in previous versions of firefox, would you be able to use [mozregression](https://mozilla.github.io/mozregression/install.html) to help track down which change introduced the bug?
> 
> If your computer is running Linux or Macos, it's easiest to install mozregression from the command line, by running pip install --user mozregression. On windows, you can install mozregression-gui.exe from [here](https://github.com/mozilla/mozregression/releases).

@jamienicol: My PC's Linux system needs to first install PIP itself, as well as other dependencies, that I unfortunately can't allow right now, due to other different stability problems, that I'll have to gradually clear up. But I am sorry, for not being able to go through with this simple request, at this time.

I have, however, manually tested today with older APK's of Firefox. The following results, for testing the feColormatrix filter's 5th column on the [SVG Color Matrix Mixer](https://fecolormatrix.com/) website:

Works on:
- 101.1.0
- 101.1.1
- 101.2.0

Does **not** work on:
- 102.0.0-beta.1
- 102.1.1
- 103.0.0-beta.2

I hope that any of this may be of, at least, some help for your team, and I apologise if I should've replied separately to the two requests.
