### ISSUE TITLE
Sponsored tiles disabled in active experiment

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#25933]
https://mozilla-hub.atlassian.net/browse/EXP-2591

In 101 and prior, the Nimbus implementation in Fenix held the responsibility for caching the experimentation values fetched through Nimbus. These values were only fetched once during the initialization sequence of Fenix.
In 102, the Nimbus startup sequence in Fenix was changed to account for updates to Nimbus’ own internal caching layer and the startup was executed earlier in the application. This caused a problem with the values that are fetched by the application because there was a race condition which led to the application fetching and storing the values from Nimbus before it was fully ready and these values were not updated to the latest values from Nimbus when its startup was completed because they were only fetched once. As a result, it is believed that this caused the experiment to not enable the feature and for the telemetry values to be reported too early with the incorrect values from Nimbus.

Our fix removes a call to an event handler that would report the home screen telemetry metrics that was called before the Nimbus updates have been applied. This should fix the incorrect telemetry metrics reporting from being called too early before Nimbus is ready.
In addition, we removed the underlying Nimbus value caching in the Fenix application and ensure we always fetching the latest value directly from Nimbus

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20944)

**Comment by heres-maria** [comment]
We have verified that the issue is no longer reproducible.
We have tested the following scenarios:

- User enrolls in study in Firefox 101, updates the app to version 102 and then updates the app to the version containing the fix. 
     - Result: Sponsored shortcuts are disabled in Firefox 102 and then re-enabled as per experiment configuration in Firefox 104 (the build containing the fix). The user is not unenrolled from the study at any point during the entire flow.
- User enrolls in study in Firefox 101 and then updates the app to the version containing the fix. 
     - Result: Sponsored shortcuts remain enabled as per experiment configuration. The user is not unenrolled at any point.
- User (using the build with the fix) enrolled in the study restarts the application repeatedly.
     - Result: Sponsored shortcuts remain enabled as per experiment configuration. The user is not unenrolled at any point.
- User (using the build with the fix) disables the study while Sponsored shortcuts are enabled.
     - Result: Sponsored shortcuts are no longer enabled at the next startup. The option is still available in Settings.
- User (using the build with the fix) changes the Sponsored Shortcuts setting while enrolled in the study.
     - Result: User choice is respected.
- User (using the build with the fix) is exposed to a Sponsored Shortcut while enrolled in the study. 
     - Result: The “topsites-impression” metrics and “contile_impression” event are correctly recorded.

Other configurations of the “homescreen” feature are also correctly applied (using a Stage experiment which disables the Pocket section).

Builds used:

- null build built from main as Release (Build #2015890971), 261569c2c+ AC: 104.0.20220707143048, 4e16186a0c GV: 104.0a1-20220707093757 AS: 93.5.0. 
- null build built from releases_v102.0.0 as Release (Build #20158909971), 05001d1fa+ AC: 102.0.14, cd19f9a6c5 GV: 102.0.1-20220705093820 AS: 93.1.0 (update scenario)
- null build built from releases_v101.0.0 as Release (Build #2015890971), be90007a4+ AC: 101.0.11, 3d21af5171 GV: 101.0.1-20220608170832 AS: 91.1.2 (update scenario)

Platforms used:

- Android 9 - Samsung Galaxy S8
- Android 10 - Samsung Galaxy S9
- Android 11 - OnePlus 6T

**Comment by delia-pop** [comment]
Verified as fixed in Firefox 102.2.1 with LG G7 fit (Android 8.1.0), from the Mobile QA team as well.
