### ISSUE TITLE
Wallpaper download/persistence state should be observable.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26211]
The state of individual wallpapers should be observable, so that updates can be received about download progress or file location etc. This could be a property exposed on each wallpaper from the `availableWallpapers` property being added to the `AppStore`, so that the entire list is diffed when changes are emitted. Something like:

```
sealed class Wallpaper {
    val fileState: WallpaperFileState
}

sealed class WallpaperFileState {
    NotAvailable
    Downloading(val percent: Int)
    Downloaded
    Error
}
```

This state should be updated appropriately when wallpapers are downloaded.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21131)

**Comment by delia-pop** [comment]
Tested with the latest Debug build updated from main with Google Pixel 6 (Android 13). We will re-test this on Nightly when available.
Currently, when tapping a thumbnail, the highlight will remain on previously selected thumbnail, until the full-size wallpaper is downloaded. Once the download is complete, the selected thumbnail will be highlighted and the snackbar will be displayed. 
No changes in opacity can be observed. Is this the expected behavior? 

https://user-images.githubusercontent.com/89388888/187944284-20e1f706-81fb-4409-9174-0047fc74393f.mp4

**Comment by delia-pop** [comment]
Re-tested with the latest Debug build updated from main with Google Pixel 6 (Android 13). When tapping on the thumbnail, a change in opacity can now be noticed.  

https://user-images.githubusercontent.com/89388888/188174569-7e0e042c-c3c8-4b60-beb3-0c89c5869f03.mp4
