### ISSUE TITLE
Implement Themed App Icon

### ISSUE THREAD

**Issue by mduchev** [mozilla-mobile/fenix#26280]
### What is the user problem or growth opportunity you want to see solved?
Since the 1st/2nd Android 13 beta, Google has been pushing the new [Themed App Icons](https://developer.android.com/about/versions/13/features#themed-app-icons). We've already seen several apps adapting this new styling (e.g. 1Password 8, Reddit, etc). I know that it's a bit early to have this change inside Firefox, but the official Android 13 release is almost here, so we have to think of implementing it at some point. The APIs for Android 13 have been finalized, so this for sure will make it into the release.

### How do you know that this problem exists today? Why is this important?
Firefox, like many other apps, hasn't implemented the new icon. It would be good at some point to have this new styling come to Firefox on Android as well, since it would increase the UI/UX.

### Who will benefit from it?
All users running Android 13+

# UX provided release icons
[icons](https://github.com/mozilla-mobile/fenix/issues/26280#issuecomment-1283066984)
todo: icons for beta/nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21178)

**Comment by MEXISNAKE** [comment]
Pretty please? It's the only app on my phone's home screen that doesn't match the theme!

**Comment by bruuteforce** [comment]
Excited to see 🔥🦊 in monochrome icon

**Comment by JordanDChappell** [comment]
+1 from me, currently using Chrome browser on my phone to match my home screen theme, but would love to make the switch back to Firefox as my default app.

**Comment by mcarare** [comment]
UX would need to provide a monchrome icon resource for this.

**Comment by coolreader18** [comment]
Isn't there already one? Just looking on the logo section of Mozilla design guidelines the Firefox logo zipfile has a `Fx-Browser-icon-oneColor.svg` which seems to be exactly what this feature would need. ![Fx-Browser-icon-oneColor.png](https://user-images.githubusercontent.com/33094578/193396962-e6359676-df56-4103-aa19-ab57b8e72a45.png)

**Comment by nidmb** [comment]
It seems pretty odd to me that Pocket has it already but Firefox doesn't:
![Screenshot_20221002-001616](https://user-images.githubusercontent.com/65424089/193430292-40c41d53-1adb-47b8-8bee-5fee1ab90aee.png)

**Comment by mcarare** [comment]
For UX evaluation, this is what it would look like, with tint adapted to the current OS wallpaper:

<img src = https://user-images.githubusercontent.com/48995920/193625387-0d564c93-43a7-4fd2-85c9-4fd675adf6b3.png width = 45%> <img src = https://user-images.githubusercontent.com/48995920/193625438-9b4f751b-d7fc-4e75-a6e5-ab59bf5a7910.png width = 45%>

Notice the other icons for comparison.

**Comment by lime124** [comment]
from design systems: Here should be all assets to make this happen at the right sizes. This includes assets to do the adaptive color and adaptive shape as well following this template: https://www.figma.com/file/rPjPBDNz95wRi501zppMwy/Android-App-Icons-(Community)?node-id=0%3A1

**Comment by VexfulNiko** [comment]
Hoping for this soon and a UI overhaul to fix Fenix honestly awful UI. Google Chrome got the themed icon and Material You app design down and it's pretty solid of course, other than being you know, Google.

**Comment by lime124** [comment]
updating label - lmk if you need anything else!

**Comment by fice-t** [comment]
@lime124 How should the Beta/Nightly/Debug icons be handled? The debug icon seems fine to leave out (it's uncommon + making it stand out seems reasonable), but having installations of more than one of Release/Beta/Nightly and wanting them all to be themed seems like something that should be supported.

**Comment by jane-wolf** [comment]
@fice-t  @lime124 and I talked through this and we currently can release the default icon as a themed option. The other icons would need some sort of badge to them but that is not possible for Android theming at the moment. 

Currently Google themed icon docs don't have any info on adding a badge layer, and our beta and nightly icons are all the same shape

**Comment by kbrosnan** [comment]
I would be happy to take the fix that works on release for now and file a followup to get some designs that work with the prerelease channels. It looks like Chrome beta creates a segment that divides the bottom of the circle and has the beta text.

**Comment by fischer-felix** [comment]
In the above commit, the monochrome icon is just the standard icon with the gradients and the globe in the middle removed. 
Imo this would be the most vanilla approach, but I think it might be worth considering a line style icon.
Since this would be quite a far step from the current look, I wanted to ask here first and get some opinions.
I'm thinking maybe we could just use the icons from [LawnchairLaucher/lawnicons](https://github.com/LawnchairLauncher/lawnicons), as the licence should allow it. This would also solve the issue of separate icons for Beta, Nightly and Release.

Below are screenshots of the modified stock icon and the regular and beta variants of the lawnicons:

![Screenshot_20221118_220528](https://user-images.githubusercontent.com/65448408/202805520-54b9d9f6-ebfd-4cd2-8acf-e378aacddb33.png)
![Screenshot_20221118_223444](https://user-images.githubusercontent.com/65448408/202807155-ac16964f-15fc-4855-aa9d-b38d2b113c9e.png)
![Screenshot_20221118_223605](https://user-images.githubusercontent.com/65448408/202807170-f2b115a7-2b33-4abc-99da-b9186434b606.png)

**Comment by fischer-felix** [comment]
quick correction, forgot the official onecolor icon before, so her it is as well:

![Screenshot_20221118_224632](https://user-images.githubusercontent.com/65448408/202808617-365f1e96-597e-48a6-9aa1-f6af2ad27d56.png)

**Comment by nidmb** [comment]
To be honest, I like both versions. However, I would lean towards using the solid icon so that it matches Pocket's icon design:
![obraz](https://user-images.githubusercontent.com/65424089/202812087-bf5e349a-5de2-436c-9163-e7d913d84bde.png)

**Comment by VexfulNiko** [comment]
I like both icons as well, but I prefer the non-solid icon; it looks cleaner in my view.

**Comment by Kernald** [comment]
The trend with the latest ones from Google (if it's anything to go by), namely Dialler, Messages and Contacts, seems to be preferring solid layers and negative colour for separating them. Overall, I think the solid variant would fit in better, but that might just be due to the icons I'm personally using.

**Comment by iamshilov** [comment]
Solid seems like the best variant.

**Comment by fischer-felix** [comment]
So since solid seems to be the preferred option, I made a rough mock-up of how the beta and nightly badges could be implemented.

I'm not really happy with it myself, but can't really find what's bothering me.
What do you think?
![ic_launcher_monochrome_beta_solid_red](https://user-images.githubusercontent.com/65448408/203155083-8a406e0e-9f9c-440d-ac10-51943344b465.svg)

**Comment by pwd-github** [comment]
Rather than add that square, could the Fox not be hugging a circle with the letter B in? So it's kinda integrated into the current design in a more organic manner?

**Comment by fischer-felix** [comment]
Absolutely love the idea!
Tried it with both Nightly and Beta, and it works quite well with an N, but the B looks a bit off (at least blown up when designing, now that I see it smaller in here, it might actually be fine when scaled down to icon size).
![ic_launcher_monochrome_nightly_solid_red](https://user-images.githubusercontent.com/65448408/203163896-9cbe184f-0a24-40c9-a513-54cfbf3edd5e.svg)
![ic_launcher_monochrome_beta_solid_hug_red](https://user-images.githubusercontent.com/65448408/203163902-d33e7e9d-ddef-467a-ae79-5f4b22904366.svg)
Note: I know that the letters are a bit off-centre in there

**Comment by pwd-github** [comment]
I like that a lot. Simple, clean and effective.

**Comment by Kernald** [comment]
Another option which might make the letters easier to identify could be to keep the letter in the bottom right corner, but use a similar negative space as a separation rather than the block you used in the previous iteration. That kind of negative space as separation is also what's used in recent Google icons, e.g. [Messages and Contacts](https://static1.anpoimages.com/wordpress/wp-content/uploads/2022/10/Google-Messages-Contacts-themed-icon3.jpeg).

Note: I'm not using any other builds than the release one so I'm not sure what the current icons look like.

**Comment by Otard95** [comment]
I apologize in advance if this is considered inappropriate to ask in issues like this, I'm just new to following GH issues for Firefox. Is there a place to see the timeline of these sorts of issues, or if not, where are we on this one, I'm exited to see it released!

**Comment by fischer-felix** [comment]
> Another option which might make the letters easier to identify could be to keep the letter in the bottom right corner, but use a similar negative space as a separation rather than the block you used in the previous iteration. That kind of negative space as separation is also what's used in recent Google icons, e.g. [Messages and Contacts](https://static1.anpoimages.com/wordpress/wp-content/uploads/2022/10/Google-Messages-Contacts-themed-icon3.jpeg).
> 
> Note: I'm not using any other builds than the release one so I'm not sure what the current icons look like.

So you mean sort of like this?

![ic_launcher_monochrome_nightly_red](https://user-images.githubusercontent.com/65448408/203307139-7e7b70e8-76f0-4e99-9883-e9c2952af7da.svg)
![ic_launcher_monochrome_beta_red](https://user-images.githubusercontent.com/65448408/203307144-f82a5089-bc1e-4f1d-be4b-1ade38521216.svg)

**Comment by Kernald** [comment]
That's exactly what I had in mind indeed!

**Comment by jane-wolf** [comment]
hi all, our design systems team will reconvene and choose the style that works best for these additional logos. Since this impacts a brand logo, it may need to go through some approvals. With it being a holiday in the U.S this week we will get back to you with an ETA on Monday for any approvals needed.

**Comment by NathanC** [comment]
These mock-ups look great! What about the Fennec F-droid icon? I like the Fennec logo quite a lot, but I'd prefer an adaptive icon even if it's the same as the standard Firefox icon.

**Comment by fischer-felix** [comment]
If the packagers apply their own patches to the codebase it's up to them if they want to keep the standard adaptive icon ore change it.
If they don't explicitly change it, the icon should be the same as upstream.

**Comment by DerpyPlayz18** [comment]
I think that the beta icon looks better if it is more like the normal version. It is more recognizable in my opinion
![FF_beta_themed_icon](https://user-images.githubusercontent.com/80034339/204034533-a5a84f18-f9c7-4352-b412-548468485d9c.png)

**Comment by fischer-felix** [comment]
That looks quite good!
Only concern I have is that when shown as an app icon (i.e. a lot smaller) you might not be able to read the text anymore, but it might be fine.

**Comment by jane-wolf** [comment]
hi all, just wanted to let you know that I've sent the different versions to legal, marketing, and localization and are waiting for feedback. I also found out that we try not to include words in imagery since they cannot be translated to different languages.

**Comment by NathanC** [comment]
@jane-wolf That's a good point about words in imagery, though beta is Greek and used pretty universal in tech. Alternatively the [beta character](https://en.wikipedia.org/wiki/Beta) could be used, would be pretty universal. That being said, I'm not a huge fan of how the beta character looks, just a potential suggestion. And maybe a small moon + stars symbol for the nightly icon version?

(Also just as an FYI for anyone here, it looks like the Fennec fdroid package now has a themed icon, and it looks great!)

**Comment by DerpyPlayz18** [comment]
Maybe the nightly icon could be a color inverted version of the normal one (everything dark except for the Firefox logo)

**Comment by nidmb** [comment]
For comparison, here are some examples of how other browsers are handling themed beta icons:
![Uploading Screenshot_20221203-012237.png…]
![Screenshot_20221203-012308](https://user-images.githubusercontent.com/65424089/205412618-f87b6f6b-6fb3-4411-b255-d2d1b73bb222.png)
()
On a sidenote, it also shows how far behind Firefox really is.
