### ISSUE TITLE
FNX3-16464 ⁃ [Bug] Pressing back on a tab with no history should close the tab

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2629]
## Steps to reproduce
1. Open the tab list. 
1. Perform a search. 
1. Open one of the search results in a new tab. 
1. Switch to said new tab via the snack bar notification
1. Press back

### Expected behavior
The tab is closed.

Whether you're taken to the parent or back to the tab list is #2483

### Actual behavior
You're taken back to the tab list and the tab remains. 

### Device information
* Android device: LG G6, Android 8
* Fenix version: 1.0.1920

**Comment by AndiAJ** [comment]
Hi, just tested on the latest Nightly Build #12970607 from 24/10 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔️ Tapping on the device back button closes the tab.

 ❌ When trying to close the last tab I've noticed the following:

► If you have >=3 open tabs in order to close the last tab you have to tap 2x on the back button
![20191024_112517](https://user-images.githubusercontent.com/51314259/67469081-54afbd80-f654-11e9-9b76-459a64ab6495.gif)

► If you have <=2 open tabs the last tab is properly closed on first attempt
![20191024_112437](https://user-images.githubusercontent.com/51314259/67468982-229e5b80-f654-11e9-8534-8de910f0fe5d.gif)

@ekager  - Please be kind and review the above. :)
I'll remove the QA needed label until clarifying this aspect.
