### ISSUE TITLE
High number of "Invalid State" errors for `engine.kill_foreground_age` and `engine.kill_background_age` Glean metrics

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26373]
This Looker dashboard shows about 8000 "Invalid State" errors per day for the `engine.kill_foreground_age` metric and and 4000 errors per day for the `engine.kill_background_age` metric:

https://mozilla.cloud.looker.com/explore/fenix/metrics?qid=VWaPjOZNKi0nIrE6MAyEDu&origin_space=746&toggle=fil,vis

These are the most common "Invalid State" errors on Fenix's Release channel, though these errors have been around for at least a year. The good news is that the error rate has steadily decreasing (from 50,000 + 25,000 errors per day a year ago) and now reached a steady state:

![image](https://user-images.githubusercontent.com/629193/183517419-8859fab9-c358-4852-a231-9341c63f3621.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21227)

**Comment by cpeterso** [comment]
Metadata about these metrics:

**Comment by cpeterso** [comment]
https://github.com/mozilla-mobile/fenix/blob/db0162465b42b10fbbbda2d0795b1aa0e6bcba86/app/metrics.yaml#L6686-L6729

**Comment by Mugurell** [comment]
According to [Glean documentation](https://mozilla.github.io/glean/book/reference/metrics/timing_distribution.html) `invalid_state` is recorded if a non-existing/stopped timer is stopped again.

We are not directly calling start/stop but just [`accumulateSamples`](https://github.com/mozilla-mobile/fenix/blob/bbf2d427d2f7191d245c8dcc295699fc7512a0d5/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt#L108-L112) which has little documentation about how it works but since we're just calling that method if it errors seems like a bug in Glean.

**Comment by cpeterso** [comment]
Oops. Looks like this error has already been fixed. The dashboard was not filtering out data from old builds. I will 

This error was a regression in Fenix 87 and fixed in 88. I'm surprised we still have users running Fenix 87, but that's what the data says.

I'll close this issue as invalid.
