### ISSUE TITLE
Increasing number of "Invalid Overflow" errors from `site_permissions.prompt_shown` and `site_permissions.permissions_allowed` Glean metrics

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26391]
This Looker dashboard shows about 9000 "Invalid Overflow" errors per day each from the `site_permissions.prompt_shown` and `site_permissions.permissions_allowed` metrics:

https://mozilla.cloud.looker.com/merge?mid=IfHcPphLA3JG0XAix1128R&toggle=mrp,vis

The error rate started to increase around July 26, which was Fenix 103's release date:

![image](https://user-images.githubusercontent.com/629193/183724881-e943257e-b042-45f6-a2eb-28453e16c904.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21241)

**Comment by Mugurell** [comment]
This telemetry is new to 103 - it was implemented in https://github.com/mozilla-mobile/fenix/issues/25658 in preparation for TCP.

Based on https://mozilla.github.io/glean/book/reference/metrics/event.html?highlight=extra_keys#limits and https://github.com/mozilla/glean/commit/4ef2d5bac966a5de1dbbb5f4fd563bcdb49eacfb the error seems to be recorded when too much data is sent in the extra key.
This scenario can happen because for example [`site_permissions.permissions_allowed`](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/site_permissions_permissions_allowed) sends a "Comma delimited list of approved permissions". [These](https://github.com/mozilla-mobile/android-components/pull/12350/commits/b908147e5b58f722e188dbf99df942a9aabbab6b) are the possible permissions.

Looks like we need a way to truncate the data sent but still keep the telemetry relevant.
Will sync with data science about this.

**Comment by Mugurell** [comment]
Opened https://mozilla-hub.atlassian.net/browse/DO-857 for consultation.

**Comment by Mugurell** [comment]
Patch landed in AC - https://github.com/mozilla-mobile/android-components/issues/12683 to ensure shorter permission names and deduplication.

@ QA A before and after test on a site which requests media permissions - like camera and microphone at once on a device with multiple cameras should show the difference we want.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 106.0a1 (2022-9-15) using the sites https://permission.site/ and https://mozilla.github.io/webrtc-landing/gum_test.html and observing the results.
When the permission prompt to use camera and microphone is shown
{
          "timestamp": 15128,
          "category": "site_permissions",
          "name": "prompt_shown",
          "extra": {
            "permissions": "ContentVideoCamera, ContentAudioMicrophone"
          }
When the permission prompt to use camera and microphone is denied.
{
          "timestamp": 10895,
          "category": "site_permissions",
          "name": "permissions_denied",
          "extra": {
            "permissions": "ContentVideoCamera, ContentAudioMicrophone"
          }
When the permission prompt to use camera and microphone is accepted
{
          "timestamp": 13933,
          "category": "site_permissions",
          "name": "permissions_allowed",
          "extra": {
            "permissions": "ContentVideoCamera, ContentAudioMicrophone"
          }
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-1609)
### Device used:
- OnePlus 6T (Android 9)
