### ISSUE TITLE
Create wallpaper file migration helper

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26424]
We plan to simplify the number of assets possible for each wallpaper. Previously, there were combinations of all of portrait/landscape, light/dark, and high/medium/low resolutions for each wallpaper. We will no longer be providing separate assets for themes or resolutions, so there will only be separate assets for different orientation (and thumbnails).

This will mean that currently saved versions of wallpapers will be stored under directory paths that are no longer relevant, like `wallpapers/<orientation>/<theme>/<wallpaperName>.png`. The new paths should follow a convention like `wallpapers/<wallpaperName>/portrait.png` and `wallpapers/<wallpaperName>/landscape.png`.

This will require migrating existing assets to the new path names. This is required because some users may have expired wallpapers that are no longer available, so we cannot just download a fresh asset. It is likely fine to ignore the consideration of updating the themed wallpaper to a non-themed wallpaper. Both the landscape and the portrait versions of an image should be copied.

If there is not a thumbnail available for the wallpaper (as could be the case with Turning Red wallpapers that are no longer available), then the portrait image of the wallpaper should also be copied as `wallpapers/<wallpaperName>/thumbnail.png` to ensure that it can be visible in the wallpaper settings page.

AC:
1. Install a build of the app that is not using the `wallpapersV2Enabled` feature flag, then set a wallpaper.
2. Overwrite it with a build that includes the migration code and has the flag enabled.
3. The selected wallpaper should still be selected.
4. The selected wallpaper can be rotated correctly.
5. The wallpaper is visible in the settings page. For wallpapers that have a thumbnail available remotely, it should use the new remote version.

The `WallpaperDownloader` and `WallpaperFileManager` contain code that would be a good starting point to building context around this issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21267)

**Comment by delia-pop** [comment]
Hi, @MatthewTighe , @Alexandru2909 , I tested this with older 104 and 105 Nightly builds updated to 107.0a1 from 09/21 with Google Pixel 6 (Android 13). The following were observed: 

- **Beach-vibes**: the wallpaper set before updating the app **is still displayed** on homepage once Fenix is updated to the latest version and continues to be properly displayed when changing the orientation. When accessing Settings > Wallpapers, the **thumbnail is not selected**. Upon selecting the beach-vibes wallpaper thumbnail, the wallpaper is set on homepage with a different color as expected;

https://user-images.githubusercontent.com/89388888/191508596-8e180392-52b7-4b62-824c-383348d4ea5a.mp4

<img src="https://user-images.githubusercontent.com/89388888/191508734-1680ee97-0abe-4b30-8582-a367ab85f051.png" width="40%" />

- **Twilight-hills**: the wallpaper set before updating the app **is still displayed** on homepage once Fenix is updated to the latest version and continues to be properly displayed when changing the orientation. When accessing Settings > Wallpapers, the **thumbnail is selected**;

https://user-images.githubusercontent.com/89388888/191508618-6d0d7cba-de9f-4779-82c8-49377219e977.mp4

- **Cerulean, Amethyst, Sunrise** : the wallpaper set before updating the app **is not displayed** on homepage once Fenix is updated to the latest version The "Couldn't change wallpaper" snackbar is displayed at launch. When accessing Settings > Wallpapers, **the thumbnail is selected**;

https://user-images.githubusercontent.com/89388888/191508671-bf3e43cb-83c6-4422-95e7-bcc7085502bd.mp4

After updating the app, the order of the wallpaper thumbnails for Twilight-hills and Beach-vibes is changed. However, these wallpaper are the only ones displayed after update.

<img src="https://user-images.githubusercontent.com/89388888/191508693-51d9001d-4adc-494a-8b82-4357bbfded2b.png" width="40%" />

**Comment by Alexandru2909** [comment]
@delia-pop thanks for testing this issue! 

For the `beach-vibes` wallpaper we have the legacy wallpaper named differently ("beach-vibe"), thus even if the wallpaper is migrated it is not found in the V2 wallpapers and also not being selected.

The `twilight-hills` wallpaper is the one that works fine because in the legacy wallpapers it implied using a file. For the other wallpapers, which in legacy were loaded from drawables, they fail to be applied because there is no `thumbnail`,`portrait` or `landscape` file for them. This case could be solved in this issue.

**Comment by MatthewTighe** [comment]
I think we should add the following to handle these special cases. Since this won't be long-lived code, I would prefer to handle every edge case explicitly even if the resulting code looks a bit hacky.

- For `beach-vibes`:
  - if `migrateLegacyWallpaper` is called with `beach-vibe` then copy the images to the correct path with the updated `beach-vibes` name **and** update `Settings.currentWallpaperName` to the updated name

- For `cerulean`, `amethyst`, and `sunrise`
  - if we can easily copy the wallpaper images from drawables to the correct updated path, we should do so
  - if we cannot easily copy them, we should instead download the updated assets using `WallpaperDownloader`

**Comment by delia-pop** [comment]
This is Verified as fixed on Nightly 107.0a1 from 09/29 with Google Pixel 6 (Android 13) and Xiaomi 12 Pro (Android 12). All wallpapers are correctly displayed on homepage and the thumbnails are selected after updating from an old build to the latest Fenix version. The wallpapers remain properly displayed when changing the orientation.
 
Note that due to https://github.com/mozilla-mobile/fenix/issues/27055 , the "Couldn't change wallpaper" snackbar is still displayed one time on homepage after dismissing the onboarding card, but after updating @Alexandru2909 on this, we agreed to continue the discussion over there and close this ticket as complete.

https://user-images.githubusercontent.com/89388888/193012879-37b2d761-8494-490d-bad5-4e3228b7ebf9.mp4

**Comment by delia-pop** [comment]
Verified as fixed on Beta 106.0b3 as well, with Lenovo Yoga Tab 11 (Android 11). All wallpapers are correctly displayed on homepage and the thumbnails are selected after updating from an old build to the latest Fenix version. The wallpapers remain properly displayed when changing the orientation.
