### ISSUE TITLE
[Bug]: Keep getting logged in on google automatically

### ISSUE THREAD

**Issue by bjorn3** [mozilla-mobile/fenix#26600]
### Steps to reproduce

I don't know how this keeps happening. Maybe accidentally clicking on an ad in youtube or clicking on a non-ad link in youtube?

### Expected behaviour

I don't get logged in on google unless I explicitly follow the login flow of google in the browser.

### Actual behaviour

Every once in a while I find myself to be logged in on google with the same user account as android despite the fact that I never logged in to google in the browser. After I log out it is fine for a while before I notice I am logged in again if I just so happen to visit a google website.

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

103.2.0

### Additional information

I don't want to ever be logged in to google in the browser. Especially not on a regular tab.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21363)

**Comment by bjorn3** [comment]
Update: It is indeed clicking on links in the youtube. Any way to prevent the in-app browser for youtube to store any data in the main firefox app? (I would write an addon for this if it was still possible to write addons for firefox for android.)

**Comment by amocirean** [comment]
Hello @bjorn3 , thank you for submitting the issue.
I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. Also, please provide more specific Reproduction Steps in order for your issue to be tested properly.
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Devices Used: Huawei P40 Lite (Android 10), Google Pixel 6 (Android 13).

**Comment by bjorn3** [comment]
I can't reproduce it anymore either. I guess google changed something in the youtube app to stop this.
