### ISSUE TITLE
[Bug]: Possible Memory Corruption?

### ISSUE THREAD

**Issue by Steve-0628** [mozilla-mobile/fenix#26661]
### Steps to reproduce

1. Open website https://misskey.io
2. Login and press some buttons, or just pressing the login button
3. Get glitches

### Expected behaviour

No glitches in website

### Actual behaviour

Many glitches

https://user-images.githubusercontent.com/49326405/186905247-2dbe8242-45ab-42ed-a7d4-88224d5de7e5.mp4

### Device name

Google Pixel 6a

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

104.1.0

### Additional information

This bug did not happen when I was using Android 12 on Pixel 6a. After my upgrade, this bug happend. 
I've tried clearing cache, deleting user data, rebooting the device. None of it helped.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21399)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1787520

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Thanks for reporting this bug @Steve-0628 .

Have you seen this on any other websites, or just the one you have linked to?

**Comment by Steve-0628** [comment]
Unfortunately, no. I've seen glitches on websites using the same source code as misskey.io, but not other. 
But I also have not seen websites with a lot of animations since I updated my phone, so I'm not sure if this is an misskey-only bug or not.

**Comment by N0ciple** [comment]
I confirm having the same problem on my Pixel 6A running Android 13 and Firefox 104.1.10.

The bug can easily be reproduced (for me) by going to any Wikipedia article and browsing the pictures.

Here is a quick video demonstrating the issue. There are roughly the same corruption pattern as the author video.

https://user-images.githubusercontent.com/19673370/189172033-45ca8800-f236-44ca-b188-f5c2680fa366.mp4

The visual glitches also appears on other websites, but I can consistently reproduce it on any Wikipedia article (with pictures) I tried.

For what it's worth, I don't remember having this issue with Android 12, but since I did not spend a long time with this phone on Android 12 I am not so sure.
