### ISSUE TITLE
Update ProGuard

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#2668]
Since GeckoView tightened their ProGuard rules, we need to bring ours up to date. This is a blocker for including a newer GeckoView release and also for shipping.

**Comment by sarentz** [comment]
[Bug 1550596](https://hg.mozilla.org/mozilla-central/rev/4fbfc8798cad) - Overly broad keep rule effectively disables proguard

**Comment by cpeterso** [comment]
@hawkinsw says he will submit a PR to fix Fenix's ProGuard rules.

**Comment by hawkinsw** [comment]
Related to #2612

**Comment by hawkinsw** [comment]
See #2716

**Comment by hawkinsw** [comment]
@cpeterso Do we want to close this?

**Comment by cpeterso** [comment]
> Do we want to close this?

Is there any Fenix engineering work left to do?

This issue has a vague title ("Update ProGuard") but it was opened specifically about the ProGuard issue that blocked Fenix from updating to a new GV version. With your fix for the kotlinx coroutine issue in #2716, Fenix since update to newer versions of GV. I'll assume we can close this issue for now.

**Comment by hawkinsw** [comment]
@cpeterso Sorry for the confusion. I didn't realize that this was not specifically related to the proguard rules. Had I known that, I would not have posted this. I'm really sorry! I hope that you weren't offended.

**Comment by cpeterso** [comment]
😄 No problem! Thanks for pointing out that this issue can be closed (and for fixing it). I'm sorry if my response above was terse. I just intended to recount our rationale for closing this issue if someone stumbles on this issue in the future.
