### ISSUE TITLE
When switching the system language, some items doesn't get translated without a restart

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#26728]
### Steps to reproduce

1. Open Fenix
2. Change the system's language to another (which is fully localized, I used Romanian and French and back to English).
3. Go back to Fenix.
4. Check the default browser banner button, on the homepage - the "Set as default browser" button
5. Open the main menu. Check the Settings button.
6. Open Settings, and check the sub-title of the Tabs menu.
7. Restart the browser. Check those items again.

### Expected behaviour

Everything should be translated without restarting the app.

### Actual behaviour

Everything seems to be translated, except these items which appear translated after an app restart.

### Android version

Android 9

### Firefox release type

Firefox Nightly, Beta and Release

### Firefox version

106, 105.b5, 104.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21431)

**Comment by Mugurell** [comment]
For technical notes this happens because of this code
https://github.com/mozilla-mobile/fenix/blob/ad1fd57b8fbbacdeac9694ab8980d5381e39c9e7/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt#L201-L203
with Nimbus apparently caching the value from when the app started.

&nbsp;

Just calling 

> FxNimbus.features.nimbusValidation.withCachedValue(null)

in `HomeFragment - onCreateView` - before the menu is created doesn't seem to fix the issue.

cc @jhugman

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812183

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
