### ISSUE TITLE
Detect when the connection is restored and refresh the page

### ISSUE THREAD

**Issue by tbertels** [mozilla-mobile/fenix#26809]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Like Chrome, Firefox Mobile should detect when the connection is restored and refresh the page instead of waiting for the user to do it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21472)

![Screenshot_20221024-223538_Firefox](https://user-images.githubusercontent.com/3265870/197624754-3fa6c697-0be9-4589-9230-2a0d91ff417f.png)

**Comment by tbertels** [comment]
@sum20156 That's great, feel free to do so! 🙂

**Comment by jonalmeida** [comment]
@sum20156 this issue hasn't yet been triaged and I can see some open questions that still need to be answered before a solution can be proposed: 
* What is the best way to know if a page needs to be refreshed? A responsive/PWA/offline-ready site might already be in a working state even after a connection is restored, so it would be wrong to automatically refresh the page for a user.
* When is the right time to refresh the page? If the connection is restored and the user is actively using the browser, it would be disruptive to refresh it page then (what is a reasonable idle time to do this?)
* Where should this feature request be fixed? Should this be fixed in [GeckoView](https://mozilla.github.io/geckoview/) which has the most control/context on web content, should something be exposed from GV for the apps to control, etc.

**Comment by tbertels** [comment]
@jonalmeida I've updated the description with a screenshot. So instead of saying "try reloading the page in a few moments", it should say "Firefox will let you know when this page is ready" with the ability to cancel it, like Chrome:

![Screenshot_20221024-223604_Chrome](https://user-images.githubusercontent.com/3265870/197624914-92c8c4f7-8cce-4189-a9e8-6ff2331b061e.png)

**Comment by sum20156** [comment]
@jonalmeida can you share some link of offline-ready pwa you are aware of.. I have to check how chrome handles it

**Comment by jonalmeida** [comment]
@sum20156 as mentioned above, this feature request hasn't been triaged yet, so please be aware that we might not be ready to accept a patch for this.

That said, you can try pokedex.org as one particular example if you'd like to do more investigation.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810842

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
