### ISSUE TITLE
[Bug]: The Wallpaper Selection Tool is not displayed on homepage

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26954]
### Steps to reproduce

1. Launch Fenix.
2. Dismiss the onboarding.
3. Visit a webpage and then return to homepage. Repeat this 2 more times.
4. Observe if the Wallpaper Selection Tool is displayed on homepage.

### Expected behaviour

The wallpaper selection tool is displayed on the third homepage visit.

As per requirements:
A wallpaper selection tool will be displayed on the homepage under the following the conditions:
- Tab Pickup and Jump Back In CFRs are not currently being displayed
- Wallpaper thumbnails have been downloaded
- The user has not seen the wallpaper selection tool before

### Actual behaviour

The Wallpaper Selection Tool is not displayed on homepage.
Note that the wallpapers were fully downloaded.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 106 from 09/13/Debug build updated from main 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21550)

**Comment by Mugurell** [comment]
Not sure the new tool is intended to be available in Nightly as it currently seems to be [available to just debug](https://github.com/mozilla-mobile/fenix/blob/3aff74b40ab5535cd8efe798f1bf44bac67df01f/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L115) but even in debug I see some potential issues when investigating this:
- we [wait until the jump back in cfr is shown](https://github.com/mozilla-mobile/fenix/blob/3aff74b40ab5535cd8efe798f1bf44bac67df01f/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt#L231). Seems like rather this tool should be managed also by the `HomeCFRPresenter` and not wait for other cfrs if it's conditions to be shown are met.
- [the check for ensuring all thumbnails are downloaded](https://github.com/mozilla-mobile/fenix/blob/3aff74b40ab5535cd8efe798f1bf44bac67df01f/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt#L513) currently fails because one thumbnail download errors with 404. 

@mavduevskiy

**Comment by MatthewTighe** [comment]
> * [the check for ensuring all thumbnails are downloaded](https://github.com/mozilla-mobile/fenix/blob/3aff74b40ab5535cd8efe798f1bf44bac67df01f/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt#L513) currently fails because one thumbnail download errors with 404.

I am curious if you're still seeing this issue, and for which wallpaper. The `dreamer` thumbnail was previously missing but has since been added and should work now. 

> we [wait until the jump back in cfr is shown](https://github.com/mozilla-mobile/fenix/blob/3aff74b40ab5535cd8efe798f1bf44bac67df01f/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt#L231). Seems like rather this tool should be managed also by the HomeCFRPresenter and not wait for other cfrs if it's conditions to be shown are met.

The intent is to wait until all CFRs have been shown before showing the wallpaper selection tool. That said, I think there is a follow-up opportunity to move all our logic around when onboarding is shown into a single class like the `HomeCFRPresenter`.

**Comment by MatthewTighe** [comment]
It's worth noting that the S3 bucket that hosts the wallpaper assets can take a while to refresh regional caches. I fixed the `dreamer` issue around 10 or 11 PST yesterday (about 24 hours before this comment) but we have seen it take a while for updates to propagate. It will be good to plan to update the remote server at least 48 hours in advance of any required deadlines.

**Comment by Mugurell** [comment]
> I am curious if you're still seeing this issue, and for which wallpaper. The `dreamer` thumbnail was previously missing but has since been added and should work now.

Yesterday and today I'm seeing the same wallpaper with problems - `innovator`.
Seems like it will stop causing issues after https://github.com/mozilla-mobile/fenix/issues/26971

**Comment by MatthewTighe** [comment]
Ah, looks like I actually forgot to add the assets for that one. Thanks for mentioning it! The update might take a while to propagate to the servers but they should be available soon

**Comment by delia-pop** [comment]
Hi, @MatthewTighe, on the latest Nightly 107.0a1 from 09/19 the wallpaper thumbnails from both Classic and Limited Edition collections are displayed and the wallpapers can be properly downloaded and set. Should the wallpaper selection tool also be available in Nightly any time soon?

**Comment by MatthewTighe** [comment]
It looks like we forgot to enable the feature flag 😅 We will land something today that should enable it in the next nightly

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/21 with Google Pixel 6 (Android 13). The wallpaper selection tool is displayed on the 3rd homepage visit. 

![1663766721143](https://user-images.githubusercontent.com/89388888/191519183-650ae6af-0c71-456f-88ec-4049f0a48be0.JPEG)
