### ISSUE TITLE
The Onboarding for an upgrading user flickers when bringing the app foreground on tablet

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26979]
### Steps to reproduce

1. Have an older Fenix version installed and sign in with a valid account.
2. Update Fenix to the latest version and launch it.
3. While the onboarding is displayed, send the app in background.
4. Bring the app foreground and observe the onboarding cards.

### Expected behaviour

The transition is done smoothly, without visual defects.

### Actual behaviour

On Lenovo Yoga Tab 11 (Android 11) tablet, the Onboarding displays an improper flicker when bringing the app foreground during which the homescreen is visible for a split second.

### Device name

Lenovo Yoga Tab 11

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 106.0a1 from 09/14

### Additional information

Note that this issue does not occur on the Google Pixel 6 (Android 13) phone device.

https://user-images.githubusercontent.com/89388888/190196370-e7f62a6e-67eb-4cb9-8a52-3efce3789261.mp4

https://user-images.githubusercontent.com/89388888/190196396-d38809a7-2d58-4278-adc6-fce82eb54b37.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21565)

**Comment by gabrielluong** [comment]
So, let’s say you’re on an old build, you are visiting [cnn.com](http://cnn.com/) and in the browser. You upgrade, and you see the home onboarding dialog for existing users. When the home onboarding dialog is dismissed, we expect the user to open back to the browser instead of the home screen. The current code is navigating to the browser and then home onboarding dialog. We could avoid the flickering by adding a new nav action to navigate to the home onboarding dialog with a popup to the browser.

**Comment by onemahon** [comment]
Bookkeeping note: adding to placeholder epic https://mozilla-hub.atlassian.net/browse/FXDROID-26 because this contains some useful information in the event that we use the MR onboarding for anything in the future.

If we don’t wind up using MR onboarding as part of that epic, this can likely just get closed out.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812465

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
