### ISSUE TITLE
[Bug]: Support more than 1 Nightly build per hour

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#27197]
### Steps to reproduce

Today [2 Fenix Nightly builds started in the same hour](https://treeherder.mozilla.org/jobs?repo=fenix&searchStr=apk&group_state=expanded&tochange=83c49cc050a5fdb7ebe67cf41c9f9303c9f88b00&fromchange=c7c5682104264ad1396fd0dc2852c0b9f9224b82&selectedTaskRun=edcEbb71SVmC6C2IzIQqEg.0) which generated the [same build ID](https://github.com/mozilla-mobile/fenix/blame/883401d8a4d80d58535d014c126009cca38076f6/buildSrc/src/main/java/Config.kt#L70) which prevented the second builds from getting uploaded to the Play store.

### Expected behaviour

The current logic can require to wait for up to an hour if new Nightlies are necessary. This should not happen because in blocks releases from going out.

### Actual behaviour

Same build id.

### Android version

bla

### Firefox release type

Firefox Nightly

### Firefox version

bla

### Additional information

cc @JohanLorenzo

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21680)

**Comment by JohanLorenzo** [comment]
Thanks for the ticket! I'm sorry, I don't think we're able to easily fix this.

Android versions code (aka buildIDs in Mozilla's jargon) are always increasing, Google Play rejects any version code lower than the current one. Because of this rule, the Fenix version code actually had to be greater than Fennec, when we migrated users and we cannot go back.

Moreover, version codes cannot be greater than this value[1]:

>  Warning: The greatest value Google Play allows for versionCode is 2100000000. 

That's why some people came up with this numbering scheme[2]. It allows us to number nightlies while ensuring we don't hit the maximum value right away. If I understand this sentence correctly:

> This yields a little under 15 years worth of hourly build identifiers

we will be running out of numbers in July or August 2030. I hope the Android ecosystem will allow for greater version codes then. I think we should cross that bridge when we get there. 

As far as I know, the number collision we saw yesterday is a first since 2015. Based on all that, I think we should keep the numbering scheme as is. If we change it, we will reduce how much time left we have until we run out of version codes. 

How does that sound to you @Archaeopteryx? 

[1] https://developer.android.com/studio/publish/versioning
[2] https://searchfox.org/mozilla-central/rev/34cb8d0a2a324043bcfc2c56f37b31abe7fb23a8/python/mozbuild/mozbuild/android_version_code.py#36

**Comment by kbrosnan** [comment]
bz-1137898 has a lot of the history around the decision about Android version codes.

**Comment by JohanLorenzo** [comment]
Thank you so much for digging that bug out, @kbrosnan! 

> If I understand this sentence correctly [...], we will be running out of numbers in July or August 2030. 

I might have misunderstood the sentence after all. This part of [bug 1137898 comment 20](https://bugzilla.mozilla.org/show_bug.cgi?id=1137898#c20) is interesting:

> The following patch sacrifices a high order bit to change the version
scheme, winning us roughly 15 years of hourly build IDs before we are
forced to lose another high order bit.  So it's clearly to our
advantage to change the scheme sooner rather than later -- we will
sacrifice 1 bit for 15 years of build IDs, rather than keeping the
current scheme and sacrificing (say) 2 bits for 3 years of build IDs.

Hey @ncalexan 👋  I know we're half-way through the 15 years and there is no rush here. That said, I prefer to ask now: do we have to do anything once first period of 15 years is over and we lose another bit? In other words, will we have to change the number scheme to accommodate the loss of a high order bit?

**Comment by ncalexan** [comment]
> Thank you so much for digging that bug out, @kbrosnan!
> 
> > If I understand this sentence correctly [...], we will be running out of numbers in July or August 2030.
> 
> I might have misunderstood the sentence after all. This part of [bug 1137898 comment 20](https://bugzilla.mozilla.org/show_bug.cgi?id=1137898#c20) is interesting:
> 
> > The following patch sacrifices a high order bit to change the version
> > scheme, winning us roughly 15 years of hourly build IDs before we are
> > forced to lose another high order bit.  So it's clearly to our
> > advantage to change the scheme sooner rather than later -- we will
> > sacrifice 1 bit for 15 years of build IDs, rather than keeping the
> > current scheme and sacrificing (say) 2 bits for 3 years of build IDs.
> 
> Hey @ncalexan 👋 I know we're half-way through the 15 years and there is no rush here. That said, I prefer to ask now: do we have to do anything once first period of 15 years is over and we lose another bit? In other words, will we have to change the number scheme to accommodate the loss of a high order bit?

Hi @JohanLorenzo -- sorry for the delayed reply: travel, the All-Hands week, and my current project, have made life very busy :)

Let me answer the immediate question first.  No, we do not _have_ to change the numbering scheme.  When we get close to running out of the existing 17 bits, we can elect to overflow into the reserved high-order 0 bit and continue more or less as we are.  This would give another `2**17 / (366 * 24) = ~14.92` years of hourly build IDs.

Can we do better?  I think we probably can, if we can incorporate some additional information (from _outside_ the build proper) into the calculation.  Two thoughts here:

1. We could make the version numbers dense by having a service that provided "next version numbers".  This would give, say `2**17` builds.  Were we to do say 4 Nightly builds a day, that would give us roughly `2 ** 17 / (366 * 4) ~= 60` years of builds.  However, builds are no longer "isolated" in the manner that Mozilla has historically espoused.
2. We could make the version numbers denser, but not maximally dense, by incorporating, say, days since January 1, 2030 and then a daily build counter.

There's some continuum here where we get a dense build number sequence but require centralization through denser but still sparse requiring less centralization all the way to our current sparse build number sequence that requires no centralization (but must discretize the build number space, leading to the "one build per hour" issue).

Now, do we **need** to do better?  I expect not: Android has accommodated additional high order bits with [`versionCodeMajor`](https://stackoverflow.com/q/52630237) in Android 28.  I have no idea how quickly we could _depend_ on Android 28, but I'd be inclined to do the simple thing: continue to exhaust our bit space with the current scheme for 6 years, evaluate, and then take our next 15 years, then transition to `versionCodeMajor=1` (assuming Android 28 is reasonable, which in 20 years, I expect it will be).

**Comment by ncalexan** [comment]
Oh: when we roll into the high-order bit, we could also take some of the unused lower order bits -- perhaps the `x` x86 bit and the `g` API version bit and have a larger space.

**Comment by JohanLorenzo** [comment]
Thank you for your thorough answer, Nick! 

TIL `versionCodeMajor`! I definitely agree on your latter strategy. Android API 28 was branded Android 9 (Pie), which was released 4 years ago and Google no longer provides security updates for it. I sincerely hope Firefox will be past that Android version 6 years from now 🙂 

In any case, thank you for the details about what we could do instead. At the moment, I believe we keep the current numbering scheme since scheduling 2 nightlies during the same hour occurs rarely. I'm going to close this issue, but feel free to reopen if you all disagree 🙂

**Comment by JohanLorenzo** [comment]
Sounds good. Done in [bug 1137898 comment 34](https://bugzilla.mozilla.org/show_bug.cgi?id=1137898#c34)
