### ISSUE TITLE
[Bug] IllegalStateException in WallpapersSettings 

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#27209]
Addressing the sentry [crash](https://sentry.io/organizations/mozilla/issues/3591939251/?project=6295546&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-2w&statsPeriod=14d)

How to reproduce: trigger the snackbar, leave the screen, press action button.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21687)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 107.0a1 2022-10-05 by performing the following steps:
1. Go to Settings -> Homepage -> Wallpapers;
2. Chose a new wallpaper;
3. Tap the back arrow in order to navigate to the previous screen and quickly tap the View option from the "Wallpaper updated!" snackbar.
However after the fix the "Wallpaper updated!" snackbar will disappear when navigating to a different section and the steps to produce the crash can no longer be reproduced. I will mark this issue as fixed.

https://user-images.githubusercontent.com/50983519/194307972-d91a22e6-d3ac-4a3e-a4e4-5465094f6bcb.mp4

### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
