### ISSUE TITLE
Location not working on GIS map

### ISSUE THREAD

**Issue by DanielSimonB** [mozilla-mobile/fenix#27239]
### Steps to reproduce

1.  I open this map on my phone:  
https://newtonmagis.maps.arcgis.com/apps/webappviewer/index.html?id=8916e8a5e54b42b0972bc9acc68b8099

2. I click on the location icon (the compass) in the upper left corner.

### Expected behaviour

A blue dot should appear at my location on the map.

### Actual behaviour

The blue dot never appears.

### Device name

Samsung Galaxys S10+

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.1.0

### Additional information

The blue dot appeared until a year ago.  Since then, I haven't been able to get it to work.  I have the Site Permission of Location set to "Ask to allow."  When I open the map, I get a request to allow location access.

I replicated the problem on a Samsung S22, on which I loaded Firefox today.  Firefox had never been used on this phone.

Both phones correctly display the blue dot when I load the map with the Chrome browser.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21702)

**Comment by makotokato** [comment]
Hmm, this site seems to call `navigator.geolocation.watchPosition` twice. If this call is one time, this should work. I can also reproduce the latest version of Fenix (with Pixel 6a + Android 13) using minimal sample (https://codepen.io/mkato/pen/BaxEEzG).

But I cannot reproduce this on GVE since GVE shows permission prompt twice. But Fenix shows one time only although `watchPosition` is called twice. a-c or Fenix?

**Comment by makotokato** [comment]
Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1812515

**Comment by boek** [comment]
Already moved to Bugzilla
