### ISSUE TITLE
[Bug] Undo snackbar is not displayed when removing a tab from a collection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2725]
## Steps to reproduce
1. Save a collection.
1. Remove a tab from the collection.
    1. Expected behavior
According to [mocks](https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/359019534), a snackbar confirmation with an undo button.
    1. Actual behavior
No snack bar with the Undo action.
    1. Device information

* Android device: Galaxy Note 8, P9 lite 
* Fenix version: 5/22

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11634)

**Comment by sblatz** [comment]
I tried working on this for a little bit. This is actually not possible given our current implementation of TabCollections. Their tabs are an immutable `List<Tab>`. Because of this, we have no way to update their list with that element removed (updating the view) without *actually calling the remove function on it*. 

This would require a-c to make the tab list mutable.

**Comment by sblatz** [comment]
You can find my quick attempt at it [here](https://github.com/mozilla-mobile/fenix/compare/master...sblatz:undo-for-tab-deletion?expand=1).

**Comment by vesta0** [comment]
Would love UX feedback on whether we should have an undo snackbar for removing a tab from a collection or whether we can make other design changes to mitigate the risk of accidental taps on remove tab.

**Comment by sblatz** [comment]
@vesta0, we can add this functionality, we just need an a-c fix for it :)

**Comment by pocmo** [comment]
@sblatz I wonder why we'd need to have AC return a mutable list here? With `lib-state` I assume we could keep the list in the `State` and while we show the undo snackbar we'd set a different list on the state until we get a new one from the storage (after actually removing)?

**Comment by sblatz** [comment]
@pocmo yes, that seems reasonable to me!

**Comment by abodea** [comment]
Reproducible on **Fenix 3.1.0-beta  3(Build #20092354) GV 72** with **Google Pixel 3a XL(Android 10).**

**Comment by Diana-Rus** [comment]
Reproducible with Google Pixel 3XL (Android 9) on Beta 5.0.0-beta.1 - 4/29

**Comment by AndiAJ** [comment]
Reproducible on 93.0.0-beta.1 using a OnePlus A3 (Android 6.0.1)

**Comment by surajeet310** [comment]
Is this issue still active ? Can I take it up ?

**Comment by topotropic** [comment]
we can use the same snackbar here as we use for when someone deletes the entire collection and update the copy to the following: 

`Tab deleted                     UNDO`

**Comment by amedyne** [comment]
@kycn see note from @topotropic above. And thanks @topotropic !

**Comment by kycn** [comment]
Looking at the current implementation for "Undo" functionality for collection and tab deletion, there is no straight-forward way to add "undo" functionality for the tab deletion from collections. Using existing functionality for a workaround (such as deleting/recreating a collection, removing/adding the tab subject to the undo, setting a new list to the collection after operation) is either a costly operation or potentially causing contaminated telemetries. 
One possible approach could have been faking the deletion of the tab on the UI (removing tab from the UI) until the duration for the undo operation ends and then taking the real deletion/undo action afterwards (which is updating the DB with the resulting tab list). Not-completed version of that solution (lines with TODO comments need to be satisfied) is as follows:

At `org/mozilla/fenix/home/HomeFragment.kt`
```
   @VisibleForTesting
    internal fun removeTabFromCollectionWithUndo(tabCollection: TabCollection, tab: ComponentTab) {
        val snackbarMessage = getString(R.string.snackbar_tab_deleted)
        lifecycleScope.allowUndo(
            requireView(),
            snackbarMessage,
            getString(R.string.snackbar_deleted_undo),
            {
                  // TODO: the undo operation
            },
            operation = {
                // actual removal of the tab, i.e. removal of the tab from DB that will result in updating the tab list in the collection
                lifecycleScope.launch(IO) {
                    requireComponents.core.tabCollectionStorage.removeTabFromCollection(tabCollection, tab)
                }
            },
            elevation = TOAST_ELEVATION,
            anchorView = null,
        )

        // TODO: fake removal of the tab, i.e. removal of the tab from UI but not from the DB until the Undo operation is completed with a success or failure
    }
```
 In order to proceed with this operation, further refactoring needs to be done on Storage, Store and Interactor layers as the tab list inside the collections are set via an observer of a livedata in the view layer, which blocks the fake removal of a selected tab from the list without causing issues on telemetries or further refactoring.
 I would appreciate for further comments/additions in case this explanation is not enough or clear @jonalmeida.

**Comment by jonalmeida** [comment]
We should file an issue explicitly to refactor Collections to follow the architecture, and then block this bug on that newly filed one.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807134

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
