### ISSUE TITLE
200ms regression Moto G5 startup: COLD VIEW nav start and COLD MAIN first frame

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#27461]
https://earthangel-b40313e5.influxcloud.net/d/s3AT6t7nk/fenix-startup-nightly-via-backfill-py?orgId=1&from=now-90d&to=now

Looks like the Moto G5 regression landed on 10/9 or 10/10. I don't know if it's related, but starting the same day, we have no startup test results from Samsung A51.

![image](https://user-images.githubusercontent.com/629193/196565690-fa531d21-2e5f-43fa-b776-1f56e7c3ddff.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21825)

**Comment by jonalmeida** [comment]
> I don't know if it's related, but starting the same day, we have no startup test results from Samsung A51.

Unrelated, @gmierz fixed this in Fenix by disabling one of the CFRs that had landed.

**Comment by Mugurell** [comment]
Interestingly when testing `fenix nightly cold_view_nav_start` on the oldest and newest merges from https://github.com/mozilla-mobile/fenix/pulls?q=is%3Apr+is%3Aclosed+merged%3A2022-10-08..2022-10-12+base%3Amain+sort%3Aupdated-asc+ on a OnePlus device I got very similar results, also when going more to the middle of the series.
On an emulator there would be a big disparity between each run.
Can try again on another device on Monday when I should get my Pixel3 back from being repaired - on that device I had more stable results.

**Comment by Mugurell** [comment]
Tested with a OnePlus 7T with Android 11 on the merges from https://github.com/mozilla-mobile/fenix/pulls?q=is%3Apr+is%3Aclosed+merged%3A2022-10-08..2022-10-12+base%3Amain+sort%3Aupdated-asc+  with
> python3 measure_start_up.py -c=100 --product=fenix nightly cold_main_first_frame < filepath >

and got the following results:

| Merge day | Revision # | Title | # runs | Max | Mean | Median | Min | Good | Graph |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 8 | effc40d | Import strings from android-l10n. | 50 | 1255 | 1221 | 1222 | 1196 | ✅ | - |
| 9 | 6c89feb0 | Update to Android-Components 107.0.20221009143152. | 100 | 1318 | 1219 | 1219 | 1190 | ✅ | - |
| 10 | 47b73363 | For #27016 - Ensure smooth search UX after the MR onboarding is closed | 100 | 1422 | 1224 | 1221 | 1196 | ✅ | - |
| 11 | fab8300a | For #27289: standardize coroutine usage in WallpaperFileManager | 100 | 1250 | 1219 | 1219 | 1186 | ✅ | - |
| 11 | 89df72b4 | Import strings from android-l10n. | 100 | 1258 | 1220 | 1220 | 1190 | ✅ | - |
| 11 | 8ed3bf7 | For #25980: Use new backQueue instead of removed backStack. | 100 | 1300 | 1269 | 1268 | 1237 | ❌ | - |
| 11 | c6ff008f | Update to Android-Components 107.0.20221011143144. | 100 | 1416 | 1273 | 1270 | 1239 | ❌ | - |
| 12 | 8b0fd1b8 | Update to Android-Components 107.0.20221011190253 | 100 | 1324 | 1268 | 1268 | 1236 | ❌ | - |
| 12 | 09b11da8 | For #27381 - Unregister FXA observer to prevent memory leaks | 100 | 1303 | 1268 | 1269 | 1241 | ❌ | - |
| 12 | 56c80f2 | Update to Android-Components 107.0.20221012190125. | 100 | 1374 | 1269 | 1267 | 1244 | ❌ | - |
| 12 | 09b11da8 | For #27381 - Unregister FXA observer to prevent memory leaks | 100 | 1303 | 1268 | 1269 | 1241 | ❌ | - |

Results available [here](https://drive.google.com/drive/folders/1GsN7KQyCI-SPRWo7U08XfTct4yQrI-qq?usp=sharing).

The results for `cold_main_first_frame` are impressively consistent and they show that https://github.com/mozilla-mobile/fenix/pull/25991 introduced the difference (the ✅❌❌ runs are in merge order).
That PR has multiple commits but I could not go deeper since when trying to build with only a subset of them the build would fail.
cc @mcarare.

**Comment by mcarare** [comment]
None of the changes in the PR touch code from the `HomeFragment` or `HomeActivity`.  So the regression might be inherently determined by one of the library updates. Unfortunately enough, all upgrades depend on each other, and the without the navigation upgrade we cannot proceed with compiling with Android 13.

I will take a look at each release note to see if something pops up, but I do not anticipate we can do much about this, other than trying to shave off time from what we did before the upgrades.

As a side note, I am curios why the graph shared by @cpeterso shows the spike in `cold_main_first_frame` **before** the dependencies updates landed.

**Comment by mcarare** [comment]
Note: Tested with the `fragment` library downgraded, the regression seems to be even bigger than with the current version.

**Comment by csadilek** [comment]
> As a side note, I am curios why the graph shared by @cpeterso shows the spike in cold_main_first_frame before the dependencies updates landed.

That just looks like an outlier we see every now and then, it becomes more obvious if you look at the last 90 days. Starting at the 10th both graphs show the increase.

I think it would be important to understand which of the library updates introduced the regression. We can also file a ticket then. Given this is 200ms on the G5, a profile comparing before/after could help narrow it down?

**Comment by mcarare** [comment]
Captured profiles on an Android 13 Pixel 4, no significant differences (~ 19 ms mean or less) between the versions.

On a Huawei, with Android 6, the difference seems to be due to `onLayout` calls:

After upgrades: https://share.firefox.dev/3SxPFK0 

<img src="https://user-images.githubusercontent.com/48995920/198055921-e5130bd4-0c62-4e58-af5b-fbe13e751bac.png" width = 185% />

Before upgrades: https://share.firefox.dev/3D7urwV


<img width="1779" alt="Screen Shot 2022-10-26 at 5 38 41 PM" src="https://user-images.githubusercontent.com/48995920/198056361-d862e6e5-5297-4b47-a824-f84273ae6819.png">


Note that other calls have significant improvement after the upgrades. For example, total layout inflation for `activity_home` and `fragment_home` drops from 401 ms to 311 ms.

**Comment by mcomella** [comment]
Triage: our understanding is that this is likely caused by an upstream dependency upgrade. The performance gets faster on some devices, like the A51. However, the Moto G5 and OnePlus 7T (from above) seem to get slower.

I noticed **the two profiles above are not comparable**: to make comparable start up profiles, **you must have Settings -> Remote debugging via USB set to off on start up for both profiles.** If you don't, some devtools scripts will execute on the parent process main thread, delaying start up. Here's where that code runs, which is only present in the second profile: https://share.firefox.dev/3szLGSH FYI @mcarare – please share with others who might not know this! It's unintuitive 😞

I recorded two profiles on my moto G5. Note that I made them directly comparable by clamping the end of the range to when the first frame was drawn (with the `onPreDraw` marker).
- Before (829ms to first frame): https://share.firefox.dev/3Dh2zpX
- After (1.2s to first frame): https://share.firefox.dev/3DclUc5

The main difference I see is that the UI operations seem to take longer across the board even though non-UI operations take roughly the same time, i.e. it doesn't seem to be caused by a regression in a specific view. Some thoughts:
- I have vague memories seeing a similar problem come and go: sometimes, a build would just take longer to do the UI things
- Could the device be more busy? e.g. maybe someone is using the disk more (since inflation likely reads the compressed layout files from disk) or we're executing more on background threads such that the main thread isn't getting scheduled as much or the CPU cache is invalidated more often (but I'm not sure the main thread ever context switches on start up)
- This could be a sampling issue: i.e. maybe the "before" profile is unrepresentative of the usual before case or the "after" profile is unrepresentative of the usual after case. fwiw, I took one more after profile and saw the same behavior

**Comment by mcarare** [comment]
@mcomella I did not change the remote debugging setting between the capturing of the profiles, in both cases, they were turned on.

**Comment by mcomella** [comment]
Looking back at the profiles mcarare posted in https://github.com/mozilla-mobile/fenix/issues/27461#issuecomment-1292166105, I noticed that `devtools` appears in both of them so I was wrong that they were totally uncomparable – so I just wanted to apologize for that.

That being said, they're likely comparable this way but it's possible the profiles are misleading – e.g. the added devtools code could change the scheduling of other code that changes the performance characteristics. We've never taken the time to verify whether or not this is true so, for simplicity, I always try to capture start up profiles with the Remote debugging setting disabled, especially if I want to look at code outside of the JVM (but if I'm capturing one profile to specifically look at JVM code, I don't bend over backwards to make sure it's off).

**Comment by mcomella** [comment]
Unrelated: in mcarare's profiles, I noticed a large gap where the JVM main thread isn't running so I filed https://github.com/mozilla-mobile/fenix/issues/27604 to see if this is a larger problem or a source of performance improvements.

**Comment by mcarare** [comment]
> for simplicity, I always try to capture start up profiles with the Remote debugging setting disabled, especially if I want to look at code outside of the JVM

@mcomella  Circling back to this detail, the messaging after activating profiling with `setup-startup-profiling.py` running instructs the opposite:
```

Startup profiling enabled on all future start ups, possibly even after reinstall.
Call script with `deactivate` to disable it.
DON'T FORGET TO ENABLE 'Remote debugging via USB' IN THE APP SETTINGS!
```

**Comment by mcomella** [comment]
That is misleading – my intention was that this message would help devs if they opened `about:debugging` and the device didn't show up but I can see why devs would just leave it on.

@mcarare Would you be interested in updating the message so it's clearer? Maybe in a future iteration of the script, we can pass an Intent extra that force disables "Remote debugging via USB" until the user explicitly enables it…

**Comment by cpeterso** [comment]
> Triage: our understanding is that this is likely caused by an upstream dependency upgrade. The performance gets faster on some devices, like the A51. However, the Moto G5 and OnePlus 7T (from above) seem to get slower.

What is the next step for this bug? Can we profile to identify which dependency regressed? Or should we accept this as our new baseline and close this bug as WONTFIX?

Note that we're standardizing on the Galaxy A51 for our perf tests and retiring the Moto G5 and Pixel 2. The A51's COLD VIEW time did not regress, so maybe we don't care about this Moto G5 regression?

**Comment by mcarare** [comment]
I did not succeed in pinpointing which dependency regressed, some combination of downgrading just one and keeping the others would result in a much bigger regression. 

As these updates are not something we can revert (some are mandatory for adopting Android 13) I think there is not much else we can do here.

**Comment by cpeterso** [comment]
In that case, I'll close this bug.
