### ISSUE TITLE
FNX3-16557 ⁃ Add tab cards to share sheet

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2754]
Parent: #331

The card on the top of the share sheet that shows the tab(s) being sent. On the right is what the share sheet currently looks like.

![](https://user-images.githubusercontent.com/1370580/58425209-3fb00d80-8067-11e9-8061-fa22e0217597.png)

**Comment by jonalmeida** [comment]
Spoke with Nicole and Vesta offline, we're going to going to use the same styling of collections for the tab list.

**Comment by colintheshots** [comment]
@topotropic 
1. How should this appear if I'm sharing a collection of series of tabs instead of a single tab?
2. What if I'm sharing a site from disk (bookmarks, history, collections, etc.) that I don't have a thumbnail handy for? It seems really inefficient to load the entire page only to present UI for sharing. Should we use some kind of placeholder?

**Comment by liuche** [comment]
Will try to get UX feedback by first day of sprint.

**Comment by liuche** [comment]
@topotropic @colintheshots how did this go? If it's ready to go just a reminder to move it into the Sprint Backlog.

**Comment by topotropic** [comment]
Yes, this got resolved – here's the updated spec https://share.goabstract.com/33797d88-bf55-41fb-9b7e-9e90e38ef645?mode=design&sha=0086540706ce6705ac5fe791cdf6fef98c9baf9f

- For sharing Open tabs, a collection or anything within the library we use a list element with favicon; the header on the share view should be updated from "Send and Share" to "Share"
- For sharing a page from the page 3-dot menu, we decrease opacity of the scrim so that the page is still visible

**Comment by sblatz** [comment]
@colintheshots are you planning on picking this up? :)

**Comment by colintheshots** [comment]
I'm still on this. I have most of it implemented. I'm adding the finishing touches.

**Comment by abodea** [comment]
Verified as fixed on the latest **`Nightly 190927 (#12700627)`** using Samsung Galaxy s10+(A9), Google Pixel 3a XL(A9).
Note that the behavior is the one presented in [this](https://github.com/mozilla-mobile/fenix/issues/2754#issuecomment-532317276) comment.
