### ISSUE TITLE
Implement remove button on search results from history page

### ISSUE THREAD

**Issue by itsmecom** [mozilla-mobile/fenix#27722]
It would be nice to have an remove icon on history search results.
this feature will help many users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21937)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21937

**Comment by cadeyrn** [comment]
In my opinion a visible icon would clutter the user interface. A better option would be a context menu on long press in my opinion.

**Comment by itsmecom** [comment]
either long press or icon anything can be fine. we only need this feature to be implemented.

**Comment by cadeyrn** [comment]
It's important *how* it will get implemented. As an permanent visible icon I am strongly against this feature. Without cluttering the UI it get my vote. This is an important consideration because it's seems obvious to me that most users won't remove history entries very often. But *every* user (with enabled history suggestions) *always* see the the history suggestions (and therefore also all the icons) when entering something into the address bar. So an icon for every history suggestion would be very distracting most of the time.

**Comment by cadeyrn** [comment]
Nevermind, I didn't read carefully enough. I thougth it was about the address bar suggestions, but it's about the history page as described in the issue title.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810837

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
