### ISSUE TITLE
Nimbus Experiments rework to compose

### ISSUE THREAD

**Issue by vrrashkov** [mozilla-mobile/fenix#27819]
Rework Nimbus experiments to be using compose.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21979)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813421

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
@vrrashkov We're moving the Firefox Android bug tracking from GitHub to Bugzilla. This bug is now Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1813421. You'll need to add yourself to that Bugzilla bug.

Also, in mid-February, we'll be moving the Firefox Android code from this fenix GitHub repo to the new firefox-android GitHub repo: https://github.com/mozilla-mobile/firefox-android. You'll need to rebase your new PR to this firefox-android repo.
