### ISSUE TITLE
Login Details page should be shown after adding a login

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27855]
### Steps to reproduce

1. Go to Settings -> Logins and Passwords -> Saved Logins
2. Tap on `Add login`
3. Enter valid login info
4. Tap on the save button

### Expected behaviour

`LoginDetailFragment` page is shown so that the user can view the newly added login (same as desktop Firefox).

### Actual behaviour

`SavedLoginsFragment` page is shown (list of logins).

### Device name

Google Pixel 3a (emulator)

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1

### Additional information

This issue was created due to this discussion: https://github.com/mozilla-mobile/fenix/pull/27816#discussion_r1022864640

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21994)

**Comment by hakeem-gitstart** [comment]
Hello,

looking at picking this up, after some investigation, i realise it might not be so flexible to re-use the `loginDetailFragment` page navigating from the `addLoginFragment` because of the required argument on the `loginDetailFragment`. so if creating a `new fragment` that looks like `loginDetailFragment` will be a suitable approach ?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815628

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
