### ISSUE TITLE
[Bug]: Opening addons.mozilla.org and attempting to install an add-on downloads an `.xpi` file

### ISSUE THREAD

**Issue by padenot** [mozilla-mobile/fenix#27923]
### Steps to reproduce

- Google `ublock origin firefox` from Firefox for Android
- Open the first result (pointing to https://addons.mozilla.org/fr/firefox/addon/ublock-origin/)
- Tap the button to add the addon to Firefox

### Expected behaviour

The addon is added to Firefox

### Actual behaviour

An `.xpi` file is downloaded

### Device name

Sony Xperia 5 II

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

109

### Additional information

I'm told by the AMO team to open a ticket here, and another one on their repo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22022)

**Comment by diox** [comment]
This happens because [the regexp Fenix uses to intercept xpi requests](https://github.com/mozilla-mobile/fenix/blob/43612486e42dd2f55f07cdf00a693f80af5bcc88/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt#L196) wants paths to contain `/android/`. Ideally it should be relaxed to also allow `/firefox/`, but there would be another issue: the collection Fenix uses as an allow list uses `/android/` URLs, so that would prevent the install as well.

As @padenot noted, there is now [an issue file on AMO about this](https://github.com/mozilla/addons-frontend/issues/11920), because AMO should show a warning suggesting to go to https://addons.mozilla.org/fr/android/addon/ublock-origin/, which has the correct download URL Fenix would recognize. Still, it may be worth looking into this issue could be avoided on the Fenix side as well.

**Comment by kbrosnan** [comment]
Not a Fenix bug.

**Comment by diox** [comment]
Why is it not a Fenix bug ? As I pointed out, it is caused by the fact that Fenix regep is too restrictive.
