### ISSUE TITLE
Cannot use vendor-spcific serif fonts 

### ISSUE THREAD

**Issue by hingbong** [mozilla-mobile/fenix#28001]
### Steps to reproduce

1. Use a Android phone that use vendor-spcific fonts
2. Use Firefox browse any sites 

### Expected behaviour

Should use vendor-spcific system's fonts to display contents 

### Actual behaviour

Just use fonts such as Noto Serif

### Device name

Moto edge 30 ultra

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

107

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22067)

**Comment by makotokato** [comment]
@hingbong

> Use a Android phone that use vendor-spcific fonts

Firefox sets default font as Noto Font. Is this issue that you want to change default font? (I guess that Moto Edge 30 Ultra has system preference to change default font, right?)

(If you are using Firefox beta or nightly, you can change default font via `about:config` (`font.name-list.<font family>.<language>`)

**Comment by CoelacanthusHex** [comment]
> @hingbong
> 
> > Use a Android phone that use vendor-spcific fonts
> 
> Firefox sets default font as Noto Font. Is this issue that you want to change default font? (I guess that Moto Edge 30 Ultra has system preference to change default font, right?)
> 
> (If you are using Firefox beta or nightly, you can change default font via `about:config` (`font.name-list.<font family>.<language>`)

I hope that Fenix ​​can behave the same as Firefox on Linux. For font families like sans serif, the default is to directly query the fonts of the system, instead of a built-in list by default, and let the user set it on the system (whether it is the interface provided by the system or use methods like magisk) After that, you need to set it again in the Fenix ​​settings.
The next best solution is to keep the current default value unchanged (if the developer has any reason to adopt this solution), add an option in the settings to allow users to choose to switch to using The fonts corresponding to these font families provided by the system. This is much better than asking users to hardcode their system font settings in about:config.

**Comment by CoelacanthusHex** [comment]
If you are worried that there will be problems with the font list returned by the system and the fonts that can be displayed cannot be found correctly, then you can append this built-in fallback list to the end of the font list provided by the system.

**Comment by boek** [comment]
Dup of #19985
