### ISSUE TITLE
Ability to opt in to receiving push notifications

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#28021]
This feature gives users the ability to opt in to receiving notifications. DDG example below.
![index](https://user-images.githubusercontent.com/6579541/204598596-1bae762a-6184-4a69-ab92-f57e8010326d.png)

**Acceptance Criteria**
As a user, I want to be able to opt in to receiving push notifications on my Android phone so that I can be reminded to use the app.
-  Firefox should ask for permission to send user push notifications on first app launch or after the app has been re-installed and launched
-   Applicable for Android 13 and higher users and only new users (users who have never installed Firefox)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22077)

**Comment by Mugurell** [comment]
It seems to me that DDG asks for notification permission in the onboarding step.
Probably because of the queue used in the merged patch I see it is possible to get the new prompt after users started browsing in which case it might seem similar to the other prompts we know from desktop where a website is asking to send notifications.

<img src="https://user-images.githubusercontent.com/11428869/205622870-0842c529-9fa6-44aa-b547-40e1d123a310.png" width="50%" />

Maybe as a followup this permission can be added to onboarding for new users and be put first in the queue for existing users - or even show the app homescreen and trigger the permission request there instead of opening the app to a tab?
For runtime permissions the overall context is very important in ensuring users understand and choose appropriately what the behavior should be and in the above video I would be left with the question: "Why / what type of notifications does Firefox wants to send me?".

**Comment by delia-pop** [comment]
Verified as fixed in Nightly 109.0a1 from 12/03 with Google Pixel 6 (Android 13).
The following were noticed: 
- the push notification is received in ~ 5 seconds after launching Fenix (as a new user, after re-installing and launching Fenix, or after updating the app);
- the user's choise is correctly reflected by the state of the Notification toggle in the Settings > Notifications screen;
- if the notification is dismissing by tapping on the screen or on the device's back button, it will be displayed again after bringing the app foreground or after restarting the app;

https://user-images.githubusercontent.com/89388888/205667882-ea216ef6-da73-49bb-9d0b-94926427482a.mp4

I will remove the qa-needed label and leave the ticket opened for further discussions.
