### ISSUE TITLE
Add telemetry for Share button(from 3-dot menu)

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#28033]
## What questions will you answer with this data?
- How often do users use the Share button to save or share links/urls?
- How and where do users Share these links? Is it to another device (linked to their Fx accounts), email, text, bluetooth, etc..?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22081)

**Comment by kbrosnan** [comment]
We had https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/quick_action_sheet_share_tapped but it expired.

**Comment by amedyne** [comment]
Thanks for checking this @zmckenney. As for point 2, is there a way to track whatever action the user does at least for the current options available? Is there a way to implement this so that when another app/action is added, we don't have to modify the telemetry ping.

**Comment by zmckenney** [comment]
@amedyne Sorry I think I was a little unclear on point 2. I don't see any event in our metrics which would satisfy selecting an app/action from the share menu. If we do add an event for it we fortunately could add something like `share_to_app` with the string extra as the package name of the app or action the user tapped. This would mean we wouldn't have to change the telemetry ping for any new apps or actions in the future.

**Comment by amedyne** [comment]
Seems like for point 2, adding a new event is what we need.

**Comment by zmckenney** [comment]
@amedyne I've implemented this so we capture the user interaction and intent but not necessarily if the share request to the app was successful. If we want we could create a `share_to_app_failure` and capture those errors too.

**Comment by mavduevskiy** [comment]
@amedyne 
I wonder if we have any interest in how often people share links by selecting them as text and sharing via the android action menu for the sake of comparison?

**Comment by zmckenney** [comment]
@amedyne The data collection review is asking if we are really sure we need to know what specific app a user is sharing to. If so, we will need a Data Collection level 3. Based on what you said above I think we will need this but as an idea we could potentially narrow it down to the most beneficial metrics like "email", "messaging", etc. although this is tricky since we only send plain text. If we wanted this method it would be a manual mapping of the selected app to the correct type (ex. `com.google.android.gm` -> "email") unless we want a more robust solution through a much larger refactor.

**Comment by zmckenney** [comment]
@amedyne I talked with @rocketsroger about the sensitive data collection for app package and app name. This is due to a user who may have private apps on their device or who may have apps with their name. 

To prevent this we can use the apps package name (ex. `com.google.android.gm`) but we would need to create a list of public apps we would like to track. Anything that isn't in our tracked app list would be sent as "other" or "na".

**Comment by amedyne** [comment]
Per our private discussion, I recommend we create a list for top PlayStore apps (like Gmail, Facebook, Messages,Instagram) top 5 messaging apps, top 5 note taking apps.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815623

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
