### ISSUE TITLE
Show the search query in the address bar in both edit and display mode

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#28155]
Currently the app will show the search term (if available) when the user taps the toolbar to allow easily modifying the current search.
@Verdi recommended to also show the search term (if available) while in display mode - the toolbar is not focused, user is not actively interacting with the search term. This should allow the user have more context about the results they are seeing and know the current query.
Safari on iOS does this already.

![image](https://user-images.githubusercontent.com/11428869/206756155-21313164-0b97-435e-b6a0-b0b5bd0f7c5d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22129)

**Comment by delia-pop** [comment]
Verified as fixed in Nightly 110.0a1 from 12/19 with Google Pixel 6 (Android 13). The search term is now displayed in the URL bar in edit mode and display mode, while the Unified Search is enabled.

![1671461716273](https://user-images.githubusercontent.com/89388888/208454153-34e040ac-377f-4002-95f9-7bdec5b35ed5.JPEG)
