### ISSUE TITLE
[Bug]: Google Search Fixer not loading/working - Android

### ISSUE THREAD

**Issue by chrispina** [mozilla-mobile/fenix#28278]
### Steps to reproduce

Have tried troubleshooting in the FF reddit and was directed to post here.

1.  Install Google Search Fixer add-on to FF or Beta (allow in private browsing)
2.  Attempt Google search in browser

Have tried with or without Adguard, have reinstalled FF and Beta, have cleared all data and cache, have rebooted phone, etc l.

### Expected behaviour

Pretty Google results should appear, Add-on should be in list of Add-ons.

### Actual behaviour

See Google search results in ugly non-chrome version.

Look for add-on in Add-ons list and it's not there, but does show as installed in Add-ons Manager

![Screenshot_20221221_111403_Firefox Beta](https://user-images.githubusercontent.com/121187435/208964756-a673587e-4a06-4567-af8c-00fa9229a961.jpg)

![Screenshot_20221221_111408_Firefox Beta](https://user-images.githubusercontent.com/121187435/208964793-95fc24a0-a179-47d1-8606-08b51f7ecd6d.jpg)

### Device name

Samsung Galaxy s21 Ultra

### Android version

Android 13

### Firefox release type

Firefox Beta

### Firefox version

109.0b2 (Build #2015922379), 6380aceb5+ AC: 109.0b2, bc9bb4c598 GV: 109.0-20221218190303 AS: 96.1.3

### Additional information

![Screenshot_20221221_104848_Firefox Beta](https://user-images.githubusercontent.com/121187435/208965997-23ebb588-67ca-4760-a03a-a1944ff43952.jpg)
![Screenshot_20221221_104913_Settings](https://user-images.githubusercontent.com/121187435/208966020-d3732b82-0156-49b0-aace-b740242d02c2.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22179)

**Comment by chrispina** [comment]
I removed uBlock.  Removed and reinstalled Google Search Fixer. Same issue.

**Comment by sheikh-azharuddin** [comment]
It's not issue..in the 3 dot menu under add ons you won't see the Google search fixer..expected behaviour.
Best way to test, is just search " what is my user agent", if it shows chrome then addon is working .

Check below screenshot. As you can see it is showing chrome version 114 but there is none! Now remove the add on and search again I am sure you will get different search page( old age ui) and user agent also will be different (true firefox)

![Screenshot_2022-12-24-19-49-34-207-edit_org mozilla fenix](https://user-images.githubusercontent.com/58127841/209439778-719bb326-249a-4178-973f-8d811356ce79.jpg)

**Comment by chrispina** [comment]
This appears to be correct.  Fixer previously showed in my Add-ons and no longer does, but it appears to be working as intended.  Thanks!

**Comment by chrispina** [comment]
This appears to be correct.  Fixer previously showed in my Add-ons and no longer does, but it appears to be working as intended.  Thanks!
