### ISSUE TITLE
[Bug] Fenix no longer supports Lockbox (Lockwise)

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2828]
## Steps to reproduce
1. Go to website that you need to log in to. 
1. Long press username field

### Expected behavior
Lockbox should automatically present a prompt upon page load, however in its absence, one of the options should be "Auto fill" which should load Lockbox. This was working and has stopped, so I suspect it's a regression. Also given the Auto Fill option is also missing in Fennec, it could be a regression to do with Fennec. Though Fennec does offer the various logins upon tapping the username field. 

### Actual behavior
Nothing. 

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1921

**Comment by cadeyrn** [comment]
I cannot confirm, Lockbox still works in Fenix. I guess the real problem is the fragility of Lockbox. I have to start and unlock Lockbox very often to make it work, but that's not a regression, it was always a problem with Lockbox. I never used another password manager on Android so I can't compare to others.

**Comment by pwd-github** [comment]
Resetting Fenix (clearing data) fixed the issue.
