### ISSUE TITLE
[Bug]: User can delete all search engines from settings

### ISSUE THREAD

**Issue by DreVla** [mozilla-mobile/fenix#28298]
### Steps to reproduce

1. Tap the settings button
2. Tap the search menu
3. Delete all search engines

https://user-images.githubusercontent.com/32488956/209303700-bc604555-1186-4a2f-8b20-1fbb3676ba80.mp4

### Expected behaviour

The user should not be able to delete the last remaining search engine from the list.

### Actual behaviour

The user is able to delete all search engines from the list

### Device name

OnePlus 6

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22190)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 110.0a1 from 12/24 with OPPO A15s (Android 10). The user is no longer able to delete the last search engine since the 3 dot -menu containing the "Delete" option is no longer available for the last search engine. 

![Screenshot_2022-12-30-13-12-44-38_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/89388888/209659118-49768eba-e885-4078-9532-125d047acdac.jpg)
