### ISSUE TITLE
[Bug]: Instagram app can be zoomed when switch is set to OFF on a specific device 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#28290]
### Steps to reproduce

1. Launch the Firefox app.
2. Go to www.instagram.com website.
3. Zoom in on the open web page.

### Expected behaviour

Instagram app can't be zoomed when switch is set to OFF 

### Actual behaviour

Instagram app can be zoomed when switch is set to OFF 

### Device name

Sony Xperia 

### Android version

Android 6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1 - 22/12

### Additional information

This issue is also reproducible on Firefox 109.0b3.
This issue is not reproducible on the Firefox 108.1.0.
This issue was not reproducible on other devices.

https://user-images.githubusercontent.com/108326843/209148640-817e1a87-fa2a-48d7-97ce-bbd85943c23b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22185)

**Comment by Mugurell** [comment]
That switch does not disable zooming but rather force allowing to zoom even on websites which don't support such a gesture.
So it is expected that various websites can be zoomed with the `Zoom on all websites` option toggled off.

Because Chrome has a similar toggle and functionality can you also check what's the behavior there for comparison?

**Comment by AdinaPetridean** [comment]
@Mugurell indeed this is reproducible also on Chrome.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807013

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
