### ISSUE TITLE
FNX3-16615 ⁃ [Bug] Fenix device not showing up in FxA device list

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#2831]
STEPS TO REPRODUCE

1. Authenticate a Fenix device by pairing or manually
1. Visit device on FxA settings

EXPECTED RESULTS

* Firefox for Android appears in list as a Sync device
![](https://user-images.githubusercontent.com/68213/58345297-ff158180-7e25-11e9-9222-8e2625a52a1c.png)

ACTUAL RESULTS

* Does not appear in any form

![](https://user-images.githubusercontent.com/68213/58345114-9af2bd80-7e25-11e9-84c3-14941f0a900c.png)

**Comment by mheubusch** [comment]
@vesta0 according to vladikoff  this  will  be fixed  with the next FxA release on Monday or Tuesday.

**Comment by rfk** [comment]
This is a display issue on the FxA side, we landed a partial fix in https://github.com/mozilla/fxa/pull/1178 and I'm working on a more complete fix in https://github.com/mozilla/application-services/issues/1125

**Comment by tv-zkal** [comment]
> 
> 
> This is a display issue on the FxA side, we landed a partial fix in [mozilla/fxa#1178](https://github.com/mozilla/fxa/pull/1178) and I'm working on a more complete fix in [mozilla/application-services#1125](https://github.com/mozilla/application-services/issues/1125)

Will this also fix older, already uninstalled, copies of Fenix from showing up on the "Send tab" feature?

**Comment by rfk** [comment]
> Will this also fix older, already uninstalled, copies of Fenix from showing up on the "Send tab" feature?

No, I don't believe so. When the "more complete fix" mentioned above lands you should be able to go into "devices and apps" on the web and delete them manually.

**Comment by pwd-github** [comment]
This still isn't fixed despite whatever was supposed to have been pushed on Monday/Tuesday last week.

**Comment by rfk** [comment]
> This still isn't fixed despite whatever was supposed to have been pushed on Monday/Tuesday last week.

They are showing up after the push last week; unfortunately they show up named very generically "Firefox Sync" rather than "Firefox Preview" or similar, which makes them hard to spot:

  https://github.com/mozilla/fxa/issues/1397

The backend changes required for https://github.com/mozilla/application-services/issues/1125 have landed, the remaining piece is updating the front-end code to use them.

**Comment by pwd-github** [comment]
> > This still isn't fixed despite whatever was supposed to have been pushed on Monday/Tuesday last week.
> 
> They are showing up after the push last week; unfortunately they show up named very generically "Firefox Sync" rather than "Firefox Preview" or similar, which makes them hard to spot:
> 
> [mozilla/fxa#1397](https://github.com/mozilla/fxa/issues/1397)
> 
> The backend changes required for [mozilla/application-services#1125](https://github.com/mozilla/application-services/issues/1125) have landed, the remaining piece is updating the front-end code to use them.

I have two devices with Fenix on it and only one "Firefox Sync", will the above also fix that or should I file a separate bug for that?

**Comment by rfk** [comment]
https://github.com/mozilla/application-services/issues/1125 will also fix that, thanks for checking.

**Comment by TinyBeard** [comment]
Also experiencing this on Firefox Preview Nightly 190710 06:03

Device using Fenix doesn't apear on "Send Tab to device..." at all. The only relevant entry on device list seems to be "Firefox Sync", but it doesn't look like regular device, also the only option is "Revoke" rather than usual "Disconnect..." for other devices.

**Comment by dholbert** [comment]
FWIW, I synced using the https://accounts.firefox.com/pair/ flow, and that produced an entry for Fenix that was (somewhat confusingly) called "Firefox Sync" in my FxA device list.  (Fenix sync settings does have a spot where I could supposedly choose the device name, and it defaulted to "Google Pixel 3", which is indeed what my phone is; but nonetheless it shows up as "Firefox Sync" in the FxA list.)

**Comment by dholbert** [comment]
Here's the Fenix sync UI, for me (immediately after linking with Sync) -- note "Device Name":
![image](https://user-images.githubusercontent.com/426803/61075987-0392fb00-a3d0-11e9-9b41-e37abca238f5.png)

... vs here's how it shows up at https://accounts.firefox.com/settings/clients :
![image](https://user-images.githubusercontent.com/426803/61075808-a7c87200-a3cf-11e9-9612-f9281ba4c04f.png)

**Comment by ryanfeeley** [comment]
@rfk Does the device name set in Preview get ignored? If so, on the client side we should fix it to be Firefox Preview and made it unreadable (but ideally we can get the renamable device).

**Comment by pwd-github** [comment]
Both of my Fenix devices have disappeared from my other devices. I have to send tabs to and from said devices via Fennec.

**Comment by ryanfeeley** [comment]
@vladikoff Do you know when the device name set manually in Fenix will be appearing in fxa device manager?

**Comment by vladikoff** [comment]
I think the only way this is gonna show up is when send tab gets enabled in Fenix. @grigoryk @rfk confirm?

**Comment by rfk** [comment]
So there are a couple of things happening here, which I'll try to tease apart.

1) Fenix needs to include the "device name" in its device record registration after the user has logged in. I don't recall whether it will always do this, or will only do it when the send-tab feature is enabled. @grigoryk can you confirm whether device-registration is bound to send-tab, or separate? Assuming that the name shown on the client is actually being registered with the server, it would ordinarily show up under that name in the devices-and-apps list on the account settings page.  However...

2) The devices-and-apps list does not show correctly show device records for OAuth clients, and instead just shows a single generic entry per OAuth `client_id`. I believe this is now fixed on master as of https://github.com/mozilla/fxa/pull/1262 and will be in production within a week or so. When this fix ships, the correct device name (e.g. "Google Pixel 3") should start showing up in the devices-and-apps list, *assuming* that (1) above is working correctly.  In the meantime, it shows a single record named "Firefox Sync", because...

3) The OAuth client name for Firefox Preview is currently set to the generic value "Firefox Sync" rather than something more specific like "Firefox Preview". This was done so that the login screen would say "Continue to Firefox Sync", but it had the unintended side-effect of showing up as "Firefox Sync" in other places in the account management UI.  This is tracked in https://github.com/mozilla/fxa/issues/1397.

Let's see how the devices-and-apps list looks after FxA train-141 ships to production this week (ref https://github.com/mozilla/fxa/issues/1397), then we can see what the next steps are from there.

**Comment by rfk** [comment]
> Let's see how the devices-and-apps list looks after FxA train-141 ships to production this week
> (ref https://bugzilla.mozilla.org/show_bug.cgi?id=1564489)

So this is now live. The good:

* I see multiple instances of Firefox Preview if I have multiple instances connected.
* The device name accurately reflects what I enter in Firefox Preview settings

The still-needs-work:

* Firefox Preview now has a "desktop" device icon; this was fixed in appservices v0.32.1 (ref https://github.com/mozilla/application-services/pull/1314) and is just waiting on uplift to latest Fenix release
* If you've been signing in and out of Firefox Preview, you'll see a bunch of old devices in the list. This will improve somewhat when we add support for explicit device teardown as part of signout, ref https://github.com/mozilla/application-services/pull/1414.
  * At least you can now go in and clean them up manually, which is an improvement!

**Comment by jdragojevic** [comment]
Done!
