### ISSUE TITLE
[Bug]: Save as PDF: unable to select or search text on the generated PDF. Text rendered as vector paths

### ISSUE THREAD

**Issue by kirisakow** [mozilla-mobile/fenix#28327]
### Steps to reproduce

This is the PDF file I saved earlier this morning from a paywall-protected media aggregator: 
[article.figaro.expatriés.fuient.Londres.pdf](https://github.com/mozilla-mobile/fenix/files/10313602/article.figaro.expatries.fuient.Londres.pdf)

### Expected behaviour

Text of the generated PDF file should be selectable and searchable

### Actual behaviour

Text of the generated PDF file is not selectable or searchable. Also, text appears to be made of vector paths (which I found out with Inkscape)

### Device name

Lenovo P2

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22203)

**Comment by delia-pop** [comment]
Hi, @kirisakow, thanks for reporting. 
I tried to reproduce the issue your experiencing with Lenovo Yoga Tab 11 (Android 11) on the latest Nightly 110.0a1 from 01/03. 
Indeed, the text on the generated PDF is not selectable, but I believe this behavior could be caused by the website, in the attempt to restrict data sharing, rather than it being a Firefox issue. The text cannot be selected on Chrome either, on both Desktop and Mobile versions. 

Could you also try saving public article (e.g. from https://getpocket.com/explore) with the Save as PDF function to see if you're still experiencing this behavior? Thank you!

**Comment by kirisakow** [comment]
Indeed, PDFs of webpages from other resources allow for both text selection and search.

My previous experience must be a result of an anti-feature deliberately implemented by developers of that press aggregator.
