### ISSUE TITLE
Remove duplicate entries in a tab collection

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#2917]
### Why/User Benefit/User Problem
As a Fenix users I don't want to have a duplicate URL in my collections.

### What/Requirements
Remove/don't add duplicate URL entries to a tab collection.

### Acceptance Criteria (how do I know when I’m done?)
I only see one of each URL in a tab collection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11776)

**Comment by liuche** [comment]
Is this dependent on Collections work? If it's a small effort for UX and eng, we should do it.

Very quick UX question:
- should we just fail silently and not add it
- should we show a toast explaining what happened
- Fail silently and move item to the "newest" spot?
- something else?

**Comment by ekager** [comment]
Hm so one question I have is that tab collections are "sessions" with a back history. I agree it's not ideal to have seemingly duplicate URLs, but I don't think we should be checking for duplicates based on the most recent URL when there could be more?

**Comment by topotropic** [comment]
> Hm so one question I have is that tab collections are "sessions" with a back history. I agree it's not ideal to have seemingly duplicate URLs, but I don't think we should be checking for duplicates based on the most recent URL when there could be more?

Do we preserve the stack? I just searched for "New York Times" opened nytimes.com from the results, saved it to a collection, opened it from the collection and when I tapped on the back button I got send to the Firefox Preview home screen instead of the search result page.

**Comment by madb1lly** [comment]
Hi all,
I also find it bizarre and unwieldy that saving tabs with an identical URL creates a duplicate tab. If I open a collection, work through some tabs, browse some, close some, open some new ones, but many stay unchanged, then when I save the collection, if I save to the existing collection, I get duplicate tabs. This doesn't make sense to me - the workaround is to either close duplicates or save to a new collection and delete the original one.

@topotropic if the history is not saved, then I see no reason why saving a tab to a collection with an existing identical tab should create a duplicate. However, if history _should_ be saved (but is not, because of #5208 and https://github.com/mozilla-mobile/android-components/issues/5529) then it would make sense to save the tab as a duplicate URL, because the history is different.

However, going back to my example in the first paragraph, if tabs remain unchanged, then saving to an existing collection should not create duplicates, i.e. if all properties of the tab are the same, then don't duplicate the entry in the collection.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812766

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
