### ISSUE TITLE
FNX3-16707 ⁃ [Bug] The fav icons from "Open Tabs" section are changed when navigating to a website

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#2964]
## Steps to reproduce
1. Install and launch Fenix.
1. Access any website*`youtube, amazon, twitch, twitter`* website.
1. Navigate to any section in any of the website mentioned above.
1. From the website tap on the tabs section.
    1. Expected behavior
The fav icons from **`Open Tabs`** section are displayed with the visited website logo(example amazon)
    1. Actual behavior
Fav icons are changed to a simple placeholder for example on amazon is displayed a capital "A" instead of amazon fav icon.
    1. Device information

* Android device: **`Samsung Galaxy Note 9(Android 8.1.0), Google Pixel 3(Android 9).`**
* Fenix version:  **`1.0.1922 (#build 11481811) 28/5`**
    1. Notes
Please note that no matter what website you use, after reaching any other section of it, the fav icon will change, but if you go back to homescreen for example on amazon, the fav icon will change to the right one.
For more details please see t he attachments: [Video](https://drive.google.com/file/d/15te4r7iPwKVILsrHLUX4Qf38NHWb2EnT/view?usp=sharing) and [logcat.txt](https://github.com/mozilla-mobile/fenix/files/3231732/logcat.txt).

**Comment by vesta0** [comment]
@pocmo do we know why this happens?

**Comment by pocmo** [comment]
Related: #3846 - the tabs tray doesn't update automatically when the icon is loaded while the tabs tray is displaying.

**Comment by AndiAJ** [comment]
Hi, I've just tested this issue on latest Nightly Build #12400613 28/8 using a Google Pixel 3a (Android 9) and noticed the following:

<details>
    <summary>1. Websites for which the Fav icons get instantaneously updated:</summary>

 https://m.youtube.com/
https://www.amazon.com/
https://m.twitch.tv/
https://mobile.twitter.com/
https://www.google.com/
https://www.bing.com/
https://www.booking.com/
https://www.spotify.com/ro/
https://www.instagram.com/

</details>

<details>
    <summary>2. If you open a webpage e.g. music.youtube.com  quickly tap on the tabs button the fav icon will not be loaded.

On the other hand if you delete that open tab and undo the deletion action the fav icon will be loaded  
</summary>
   
![20190828_122407](https://user-images.githubusercontent.com/51314259/63843936-e8844680-c98f-11e9-9204-f1bcdf6c8740.gif)

</details>


<details>
    <summary>3. Contrary to point 2, I've noticed that after accessing taobao.com the fav icon is properly loaded.

The problem is that when deleting that tab and undoing the deletion the fav icon is replaced with a placeholder. 
 </summary>

![20190828_122041](https://user-images.githubusercontent.com/51314259/63844345-be7f5400-c990-11e9-8243-97b24e5b7bf2.gif)


</details>

<details>
    <summary>4. The fav icon is properly loaded for yahoo.com, afterwards a GDPR consent shows up (in my case in romanian) and by accepting you are redirected to the ro.yahoo.com

In this case the correctly loaded fav icon turns into a placeholder 'C' from the consent page and after giving your consent the fav icon is transformed to 'R' probably from the ro.yahoo  
 </summary>

![20190828_124905](https://user-images.githubusercontent.com/51314259/63846063-b1179900-c993-11e9-8d2d-ec02bdf798b1.gif)


</details>


<details>
    <summary>5. For some websites the fav icon is properly loaded only after the user taps on the "+" sign from the "Open tabs" section or if the user revisits the previously opened page e.g.  vw.com & theverge.com </summary>

![20190828_120436](https://user-images.githubusercontent.com/51314259/63846425-72361300-c994-11e9-8d58-ed421f975cb2.gif)

![20190828_120659](https://user-images.githubusercontent.com/51314259/63846521-a8739280-c994-11e9-85b7-3ae43b22d4b9.gif)


</details>


### Notes
All the above segements ► are drop downs which contain videos.
@pocmo I would kindly ask you to review the above findings and let me know how should we proceed.

**Comment by pocmo** [comment]
Thank you for this detailed report, @AndiAJ. I nominated this issue for our next AC triage so that we can continue with an engineering investigation of the issues you mentioned above.

**Comment by pocmo** [comment]
> 2. If you open a webpage e.g. music.youtube.com quickly tap on the tabs button the fav icon will not be loaded.

The reason for that is described in issue #3846 - The tabs tray does not update when the icon changes. I defer fixing this to the Fenix team in #3846.

> 3. Contrary to point 2, I've noticed that after accessing taobao.com the fav icon is properly loaded.
> The problem is that when deleting that tab and undoing the deletion the fav icon is replaced with a placeholder

I can't reproduce this anymore. Is this still an issue?

> 4. The fav icon is properly loaded for yahoo.com, afterwards a GDPR consent shows up (in my case in romanian) and by accepting you are redirected to the ro.yahoo.com

It looks like the default favicon on ro.yahoo.com is pretty small and therefore we do not use it. However we do not try any of the other icons. I'll file an AC issue for that.

> 5. For some websites the fav icon is properly loaded only after the user taps on the "+" sign from the "Open tabs" section or if the user revisits the previously opened page e.g. vw.com & theverge.com 

This looks almost like the same issue as (1) only that those sites are loading very slowly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13040608 from 31/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

► The STR from my fellow colleague @abodea : 
![20191031_111605](https://user-images.githubusercontent.com/51314259/67934931-8800c800-fbd1-11e9-9140-9004dc0bdc7e.gif)

► The [issues](https://github.com/mozilla-mobile/fenix/issues/2964#issuecomment-525677744) I've encountered:
![20191031_112220](https://user-images.githubusercontent.com/51314259/67935106-de6e0680-fbd1-11e9-92ff-e609fec92926.gif)
