### ISSUE TITLE
FNX3-16733 ⁃ [Collections] When open tabs are saved to a collection, they should be removed from open tabs section

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3005]
Steps to reproduce

1. Open several tabs on homescreen
1. Select "Save to collection" and go through process of saving

Expected:
Tabs that are selected to be saved into a collection are moved from the opened tabs section and placed in a collection.

Actual: 
Tabs that have been saved into a collection are still present in the open tabs section so instead of moving it's been duplicated into the collection.

**Comment by ekager** [comment]
This seems strange to me. If we think about collections as almost like a named list of bookmarks, we don't close someone's tab if they decide to bookmark it. We won't be able to restore the history of that tab if they immediately try to reopen that link because this is unexpected behavior. You can also add a tab to a collection from the browser menu, so would that just close your tab there and pop you back to home? I just didn't think of adding to collection as a destructive action.

**Comment by vesta0** [comment]
@AmyYLee @mheubusch can we revisit this when we user tests Collections?

**Comment by AmyYLee** [comment]
> @AmyYLee @mheubusch can we revisit this when we user tests Collections?

Yes

**Comment by AmyYLee** [comment]
This bug has been reopened as a result of user testing observations. It seems like the mental model of the users we tested collections on was when saving tabs to a collection they are picturing tabs moving from one location to another rather than duplicating. Also, when tabs from a collection are already opened, users are surprised that clicking on open tabs in the 3-dot menu in collection would open a duplicate copy of those tabs.

**Comment by AmyYLee** [comment]
Here is the spec that clarifies the rules around saving and opening a collection.

https://mozilla.invisionapp.com/share/73SDGWMRDFS

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on the latest **`Fenix Build #11830608 from 2/7`** using the following devices:
• OnePlus 6T (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
![20190702_111825](https://user-images.githubusercontent.com/51314259/60497021-ac4ca680-9cbc-11e9-95db-dbaf832d491c.gif)
