### ISSUE TITLE
FNX3-16784 ⁃ Test website icon capture/display in the Alexa top sites

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#3094]
This is a request for QA to test website icon capture and display on a larger list of websites like for example the Alexa top 100. We hope that by going through a larger list, we can catch some more edge cases that we can deal with in the code.

We need to make sure that the icon appears properly in history and bookmarks and possibly in the site permissions where applicable.

@vesta0 can you comment on the priority? I feel this could be a post-MVP request but if QA has time to pick this up sooner than they can decide that of course.

**Comment by vesta0** [comment]
Thanks @sarentz 

This is high priority but it does not take precedence over Fenix MVP QA.

**Comment by sv-ohorvath** [comment]
We will have look over these. But in the meantime, we already have this bug: https://github.com/mozilla-mobile/fenix/issues/2964

**Comment by softvision-miralobontiu** [comment]
Hi,
From https://www.alexa.com/topsites we've opened the first 50 top sites and bookmarked them. We did that on Chrome, as well, in order to compare.
The following pages don't have the proper icon displayed in Firefox Preview:
- google.com,
- youtube.com,
- qq.com,
- tmall.com,
- twitter.com,
- jd.com,
- live.com,
- weibo.com,
- m.vk.com,
- taobao.com,
- 360.cn,
- twitch.tv,
- alipay.com,
- ebay.com,
- github.com,
- gmw.com.

Here are the icons displayed in History:
![History](https://user-images.githubusercontent.com/40694158/59034339-82e25b80-8873-11e9-9937-997b9e37f697.png)

Here, in Bookmarks:
![Bookmarks](https://user-images.githubusercontent.com/40694158/59034354-8d045a00-8873-11e9-8f15-25f5a151d900.png)

And here in Chrome - bookmarks:
![BookmarksChrome](https://user-images.githubusercontent.com/40694158/59034375-97265880-8873-11e9-9c82-e00003b8935e.png)

@sarentz do you think we should investigate more with the next 50 sites? 
Thanks!

**Comment by sarentz** [comment]
@pocmo what do you think? will it be good to have more data?

@softvision-miralobontiu there is also a safe list from alexa btw, if you don't want to check 'those' kind of sites.

**Comment by pocmo** [comment]
@softvision-miralobontiu That is awesome, thank you for this list. I copied it over to the following AC issue to perform the investigation as to why those pages do not have icons: https://github.com/mozilla-mobile/android-components/issues/3294

**Comment by softvision-miralobontiu** [comment]
Unfortunately, I'm not able to continue with the following 50 top sites, because I need to make an account, with credit card details.
@pocmo  do you think I can use top 100 from this page https://moz.com/top500?

**Comment by pocmo** [comment]
@softvision-miralobontiu I think the current list is enough for now. Let's figure out what the issues are and if there needs to be sth. fixed. After that we can continue.

**Comment by bifleming** [comment]
@pocmo do we have a separate bug filed to address the issues found?

**Comment by pocmo** [comment]
Yes, that's https://github.com/mozilla-mobile/android-components/issues/3294

**Comment by kbrosnan** [comment]
Closing this in favor of the a-c issue.
