### ISSUE TITLE
Please provide a Desktop-Mode

### ISSUE THREAD

**Issue by szaimen** [mozilla-mobile/fenix#3107]
Please provide a Desktop Mode with a Desktop-like experience for Samsung Dex, Huawei Easy Projection & Android Q Desktop Mode.

**Comment by paroj** [comment]
Current firefox nightly already launch in Samsung Dex desktop mode, however the window is of fixed size.
To make it resizeable the following must be added to `AndroidManifest.xml`:

```xml
<activity android:resizeableActivity="true">
</activity>
```

source: https://developer.samsung.com/samsung-dex/modify-optimizing.html

**Comment by bergie** [comment]
Additionally to supporting resizing, an important feature would be requesting desktop sites by default when run in desktop mode.

Tons of info in https://developer.samsung.com/samsung-dex/modify-optimizing.html and https://developer.samsung.com/samsung-dex/modify-optional.html (see especially _Samsung Mobile Browser_ section in the latter)

**Comment by NotWoods** [comment]
I've been able to open Fenix in Chrome OS and resize the window without issues, but I don't have a Samsung Dex device to test with. Can you provide device information for the phone you tried to use Dex with?

I'll split out defaulting to desktop mode into a separate issue: #10631.

**Comment by szaimen** [comment]
> I've been able to open Fenix in Chrome OS and resize the window without issues, but I don't have a Samsung Dex device to test with. Can you provide device information for the phone you tried to use Dex with?

Resizing and opening fenix on samsung dex works.

What I meant with desktop mode is a desktop like experience with tabs, etc.
Because a mobile like experiwnce isn't that great in terms of UX on a Desktop mode like Samsung DEX.

E.g. this is Brave (which is based on chromium) on Samsung Dex, which is mich better to use on DEX:
![Screenshot_20200513-195516_Brave](https://user-images.githubusercontent.com/42591237/81847713-407dd000-9554-11ea-9def-fcfac744430e.jpg)

This is fenix on samsung dex:
![Screenshot_20200513-195453_Firefox Beta](https://user-images.githubusercontent.com/42591237/81847777-5be8db00-9554-11ea-996a-9d5ac294fd02.jpg)
![Screenshot_20200513-195458_Firefox Beta](https://user-images.githubusercontent.com/42591237/81847798-60ad8f00-9554-11ea-95ac-e00348f5acb1.jpg)

**Comment by paroj** [comment]
> I've been able to open Fenix in Chrome OS and resize the window without issues, but I don't have a Samsung Dex device to test with. Can you provide device information for the phone you tried to use Dex with?

resizing works on Dex now and was fixed with https://github.com/mozilla-mobile/fenix/commit/56eb2ec1d736a5c1f9eecaebfaabaf604dd7ca06

**Comment by jdelga2** [comment]
> mode is a desktop like experience with tabs, etc.
> Because a mobile like experience isn't that great in terms of UX on a Desktop mode like Samsung DEX.
What would be really useful in Samsung DeX is to activate automatically the check for desktop view/site and deactivate it when switching to mobile use (not in DeX mode)

**Comment by liuche** [comment]
This looks similar to what we may want to do in #4498

**Comment by mkaply** [comment]
Motorola is moving into this space as well:

https://www.engadget.com/motorola-ready-for-phone-pc-edge-plus-103506144.html

This is really different than #4498 and we should treat it as such.

https://developer.android.com/topic/arc

**Comment by alexanderadam** [comment]
> Resizing and opening fenix on samsung dex works for me.

@szaimen, are you sure that you didn't activated the experimental Samsung DeX setting "_Force apps to resize_"?

Because otherwise Firefox would really need [the already mentioned](https://github.com/mozilla-mobile/fenix/issues/3107#issuecomment-591089159) `resizeableActivity` directive.

I have Firefox 87.0.0-rc 1 installed and I definitely cannot resize Firefox without the experimental setting or a build with the `resizeableActivity` directive:

![Firefox on Samsung Dex](https://user-images.githubusercontent.com/372620/113057340-3507b780-91ad-11eb-8511-d90aa7934e6c.png)

Other apps like [NewPipe](https://github.com/TeamNewPipe/NewPipe/pull/3948/files), [MaterialFiles](https://github.com/zhanghai/MaterialFiles/commit/7f2b9b177d43757a5063f11d3d22beb0584cc4f5), [AntennaPod](https://github.com/AntennaPod/AntennaPod/pull/4343/files), [SkyTube](https://github.com/SkyTubeTeam/SkyTube/pull/782/files), [Vinyl](https://github.com/AdrienPoupa/VinylMusicPlayer/commit/e90bc298d2313561bb42ec185370e26bda0256ee), [Joplin](https://github.com/laurent22/joplin/pull/4624/files), [Kiwix](https://github.com/kiwix/kiwix-android/pull/2330/files), [Zapp](https://github.com/mediathekview/zapp/commit/803968e7abae675b4c3142ea7f4b85386a962a39) or [GitNex](https://codeberg.org/gitnex/GitNex/commit/9e352df1ed7d1d285fde61632822e2db5d128f16) also needed this simple patch.

@liuche should I open another issue for resizing support in Firefox or can we recycle one of the 'duplicated' issues?
Because #4498 seem to be about UI/UX changes but the change I'm looking for is independent from that and just requires patching the `AndroidManifest.xml`.

As mentioned before, [Samsung also has some documentation on that](https://developer.samsung.com/samsung-dex/modify-optimizing.html#Enabling-Multi-Window-support).

**Comment by szaimen** [comment]
> @szaimen, are you sure that you didn't activated the experimental Samsung DeX setting "Force apps to resize"?

It is completely possible that I've done that but I cannot remember.
