### ISSUE TITLE
FNX3-16844 ⁃ Not all share intents find Fenix

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#319]
### Steps to reproduce
1. Open YT and click a link in a video description

### Expected behavior
* (if you have mulitple browser apps) The menu of apps should include r-b.

### Actual behavior
* The browser isn't on the list at all.

### Device information
* Android device: Android 9 (Pixel 2)
* Reference Browser version: 1.0.1905 (Build #10301403 :lizard: 66.0a1-20190128092811)

See https://github.com/mozilla-mobile/reference-browser/issues/526

**Comment by colintheshots** [comment]
Google Maps still cannot share to Fenix, among others.

**Comment by jonalmeida** [comment]
That's because Google Maps gives us more than just a link we can handle. 

For share intents with: "X person wants you to join them: https://example.com"
We don't handle this because we would need to parse out the URL which has it's issues.

I'm going to close this since we handle the cases we set out to do. We can file a follow up for investigating how we want to handle intents with mixed data.

**Comment by pocmo** [comment]
> For share intents with: "X person wants you to join them: https://example.com"
We don't handle this because we would need to parse out the URL which has it's issues.

`IntentProcessor` does either open a URL or performs a search for text.

That said.. we do have `WebURLFinder` in `support-utils` which can find URLs in text too. And we use that to find URLs in the clipboard. Maybe we could add that to the `IntentProcessor` too?
