### ISSUE TITLE
[Bug] Search bar is cleared when activity is killed by system

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#3258]
## Steps to reproduce
* Turn on "Don't keep activities in developer settings menu".
* Open Fenix.
* Tap on search bar.
* Enter something.
* Tap on system "Home" button.
* Open Fenix from "Recent".

### Expected behavior
* Entered test should be displayed in toolbar.

### Actual behavior
* Search toolbar in empty.

### Root of issue
`toolbarComponent` state in `SearchView` is stored in `ViewModel` but `ViewModel` isn't restored when activity was killed by the system.

**Related issue**: #1366

**Comment by pocmo** [comment]
When fixing that let's chat since the AC toolbar should already retain it (if not that's a bug on our side) and let's not add a bandaid to save the state in Fenix on top of that :)

**Comment by pocmo** [comment]
I can reproduce in RB, so it looks like a toolbar issue.

**Comment by dector** [comment]
@pocmo I'm not sure that this issue can be fixed by changing only AC toolbar.
Sure, we can save/restore view state (and I think it's already saved by default). But Fenix uses [ViewModel](https://github.com/dector/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarComponent.kt#L102) to store [SearchState](https://github.com/dector/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarComponent.kt#L79).

`ViewModel` can be good for handling configuration changes. But [not activity/process death](https://developer.android.com/topic/libraries/architecture/saving-states#options_for_preserving_ui_state). This means that when activity is killed - ViewModel may be removed from memory as well. And there is no way for AC toolbar to handle it.

Seems like architecture issue for me. I've done some [quite successful experiments](https://github.com/dector/fenix/commit/ed83e55c6730e7dcc479f4d2b31d793f370d2fd8#diff-9ca77fb5606b8c69916f145f9409da2aR42) but I don't like the way android's `ViewModel` implementation saves/restores it's state.

**Comment by colintheshots** [comment]
@dector The use of ViewModels is orthogonal to save/restore instance state. You have two options: either you can 1. manually save/restore state to the ViewModel or you can 2. make use of the alpha SavedState library. We chose to option 1 in our app so far. There is nothing in the architecture impeding anyone from using Save/Restore. In fact, I only added ViewModels because it became clear that Google would not support any other mechanism of persisting on configuration changes in the long term and that code was being put in place to make it easy to Save/Restore with ViewModels.

The only issue with ViewModels, one I'm acutely aware of, is it tends to make engineers forget the importance of Save/Restore callbacks when their rotation issues go away. Before I left on PTO, I left specific examples of how to use Save/Restore within the architecture.

**Comment by dector** [comment]
@colintheshots Thanks for paying attention to this! First, I'm not against `ViewModel`, so no offense at all. :)

But I don't like the way Google implemented it's saving state because in this case we'll have serialization to `SavedState` every time component's inner state is changed. Handling `onSaveInstanceState()` manually if fine for me. But it requires some boilerplate. So my question here is: do you have some in-project guideline for saving `ViewModel`'s state or it can be designed/implemented in the scope of this issue?

**Comment by sblatz** [comment]
Bumping @colintheshots on this as it's an MVP blocker :)

**Comment by sblatz** [comment]
This is blocked on feedback from @colintheshots.

**Comment by dector** [comment]
[Simple solution](https://github.com/dector/fenix/commit/f02e002793f0e6dda36db830a88beb2da3d9ca40) seems not-so-dirty.

However, there is issue with `SearchEngine` saving. This model contains resources (`Bitmap`) so with storing it inside the `Bundle` we have a risk to get `TransactionTooLargeException`. I suppose `identifier` should be stored instead and `SearchEngine` should be loaded when state is initialized.

However :), for now `engine` field seems always `null` and search engine icon is always restored. :thinking:
