### ISSUE TITLE
[Bug] QR code doesn't scale back when you exit Android Split Screen

### ISSUE THREAD

**Issue by malgamves** [mozilla-mobile/fenix#3303]
## Steps to reproduce
Open Private Browsing
Split screen with another app 
Select scan and camera opens
Take app back to full screen

### Expected behavior
Camera is supposed to scale back to proper size
![Screenshot](https://user-images.githubusercontent.com/25641936/59159207-cc38e200-8ae3-11e9-8d6b-20f7366e4aa9.png)UNITO-UNDERSCORE!20190609-180844!
![Screenshot](https://user-images.githubusercontent.com/25641936/59159229-11f5aa80-8ae4-11e9-937a-988e9aef77b4.png)UNITO-UNDERSCORE!20190609-182550!

### Actual behaviour
Camera does not scale back to proper size
![Screenshot](https://user-images.githubusercontent.com/25641936/59159245-4e290b00-8ae4-11e9-9a4e-fb62039c4339.png)UNITO-UNDERSCORE!20190609-182741!

### Device information
Android device: Nokia 8.1, Android 9
Fenix version: Fenix 1.0.1923 (Build #11590616 lizard 68.0-20190604110028)

**Comment by sflorean** [comment]
Tested on Nightly 6/12 and following the steps from the description I got a different behavior: after this step **Take app back to full screen** and with the keyboard displayed if  I tap back (device button), the camera is closed, meaning that the camera isn't fully displayed on all screen due to the keyboard. 
The keyboard is visible when I open another app, or just interact with Fenix. 

Devices: Samsung Galaxy Note10(Android 10), LG G7 FIT (Android 8).
