### ISSUE TITLE
Fix Snackbar issues

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3319]
We should spend some time re-thinking if or how we want snackbars to work. We have lots of issues regarding them.

It will require some work in a-c, so let's make sure that gets prioritized too.

Tracked by [`Feature:Snackbar`](https://github.com/mozilla-mobile/fenix/labels/Feature%3ASnackbar) label

**Comment by sblatz** [comment]
Really we need these to be implemented on the android components side. I'm going to throw a blocked label on this until we're able to address it there.

**Comment by mheubusch** [comment]
@AmyYLee There are a number of bugs related to snackbars and confirmation dialogs - can we talk about how to work with engineering to locate all the dialogs that appear instead of a snackbar where a snackbar was originally specified?  Also, have we articulated a rationale or listed the use cases for snackbar vs dialog?  It might help to attach that to this bug if so.

**Comment by AmyYLee** [comment]
@mheubusch Can you provide an example of where a dialog appears instead of a snackbar? I don't think I've seen this. Dialogs and snackbars are used in fairly different scenarios.

Snackbars are transient confirmations that time out and appear AFTER an action - i.e deleting 
Dialogs requires a user to choose an action and don't go away until they do so - i.e asking permission

**Comment by sblatz** [comment]
@mheubusch @AmyYLee currently we're using dialog confirmations in place of snackbars in some places (deleting a collection, for example) because we were having so many bugs with the undo part. 

I think this issue is less about the UX of them and more about the fact that we need to implement them in AC to have the results we want :)

**Comment by mheubusch** [comment]
@sblatz I will remove the UX tag for now - as long as you have a record of which dialogs were originally spec'ed as snackbars and pulled because of bugs and can revert to the original intent. If there are any questions, please tag this for us again.

**Comment by liuche** [comment]
Need to audit this list of bugs in [`Feature:Snackbar`](https://github.com/mozilla-mobile/fenix/labels/Feature%3ASnackbar) to see what is still blocked by AC, or what is done.

**Comment by liuche** [comment]
Talked to @sblatz and it looks like AC would need to prioritize the "Bookmarks Undo" callbacks (so we can actually use this).

If we want to, then this should go into the Waiting column, and we will need to add it to the AC planning board.
