### ISSUE TITLE
[Bug] new tabs to bottom when fenix is closed

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#3346]
## Steps to reproduce
1. Have multiple tabs openin Felix (I have 38) 
1. Close Felix 
1. open a link from an external app (email etc) 

### Expected behavior
Link opens in New tab. On tab page, the new tab is at the top of the list

### Actual behavior
The new tab is at the bottom of the list

### Device information
* Android device: BlackBerry KeyOne  8.1.0 
* Fenix version: 1.0.1924 (Build #11620623 :lizard: 68.0-20190604110028)

**Comment by sblatz** [comment]
This may not be possible to fix without an a-c change. Since we're restoring the session manager sessions asynchronously, this new session gets added before the other ones are loaded into memory. This causes it to get added to the bottom of the session list. 

Possible solutions:
1. Delay adding the session until the sessions are loaded into memory. I'd recommend strongly against this since it could take a while and we want the user launched into the browser asap.
2. Make a change in a-c that gives us a timestamp of when the session was created so we can properly sort the list on the home view.

**Comment by sblatz** [comment]
This is blocked on this a-c patch: https://github.com/mozilla-mobile/android-components/issues/3432

**Comment by nahuhh** [comment]
This appears to be fixed
