### ISSUE TITLE
app links

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#3349]
### Why/User Benefit/User Problem
This isn't specific to YouTube, but YouTube is an easy website to use as an example.

When clicking on a YouTube video, 
( any one from here will do https://duckduckgo.com/?q=ubuntu&t=fpas&iar=videos&iax=videos&ia=videos&iai=lmeDvSgN6zY ) 
the drawer opens to ask if you would like to open the link in the associated app.

This happens every single time you enter a website  that you have an associated app for. ..which can get quite annoying.

### What/Requirements
The drawer appears to be self contained within Firefox. If it is, I suggest adding to the drawer the option to choose "always/never" with "just once" being the by default

### Acceptance Criteria (how do I know when I’m done?)
Always (a selectable check box) =always open links using the app
Never (a button) = always open links in fenix
Just once (default, happens if you click the associated app without selecting always or tapping never) = self explanatory 

Within the settings menu, the ability to view default app associations and delete them individually.

**Comment by buttercookie42** [comment]
Seconded.
Also, to expand on
> Within the settings menu, the ability to view default app associations and delete them individually.
on the one hand it seems a bit unfortunate having to duplicate Android's own default app settings, but on the other hand I think that having different default apps inside the browser and generally on the rest of the phone can be a valid use case.
E.g. I'm usually fine with MP3 files I come across during browsing to be opened inside the browser itself (or might actually prefer that behaviour), but that doesn't mean I want to make Firefox my default music player. If Firefox however strictly followed only Android's global default app settings, there would be no way to model this, because in that case there would be no way to have separate settings inside and outside the browser.

Alternatively, a simpler solution for the time being might simply be a global switch in the settings to turn app links on or off, allowing to revert the Fennec's behaviour today (i.e. ideally you still get the option to manually open the page in an external app using either the context menu for links, or something like Fennec's Android icon in the URL bar).

**Comment by jhugman** [comment]
This is being tracked on the [Android Intent URLs board][0].

[0]: https://github.com/orgs/mozilla-mobile/projects/32
