### ISSUE TITLE
FNX3-16969 ⁃ [Bug] Can't unselect a bookmark folder when in EditBookmark

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3365]
## Steps to reproduce
1. Navigate to a website
1. Press Bookmark
1. Press "edit"
1. Tap the "folder" icon
1. Select any folder
1. Select it again

### Expected behavior
1. The folder is unselected, allowing me to file the bookmark in the root view

### Actual behavior
1. The folder stays selected, forcing me to save it to a place I don't want.

**Comment by colintheshots** [comment]
The title is prescriptive and does not seem like good UX. I'm not sure we want the folder to be un-selectable or if we do, we'd want the bookmark to stay where it is rather than be filed in the root folder. What's really missing the ability to file bookmarks in the root. Un-selecting the folder is not choosing a folder and seems it may have undefined behavior.

**Comment by colintheshots** [comment]
This is most certainly not fixed by the PR, but I decided it was progress on the issue to provide a means to keep the existing root. Also, we don't have translatable strings available to be able to pick the mobile root by MVP date.

**Comment by colintheshots** [comment]
PR#3446 should address this by restructuring the edit bookmark folders.

**Comment by AndiAJ** [comment]
Hi, **all good** on the latest Fenix build (1.0.1926 Build #11771809 from 26/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Sony Xperia Z5 Premium (Android 7.0)

►Video from the Google Pixel 3XL
![2019_06_27_11_04_40](https://user-images.githubusercontent.com/51314259/60248972-6d89ab80-98cc-11e9-8e92-9d5bc3ad63dc.gif)
