### ISSUE TITLE
As a user I want my tabs closed when quitting and reopening Fenix

### ISSUE THREAD

**Issue by akarshanbiswas** [mozilla-mobile/fenix#3605]
## User Story
* As a user, I want all my open tabs closed after quitting and re opening Fenix.

## Dependencies
* A setting that needs to add to mimic the current stable Fennec browser.
![20190622](https://user-images.githubusercontent.com/17230826/59962205-ede09300-94ff-11e9-9478-62dc17652495.jpg)UNITO-UNDERSCORE!150843!

### Acceptance Criteria
* I can set the settings to not to restore the tabs after quitting Fenix.

**Comment by topotropic** [comment]
There's a feature that allows to close open tabs on quit. Go to Settings / Delete browsing data on quit and select "Open tabs". https://github.com/mozilla-mobile/fenix/issues/3700

**Comment by akarshanbiswas** [comment]
@topotropic Tried the feature. It doesn't actually clear the tabs (using latest firefox preview from play store)

**Comment by yoasif** [comment]
Spoke to the team briefly on Matrix. Takeaways:

* Fenix is not able to tell if it is closed automatically or due to a user directed action (swiping away)
* Fennec had this feature and people liked it.
* presumably, even if Fennec lost tabs by accident after enabling this option it is acceptable because users asked Fennec to do so.
* Edge (at least) has the same behavior

Fennec:

![image](https://user-images.githubusercontent.com/152493/91348449-c47d6000-e7b1-11ea-9b7c-b02fe26bb843.png)

Edge:

![image](https://user-images.githubusercontent.com/152493/91348477-ce06c800-e7b1-11ea-9281-326c868cbb7e.png)

I have seen a solid amount of feedback about this on social media and Google Play, so I'd love to see this explored, especially as it is a Fennec Transition item and a competitiveness item.
