### ISSUE TITLE
FNX3-17155 ⁃ [Bug] Find in page doesn't work when opening tab from CustomTab

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#3609]
## Steps to reproduce
* Load page in CustomTab (e.g. from Reddit is Fun)
* 3 dot menu -> Open in Firefox Preview
* 3 dot menu -> Find in Page

### Expected behavior
* Find in page widget opens

### Actual behavior
* Nothing happens

### Device information
* Android device: Samsung S10e
* Fenix version: Latest Nightly from Playstore

**Comment by alexa-v2** [comment]
You say this if firefox nightly, do you mean Fenix (firefox preview)?

**Comment by agi90** [comment]
yes, it's the latest Fenix from the playstore.

**Comment by softvision-miralobontiu** [comment]
If I understood correctly, these are the STR:
1. Open a link via custom tabs (I used Gmail)
2. From three-dot menu from the custom tab open the link in Firefox Preview
3. From three-dot menu from Firefox Preview select Find in page

In this case, this issue is fixed. I was able to use "Find in page" without issues.
Tested on the latest build 1.0.1926 (#11760617) with LG G7 Fit (Android 8.1), and Nexus 5 (Android 6.0.1).

@https://github.com/agi90 could you, please, confirm the steps?
Thank you!

**Comment by agi90** [comment]
@softvision-miralobontiu Yep, the steps are correct! Also it now works for me too :) Thank you.

**Comment by softvision-miralobontiu** [comment]
Based on Agi's comment, I'm closing this issue.
