### ISSUE TITLE
[Bug] Don't enable fontInflation

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/fenix#3639]
## Steps to reproduce

Navigate to https://searchfox.org/mozilla-central/source/docshell/test/browser/browser_csp_uir.js

### Expected behavior

Font sizes aren't hosed

### Actual behavior

Font sizes are hosed from what looks like font inflation.

### Device information

* Android device: Pixel 2
* Fenix version: 1.0.1926

`fontInflation` in GeckoView is a context-sensitive way to increase unreadable text. It is not the same as the `fontSizeFactor`[1], which just increases all fonts by some factor. It is also different from `automaticFontSizeAdjustment`[2], which scales the fonts according to the system font settings.

[1] https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.html#setFontSizeFactor-float-
[2] https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.html#setAutomaticFontSizeAdjustment-boolean-

**Comment by snorp** [comment]
I can reproduce this in Reference Browser, but not GVE, so I would guess this is getting accidentally enabled in android-components.

**Comment by buttercookie42** [comment]
I could equally point out a number of other websites where the text would be unreadable *without* font inflation, though. (And we have indeed had some complaints that that kind of pages would render okay in Chrome - because of their font inflation equivalent - but with tiny text in Firefox because there we didn't enable it by default)
And specifically regarding searchfox.org, if I remember the state my local Firefox build is in correctly, then it seems that [bug 1552781](https://bugzilla.mozilla.org/show_bug.cgi?id=1552781) should improve the behaviour there as well, i.e. just like Chrome we would no longer inflate text on Searchfox even with font inflation turned on.

**Comment by karlcow** [comment]
I'm not completely sure, but this same site breaks in Firefox Fenix and not in Firefox fenix
https://github.com/webcompat/web-bugs/issues/33625

This seems related to either a default font size which is different or a font inflation system.
On Fennec, 16px
On Fenix, 18.4px

**Comment by ekager** [comment]
I think the GV team is looking into the right solution for this since removing it here didn't actually change anything about this bug. See https://github.com/mozilla-mobile/android-components/issues/3522 and https://bugzilla.mozilla.org/show_bug.cgi?id=1561135

**Comment by karlcow** [comment]
Thanks @ekager Do you know what is the default css of Firefox Fenix. 

For Fennec
https://searchfox.org/mozilla-central/source/layout/style/res/

does Fenix reuses this, or something different?

**Comment by buttercookie42** [comment]
The page from webcompat/web-bugs#33625 has a "width=device-width" meta viewport tag, so font inflation doesn't matter there.

And I still disagree with the premise of this bug - the specific case of Searchfox (and some other similar pages, like #2606) will be fixed in Gecko shortly, and **not** enabling font inflation likewise makes a number of other pages unreadable because of too small text.

**Comment by ekager** [comment]
I'm unassigning myself until @snorp / GV tells me to do something differently. The current state of Fenix is fontInflation is not enabled at any time. If you want us to change that, ping me!

**Comment by ekager** [comment]
I'm closing this because there's been no actionable information for Fenix as far as I can tell. I think they removed font inflation from being enabled through automaticFontSizeAdjustment. Please reopen or open a new bug if we should update any behavior here.

**Comment by buttercookie42** [comment]
> Please reopen or open a new bug if we should update any behavior here.
#4458
