### ISSUE TITLE
[Bug] Back Button Stacks Through Saved Collection Items Instead of Going Back to Home Screen

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#3650]
## Steps to reproduce
See video: https://photos.app.goo.gl/J6zssjo5yUL6v47bA

### Expected behavior
Pressing back button should always go back to home screen

### Actual behavior
Pressing back button goes to first web page in stack

### Device information

* Android device: Samsung Galaxy S8 with Oreo
* Fenix version: Yesterdays

**Comment by sblatz** [comment]
This is currently expected behavior. When you save a tab to a collection we're saving its history too. When you press back, you navigate back through your history before hitting the home view. 
See #3215.

**Comment by yoasif** [comment]
>This is currently expected behavior. When you save a tab to a collection we're saving its history too. When you press back, you navigate back through your history before hitting the home view.

FWIW, this seems like the desired behavior to me.

**Comment by Sdaswani** [comment]
Ok, like @vesta0 , I'm not convinced this is desired behavior :) https://github.com/mozilla-mobile/fenix/issues/3215#issuecomment-502290723 

IMHO the point of a collection is to save a set of related sites, not the _whole history_ of how i generated that collection. when i share that collection with another of my firefox instances, is the history transferred too? or if i share it with another person, i definitely wouldn't want that history shared with them.  just my 2 cents...

**Comment by yoasif** [comment]
I see it as me saving the tab, not a link -- I don't see collections as bookmark folders (many browsers have had that forever), but as saved tabs. 

I don't know the answer to how sharing works if shared to desktop (I kinda want to try it now!), but from what I know about sharing tabs, Fenix/Fennec just shares the link, not some binary encapsulation of the tab -- at least when sharing to other apps. 

Pretty sure that is what happens when sharing to another device, too. 

If we just save links, how are collections different from a spin on bookmark folders?

**Comment by yoasif** [comment]
FYI -- just tested sending collections to desktop, and it just sends links, just like sending tabs. 

Sending tabs to mobile also sends as links - I haven't tried a desktop to desktop send, but I suspect that is the same as well.

**Comment by vesta0** [comment]
Thanks for the feedback @Sdaswani :) The UX team is investigating the Collections design and I think this is a good use case to consider and make sure we are intentional in how we design it. FYI @shorlander @mheubusch
