### ISSUE TITLE
Find in page - matching words behind the toolbar aren't visible

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#371]
## Steps to reproduce
1. Open a webpage with a lot of text.
2. Search for a word that will be located behind the "find in page" toolbar once it's opened.
3. Open the "Find in page" toolbar and type the word. Press up/down until you reach the targeted word.
### Expected behavior
The page scrolls up to make the word visible.
### Actual behavior
No scrolling, the word is not visible if it's covered by the "find in page" bar. 
*The page scrolls if the word is below the bar.
### Device information

* Android device: Pixel (Android 9)

**Comment by boek** [comment]
@ekager another interesting side effect of the bottom toolbar

**Comment by vesta0** [comment]
blocked by #552

**Comment by softvision-miralobontiu** [comment]
This issue is not entirely fixed: The "Find in page" toolbar scrolls down the page, but the last found word is not displayed if it is on the last row.
Please see the attached GIf for more clarity.

![Inkedfind](https://user-images.githubusercontent.com/40694158/58327898-786a9f80-7e39-11e9-9671-a8c83b6e00c5.gif)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1923 (#11550608), with Sony Xperia Z5 Premium (Android 7.1.1), and Huawei MediaPad M2 (Android 5.1.1).
