### ISSUE TITLE
View Page Source option

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#3710]
### Why/User Benefit/User Problem

Useful for developers and users who want to view the source of the page

### What/Requirements

View Page Source option to view current page source

### Acceptance Criteria (how do I know when I’m done?)

Feature parity with Fennec to view current page source

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12325)

**Comment by buttercookie42** [comment]
Ideally needs [bug 1539363](https://bugzilla.mozilla.org/show_bug.cgi?id=1539363) in GeckoView.

**Comment by Oymate** [comment]
@vesta0 timeline for update?

**Comment by rickrich** [comment]
Please put view-source on your list.  Right now I have a problem with https://www.certitudes.org/ and I need this.

**Comment by andreicristianpetcu** [comment]
Install android dev tools. Link phone to desktop via USB. Make sure `adb device list` sees your phone. Enable remote debugging on Android Firefox. Go to about:debugging on desktop. Debug the site. @rickrich

**Comment by madb1lly** [comment]
Hi @andreicristianpetcu,

Whilst suggesting out-of-app workarounds is helpful for people in the short term it doesn't address the problem that this is a feature which has been removed from Firefox for Android; a feature which people used and is no longer available to them and which needs to be reinstated if the app is to remain as useful to them.

And frankly who wants to have to faff around getting a laptop when all that's needed is a quick check and fix of the source?

Cheers 🙂

**Comment by andreicristianpetcu** [comment]
Rickrich seemed to need to fix a urgent issue with a site. I tried to help with a workaround untill this lands.

**Comment by csoti** [comment]
I really could use this feature to help quickly begin diagnosing why a private webpage is working for me on Fenix 79.0.5 but not 80.0.1-beta.2
The software developer I'm working with on our project was dumbfounded to learn _view page source_ isn't a standard feature like in all versions of ff for android / web browsers in general.

**Comment by lnicola** [comment]
@csoti try the remote debugging tools, they're easy to set up if you have a cable at hand. View Source is useless unless the server does UA sniffing because its shows the source as returned by the server and not the DOM (as modified by JavaScript).

**Comment by csoti** [comment]
@lnicola Thanks for taking the time to offer a thoughtful solution.
I'd like to play around with the remote debugging tools just to learn about it if nothing else.

I brought this up because the software developer suggested viewing the page source to quickly see if anything was trying to load on the page (I was getting a completely blank page).
For my purposes this is all moot as the latest (as of Sept. 4) Firefox for Android beta and stable handle our webpage just fine now. Whatever was preventing the page from loading in 80.0.1-beta.2 is resolved now.
But I am curious about the remote debugging tools. Those could be some fun.

**Comment by clientenq** [comment]
View page source should be part of any webbrowser via default functionality. A webbrowser is a tool for rendering content, not a magic solution disabling user need to view raw resources. Making view page source only available to users who comply with extra hardware and software requirements via debug tools is not user friendly and does not give users enough control over content and www resources.
We should not release or develop like users have minimal control or knowledge over resources they request when using firefox for android.

**Comment by jayaddison** [comment]
A browser has to retrieve the HTML source of a page before it can render it, and similarly anyone who would like to create their first web page benefits by seeing how web pages are built (including their own, if they happen to start by using software or a service that generates it for them).

It may be a rarely used feature for the average person but it is an essential feature for the curious technical explorer.

**Comment by bjorn3** [comment]
To provide my own usecase for view-source: Github only shows who reacted with an emoni when hovering over it. On a phone it is not possible to hover over any element, so using view-source instead is a workaround I often used.

**Comment by lnicola** [comment]
@bjorn3 tapping the emoji sometimes shows who reacted, but this no longer seems to work for me lately. Desktop mode also used to make it easier.

**Comment by dadeke** [comment]
[view-source:https://github.com](view-source:https://github.com)

**Firefox PC:** It works! 😀️👍️

**Firefox for Android:** "Cannot Complete Request" 😐️

**Comment by abramclark** [comment]
I'm rather disappointed in Firefox for removing this in a public release

**Comment by cadeyrn** [comment]
> I'm rather disappointed in Firefox for removing this in a public release

It was not "removed". The new Firefox (79+) is a completely new developed browser and it has to be re-implemented. Of course it's a matter of prioritization whether / when this will happen. If you want to see this feature in the new Firefox it would be more helpful to tell the developers why do you think this feature is more useful than using the remote debugging tools.

**Comment by B0pol** [comment]
As a workaround, you can install [View Page Source (mobile)](https://addons.mozilla.org/android/addon/view-page-source-mobile) on Nightly

**Comment by Oymate** [comment]
@B0pol doesn't install

**Comment by B0pol** [comment]
@Oymate follow this to install it on Firefox Nightly https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by Idesmi** [comment]
bump

Please reintroduce it, I used to read the source regularly on Fennec. The need of a second computer to do that is a hassle, when it could already be done on mobile alone.

**Comment by wyatt8740** [comment]
@B0pol The fact that I need to create an account in order to install the add-on is also a bit of a dealbreaker for me, personally. More and more hoops to jump through.

**Comment by madb1lly** [comment]
> 
> 
> > I'm rather disappointed in Firefox for removing this in a public release
> 
> It was not "removed". The new Firefox (79+) is a completely new developed browser and it has to be re-implemented. Of course it's a matter of prioritization whether / when this will happen. If you want to see this feature in the new Firefox it would be more helpful to tell the developers why do you think this feature is more useful than using the remote debugging tools.

Hey @cadeyrn,

We've been over this umpteen times. From a user perspective it was removed - it was there one day, the app was updated and then this and many other features were not there any more. Some new features were added with a minor onboarding experience. There was almost zero warning that the new version would not have all these features, even for people using Nightly like me - the fact that Mozilla updated the Release version with all these things missing was a huge shock, _why_ did they do that?! To me it was crazy and the backlash they're experienced was totally expected and justified.

I can understand why you want to defend Mozilla, most of us posting here want Mozilla to "win", but sometimes we have to recognise that bad decisions were made and, yes, a shed-load of features were "removed".

Cheers 🙂

**Comment by cadeyrn** [comment]
> I can understand why you want to defend Mozilla

Great, because I don't understand this sentence at all. 🤔 I see no reasons why a software vendor should have to be defended for having different priorities (because it is perfectly normal that every user has different ideas about the feature set of a product!) and my comment is not "defending" anyone. Unfortunately you completely missed the point of my comment: Another user was obviously not aware of the fact that nothing was removed and every feature has to be re-implemented. If an users says he is "disappointed" it's important to **help the user** to understand the wider context. My comment was a direct response to that user. I gave the user an **explanation** and told him that the **best way to convince Mozilla** is to tell Mozilla about his use cases. Nothing is more convincing than arguments and therefore that's the way to go if you want to see something implemented. So I have no idea how your response to me was supposed to contribute to the implementation…

**Comment by madb1lly** [comment]
Hi @cadeyrn,

Thanks for explaining. Clearly what I inferred from what you wrote is completely different from what you implied, and the same seems to have happened with what you inferred from what I wrote. The pitfalls of communicating only in writing.

From my point of view your second explanation makes more sense, your motives are clearer, you explain much more clearly that the key point is that users now need to convince Mozilla to reintroduce features and you're not "defending" the fact that Mozilla decided not to keep (i.e. remove) this or any other feature. I'll try to remember that when I read similar comments of yours in the future.

I didn't realise I was commenting two months later, please excuse me.

My use case for view source is when I am trying to read a webpage and can see it's not displaying properly I can view the source to see what I'm missing; or I can find the web address of an embedded image, or I can extract a hyperlink that I can't seem to get to work properly via the touch UI. Many other use cases like this - it's a power user tool to 1) help us access poorly coded websites, 2) help us overcome any web compat issues that Firefox has or 3) both 1 and 2 🙂

Cheers 🙂

**Comment by Oymate** [comment]
I think it's a bout time to lock this thread with need to get feature parity/reimplement view-source:
:)

**Comment by abramclark** [comment]
Yeah that is reasonable to lock it. Haven't we fully established the use
cases? My disappointment was that such a fundamental feature wasn't
required for "parity" before release. It is unprecedented for a serious
browser to not have view-source, and it's a terrible precedent to set.

**Comment by jawz101** [comment]
https://github.com/mozilla-mobile/fenix/issues/3972
is the same thing with about as much discussion.

**Comment by headbank** [comment]
Per #3972 `view-source:` protocol support has quietly landed in release version, so all we are missing now is the UI to expose it.

**Comment by djbrown** [comment]
manually typing `view-source:` works for me
92.1.1 (Build #2015832081)
AC: 92.0.15, e00bef534d
GV: 92.0-20210903235534
AS: 82.1.0

@andreicristianpetcu Can this issue be closed, or do people still need a UI button to view source?
#3972 was closed already...

**Comment by headbank** [comment]
@djbrown I still would like UI for it. If you use View Source at all, often you use it many times repetitively, so it's a lot of typing for people at least some of whom (a) don't much enjoy typing on a phone keyboard more than necessary and/or (b) find the addressbar in Fenix full of UX pain-points (which I won't list here, there are plenty other tickets) and would rather avoid it as much as possible.

Certainly it's a completely distinct issue from the basic matter of `view-source:` support, otherwise this ticket would not have been allowed to survive on its own until now ;) so the disposition of #3972 should have no bearing here.

**Comment by no-identd** [comment]
First ordert User story:

As a: Amateur professional hobbyist researcher

I encounter: https://www.nature.com/articles/d41586-022-03681-w in my newsfeed. Nature f'd up the Paywall wrapper.

And I want to click the link erroneously wrapped behind the Paywall wrapper, so I can know the doi for the actual paper instead of the blurb article talking about it.

Second-order user story:

As a: Web power user

I want to: Access the source code of a website

So I can: compensate for mistakes made by developers

Third-order user story:
As a bug reporter

I want to: Encourage kindness

So I can:
Post snark about this issue having been open since 2019 while frustrated about state of science

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809224

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
