### ISSUE TITLE
Improve UX for opening Collections

### ISSUE THREAD

**Issue by Mardak** [mozilla-mobile/fenix#3731]
### Why/User Benefit/User Problem
I made a Reddit Collection of 6 subreddits that I tend to visit when just browsing (not logged in), and currently I need to tap the collection's menu item and select the last item to open all in tabs. And when opening the tabs, they appear in reverse order from how they were added to the collection. If there's many tabs already open, one might need to scroll quite a bit to access the collections. Also, the collection shows up as "[icon] Reddit [expand] Reddit, Reddit, Reddit, Reddit, Reddit, Reddit"

Seems like the current UI is optimized for sharing a set of pages, so maybe I'm just using collections wrong. 😉 

### What/Requirements
Maybe add a dedicated button to open all in tabs? Instead of the share -> moved to menu?

### Acceptance Criteria (how do I know when I’m done?)
This probably wants to be split up into multiple issues if some ideas seem useful.

**Comment by vesta0** [comment]
@Mardak thanks for the suggestion, would you mind elaborating on your desired behaviour? As you mentioned, there is already an "Open Tabs" option in the menu. Do you just want that moved somewhere else as a button, or do you want it to behave differently (e.g. not open in reverse order, etc)?

**Comment by Mardak** [comment]
I guess maybe I'm just confused about what's the expected behavior of Collections, so perhaps I'm just using them wrong. The current behavior has a collapsed collection's largest tap target as everything other than the share and menu icons as expanding the collection which then shows a list of pages that can be opened individually.

At least how I've been using Collections, of all the possible actions including expanding, the only thing I've wanted to do is "Open tabs." I guess if there's telemetry on the menu items, might be interesting to see how people are using the feature.

**Comment by topotropic** [comment]
Please open the tabs from a collection in the same order as they are displayed in the collection – this helps people to find their tabs and they don't have to re-orient themselves. 

It also makes sense to update the order of the menu so that people quickly find "Open tabs"

- Open tabs
- Rename collection
- Add tab
- Delete

**Comment by mcarare** [comment]
Just a note: Actually, the tabs currently open in the order they are saved in the collection, but they are ordered in the list with the most recent opened on top. This makes the list look reversed to the one in the collection.

**Comment by topotropic** [comment]
right – I see; open tabs sorts new to old and collection sorts old to new; so whatever we do, we should stick to the same sorting scheme

**Comment by sv-ohorvath** [comment]
This is fixed on Nightly 9/22. But I think there's still place for confusion by ordering the tabs in a collection in the reverse order as they are in the list. 
E.g. When you click Save collection, you are presented with the list of open tabs to pick, you see an order there, then in the finalized collection you see them in reverse order.
@mcarare  Wouldn't it be easier to just keep everywhere the order they have in the open tabs list?

**Comment by mcarare** [comment]
@sv-ohorvath I can understand what you are saying, but I think this is a different problem. The problem in this issue was that you had a list (collection) and when you opened that list the order of the items was reversed. Even if we keep the order when saving to a new collection, the issue would still have presented. 

@topotropic If you think the order of saving them in a collection (the issue described by @sv-ohorvath ) is something we want to change, we can open a new issue and fix it.

**Comment by topotropic** [comment]
I added a new issue https://github.com/mozilla-mobile/fenix/issues/5528
