### ISSUE TITLE
[Bug] After clicking 'Open in Fenix' from a Custom Tab, all features no longer worked.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#3739]
From debugging #3609, the fix is missing a solution for the problem underneath: when click 'Open in..', the BrowserFragment starts up all the features when it receives the `onStart` Android lifecycle event, but immediately after receives an `onStop` even when the BrowserFragment is still shown on the screen (no following `onStart` is observed either).

We need to find out why the `onStop` is received prematurely since it stops **all features** from running immediately after entering the BrowserFragment.

TODO: Also revert the patch 084fab77d41801bd411208343fce22ade214e4b4 when a fix is found.

Similar STR as original PR:
 - Load page in CustomTab (e.g. from Reddit is Fun)
 - 3 dot menu -> Open in Firefox Preview
 - 3 dot menu -> Use any a-c feature (e.g. Find in Page, Reader View, etc.)

**Comment by ekager** [comment]
Did a bit more investigation and this is what I've found: 
- Does not have to do with our openToBrowser code (this is working correctly as far as I can tell)
- Order of starting the new intent and finishing the old activity doesn't seem to matter

**Comment by ekager** [comment]
It turned out to be a weird overlapping lifecycle problem. I solved it this way https://github.com/mozilla-mobile/fenix/pull/3775
I'm going to close this issue because the features are all working now after opening from a custom tab. 
This may not be the best way to solve this though so maybe the "Open in" use case you proposed could deal with this better.
