### ISSUE TITLE
Pocket Integration

### ISSUE THREAD

**Issue by kumarharsh** [mozilla-mobile/fenix#3788]
### Why/User Benefit/User Problem

As a regular user of Pocket, I'd like to be able to see the items I have in my list, and be able to access them from my browser.

### What/Requirements

In addition to putting stuff in Pocket, a user should be able to access previous content they have Pocket'ed. 

### Acceptance Criteria (how do I know when I’m done?)

I realise that Pocket is also a separate app, and putting all that functionality here is not feasible or desired, but Firefox should have some level of integration with Pocket.

The least amount of work I'd expect is to have a "View my Pocket" button near the my collections list. This button will open the app if it exists, or the website.

A slightly better integration would let the user view their recently Pocket'ed items in Firefox, and let the user open Pocket for full list.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12386)

**Comment by silanea** [comment]
Please keep Pocket restricted to an extension, once support for those arrives.

**Comment by cadeyrn** [comment]
@silanea: If there will be any prominent Pocket integration like the recommendations on the start screen in the old Firefox an option to disable it would be totally fine. If it's only something like an button to save something in the personal Pocket list and to access the Pocket list then I don't even think that an option is needed. Anyway, there is no reason why it has to be an extension, especially since Pocket is a service by Mozilla and not a third party.

**Comment by silanea** [comment]
@cadeyrn Not to open a discussion on Pocket itself, but every single line of code is a maintenance debt. Doubly so when the code interacts with a remote service. Fenix is being advertised as a lean secure browser. Integrating Pocket (or any other remote service) increases its attack surface and risk of bugs. Since it is a non-essential service and, to the best of my knowledge, not a very widely used one, I see no justification for including it in the browser itself.

**Comment by cadeyrn** [comment]
More than 30 million users according to Bloomberg, and you say "not widely used"? Also maintenance debt is not a strong argument, you can argue against everything with maintenance costs. And an extension has also maintenance costs.

Maybe you don't know it but there is already some kind of pocket integration in the old Firefox for Android, in Firefox for Amazon, in Firefox for Desktop and in Firefox for iOS. Why should the new Firefox for Android be the only Firefox product without any Pocket feature? And you also know that Pocket is one part of Mozilla's business? So it totally makes sense for Mozilla to use Firefox for pushing Pocket.

**Comment by Dakkaron** [comment]
Why was the pocket integration removed in the new Firefox? This was an amazing feature in the old Firefox.

**Comment by Dakkaron** [comment]
Pocket integration is done? Awesome!
If the tabs make their comeback, I can switch back to FF again!

**Comment by cpeterso** [comment]
@Dakkaron Sorry, saving articles directly to your Pocket account is not integrated in Firefox, but you can use the Share menu to save articles from Firefox to the Pocket app:

https://support.mozilla.org/en-US/questions/1365059

This GitHub issue was closed because we're moving Firefox issue tracking from GitHub to Bugzilla. See https://github.com/mozilla-mobile/fenix/issues/26855 for more information.

We have a new Bugzilla component for Fenix::Pocket issues:

https://bugzilla.mozilla.org/describecomponents.cgi?product=Fenix&component=Pocket#Pocket

**Comment by Dakkaron** [comment]
@cpeterso Oh, that's a little disappointing... Thanks for the correction.
I'd love to be able to return to FF. For now I'm stuck with Vivaldi, which also doesn't have all the features I want, but the most important to me (Tabs, keyboard shortcuts) are there.

I'd really be happy if you could implement these changes so that I can return to FF on Android. Using different browsers for FF and Windows is annoying, and Vivaldi for PC is much worse than FF for PC.
