### ISSUE TITLE
Swap tabs when using collections

### ISSUE THREAD

**Issue by Madis0** [mozilla-mobile/fenix#3804]
### Why/User Benefit/User Problem
When opening tabs from a collection, they are appended to the current tabs, even when using the option "open tabs". So what is the benefit of the collections if they still keep cluttering the tab list? 

I suggest to open all tabs of a collection at once and placing all current tabs to a new collection, therefore only showing the opened collection tabs on the tab list.

### What/Requirements
Add a feature to move current tabs to a new collection when opening tabs from any collection.
To improve the UX, also default to opening all tabs when tapping on an existing collection.

### Acceptance Criteria (how do I know when I’m done?)
- [x] #3005 
- [ ] Move existing tabs to a new collection
- [ ] Open all tabs when tapping on a collection as a default (separate tabs as an option when expanded)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12399)

**Comment by vesta0** [comment]
@topotropic I think this is a great idea to consider :)

**Comment by Djfe** [comment]
collections could be like tab groups

the feature could be combined with multi account containers. For example several collections belong to the account container shopping. One collection  is for new shoes, one is for a new TV, etc.
and then there are collections with the container work and so on.

one thing to consider:
right now collections are still "only" bookmarks/something like Pocket. They don't keep the session. (session cookies, scroll position, video/audio playback position, stuff entered into forms.

which is also a good thing. most tabs don't need that when they are saved and I'm already looking forward to using collections in my daily life once Fenix gets released and sorting my open mobile tabs this way.

this definitely would make the most sense to me in a way that I can delete read tabs/remove tabs from collections once I'm done with them.
Having to remove them from both open tabs and the collection could be quite a hassle once the collection grows beyond a certain size.

btw. to me "tab" kind of implied collections actually save the session even though they don't. though "save" already indicates that it is implemented differently, it still was something I had to figure out on first use.
either you want to change the wording (ux + testing with users what works best) or maybe saving the session isn't so bad after all?

As an example how I also would use collections:
have one/several pinned tab at the top like the YouTube subscription feed or the main page of a news page.
actual YouTube videos or news articles I want to read below. (watch/read later functionality)
once I read them I will delete them fro  the collection (not the pinned tab)

another use-case (others might have): a playlist for music videos on YouTube they listen to often, in that case they obviously want to keep all tabs in the collection

Depending on the implementation it would be nice if Firefox could automatically sort new tabs into certain collection(s) depending on the domain or the app it was opened from. (not automatically load them in a tab)
for example add news urls from BBC into the news collection.
Sort urls that don't fall into any domain category by the app: a collection for all links opened from the Facebook app that don't belong to a domain like the bbc
(I think, it makes sense to prioritize domain over app here, but it could be a setting)

If I surf on BBC and save an article, then Fenix should automatically add it to a collection if a filter applies else ask me which collection to choose.
Maybe give me the option to create a new filter for this type of url.
If I selected more than one tab and one filter doesn't apply to all tabs, then let the user choose.

I know this is an advanced feature but quite useful imo.
It could be realized similarly to the mail filters in thunderbird.

I wrote this here because I wanted to start a discussion on the direction of collections (and I think that this is related to swapping collections) and I also wanted to suggest the ideas I had.
I will now create separate feature suggestions for pinning tabs in collections and a filtering system and add links to this comment.

**Comment by vesta0** [comment]
@boek ^^

**Comment by tukusejssirs** [comment]
Although #3005 is closed as it dealt with Fennec, it is not working that way in Fenix, which I why I have open another issue #11463.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812765

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
