### ISSUE TITLE
[Bug] (L10N) regression: alignment issue when saving tabs to collection

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3843]
There is a regression in master branch. The problem does not exist in Fenix 1.0.0. It does not happen with the English translation.

### Steps to reproduce

0. switch language to German
1. press the "save to collection" button on the Fenix start screen
2. select at least one tab

### Expected behavior

No alignment issue.

### Actual behavior

Please have a look at the purple bar. The "1 Tab ausgewählt" has moved to the top.

![Screenshot_20190701-234621](https://user-images.githubusercontent.com/1100614/60497610-78ba4e00-9cb5-11e9-972a-a87dd79ae0b3.png)

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 50052c9b9bee6c15a6517eed75834f78b945ea5c

**Comment by cadeyrn** [comment]
It still happens in 1.1.0 RC 1. @vesta0 Since it's a regression (the issue was not there is 1.0.1) and it affects one of the core features of Firefox Preview, meaning it has a high visibility - should this be fixed for 1.1.0?

**Comment by mihai-adrian** [comment]
The text is actually centred, but it is centred as if the textview had two lines of text, when the text is nearly filling one line of text. The regression is due to removing the singleLine attribute. To avoid the text spreading on two lines with a blank line at the bottom, we can change the height attribute, to be calculated using constraints.

**Comment by sv-sdeiac** [comment]
Verified as fixed on Firefox Preview 1.2.0-rc.2 using Nexus 9 (Android 7.1.1) and LG G7fit (Android 8.1).
