### ISSUE TITLE
[Bug] keep URL bar position consistent

### ISSUE THREAD

**Issue by blokeley** [mozilla-mobile/fenix#3862]
## Steps to reproduce

When reading a web page, the URL bar is at the bottom of the screen, which is probably deliberate and sensible given that the user's thumb can reach the bottom of the screen easier than the top on most mobile devices.

However, when Firefox Preview is opened or on a new tab, the URL bar is in the middle of the page.

When the user focuses on the URL bar, it zooms up to the top of the page! Just because Chrome does that, it does not make it a good user experience.

### Expected behavior

Keep the URL bar at the bottom in all cases. Even if entering text. It is jarring to have it move around.

### Actual behavior

The URL bar could be at the bottom of the screen, or the top, or the middle depending on what's happening at that moment. It's not a consistent UI.

### Device information

* Android device: Nokia 8 Sirocco
* Fenix version: 1.0.0

**Comment by cadeyrn** [comment]
> Just because Chrome does that, it does not make it a good user experience.

The user experience from Chrome is totally different so it's inappropriate to argue with "just because Chrome does it Mozilla shouldn't do this". The behaviour of Fenix has nothing to do with Chrome at all…

FWIW I like the toolbar at the bottom and movement to the top when I enter something into the address bar because it makes sense. It would be confusing for me to have the suggestions above the address bar. The address bar stays on bottom in the Reference Browser and I don't like it at all, in my opinion it looks much better in Fenix.

I don't have a strong opinion about the search field on the Fenix start screen. If that changes, it's less of a problem for me.

**Comment by blokeley** [comment]
This is indeed a duplicate of #562 so I'll close it.

Whichever way the decision goes, I hope it is based on good User Interface and User eXperience [sic] design rather than the personal opinions of one or a few people.  

Consistency in the UI is one of the first principles that all UI research and guidelines promote.  Examples include:

* "[Create consistency ... in layout](https://www.usability.gov/what-and-why/user-interface-design.html)" from none other than `usability.gov`
* "[Consistently place elements throughout your site or app](https://designshack.net/articles/graphics/maintaining-consistency-in-your-ui-design/)"
* "[controls should be consistent so that users know how to repeat their actions](http://www.argondesign.com/news/2014/feb/5/5-aspects-good-user-interface/)" and so on.
