### ISSUE TITLE
The URL should not be displayed when accessing URL bar while a tab is opened

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3924]
### Why/User Benefit/User Problem
As a user I want to be able to write text on the `URL` bar when tapping on it without deleting the previous URL.
### What/Requirements
For example if tapping on the `URL` bar while a tab is opened, the URL text should be hidden and the cursor should be on the `URL` bar and the text can be added without deleting the `URL` from the opened tab. 
Note that accessing web pages when accessing URL bar from a tab will be more faster.
### Acceptance Criteria (how do I know when I’m done?)
The `URL` is hidden when tapping on the `URL` bar while a tab is open.
### Note
When opening a new tab with www.google.com for example, when tapping the URL bar, no URL text should be displayed but when tapping back www.google.com should be displayed.
Also, the URL text will still be available while the page is open.

**Comment by cadeyrn** [comment]
I know that Chrome hides the URL but since the URL is automatically selected in Firefox and Fenix there is no need for the user to remove the URL, you can immediately start typing. It's only a visual difference, accessing web pages is _not_ faster with the proposed change.

Please also note that, at the moment, it's the only way to see the full URL in Fenix because you can't scroll within the address bar. That's an other issue but I guess to change the scrolling issue is a requirement for this proposal.

**Comment by buttercookie42** [comment]
And hiding the current URL of course makes it rather difficult if you want to actually _edit_ or otherwise access the current URL (e.g. to copy only parts of it).

**Comment by lime124** [comment]
Hi @abodea what I'm reading is that the core problem you are trying to solve is that you would like to be able to immediately start typing text after tapping on the URL bar. If I'm understanding that correctly, I believe Fenix already allows you to do this.

STR
1. Browse to any webpage (e.g. centipedes on wikipedia)
2. Tap URL bar
3. Tap any letter on the keyboard

Results
The bar animates to the top of the screen, the entire string (current URL) is selected. Pressing any letter on the keyboard replaces the entire selected string with that letter. 

If I've misunderstand something, I'm so sorry.  Could you please elaborate further on the problem? Otherwise please close the issue. Removing the ux label as there is no further action for us to take right now. Thanks!
