### ISSUE TITLE
[Bug] Unable to share to other devides

### ISSUE THREAD

**Issue by jcursiolf** [mozilla-mobile/fenix#3969]
## Steps to reproduce
So far, I just need to open Firefox Fenix and it happens.

### Expected behavior
Be able to share to my other devices with Sync activated.

### Actual behavior
I do not see other devices. 
_Note_: I am having many problems with #3877 and, even right after logging in, the other devices do not show up.

[Screenshot_20190709-093658](https://user-images.githubusercontent.com/41722528/60957221-94040980-a304-11e9-9d71-3ec8be81c1c8.jpg)

### Device information

* _Android device_: OnePlus 5 (model A500, Android version 9, OxygenOs version 9.0.6, no root, no ROM)
* _Fenix version_: Nightly 190709 18:02 Build # 11901819 (Note: this is the actual version, but it has been happening for at least 10 days)

**Comment by krzyk** [comment]
Same here (I also have issues with #3877), device Pixel 3, Android version 9.
I is happening since some time, I don't know exactly because I frequently stopped trying to share to other devices because of #3877 being a major PITA.

**Comment by mackncheesiest** [comment]
A similar issue started happening me within the last couple weeks as well. I'll add it here rather than make a new issue

In my case, the "send to device" menu does appear, but it just says "Offline" despite clearly having this device online and other devices online, all signed in to my firefox account

Android device: LG V20, non-root, non-custom ROM stock Android 8.0.0
Fenix build: Nightly 191224 18:02 (Build #13581811)

**Comment by mackncheesiest** [comment]
For the record, the feature still works fine in my baseline FF Preview with build info:
3.0.1 (Build #13502256)
📦: 24.0.0, 968f858c1
🦎: 71.0-20191125115111

**Comment by ekager** [comment]
Closing because this is very old. Please open new issues if this is still happening
