### ISSUE TITLE
[Bug] Can't scroll the turn on sync screen in landscape mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3998]
## Steps to reproduce
1. Go to Settings>turn on sync.
2. Switch to landscape mode. Scroll down to see the buttons.
### Expected behavior
Can scroll down
### Actual behavior
Can't scroll to reach the 2 buttons.
### Device information

* Android device: Galaxy S8 (Android 9), HTC 10 (Android 8)
* Fenix version: 1.0.1928, 7/11 Master build

**Comment by AndiAJ** [comment]
Hi, the issue is still replicating on the latest **`Nightly Build #11960610 from 15/7`** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S8+(Android 8)
• Samsung Galaxy S7 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)

### Note
It works fine on Huawei MediaPad M3 Lite 10 (Android 7)
 
►Video Google Pixel 3a
![20190715_105730](https://user-images.githubusercontent.com/51314259/61202487-4ca8bf00-a6f0-11e9-8bb5-b6bc3c359a6e.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #11990109 from 18/7** using the following devices:
 • Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)  


►Video from Google Pixel 3a
![20190718_103708](https://user-images.githubusercontent.com/51314259/61438570-7825e680-a948-11e9-8830-ecb29b8cc327.gif)
