### ISSUE TITLE
[Bug] Tab(s) Sent snackbar confirmation displays over toolbar

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#4010]
![Screenshot_20190711-151758](https://user-images.githubusercontent.com/40694158/61050906-bc693200-a3f0-11e9-868d-551dce4d2099.png)

## Steps to reproduce
1. Send current page while browsing 

### Expected behavior
Snackbar displays above toolbar like other snackbars

### Actual behavior
Snackbar displays covering toolbar

This seems to be a drawback of the "easy" solution that we decided on. The solution to this could be to go back to creating and passing a unique callback through to the ShareFragment from each Fragment through MainActivity so that we can pass an anchor view for each fragment. What do you think @jonalmeida ?

**Comment by jonalmeida** [comment]
@pocmo [reminded me](https://github.com/mozilla-mobile/reference-browser/pull/794#issuecomment-499143219) that we use the `BrowserToolbarBottomBehavior` to fix this in the BrowserFragment. That might be a solution as well.

There was an issue where the behaviour wasn't working in r-b, but that might be scoped to only being an r-b issue.

I can take a look at it soon if you'd like!

**Comment by ekager** [comment]
Hm I'm not sure if that'll work since we're just relying on HomeActivity to handle displaying the snackbar which doesn't know about the toolbar?

**Comment by jonalmeida** [comment]
You're right! I didn't read the docs as I should have. According to it, that behaviour only works if the view is a layout child:

> Determine whether the supplied child view has another specific sibling view as a layout dependency. 

My next guess is if we can set the context of the toast to be that of the current fragment so that it would work as expected.

```kotlin
val currentFragment = getVisibleAndSelectedFragmentHereMagically()

currentFragment?.context?.let {
    FenixSnackbar.make(it, Snackbar.LENGTH_SHORT).setText(
        getString(
            if (tabsSize == 1) R.string.sync_sent_tab_snackbar else
                R.string.sync_sent_tabs_snackbar
        )
    ).show()
}
```

Making each fragment implement the callback and pass the tab count doesn't feel like the best way forward.

/me needs to think more about this..

**Comment by ekager** [comment]
We could do what I did as an intermediate step and pass a created callback (call a function in HomeActivity to create the callback while setting the anchorView when that callback happens)?

**Comment by jonalmeida** [comment]
With the intermediate step, wouldn't the problem still exist since the snackbar is being created with the HomeActivity context? I imagine the way to make it work is to use the context of the current fragment so that the snackbar is a child of that fragment's layout.

Your original solution would definitely work but I'd like to investigate a more minimal solution that avoids duplicating the code across all the fragments.

**Comment by ekager** [comment]
You can get the current fragment id through the Navigation library like ``navHost.navController.currentDestination?.id``

**Comment by Mugurell** [comment]
I think this is fixed by now. Closing.
