### ISSUE TITLE
[Bug] Font inflation makes bugzilla unusable

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#4050]
## Steps to reproduce
Go to https://bugzilla.mozilla.org/show_bug.cgi?id=837752 

### Expected behavior
Page renders normally

### Actual behavior
Looks ugly because font sizes are very random looking. Button labels are truncated, text is leaking out of the containing elements, etc.

### Device information

* Android device: 9
* Fenix version: 1.0.1 (Build #11891918 🦎 68.0-20190611143747)

**Comment by buttercookie42** [comment]
[Bug 1552781](https://bugzilla.mozilla.org/show_bug.cgi?id=1552781) should have improved the situation regarding the "random looking" font sizes around the comment box (assuming it's that what you meant?), though it seems that even Fenix Nightly builds are still stuck on some outdated GeckoView version predating the fix for that bug.
Unless I'm overlooking anything else, that leaves mainly the buttons, which I think aren't quite as bad looking as the font sizes around comment box, but indeed still shouldn't be overflowing things. Though maybe they shouldn't even be inflated in the first place [1]? Can you file a Core::Layout bug (possibly "Text and Fonts" specifically?) and CC me, please?

[1] (Chrome leaves the buttons alone, so maybe we should, too - although their font inflation algorithm also seems to fail to handle Markdown-enabled Bugzilla comments, so isn't entirely fool-proof, either).

**Comment by staktrace** [comment]
I'll wait until there's a Fenix version that includes that bugfix and see what the state is like.

**Comment by buttercookie42** [comment]
I did take an initial further look regarding the buttons and filed [bug 1566632](https://bugzilla.mozilla.org/show_bug.cgi?id=1566632) regarding the buttons after all.

**Comment by ekager** [comment]
Font inflation is off for automatic font size now and the bugzilla links looks fine to me. I'm closing this for now until I get more direction from the GV team about what Fenix should do here

**Comment by buttercookie42** [comment]
@staktrace The partial fix I mentioned is on ESR, too, so could you try a Fennec Nightly to see whether there's anything other than the button issue left?

**Comment by staktrace** [comment]
What prefs do I need to set in Fennec to replicate the Fenix font inflation settings? I don't see anything in [geckoview-prefs.js](https://hg.mozilla.org/mozilla-central/file/tip/mobile/android/app/geckoview-prefs.js)

**Comment by buttercookie42** [comment]
Turning on Settings -> Accessibility -> Use system font size should be enough (otherwise make sure *font.size.inflation.minTwips* is set to 120 or something around that value).

**Comment by staktrace** [comment]
Looks like just the buttons are bad now.

![Screenshot_20190809-123152](https://user-images.githubusercontent.com/485789/62794300-bd4dbc00-baa1-11e9-86b8-1be833e93fbe.png)

**Comment by buttercookie42** [comment]
Just for the record, the buttons issue should now be fixed as well.
