### ISSUE TITLE
[Bug] Failing UI test - settingsAfterScrollMenusTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#4094]
The settingsAfterScrollMenusTest (UI test) is failing in Firebase on API 21.
Click on link to Firebase dashboard:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8610891157502804039
Drill down on failing API and click on tabs or "Test Results" button on upper right to view raw logs in GCP.
```
07-16 12:51:51.696: I/TestRunner(25691): ----- begin exception -----
07-16 12:51:51.698: I/TestRunner(25691): androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/switch_widget
```

**Comment by isabelrios** [comment]
The issue is happening because we are using tapping on the `Set as default browser`option to scroll down and so take the screenshots of the different Settings menus. Looks like on API 21 that option is not available and so the test fails.
Nexus 6 API 21:
<img width="255" alt="Nexus 6 API 21 Different Settings list" src="https://user-images.githubusercontent.com/1897507/61357894-72150480-a879-11e9-81a4-5650454deedb.png">

Pixel API 28:
<img width="304" alt="Pixel API 28" src="https://user-images.githubusercontent.com/1897507/61358011-b30d1900-a879-11e9-8f51-db2ae0683ba8.png">

I have realized that we don't have to scroll step by step since all the menus are shown when entering at Settings menu and scrolling to bottom, so I will modify the tests to avoid scrolling using settings menu options. This way we can get rid of test `settingsScrollToBottomTest`which was also failing.

With this approach the test is green on [Firebase](https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.dee052bb5e1bdd86/matrices/7084502824008663962)
