### ISSUE TITLE
Remove raptor-specific activity and config

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#4132]
Raptor can now test and run again the release build directly. It no longer needs to pass along specific intent arguments. It is just launching a .VIEW intent with a provided url. The Gecko runtime parameters are written to a config.yaml file before the app is launched.

With this, we can now remove our custom [BrowserPerformanceTestActivty](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserPerformanceTestActivity.kt), the `testConfig` global state, as well as the custom build `forPerformanceTest` and the relevant parts of the build scripts. 🎉 

@JohanLorenzo as far as I know, the forPerformanceTest build is only used by Raptor. Any concern about removing it? Definitely need some help here removing all bits correctly. @rwood-moz is already updating his script to switch to the release build: https://bugzilla.mozilla.org/show_bug.cgi?id=1566905

**Comment by JohanLorenzo** [comment]
> @JohanLorenzo as far as I know, the forPerformanceTest build is only used by Raptor. Any concern about removing it?

This removal makes sense to me. I'm not aware of any other projects using that build. Thanks for letting me know :)

**Comment by JohanLorenzo** [comment]
cc @mitchhentges because [bug 1566905](https://bugzilla.mozilla.org/show_bug.cgi?id=1566905) will use different indexes.

**Comment by mitchhentges** [comment]
I believe that we still want the `forPerformanceTest` build type for two reasons:
* I believe it's used by @hawkinsw for browser-chrome performance testing
* We still need a generic "optimized" build for Raptor. If we don't use `forPerformanceTest`, then what will we use? `nightly`/`beta`/`production` shouldn't be used, because they're tied to specific channels (and have associated secrets). `debug` shouldn't be used, because it's not optimized. We _can_ re-enable the `release` build type, but then we'll have the same confusion we had months ago ("is 'release' the production build of Fenix? Is it the same as 'production'? How is it different? What do you mean it's _only_ used for tests?")

**Comment by csadilek** [comment]
After talking this through with @mitchhentges, we'll keep the build type and just remove the unneeded activity and related configuration.

**Comment by mcomella** [comment]
I did an analysis in #6464 & `forPerformanceTest` is still important: see [the updated Fenix readme](https://github.com/mozilla-mobile/fenix/#performance-build-variants) for a summary and my conclusions in https://github.com/mozilla-mobile/fenix/issues/6464#issuecomment-568045860.

In the future, please keep me in the loop wrt performance build configuration changes!

**Comment by mcomella** [comment]
Addressed with https://github.com/mozilla-mobile/fenix/pull/13237.
