### ISSUE TITLE
On tablet move some of the commands - like forward, back, refresh - from the menu next to the URL window

### ISSUE THREAD

**Issue by Chris01277** [mozilla-mobile/fenix#4134]
I use the Firefox Preview aka Fenix ​​on a 10 "tablet, which offers enough space.
 Elsewhere I had said that I would miss the tab design on a tablet as on the desktop or like the current Firefox for Android in tablet design.
 However, I can become more and more familiar with the current design of Fenix.  The undeniable advantage of the large overview image of all currently open browser windows is that they can identify them better than the tabbed tabs.  For that you should be able to accept the one more tap.
 But I would like to see some of the commands - like forward, back, refresh - move from the menu next to the URL window.

**Comment by LittleAngelwings** [comment]
In association with this: https://github.com/mozilla-mobile/fenix/issues/2344

**Comment by Chris01277** [comment]
Thanks for the link: #2344 from Kuvesz.  I have already seen this.  
 But Kuvesz pleads for a tab design like seen at Firefox for desktop I do not necessarily want.  I think the current UI is basically OK, but in case of sufficient form factor - like a tablet - some commands from the 3-point menu should be moved or duplicated next to the URL bar.

**Comment by Lululalu** [comment]
As someone who uses a tablet every single day I wish I could open just certain websites in desktop mode. I still prefer mobile webpages, but some websites (my local super market for example) just doesn't have a great mobile experience. As of today I know no browser that offers per-site desktop mode.

**Comment by black7375** [comment]
There are examples like [Whale](https://play.google.com/store/apps/details?id=com.naver.whale).

We need to modify the design to fit Fenix, but I think it will be helpful not only for tablets but also for general mobile users.
UI that shows the URL as much as possible is useful, so I think we should use it as an option.

![Whale-0_Toolbar](https://user-images.githubusercontent.com/25581533/94687085-3ac63280-031b-11eb-9c98-b6e902e8228f.jpg)

**Comment by DrBrainsDude** [comment]
Put the navigation buttons in the main UI!!!!!!(next to the URL) WHY is this so difficult??! WHY have some people/moderators here decided that just because THEY don't think this is useful NOBODY ELSE should at least have the OPTION to display them where they should be, and not hidden away behind a menu button!!!?!? If I want to do something as simple as go forward one page i have to through FOUR steps!!!! (instead of only two on a browser with regular navigation buttons! 1. Move my finger/pointing device all the way up to the uppermost righthand corner. 2. Click on the #$@%^^ menu button(!!!). 3. Move my hand/finger/pointing device to the "forward" arrow. 4 . Click on that. WHO thought this was a GOOD IDEA???! AMAZING.

**Comment by ssk97** [comment]
This issue can be closed, as the buttons were added in #20818!

**Comment by LittleAngelwings** [comment]
But there is no alley for left or right handed users...

**Comment by cadeyrn** [comment]
A mode for left-handed users is not related to this issue. Please see #6365 for your feature request.

**Comment by sflorean** [comment]
Verified as fixed on tablets, on latest Nightly build. Closing as verified.
