### ISSUE TITLE
[Bug] Rotation in video full screen mode not supported

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4143]
## Steps to reproduce
1. Navigate to youtube.com
2. Play a video
3. Enter full screen mode
4. Rotate device

### Expected behavior
After the fix from #1343 after entering full screen view the image is now exclusively displayed in landscape mode.
Rotation should be supported as in Chrome.

### Actual behavior
Nothing happens after rotating the device while in full screen mode.

### Device information

* Android device: 
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)  

* Fenix version: Nightly Build #11990109 from 18/7

**Comment by Dunexus** [comment]
I noted two differences with Fennec and Chrome implementation of full screen mode : 
- on Fenix, vertical videos triggers landscape mode when entering full screen mode
- on Fenix, while in landscape mode, we can't flip the phone to get the landscape to the other direction

**Comment by ekager** [comment]
The second issue is easy to address, just setting a different flag thanks for pointing that out! 
The first issue not so much. Could you link to a good example of a vertical video for testing @Dunexus ? :)

**Comment by Dunexus** [comment]
@ekager 
I tested full screen mode on Fenix, Fennec and Chrome with this video https://www.youtube.com/watch?v=zyR5HRmqyIs

From what I infer about how Fennec handles the rotation choice, it takes the ratio height/width of the video at the moment it enters in full screen mode to choose between portrait and landscape mode.

However, there is an issue with this behavior. If you enter in full screen mode before the browser has the height/width data (e.g. going full screen mode before pressing play to start loading the video) it will go by default in portrait mode and stay in portrait mode even if the video turns out to be landscape.
This issue is shared by Fennec, Chrome and even Youtube app (it happens when the ad is in portrait and the video after is in landscape).
To be honest, this isn't very annoying and I don't know how hard it would be to detect and switch landscape mode on the go.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build of RC 1.2.0-rc.2 with Sony Xperia Z5 Premium (Android 7.1.1), Huawei P9 Lite (Android 6), and Motorola Moto G6 (Android 8).
