### ISSUE TITLE
FxA create account flow is confusing

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4195]
Currently I find our create account flow for FxA a bit confusing. If I'm a new user it's not clear to me how to create an account. The first button I press is "Use email instead" (and says nothing of creating a new account).

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/61571681-19489600-aa4a-11e9-91b6-7ae9bda63a77.png">

Then when I get to the new page, it's not clear that I can enter a new email to make a new account (usually websites have a separate create account flow)

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/61571683-1c438680-aa4a-11e9-85c6-85f4e54ab2e4.png">

Is this intentional? I think we may want to consider changing this flow on the Fenix or FxA side.

@ryanfeeley for your input :)

**Comment by ryanfeeley** [comment]
It's intentional, and seems to perform well where we do this single-button-to-authenticate pattern on desktop.

I'm hesitant to change language, perhaps @mheubusch has an opinion?

Perhaps instead of the Fenix headline **Sign in with your camera** we could say **Connect an account with your camera**.

**Comment by ekager** [comment]
Closing for #12829
