### ISSUE TITLE
Bookmarks should be displayed in a tree with directories and subdirectories

### ISSUE THREAD

**Issue by Chris01277** [mozilla-mobile/fenix#4203]
For years, I have been using a sometimes very deep tree of bookmarks.  On the desktop, this tree is displayed similar to a file manager in the sidebar of Firefox.  With Fenix ​​(and Firefox for Android on a tablet) you have to go blindly through the directories and subdirectories.  
I would like Fenix ​​to display on a tablet a representation of the bookmarks in a tree with directories and subdirectories, with the branches closing as soon as they leave.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12664)

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

This will be great if also it implemented in mobile UI, 

For me (as someone that heavily use bookmarking system) one of the biggest advantages of Firefox Desktop over chrome is its tree like bookmark page. (one of the biggest reasons i switched from chrome to firefox was this)

But both classic firefox for android (fennec) and firefox preview (fenix) don't have that great option and using bookmarking system in mobile is really annoying/frustrating.

Please if may consider this on new firefox android (fenix) because it will make it far more enjoyable to use.

Thank you very much

**Comment by jrollf** [comment]
"But in both classic firefox for android (fennec) and firefox preview (fenix) when we add a new bookmark and edit it to change its folder the browser shows all folders open and it is really annoying/frustrating."

This is my biggest complaint about the mobile browser.  Please make the bookmark structure collapsible when saving/editing bookmarks.

**Comment by jrollf** [comment]
> Hello
> 
> This will be great if also it implemented in mobile UI,
> 
> For me (as someone that heavily use bookmarking system) one of the biggest advantages of Firefox Desktop over chrome is its clean ui of bookmarks page. (one of the biggest reasons i switched from chrome to firefox was this)
> 
> But in both classic firefox for android (fennec) and firefox preview (fenix) when we add a new bookmark and edit it to change its folder the browser shows all folders open and it is really annoying/frustrating.
> 
> Please if may consider this on new firefox android (fenix) because it will make it far more enjoyable to use.
> 
> Thank you very much

This is my biggest complaint about the mobile browser.  Please make the bookmark structure collapsible when saving/editing bookmarks.

**Comment by ratkiley** [comment]
It is a very confusing and difficult to navigate display of bookmarks in nested folders on mobile phones.  This makes the app completely unusable for me. So much so that I uninstalled firefox the day after it was upgraded to 79.0.5, abandoning the browser for a more functional one.

**Comment by WebworkrNet** [comment]
It is pleasing that this request is still open and has not been closed in the meantime. But it is not on the agenda either. That is a pity. Implementing it would bring immense added value. Apart from the fact that many, many other tickets are still open and new ones are added daily, what is the problem here?

**Comment by marco-eckstein** [comment]
I have used Firefox  on Windows for many years. On Android, I have waited with switching from Chrome to Firefox because I was worried it may not be mature enough yet, but I want to switch now. I am shocked by the horrible bookmarks UI, this issue being open for 3.5 years and having only seven likes.

However, the scope of this issue is too narrow. This is definitely not just a tablet issue. It applies to phones just as well. Maybe the _b:tablet_ label is the reason why this issue has gained so little traction. @topotropic, can you please remove that label?

Additionally, I think the feature request is too specific. Always showing the fully expanded bookmark folder tree is an issue when you have dozens or hundreds of deeply nested folders. There are multiple viable solutions. The easiest one should be implemented ASAP, while the other ones could be supported later via an option:

1. Display a tree with manually collapsible folders
  - This is what we have in in Firefox on desktop.
2. Display a tree with automatically collapsing folders
  - This is what the OP has requested,
  - Ideally, this would be a configurable option for 1.
3. Display only one level of the folder hierarchy and allow navigation through the hierarchy
  - This is what Chrome does on Android.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812725

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
