### ISSUE TITLE
Option to disable Quick Action Sheet

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#4204]
### Why/User Benefit/User Problem

Some users may find the Quick Action Sheet to be distracting and redundant to the main menu functionality.  It is easy to accidentally open it and it takes up valuable screen space.

### What/Requirements

Either an option in the main settings or about:config to disable it.

**Comment by Poopooracoocoo** [comment]
I don't even think this should be an option which is why I created #4210 @kbrosnan

**Comment by Poopooracoocoo** [comment]
@cadeyrn hi. out of curiosity, why did you react to my comment with a thumbs down?

**Comment by cadeyrn** [comment]
@Poopooracoocoo: Because I disagree with your comment?

**Comment by Poopooracoocoo** [comment]
@cadeyrn Why do you like the idea of the QAB? 

You already have to swipe up to see it. In Chrome (and in the native android menu) you can swipe to open the menu. There are issues suggesting that. This is what I think.

It's obvious that you disagreed with my comment. I didn't have any attitude towards you. T.T I just wanted a discussion and wanted to know why you disagreed.

**Comment by cadeyrn** [comment]
> Why do you like the idea of the QAB?

Because it's a) faster than opening the menu and b) not overloaded with all the menu items. It contains only a few important page specific actions. With the full menu you can't reach all menu item with only one hand. So you have to make sure that the current QAB actions are all on the bottom of the menu. But if the menu structure changes other menu items will be more difficult to reach. So as long as there is no good proposal to solve this I am strongly against removing the QAB.

Of course it's possible that I will change my opinion if/when there will be a good proposal. But so far there is no proposal attached to this issue.

> In Chrome (and in the native android menu) you can swipe to open the menu.

Nope, that's not true for Chrome on my device.

**Comment by Poopooracoocoo** [comment]
@cadeyrn I don't mean swipe but tap, hold and drag to an item and then release. 

Thank you for telling me why you like the QAB. I personally don't share, bookmark or use reader mode that often. It reminds me of Firefox for desktop's page actions.


If I were to move the buttons I would place them like this: (not my screenshot, it's from the Kiwi Browser Discord server. I don't even understand German)
![](https://cdn.discordapp.com/attachments/494885717562884098/577176546939240449/Screenshot_20190512-184713.png)

or place some in the address box.

Although I've definitely changed my mind.

**Comment by cronosun** [comment]
Somewhat related: [https://github.com/mozilla-mobile/fenix/issues/3852](https://github.com/mozilla-mobile/fenix/issues/3852)

**Comment by vesta0** [comment]
We will address this here #4281
