### ISSUE TITLE
Option to automatically change theme at sunrise/sunset or at a set time

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#4236]
### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12692)

**Comment by shahsurajk** [comment]
This was once a feature in the support library, but since it requires location permission to calculate the sunrise/sunset time and the fact that *still* computing the sunrise and sunset times is not accurate, these were removed. A fact to note here is that this feature can introduce more bugs than actually providing features. A thing rather to look out for would be the "battery mode" which is turn on night mode when battery is low.

**Comment by anmol257** [comment]
Users should be able to select a fixed time at which to turn it on & off based on their mobiles time.It would be very convenient for everyone

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807083

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
