### ISSUE TITLE
[Bug] Making changes to a collection, moves it to the top of the list

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4239]
## Steps to reproduce
1. Save 2-3 collections.
2. Make changes to the last one from the bottom: rename it, or remove a tab, or add a tab.
### Expected behavior
It remains in its position in the list.
### Actual behavior
It moves at the top of the list.
### Device information

* Android device: Nexus 5 (android 6.0.1)
* Fenix version: 1.1.0 rc2

**Comment by sblatz** [comment]
I believe this is expected behavior. Can UX please confirm?

**Comment by lime124** [comment]
thanks sawyer! @topotropic can you please take a look and comment. please either close due to expected behaviour or label "ready for eng". thanks!

**Comment by thewhitetulip** [comment]
Shouldn't be expected behaviour! As a user, I have muscle memory about my collection tabs. I use collection as a bookmark service and because I added a new news site to my news collection, my social collection is where my news collection was present.

So every time for a few weeks I opened reddit instead of my news site

**Comment by mcarare** [comment]
@topotropic Could you please confirm what is the expected behaviour in this case?

**Comment by topotropic** [comment]
Yes, @thewhitetulip's explanation makes sense, please don't sort collections after last edit. Thanks!

**Comment by sv-ohorvath** [comment]
This is verified as fixed on Nightly 9/22.
