### ISSUE TITLE
[Bug] Stay & show the empty state message after clearing all TP exceptions

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4265]
## Steps to reproduce
1. Add a TP exception.
2. Go to Settings>TP>Exceptions.
3. Clear all exceptions.
### Expected behavior
The view stays on the Exceptions list. The empty list message is displayed.
### Actual behavior
The exceptions list is closed, returns to the TP menu. The message is displayed if you go back to the Exceptions list.
### Device information

* Android device: Huawei P20 (Android 9)
* Fenix version: Nightly 190724 Build #12050609

**Comment by ValentinTimisica** [comment]
Hi,

I investigated this issue and from the code ([reloadData method](https://github.com/mozilla-mobile/fenix/blob/9bc0122ce3cf6d5bdf2ad7eb8c3cc10dc6eb0479/app/src/main/java/org/mozilla/fenix/exceptions/ExceptionsFragment.kt#L105)) it appears that this is the expected behaviour (to return to the TP menu if the list is empty). I think we need the UX to confirm this.

**Comment by lime124** [comment]
@AmyYLee

**Comment by AmyYLee** [comment]
@lime124 @ValentinTimisica Hi, when the user taps "clears all exceptions" button it should stay on the exceptions list screen so the user can see that the items have been cleared. Please fix to match the expected behavior. Thanks!

**Comment by sv-ohorvath** [comment]
Verified as fixed on RC1.2-rc2.
