### ISSUE TITLE
Refactor getSessionById

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4282]
We should refactor getSessionById to just always return a session. I think it should just be calling `selectedSessionOrThrow`

**Comment by jonalmeida** [comment]
Thanks for filling this!

> I think it should just be calling selectedSessionOrThrow

I don't recommend doing this because the usages of getSessionById are not always safe, which would lead to crashes (which is what it used to be).

This might be an excellent opportunity to use the `browser-state` component for observing the selected session changes and refactor all the usages of `getSessionById`.
