### ISSUE TITLE
Refactor out openToBrowserAndLoad and browserMode off of HomeActivity.

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#4287]
We're using this everywhere and we should come up with a better strategy going forward

**Comment by colintheshots** [comment]
As I've pointed out, it's considered a bad practice to assume your fragment is directly attached to a particular activity and call those methods directly by casting. The old-school solution was to [bind an interface and re-bind to a dummy interface when unattached](https://developer.android.com/training/basics/fragments/communicating#DefineInterface).

**Comment by Mugurell** [comment]
Just throwing it out there... sorry if it has been discussed.
Instead of imperative calls wouldn't it be better 
- if the Activity would have it's own State for destinations (same possible destinations as in the nav_graph)
- use the `BrowserDirection` (and/or other properties) in a Reducer similar to what [is used in HomeActivity#openToBrowser()](https://github.com/mozilla-mobile/fenix/blob/4747f2c16596306c1ebe3b56838df1d37d5a5040/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L225) and ultimately 
- render the new state on the screen - actually navigating to a new fragment / loading a new state for the one on top

Sticking to MVI in this case also would reduce the coupling but maybe going full MVI would be non-trivial because of the navigation component actually handling the back stack.

**Comment by liuche** [comment]
What's the status here, and should we carry this forward to the next sprint? Trying to get an idea of the remaining work.
