### ISSUE TITLE
[Performance] Unconditional Inflation of Quick Action Sheet view

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4308]
## Steps to reproduce
1. Start a SysTrace session.
2. Start Firefox Preview from an external application link with the app warmed up and no pages loaded.
3. End SysTrace session.

### Expected behavior
The Quick Action Sheet view should not get inflated until the user clicks the button to use the feature.

### Actual behavior
The Quick Action Sheet view is inflated on warm startup, taking ~50ms on a Nexus 5X and >15ms on a Samsung Galaxy S8. On every device, one or more frames are skipped.

[SysTrace output: output.html.zip](https://github.com/mozilla-mobile/fenix/files/3433402/output.html.zip)

### Device information

* Android device: Nexus 5X and Samsung S8
* Fenix version: 1.1.0

**Comment by sblatz** [comment]
@colintheshots can you please place a priority on this so we know if it's critical to work on

**Comment by hawkinsw** [comment]
I know that it's obvious, but this is also an issue for cold start. Just flagging it.

**Comment by hawkinsw** [comment]
According to my measurement, for Cold Start this accounts for approximately 4.5% of total startup time.

**Comment by hawkinsw** [comment]
[cpu-art-20190924T162731.zip](https://github.com/mozilla-mobile/fenix/files/3649311/cpu-art-20190924T162731.zip)

**Comment by sblatz** [comment]
The quick action sheet is always present on the screen in browser fragment which is why it's getting inflated even before the user wants to interact with it. It's how "bottom sheets" work (it peaks out to hint to the user that it's there). We would have to change the styling of this feature and re-work it quite a bit to get this performance bump.

I recommend we hold off on that for now since we're already investigating making items inside the sheet more discoverable.

**Comment by mcomella** [comment]
Severin is in the process of removing the Quick Action Sheet: https://github.com/mozilla-mobile/fenix/issues/4281 I am pre-emptively closing this bug.
