### ISSUE TITLE
allow users to sort bookmarks

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4348]
### Why/User Benefit/User Problem

Please allow users to sort the bookmarks. How to reorder your bookmarks is a question that comes up in support for _Fennec_ again and again. On Desktop you can reorder your bookmarks and now Mozilla introduced exactly this feature in Firefox 18 for Apple iOS.

![Bookmark-Editing-5-600x1299](https://user-images.githubusercontent.com/1100614/62009023-5acbf600-b15a-11e9-80d8-570da2755b8c.png)

So it would be great for cross platform parity to bring this feature to Android, too. Otherwise Android is the only platform without this feature in Firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12786)

**Comment by lisanez** [comment]
So, as of 5/20/20, how do I change the order of my Android bookmarks? Please tell me someone made this possible...?

**Comment by eliserichards** [comment]
Option to sort folders as well (see #18924)

**Comment by ElizabethTree** [comment]
Without the ability to sort bookmarks I'm regulated down to creating one folder "A B C s" and the a folder per letter below.  While this is a good way to group folders I am at letter M and tired of creating the letter folders since some of them are empty and this just placeholders.  

Please add the feature to sort bookmarks and folders alphabetically!!!  It would also be nice to just move folders if you want into non-alphabetically order, but able to move them to be higher than some previously created folders without having to move all folders that you want lower to a tmp folder and then back to the main folder so that they are lower.

I don't know how much work it is to do this, but I really want these features!  Thanks!!!

**Comment by SeburoSUMO** [comment]
User feedback:  https://support.mozilla.org/en-US/questions/1350286

**Comment by drbuggolo** [comment]
FWIW, I want this feature too. Also top sites. W/r/t the competition, it also exists in Safari for iOS.

**Comment by keiviv** [comment]
This simple essential feature is still missing – after all this time. Firefox for Android is the only browser on the planent where you can't rearrange your bookmarks – while you can do it even on a **text-based Lynx**.

I'm not sure devs are using their own browser – as otherwise at least **one** of them would say *"wait, I can't move this mark up – wtf, lol"*.

It's painful to see Firefox falling from "Take Back The Web" to "Jump Through Hoops For Addons & Sort Your Stupid Bookmarks at Desktop".

Don't add it – you'll shock reddit & hackernews to their cores. We here more expect Recollections and licking the logo 666 times to enable the address bar – anything sensible would be too puzzling to bare.

**Comment by WebworkrNet** [comment]
An optional alphanumeric sorting (#18924) should not exclude a prioritized classification based on other criteria. This means: Sort all bookmarks and folders alphanumerically, but allow certain bookmarks to be given priority over the respective directory level.
An example could be the manual sorting.

**Comment by sergioad** [comment]
Please give this issue more priority, thes is essential

**Comment by drbuggolo** [comment]
After following this issue for some time, I am unsubscribing. I have discovered that it can easily be fixed by switching to Opera. Which offers the added benefit of allowing me to save a PDF of a web page... a feature that I gather used to exist in FF but was removed.

**Comment by kbrosnan** [comment]
Duplicate bz-1811652
