### ISSUE TITLE
Sync collections (restore in Fenix)

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#4424]
**Description**
Save collections to Firefox Account to access sites and collections order when i sign in again with  a new device .
**benefits**
When signing in with Firefox account 
should got a choice to restore Collections backup from the server,
add new sync option in Firefox preview  to sync collections with bookmarks and history.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12838)

**Comment by ViktorZhurbin** [comment]
Reinstalled the app and my collections were gone. This was very frustrating

**Comment by yoasif** [comment]
Hit another user in the wild: https://www.reddit.com/r/firefox/comments/ehkbj0/i_deleted_firefox_preview_nightly_and_installed/

**Comment by SS1113** [comment]
Please bring this feature as it takes a lot of effort curating all those collections and not having a way to restore them if I reinstall the browser or on a new phone is really frustrating!

**Comment by madb1lly** [comment]
Hi @SS1113,

I completely agree, now that tabs are synched I'll probably keep using those rather than use collections.

Cheers 🙂

**Comment by liuche** [comment]
There's currently some work going on in terms of redefining how/what collections are, will that affect this work? Or need to be taken into account? Collections will probably still be urls-based, but may change somewhat.

**Comment by liuche** [comment]
Okay, got some answers here, and summarizing them for @vesta0 

There are 4 main options for the underlying Sync Collections foundational work:
1) write a new sync engine specifically for Collections [not being considered]
2) write a generic sync engine that could be used in the future, and make an instance for Collections (will a good deal of AS time to design, architect)
3) Piggyback off of Tabs Sync
4) Piggyback off of Bookmarks Sync

Only 3 and 4 are currently being considered for a "short-term" solution, especially since Desktop will get them "for free" because they're piggybacked off of existing engines. However, there are some tradeoffs, that have some implications for what is easy/possible with Collections in the future, and thereby result in some wasted eng work.

If we follow option 3) and reuse tab sync (with +/-):
+ easy to have history (since tabs sync this)
- is more work, bc requires implementing interleaving when different devices update Collections (since tabs are per-device) (OR could have "collections per device", similar to Tab Sync UI where each set of tabs is associated with a device - but this doesn't really match with what collections is)

Option 4) reuse bookmarks sync (with +/-):
+ matches with current idea of collections (basically, a synced bookmarks folder)
+ don't need to additionally have reconciling 
- would need to additionally implement collection item state like history, scroll position, other session state

The question is, what is the better fit for collections? Some things to consider:
- If we keep the design of Collections as-is, there is probably still a good deal of work to be done
- If we change what Collections are (e.g. automatic collections), we may need to either throw away some eng work, or layer on additional eng work
- it would be easier to choose between 3) & 4) if we knew what format Collections was going to be

**Comment by madb1lly** [comment]
Hi all,
Where is this ongoing discussion about Collections? Is it here #11967?

Of the above options from @liuche I prefer option 3. To me, Collections offered the promise of saved sessions which I could swap between, like tab groups on desktop, and unfortunately that promise hasn't materialised yet. I don't think that the disadvantage of interleaving needs to be considered, as this is optional - collections could remain per device (like they are at the moment, because they're not synced). If you _could_ make Collections be global across all synced devices then that would be great! But could also have unwanted side effects, e.g. the user might need to store different collections for mobile and desktop (would still be less work than currently though).

Option 4 would seem like little more than bookmarks with a privileged position on the homescreen, so I don't see the point; I'd rather have all my bookmarks folders on the Fenix homescreen if that's the way collections are going.

Cheers 🙂

**Comment by pedroldk** [comment]
Is this still being taken into consideration? I believe that at this point users have a feature in a stable version and they expect it to synchronize and not loose their collections...

**Comment by xcalc** [comment]
++
Sync collections and make them available as "Important Pages" (as selectable collections to be shown).

**Comment by pedroldk** [comment]
I believe that it is better to have something than nothing at all, loosing collections when reinstalling/switching devices is frustrating and not expected by any user. So I would say go for the simple solution even if it is not perfect and improve it afterwards.

**Comment by lumbo7332** [comment]
Bump

**Comment by FabHof** [comment]
Anything new on this? Having a new device and not getting the collections is frustrating...

**Comment by Djfe** [comment]
I cannot believe this isn't a thing, yet. most users will buy new devices soon and the only ones who can keep collections need a rooted device like me?
Please increase the priority of this, where is the server side issue?

**Comment by mmbng** [comment]
I agree after creating several collections from news sites / receips / real estate ... I now have to recreate those collections on my new phone by sharing the collections via email then clicking each link and save.   Even if we could export to csv and import that would be better than manually re-creating the collectiosn.  We need the mobile version to not just sync tabs but the collections as well.

**Comment by madb1lly** [comment]
> I cannot believe this isn't a thing, yet. most users will buy new devices soon and the only ones who can keep collections need a rooted device like me? Please increase the priority of this, where is the server side issue?

Good point @Djfe, there probably do need to be other issues to link to this one, maybe in bugzilla or android-components?

**Comment by Djfe** [comment]
I created one on Bugzilla to make the developers of Firefox Sync aware of this
https://bugzilla.mozilla.org/show_bug.cgi?id=1747614

**Comment by DistortedBit** [comment]
I just lost my phone and I had no idea collections were not synced. 2 years worth of collections. This feature would be really helpful.

**Comment by blinkertoon** [comment]
Can't believe this still hasn't been resolved somehow 😕

**Comment by sheikh-azharuddin** [comment]
Please add the option to sync collections or atleast give the option to take local backup and restore collection

**Comment by Matth7878** [comment]
Can't understand why collections couldn't be converted as bookmarks in a special folder. Then it would sync normally and it would also solve problems like not being able to rename or changing their order. 😕

**Comment by Djfe** [comment]
because collections aren't bookmarks but saved tabs

if you open a collection entry, you get the complete tab history as well (previously opened pages)

you can go backwards and forwards

**Comment by sheikh-azharuddin** [comment]
But we don't want tab history..what is the use if they are not synced! Even with the share button, it actually shares the links.
So the url could be saved in the bookmark rather than state/tab history

**Comment by Binly42** [comment]
> But we don't want tab history..what is the use if they are not synced! Even with the share button, it actually shares the links. So the url could be saved in the bookmark rather than state/tab history

As a perspective, with supporting saving history, the `collection` could be used to **fold**/**classify**/**recycle** the browsering tabs.

After all, *screen space* on cell phones is too precious……

In particular, for someone like me, I often keep over 100/200/…… tabs (well, I really should improve my habit and manage way ……

**Comment by Djfe** [comment]
I think that was the idea at first ^^
tab groups, but they called it collections and they don't work well if you already have hundreds of tabs open. and they aren't removed from the collection on opening

**Comment by sheikh-azharuddin** [comment]
Microsoft edge has proper collection feature which actually syncs!

Here even after 3 years Mozilla could not find a solution to sync collection!
Wondering whose idea was to implement half baked collection in firefox android with no vision of future!

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810652

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
