### ISSUE TITLE
[Bug]Find in page leaves a blue mark in the web pages search box

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4590]
## Steps to reproduce
1. Navigate to ebay.com
2. Tap on the 3dot button and select "Find in page"
3. Enter letter 'a' and tap next "v" a couple times
4. While moving to the next result check the search text box

### Expected behavior
Should move from one result to another properly.

### Actual behavior
While moving through the results, a blue highlight remains visible in the websites search box.

### Device information
* Android device: 
• Google Pixel 3a (Android 9)
• Samsung Galaxy Tab A (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Fenix Nightly Build #12190111 from 7/8

### Notes
**Reproducible on Wikipedia as well.**

►Video Google Pixel 3a
![20190807_160804](https://user-images.githubusercontent.com/51314259/62626211-89528980-b92f-11e9-94bf-5553bd5f3284.gif)

**Comment by Mugurell** [comment]
This functionality uses the [Find In Page](https://github.com/mozilla-mobile/android-components/tree/master/components/feature/findinpage) component and all of the FindInPageInteractor's calls to find, like [onFindAll](https://github.com/mozilla-mobile/android-components/blob/0c63c199ab7096b736ffc132e3755969d930cc15/components/feature/findinpage/src/main/java/mozilla/components/feature/findinpage/internal/FindInPageInteractor.kt#L70) are delegated to `engineSession`.
This other [Engine-Gecko](https://github.com/mozilla-mobile/android-components/tree/master/components/browser/engine-gecko) component uses it's own `finder` [like in the case of the `findAll` call](https://github.com/mozilla-mobile/android-components/blob/0c63c199ab7096b736ffc132e3755969d930cc15/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L217) to actually search in the webpage and highlight the results, `finder` which is an instance of [GeckoView's SessionFinder](https://github.com/mozilla/gecko-dev/blob/master/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/SessionFinder.java).
As such I think this issue is to be resolved on GV's side.

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639085
