### ISSUE TITLE
[Bug] Pairing Feature's QR Code Scanner does not work

### ISSUE THREAD

**Issue by dianehuang11** [mozilla-mobile/fenix#4594]
## Steps to reproduce

1. Open Firefox Preview
2. Open settings menu
3. Select Turn on Sync 
4. Select "Ready to scan"

### Expected behavior
QR scanner opens, scans, and successfully pairs. 

### Actual behavior
Black screen with no scanner.

### Device information

* Android device: Samsung GT-19500
* Fenix version: Nightly 190807 06:02 _and_ 1.1.0 (public build) 

![Screenshot_2019-08-07-11-57-56](https://user-images.githubusercontent.com/28498717/62638805-39160000-b90c-11e9-8528-ed5cd4db9e14.png)
![Screenshot_2019-08-07-11-58-01](https://user-images.githubusercontent.com/28498717/62638810-3adfc380-b90c-11e9-825c-77d576843970.png)

**Comment by ekager** [comment]
@dianehuang11 did you already give camera permissions to Fenix? Did you dismiss the permissions dialog?

**Comment by dianehuang11** [comment]
The permissions dialog didn't appear for me when I opened for the first
time.

**Comment by ekager** [comment]
Could someone from QA possibly test with a variety of devices here?

**Comment by sv-ohorvath** [comment]
Tried with a few devices but could only reproduce this with a Xiaomi Mi 4i (Android 5.0.2)
[camera logcat.txt](https://github.com/mozilla-mobile/fenix/files/3492233/camera.logcat.txt)

Other devices verified:
Samsung Galaxy Tab A 6 (Android 5.1.1)
Xiaomi Mi 8 Lite (Android 8.1)
Pixel 3 (Android 9)
Huawei P9 Lite (Android 6.0)

**Comment by AndiAJ** [comment]
Hi @ekager & @sv-ohorvath , I've just checked the above mentioned issue using the latest **Nightly Build #12240720 from 12/8** on the following devices and **couldn't reproduce the issue**:
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy Note5 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Samsung Galaxy J7 (2016) (Android 6.0.1)
• Samsung Galaxy S5 (Android 6.0.1)
• Samsung Tab Active (Android 5.1.1)

On the other hand @dianehuang11 has a **Samsung Galaxy S4** which has **Android 4.2.2 (Jelly Bean)** as stock firmware and the last firmware update option was **Android 5.0.1 Lollipop**
Considering the above, there **can't be any permissions issue** because the "App permissions" feature got introduced first in **Android 6.0** and later versions.
When installing an app to a device that has Android Lollipop **all permissions are granted when installing that particular app**.

► Pic from Samsung Tab Active (Android 5.1.1)
![Screenshot_2019-08-12-16-08-13](https://user-images.githubusercontent.com/51314259/62868435-58eb6080-bd1e-11e9-9f99-d1d86b9a99b7.png)

**Comment by softvision-miralobontiu** [comment]
Hi!

I was able to reproduce this issue on Xiaomi Mi 4i (Android 5.0.2) on the latest Nightly build from 12/09.
The [logcat](https://github.com/mozilla-mobile/fenix/files/3492233/camera.logcat.txt) Oana attached is the same I got today.

Thank you!

**Comment by AndiAJ** [comment]
Not reproducible on **Nightly Build #13430607 from 12/9** using the following devices:
• LG Nexus 4 (Android 5.1.1)
• Samsung Tab Active (Android 5.1.1)
• Asus Nexus 7 (Android 5.1.1)
