### ISSUE TITLE
Modify the Navigation Bar color to match Fenix color while being in Private Mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4682]
### Why/User Benefit/User Problem
Modifying the navigation Bar in private mode to be transparent, it will create a feeling of a full screen app while browsing. 
### What/Requirements
Modify the color for the navigation Bar.
### Acceptance Criteria (how do I know when I’m done?)
The navigation bar color matches the Fenix color in private mode.
### Notes
This change will make a difference for the newest devices with a small Notch.
Also, note that in normal browsing mode, it looks very good as everything is in the same color.
I will add 2 photos(not screenshots) to see the difference. 
Device: Samsung Galaxy S10+
![62202318-c0ee8e00-b391-11e9-8339-968a2f5e381e](https://user-images.githubusercontent.com/42831109/62863970-1a9c7400-bd13-11e9-8f7e-c05d66431163.jpg)
![62202443-fabf9480-b391-11e9-899f-9cfa611abe97](https://user-images.githubusercontent.com/42831109/62863976-1cfece00-bd13-11e9-8d92-8075218c2123.jpg)

**Comment by vrudesai** [comment]
Feature does not exist in Fennec as nav bar is tucked when scrolling

**Comment by lime124** [comment]
@AmyYLee for comment. thanks!

**Comment by AmyYLee** [comment]
> Feature does not exist in Fennec as nav bar is tucked when scrolling

@vrudesai Can you please clarify what the issue is here? Thanks

**Comment by AmyYLee** [comment]
@abodea Hi, I think you are referring to the gradient in the search bar should be the same solid dark purple in the status bar?

The gradient has been intentionally added for several reasons:
- It helps to distinguish between private browsing mode and non-private modes (especially if the user has dark theme since the dark purple and dark grey are similar).
- When the options menu is opened (3-dot menu), it helps separate the foreground and background between the menu and the URL bar. If we set the search bar to the same purple, the options menu will blend into the search bar. 
- The gradient ensures visual consistency between the homescreen for Private browsing mode and when the user is on a website.

Hope this explanation helps.

**Comment by RyanMarzec** [comment]
Is anyone working on this or may I?

**Comment by lime124** [comment]
hi @RyanMarzec - you  can pick up the issue. Amy is part of our mobile design team and is  offering design support/guidance.

**Comment by lime124** [comment]
sorry @RyanMarzec - amy just mentioned to me there is a similar issue #4107 that has been picked up. I think this may be a dup :-/

**Comment by RyanMarzec** [comment]
@lime124 okay thank you for letting me know, I'll keep looking around for a good starting point.

**Comment by abodea** [comment]
@lime124 Closing this issue as the #4107 was verified as fixed.
In the beginning, this was a follow up for the navigation bar but it was solved in #4107.
