### ISSUE TITLE
[Bug] Typing in the search box of f64.ro is hard

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#4697]
## Steps to reproduce
open f64.ro and type in the search field
https://vimeo.com/343310523
### Expected behavior
easy to type
### Actual behavior
had to type the same letter several times
### Device information

* Android device: 
![android_version](https://user-images.githubusercontent.com/922368/62898615-95d74780-bd5e-11e9-94b0-f16c1fd03b96.png)

* Fenix version: latest nightly

**Comment by boek** [comment]
@cpeterso is this a known issue?

**Comment by cpeterso** [comment]
@andreicristianpetcu - When you say you had to "type the same letter several times", does that mean the first few keyboard taps didn't output any letters to the web page? Which Android keyboard are you using? Does Lineage use a different keyboard than Google's Android (Google's Gboard keyboard)?

**Comment by cpeterso** [comment]
> @andreicristianpetcu - When you say you had to "type the same letter several times", does that mean the first few keyboard taps didn't output any letters to the web page? Which Android keyboard are you using? Does Lineage use a different keyboard than Google's Android (Google's Gboard keyboard)?

Never mind. I can reproduce this typing problem in Fenix on my Moto G5. 😄 This seems to be a Fenix-specific problem because keyboard input seems to work fine in Fennec, Focus, and R-B (and Chrome and Edge). I'll file a GeckoView bug for that.

I also see that the site's "Este timpul" newsletter popup is displayed in the wrong position (covering the search box) in Fenix and R-B instead of below the search box (like Fennec and Chrome). I suspect that is related to the page offset caused by Fenix and R-B's bottom toolbars. I'll file a GeckoView bug for that.

**Comment by andreicristianpetcu** [comment]
@cpeterso I typed l several times in the video with no output. I'm using Hacker Keyboard from F-Droid https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/
LineageOS uses the keyboard from AOSP (the last open source google keyboard). I think the latest versions of google keyboard is proprietary and is shipped in Google Play now.

**Comment by andreicristianpetcu** [comment]
Damn. The AOSP keyboard works fine with Fenix on the site.

**Comment by makotokato** [comment]
@andreicristianpetcu could you still reproduce this when using the latest version of Firefox Preview Nightly?
I cannot reproduce this using my Pixel 2 and Galaxy S7 with GBoard/Samsung Keyboard/Hacker Keyboard.

**Comment by andreicristianpetcu** [comment]
Seems fixed. Closing.

**Comment by cpeterso** [comment]
@andreicristianpetcu - Thanks for reporting this bug and confirming it works now!
