### ISSUE TITLE
[Bug] [site permissions] "permissions" is not vertically centered

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#4718]
## Steps to reproduce
Go to site permissions

### Expected behavior
The interface is consistent

### Actual behavior
There's too much between "permissions and "exceptions"
![Screenshot_20190814-012319_Firefox Preview](https://user-images.githubusercontent.com/32398857/62994535-ce485580-be32-11e9-94b4-38de059978ad.jpg)

### Device information

* Android device: Galaxy A5 2017
* Fenix version: 190813

**Comment by Pheonix73** [comment]
@pocmo is it possible to get the actual padding for this?

**Comment by kbrosnan** [comment]
@pocmo is not the best person to answer that.

@lime124 who owns this dialog? Should we line the header up with the items or something else?

**Comment by lime124** [comment]
@AmyYLee can you take a look?

**Comment by AmyYLee** [comment]
Hi I don't see the header at all in the latest Nightly. Are you still experiencing this? @Lululalu @kbrosnan  
![Screenshot_20190821-112026](https://user-images.githubusercontent.com/5992746/63445131-db9eaa80-c405-11e9-9553-c432c9e2658a.png)

**Comment by AmyYLee** [comment]
Hi, 

Can you please remove the header "Permissions". This is redundant since we already have a header that says "Site permissions" 

Can you please relocate "Exceptions" to the bottom of the list and include a hairline above (see reference mock). This will align with how we handle "Exceptions" in Enhance Track Protection. Let me know if you have any questions.

![Screen Shot 2019-08-21 at 2 02 41 PM](https://user-images.githubusercontent.com/5992746/63456554-31cb1800-c41d-11e9-8e7d-699c0c9a591c.png)
