### ISSUE TITLE
Consider removing voice icon from search widget if not using Google as default engine

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4757]
@vesta0 mentioned we should consider disabling the voice icon if a user doesn't have Google as their default engine because a user likely wouldn't want their speech data going to Google.

**Comment by vrudesai** [comment]
Not a feature in Fennec

**Comment by yoasif** [comment]
This should definitely happen, but it would be nice if common voice was available instead (as to be a drop in replacement). 

It'd be nice to have it be configurable if common voice was available, for people who are comfortable searching with Google, but not interested in sharing voice data with Google.

**Comment by yoasif** [comment]
After seeing the voice UI in the latest Fenix, I think that this is less of an issue as long as there is an accessibility setting to disable the feature. 

I went ahead and created a feature request here for this: https://github.com/mozilla-mobile/fenix/issues/10828

**Comment by yoasif** [comment]
...and it looks like the toggle is available. I don't personally think this is required. Common Voice would still be great though!

**Comment by madb1lly** [comment]
Hi all,

Google isn't needed for voice search, as far as I can tell, please see #15348.

Cheers 🙂

**Comment by madb1lly** [comment]
Hi @pocmo,

I don't agree this should have been implemented as it wasn't even a valid bug. See #15348. the Fenix team are making the wrong assumption that voice search _requires_ Google search, but it doesn't, it can be used with any search engine because it uses whatever the default Android voice-input is. By preventing people using voice search when Google is not the default search engine Firefox is unreasonably blocking them from a usability feature.

Cheers 🙂
