### ISSUE TITLE
Come up with sustainable triage model & also triage

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4775]
We currently have 300 untriaged issues. While this number is staying roughly consistent and not growing, we should make an effort to burn it down initially so we have a smaller number of unknown issues.

**Comment by liuche** [comment]
Here’s an update on our triage process.

Currently, our repo gets tons of issues (which is a combination of bugs, feature requests, etc). However, this load is getting pretty unmanageable, and I know everyone’s is balancing a ton of work.

In order to mitigate the risk of missing really critical issues that get filed, we should still triage, but should prioritize labeling S1 issues. Please spend some time triaging so we can make sure to see all the critical issues.

As part of this, I’ve also:
- Made a label S1-not, so we won’t re-triage issues
- Updated the triage queries on the wiki (Phase 1 is now Severity Triage)
- PR to README to explain to contributors our priorities in triage

Please still feel free to triage normally (with P1, P2, etc labels) if you want to/have time. Also, raise issues w/ needs:group-triage.

During triage, we’ll still continue to look at needs:group-triage issues, but also will check S1 issues.
