### ISSUE TITLE
[Bug] Cleaning Open Tabs will brake Fenix

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#4788]
## Steps to reproduce

1. Open **2** new tabs (EDIT: **1** is enough)
2. Go to settings
3. Go to "Delete browsing data"
4. Delete **"Open Tabs" only!** (EDIT: **More than 1** selection will lead to the same result)

### Expected behavior

Closing the settings by going 2 times back (back button of device and Fenix) shows the homescreen of Fenix.

### Actual behavior

It shows a white screen with a black bar at the bottom.

![Screenshot_20190817-111337__01](https://user-images.githubusercontent.com/52482050/63209383-5901ac80-c0e0-11e9-9f37-6bd810d8e937.jpg)

### Device information

* Android device: Android 9 on OnePlus 3T (A3003) Oxygen OS 9.0.5
* Fenix version: Nightly 190817 06:05 (Build #12290612)
    package: 8.0.0, 78354bc12
    lizard: 69.0-20190812090043

**Comment by mikeGolf08** [comment]
Latest update has not solved the bug.

### Device information

* Android device: Android 9 on OnePlus 3T (A3003) Oxygen OS 9.0.5
* Fenix version: Nightly 190819 18:08 (Build #12311823)
📦: 9.0.0, 8199523c3
🦎: 69.0-20190815091718

**Comment by ekager** [comment]
@mikeGolf08 are you still seeing this? I can't reproduce

**Comment by mikeGolf08** [comment]
Since the current state is that the settings close in any case and no going back by Android back keys is possible I have closed the ticket.

**Comment by AndiAJ** [comment]
Hi, due to the fact that after deleting any browsing data you are redirected to the home screen I'll mark this ticket as **verified** on Nightly Build #12621819 from 19/9
I've tested using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)
