### ISSUE TITLE
[Bug] Glitched scrolling

### ISSUE THREAD

**Issue by hXtreme** [mozilla-mobile/fenix#4834]
## Steps to reproduce
1. Open a website that doesn't zoom. Tested [here](https://unluckyslime.wordpress.com/2019/02/14/hero-of-black-chapter-4/) in reader mode, and also somewhere else while not in reader mode.
2. Perform the zoom in gesture.

### Expected behavior
Do nothing

### Actual behavior
About once out of every four tries the page scrolls by a large amount. (The large amount could be because of #3744)

[Video](https://streamable.com/sejk8)

### Device information

* Android device: Pie (MIUI 10) on Pocofone
* Fenix version: 1.2.0

**Comment by theres-waldo** [comment]
The possibility for a two-finger gesture to perform scrolling is an intentional feature (two-finger scrolling). It happens if the two fingers move in the same direction. During a pinch gesture, that typically does not happen, but it's possible the two fingers move in the same direction by a small amout, resulting in a small scroll.

Momentum scrolling at the end of a two-finger scroll gesture is also intentional.

However, getting such a large momentum scroll after a small two-finger scroll is a bug. It should be fixed by [bug 1458653](https://bugzilla.mozilla.org/show_bug.cgi?id=1458653), which is being worked on.

**Comment by hXtreme** [comment]
Seems like the underlying bug has been resolved already, so I'll go ahead and close it.
