### ISSUE TITLE
UI nit picks:- Library screen

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#484]
Nit 1:- in the Library screen the title text is left justified but in the History screen it is offset to the right by the back arrow ("<- History"). Could the text be in the same position horizontally on all these screens? Arguably the Library screen needs a back arrow to go back to Settings which would be a good way to fix?

Nit 2:- on the Library screen I dislike the horizontal dividing lines, I don't see what they add & they don't seem very "Android". They are not present on other screens & menus (e.g. History, Settings).

Thanks!

**Comment by brampitoyo** [comment]
@Cheap-Skate 

> Nit 1:- in the Library screen the title text is left justified but in the History screen it is offset to the right by the back arrow ("<- History"). Could the text be in the same position horizontally on all these screens?

The Library title text is left justified, because it’s the first page that you access from within the main menu ⋮. You can’t access our Library within Settings; if you can, then you’re right that there should be a back arrow.

Whereas History, Bookmarks, Logins, etc. all have back arrow ← because the page is one level inside the structure.

If you look at other Android apps (e.g. Messages, Chrome), you’ll see that the very first screen doesn’t have any back arrow, but every screen afterwards does. So we’re following a system convention here.

**Action:** I don’t recommend changing anything.

> Nit 2:- on the Library screen I dislike the horizontal dividing lines […] They are not present on other screens & menus (e.g. History, Settings).

You are totally right on this one. If you’re running Android Pie, have a look at Android System Settings, and you’ll see that each menu item isn’t divided with a horizontal ruler.

**Action:** remove horizontal dividing lines on our Library screen.

Good catch! Thanks.
