### ISSUE TITLE
Temporarily disable screenshots UI tests til androidx upgrade

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#4906]
Android Gradle Plugin 3.5.0 requires AndroidX dependencies for testing , but screengrab doesn't work yet with AndroidX. @colintheshots has contributed back a patch (see: https://github.com/fastlane/fastlane/pull/15217).  Until Google maintainers pick it up and create a build, we'll need to temporarily disable the screenshots tests.

cc: @isabelrios @npark-mozilla 

see also:
https://github.com/mozilla-mobile/fenix/pull/4903

**Comment by rpappalax** [comment]
@isabelrios I assume we still need to keep these turned off until they're all working again.  Did I understand that correctly?

**Comment by isabelrios** [comment]
Well, no, I would say the opposite, these tests could be re-enabled. In fact, I recently created PR #6617 where screenshots and all UI tests are working. The screengrab PR that Colin created got merged and I can get screenshots working, as you can see in that PR.
In my opinion, we can enable them so that we have the environment ready and we keep them updated as the app evolves in case we are requested to get them and share with localizers. 
[See example of latest screenshots](https://console.cloud.google.com/storage/browser/l10n-fenix/2019-11-20/android/phoneScreenshots/?project=l10n-screenshots).

There is still a [fastalane issue](https://github.com/fastlane/fastlane/issues/15690) with the report automatically generated, but we can still get and share the screenshots per language until that is fixed.

**Comment by VitaminPSG** [comment]
Screengrab is migrated to AndroidX. But I still have issue with `report` and `output_directory`. - 
- `report` is empty.
- `output_directory` is  common for all locales. It means that screenshots for next locale overwrite previous locale.

**Comment by isabelrios** [comment]
Above comment is right, that's the issue reported on Fastlane, but we can still get the screenshots per language, getting each one at a time, at least we can have them if necessary while that issue is fixed.

**Comment by rpappalax** [comment]
This issue has been resolved, screengrab tests re-enabled
