### ISSUE TITLE
Fennec migration: Keep Home Screen Website Shortcuts working

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4977]
Related to #4976 but for shortcuts added via "Add page to home screen".

> In Fennec the user can add pages to the home screen. After updating to Fenix those shortcuts can disappear or become non-functional. Providing the same entry points in Fenix is required to keep shortcuts active.

**Comment by st3fan** [comment]
Telemetry https://bugzilla.mozilla.org/show_bug.cgi?id=1583525

**Comment by Mugurell** [comment]
The most important part here is getting the shortcuts to open Fenix although they are are created with an explicit Intent to **`org.mozilla.firefox`**`/org.mozilla.gecko.BrowserApp`

Declaring `org.mozilla.gecko.BrowserApp` in manifest as a new alias for `.HomeActivity` seems to allow for this,
but only if in Fenix the launcher activity alias is `org.mozilla.firefox.App`(the current launcher activity alias on Fennec) and not the current [`org.mozilla.gecko.App`](https://github.com/mozilla-mobile/fenix/blob/80693f4f0bd503657179af9f927f9cf616d21b43/app/src/main/AndroidManifest.xml#L38)

Seeing that you declared this alias @pocmo, would you say it's ok to use `org.mozilla.firefox.App` as the launcher?

Otherwise we could have our own BrowserApp but this seem uglier than it needs to.

**Comment by pocmo** [comment]
@Mugurell I don't think I fully understand the change you want to make. Is this easy to draft and show as a patch/diff?

The existing alias is the same as in Fennec and was used to keep launcher icons on the home screen when migrating to Fenix. If this needs to be package name specific (think of beta and nightly) then we would need to use `.App` here like Fennec...?

**Comment by pocmo** [comment]
Okay, I was very confused why I ended up using `org.mozilla.gecko.App` and why it worked when I tested it locally.

Looking inside various APKs made me realize that:
- For local builds you end up with `org.mozilla.gecko.App`. I am not sure why. But that explains why it worked in my local tests.
- For a release APK from archive.mozilla.org I see `.App` being used.

This also explains why #4976 needed to be reopened since it didn't work with the actual builds. So, yeah, I"m pretty sure we should use `.App` in the manifest (so that it works with Beta/Nightly too). This means this no longer works with a local Fennec build. But instead you can use a re-signed actual Firefox build if needed.

**Comment by Mugurell** [comment]
From what I've seen using just `.App` is not enough.
This only keeps the launcher icons on the homescreen but not the pwas or pinned shortcuts.
For keeping all of them on homescreen (tested with Pixel's Launcher3) we need to use `org.mozilla.firefox.Appnc`

**Comment by pocmo** [comment]
I did some further testing and it didn't work for me either with `.App`. Which is very confusing since that is in the actual APK I get from Fennec. But since Fennec does a lot of manifest shenanigans it might produce something else than Gradle if you put `.App` in the manifest.

**Comment by Mugurell** [comment]
I can also look into this.
Thinking into leveraging manifestPlaceholders.

**Comment by pocmo** [comment]
Yep, that's what I did: https://github.com/mozilla-mobile/fenix/pull/7239

**Comment by ebalazs-sv** [comment]
@pocmo I had tested this on today's Release, Beta, Nightly migration build 01/09 with the devices:

- Google Pixel (Android Q) - ARM64;
- Samsung Galaxy S8 (Android 9) - ARM64;
- Nexus 6P (Android 8.1.0) - ARM;
- Xiaomi Mi Pad 2 (Android 5.1) - x86.

The Website Shortcuts are displayed on homescreen after migration, but when tapped, the "App isn't installed" message is displayed.

**Comment by ebalazs-sv** [comment]
Here is a [logcat](https://github.com/mozilla-mobile/fenix/files/4040515/shortcut.txt) for this issue.

**Comment by Mugurell** [comment]
> Here is a [logcat](https://github.com/mozilla-mobile/fenix/files/4040515/shortcut.txt) for this issue.

In the above logcat I see
> I/ActivityManager: START u0 {act=org.mozilla.gecko.WEBAPP typ=null flg=0x10000000 cmp=ComponentInfo{org.mozilla.firefox/org.mozilla.gecko.LauncherActivity}}
from which I understand the homescreen shortcut is for a PWA not for a website shortcut.
Migrating PWA shortcuts is indeed not supported atm, them being added in https://github.com/mozilla-mobile/fenix/issues/4979

For adding a website shortcut can you please do the following in Fennec?:
- navigate to a website
- press the 3 dot menu button
- tap Page -> Add Page shortcut

After this you can install Fenix and check that the homescreen shortcuts you've added with the above steps are preserved and that they are opened in Fenix as intended.

I think there is a small quirk because of the first time run experience in Fenix, that would affect the Fennec migrated search widget, pwas and shortcuts but I think this will be addressed separately.
If Fenix was first opened and user pressed "Start browsing" it should all work perfectly.

**Comment by ebalazs-sv** [comment]
Indeed, in the previous comment PWA's were added. Sorry for the confusion.
I tested this with page shortcuts and they are opened in Fenix as intended.
I will move this to Done. Thanks!
