### ISSUE TITLE
Fennec migration: Keep user logged in

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4980]
We have made this possible when Fenix and Fennec are installed side-by-side. Let's make sure that also works when Fenix is replacing Fennec.

**Comment by grigoryk** [comment]
Support for most-common use cases landed in https://github.com/mozilla-mobile/android-components/pull/4873

**Comment by ebalazs-sv** [comment]
Hi!
I tested this on Nightly builds 191102 GV 71 from 
https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration 
with Samsung Galaxy S8 (Android 9), Nexus 6P (Android 8.1.0), Google Pixel 3 (Android 10) and the user is not kept logged in after Fennec is replaced by Fenix.
Are there other builds available for testing this fix? Thanks!

**Comment by ebalazs-sv** [comment]
Hi!
I tested this on Fenix Nightly 191109 GV 71 with Google Pixel 2 (Android 9), Google Pixel 3 (Android Q) and the user is kept logged in. 
I filed the following issues, that might be related to this fix:
https://github.com/mozilla-mobile/android-components/issues/5041
https://github.com/mozilla-mobile/android-components/issues/5044
I could not verify this on other devices because of the start up crash. Thanks!

**Comment by ebalazs-sv** [comment]
Hello!
I verified this as fixed on Fenix Nightly 191127 GV 71, with the following ARM, ARM64 and x86 devices:
- Pixel 2 (Android 9);
- Samsung Galaxy S8 (Android 9);
- Nexus 6P (Android 8.1.0);
- Huawei Honor 8 (Android 7.0);
- Xiaomi Mi Pad 2 (Android 5.1),

and I will mark this as Done.

_Note:_ The account is displayed in the Settings page after the app crashes 2-5 times, see issue mozilla-mobile/android-components#5041.
