### ISSUE TITLE
Enable users to both clear text and cancel the action in search bar

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#500]
### Why/User Benefit/User Problem
Via milestone 1 user study recommendation

### What / Requirements
- Enable users to both clear text and cancel the action in search bar
- Similar to other browsers

**Comment by jonalmeida** [comment]
Moving @brampitoyo 's feedback on this from https://github.com/mozilla-mobile/reference-browser/issues/503 to here:

> On Fennec, the ‘x’ icon doesn’t clear text, but instead closes the keyboard + address bar. While the URL is highlighted, you can tap-and-hold to paste a link over it (and this link will rewrite the whole URL.
> 
> On Chrome and other Android apps, the ‘x’ icon clears text, and while the URL is highlighted, tapping-and-holding will only select one work in that URL – so if you try to paste something, it will not rewrite.
> 
> I agree that we should follow Chrome and Safari here. Use the ‘x’ to clear text (actually, it should be an ‘x’ icon inside a circle).

Leaving open for @vesta0 to close if this is fine.

**Comment by vesta0** [comment]
Let's change the behaviour to align with what @brampitoyo  proposed in his mockup.

@jonalmeida is there an A-C issue for this?

**Comment by ekager** [comment]
Yes there's an issue for the first comment for the behavior. 
https://github.com/mozilla-mobile/android-components/issues/2147

I'll open another for the icon update.

**Comment by mheubusch** [comment]
@topotropic @lime124 just confirming that our recommendation/request of engineering is defined and is what we still expect to see.

**Comment by ekager** [comment]
For context/history, the button initially canceled the search action but as per Bram's comment https://github.com/mozilla-mobile/fenix/issues/500#issuecomment-467137351 we changed the button behavior to clearing the text and dissappearing if there is no text to clear. The work was completed in AC and this ticket was never closed because the title was "both clear text and cancel the action". 

So the UX question is: do we still want to somehow have *both* actions (clear and cancel) in this button or in the search bar and if so, how? If not and the current behavior of clearing is desired behavior, can we close this ticket?

**Comment by topotropic** [comment]
The current implementation looks good to me – clearing the bar is fine.

**Comment by ekager** [comment]
Thanks @topotropic ! Closing this issue
