### ISSUE TITLE
Sync Logins

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5074]
## User Story
- As a user, I want to choose whether I want my browser to access my existing synced logins and sync new Fenix logins with my Firefox account.

### Dependencies
- [ ] [Keep Logins storage unlocked](https://github.com/mozilla-mobile/android-components/issues/4741)

### Acceptance Criteria
- [ ] Integrate Login Sync component
- [ ] I can choose to enable Sync logins in Fenix from the Sync page
- [ ] This is behind a Nightly feature flag

This is not including:

- When enabled, I can sync my new Fenix logins with my Fx account 
- When enabled, I can access existing FxA logins in Fenix #5544

**Comment by liuche** [comment]
This might have overlap with Login Migration, and can work on together w/ AC/@grigoryk - need to see where the overlap is.

**Comment by Baron-Severin** [comment]
@jpfaller I'm landing strings for 3.0, do you know if we have any ready for this story?

**Comment by jpfaller** [comment]
This wasn't on my radar - @lime124 , is there a UX spec I can look at?

**Comment by liuche** [comment]
@boek did you add the strings-needed label for L10N or for something else? Maybe this was a problem because the eng:ready label was already on it? The main mocks are in #1284 (but I think this is the correct screen).

**Comment by jpfaller** [comment]
These strings are ready based on ux mocks from @AmyLee

**Comment by liuche** [comment]
@grigoryk will land the AS pieces for this work by the end of the week.

**Comment by AndiAJ** [comment]
Hi @ekager , I've just checked the Sync Logins on latest **Nightly Build #13220606 from 11/18** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)


✔️ The "Logins" is displayed and can be enabled/disabled in the "Choose what to sync" section from the Account settings.
✔️The Logins pref setting status (enabled/disabled) is properly updated in the "Sync logins" from the "Passwords" section.
✔️When tapping "Sync logins" the user is redirected to the Account settings to enable/disable the "Logins" pref.

► Video from Google Pixel 3a XL
![20191118_153746](https://user-images.githubusercontent.com/51314259/69058071-a6f9b980-0a1b-11ea-8f52-2651d54b1798.gif)

❓ I've noticed that when you enable the first time the "Logins" from the Account settings, the **authentication set up prompt** is displayed.

**Is this the desired behavior?**

I'm asking because the **Google Pixel 3a XL** is the only device that doesn't display the prompt when enabling the "Logins" for the first time. 

► Video from Huawei Mate 20 Lite
![20191118_153250](https://user-images.githubusercontent.com/51314259/69058775-fa203c00-0a1c-11ea-8d83-3f847763e935.gif)

Please review and let me know if I've missed any other aspect while testing. :relaxed:

**Comment by ekager** [comment]
Yes this looks good! Thank you @AndiAJ !
