### ISSUE TITLE
[Bug]Improperly displayed Site permissions - "No site exceptions" after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5104]
## Prerequisites
Don't have any saved site exceptions

## Steps to reproduce
1. Navigate to Settings
2. Tap on Site permissions
3. Tap on Exceptions
4. Rotate the device to landscape view
5. Rotate the device back to portrait view

### Expected behavior
The "No site exceptions" string remains centered after each rotation

### Actual behavior
Whit each rotation the "No site exceptions"gets shifted.

### Device information

* Android device: 
• OnePlus 6T (Android 9)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nighlty Build #12470611 from 4/9

### Notes
► Video
![20190904_090048](https://user-images.githubusercontent.com/51314259/64257245-b34a9c00-cf2d-11e9-928d-59355797a1a7.gif)

**Comment by ekager** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build #13010606 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4(Android 5.1.1)

►Video
![20191028_100508](https://user-images.githubusercontent.com/51314259/67662024-41aa2f80-f96b-11e9-9919-f25680925bf1.gif)

**Comment by AndiAJ** [comment]
Still reproducible on Fenix 2.3.0-rc.1 from 28/10 using a Samsung Galaxy Tab A (Android 9).

**Comment by ValentinTimisica** [comment]
Looks like it's still reproducible because my PR is not included in 2.3.0-rc.1 RC.

- [The change I did on empty_exception_container](https://github.com/ValentinTimisica/fenix/commit/237a5a23fdc2cd2d1428f3485babbf2baf61b46c)

- [empty_exception_container from 2.3.0-rc.1 RC](https://github.com/mozilla-mobile/fenix/blob/bc241db904a2c16fd1b88c451435637aac4be89a/app/src/main/res/layout/fragment_site_permissions_exceptions.xml#L38)
