### ISSUE TITLE
Support about:reader?url= URLs (reader view pages saved in Firefox desktop)

### ISSUE THREAD

**Issue by elcste** [mozilla-mobile/fenix#5190]
### Why/User Benefit/User Problem

Right now, if I open a page in Firefox desktop, enable reader view, bookmark the page, and then try to open this link in Fenix, I just get an "Invalid Address" error page since the link starts with about:reader?url=... (And since the underlying page URL is percent-encoded, it's hard to just remove the protocol part.) 

### What/Requirements

about:reader?url= links should opens, ideally in Reader Mode. But even just loading the page would be better. Fennec opens these links in its reader view.

### Acceptance Criteria (how do I know when I’m done?)

Reader view page links from desktop Firefox open in Fenix without any problems.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13337)

**Comment by csadilek** [comment]
Thanks for filing! 

This requires solutions to the following issues (and their dependencies):
https://github.com/mozilla-mobile/android-components/issues/2879
https://github.com/mozilla-mobile/android-components/issues/2985

**Comment by gijsk** [comment]
FWIW, https://bugzilla.mozilla.org/show_bug.cgi?id=1185918 suggests that we want to just not allow bookmarking these URLs and bookmark the "real" URL instead.

**Comment by opusforlife2** [comment]
> FWIW, https://bugzilla.mozilla.org/show_bug.cgi?id=1185918 suggests that we want to just not allow bookmarking these URLs and bookmark the "real" URL instead.

I would go the opposite way and say that these about:reader URLs are **useful** and should not only be bookmarkable, but copyable and shareable from the address bar as well. Instead of messing with the about:reader URL, the user could right click on the original page link at the top of the page, and bookmark _that_. (On that note, why show just the top level site link when it is actually the full URL? If the full URL was shown, it would be more discoverable and users might interact with it more.)

The main benefit is that Reader Mode removes cruft. There are so many cases where you want to share an article with someone but the site itself is filled with ads and other irrelevant nonsense. Directly sharing an about:reader URL so that the other person doesn't have to deal with all that is valuable. Bookmarking the Reader Mode URL so that you can open it directly later is valuable.

I would go so far as to say that when you long press on links in Reader Mode, there should be an option listed that offers to open _that_ link in Reader Mode as well.

**Comment by thirdconspiracy** [comment]
As stated in #14800 the about:reader is useful for
* bookmarking reader view
* sharing reader view
* faster load on open
* editing URL to go to next chapter in web novel without visiting site

If I'm in reader view when i bookmark, I would expect to return to reader view when selecting said bookmark.  Just like if I was in normal view, I'd expect to return to the normal site. 

An alternative would be to make it configurable but I've always considered clear indicators of state as good UX. Perhaps a better option would be to add a flag as part of the bookmark for reader view.  Then you see the decoded URL but have a clear indication on which view you want.

Bookmark Wireframe
Name: _________
URL: _____
Use Reader: [x]
Tags: ______
Keywork: _________

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813176

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
