### ISSUE TITLE
[Bug] behaviour of regular and private shortcut is not consistent

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#5231]
### Steps to reproduce

1. add private browsing shortcut to home screen
2. press the regular shortcut and the private shortcut
3. compare

### Expected behavior

Same behaviour in both modes.

### Actual behavior

Regular shortcut: Fenix opens with the start screen.
Private shortcut: Fenix opens with the search engines opened.

### Device information

* Android device: HTC U11 with Android 9.0
* Fenix version: Master branch revision bafbea1512f36b7c8771bf865ac234d8e411e608

**Comment by brampitoyo** [comment]
@cadeyrn The Private Tab shortcut should make Fenix open the Private Mode start screen.

**Comment by sblatz** [comment]
Can we get @AmyYLee's confirmation on this? I believe this goes against her original design.

**Comment by brampitoyo** [comment]
@cadeyrn,

@sblatz was correct. It was wise for me to get @AmyYLee’s confirmation, because her original design did specify that the private shortcut should access Fenix PBM with the search engine open.

Why didn’t the shortcut access the PBM homescreen instead?

The scenario:

* A user had PBM minimized in the background
* The user had forgotten that they have some private tabs open, or deliberately didn’t close them
* They decided to search something privately by using the shortcut
* There’s somebody else present around the phone

In this scenario:

* We still want to respect the user’s choice by opening PBM
* However, we also want to respect the user’s privacy, _just in case_, by not opening the homescreen: the page that contains the list of all private tabs that the user has open
* Therefore, we open Fenix PBM with the address bar selected and search engine open

So the behaviour isn’t inconsistent. It’s by design. Hope this helps clear it up!
