### ISSUE TITLE
[Bug] Crash: RemoteServiceException Couldn't expand RemoteViews for StatusBarNotification

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#5318]
## Steps to reproduce
The exact steps are unknown, but it appears to only happen with the search widget on Android 5.x devices, mostly from Huawei.

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6241350/

### Expected behavior
The search widget should not crash.

### Actual behavior
The search widget crashes.

### Device information

* Android device: Huawei Android 5, Lollipop
* Fenix version: 1.4.0-1.4.1 release

**Comment by colintheshots** [comment]
It almost seems like Huawei and other Chinese manufacturers don't support the full set of views in RemoteViews in their old smartphones.

**Comment by boek** [comment]
Also a problem here: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7672941/?query=is%3Aunresolved%20level%3Afatal

**Comment by mcarare** [comment]
I investigated this and it seems like the problem was solved in https://github.com/mozilla-mobile/android-components/pull/7514. That also correlates with the app versions that we see in sentry. The fix was integrated in 78 beta, and we do not have any reports for versions >= 78 beta. 
@liuche IMO this can be closed, and reopened only if we see reports for versions after 78 beta.

**Comment by liuche** [comment]
Thanks for the investigation! Looking at the sentry jeff posted, it does seem to have dropped off, and neither report has a lot of issues, so I agree this is okay to close.
