### ISSUE TITLE
[Bug] ui parity for delete browsing data screens

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5339]
## Steps to reproduce
Go to: 
Menu > Settings > delete browsing data [DBD]
And
Menu > Settings > delete browsing data on quit [DBDOQ]

### Expected behavior
- Consistency between available information and element sizes
- DBDOQ screen shows the same quantity of information as the DBD screen (number of items to be erased)
- DBD screen appearance follow that of the (newer, better looking) DBDOQ screen 

### Actual behavior
- The DBDOQ screen contains less info (number of items to be erased)
![Screenshot_20190915-115321](https://user-images.githubusercontent.com/50635951/64924265-9aa17800-d7b0-11e9-9064-93a2c15f69ad.png)

- The DBD screen elements are undersized and design should(?) Follow DBDOQ 
![Screenshot_20190915-115308](https://user-images.githubusercontent.com/50635951/64924278-bad13700-d7b0-11e9-9c78-11137ef2e3d0.png)

### Device information

* Android device: 8.1.0
* Fenix version: Nightly 190915 06:04 (Build #12580614)
📦: 13.0.0, 946a4254f
🦎: 71.0a1-20190913092859

**Comment by NotWoods** [comment]
UX team: Please specify which design the two screens (Delete Browsing Data & Delete Browsing Data on Quit) should follow.

**Comment by lime124** [comment]
Hi all - let me tackle one point at a time...
- quantity numbers missing (e.g. tab count)- the DBDOQ screen shows less information (e.g. tab count) b/c the information is going to vary each time the person quits the browser and data is deleted. whereas in the DBD screen, that is a one time delete at that precise moment so the information (e.g. tab count) reflects exactly what is going to be delete at that moment

- number of data categories deleted - the only difference i see here is collections. i would have to refer to @AmyYLee for the design rationale here (she's on PTO right now). i would hazard though the reason is along the lines of if you are deleting data every time you quit the browser, you probably are avoiding creating additional data like collections. Create a collection is a user initiated task - it doesn't make sense to delete something you just purposefully created. Similar to a bookmark!

- missing delete button - the delete button is missing from DBDOQ because this is a setting and the delete action is on "quit" from the browser. 

- visual design - i'm not sure why the checkbox list looks visually different between the two screens. @NotWoods please refer to the spec to see which is correct and update. 

i think i covered all the difference between the two screen. please lmk if i missed something. the only item i'm seeing out of this is the visual design difference. @NotWoods please reach out to us again if there's additional follow up from my team. removing needs ux label. thanks!

**Comment by nahuhh** [comment]
1. Fair enough. Perhaps when you hit the "quit" button, a prompt will show 
"quit Firefox and shred 
40 open tabs
25 items from history
200mb cache
All Cookies
All Site permissions

Cancel/delete"

2. My thoughts exactly. Collections should not be included (manually created collection should be manually deleted) 

3. Agree. Should be no "delete" button on DBDOQ  screen

4. Visual design. Should DBD should match DBDOQ (spacing etc). DBDOQ is the better looking version IMO

**Comment by AmyYLee** [comment]
Visual design. Should DBD should match DBDOQ (spacing etc). DBDOQ is the better looking version IMO. 

@nahuhh @boek Agreed. Can you please update? Thanks!

**Comment by lepiku** [comment]
In my pull request, I followed DBDOQ item height on DBD items. Any suggestion? Thanks!

**Comment by brampitoyo** [comment]
UX feedback is no longer required on this issue, so I’ll remove the label.
