### ISSUE TITLE
[Bug] In a private custom tab, "Open in Firefox Preview" open a non-private tab

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5345]
First reported in #5334.

## Steps to reproduce
Video attached.  

"Menu > open in Firefox preview" opens in a non-private tab
### Device information

* Android device: 8.1.0 
* Fenix version: Nightly 190914 06:02 (Build #12570610)
📦: 13.0.0, 1f55c03be
🦎: 71.0a1-20190913092859
![20190914_141745](https://user-images.githubusercontent.com/50635951/64912260-a894c180-d6fa-11e9-8933-52930a4af7cc.gif)

#### Design Work
- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~
- [x] Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed
- [x] Interaction details included
- [x] Accessibility – is this a review by someone, just keeping it in mind?
- [x] For existing UI changes, deltas are highlighted: compare “Current” to “Proposed” in user flow
- [ ] ~Strings/content reviewed and approved~ (no new strings/content)
    - [x] Are they too long for the component in other locales (our menu will be able to handle it)

#### Deliverable
- [ ] ~Assets uploaded to Google Drive~ (No new asset)
- [x] Links to deliverables (spec, assets) posted in comment 0

### Deliverable links
- User flow: none
- Spec: see below
- Assets: none

### Spec

<img src="https://user-images.githubusercontent.com/51007/69688564-4d843f80-112b-11ea-9a72-81b59fe4a10a.png" width="360">

* The menu item inside the custom tabs menu should say “Open in Firefox Preview (Private)”
* This means that private custom tabs should always open Firefox private tabs
* Why? Because users have specifically gone inside Settings and overrode our default policy. We should respect their choice by carrying over our tab type.

**Comment by AndiAJ** [comment]
Hi, reproducible on **Nightly 12671259 from 24/9 (Play Store)** using a Google Pixel 3a (Android 9) when enabling the "Launch link in a private tab" #5396 

►Video
![20190925_122917](https://user-images.githubusercontent.com/51314259/65588773-c54db680-df90-11e9-80d1-dac8d83ddb5f.gif)

**Comment by kamran-12** [comment]
It also happens when the app which requests the browser uses a normal browser tab instead of a custom tab.
I am not sure if it is a bug, but this behavior is definitely bad. I particularly like the fact that Fenix doesn't disable private mode at the end of each browsing session. I hate browsing history, and I hate clearing it or enabling private mode every time. Of course, we users sometimes need features of non-private browsing. But if that happens 10% of time when we open the app by touching the icon, it is 1% when we open a link directly from another app.

**Comment by mcarare** [comment]
Questions for UX: 
 - What should the text be on Private Custom Tabs: "Open in Firefox..." or "Open in Firefox private tab", or something similar? Could we add them both?
 - Should the tab opening in Firefox from Private Custom Tabs default to the type of the custom tab? Or could we give both options?

**Comment by brampitoyo** [comment]
Hi @mcarare, I think that @apbitner has been working on Custom Tabs, so let’s ask him about the text labelling and behaviour.

My initial opinions:

- I assume you refer to the text inside the custom tabs menu. If so, it should say “Open in Firefox Preview (Private)”, and it should open private tabs by default.
- Correct. The tab opening in Firefox Preview originating from Private Custom Tabs, should also be a private tab.
- Why? Because users have specifically gone inside Settings and override our default custom tabs policy. If they’ve gone through the steps to make their custom tabs private, it makes sense for us to carry over the same tab type.

**Comment by apbitner** [comment]
I agree with @brampitoyo 's assessment

**Comment by brampitoyo** [comment]
Thanks @apbitner for confirming!

I’ve updated comment 0 with UX behaviours. Removing `needs-ux`.

**Comment by mcarare** [comment]
@brampitoyo @apbitner Thank you both for the help!

**Comment by sblatz** [comment]
This seems to be working when I just tested on my Galaxy S9 (on master)

![private demo 2019-12-26 09_50_30](https://user-images.githubusercontent.com/4400286/71480051-2d48ae80-27c5-11ea-88e5-f5e725c30c28.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13610606 from 12/27** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191227_100827](https://user-images.githubusercontent.com/51314259/71508842-d8269e80-2891-11ea-8fc9-69a2686ea304.gif)
