### ISSUE TITLE
Consider persisting private tabs through memory eviction / force quit

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5386]
We should consider persisting private tabs even when users force quit the app or it is evicted from memory. Currently private tabs are all lost when the OS decided to kill our app which can happen frequently especially on older phones. 

We currently match the behavior of Focus so CHANGING it would be against how Focus operates.. 

I think it's reasonable to think about this especially if we are implementing #4780 since it won't expose user data by default when opening the app, but definitely up for discussion.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13471)

**Comment by buttercookie42** [comment]
See also #2493

**Comment by weedy** [comment]
Please please please, please please, please please do this.

I have "Delete browsing data on quit" and "open links in private tab" turned on since I replaced Focus with Preview. But I fundamentaly understood that Focus is a temp sandbox and I go do heavy lifting in full fat Firefox. Preview is full fat, I use it for everything all the time...

But losing 10, 20, yesterday 43 private tabs because Preview crashed or android LMKs the app is frankly bullshit. 

Add another toggle in "Delete browser data on quit" so it only nukes stuff when I close a tab or manually hit Quit in the menu. 
I understand why the current behaviour is what it is, but if I'm bothering to turn on all the other privacy options maybe I have plans that don't involve the browser thinking it's okay to nuke my session. Especially when it's not even up to Preview in the case of reboots/LMK/app crash.

**Comment by hackel** [comment]
This is also a frustration when Firefox gets updated automatically in the background and you lose all your (private) tabs.  There really needs to be an option to persist private tabs.  On a mobile device, "private" isn't about other people using the device (this just isn't a concern), it's about not persisting any cookies, local storage, or other potential tracking data that sites can access.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807554

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
