### ISSUE TITLE
Let Users Know About "Send to device" (Feature Discoverability) 

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#5400]
### Why/User Benefit/User Problem
It allows for example continuing to read something from my phone to my laptop.

### What/Requirements
Add a feature similar to "Send Tab to Device" on Firefox desktop.

### Acceptance Criteria (how do I know when I’m done?)
When you can send a tab to a device that is syncing with Firefox Accounts and for the tab to open on that device.

**Comment by ekager** [comment]
We do have send to device if you are logged in to fxa and press the 3 dot menu -> share. Is this different than what you mean?

**Comment by matusaurio** [comment]
It'd be nice to have the option **_Add to Firefox_** directly in the share options like the one in Firefox for Android (see image below) instead of just opening the link (current behaviour).

![fenix](https://user-images.githubusercontent.com/6020173/65321065-84762c00-dba3-11e9-811c-7de40100e658.png)
