### ISSUE TITLE
Public (community) wikis and issues should not link to google docs that can't be accessed by the community.

### ISSUE THREAD

**Issue by creesch** [mozilla-mobile/fenix#5410]
I am really not sure where else I am supposed to place this but as there doesn't seem to be any other place to publicly discuss the development of fenix (I briefly considered the support forum, but that seems to be more specifically for... well, support) so I figured this is the best shot. 

For a while now I have been trying to get some insights in the development direction of fenix and generally what decisions are being made. 

What I have noticed though is that in many places when I try to follow links with more information I run into google documents where I have to request access to view the documents. 

I do understand that there is an internal development team, product owners, product managers, etc who also need to decide on things internally and document these things. But when all the information available to the outside world is a google document link you can't access it really doesn't feel like an open source community project to me. 

This is further strengthened by the use of labels in the project that aren't always publicly documented making it unclear what the status is of an issue. 

Some random examples: 

- [This is a public wiki that at the face of it just describes general processes](https://github.com/mozilla-mobile/fenix/wiki/Fenix-Team-Processes), reading it further and trying to follow it the links it becomes clear that it only describes the process for internal mozilla devs. 
- [This issue consists of only a link to a google docs hosted feature brief](https://github.com/mozilla-mobile/fenix/issues/5315), which I don't need full access to but a summary would be nice.

It might seem like I am trying to make a big deal out of the entire thing, *that is not the case*. It is simply something I noticed and this does seem to be the best place for it. I am still very much excited about the development of fenix and am very much looking forward to further development.

**Comment by jonalmeida** [comment]
Assigning to myself to go through our issues and find private docs that should be public.

**Comment by dessant** [comment]
This is a widespread issue across all Mozilla projects, there are thousands of design documents and project plans that sit in private Google Docs and are linked from Mozilla projects on GitHub and Bugzilla.

https://github.com/search?q=org%3Amozilla+docs.google.com&type=Issues

Ideally the internal policy at Mozilla should be changed to default to public Google Docs, when the links are shared in public repositories.

Forbidding users from having access to all this material makes it difficult for them to participate, share ideas and feedback, and to efficiently contribute to Mozilla projects, and it goes against everything Mozilla stands for.

Please reach out to other collegues at Mozilla and consider bringing up this issue at a meeting. Turning already shared documents public is needed, but not enough, the policies for document sharing must be changed.

**Comment by vesta0** [comment]
@creesch thank you for sharing your thoughts and recommendations with us. 

At Mozilla, we always strive to be as open as possible and this is definitely top of mind. It is important to us to support our open source culture and engage with our community. 

As you mentioned yourself, there are times during the initial phases of a project that we need to keep some discussions internal (or even limited to specific people within) simply in order to stay focused and effective, before sharing more publicly and asking for much needed and appreciated participation and brainstorming. In such cases, we often try to refrain from posting links to private docs on Github but I admit that we haven't been consistent about that. However, we do frequently update issue descriptions as more info come to light, which was the case with WebExtensions for example. 

In the case of design docs, access is often limited to folks who have an account, so not even all team members always have access until needed. We hope to improve this in the future.

**Comment by TitanNano** [comment]
> As you mentioned yourself, there are times during the initial phases of a project that we need to keep some discussions internal (or even limited to specific people within) simply in order to stay focused and effective, before sharing more publicly and asking for much needed and appreciated participation and brainstorming.

@vesta0 I understand that there are times when teams at Mozilla do not have the capacity to accept contributions from the community, but I personally believe that if Mozilla wants to stay true to its principles, everything should be always publicly viewable. Just because something is visible to the public does it not mean it's always open for contribution. I understand that you can not always include the entire community in every decision, but it becomes difficult to contribute, if people can not understand parts of the process because these parts are locked away from the community.

**Comment by creesch** [comment]
[This is another example](https://github.com/mozilla-mobile/fenix/issues/5315#issuecomment-582953593) of the sort of thing that makes this feel less like an open source project and more like a project where the source happens to be public.
