### ISSUE TITLE
[Meta] Iterate on search experience

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#5457]
### Why/User Benefit/User Problem
- Iterate on the search experience and bring more alignment between desktop and mobile search experiences. 

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)
-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

### What / Requirements (Added by PM and Eng Manager)
-UX Designs (Immediate task: Assign UX issue to this epic)
-User stories (to be created by PM)
-List dependencies on other issues/teams etc.

### Reference Issues
- #482 - de dup awesome bar results
- #4637 - enhanced search experience

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13512)

**Comment by lime124** [comment]
@Verdi FYI

**Comment by yeeeehooo** [comment]
I'll add it here since it's somewhat related... if you visit a bookmarked website you also end up with duplicate entries. If it's not too expensive a check it should be added to make sure bookmarked websites aren't added to the history. I was gonna add another issue for not adding invalid URLs but there seems to already be an issue for that  #(#2064)...

**Comment by boek** [comment]
Going to close this as there has been iterations on the search experience since this was created. We can create a new epic when we want to revisit again.
