### ISSUE TITLE
[Bug] Read button doesn't appear if an article is opened in the main app from a custom tab

### ISSUE THREAD

**Issue by Trevonn** [mozilla-mobile/fenix#5472]
## Steps to reproduce
1. Open article in a custom tab
2. Use three dot menu to open in Firefox Preview

### Expected behavior

Read button appears alongside share sand bookmark buttons

### Actual behavior

Only share and bookmark buttons appear.
Refreshing the page will cause the read button to now appear as expected.

### Device information

* Android device: Pixel 3 - Android 10 (Sept Patch)
* Fenix version: Nightly 190919 18:00 (Build #12621820)
📦: 14.0.0, 0681a1e65
🦎: 71.0a1-20190916093313

**Comment by ValentinTimisica** [comment]
I investigated this bug and the problem is that when you open a custom tab in Firefox Preview, the [onPortMessage](https://github.com/mozilla-mobile/android-components/blob/b7bff5edf3653824c5295633cd2839daf740e4c0/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt#L241) callback from ReaderViewContentMessageHandler is not triggered and therefore the ReaderActiveStateChange is not changing in [initializeUI](https://github.com/mozilla-mobile/fenix/blob/18c0525ff6f67545d4e670b1842d0f47406133c6/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L122), so the ```Read``` button remains hidden.

I tried to manually call [checkReaderable](https://github.com/mozilla-mobile/android-components/blob/b7bff5edf3653824c5295633cd2839daf740e4c0/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt#L192) but seems like the port is not connected for the active session thus ```extensionController.portConnected(engineSession)``` returning false, so I'm currently stuck going forward with this proposed solution.

Does anybody has any idea on how to proceed with the above scenario or has any other solution?

**Comment by csadilek** [comment]
@ValentinTimisica Yes, the reason for this is that the content script (`readerview.js`) injected by the `ReaderViewFeature` web extension runs when the page is loaded. If the page is loaded in a `CustomTab`, it won't run at all, because we don't start this feature for custom tabs. When the tab is then opened in / migrated to the main app it is too late. The page has already loaded. If you reload, you will see it working.

Since we don't want to reload in this case, we would have to start the `ReaderViewFeature` for custom tabs as well. This would require the following changes:
- In Fenix: Start the `ReaderViewFeature` in the `BaseBrowserFragment` instead of the `BrowserFragment`
- In A-C: Allow the `ReaderViewFeature` to operate on a specific (provided) session, not just the selected session

So, it's not a straight forward fix, unfortunately.
