### ISSUE TITLE
[Meta] Adding user-specified search engines

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5489]
## User Story
As a user, I want to be able to add and use a custom search engine other than the ones provided by the browser, so I can have more options and choice. 

### Acceptance Criteria
- I can add a custom search engine in Fenix.
- I can remove a custom search engine from my list of search engines
- I can see my custom added engine in the list of search shortcuts

**We will follow the Fennec approach for this ticket**

**Comment by liuche** [comment]
@sblatz Also can do a walkthrough w/ Fennec Search engine feature w/ you, which includes OpenSearch plugin (for some sites) and adding a search engine from a text field.

**Comment by sblatz** [comment]
@vesta0 and I will go through this and make sure we cover all of the dependencies/edge cases:

- GV support to "detect" if a page is a search engine (@cpeterso is this already supported?)
- Adding custom engine to AC EngineManager
- Adding/deleting/editing engines (including default ones?)
- Making sure we don't send telemetry about which custom engine a user has selected
- Adding custom engines to the "Search Shortcut" screen in the Search Fragment

**Comment by cpeterso** [comment]
> GV support to "detect" if a page is a search engine (@cpeterso is this already supported?)

No. Fennec and desktop Firefox have logic for this, but GV does not.

Channeling the GV engineers, I expect they will say GV should not add a search engine API, but instead A-C should use an extension to detect whether a page includes a form with an `<input type="search">` element.

**Comment by mconnormoz** [comment]
Hi folks, looks like this got deprioritized, but we're planning on dropping support for OpenSearch entirely on desktop, so please don't implement it in Fenix!  We should focus on supporting this feature only through WebExtensions.

**Comment by snaggen** [comment]
@mconnormoz As a user I wonder what the migration from OpenSearch to WebExtentions means for me. Where am I supposed to find them? Should I expect each search engine to provide them, should I search addons (and if so, how do I know which one I should use, there are a lot of different addons for example duckduckgo).
Also, will there be a set of pre-installed webextensions?

Currently, due to this ticket never being prioritized, I'm forced to use an external search app on my phone to be able to use duckduckgo, which is not really optimal... it would be nice to not be forced to use the worst search engine from a privacy perspective, in a privacy focused browser.

**Comment by maverick74** [comment]
Hã?!?!

Why is OpenSearch being deprecated?

I mean... it's INCREDIBLY USEFUL to be on a site and just click "Add this search engine"... and get on with it

**Comment by saddy001** [comment]
For me, not being able to add a custom search engine is a show-stopper. Searching is one of the most important features in this internet-thing.

**Comment by vesta0** [comment]
We will track this feature here: #5577
