### ISSUE TITLE
[Spike] Address autofill Dependencies and options

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5492]
This is an investigation ticket for this Meta: #5419

*  What is Desktop doing in terms of Form Save/Autofill, and can that be reused so Fenix can align with it? What heuristics can we reuse/share?
* What APIs does GeckoView provide, in terms of Form save/autofill? Are there other APIs that we need, and if so, we need to get those in the GV backlog.
* What is necessary for Form Sync, in AS?

### Acceptance Criteria
- [ ] Verify existing APIs for form save/fill  available for use in Meta #5419 
- [ ] Identify any outstanding dependencies and link them below
- [ ] Technical limitations for #230 Autofill Addresses

**Comment by linacambridge** [comment]
Hi @liuche and @vesta0! I'll likely be helping with this from the AS side, and wanted to fill in some details. I think it'd be worth writing up a one-pager eventually, but let's chat on GitHub for now. Reading through the issues you linked to, it sounds like you want:

* Heuristics, to extract name, address, and credit card fields from the page.
* A way to persist those fields, and autofill them on other pages.
* Sync those fields.

Desktop currently has two ways to do this, and they partially overlap:

### Form history

[Form history](https://support.mozilla.org/en-US/kb/control-whether-firefox-automatically-fills-forms) stores values that users type in to text `<input>` elements, keyed by the element's `name` or `id` attribute. It's mainly useful for remembering text fields on the _same_ site, but not between sites.

Form history isn't tied to the page origin—if I type "hi" into an `<input type="text" id="baz">` on foo.com, and bar.com also has an `<input type="text" id="baz">`, I'll get "hi" as a suggestion on bar.com.

It also doesn't use any heuristics (and doesn't understand anything about the structure of what it's storing...it doesn't know if a field is a name, address, city, or plain old free form text entry), which makes it less useful across sites. For example, if foo.com has `<input id="address-line1">` but bar.com calls it `<input id="addrline1">`, the address I typed in to foo.com won't show up in bar.com, and vice versa.

There's no way to see all your form history, and no way to edit it outside of the page. You have to open the page, focus the control, use the down-arrow to select the entry you want to change, delete it, and then enter a new value. Suggestions are presented using a [frecency algorithm](https://searchfox.org/mozilla-central/rev/153feabebc2d13bb4c29ef8adf104ec1ebd246ae/toolkit/components/satchel/FormHistory.jsm#1204-1212), and old history is periodically expired.

Form history is synced as part of regular browsing history—toggling the "history" checkbox in Sync prefs affects both page and form history. However, it's possible to configure Firefox not to store one or the other in about:preferences#privacy, using custom settings for history. There are checkboxes for "Remember browsing and download history" and "Remember search and form history" in the "History" section.

### Form autofill

[Form autofill](https://support.mozilla.org/en-US/kb/automatically-fill-your-address-web-forms) uses [heuristics](https://searchfox.org/mozilla-central/rev/153feabebc2d13bb4c29ef8adf104ec1ebd246ae/browser/extensions/formautofill/FormAutofillHeuristics.jsm) to scan a page, and guess the structure of the address that the page is expecting. There are two parts to form autofill: addresses, and credit cards.

Address autofill heuristics are locale-specific, since address formats vary from country to country. For this reason, it's only currently enabled in `en-US` locales by default.

Credit card autofill is disabled everywhere, since there are concerns around secure storage (showing a prompt to unlock the Master Password, or macOS Keychain, to avoid snooping), and ensuring it works reliably on top shopping sites.

Like form history, neither address nor credit card autofill are tied to origins, since they're designed to be used across sites. Unlike form history, users can see the addresses they've saved, edit and remove them, and add new ones. There's a "Saved Addresses..." button that shows the list in about:preferences#privacy, in the "Forms and Autofill" section.

Addresses and credit cards are synced separately. The "Addresses" and "Credit cards" checkboxes are only offered to users for whom these are enabled—by default, only US users for addresses, and no one for credit cards. Of course, it's still possible to enable these by flipping the `extensions.formautofill.creditCards.available` and `extensions.formautofill.addresses.enabled` prefs (and `services.sync.engine.addresses.available` and `services.sync.engine.creditcards.available` prefs for Sync).

Address autofill has a [wiki](https://wiki.mozilla.org/Firefox/Features/Form_Autofill) with more details.

### What does this mean for Fenix?

* Form history is still useful, and can be implemented relatively easily. AS can provide APIs to store, delete, and clear all form history entries, and fetch all suggestions for a form element.
* Address autofill would be super useful to have, and higher user value than form history—all the linked tickets call it out as the main use case—but much more difficult. Syncing and storing them is easy, but the heuristics are tricky. We'd need to implement them in either Rust code or Android Components, and figure out a way to keep them up to date. Since address formats vary, we'd need to figure out which countries we're supporting, and our timeline for adding new ones. Supporting the same locales and Desktop feels like the easiest option—it would be unfortunate if Fenix let you save addresses that you couldn't then see on your laptop!
* Credit card autofill is the most difficult of all, and Desktop's implementation still needs work. Additionally, it's not currently synced or stored anywhere by default. As with addresses, the syncing and storing plumbing isn't difficult (it's a document format with string keys and values!), but the heuristics and privacy are much more challenging.

This glosses over a lot of the details, but it's a starting point. (@thomcc, please add or correct anything as you see fit!) Let's talk more about it this week, @liuche!

**Comment by vesta0** [comment]
Met with Lina, Ana, and Janet today. Product will investigate use cases further and then work with Lina on this spike. Removing this from the Fenix Q4 backlog.
