### ISSUE TITLE
Add an option to disable Custom Tabs and just open the browser directly

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#5513]
### Why/User Benefit/User Problem

When I open web pages from another app (for example, LinkedIn -- it doesn't seem to happen for all apps), I get what appears to be a Fenix web view in a limited, app-specific chrome. Since this looks a lot like built-in Chrome web views, which I would like to avoid to keep all my browsing in a single browser, I would prefer to always get the full Fenix chrome.

### What/Requirements

Add a way to disable the web view activity in favor of full chrome.

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13554)

**Comment by NotWoods** [comment]
That limited view is called a [Custom Tab](https://developer.chrome.com/multidevice/android/customtabs). It's for apps that want to look like a page is opened in the app, without using a limited webview. These are actually powered using Firefox Preview and you'll get shared cookies, history, etc. The only different is the toolbar looks difference.

FYI there is an "Open in Firefox Preview" button in the custom tab overflow menu, so there's an easy way to get the full experience.

**Comment by djc** [comment]
I guess I'd feel more comfortable with them if there was some clearer Firefox branding, but I'd still prefer to be able to opt-out of the use of Custom Tabs.

**Comment by klint** [comment]
Philistine question, but is this what is called a Custom Tab? Thanks

![image](https://user-images.githubusercontent.com/218971/65688932-3ada8500-e06c-11e9-9546-1adc6bf992c0.png)

**Comment by serovar** [comment]
Another problem, but I don't know if it's a bug or a "feature" is that in custom tabs uBlock Origin (and I suppose addons in general) does not work.

**Comment by festelo** [comment]
> The only change is the toolbar looks different.
> 
> FYI there is an "Open in Firefox Preview" button in the custom tab overflow menu, so there's an easy way to get the full experience.

But you can't get full advantages of android multitasking with custom tab (look at the pic). For example, when I open some long-read article in reddit through a link, i can't just return back to reddit app without loosing browser context (like scroll position). At first i need to make two taps to open full browser, why i need this?

So, i don't see any advantages of Custom Tabs, but see disadvantages. That's only reason why i switched from Chrome to FF, because FF has an option to disable CT.

![image](https://user-images.githubusercontent.com/20724864/74334550-2b55a180-4dab-11ea-9edc-99e929eccaa7.png)

**Comment by kevincox** [comment]
I agree. I have no interest in opening webpages in a more basic version of the browser. You can see numerous other feature requests in this tracker about adding features that already exist in the browser to custom tabs. Personally I an very confused what the advantages are. I think the one advanted I saw was faster loading, but if that is the only advantage then it seems like a better option is to provide a custom tabs shim that preloads in the full browser. 

But that is all besides the point. If the user prefers the full browser they should have the option to use it.  (Just like Fennic provides today)

**Comment by klint** [comment]
FYI, not directly dealing with Custom Tabs, but still, related to the current issue all the same : https://github.com/mozilla-mobile/fenix/issues/8908

**Comment by klint** [comment]
FYI, not directly dealing with Custom Tabs, but still, related to the current issue all the same : https://github.com/mozilla-mobile/fenix/issues/7758

**Comment by dcdruck** [comment]
This issue is the primary reason I downgraded to Firefox for Android 68 where I still have the option to disable CT (another major reason was many of my add-ons are incompatible). I see no advantage to CT but several disadvantages, including privacy implications from add-ons not working and crippling the concept of multi-tasking, which is an Android feature I use all the time. This makes me miss using Xposed and the ActivityForceNewTask module which solved this problem for all apps.

**Comment by wtanggg** [comment]
It looks like no one has been able to provide any reason that custom tabs are good. I think that's because there is literally nothing good about custom tabs.

**Comment by doctor82** [comment]
Please enable option to disable custom tabs

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812848

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
