### ISSUE TITLE
Add top-level authentication when accessing passwords

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#5547]
### Why/User Benefit/User Problem
As a user I want my logins to be behind an authentication prompt so they are protected 

### What/Requirements
- We will use the system biometrics prompts to block access to viewing sensitive login information
- Users that don't have any password protection system (do the minimum here, like not providing the protection, will handle this in spike)

What is NOT part of this issue:

- We need a fall back password system (other than biometrics) will be handled in spike #6055 

### Acceptance Criteria (how do I know when I’m done?)
- User logins are more protected by having an authentication prompt

**Comment by liuche** [comment]
@AmyYLee and @ekager will follow up about:
- What password/biometrics APIs are available
- How to handle error cases
- TODO: Decide what to do when biometrics fail
- TODO: Decide what to do if users don't have a password

And report that back.

We want to try the minimum non-edge case situations, and then file follow-ups.

**Comment by liuche** [comment]
Moving this into the sprint because we're moving out #5543 due to new GV work being done on it.

**Comment by liuche** [comment]
It looks like this PIN-code flow has some strings that will need to be landed - specifically, the two popup screens explaining the PIN protection (what they need to enter, or why they should set a PIN).

**Comment by ekager** [comment]
QA please tests:
1. If biometric is set, a user has to use biometrics or pin to auth
2. If only a PIN is set, a user must use a PIN to access passwords
3. If nothing is set, the user gets warned 
4. If you pause the app past the auth screen, you need to auth again

**Comment by ekager** [comment]
#6444 has landed and this should be ready to test now!

**Comment by abodea** [comment]
#### Hi @ekager, I tested what you mentioned above, here are my results:
| Screen lock type  | Displayed as unlock option? |Saved logins section opened?| Pause app past auth screen|
|------------- | :-------------: |:-------------:|:----:|
| **None** | **No warning displayed** [#6624](https://github.com/mozilla-mobile/fenix/issues/6624)  | ✔️  | N/A|
| **Swipe**  | **Yes**   | ✔️  | N/A | 
| **Pattern**  | Yes  | ✔️  | **Auth requierd again** | 
| **Pin** | Yes   | ✔️  | **Auth requierd again** | 
| **Password** | Yes   | ✔️  | **Auth requierd again** | 
| **Face Recognition** | No, the pattern was first option for unlock [#6630 ](https://github.com/mozilla-mobile/fenix/issues/6630)  | ✔️  | **Auth requierd again** | 
| **Fingerprint** | No, Fenix crashes [#6628](https://github.com/mozilla-mobile/fenix/issues/6628)   | ❌  | **N/A** | 


- Note that for the `Swipe` security lock option, it is nothing more than a swipe and because of that it acts like nothing is set.

Emily if possible please let me know if we can close this issue and follow the new bugs I added.
And there are few more issues that still need to be retested.
Here are the bugs that I found when I tested this issue:
- [Bug] The Saved Logins section is dismissed when resuming Fenix from a multitask to another app [#6618](https://github.com/mozilla-mobile/fenix/issues/6618)
- [Bug] There is a drop-down/expanded animation when accessing Settings for Passwords section [#6619](https://github.com/mozilla-mobile/fenix/issues/6619)
- [Bug] The Saved Logins section and passwords can be recorded [#6621](https://github.com/mozilla-mobile/fenix/issues/6621)
- [Bug] Saved Logins cannot be deleted even after logging out [#6623](https://github.com/mozilla-mobile/fenix/issues/6623)
- [Bug] The user is not warned when accessing Saved Logins if no biometrics or pin is set [#6624](https://github.com/mozilla-mobile/fenix/issues/6624)
- [Bug] Fenix crashes when trying to access Saved Logins if Fingerprint Biometrics are set [#6628](https://github.com/mozilla-mobile/fenix/issues/6628)
- [Bug] Pattern, Pin or Password screen lock types are always displayed over Biometrics(Face recognition and Fingerprints) when unlocking Saved Logins section [#6630](https://github.com/mozilla-mobile/fenix/issues/6630)

**Comment by abodea** [comment]
I synced with @ekager on slack and she agreed on closing this issue. We will open new bugs, as this one is verified according to my comment from above.
