### ISSUE TITLE
Choose a secure storage library for storing Logins 21-23

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5550]
### Why/User Benefit/User Problem
When storing my logins in my browser, I want the encryption key I'm using to encrypt the Logins Storage to be stored somewhere safe, so my logins won't be at risk.

Android secure storage library is 23+ (which is what Lockwise uses).

### What/Requirements
* Library needs to generate keys? Or is this generated by FxA
* Storage encryption library (?) that Fenix can use to store Sync encryption key
* API 21+
* Include library (need to decide/ask if this library will be in AC or in Fenix)
* Get security review for this library

### Acceptance Criteria (how do I know when I’m done?)
Fenix can include secure storage library that will keep Sync key secure locally.

**Comment by liuche** [comment]
I talked to @linacambridge about Sync storage and Logins, and it turns out that AS automatically will encrypt your logins for storage on-disk. I updated this issue to reflect that, so what it probably needs to cover is storing the Sync encryption key securely.

**Comment by liuche** [comment]
Lockwise uses storage and sync component, but this API level might be too low.

**Comment by sblatz** [comment]
@liuche can we please make sure this is actionable and we aren't jumping the gun on it?

**Comment by liuche** [comment]
I'm pretty sure we still need this once we start storing logins.

I remember talking to @grigoryk about this, briefly - grisha, could you look over comment0 and make sure it accurately represents what we need this secure storage library for & is actionable? And also if there's any additional context that I'm missing for someone to start on this.

**Comment by grigoryk** [comment]
An alternative to this is that we do nothing for APIs 21-23, acting like Fennec without a set master password.

IIRC, by default Fennec encrypts logins storage with a key that's something like "". Setting a master password changes that key, but for 99.9% of the users (whatever that number actually is, it's very high) our login storage story in Fennec is essentially "plaintext".

Fennec entirely depends on android-level protections for the appdir. On a rooted device or physically compromised device, you're out-of-luck. I think this is reasonable behaviour - it's in-line with our current approach to FxA state, for example, which can provide access to logins data as well (via a Sync client).

So using an empty cipher (or equivalent) for API21-23, and supporting proper secure storage for API23+ would be no worse (and much better for newer devices) than our current state of the world. This lets us avoid having to own a sec review for an external library, as well - which to me sounds like a can of worms you don't want to open. And it helps reduce our vulnerability surface, as well (due to one less dependency).

**Comment by liuche** [comment]
For 23+, AC (should) expose a way to configure and use the Android platform keys, but we'd still need to generate and store a key. (Look at what Lockwise does.)

Will look to discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1568690

**Comment by ekager** [comment]
The jetpack security library is considering lowering their min API to 19 but no updates since June :/
https://issuetracker.google.com/issues/132325342

**Comment by grigoryk** [comment]
We should be able to use A-C's dataprotect for all API levels once @ekager lands https://github.com/mozilla-mobile/android-components/pull/4740. This is great news, since we'll be able to just have one approach (at the high level, anyway) for all API levels.

**Comment by ekager** [comment]
@liuche I'm closing this ticket because we've gotten sign off on our current plan
