### ISSUE TITLE
[UX] Explore value and usability of organized living tabs (collections)

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#5652]
## User Story
- As a user I understand how collections can be useful for me and how they are different than bookmarks. 

Please see user feedback in this [spreadsheet ](https://docs.google.com/spreadsheets/d/1_scqRuhOezFDiiTN47ir9henxSzWFQwhERoryWWcC08/edit#gid=0)(filter for Collections)

### Acceptance Criteria
What should happen when a collection is restored (restoring a session or updated content?)
When saving tabs to a collection, does the user want to keep those tabs open in the tabs tray or remove them?
How might the user make best use of collections in a way that is different from bookmarks?
How might the user want to re-order tabs from within or between collections?
Does the user want to be able to save a collection as a homescreen shortcut?

See related files requests:
#9674

Also based on recent user feedback
-Some users thought we had replaced bookmarks with collections (and didn't have bookmarks) and wondered why collections didn't sync with desktop bookmarks.
-Navigating to saved bookmarks take too many steps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13658)

**Comment by lime124** [comment]
@vesta0 I know you said you would file it, but I had a spare minute as I am going through our backlog of work and cleaning things up for monday. :)

**Comment by lime124** [comment]
this will carry over to the next sprint since this was picked up part way through this sprint.

**Comment by yoasif** [comment]
I see collections like the old Panorama: http://www.azarask.in/blog/post/designing-tab-candy/

Collections are about saving a session or group of tabs to recall them at a later date. The biggest issue I have with collections right now is that they feel more like bookmark folders than collections -- instead of being able to treat collections like windows, opening a collection just adds them to my open tab list (like it would if I had opened a folder full of bookmarks).

Updating the collection also doesn't happen as a part of browsing -- if collections were treated like windows, I would be able to close the tab inside of the collection, and I wouldn't have a duplicate entry in "open tabs".

My feeling is that the collections idea has some interesting applications, but it really needs to be thought of like Panorama, because right now it is really a very weird form of bookmarks.

**Comment by madb1lly** [comment]
Hi @yoasif, I completely agree - currently collections aren't really fulfilling their potential. It's one of the reasons I opened this suggestion #6299.

Hi @vesta0, it appears that there is a lot of confusion about how Collections are supposed to work, with a lot of people expecting them to work like tab groups, like the Panorama or Simple Tab Groups add-ons in Firefox for Desktop, e.g. #5967 and #3804.

Please can you share the thinking behind how Collections are currently implemented and how the Fenix team expect them to be used? What user behaviour, telemetry, feedback, surveys or just general brainstorming led the team to conclude that Collections, as currently implemented, are what will help people?

**Comment by liuche** [comment]
Linking a few bugs that are related to Collections usability for @topotropic: 
- are there too many entry points to adding collections?
- how do we highlight to users that Collections maintain history (but, for example, don't automatically refresh)?

**Comment by Dunexus** [comment]
> * how do we highlight to users that Collections maintain history (but, for example, don't automatically refresh)?

What about renaming collections to tab group ? The notion of tab implies that there is an history while a collection sounds like an inert set of links (more like bookmarks)

**Comment by andreicristianpetcu** [comment]
Tab groups sounds intuitive

**Comment by yoasif** [comment]
The concept has previously been named saved sessions by various desktop add-ons. But I do recommend that the team read through the various comments that are out there about comments.

Collections are powerful - perhaps too powerful to wrap your mind around without some stepping stones or affordances. 

You can simplify the feature by conceptualizing them like windows on desktop - each collection is a window, and i can freely switch between them via some nice UI (Chrome was experimenting with an interesting one that still had flaws in _tab groups_).

The save and restore functions of collections are something desktop Firefox users have asked for for [years](https://bugzilla.mozilla.org/show_bug.cgi?id=1427928), so it is very interesting that collections did it all at once almost as an aside (I realize that the fenix team think that this is a cool feature, and it is - but it is flawed).

Conceptually, I think of that aspect of collection as being closest to a true power user feature, whereas the collections as windowing concept as the more accessible concept (but can reuse the same tech). 

I don't think that it is too complex an onramp, though - we just need to build the missing intermediary experience - we've already shot ahead to the save and restore functions without allowing users to interact with collections as a live, modifiable collection (ha!) of tabs that act like a window -- that in *addition* can be completely archived and restored *back to its own window* (this is missing and provides the missing link).

Happy to discuss further, as always.

**Comment by madb1lly** [comment]
Oh, Firefox <45 wants it's feature back! 😆

Because, really, how different are collections from tab groups? 

Or let's just call them Panoramas and really do a 180, making everything even more confusing in the process...

No,  tab groups is a better,  more understandable name,  until we can switch between them without the mess of manually updating them,  and sync them and desktop gets full compatibility, then we can go back to calling sessions again,  which to me makes more sense to me. 

Cheers🙂

**Comment by otede** [comment]
There are several things with the "history of a tab" per se no one seems to be talking about:
1. The discoverability of it is poor. You either read the release notes carefully or you don't know about it. 
2. Even once you do long-press the left arrow:
a) all entries may have the same truncated name
b) you don't know the time order of the entries
c) you don't know how or if visiting an entry from the list will affect the list itself

**Comment by jellocube** [comment]
After a few weeks of trying to make collections more useful than bookmarks and finding myself disappointed in a lack of collection parity with desktop syncs, I agree that this feature might be better implemented as "grouped tabs" or the like. Calling it "collections" certainly implies the multi-window grouping functionality described in above comments, but I don't find this paradigm translates well to mobile. "Windows" aren't really a thing on mobile, where tabs effectively serve the same function.

Grouped tabs are already conceptually related to bookmarking, so why do we need more UX abstraction/nomenclature?

**Comment by nhooyr** [comment]
> Grouped tabs are already conceptually related to bookmarking, so why do we need more UX abstraction/nomenclature?

Fully agreed! It's possible I'm confused but I've read through this thread and skimmed the official docs but I still don't understand how collections are any different from bookmark folders?

**Comment by nhooyr** [comment]
My bad, I suppose https://github.com/mozilla-mobile/fenix/issues/13793 is the differentiator?

**Comment by madb1lly** [comment]
Well only Mozilla can tell us if they think they've addressed this user story but I still don't think collections have fulfilled their potential, especially as they're not synced or backed up yet.
Cheers 🙂

**Comment by samlux04** [comment]
Let's be honest, what's the actual purpose for collections?
Previously there's pocket or something else I don't really remember since I don't really use any of this gimmick. Isn't it just a bookmark folder? Maybe with session saved like scroll position? But if the page updated it's useless anyway. If it just to open multiple tabs, why don't just add a feature to open a bookmark folder. There must be some intention when creating this gimmick. Maybe to suggest users to look at the homescreen where you can put news and stories to make money? It's okay if you just being honest.

**Comment by otede** [comment]
It's trivial, people! Anything not synced with Firefox Sync is a potential black hole for losing information.

**Comment by DavidJCobb** [comment]
It seems pretty notable that [Mozilla's own public messaging](https://blog.mozilla.org/en/products/firefox/get-organized-with-firefox-collections/) fails to properly describe what this feature is and how it works. It's described as a "more front-and-center" equivalent of bookmark folders... which begs the question of why one would need an entire new feature instead of making bookmark folders themselves "front-and-center" (as they were in Fennec, incidentally). But Collections aren't bookmarks; they apparently store session state as well.

The [support site](https://support.mozilla.org/en-US/kb/collections-firefox), meanwhile, describes the feature as a way to "save tabs," but to a layperson this can easily just sound like a synonym for adding a bookmark. No detail is given to the fact of this feature saving *sessions*, with all that that implies -- back/forward history and the like.

Saving and restoring multiple sessions is more of a power user feature than a casual user feature. Collections seem like an attempt at implementing an advanced / power user feature for casual users, but with literally no plan on how to actually promote and *teach* the feature to casual users... And this, it seems, leads to marketing copy and support text that actively avoids using the terms that would best describe what the feature *is* (because "session management" is jargon, you see) while offering a description so oversimplified and butchered as to make the feature seem pointless and redundant.

I doubt you can have your cake and eat it too, and trying just results in a janky feature with no clear design and no clear use case. It may be better to just bite the bullet and start treating and designing Collections like an advanced feature, rather than trying to hide its complexity -- and hiding its only unique and useful qualities in the process.

**Comment by lnicola** [comment]
@stale I still don't know what collections are.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812723

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
