### ISSUE TITLE
Grid layout for the main menu

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5702]
### Why/User Benefit/User Problem
At the moment the main menu is a list, that keeps getting longer and feels cluttered. It must me cleaned (e.g new tab option in the tab viwer instead), and a grid layout, similar to the Samsung Internet approach, would make such menu more organized, and space and thumb-friendly. I suggest that in the grid, instead of an option that gets us to the library, every library item to be shown directly, so that less taps are needed.

### What/Requirements
Instead of a list layout Fenix uses a grid layout for the main menu.

### Acceptance Criteria (how do I know when I’m done?)
The main menu has a grid layout.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13695)

**Comment by tonmoygoswami** [comment]
I completely agree with this.

Why: The motive of moving the Address Bar to the bottom is to enable better usability using the thumb. Moreover, mobile phones have become taller than earlier, hence stacking things at the bottom helps.

Hence, the menu can also be a horizontally stacked grid (closer to bottom), rather than the current vertical layout.

Here's a mockup I made:
![Image of grid layout](https://tonmoygoswami.com/wp-content/uploads/2019/10/menu-mockup.jpg)

**Comment by Lululalu** [comment]
@tonmoygoswami Maybe it depends on the size of our hands. For me at least it's easier to touch any item from you muckup using my right thumb, than from a list that reaches the top a 21:9 screen.

**Comment by Lululalu** [comment]
Closed by accident

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809225

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
