### ISSUE TITLE
[Bug] "Rate on Google Play" opens a dialogue asking if the user wants to open the Galaxy Store

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5714]
### Steps to reproduce
Go to the settings and touch "rate on Google Play".

### Expected behavior
Google Play's Firefox Preview page opens automatically

### Actual behavior
A dialogue is opened asking which app to use. Touching the Galaxy Store opens the Googl Play Store anyway
![Screenshot_20191001-162308_Android System](https://user-images.githubusercontent.com/32398857/65993974-b4a5b080-e468-11e9-996a-6a5333d4d606.jpg)

### Device information

* Android device: Galaxy A5 2017 Android 8.0
* Fenix version: 191001

**Comment by sblatz** [comment]
I think we could set the package to specifically be the google play store. Do we think that's a good idea? 🤔

**Comment by sblatz** [comment]
This sounds like it may be the Galaxy Store forwarding to the Google Play Store (since that's where we're hosted). It sounds like we don't want to specifically target the google play package since we may host on other stores in the future. 

That being said, we **could** detect if Google Play Store is installed and change the text of this button in cases where it's not?

Either way we decided this wasn't something we wanted to make a high priority.
