### ISSUE TITLE
[Bug] Inconsistent back button behaviour when navigating to library from browser

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#5727]
Follow-up to #4517 

## Steps to reproduce

Open a tab.
Open from Menu: Library go to History or Bookmarks
Open a new link from History /  Bookmarks
Press Back Button
### Expected behavior
Goes back to History / Bookmarks screen
### Actual behavior
Goes to Home screen

Needs investigation per https://github.com/mozilla-mobile/fenix/issues/4517#issuecomment-533608455

**Comment by topotropic** [comment]
In the latest nightly (Wednesday 1/8) it just quits the app immediately when I use the Android back button. 

I don't think I understand the explanation here https://github.com/mozilla-mobile/fenix/issues/4517#issuecomment-533608455 but if it's easier to send people to home, we can also keep that for now and exclude history or bookmarks view from the stack

**Comment by darkwing** [comment]
When I swipe back, I see the home screen as described in original bug.

**Comment by topotropic** [comment]
We want to review the menu structure and consider breaking "Library" up into "Bookmarks" and "History" so that you can navigate directly to bookmarks or history – and the current implementation isn't a show stopper. Let's wait for the decision on the menu structure before we pick this up again.

**Comment by topotropic** [comment]
This is expected behavior – the library view(s) isn't part of the stack and we ignore it when navigating back.

**Comment by htsmi** [comment]
Perhaps it is an expected behavior, but I've found this to be a major UX regression compared to Fennec. Previously I could check on several sites in a bookmarks folder while navigating back to the folder by hitting the back button. Now the same task requires many more taps, especially when I am several folders deep in my bookmarks, and by the time I get back to the folder I usually forget where I was in the list.

This combined with the lack of instant access to bookmarks on the new tab/edit URL page (#1487 seems to be closed without addressing this) and bookmarks always creating a new tab (#13336) makes the whole experience feel clunky and has me staying with Fennec as long as I can manage.
