### ISSUE TITLE
Implement Alert Page Template and Update Alerts

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#5892]
This work has carried over from the MVP. This ticket should cover implementing these template for alerts and then updating the various alerts to use it.

Designs here:
Low risk: https://mozilla.invisionapp.com/share/P8UB1E9Y5N4
Medium risk: https://mozilla.invisionapp.com/share/ZYUB1FDT9MR
High risk: https://mozilla.invisionapp.com/share/SHUB1FV2AF6

### Acceptance Criteria
- Create error fragment similar to crash screen (instead of native html)
- Pages work with Top or Bottom nav bar (were hard-coded to be bottom nav bar) and do not require scrolling

### Reference Issues
- Related #5540 - for offline case

**Comment by lime124** [comment]
@brampitoyo worked on this awhile back (I believe). can you dig up the background images? thanks!

**Comment by liuche** [comment]
@boek should this be in the in-progress column? we shouldn't block on the background images.

**Comment by brampitoyo** [comment]
@boek @liuche You can find all the illustrations in this folder: https://drive.google.com/drive/folders/1-wBh9AB9bYmPxIn5tfmvo57UchBRsGeS (`Ω Archive` contains out of date illustration). Each illustration is numbered.

Refer to this A-C Errors document (https://docs.google.com/spreadsheets/d/1SIAm3XZz5uGOm39rAR1hcCje7XYOfqqfSkxnXWttBeU/edit#gid=1453201767) to know which illustration (column G) goes with what message (column J)

**Comment by lime124** [comment]
sean needs to provide some new illustrations based on updated branding guidelines. if this is picked up before those are provided, please use the one's bram mentioned above and ping me so we can get those to you.

**Comment by vesta0** [comment]
We need to prioritize making sure this works well with top nav.

**Comment by liuche** [comment]
We're concerned that asking GV for an API to expose injecting images might take a while, considering the other work that GV is working on.

We'd like to collaborate w/ AC on this.

**Comment by sblatz** [comment]
This is probably more like an E5 instead of an E8 since we won't be completely reworking these into fragments.

**Comment by sblatz** [comment]
For QA: a great website to test this is `badssl.com`

**Comment by sv-sdeiac** [comment]
Hi, I checked this matter on the latest **`Nightly Build #20370604 from 2/6`** using a Google Pixel 3 XL (Android 9) and Google Pixel 3 (Android Q).

@lime124 & @brampitoyo - I would kindly ask you to review and share your thoughts on the bellow error pages with the corresponding templates. 
Due to the fact that the designs don't cover all the possible 

if I missed or overlooked any sure if the correct illustrations

<details>
    <summary>Low Risk (dropdown with screenshots)</summary>

• Crash content 
![rsz_screenshot_20200204-171751](https://user-images.githubusercontent.com/51314259/73761464-91bd3d00-4777-11ea-8aa9-6f30f8150603.png)

• Redirect loop
![rsz_screenshot_20200204-171834](https://user-images.githubusercontent.com/51314259/73761659-d1842480-4777-11ea-80cd-ac6b104e8015.png)

• Website can't be reached
![rsz_screenshot_20200204-171940](https://user-images.githubusercontent.com/51314259/73761842-1019df00-4778-11ea-9c84-cda78976e874.png)

• Address not found
![rsz_screenshot_20200204-172201](https://user-images.githubusercontent.com/51314259/73762183-80286500-4778-11ea-910a-8c09652bc9db.png)

• Connection interrupted
![rsz_screenshot_20200204-172237](https://user-images.githubusercontent.com/51314259/73762289-ab12b900-4778-11ea-94e9-91c8b2d72fa4.png)

• Unknown protocol
![rsz_screenshot_20200204-172340](https://user-images.githubusercontent.com/51314259/73762529-fa58e980-4778-11ea-92b5-ab11fcd626de.png)

• No internet connection
![rsz_screenshot_20200204-173403](https://user-images.githubusercontent.com/51314259/73762715-2bd1b500-4779-11ea-8461-9e85806c0631.png)

</details>

<details>
    <summary>Medium Risk (dropdown with screenshots)</summary>
   

• Expired invalid SSL
![rsz_screenshot_20200204-172432](https://user-images.githubusercontent.com/51314259/73763368-01342c00-477a-11ea-81ca-7a496a1c21e8.png)

</details>


<details>
    <summary> High Risk (dropdown with screenshots)</summary>
   
• Phishing
![rsz_screenshot_20200204-172832](https://user-images.githubusercontent.com/51314259/73763014-89660180-4779-11ea-8361-2b16969b3b63.png)

• Unwanted software
![rsz_screenshot_20200204-172930](https://user-images.githubusercontent.com/51314259/73763139-b1556500-4779-11ea-9beb-1832fd87ecc2.png)

• Malware
![rsz_screenshot_20200204-172856](https://user-images.githubusercontent.com/51314259/73763280-e19d0380-4779-11ea-9041-f38636a72e3e.png)

</details>

**Comment by sv-sdeiac** [comment]
Removing the qa:needed until we have more information, thanks.

**Comment by sblatz** [comment]
I'm fixing a bug in AC that makes it so we're swapping the placeholder text for "high risk" error pages: https://github.com/mozilla-mobile/android-components/pull/5879

I also improved the link break as discussed with @brampitoyo.

Once this AC fix is in, I think we'll be able to close this 😄

**Comment by brampitoyo** [comment]
The design decision is documented on https://github.com/mozilla-mobile/fenix/issues/8215#issuecomment-583961419

**Comment by sblatz** [comment]
I'm going to close this as these designs match expectations set by @brampitoyo and I during AllHands :)
