### ISSUE TITLE
Investigate Depedency Injection Options

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#59]
Several of our existing project use Java static singleton classes to make app functionality available. This frustrates effective testing and makes it harder to utilize inheritance over composition.

We should consider dependency injection options to find something simple that won't significantly harm performance or cause needless boilerplate or pain for developers adding new features.

**Comment by colintheshots** [comment]
My initial investigation has shown that dependency injection is traditionally a very Java problem. It's a much harder problem in the Java world than with Kotlin. Adding inlining, class and property delegation, and reified types means that Kotlin can address many of the same problems without the horrific overhead of code generation and annotation processing or reflection.

I propose that we look into using Koin for dependency injection with Fenix and other mostly Kotlin projects. Alternatively, Kodein is very similar to Koin.

**Comment by csadilek** [comment]
I think we should consider not using a DI framework/library at all. Having spent years implementing a CDI container, and even more using EJB, Spring, then Dagger, I am no longer convinced that the benefits outweigh the complexity and performance costs. I'm also not excited about the lock-in this ultimately creates.

I'm all for DI and IoC, but don't think we necessarily need a library for it. Why is it not enough to provide constructors (in preferably immutable types) that accept all required dependencies? The manual work involved here is minimal and these types are easy to unit test.

I'm not arguing against investigating DI library options, and certainly not defending the singletons :). I just prefer our default position to be: Let's not use a DI library until we're convinced of it's long-term benefits. If the problem comes down to designing a bootstrap mechanism to prevent automatic creation of singletons then I would prefer doing that anyway, even if we end up using a DI framework.

**Comment by bbinto** [comment]
Any news, udpates on that? 
Size? Urgency? Milestone?

**Comment by colintheshots** [comment]
I think we'll skip this. One of our project goals is around app startup time. DI makes testing much easier, but it may result in a significant penalty on cold startups.
