### ISSUE TITLE
[Meta] Review settings organization

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#5905]
Let's review the settings screen and see where we can improve/consolidate as we add new items to it.

@apbitner @lime124 
- [x] Pre-land strings
- [x] Revisit Privacy Settings items #5619

[UX Spec](https://share.goabstract.com/ee40800d-4b36-49d5-8a5b-a89f8ab21141?mode=design&sha=6e82c52070e76eb62b1e8511710296a22ed87cd7)

**Comment by sblatz** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/5619

**Comment by brampitoyo** [comment]
@AmyYLee @apbitner @lime124 Once we size and MuSCoW this issue, let’s remove the needs:UX-feedback label.

**Comment by cadeyrn** [comment]
@sblatz said in #6559:

> That being said, UX is considering re-organization of this toolbar menu, perhaps this feedback is better situated there: #5905

So I want to repeat my feedback from the closed issue:

> After the removal of the QAB there is no longer a back button in the menu making it impossible for me to use Fenix with one hand (in most cases).

---

Unfortunately most smartphones today are really big making it impossible for some people to reach the bottom left of the smartphone with the right hand - including the back button of the device. But with Fenix you was able to navigate back with only only one hand before the removal of the QAB - this was a really big advantage of Fenix compared to other browsers like the old Firefox or Chrome. Now this advantage is gone.

**Comment by brampitoyo** [comment]
Now that this issue has been sized and prioritised, I’m removing the needs-ux label.

**Comment by cadeyrn** [comment]
Related: #7188

**Comment by AmyYLee** [comment]
The UX spec has been posted in comment 0 for the new Settings reorg. Let me know if you have any questions.

**Comment by abodea** [comment]
Hello, as we have the `Add-ons` now in settings it is under the `Advanced` section that based on the most recent UX specs should be deleted.

Also, the `Open links in apps` option are missing from the UX specs but in the latest Fenix Nightly from 2/12, it's under the `Privacy and security` section.
@vesta0 @AmyYLee should I open a new bug for those from above?
Is the `Open links in apps` option in the right place? As it's missing from the specs.

Note that the rest looks ok, but I will verify the bug after we will clarify with the questions from above.

**Comment by cadeyrn** [comment]
May I suggest another change? In Fenix Nightly there is also a LeakCanary toggle in the privacy and security section (it's not in the UX spec at all). It does not really have anything to do with privacy or security. I guess the developer or advanced section is a much better place for this toggle.

**Comment by AmyYLee** [comment]
> Hello, as we have the `Add-ons` now in settings it is under the `Advanced` section that based on the most recent UX specs should be deleted.
> 
> Also, the `Open links in apps` option are missing from the UX specs but in the latest Fenix Nightly from 2/12, it's under the `Privacy and security` section.
> @vesta0 @AmyYLee should I open a new bug for those from above?
> Is the `Open links in apps` option in the right place? As it's missing from the specs.
> 
> Note that the rest looks ok, but I will verify the bug(and modify the labels accordingly) after we will clarify with the questions from above.

Hi, 

@abodea The "Open links in apps" should be located here (see screenshot). This is part of issue #3177 and the full UX spec can be found in comment 0. Let me know if you have any questions.

<img width="1138" alt="Screen Shot 2020-02-12 at 12 01 11 PM" src="https://user-images.githubusercontent.com/5992746/74378968-e33b7c80-4db4-11ea-8060-650ca949ac0b.png">

**Comment by AmyYLee** [comment]
> May I suggest another change? In Fenix Nightly there is also a LeakCanary toggle in the privacy and security section (it's not in the UX spec at all). It does not really have anything to do with privacy or security. I guess the developer or advanced section is a much better place for this toggle.

The "advanced" section was initially removed because we did not have more than 1 item (language) in the section. As part of the reorg of settings, "basic" was renamed to "general" and language was moved into that section. If we end up having more than 1 "advanced" item then we could possibly bring back "advanced" as a section which could also cover developer tools. I would let @brampitoyo make the final call.

**Comment by brampitoyo** [comment]
@cadeyrn I agree with @AmyYLee. Let’s hold off on making any change until we know we have multiple items under “Advanced”.

**Comment by abodea** [comment]
Hello, @AmyYLee thank you for the response.

Note that in the description where you posted the [UX specs](https://github.com/mozilla-mobile/fenix/issues/5905#issue-504909257) the photo you uploaded [above](https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-585427769) is not displayed.

I added this [bug ](https://github.com/mozilla-mobile/fenix/issues/8380) as the `Prevent websites from opening links in external apps` is not in the right place.
Based on your picture from [here](https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-585427769) should the following icon be gone from the  `Prevent websites from opening links in external apps`?
![download (2)](https://user-images.githubusercontent.com/42831109/74435848-0a09b980-4e6e-11ea-9b8c-5073aaced6a6.png).

>AmyYLee commented 15 hours ago
As part of the reorg of settings, "basic" was renamed to "general" and language was moved into that section. If we end up having more than 1 "advanced" item then we could possibly bring back "advanced" as a section which could also cover developer tools.

Please note that the `Advanced` section is back with the `Add-ons` section, is this intended? 
If we keep in mind that `Language` was in advance before and moved because it was the only one, now we can say that we have two menus for advanced.
Should `Add-ons` be moved in another section?

![Screenshot_20200213-143802_Firefox Nightly (1)](https://user-images.githubusercontent.com/42831109/74436486-383bc900-4e6f-11ea-8026-f9c8f4410968.jpg)

**Comment by AmyYLee** [comment]
> Hello, @AmyYLee thank you for the response.
> 
> Note that in the description where you posted the [UX specs](https://github.com/mozilla-mobile/fenix/issues/5905#issue-504909257) the photo you uploaded [above](https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-585427769) is not displayed.
> 
> I added this [bug ](https://github.com/mozilla-mobile/fenix/issues/8380) as the `Prevent websites from opening links in external apps` is not in the right place.
> Based on your picture from [here](https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-585427769) should the following icon be gone from the `Prevent websites from opening links in external apps`?
> ![download (2)](https://user-images.githubusercontent.com/42831109/74435848-0a09b980-4e6e-11ea-9b8c-5073aaced6a6.png).
> 
> > AmyYLee commented 15 hours ago
> > As part of the reorg of settings, "basic" was renamed to "general" and language was moved into that section. If we end up having more than 1 "advanced" item then we could possibly bring back "advanced" as a section which could also cover developer tools.
> 
> Please note that the `Advanced` section is back with the `Add-ons` section, is this intended?
> If we keep in mind that `Language` was in advance before and moved because it was the only one, now we can say that we have two menus for advanced.
> Should `Add-ons` be moved in another section?
> 
> ![Screenshot_20200213-143802_Firefox Nightly (1)](https://user-images.githubusercontent.com/42831109/74436486-383bc900-4e6f-11ea-8026-f9c8f4410968.jpg)

Hi, 

Yes with the new location we don't need the icon for "Prevent websites from opening links in external apps". 

I'm wondering if "Developer tools" header can be removed and "Remote debugging via USB" can be moved into the "Advanced" section where "add-ons" is. I would keep "Language" in the "General" section. @brampitoyo is the owner of settings so I'll let him make the final call if he agrees.

**Comment by brampitoyo** [comment]
@abodea I agree with @AmyYLee:

- Remove “Developer tools” heading
- Move “Remote debugging via USB” to belong under “Advanced”. This item should be put below “Add-ons”.

**Comment by cadeyrn** [comment]
@brampitoyo Can the LeakCanaray item moved from "Privacy and Security" to "Advanced" then?

**Comment by brampitoyo** [comment]
@cadeyrn Is LeakCanary the library that we use to detect memory leaks?

Do you know what the menu item will be called? I assume that release users won’t see this, correct? Only Nightly and maybe Beta.

Yes. If that’s the case, then it should belong under “Advanced”.

**Comment by cadeyrn** [comment]
> Is LeakCanary the library that we use to detect memory leaks?

Yes!

> Do you know what the menu item will be called?

It's called "LeakCanary" and it's a toggle like the item for external debugging.

> I assume that release users won’t see this, correct? Only Nightly and maybe Beta.

I don't know about Beta but yes, it's in Nightly and release user don't see this option.

**Comment by abodea** [comment]
Thank you @AmyYLee and @brampitoyo.
Based on the comments from above I have added two new issues:
 - [Bug] Add "**Remote debugging via USB**" and "**LeakCanary**" under Advance option in settings #8485
 - [Bug] Add "**Prevent websites from opening links in external apps"(previous Open links in apps**" under General in "set as default browser" option #8486
Note that I added the reference to this issue, once I will verify those two I will close this issue as well.

Also, regarding LeakCanary, I'm not sure if it will be present/visible in Nightly/Beta/RC. From what I've seen it was present only on the debug builds. @boek can you please help us with this?

I will let `eng:qa:needed` until I will confirm the latest two issues and then I will verify this one too as everything will be done.

**Comment by danielzgtg** [comment]
I would like to bring up the feedback in a related closed issue, #8083. It is also about the back button but is about another use case of it.

I used to be able to long-press back/forward to get the history of the current tab. After my Firefox Nightly upgraded to fenix, this got broken.

Now I am unable to take back control from websites that like to intentionally redirect me around in an attempt to trap me there. This often happens when a malicious ad is loaded and sends me to pages that use scripts to spam the back stack to crowd out the site I wanted to stay on.

Using the device back button is not a solution. After pressing back on these sites, the previous page will push an even longer chain of URLs onto the history stack. The only way to get out of this situation is to long-press back right after it happens, scroll down to the last good website, and tap there. This security feature was one of the main reasons I switched to Firefox for. Now I am only able to get out after pressing the back button for minutes and hoping the hosting provider runs out of bandwidth.

**Comment by brampitoyo** [comment]
@danielzgtg I’ve reopened #8083, renamed it to suit our problem, and put your comment there.

Note that the final design may not be in the form of a long-press back button, but it will solve your malicious redirect problem.

Also note that History is a page that’s already easy to access from the main menu. With it, you can go back several pages into the stack (although the history presented is of _all_ tabs, not just for any specific tab).

**Comment by abodea** [comment]
Hello, @brampitoyo @AmyYLee I will remove the `Eng:QA:Needed` label until the bugs https://github.com/mozilla-mobile/fenix/issues/8485 https://github.com/mozilla-mobile/fenix/issues/8486 will be fixed. 
Note that I added those regarding your feedback on how the settings menu should be.
See more details here https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-587517223

**Comment by vesta0** [comment]
Will track #8485 separately :)
