### ISSUE TITLE
[Bug] leaving a PWAs scope transforms activity into custom tab

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#5907]
## Steps to reproduce
Click a link inside a PWA which takes the user to a page outside the PWAs scope.

### Expected behavior
This should actually behave like in a native app and similar to how it works in Fennec right now. If the navigation sends the user out of the PWA, a new custom tab intent should be created.

### Actual behavior
Transforms the current PWA activity into a custom tab.

### Device information

* Android device: 7.1.1
* Fenix version: 191909 06:01 (Build #12820612)

**Comment by liuche** [comment]
@NotWoods could you link to mocks or explain the rationale behind this behavior?

**Comment by NotWoods** [comment]
We chose to show/hide the toolbar view rather than launch a new activity so that we can handle various cases with navigation.

When the user returns to the original scope, we need to hide the toolbar again. Additionally we want to show the toolbar if validation fails in a Trusted Web Activity. 

We didn't see any benefit to launching a new task and managing that lifecycle complexity over just revealing a view and creating a similar effect. I believe other browsers do the same.
