### ISSUE TITLE
Consider adding default share sheet as an option & separate send tab

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5935]
To guide this decision, we should investigate telemetry of: 
* how often "share tab" happens in share sheet
* how often users click "sign in" from share sheet

If we are going to keep these together, we should likely add more custom UI that creates more of a value add for the trade off we're making here.

We could consider breaking "send tab" out into a separate button so that we can use the default share sheet and all of its optimizations :)

**Comment by vesta0** [comment]
When investigating this ticket, please consider the previous investigation documented here #4275

**Comment by jonalmeida** [comment]
I think this issue is a no-op as vesta mentioned. We've already spent time investigating the advantages of the native sheet and they do not hold up for what we want to accomplish. See https://github.com/mozilla-mobile/fenix/issues/4275#issuecomment-521812582.

**Comment by sblatz** [comment]
Let's look at the data around this--how many users are being onboarded to FxA through the share sheet, etc. 

Why we should consider adding the default share sheet back:
- It has hooks into "smartly" choosing where to share things (send a message to X person), etc.
- The share sheet will only get better over time
- We should adopt system standards whenever possible.

**Comment by cassidyjames** [comment]
My opinion as a single user might not matter a whole lot, but I am thrown off every time I go to share a page and get the custom share sheet instead of the OS one. The behavior is different, the scroll direction is different, the sorting is different, and the supported features (i.e. exposing direct share items) is different. I understand that on Android 9 and earlier the share sheet was not the most performant, but on Android 10 it is great and I love that it's extremely fast to send things to my frequent/recent conversations and apps. I miss that every time I'm in Fenix.

**Comment by xcffl** [comment]
IMO send tab and login buttons can be implemented as direct share items, which has similar functionality as the current customized one, but is more standard and has a lot of built-in effects.
The only issue might be the compatibility on older Android systems. Direct share menu wasn't implemented elegantly (e.g. items jump until everything is loaded).

**Comment by kevincox** [comment]
Please! The custom share sheet really pales in comparison to the native one. It seems that the main blocker is sharing tabs but I would still prefer the native share sheet if I needed to do something more complicated to share tabs. 

The suggestion to implement Send Tab as a regular share target sounds amazing as I would often like to share from other apps to my desktop and it is a little awkward because it currently isn't exposed as a share target. 

It seems that one of the other concerns is that if the with expires, but maybe we can consider just raising a notification when this happens and the user can fix this outside of the share sheet. Or when sharing from within firefox the auth could be checked before opening the share sheet. Or possibly better just wait until the user selects the Send Tab share item then ask them to log in. Of course we would need to check all of the reasons that this auth check is required.

**Comment by liuche** [comment]
This is a good thread! We'll plan to address this in #14926
