### ISSUE TITLE
On home page, "Current Session + 3-dot" feels unbalanced

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#600]
## Steps to reproduce
- Visit homescreen

### Expected behavior
"Current session", "+", and 3-dot element feel balanced

### Actual behavior
They feel unbalanced, the whole row feeling almost "left aligned":
![screenshot_20190220-150222](https://user-images.githubusercontent.com/759372/53131315-4f2c3180-3521-11e9-9eeb-a34ff0349026.png)

The "Current Session" feels too far to the left and the menu button doesn't feel far enough to the right. I think this is because of the curve of the current session thumbnail: "Current session" aligns with the left edge but perhaps should align with the end of the curve of the rounded corners. The menu button also feels out of place but I don't have a good reason why (maybe just because Current Session is off). Here is an annotated version with a line where these views might better align:

![screenshot_20190220-150222](https://user-images.githubusercontent.com/759372/53131303-4176ac00-3521-11e9-8d1c-b31c4db06159.png)

### Device information

* Android device: Pixel 2
* Fenix version: 1.0.1908

**Comment by kbrosnan** [comment]
This is still true of the tabs UI using the April 29th build.

**Comment by cadeyrn** [comment]
The private browsing home screen is also affected and because there is text below the "open tabs" caption the alignment issue is a bit more obvious.

**Comment by cadeyrn** [comment]
Attaching a screenshot to demonstrate that the alignment of all the things on the private home screen is totally arbitrary.

<img width="773" alt="fenix2" src="https://user-images.githubusercontent.com/1100614/59269819-32427800-8c50-11e9-9c1f-260ea3d474f8.png">

**Comment by lime124** [comment]
i think the first thing to do here is to make sure the app UI matches the specs provided.

@AmyYLee you can take a look at the private browsing screenshot. if it's not to spec can you add it to the implementation checklist please. otherwise please create a new issue for our team to address.

we'll hold off on the homescreen comment as that's being examined as part of a larger ux effort. if it's not to spec we'll catch it and fix it. thanks!

**Comment by topotropic** [comment]
We restructured the home screen slightly (moved search bar and + to bottom bar) and it looks alright now. There are also explorations to move the open tabs to a dedicated tab tray, so we don't need to invest work here imo. 

On private mode, it would be nice if we can re-position the body copy starting with "Firefox Preview clears your..." so that it aligns with the header "Private session"

**Comment by AmyYLee** [comment]
> i think the first thing to do here is to make sure the app UI matches the specs provided.
> 
> @AmyYLee you can take a look at the private browsing screenshot. if it's not to spec can you add it to the implementation checklist please. otherwise please create a new issue for our team to address.
> 
> we'll hold off on the homescreen comment as that's being examined as part of a larger ux effort. if it's not to spec we'll catch it and fix it. thanks!

@lime124 Hi, I've created a new implementation checklist for PBM
https://github.com/mozilla-mobile/fenix/issues/6629

**Comment by topotropic** [comment]
can we close this issue @AmyYLee ?

**Comment by AmyYLee** [comment]
Closing issue since edits for PBM will be tracked in #6629 and this is no longer relevant for homescreen in none PBM based on feedback from @topotropic above.
