### ISSUE TITLE
[Telemetry] Choosing top nav bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6054]
#### Description & Product Manager / Data Scientist User Story
- As a product owner, I want to know if users prefer a top nav bar. 

#### What questions will you answer with this data?
- How often users choose a top nav bar. If more than 20% of users choose top nav bar (without surfacing this option during onboarding) then we will investigate (through user research or otherwise) whether we need to consider changing the default. 

#### What probes (suggested, if applicable)
- user chooses "top" toolbar in settingws

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by blikblum** [comment]
Long time Firefox (Desktop and Mobile) here.

This week just tried Firefox Preview and after a few moments using it, i switched back to Firefox Mobile because i could not get used with the navbar on bottom (years and years using navbar on top).

Waiting for the 3.0 version, with ability to set top navbar, be available on Play Store to try Preview again.

You could expose somehow this option on onboarding, even with default as bottom, to make easier to users switch if desired.

**Comment by vesta0** [comment]
Thanks @blikblum that is very helpful feedback. We will look into how we can surface this during onboarding.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13310607 from 11/27** using a Google Pixel 3a (Android 9)

✔️ Choose Top - Ping b9d07a3a-1d11-4fcc-aad0-fa23ea25fe31
✔️ Choose Bottom - Ping a299a6a2-7dcd-418a-b4d5-2ece2288ce87

[Logcat](https://github.com/mozilla-mobile/fenix/files/3897560/toolbar.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t271100)
