### ISSUE TITLE
Adding screen timeout option or at least option for blocking locking screen

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6086]
### Why/User Benefit/User Problem
Android allows for setting screen timeout (generally time after which screen is disabled and keyboard is locked), but many readers have option for disabling it (which is useful when you don't do anything for longer time because you're just reading).

### What/Requirements
I propose adding general option, which will have settings: 

system setting
1 minute
2 minutes
3 minutes
5 minutes
10 minutes
infinite time

User should be able to select the most convenient time.

### Acceptance Criteria (how do I know when I’m done?)
Availability of option in the application which is blocking screen blocking by system after specified inactivity time.

**Comment by kbrosnan** [comment]
Feature requests need to go through Product and UX review.

**Comment by marcinwiacek** [comment]
Dear @kbrosnan ,

@ekager closed #7520 , can I ask if it went over review or was it closed without anything?

**Comment by ekager** [comment]
@marcinwiacek we did discuss this in a meeting and I closed your PRs because they were unsolicited and we don't land random features we don't ask for. 

I'm going to explain this one more time.

We cannot take unsolicited PRs for features you come up with alone. That is not how our product and team works. Every added feature needs product/UX/content decisions. Just because you have already written the code doesn't mean that it's not any work for us. Reviewing the code takes eng resources. Having UX review the final product and make changes takes UX resources. Having product look over the new feature and figure out if we need telemetry, marketing, etc takes resources. Having our content team come up with strings for the new UX takes resources. 

I understand you are frustrated that this feature request has been open since October, but there are features and issues that have been open longer or are higher on our priority list right now that more than just you personally want and this needs to wait. If you are interested in contributing code immediately please look at our "help wanted" issues.

**Comment by marcinwiacek** [comment]
It was enough to write "we notified it in our team, but decided not to process and it was closed".

I don't have push for committing code to this project, if project drops all commitment tries (even simple), then situation is clear & there are 3 potential reasons - either I didn't follow your rules (I don't think so, I really went over info from https://github.com/mozilla-mobile/fenix, but maybe...), or you don't want code or thing is personal.

Shame and peace.
