### ISSUE TITLE
Open Link in New/Private Tab does not switch to the tab

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#612]
The tabs are created but we do not switch to them. If staying on the current page is the intended behavior (I would love this to be configurable with a setting) then I think we should consider introducing the same snackbar that Fennec has.

![screenshot_20190220-223243](https://user-images.githubusercontent.com/28052/53141833-a224d980-355f-11e9-846b-2bbf2dbc3566.png)

**Comment by buttercookie42** [comment]
> If staying on the current page is the intended behavior (I would love this to be configurable with a setting) then I think we should consider introducing the same snackbar that Fennec has.

My preference is for the current Fennec behaviour and I think that the snackbar should available even if this is made configurable (or as an option in its own right):
The reason is that I think the desired behaviour can be rather context-dependent. I.e. sometimes I want to open a few tabs in the background for a little later (in which case switching to the new tab would be rather annoying), but sometimes I do indeed want to switch to the new tab right away. Therefore, being able to decide this on the fly (instead of only being able to change this through some hidden configuration menu) would be very valuable.

**Comment by buttercookie42** [comment]
It looks like #1293 would take care of this?

**Comment by vesta0** [comment]
Will address this in #1293
