### ISSUE TITLE
Show progress bar when page is loading

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#619]
As a user, I want to see progress bar when I am loading a page, so I know that the page is loading.

### Acceptance Criteria:
I can see the progress bar when I lick on a link on a page (with the URL bar collapsed).

**Comment by pocmo** [comment]
@brampitoyo What's the expectation here? Should a load process always reveal the whole toolbar. Or just the loading bar? Do we have mocks schowing the loading process?

**Comment by thanuj10** [comment]
Just a loading bar is fine. The whole toolbar just takes up screen space, A simple load bar at the bottom will suffice.

**Comment by mheubusch** [comment]
@shorlander can you please advise on behavior here. once you do, please remove thee Needs UX Feeedback label

**Comment by shorlander** [comment]
When are loading a page we should show the toolbar and the loading bar the way we currently do in Fennec.

**Comment by adiron** [comment]
I was about to open an issue for the same, so definitely a +1 from me. :)

As for the desired behavior, I'm with @thanuj10 on this one: showing a progress bar is fine. Showing the entire toolbar isn't that helpful

My reasoning is that the heart of the issue is needing assurance that my clicks _did_ in fact work. Unfortunately, the dotted outline and whatever the website set for `:focus`/`:active` don't cut it for some reason (maybe it changed something out of my viewport, maybe it doesn't work, maybe I didn't actually tap it right, etc.). It's been driving me insane 😝

**Comment by mheubusch** [comment]
@shorlander can you please advise on behavior here. once you do, please remove the Needs UX Feedback label

**Comment by vesta0** [comment]
I believe we have the following direction from @shorlander 

When are loading a page we should show the toolbar and the loading bar the way we currently do in Fennec.

**Comment by SorinaFlorean** [comment]
Works as expected on Nexus 5(Android 6.0.1). 
Build: 4/24
