### ISSUE TITLE
When user adds bookmarked page to collection, use bookmark text as collection label

### ISSUE THREAD

**Issue by narzb** [mozilla-mobile/fenix#6243]
## Steps to reproduce
Put a bookmark page in a collection 
### Expected behavior
The displayed titles should be titles set in bookmarks
### Actual behavior
The displayed titles are the names given by the site to the page
### Device information

* Android device: 9
* Fenix version : 2.2

### Design Work
- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~
- [ ] ~Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed~
- [x] Interaction details included
- [x] Accessibility ~- is this a review by someone,~ just keeping it in mind?
- [ ] ~For existing UI changes, deltas are highlighted~
- [ ] ~Strings/content reviewed and approved~
   - [ ] ~Are they too long for the component in other locales~

### Deliverable
- [ ] ~Assets uploaded to Google Drive~
- [x] Links to deliverables (spec, assets) posted in comment 0 – see below

### Interaction details
When a bookmark is put inside a collection, the collection title should use the title of the bookmark, and not the title given by the site.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14107)

**Comment by brampitoyo** [comment]
I’m assigning @topotropic to this issue, because she has been working on bookmarking and collections.

Nicole, the question in this issue is fairly simple, and I think you can help answer it:

1. When I bookmark a webpage, Firefox takes its page-name and use it as the default bookmark name
2. I can change the bookmark name to whatever I wish
3. I then put this bookmark in a collection

Question: when a custom-name bookmark name is put in a collection, will the collection use this custom-name, or will it use the default page-name?

**Comment by topotropic** [comment]
It makes sense to re-use the custom title for the page, because the user updated it once and you can't update titles of sites you save to a collection. 

That said, it also depends on how complicated it is to implement and how many people are actually updating titles – up to PM.

**Comment by brampitoyo** [comment]
Updated comment 0 with interaction details.
