### ISSUE TITLE
[Bug] LeanPlum initialization is accidental; not explicit

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#6251]
Leanplum docs suggest initializing the LP singleton in the Application onCreate. However, this is happening in the Leanplum Metrics class [accidentally in a non-explicit way](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L75).

If telemetry is disabled, Leanplum is never initialized for metrics **but also push messaging** and also lead to future problems.

**Comment by jonalmeida** [comment]
With LP push support in #7906 landing soon, this bug will become more noticeable.

**Comment by Mugurell** [comment]
I think we want to have Leanplum enabled only if telemetry is enabled.
Otherwise, with telemetry disabled we should have no data to be used for mma, we could not decide to which user segment to send different notifications.

I think this is now explicit in code whereas at the time of this ticket [Leanplum was enabled without any check](https://github.com/mozilla-mobile/fenix/blob/8c30200ced8e60756829518170fc8e53e3eb650b/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L75) in the meantime I see [a `marketingTelemetryEnabled` condition has been added](https://github.com/mozilla-mobile/fenix/blob/41a92a8d8b316446e21a2fc8a6eadec43e6f4799/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L84) even after [a `isTelemetryEnabled` check](https://github.com/mozilla-mobile/fenix/blob/b8de7079a963efb140ed318d876f23a17a0e3d9e/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt#L96) done for both the start and stop methods of the metricController.

Because of this I don't think there is anything to do here at this time.
Asking @boek for a second opinion.

**Comment by jonalmeida** [comment]
Turnings LeanPlum off if telemetry is disabled will also disable Leanplum marketing push notifications. Is that our expectation?

If yes, then yes, we can close this ticket.

**Comment by boek** [comment]
that is true. Lets close this
