### ISSUE TITLE
[Bug] Alert Page Error State Content and Illustrations

### ISSUE THREAD

**Issue by jpfaller** [mozilla-mobile/fenix#6256]
This work has carried over from the MVP. This ticket should cover a content and UX review of the content and illustrations for alerts.

A review to bring the illustrations current with accepted style and to shorten / clarify strings is needed.

Note: Most recent content updates by @mheubusch are in the XML files.

Content Matrix here:
https://docs.google.com/spreadsheets/d/1SIAm3XZz5uGOm39rAR1hcCje7XYOfqqfSkxnXWttBeU/edit#gid=1453201767

Designs here:
Low risk: https://mozilla.invisionapp.com/share/P8UB1E9Y5N4
Medium risk: https://mozilla.invisionapp.com/share/ZYUB1FDT9MR
High risk: https://mozilla.invisionapp.com/share/SHUB1FV2AF6

Acceptance Criteria
Content and illustrations meet brand guidelines and are mobile friendly

Reference Issues
#5540 - for offline case
#5892 - Updating Templates
#3910 - Adding way to view page despite an site error

**Comment by Baron-Severin** [comment]
Hey @mheubusch, do you know when these strings need to be landed?

**Comment by liuche** [comment]
Talked this over w/ Tif, and it looks like this is still in progress (and has some Fennec strings).

For Content (@mheubusch @jpfaller), could we also get:
- Headings for what each column means? (there seem to be multiple strings)
- When strings are getting finalized, using the %1$s format for the placeholders (so that we can just copy paste when we use the string).

**Comment by vesta0** [comment]
@liuche @lime124 is this done or hasn't been picked up?

**Comment by liuche** [comment]
I think this is done, we have error page strings and images in AC #5892
