### ISSUE TITLE
avoid shipping unlocalized strings

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6262]
Firefox Preview 2.2 was not the first stable release of Fenix which shipped with untranslated strings ("open links in a private tab"). Side note: The same happens with Fennec, Firefox 68.2 was released with untranslated strings, too.

Shipping untranslated strings gives always the impression of an unfinished product and should be avoided in stable releases. Unfortunately I can't make any concrete suggestions how to avoid this in the future but I wanted to log an issue so that it appears on someone's radar. :)

**Comment by liuche** [comment]
This is an ongoing effort for us, thanks for raising this! We try to give our localizers 2 weeks to do localization, but sometimes people don't have time (which is okay) or we need to make last-minute changes to the strings.

Moving forward, we'll also be adding an extra 2-week beta channel in between Nightlies and Release, so that should also give extra time for localization (starting around December).

As an aside, there's been localization research that shows that people would rather have the feature, even partially localized, rather than have than wait for full localization.

I'm going to close this for now, but please feel free to open/comment if you see places for more concern!
