### ISSUE TITLE
[Bug] [Crash] IllegalStateException: it.campaign must not be null

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#6344]
This started yesterday and is our top crash now in Nightly:
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6564461/

**Comment by csadilek** [comment]
Ah @sblatz, looks like this commit removed the null check: https://github.com/mozilla-mobile/fenix/commit/2a358db56189c5efcf796cb55bb8a3ec9c1968c2#diff-1e58c877c8ba0f1703519133669e926aR38

**Comment by sv-ohorvath** [comment]
@sblatz Do you have some STR for this?

**Comment by sblatz** [comment]
@sv-ohorvath this was happening when we were not properly sending the campaign info for Adjust. This has been addressed in my PR's: https://github.com/sblatz/fenix/commit/7eba3e993ce97905d4375777cfc0930e47f90167 & https://github.com/mozilla-mobile/fenix/pull/5896

Since this Sentry crash has reached 0 reports, I don't think we need QA verification on this 😄
