### ISSUE TITLE
[UX] Education & Discovery of TP exceptions list

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6375]
## User Story
- As a user, I want to know that I can allow tracking/ads from an specific site by toggling off ETP, so I can control how I view trusted sites. 

### Acceptance Criteria
- When I toggle off TP on a site, I learn that the site has been added to my exceptions list
- I know how to allow tracking/ads from a trusted a site

Potentially in scope:
- Heuristics for determining when to show ETP education (in case users are running into problems, similar to how we could show a webcompat dialog if user switches to Desktop mode) - ETP can break sites #5392 [b:etp](https://github.com/mozilla-mobile/fenix/labels/b%3Aetp)

**Comment by lwa-moz** [comment]
@vesta0 Adding some user stories to convey possible changes to the messaging around the TP exception process: 

As a user, I want to be able to understand that ETP may trigger site specific "ad block" warnings, and that by toggling this feature off, I have "whitelisted" the site. The language that is used in the app should be as consistent as possible with the warnings that frequently gate content so I can understand how to respond to these major interruptions.

As a user, I want to be certain that only the specific site has been whitelisted, and not all sites. When toggling ETP off, or from Strict to Standard, I want to be reminded where I can see which sites have been whitelisted, both to double check that the site has been correctly configured, and also to verify what other sites I have whitelisted in the past.

As a user I want to understand that ETP is blocking advertising. In some cases, I want to enable advertising to support the publisher; in other cases I want to suppress advertising because it is invasive. In order for me to make informed decisions, the messaging should be clear that advertising is being blocked. Advertising is generally more top of mind to me than trackers.
