### ISSUE TITLE
Make "Always launch in private mode" more discoverable

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6381]
## User Story
- As a user, I want to know that I can use Fenix to open 3rd party links in private mode by default, so I can take advantage of this feature. 

### Acceptance Criteria
- I know about "launch in private mode" and how it works

**Comment by liuche** [comment]
@AmyYLee should "Open links in Private Mode" be a setting that is also available even if you don't have the browser set as the default? Currently it's greyed out. I know we had the regression for "open with Private Fenix" which originally handled this case, but that was backed out due to #5972 and I don't think we currently have a solution yet.

![Screenshot_20191219-195341~2](https://user-images.githubusercontent.com/1082253/71221167-8ed6bd80-2299-11ea-996a-c737b64ad0f6.png)

**Comment by AmyYLee** [comment]
> @AmyYLee should "Open links in Private Mode" be a setting that is also available even if you don't have the browser set as the default? Currently it's greyed out. I know we had the regression for "open with Private Fenix" which originally handled this case, but that was backed out due to #5972 and I don't think we currently have a solution yet.
> 
> ![Screenshot_20191219-195341~2](https://user-images.githubusercontent.com/1082253/71221167-8ed6bd80-2299-11ea-996a-c737b64ad0f6.png)

@liuche I thought we were only able to set "Open links in private tab" if Fenix was set as a default? If this is not the case then yes we should break these items out into separate toggles. Please confirm and I'll post a mock.

**Comment by liuche** [comment]
Yes, @AmyYLee  that's correct! We can set "open links in private tab" even if Fenix is not the default.

For more context, non-default browser Fenix users will be prompted to select which browser they want to use - we used to show the "open in Fenix PB Mode" but removed it due to #5972. This setting would control what happens when they click "Open with Fenix" - whether it's a Private tab or Normal tab.

**Comment by AmyYLee** [comment]
> @AmyYLee should "Open links in Private Mode" be a setting that is also available even if you don't have the browser set as the default? Currently it's greyed out. I know we had the regression for "open with Private Fenix" which originally handled this case, but that was backed out due to #5972 and I don't think we currently have a solution yet.
> 
> ![Screenshot_20191219-195341~2](https://user-images.githubusercontent.com/1082253/71221167-8ed6bd80-2299-11ea-996a-c737b64ad0f6.png)

@liuche I thought we were only able to set "Open links in private tab" if Fenix was set as a default? If this is not the case then yes we should break these items out into separate toggles. Please confirm and I'll post a mock.

> Yes, @AmyYLee that's correct! We can set "open links in private tab" even if Fenix is not the default.
> 
> For more context, non-default browser Fenix users will be prompted to select which browser they want to use - we used to show the "open in Fenix PB Mode" but removed it due to #5972. This setting would control what happens when they click "Open with Fenix" - whether it's a Private tab or Normal tab.
> 
> ![Screenshot_20191230-104051](https://user-images.githubusercontent.com/1082253/71595429-96079200-2b09-11ea-819a-56bf7fdd4b71.png)

Hi @liuche 

In that case yes let's make "Open links in a private tab" a toggle and not have it be the child. This should also be moved to the "Privacy" section. 

Now that we have a few new privacy items, I think it makes sense to create a new sub screen for "Private browsing" and move items in there. Please see attached mock.

<img width="865" alt="Screen Shot 2019-12-31 at 1 30 53 PM" src="https://user-images.githubusercontent.com/5992746/71630651-1f829700-2bd2-11ea-86f6-814c728d3a3b.png">

**Comment by vesta0** [comment]
The changes proposed above will be covered by the settings reorg work currently in progress here: #5905
