### ISSUE TITLE
[Bug] Harmonize library flows

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#6418]
Currently, on the homescreen there are options to go directly to _History_ or _Bookmarks_.
In the browser screen there is an option to go to _Library_ screen, and only then to _History_ or _Bookmarks_
IMO this is not consistent, and it also causes bugs like: #6408.
There are also other issues with navigation, like: #5727
If we add more items to _Library_ in the future, not having a consistent flow for accessing them  and navigating away will only confuse the navigation more.

**Comment by brampitoyo** [comment]
Hi @mcarare, you’d be glad to know that @topotropic are thinking of ways to unify our Library navigation!

I will let her comment on this issue. If possible, she may also be able to provide an accurate size (s, m, l, xl) for the design effort. However, an estimate may not be possible since it’s still early in the process.

**Comment by topotropic** [comment]
@mcarare https://github.com/mozilla-mobile/fenix/issues/7276 feel free to close this issue if you feel your concern is addressed with it. Thanks!
