### ISSUE TITLE
[Bug] When cutting the wi-fi off, the download notification displays the download completed

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6434]
## Steps to reproduce
1. Go to https://www.thinkbroadband.com/download.
2. Select to download a file.
3. Cut off the wi-fi and observe the download notification.

### Expected behavior
The download should fail.

### Actual behavior
The notification displays the download to be complete.

### Device information
* Android device: all
* Fenix version: 11/4 (13080608)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3804804/logcat.txt)

**Comment by sblatz** [comment]
This issue is really strange. In Sample Browser inside of Android Components, the way I implemented this, an IO exception is thrown when the internet cuts out. However, for some reason, inside of Fenix, that IO exception is either never thrown or is being caught by some universal catch somewhere? 

@BranescuMihai if you're digging into this more, it's going to be in this section of the code:

https://github.com/mozilla-mobile/android-components/blob/master/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L170-L191

**Comment by sblatz** [comment]
Really strange that this is working as expected in Sample Browser but not inside of Fenix 😕 they're both using the same download service.

**Comment by BranescuMihai** [comment]
@sblatz yep, I was looking into that method, but thanks for the idea with the Sample browser, will check that out

**Comment by sblatz** [comment]
Thanks for investigating this, @BranescuMihai! Sounds like we need a GV/AC patch to fix this.

**Comment by sblatz** [comment]
This should now be partially fixed. Files that have a download size will now fail when the wifi is cut off. The file does not have a content length, we're still waiting on that GV fix. 

QA could you verify that this is partially fixed and I'll keep this open track the GV one?

**Comment by sv-ohorvath** [comment]
The paused download still appears as completed on the in-app notification.
![Screenshot_20191115-114016](https://user-images.githubusercontent.com/4037709/68933222-e5357580-079c-11ea-88d5-cc1e362aa53f.png)

**Comment by sblatz** [comment]
@sv-ohorvath thanks for catching those 😄 

https://github.com/mozilla-mobile/fenix/pull/6645 Should address point 1
https://github.com/mozilla-mobile/android-components/pull/5076 Should address point 2

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 11/19.

**Comment by sblatz** [comment]
To be clear, the GV bug still stands which means that this will still have incorrect behavior when files do NOT have a file size. https://github.com/mozilla-mobile/android-components/issues/4999 Will track that :)
