### ISSUE TITLE
Consider enabling telemetry in debug builds

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6447]
### Why/User Benefit/User Problem
Developers write code on debug builds: it is on these debug builds that they'll notice issues with the code they've written and fix them. As such, debug builds should be as close as possible to what users are using: the release builds.

Currently, telemetry is disabled on debug builds: imo, we should re-enable it.

### Acceptance Criteria (how do I know when I’m done?)
- Telemetry collection & uploads are enabled on debug builds
- Release telemetry is not skewed by debug builds (e.g. telemetry from debug builds is stored in a separate bucket from release builds by app id)
- Telemetry upload is disabled during unit & UI testing

These are the criteria that desktop uses.

---

Some notes from our discussion on Slack:
- Reason for originally not enabling it in debug: num users of Fenix are relatively small and we don't want to overwhelm the telemetry data (esp with automated tests).
- We should consider if contributors outside Mozilla would expect that they are submitting debug telemetry by default.
- "Could telemetry get disabled during testing somehow (ci) but be enabled in the builds themselves, even debug?  That's roughly what happens on desktop"
  - On Desktop, telemetry is always on, but upload is not. This is the same behaviour of Glean. Nothing prevents Glean consumers to init glean and set set upload to disabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14264)

**Comment by Dexterp37** [comment]
> Currently, telemetry is disabled on debug builds: imo, we should re-enable it.
> ### What/Requirements
> ### Acceptance Criteria (how do I know when I’m done?)
> 
>     * Telemetry collection & uploads are enabled on debug builds

I'm not sure upload is strictly required here. Our team discussed about a potential path here: a reasonable strategy could be to always init Glean and just set upload to disabled (e.g. make the "telemetry" setting default off for debug builds). Developers testing things would simply need to flip a setting vs rebuild again.

>     * Release telemetry is not skewed by debug builds (e.g. telemetry from debug builds is stored in a separate bucket from release builds by app id)

This already happens: Glean telemetry is faceted by application id. As long as the debug version uses a suffix or a different id we should be fine (this is already the case for Fenix, which adds a `.debug` suffix to the application id).

>     * Telemetry upload is disabled during unit & UI testing

This is already the case for unit testing, since it requires to use the `GleanDebugRule`. UI testing can use the `GleanLocalNetworkRule` which sends to the local network.

> Some notes from our discussion on Slack:
> 
>     * Reason for originally not enabling it in debug: num users of Fenix are relatively small and we don't want to overwhelm the telemetry data (esp with automated tests).

Did this concern come from the telemetry team? I don't think we should be worried about receiving data from debug builds. (FYI @fbertsch)

>     * We should consider if contributors outside Mozilla would expect that they are submitting debug telemetry by default.

This is a legitimate concern. Without getting too much magic in the build system, that's potentially addressed by making the telemetry setting in Fenix default off for debug builds.

What about non-Glean telemetry that Fenix collects, though?

**Comment by mcomella** [comment]
> >     * We should consider if contributors outside Mozilla would expect that they are submitting debug telemetry by default.
>
> This is a legitimate concern. Without getting too much magic in the build system, that's potentially addressed by making the telemetry setting in Fenix default off for debug builds.

Related to this, on Matrix:

> you 100% need to get sign-off from data stewards and data privacy. it's a case-by-case basis, not a broad policy
we're currently doing that for moz-phab ([bug 1621025](https://bugzilla.mozilla.org/show_bug.cgi?id=1621025)).  build is next; however mach already has some telemetry (not using glean)

See https://wiki.mozilla.org/Firefox/Data_Collection to get started.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809321

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
