### ISSUE TITLE
Investigate Sync collections

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#6512]
This ticket is for UX + Sync team to investigate how we might we solve the following user problems:

Problem Statement:
FxA users can't access their Fenix collections on other FxA enabled devices, so they are not able to continue/complete their tasks across devices.

**Comment by yoasif** [comment]
There is interest in syncing Fenix collections to desktop: https://www.reddit.com/r/firefox/comments/egd6zb/firefox_preview_for_android_has_collections_can/

There is prior art in Fennec of syncing open tabs (this is available in View > Sidebar > Synced Tabs on desktop) -- I think it makes sense to extend that metaphor to collections stored on Fenix (on desktop).

**Comment by jawz101** [comment]
This could be fixed with this


https://github.com/mozilla-mobile/fenix/issues/5853


Because collections are just yet more bookmarks, why do we keep reinventing wheels?

**Comment by pauljacobson** [comment]
It would be really helpful if Collections could be synced, as Collections.

**Comment by jawz101** [comment]
.. and we call the tab groups 0_o

**Comment by andreicristianpetcu** [comment]
Calling them tab groups would be really cool since a lot of people use tab groups one way or another. Heck, even Chrome is working on tab groups on desktop.

Just a rename from Collections to Tab Groups would bring a huge spike in popularity for this feature.

**Comment by yoasif** [comment]
Ran into this due to trying to migrate tabs from an old Fenix on an old device and finding that #11404 does not exist, nor does #2080. @liuche suggested that I send a collection over via send tab, but I ended up not receiving 90% of my tabs - and they appeared as notifications anyway, instead of a neat bundled collection. 

This feature should happen in any case, but I wanted to provide another angle in which it could be useful (data portability).

**Comment by madb1lly** [comment]
Hi all,

Not being able to sync collections undermines their usefulness because I've got no way to back them up, therefore I'm much more likely to keep a massive tab stack instead because these tabs are synchronised.

Wouldn't a simple way to do this be to make Collections a special bookmark folder?

Cheers 🙂

**Comment by vesta0** [comment]
Thanks for the use case @madb1lly we will be working on this feature in Q3 :)

**Comment by NotWoods** [comment]
A-C issue: https://github.com/mozilla-mobile/android-components/issues/7640

**Comment by NotWoods** [comment]
After discussions with the sync team here is the approach we've agreed on.

Generic sync is nice to have but will have many implications, so that work will be deferred. For collections in particular, we can "abuse" the synced tabs store.

Fenix would report all tabs in a collection as being "open", but would also record a new attribute called 'collections' which would be an array of strings (to handle a tab existing in multiple collections). This system would resemble labels in GMail.

Advantages:
* Simple to add and doesn't require complicated discussions around offering a new data choice to sync users.
* Desktop gets some support for free! It would immediately list these tabs from Fenix, and it would be a fairly simple change in desktop to start recognizing this new attribute and create nested menus for tabs in collections, or otherwise use a custom UI for such tabs.
* It doesn't lock us in - if desktop ends up wanting the feature we can think about doing it in a slightly different way and making it a "first class" feature.

Downsides:
* "Merging" of collections is the responsibility of the android-specific code - there's no single, canonical definition of what a named collection is, but instead, each device gets to nominate what it has as the collection locally.

**Comment by madb1lly** [comment]
Hi @NotWoods,
Sounds good! ETA? 😃
Cheers 🙂

**Comment by madb1lly** [comment]
Hi @vesta0,

I interpret the status of this ticket to mean that collections are still not synced, is that correct? 

And should I interpret the Fenix product backlog board to mean Q2, Q3, Q4 of 2021, Next is 2022 and Later is 2023? So collections syncing won't be worked on until 2022?! Even though the above solution proposed by @NotWoods seems like a relatively simple implementation?

Cheers 🙂

**Comment by NotWoods** [comment]
The above solution was discussed with the sync team and we decided against it. Other solutions are being looked at instead.

**Comment by madb1lly** [comment]
Hi @NotWoods,
Thanks for the update. So does "Next" mean 2022 is when we should expect collections to be synced?
Cheers 🙂

**Comment by klint** [comment]
I just lost all my collections after a constant crash of Firefox Nightly when I had to delete all data from the app.
Please, either remove the collections feature or sync them. The in-between state makes no real sense.

**Comment by madb1lly** [comment]
Hi @klint,

That's just what I fear happening too. I know I'm using Nightly so it's higher risk, I've been thinking for a while I'll switch to beta or release.

I've also realised that I just use collections as bookmarks because the rest of the promise of collections (to switch between them like tab groups) isn't realised or cannot be done efficiently. So if I'm just using them as bookmarks I should change them to bookmarks.

Still, the absence of sync for this is still a very strange choice.

Cheers 🙂

**Comment by klint** [comment]
Please remove collections completely from Fenix if sync is not enabled.

**Comment by lle-git** [comment]
Hello,
Sorry if the answer is obvious,  but it is not clear to me : 
This ticket is labelled wontfix but it is not clear why (main difficulties, guiding principles)
Moreover it was proposed : 
 3 Feb > The above solution was discussed with the sync team and we decided against it. Other solutions are being looked at instead.

What can we expect on this ticket ?

Thanks
