### ISSUE TITLE
[Bug] Big lags after using filter: invert(100%);

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6549]
## Steps to reproduce
1. open www.mwiacek.com
2. click Color on the right top corner to enable dark mode

### Expected behavior
Page scrolling is nice.

### Actual behavior
Huge lags in refresh (Chrome is OK).

### Device information
* Android device: Galaxy S7
* Fenix version: 2.3.0

**Comment by boek** [comment]
This seems to be working better now. @marcinwiacek are you still able to reproduce?

**Comment by marcinwiacek** [comment]
Yes, still visible on nightly 18.05 + the same device. I can move page and get into situation, that page is not rebuilt at all (you see only black screen and no content).

**Comment by ebalazs-sv** [comment]
Hi!
I tested this on the latest Fenix Nightly from 5/21 with
 
- Samsung Galaxy Tab S3 (Android 8) - not reproducible;
- Motorola Moto G6 (Android 8) - not reproducible;
- Nexus 5 (Android 6.0.1) - reproducible;
 
The issue is reproducible on Nexus 5 (Android 6.0.1) when scrolling the mentioned page fast.
I will remove the qa:needed until further notice.
