### ISSUE TITLE
[Bug] back button is missing from the menu

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6559]
### Steps to reproduce

1. open a website and press a link
2. press the menu button

### Expected behavior

There is a back button.

### Actual behavior

After the removal of the QAB there is no longer a back button in the menu making it impossible for me to use Fenix with one hand (in most cases).

### Device information

* Android device: OnePlus 7T Pro McLaren Edition with Android 10
* Fenix version: master branch revision f0468f8099244095351753e897bc77e772a6609d

**Comment by sblatz** [comment]
This is expected behavior when we removed the QAB: https://github.com/mozilla-mobile/fenix/pull/6310

This was an explicit decision made by UX to reduce overcrowding of the menu toolbar. Because of that, we are deferring to the system back button's use here. 

That being said, UX is considering re-organization of this toolbar menu, perhaps this feedback is better situated there: #5095
