### ISSUE TITLE
[Bug] Tracking protection not working in Fenix Build 13181522

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6606]
## Steps to reproduce

1) Enable Enhanced Tracking Protection, for instance in the Strict mode.
2) Go to https://senglehardt.com/test/trackingprotection/test_pages/ and choose any of the tests that concern Trackers or Social Tracking Protection.

### Expected behavior

Tracking should be reported as BLOCKED.

### Actual behavior

Tracking is reported as NOT BLOCKED.

Could this be related to https://github.com/mozilla-mobile/fenix/issues/6325 (and everything referenced therein)?

### Device information

* Android device: Nokia 5 (model TA-1024) with up-to-date Android 9 (Android One program)
* Fenix version: 191114 15:15 (Build 13181522)

**Comment by Amejia481** [comment]
Thank you for reporting, there is an [opened bug ](https://bugzilla.mozilla.org/show_bug.cgi?id=1590788) for updating the test pages. Until this bug is not fixed everything related to Social tracking protection and content trackers(base-track-digest256 list) on the test pages is not going to show properly. The only thing that is affected is the test pages, everything else should be working.

**Comment by Amejia481** [comment]
I think this can be closed now.
