### ISSUE TITLE
[Telemetry] Add ANR (Application Not Responsive) to the Fenix metrics

### ISSUE THREAD

**Issue by saptarshiguha** [mozilla-mobile/fenix#6741]
Owner: Product Manager

#### Description & Product Manager / Data Scientist User Story
ANR is an important metric related to application stability. It is reported (alongwith Crash Rate) in the Play App Store. We will be using ANR as stability metric for Fenix release

We already measure three types of crashes in Fenix metrics: caught and uncaught exceptions and native crashes. Rather than accessing Play Store we would like to keep a count of ANR along with these metrics.

#### What questions will you answer with this data?

Measure ANR on platforms with  different memory use/os versions. Keep track of ANR so it doesn't increase.

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?

A lower ANR is better for user experience and is an indicator of app quality

#### What probes (suggested, if applicable)
- 

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14475)

**Comment by pocmo** [comment]
If we go ahead with this proposal then we should consider implementing this in Android Components so that all our apps can use that. But I'm going to leave this issue in this repository so that it can get a priority from the Fenix team.

To my knowledge there is not system API that allows us to hook into its ANR detection. There have been workarounds to measure the responsiveness of the UI thread and report hangs, e.g.:
https://medium.com/@cwurthner/detecting-anrs-e6139f475acb

I have never used such a "watchdog" in production, so I am wondering:
* Does this add additional stress to the app since we switch to the UI thread frequently (performance, resource usage, ..).
* In the case of a blocked main thread: Will our telemetry reporting still work sufficiently or will it be affected by the blockage too?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809316

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
