### ISSUE TITLE
[webcontent] Crash on www.ucas.com results screen

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#6742]
Originally reported at https://github.com/webcompat/web-bugs/issues/44145#issue-518652564, which includes steps to reproduce (confirmed by our QA team).

**Comment by ValentinTimisica** [comment]
I tried to reproduce this but for me the app doesn't crash. I used the same input as in the original report. Can someone from QA try to reproduce this?

**Comment by Diana-Rus** [comment]
Hi, I did not reproduce the issue with the input from ticket: https://github.com/webcompat/web-bugs/issues/44145 with build Firefox Preview Nightly 191114 (🦎: 72.0a1-20191109093718) on the following devices:
- Google Pixel XL (Android 10)
![20200302-115313](https://user-images.githubusercontent.com/49859863/75665538-fa1b1380-5c7c-11ea-8e52-1c5ff18d5763.gif)

- Samsung Galaxy Note9 (Android 9)
![20200302-104030](https://user-images.githubusercontent.com/49859863/75661537-2b441580-5c76-11ea-9f33-5bdbd4b7d359.gif)

- Samsung Galaxy S9 (Android 8.0.0)
![20200302-095315](https://user-images.githubusercontent.com/49859863/75661515-21221700-5c76-11ea-9ee4-1fd9ce9388e4.gif)

- Sony Xperia Z5 (Android 7.0.0)
![20200302-100011](https://user-images.githubusercontent.com/49859863/75661426-f33cd280-5c75-11ea-917c-29c3f5f8fa05.gif)

Notes:
- The issue is not encountered on the latest build, checked on the same devices: Firefox Preview Nightly 200302 (Build #20620607) and GV: 75.0a1-20200228092428
- I have also tried through custom tab functionality and did not managed
- I have also checked with the default ppi for each device and with (~570 ppi density - changed in Developer tools level) based on comment: https://github.com/webcompat/web-bugs/issues/44145#issuecomment-554892027

Based on my findings I will close the ticket.
