### ISSUE TITLE
Top toolbar: when toolbar is at top, move toolbar on Home screen to top as well

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6820]
If I choose Top Toolbar, it seems odd that the toolbar on the Home/Tabs screen (with the Fenix logo) is at the bottom. 

Would it make more sense to have ALL toolbars (Home/Tabs screen & Search screen & page content screen) at the top?

Thanks

**Comment by sblatz** [comment]
Agreed, I think this makes a lot of sense :)

**Comment by brampitoyo** [comment]
Agreed. When the toolbar is set to top, _all_ toolbars should be positioned on top, too – including toolbar on the start screen/tab manager.

**Comment by Cheap-Skate** [comment]
> Agreed. When the toolbar is set to top, _all_ toolbars should be positioned on top, too – including toolbar on the start screen/tab manager.

So, should it also be the case that if I choose a bottom toolbar the Search toolbar should also be on the bottom. At the moment it's at the top which I find odd.

i.e. either all toolbars at the top, or all toolbars at the bottom  where  all = Home & Search & content view screens

(this might be a separate issue)

**Comment by brampitoyo** [comment]
@Cheap-Skate Sorry, I should’ve clarified.

When toolbar Settings = “Bottom”, our positions are as follows:

| Address bar  | Position, if toolbar Settings == “Bottom” |
| ------------- | ------------- |
| On start/home screen  | Bottom  |
| On “Search with”  | Top  |
| On webpages | Bottom |

If toolbar Settings == “Top”, these were the positions I proposed:

| Address bar  | Position, if toolbar Settings == “Top” |
| ------------- | ------------- |
| On start/home screen  | Top  |
| On “Search with”  | Top  |
| On webpages | Top |

You correctly noticed an inconsistency. If toolbar Settings == “Bottom”, then why is the toolbar on “Search with” screen located on top?

It’s because there’s a conflict between your thumb (closer to the bottom of the screen) and the way you read search results (top to bottom).

In this particular scenario, we had to choose between ergonomics and readability. We prioritised the latter: show you search results from top to bottom.

This means that the top-most search results are the furthest away from your thumb, yes. But it also makes search results show in an orderly fashion. The topmost one is always the first, the bottom-most one always the last.

The address bar is where the search keyword originates from, right? It makes sense that the “source” is located at the apex of the hierarchy: the very top of the screen, always above the search results.

**Comment by darkwing** [comment]
@sblatz How difficult will this be.  Any tips you can give me?

**Comment by sblatz** [comment]
@darkwing 
In theory not crazy difficult since we have a "fake" toolbar on the home screen that doesn't need to scroll away or have any movement on the screen (it should automatically animate when we transition to Search Fragment). 

You'll just want to mess with `bottom_bar` in `fragment_home.xml` and base it off of `shouldUseBottomToolbar` (settings property)

Let me know how else I can help 😄

**Comment by darkwing** [comment]
Fixed in: https://github.com/mozilla-mobile/fenix/commit/4b3effdfabb1b80eafdd2d172de8ca7dd574e226

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/5 @20360606.

Devices:
- Nexus 5 (Android 6.0.1);
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android Q).
