### ISSUE TITLE
Keep performance-test build to have tracking protection popups diabled 

### ISSUE THREAD

**Issue by sefeng211** [mozilla-mobile/fenix#6903]
After #6354, performance-test builds start to have the tracking protection popups to show up, and this causes some trouble to measure some visual related performance numbers, can we please have it keep disabled for performance-test?

**Comment by boek** [comment]
@mcomella?

**Comment by mcomella** [comment]
We'll triage and presumably try to address this. This one is tricky: a goal of performanceTest builds is to make them as close to release builds as possible because anything in release builds may affect performance (including those pop-ups). We wouldn't want to disable these pop-ups for local performance development but perhaps we'd want to disable them for visual-metrics testing.

I wonder if we should disable this (and other blocking things) at runtime using an Intent instead of disabling it universally via the compile-time Build Variant.

**Comment by mcomella** [comment]
There may be some precedent with doing this through intents from disabling onboarding: https://github.com/mozilla-mobile/fenix/pull/7127

**Comment by mcomella** [comment]
@sefeng211 Is this still an issue? If so, how urgent is it?

**Comment by sefeng211** [comment]
@mcomella yeah it is still an issue. Not 100% sure about the urgency, however since we are urgent in getting visual metrics in CI, I'd say this is quite urgent. 

Using an intent or a possibly a pref sounds good to me, as long as these changes won't introduce any new overheads...

**Comment by acreskeyMoz** [comment]
Given that we'd also like to evaluate the pageload performance of other Fenix builds, notably  production, I agree it would be best to have a solution that works outside of performance-test.
A pref works, or also an intent option (provided that it can work for all build options).

**Comment by mcomella** [comment]
> Given that we'd also like to evaluate the pageload performance of other Fenix builds, notably production, I agree it would be best to have a solution that works outside of performance-test.
> A pref works, or also an intent option (provided that it can work for all build options).

@MarcLeclair FYI

**Comment by MarcLeclair** [comment]
closed with #8226
