### ISSUE TITLE
Pop-up blocker: better bottom sheet design

### ISSUE THREAD

**Issue by ColourGrey** [mozilla-mobile/fenix#6973]
### User Problem

When a user opens a page that tries to open pop-ups, the user is presented the message "Prevent this site from opening a pop-up window?" followed by the URL of the page and the buttons "DENY" and "ALLOW". These two answers are confusing. If I "allow", do I allow pop-ups, or do I allow Firefox to block them? If I "deny", do I deny Firefox the possibility to block them, or do I deny the page the possibility to open them?

### Solution

Change the answers to the shorter, simpler and non-ambiguous "yes" and "no". And maybe not write them all in capitals, as they are now. Why shout?

(PS: this feature request is midway between a feature request and a bug report.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14638)

**Comment by NotWoods** [comment]
The "shouting" is just because [Android's popup styling](https://material.io/components/dialogs/) uses all caps for the buttons. Adding the UX-feedback label so the UX team can weigh in.

**Comment by topotropic** [comment]
@NotWoods let's follow the material design guidelines here and keep all caps. 

@mheubusch can you make a recommendation for the copy? Thanks!

**Comment by brampitoyo** [comment]
Assigning @mheubusch to this issue.

**Comment by kbrosnan** [comment]
Yes and No are generally poor choices for these sorts of dialogs as the answer is dependent on the question's structure. `Show popup from example.com? [Y/N]` Yes shows the popup, no blocks the popup. `Block popup from example.com? [Y/N]` Yes blocks the popup, no shows the popup.

Allow/Show and Deny/Block describes the action that results from pressing the button.

**Comment by brampitoyo** [comment]
Keep in mind that our default state for pop-up is not “Allow”, but “Block”. We want to prevent all pop-ups from opening, unless the user had specifically said “Allow”.

My first reflex (keep in mind that this is just an initial idea) is to solve this problem not by rewording the button, but rewording the message itself:

> Pop-up blocked
> [Allow] [Continue blocking]

(Continue blocking should be the highlighted/preferred option)

Or even better: make all Blocked permission small and non-interruptive (in the preview below, the scrim is shown – imagine that it’s not there: you can continue using the site as usual). The user can ignore/dismiss them with a simple “x”, and must press “Advanced” to allow it.

<img width="775" alt="Screen Shot 2020-02-06 at 6 24 18 PM" src="https://user-images.githubusercontent.com/51007/73908252-f8745f00-490d-11ea-9198-cb2fbbd7b223.png">

**Comment by TitanNano** [comment]
> Or even better: make all Blocked permission small and non-interruptive (in the preview below, the scrim is shown – imagine that it’s not there: you can continue using the site as usual). The user can ignore/dismiss them with a simple “x”, and must press “Advanced” to allow it.

Couldn't this just be a snackbar with a reasonable timeout?

**Comment by brampitoyo** [comment]
@TitanNano 

A time out sounds fine to me. My hypothesis is that most users would be ok if the pop-up notification disappear automatically.

On the rare cases that users want to re-allow pop-ups or open specific ones, they can:

1. Simply refresh the site – the notification will show up again – then tap “Advanced”
2. Or, go to the Site Information Panel

<img width="320" src="https://user-images.githubusercontent.com/51007/74119038-b9525080-4c22-11ea-91d7-d5ff556d3189.png"> <img width="320" src="https://user-images.githubusercontent.com/51007/74119059-c7a06c80-4c22-11ea-8679-6675dc32e730.png">

**Comment by brampitoyo** [comment]
Here’s a flow that I propose:

<img width="1707" alt="Screen Shot 2020-03-16 at 5 44 37 PM" src="https://user-images.githubusercontent.com/51007/76723917-e065ea00-67ad-11ea-91b5-639d189b66ad.png">

1. If we detect a pop-up, always auto-block it
2. When we auto-block a pop-up, show a UI that will disappear after a few seconds. Either:
    - A non-modal bottom sheet
    - A snackbar
3. When the button is tapped, open the site information panel. This panel allows users to control all permissions, including pop-ups
4. By tapping on the “Blocked” button, a dropdown menu shows up. It allows users to allow all, block all, or selectively open certain pop-ups

@TitanNano what do you think?

@betsymi This issue isn’t high priority, but just in case you have time: we’d like to default to blocking all pop-ups, but this creates the need for a new UI that we don’t use for any other permission. Pop-up is unique in that the default policy isn’t “Ask”. It’s “Block”.

1. I wonder whether it’s better to show a bottom sheet or a snackbar? The idea is that, because pop-up defaults to “Block”, the permission notification shouldn’t interrupt the current website, and it should disappear after a few seconds. I think a snackbar may be better, but every other permission shows a bottom modal sheet.
2. What should we say in this notification? I proposed something like “Pop-up blocked”, with an action/button called “Advanced”

**Comment by TitanNano** [comment]
@brampitoyo I think the snackbar fits better here. As you say, it is supposed to disappear after a couple of seconds and since it defaults to blocked it's not a permission prompt, but just a notification for the user.

**Comment by AmyYLee** [comment]
@brampitoyo @betsymi to follow-up

**Comment by betsymi** [comment]
@brampitoyo Let's get some time on this when you're back from PTO. I believe the appropriate use for a snackbar would be only after a user completed an action, but I could be wrong. Let's discuss the best approach.

**Comment by AmyYLee** [comment]
@brampitoyo for follow-up

**Comment by sheikh-azharuddin** [comment]
Any update on this popup blocker.. Today i faced this issue even after clicking allow it simply continues to block popup...

**Comment by smac89** [comment]
@sheikh-azharuddin  see https://github.com/mozilla-mobile/fenix/issues/22641

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813202

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
