### ISSUE TITLE
[Bug] Content moves down when toolbar automatically unhides #6955

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6976]
#6955 brought auto unhiding to the toolbar - great - but minor nit

Select top toolbar
Navigate to a URL
Scroll so the toolbar is hidden
Tap a link to move to a new URL

The toolbar unhides AND the existing page content scrolls down to accommodate the toolbar -> the toolbar "pushes" the content down the screen as it appears

This is different behavior from Fennec & Chrome where the toolbar unhides without the content moving -> the toolbar moves "over the top" of the content without the content moving

(not sure if this is a bug or a feature, and it's definitely a nit)

Personally I prefer the Fennec/Chrome behavior

**Comment by sblatz** [comment]
Here is a demo of the current behavior:

![push up 2020-01-07 10_45_29](https://user-images.githubusercontent.com/4400286/71920076-dfc03000-313a-11ea-909d-8a22a229137c.gif)

**Comment by brampitoyo** [comment]
@Cheap-Skate wrote:

> [In] Fennec & Chrome […] the toolbar moves "over the top" of the content without the content moving

You’re right. This is a bug rather than an intended behaviour. We should fix it.

**Comment by mcarare** [comment]
This will not be a trivial fix, because we rely on an out-of the box behaviour for the hiding and showing of the toolbar.

The fixes would be to either build a custom behaviour by overriding the current one, or do what Fennec does, by taking a snapshot of the toolbar, but again, it requires some not-so-minor changes.

As a side note: Focus does not even show the toolbar after navigating to another link.

**Comment by liuche** [comment]
Sounds like we should fix this in AC, not overriding the behavior. This sounds like a bug in the out-of-the-box behavior, if no browser actually wants to have this behavior.
