### ISSUE TITLE
[Bug] (regression) Google (and other engines) missing in other languages

### ISSUE THREAD

**Issue by mkaply** [mozilla-mobile/fenix#6981]
## Steps to reproduce

Switch language to French or German on the device.
Go to conduct a search.

### Expected behavior

Google (and other engines) are present.

### Actual behavior

Google is missing. All that is there is Bing, DDG and Twitter

### Device information

* Android device: Motorola G6
* Fenix version: Latest nightly

**Comment by liuche** [comment]
Maybe this is expected if these are the bundled search engines for each locale.

Just to clarify @mkaply: is the expectation that your search engines will always match the locale that you start with? or location? And if you switch to a different locale (or location), you do not change the search engines (and add a Yandex if you switch to RU, for example).

**Comment by mkaply** [comment]
These definitely aren't the bundled search engines for each locale. Every locale has Google, Wikipedia and others and those are missing. The three that are being used (Bing, DDG, Twitter) are coincidentally the only engines that are exactly the same in every locale. I'm guessing that's going to help figure this out.

And yes, the expectation is that when you switch locales, you get a new set of engines for that locale.

**Comment by Mugurell** [comment]
@kglazko Are you still working on this? Need any help?

**Comment by kglazko** [comment]
I will unassign myself for now because I have some  other things I'm working on at the moment :) Feel free to take a look!

**Comment by liuche** [comment]
Thanks @Mugurell! If you could pick this up, that would be great.

**Comment by Mugurell** [comment]
Looked into this, found the underlying problem to be that when we return the list of search engines to be displayed in the AwesomeBar [we filter the engines by a list of search engine identifiers](https://github.com/mozilla-mobile/fenix/blob/cd53e9778a9af3017f1280a161ecc37104be0535/app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt#L71)  
identifiers read from SharedPreferences and [initialized only once](https://github.com/mozilla-mobile/fenix/blob/cd53e9778a9af3017f1280a161ecc37104be0535/app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt#L149) when we first ask for the search engines.

So after changing the language on the device and ask for the search engines list to be displayed in the AwesomeBar we get a new list of search engines (different than before because of the locale change) which we filter by the same initial list of identifiers and now get fewer engines matching.

A solution might be to rebuild the list of identifiers every time the locale is changed (remove all identifiers of the previous default engines, add the identifiers of the new ones (keep the identifiers of the custom search engines )). But I'm just wondering why do we need this identifiers.

Since I see you worked the most on this, @boek I'm asking you if you think it would be ok to just remove the identifiers altogether or if we should go through the route of rebuilding the identifiers with each locale change.

**Comment by ekager** [comment]
Can reproduce and another particularly bad example: 
1. Device is in en-US, change locale in Fenix in Russian
2. Restart app and go to Search Engine Settings

You only see Twitter as an option

**Comment by Diana-Rus** [comment]
Hi, the issue is not reproducible anymore.
There are no missing engines in other languages, neither when accessing AwesomeBar nor through "Settings"/"Search"/"Default search engine" list:
- French - Google
- German - Google
- Russian - Yandex - impacted by #3869 but present as search engine
- Japanese - Google

Devices:
- Google Pixel 3a (Android 9)
- Samsung (Android 8.0.0)
- Sony Xperia Z5 (Android 7.0.0)
- LG K4 (2017) (Android 6.0.1)

Build:  Firefox Preview 4.0.0-beta.1 (Build #20500408) GV: 74.0-20200216164042
Note: 
- Issue through the alternative scenario from Comment 5 does not reproduce.
- Firefox Beta still does not yet have the "Language" option in Settings.

Google Pixel 3a (Android 9)
- French - Google search engine default, other engines displayed
![Screenshot_20200219-154559](https://user-images.githubusercontent.com/49859863/74842953-da5a2600-5333-11ea-8112-2220bc95226f.png)

- German - Google search engine default, other engines displayed
![Screenshot_20200219-154742](https://user-images.githubusercontent.com/49859863/74843017-f78ef480-5333-11ea-86ef-b27fe4e04497.png)

- Russian - Yandex search engine default, other engines displayed
![Screenshot_20200219-155143](https://user-images.githubusercontent.com/49859863/74843052-0a092e00-5334-11ea-9384-66cd622d7503.png)

- Japanese - Google search engine default, other engines displayed
![Screenshot_20200219-155333](https://user-images.githubusercontent.com/49859863/74843149-302ece00-5334-11ea-8a69-518529e2d5ef.png)

**Comment by abodea** [comment]
Removing the **`:need:STR`** as this issue was confirmed and closed by QA.
