### ISSUE TITLE
[Bug] links opened in private browsing also loads in normal mode

### ISSUE THREAD

**Issue by mirza-ibrahim** [mozilla-mobile/fenix#6990]
## Steps to reproduce

Close fenix browser.

Open any external link in pri vate mode, e.g a link from twitter. Now only one private tab is loaded.

Press back button on Android. It will take back to your app (e.g Twitter)

And when we switch back to Firefox, that private tab is loaded in normal mode. 

### Device information
* Android device: Android pie
* Fenix version: 2.3.0

**Comment by mcarare** [comment]
I cannot reproduce this using the latest master.

**Comment by mirza-ibrahim** [comment]
Updated steps to reproduce, please try again.

**Comment by abodea** [comment]
Verified as fixed using the latest Nightly build from 12/11 with Samsung Galaxy S10+(Android 9).
Note that I tried the following cases:
#### I've set Fenix Nightly as my default browser:
   - I opened the Twitter app
   - Tap on any link - > the custom tab for Fenix was opened in private browsing - Tap on the device back button --> everything worked as expected.
- Tap on any link - > the custom tab for Fenix was opened in private browsing -> Tap on the 3 dot menu and then access `Open In Firefox Nightly` -> tap on the device back button  --> everything worked as expected.

@mirza-ibrahim Note that in order to open links in Private Mode you have to enable the option from Fenix > Settings > Set as default browser but for the RC 2.3.0 this option is not available yet.

This issue is working as expected in Fenix Nightly and when it will reach the RC it will work well there too.

**Comment by sv-sdeiac** [comment]
Hello, O can confirm that the issue is not reproducible on the latest version of RC 3.0.1 #13502255 12/16 using the steps provided by Andrei. 

Devices:
- LG g7 fit (Android 8.1);
- Xiaomi Mi 8 Lite (Android 9);
- Motorola Moto G6 (Android 8).
