### ISSUE TITLE
[Bug] Extra Headers are not set for Custom Tab

### ISSUE THREAD

**Issue by ATizik** [mozilla-mobile/fenix#7030]
## Steps to reproduce
1. Set FIrefox to default browser
2. Add the following code for custom tab intent:
`
Bundle headers = new Bundle();
headers.putString("X-Extra-Header","true");
customTabsIntent.intent.putExtra(Browser.EXTRA_HEADERS, headers);
`
3. Launch custom tab intent with Firefox

### Expected behavior
X-Extra-Header is set

### Actual behavior
X-Extra-Header is missing

### Device information
* Android device: Note 9 and Emulator
* Fenix version: 
2.3.0 (Build #13031728)
📦: 18.0.0, ef631b6df
🦎: 70.0-2019101403264

**Comment by boek** [comment]
We're guessing we want to pass this header through to GV? This is something we'll have to add to a-c

**Comment by liuche** [comment]
Here's an [explanation of headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers), and what things could be going wrong (auth, caching, resource fetching, DNT, etc)

**Comment by jonalmeida** [comment]
Assigning to self to find GV bug that was filed for this.

**Comment by softvision-miralobontiu** [comment]
@psymoon could you help us with some STR, in order for the QA team to test this?

**Comment by abodea** [comment]
Removing the qa needed until further notice.
@jonalmeida can you please help us with the question from above?

**Comment by jonalmeida** [comment]
> Removing the qa needed until further notice.
> @jonalmeida can you please help us with the question from above?

This isn't something QA can easily test since it work require making a custom Custom Tabs client to send headers and then inspect the requests going through.

Using the demo [`custom-tabs-client`](https://github.com/GoogleChrome/custom-tabs-client) project, I added OP's request header to the intent and inspected the requests:

```java
Bundle headers = new Bundle(); headers.putString("X-Extra-Header","true");
CustomTabsIntent intent = intentBuilder.build();
intent.intent.putExtra(Browser.EXTRA_HEADERS, headers);
```

You can see the request coming through 
<img width="285" alt="Screen Shot 2020-04-16 at 9 54 22 AM" src="https://user-images.githubusercontent.com/1370580/79464894-ac5a3080-7fc8-11ea-81ec-f83f34c71590.png">

Closing this as verified.
