### ISSUE TITLE
Make Normal and Private Browsing customizable color schemes 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7058]
### Why/User Benefit/User Problem
As a Fenix user, I want to be able to personalize my home screen colors in **normal** or **private browsing.**
### What/Requirements
Add a button in the `Themes` menu in settings adding for Normal and Private Browsing customizable color schemes.
### Acceptance Criteria (how do I know when I’m done?)
![priv6](https://user-images.githubusercontent.com/42831109/70534053-ed49c080-1b62-11ea-8da7-63f8c6de85f8.png)
![priv4](https://user-images.githubusercontent.com/42831109/70534064-f044b100-1b62-11ea-8863-e7be74150d77.png)
![priv](https://user-images.githubusercontent.com/42831109/70534065-f044b100-1b62-11ea-8fd2-981dbf064099.png)
![priv3](https://user-images.githubusercontent.com/42831109/70534066-f0dd4780-1b62-11ea-9cab-181ed160924d.png)
![priv5](https://user-images.githubusercontent.com/42831109/70534069-f2a70b00-1b62-11ea-9064-95af5f55f228.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14702)

**Comment by cadeyrn** [comment]
For reference: In Firefox Lite you can change the background of the start screen with a double tap. But only in the regular, not in the private browsing mode. I think it make sense to restrict this feature to non-PBM because of the special nature of the PBM.

Firefox Lite could also be inspiration for the background itself. There is a background pattern and it looks much better than a plain color or linear gradient.

If Mozilla wants to be even better they could allow a combination of a background color and a background pattern (or no pattern).

**Comment by AmyYLee** [comment]
Hi, 

Thanks for the suggestion. We will keep this in mind for consideration in our future updates.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807085

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
