### ISSUE TITLE
Handling intent for uninstalled apps

### ISSUE THREAD

**Issue by bifleming** [mozilla-mobile/fenix#7101]
## User Story
- As a user, if I open a deep-link and don’t have the 3rd party application installed, I get the option to install the app from the Play Store. 

### Acceptance Criteria
- I can choose to open an app link intent in a 3rd party application by being offered the choice to install the app if I don't have it.

**Comment by vesta0** [comment]
This specific user story is no longer relevant since user will decide how all intent will be handled.

**Comment by howels** [comment]
Intent for links on banggood.com result in a redirect to banggood:// and still lead to an "invalid URL" instead of trying to install an app (or staying on the actual web page) in firefox preview nightly 200125 06:01 (build #20250609) although the issue https://github.com/webcompat/web-bugs/issues/47491 is marked as resolved.

**Comment by pinta83** [comment]
Same problem here... Firefox mobile....

**Comment by TungstenE2** [comment]
same problem here. any updates? how to reopen?
