### ISSUE TITLE
[Bug] Videos cannot auto landscape on fullscreen

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7136]
### Device information

* Android device: ?
* Fenix version: ?
Nightly 191213 06:01 (Build #13470611)
26.0.0, e29cc1990
GV: 73.0a1-20191211094640

**Comment by abodea** [comment]
Thank you for the report @lindongbin.
Can you please add the steps?

If I hold the device in portrait mode and I tap on the fullscreen button, the video enters the fullscreen mode, but do not auto-rotate until I rotate it in landscape mode.

The following issue https://github.com/mozilla-mobile/fenix/issues/1343 was verified by QA a long time ago.

@ekager, @colintheshots, @jonalmeida can you please check this in case something changed since our last verification?

**Comment by kbrosnan** [comment]
Dupe #5771 this feature was backed out because it always assumed full screen video was landscape.
