### ISSUE TITLE
[Bug] v3 upgrade: sites previously added to homescreen wiped

### ISSUE THREAD

**Issue by campbellkerr** [mozilla-mobile/fenix#7179]
## Steps to reproduce
In the previous version before this v3 one, I had added some sites/bookmarks to my home screen. After upgrading to v3 from the Play store, they had been removed/deleted.

### Expected behavior
Home screen bookmarks/shortcuts remain

### Device information

* Android device: ?
* Fenix version: ?

Might just be me - I guess my biggest gripe is that I can't remember all the sites I had pinned to my home screen so I don't know which ones I've lost (just yet).

**Comment by cadeyrn** [comment]
> This is fallout from #4976. We had the choice of Fennec users loosing home screen shortcuts or Fenix users. we chose the latter

quoted from #7006.

**Comment by pocmo** [comment]
As mentioned above this was an intentional change unfortunately. We have to have matching entry points with Firefox for Android so that we can eventually replace it with Firefox Preview *without* losing the launcher entries. However this meant that Firefox Preview users would lose them on an update. Since it is a "Preview" version we determined this to be an acceptable drawback.

> Might just be me - I guess my biggest gripe is that I can't remember all the sites I had pinned to my home screen so I don't know which ones I've lost (just yet).

I'm sorry for that. To be honest I didn't expect users to have that many shortcuts on their home screen. Can you help me understand your use case? I'm curious if you just like to have them on your home screen or whether you are trying to solve an issue that we could solve inside Fenix for you (e.g. currently we do not support "top sites" - but it is coming.)
