### ISSUE TITLE
1.5 MB increase to APK size from hyphenation dictionary (around Nov 14)

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#7223]
There was a 1.5mb increase in the size of the APK on/around Nov 14th.

It likely comes from either android components or geckoview. The version was bumped to 22 that night (from 21).

**Comment by mcomella** [comment]
I've taken the action items in the previous comment. This is unlikely to be a priority in the short term for the perf group but we'll see from triage.

**Comment by heycam** [comment]
I don't think such a large change in APK size was expected. @jfkthame I assume that the new binary format files are smaller in uncompressed size, but maybe they don't compress as well as the old text-based files?

**Comment by jfkthame** [comment]
The new binary files are (generally) *larger* than the old text-based files, because they don't simply list the hyphenation patterns but rather encode a finite state machine that can efficiently match those patterns at runtime. With the (smaller) text-based files, the equivalent state machine has to be created in RAM when the hyphenation resource is loaded (and then occupies several times more memory than the new binary files). So although the on-disk resources are larger, the end result is that we use less memory to implement hyphenation at runtime.

Is geckoview using a compressed omnijar (like current Fennec, AIUI) or uncompressed (like desktop Firefox)? What kind of compression is used? Maybe the binary files can be compressed more effectively than we're currently managing.

**Comment by heycam** [comment]
If we are unable to compress them more effectively, would it make sense to go back to using the text-based files on Android (so basically doing the build time step at run time), since we have to allocate memory for the state machine anyway?  We'd lose the performance benefit from not needing to generate the state machine the first time a content process uses hyphenation in a given language, but we'd still have the memory gains from sharing the data across processes.

**Comment by jfkthame** [comment]
Yes, we could explore that option if we can't achieve good enough compression of the binary files. There could be further trade-offs we'd need to look at if we go that way: currently, the mapped_hyph state machine compiler does extra work (compared to libhyphen's file-load) to make the resulting machine more compact (identifying and merging duplicate states), but that might be too expensive to do at runtime.

**Comment by mcomella** [comment]
@heycam @jfkthame Is it too late to do something about this issue? Has APK size been improved in more recent versions?

**Comment by jfkthame** [comment]
There's been no change here, AFAIK. (I don't know whether the overall APK size may have changed significantly because of unrelated issues, but the hyphenation data, at least, hasn't been touched.)

If we could get an answer to my [questions re the GV omnijar format -- is it internally compressed?](https://github.com/mozilla-mobile/fenix/issues/7223#issuecomment-566289351) above, that would help clarify possible mitigations we could try here.

**Comment by mcomella** [comment]
> Is geckoview using a compressed omnijar (like current Fennec, AIUI) or uncompressed (like desktop Firefox)? What kind of compression is used? Maybe the binary files can be compressed more effectively than we're currently managing.

@snorp Can you answer this?

**Comment by jfkthame** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1667192 to look into possibly mitigating the size here.
