### ISSUE TITLE
[Bug] Pixel 2 API 28 x86 Emulator - Unable to turn on "Set default browser" switch 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7274]
## Steps to reproduce
1. Create a Pixel 2, or Pixel 3 API 28 x86 Emulator in AS.
2. Install the fenix debug app
3. Set as default browser by going to Settings>Set as default browser, tap the switch and select Firefox Preview as default.
4. Return to the Set default browser screen by tapping the device back button
5. Check the switch is on.
### Expected behavior
Switch is on.
### Actual behavior
Set default browser switch is not enabled.
Doesn't reproduce on the physical Pixel 2 device, or on API 29 (Q).
### Device information

* Android device:  Pixel 2 API 28 x86 Emulator. 
* Fenix version: geckoNightlyDebug version

**Comment by boek** [comment]
@sv-ohorvath Is this something that is important for automation/testing? If so feel free to bump to a P2 👍

**Comment by sv-ohorvath** [comment]
@boek It is blocking me to run my tests locally, but it's not urgent. I noticed that on the first install this doesn't happen (on a data swiped device). If it was already installed once and already set as default, it will not toggle the switch On (it should be automatically on if it's already set).

**Comment by sv-ohorvath** [comment]
Also happening on Firebase, same device configuration: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6930189069925175076/executions/bs.379f518947b45a01/test-cases

**Comment by sv-ohorvath** [comment]
blocked test: https://github.com/mozilla-mobile/fenix/blob/openLinksInPrivateMode/app/src/androidTest/java/org/mozilla/fenix/ui/PrivateModeTest.kt#L57

**Comment by Mugurell** [comment]
Found this to be happening  &nbsp;&nbsp; because
`Open links in a new tab` from Settings -> Set as default browser is disabled  &nbsp;&nbsp; because
[BrowsersCache.all(requireContext()).isDefaultBrowser](https://github.com/mozilla-mobile/fenix/blob/d10a30e356188868f801e403fd29cd24e8737f77/app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserSettingsFragment.kt#L58) returns false &nbsp;&nbsp; because
[packageManager.resolveActivity(..)](https://github.com/mozilla-mobile/android-components/blob/22c0e34d3f64a2606ed539d60bc1f9dd3e6a5ebb/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt#L264) returns a different app (`com.google.android.setupwizard` in my tests)

The tests fail intermittently but after they do we can see `Android Setup`(with the above package name) appearing in the list of default browsers in Android Settings.
Curiously in Android's settings Fenix does appear as default
when opening a link it is opened in `Android Setup` who then passes the Intent to Fenix
and then `Android Setup` dissappears from the list of browsers.

Video - https://drive.google.com/file/d/1Suz6-oSXBaORI80LTpvPr63Ibic2dV7y/view?usp=sharing

<img width="449" alt="image" src="https://user-images.githubusercontent.com/11428869/73857586-d4e2e300-483f-11ea-8bd8-d900624bacb2.png">

**Comment by Mugurell** [comment]
Somewhat related issue in which it is recommended to disable `Android Setup`
https://issuetracker.google.com/issues/37119296

**Comment by Mugurell** [comment]
Thinking about this more an ugly solution would be to just use 
`adb shell pm hide com.google.android.setupwizard` 
maybe before the check for default browser!?

Otherwise, as Oana confirmed this doesn't happen with Android API 29 emulators maybe we could change the CI configuration so that the tests would run on these, versus the current Android API 28 emulators?

Tagging @liuche who may know better to choose between the two.

**Comment by sv-ohorvath** [comment]
> Thinking about this more an ugly solution would be to just use
> `adb shell pm hide com.google.android.setupwizard`
> maybe before the check for default browser!?
> 
> Otherwise, as Oana confirmed this doesn't happen with Android API 29 emulators maybe we could change the CI configuration so that the tests would run on these, versus the current Android API 28 emulators?
> 
> Tagging @liuche who may know better to choose between the two.

And @rpappalax

**Comment by sv-ohorvath** [comment]
This is not a blocker anymore, as https://github.com/mozilla-mobile/fenix/issues/5905 has just landed and we can avoid this situation probably until later.
