### ISSUE TITLE
The text cursor disappears after clearing an autocomplete url

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#733]
## Steps to reproduce
1. Tap the search bar.
2. Type f and facebook.com will be autocompleted.
3. Tap the "x" button to clear the url.
### Expected behavior
URL bar is cleared, the text cursor is displayed.
### Actual behavior
URL bar is cleared, the text cursor is gone. You can still type a new search term.
Clearing search terms or already loaded page URLs, will show the cursor.
### Device information

* Android device: Huawei P20 lite (Android 8.0)
* Fenix version: 1.0.1909

**Comment by sblatz** [comment]
This is an a-c issue with the `InlineAutocompleteEditText`. I was able to reproduce on the latest Fenix master as well as Sample Browser.

I filed an [ac issue]()

**Comment by AndiAJ** [comment]
Hi, the issue is still replicating on the latest Fenix Build **`#11840608 from 2019-07-03`** using the following devices:
• OnePlus6T (Android 9)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

►Video from OnePlus6T
![OnePlus](https://user-images.githubusercontent.com/51314259/60580896-8b548600-9d8e-11e9-91e2-da9162005e90.gif)

Moreover, I've bumped into another issue on a Samsung Galaxy S8+ (Android 8), namely, after pressing the clear button, the string previously added isn't cleared

►Video from Samsung Galaxy S8+
![SamsungS8](https://user-images.githubusercontent.com/51314259/60581164-0027c000-9d8f-11e9-9705-c9608e76ac71.gif)

**Comment by sblatz** [comment]
@AndiAJ Are you able to test again off the latest master? I just tested on the nightly build on my device (Galaxy S9) and cannot reproduce either of these issues. 

(Nightly 190703)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix Build `**#11850611 from 4/7** `using the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1) 

►Video from Google Pixel 3XL
![2019_07_04_10_48_54](https://user-images.githubusercontent.com/51314259/60649241-5574d780-9e4a-11e9-994a-89fb926d2888.gif)
