### ISSUE TITLE
[Bug]The app crash after sharing multiple times a collection

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7343]
## Prerequisites
1. You are connected to a Firefox account with two devices;
2. You have at least one collection created;

## Steps to reproduce
1. Tap on the 'share' button from your collection;
2. Tap 2-3 times on the second device icon;

### Expected behavior
The tabs are sent to the second device;

### Actual behavior
After sharing the tabs, the app crash.

### Device information

* Android device: Oneplus 5T (Android 9), LG G7 fit (Android 8.1) and Nokia 6 (Android 7.1.1);
* Fenix version: Firefox Preview Nightly 12/23 #13570607
* Not reproducible using Firefox Preview RC 3.0.1 #13502256
* [logcat](https://github.com/mozilla-mobile/fenix/files/3995100/logcat.txt)

**Comment by AndiAJ** [comment]
Hi using a Google Pixel 3a (Android 9)

✔️ Not reproducible on :
Fenix Nightly build from 11/15
Fenix Nightly build from  12/5
Fenix Nightly build from  12/6
Fenix Nightly build from  12/7
Fenix Nightly build from 12/10

❌ Reproducible on:
Fenix Nightly build from 12/13
Fenix Nightly build from  12/20

@gabrielluong  - Please share your thoughts on this,  in regards with #5574 
Could this issue be caused by something else, considering the fact that [PR #6651](https://github.com/mozilla-mobile/fenix/pull/6651) was merged on 12/05 ?

**Comment by gabrielluong** [comment]
This is likely not due to the libstate migration since I am reusing the previous logic of showing the share fragment with the list of collections.

**Comment by sv-sdeiac** [comment]
I found a different scenario to reproduce the crash.
1. Open different tabs;
2. Share tabs by tapping multiple times on the second device icon;

The issue is still reproducible for any type of sharing(private, normal, collection, open tabs, history).

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Nightly 1/10 #20100616.

Devices:
- OnePlus 5T (Android 9);
- Xiaomi Mi 8 Lite (Android 9);
- LG G7 fit (Android 8.1).

**Comment by sv-sdeiac** [comment]
This issue is reproducible on the latest version of Beta 3.1.1-beta4 #20170728 on OnePlus 5T (Android 9).
