### ISSUE TITLE
Check non-startup user flows for performance problems

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7380]
We've invested a lot of time investigating perf during startup and not so much outside of startup: we should identify which user experiences are important to investigate and check them for performance problems (like mstange has been doing).

### Acceptance criteria
- Identify a list of user experiences to investigate (consult ecsmyth)
- List of user experiences is stored on Performance drive so we can revisit it
- Then, EITHER (depending on scope?):
  - Do it all now: investigate performance of all identified user flows and file issues for identified performance problems. These issues should go to triage
  - Parallelize: a new issue is filed for each user flow to investigate. These issues should be prioritized the same in the backlog as this issue

**Comment by mcomella** [comment]
Triage: it may make more sense from someone on the product team to decide the important workflows.

**Comment by mcomella** [comment]
@ecsmyth Please update the description if it doesn't match your expectations. If you have an initial list of user experiences, that'd be great too (maybe from https://github.com/mozilla-mobile/fenix/issues/8662 ?).

**Comment by ecsmyth** [comment]
[Prioritized list for investigation](https://docs.google.com/document/d/1VKN5KsvFDIj-SooRcDLZ4FjRa1tzvfIeseW_CG9ZIII/edit?usp=sharing). I recommend breaking out each high-level action into separate issues.

Several of the flows in the linked document do not have drafted release criteria. I'm working to address this now, but please ping me if resources are available to start an action that is still missing criteria.

When investigating, please identify variations of the flows that should be covered by release criteria because of performance-impacting implementation details not captured by the existing criteria. An example being the "Save to Collection" criteria that does not specify the number of existing collections. If this flow is impacted by the number of collections similar to how startup is impacted, then lets capture that with an issue to modify or add release criteria to cover user-representative quantities of collections.

**Comment by mcomella** [comment]
> Prioritized list for investigation. I recommend breaking out each high-level action into separate issues.

I said I'd do this but to save time, I'm not going to. When addressing this bug, please:
- Leave it in the Backlog unassigned so this issue can be parallelized
- Select one item from the list Eric linked and file a bug to represent it: assign yourself and move to In progress
- In the linked document, add a note mentioning you've filed the bug for that item
- Work on the bug
- Repeat until they're all gone

Let me know if you have any questions.

**Comment by mcomella** [comment]
Moved to JIRA: https://jira.mozilla.com/browse/FXP-1249
