### ISSUE TITLE
[Bug] Two different kinds of "Share" buttons in custom tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7431]
## Steps to reproduce
Open a custom tab from any other app
### Expected behavior
There should be one button to share either on the address bar or on the 3 dot menu. preferably this should open the firefox link share menu
### Actual behavior
There are two such buttons, on the address bar and the other on the 3 dot menu. Both function differently. The address bar option opens up the standard android text share menu. The 3 dot menu option open up the firefox specific link share option.
<p float="left">
<img src="https://user-images.githubusercontent.com/33252312/71614084-c6b1ff00-2bcf-11ea-96ae-f89c6953dfe7.png" width="200"/>
<img src="https://user-images.githubusercontent.com/33252312/71614087-c87bc280-2bcf-11ea-8e1d-86c0dfcb16ad.png" width="200"/>
</p>
### Device information
* Android device: Asus Zenfone Max Pro M1

* Fenix version: 
Nightly 191230 18:01 (Build #13641809)
27.0.0, 202f6d4f8
GV: 73.0a1-20191227094418

**Comment by ekager** [comment]
The action in the toolbar is sent to our custom tab with a pending intent from the originating app [(See `CustomTabActionButtonConfig`)](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabConfig.kt#L66). In this case, the app is sending an intent to launch the system share sheet. The action in the menu is controlled by us and launches our custom share sheet. 
I'm not sure if this bug is actionable.

**Comment by ekager** [comment]
It appears I was wrong (AC adds a share button to the toolbar unless the calling app gives us a custom action) and @NotWoods submitted a fix to remove the duplicate menu item :)

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 1/13 #20130605.

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 2 (Android 9);
- Google Pixel (Android Q).
