### ISSUE TITLE
Consider removing Lottie for blocking the main thread & to reduce APK size by 188.7 KB (already proguarded)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7435]
According to the Analyze APK tool on my proguarded `forPerformanceTest` build, the Lottie dependency takes up 188.7 KB in the proguarded APK. It additionally defines 1203 methods, which I believe will slow startup time (but I'm not sure by how much). afaict, it's only used in one class (`ToolbarIntegration`): it's unlikely that this one call is worth 188.7 KB. Assuming we don't intend to add significantly more usages in the future, we should consider removing it.

In general, we should avoid taking on large dependencies if we're only going to use them in one place.

**Comment by mcomella** [comment]
Startup perf impact is unknown but adding to perf board to keep it on our radar.

**Comment by jesup** [comment]
Looking at simpleperf profiles (both with intent start and browsertime start) in https://perfht.ml/3cr91fN and https://perfht.ml/2TzroH1 shows ~100ms taken at startup in com.airbnb.lottie, not an insignificant amount.  It is on a pool thread, so may not block critical operations if there are cores free.

**Comment by kbrosnan** [comment]
Lottie also blocks us on upgrading MockWebServer. See https://github.com/mozilla-mobile/fenix/issues/8169#issuecomment-600231224

**Comment by ekager** [comment]
Documenting our discussion from Matrix in this bug:
- We currently use Lottie only for the ETP shield animation
- We use Lottie instead of Android Vector Drawable because AVDs don't support gradients until 24+
- Longer term we could work with UX to find a solution that would allow us to use AVDs (or something else) and remove Lottie

**Comment by AaronMT** [comment]
Our team would like to upgrade Mockwebserver as soon as possible. We are using 3.11.0 (July, 2018) and 4.5.0 just shipped (April, 2020). Upgrading for this fix seems worth it alone:

> This release fixes a severe bug where OkHttp incorrectly detected and recovered from unhealthy connections. Stale or canceled connections were incorrectly attempted when they shouldn't have been, leading to rare cases of infinite retries. Please upgrade to this release!

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/11627 for investigating main thread perf issues with Lottie.

**Comment by AaronMT** [comment]
Based on these, will Lottie will be removed?

**Comment by mcomella** [comment]
In https://github.com/mozilla-mobile/fenix/issues/11627#issue-639276202, I added notes about main thread perf issues with Lottie including a profile with up to a 100ms delay on a Galaxy S5.

**Comment by AaronMT** [comment]
@mcomella @liuche @AmyYLee (no idea who else to tag here :) ) – can we get the ball rolling on removal of Lottie? Recall we can not upgrade the MockwebServer dispatcher (https://github.com/mozilla-mobile/fenix/issues/8169) see: https://github.com/mozilla-mobile/fenix/blob/master/buildSrc/src/main/java/Dependencies.kt#L40 which is using 3.11.0 from 2018 and OkHttp 4.x relies on Okio 2 which creates a circular dependency because we use Lottie from AirBnB which still requires Okio 1 (https://github.com/airbnb/lottie-android/blob/master/lottie/build.gradle#L36).

Upgrading our Mockwebserver is a need to bring in sec fixes and stability improvements in our testing

**Comment by ekager** [comment]
New behavior for the shield icon should be: 
API 21-23 - Solid blue shield fade in animation on sites with blocked content 
API 24+ - Blue to purple gradient shield fade in animation on sites with blocked content

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201019`** build using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

**►Screenshot  - OnePlus A3 (Android 6.0.1)**
![rsz_screenszzhot_20201019-122228](https://user-images.githubusercontent.com/51314259/96427476-45cbfe80-1207-11eb-85ea-3a19cf56651d.png)

**►Screenshot Google Pixel 3a (Android 11)**
![rsz_screenshot_20201019-1223332255](https://user-images.githubusercontent.com/51314259/96427485-4795c200-1207-11eb-9d51-7370ec202817.png)
