### ISSUE TITLE
Leanplum has a large impact on cold startup (5.68% to first frame drawn)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7448]
We're trying to move everything non-essential until after visual completeness in order to improve startup time. We should see if we can move Leanplum too. If not, consult the team: if the impact on startup is non-trivial, we may wish to remove it for GA until we can come up with a better solution.

---

_old comment 0_

Note: #6679 already exists but I'm not sure what the deliverables are so I filed a new issue: maybe we can dupe.

`Leanplum.start()` is pretty slow: it is 11.21% of `FenixApplication.onCreate` and has various intermittent startup problems that take up even more time: #7442. It may take up additional time to startup in other methods too.

We should consider creative solutions in order to improve leanplum performance on cold startup:
- Open PRs against the open source SDK
- Fork the SDK
- Write our own wrapper around the Leanplum API (Will's idea)
- Defer init until after startup
- Init off the main thread (this was tried already and may not be possible)
- Remove it entirely

**Priority recommendation:** this issue may take a long time to implement so it's probably mid-range priority.

---

Jan 19 update: when commenting out `LeanplumMetricsService`'s initializer, I see a 5.68% improvement in Displayed time, Pixel 2, local geckoBetaFenixBeta build: 395.83ms to 373.33ms.

This is with a debug key: Leanplum may have a smaller impact in release variants.

### Acceptance criteria
- Identify best course of action wrt improving Leanplum performance
- Attempt to implement or close this issue if unactionable

**Comment by hawkinsw** [comment]
1. Writing our own wrapper around the API would be far more difficult than @boek and I originally imagined. When we discussed this option, we thought that we did not use Leanplum's Push mechanics. After talking to @jonalmeida, we realized that this is not the case. Reimplementing their Push mechanics would be relatively expensive (in terms of time and testing) and probably not something that we want to pursue.
2. With respect to deferring initialization until after startup, this is the option that @jonalmeida is pursuing in #6730.
3. There is a relatively straightforward path to initialization of Leanplum off the main thread. It is not without risk, however. Based on my understanding of the SDK (albeit yet limited), there is a single action that absolutely must be performed on the main thread when the SDK is initialized. That is a call to the `OsHandler.getInstance` method. It is possible to make that call directly to the SDK (because it's an invocation of a static method) and then do the entirety of the initialization off the main thread. If this is something that we want to pursue, we will need to discuss the tradeoffs. One of the (many) risks with this approach could be mitigated if we forked the SDK.  Though there are tradeoffs, this option is viable and something to investigate further.
4. I like the idea of removing Leanplum entirely, but from the product perspective, that does not seem to be a viable option.

**Comment by hawkinsw** [comment]
Wanted to track in here the open PRs that are up for consideration w.r.t this issue:

1. Caching the results of `Browsers.all()` in Fenix: See PR https://github.com/mozilla-mobile/fenix/pull/7490 
1. Setting the user Leanplum session's user attributes after calling `Leanplum.start()`: See PR https://github.com/mozilla-mobile/fenix/pull/7475

It seems like taking *both* steps is worthwhile. Landing (1) will reduce the performance impact of building the hash map of user attributes used in (2) but I think that there could be other places where the `MozillaProductDetector` is still slow and building that map asynchronously is not a bad idea. 

Please let me know what you think, @mcomella and @MarcLeclair

**Comment by mcomella** [comment]
Triage: we'll wait until next week to see if a larger effort needs to be made here.

**Comment by mcomella** [comment]
Ping stefan to discuss Leanplum opportunities.

**Comment by mcomella** [comment]
Apparently, leanplum is initialized in the background on Fennec ([source](https://searchfox.org/mozilla-esr68/rev/91c2c3f196069f2c90bbd774ad622ea5e1245f9f/mobile/android/base/java/org/mozilla/gecko/BrowserApp.java#991)). In a worst case, I guess we could init in the background and it'd be no worse than fennec :grimacing:

**Comment by MarcLeclair** [comment]
Found out quite a bit today: Moving our `LeanplumMetricsService` off the MT (or later) would be possible. It's not used for critical stuff for our app to start.  To add on top of that, Regular cold start runs _with_ LeanplumMetrics (on a G5+) will vary from 820ms-900ms. Without LeanplumMetrics (just for testing ofc) we get ~750ms-780ms. At worse a 40-50ms gain and at best 150ms gain. @mcomella. Imo, this stuff isn't critical for user experience. From what I gathered, it seems safe to later init or Async init (that's up to us). 

Note: I'm also assuming these time stamps get worse with lower end devices and better with higher end devices.

**Comment by AndiAJ** [comment]
Hi @mcomella , can you help us out with a STR to test this matter? ☺️

**Comment by mcomella** [comment]
@MarcLeclair ^

**Comment by AndiAJ** [comment]
Hi @MarcLeclair , could you help us out with a STR  to test this problem?

**I'll remove the QA needed label until further notice**

**Comment by csadilek** [comment]
We've landed @MarcLeclair's PR a while ago: https://github.com/mozilla-mobile/fenix/pull/8558

We've also recently upgraded LP and tested it so I don't think this older ticket needs QA. Closing.
