### ISSUE TITLE
Improve performance of SecureAbove22Preferences in cold startup (40ms perfTest)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7450]
Note: some of the init of SecureAbove22 will happen in https://github.com/mozilla-mobile/fenix/issues/8056

`SecureAbove22Preferences` takes up 9.66% of `FenixApplication.onCreate` start time:
- `Core.getSecureAbove22Preferences` is 3.90%
- `SecureAbove22Preferences.getString()` is 5.76%

We should see what we can do to improve performance – e.g. can this be deferred until after startup?

### Priority
**Difficulty** (1-5): 2? Patch already in progress.

**Impact** (Pixel 2): 
  - `forPerfTest`: 41.72ms

---

@MarcLeclair Please add any additional details as necessary!

I think there may be some `SharedPreferences` disk accesses that are causing this.

**Comment by MarcLeclair** [comment]
So, for a quick summary: the implementation of the SecureAbove22Preferences is done in AC but, I think we should be able to go read it in a background thread. I did a quick implementation to try it out ( anyone is welcome to test it too to make sure I didn't do anything to break the app with other flows). 

[Here's my branch](https://github.com/MarcLeclair/fenix/tree/issue_7450_SecureAbove22Preferences_perf)

Trace with original code: 
[SecureAbove22Preferences_trace.zip](https://github.com/mozilla-mobile/fenix/files/4013613/SecureAbove22Preferences_trace.zip)

**Comment by mcomella** [comment]
@ekager I see you're assigned to https://github.com/mozilla-mobile/fenix/issues/8324: do you think that bug will remove SecureAbove22Preferences init on Release and Beta channels?

I'm not sure we want the behavior to diverge significantly but it could be a way to speed up those channels a bit.

**Comment by ekager** [comment]
@mcomella so #8324 was because we were seeing crashes with using the Keystore and want to continue to monitor those in Nightly. The solution was to force the insecure storage impl in `SecureAbove22Preferences` via #8446 and AC changes mozilla-mobile/android-components#5902

Release/Beta will still init `SecureAbove22Preferences` in a likely similar fashion. The only change I can think of that would possibly help perf is that I added a way to try to migrate secure -> insecure and insecure -> secure on every init (so we could in theory flip back and forth via this `forceInsecure` flag) but only if the current selected prefs are empty (so hopefully just on first startup?)

Let me know if this makes sense

**Comment by mcomella** [comment]
Before working on this issue, if possible, validate the performance impact of `SecureAbove22Preferences` in a release variant.

**Comment by mcomella** [comment]
Triage: @csadilek said there is a PR open to get rid of this during startup and that we should re-evaluate after that lands.

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/fenix/pull/8875 removes `passwordStorage` init (and `SecureAbove22Preferences` access) from the startup path.

**Comment by mcomella** [comment]
@grigoryk Do you think this issue can be closed then?

**Comment by grigoryk** [comment]
Not yet. Currently, we're triggering it via engine initialization. I'm working through it right now - fixed the engine init problem, now need to deal with background services touching this stuff.

**Comment by grigoryk** [comment]
See https://github.com/mozilla-mobile/fenix/issues/7450
