### ISSUE TITLE
Investigate `setupCrashReporting` perf improvements on cold startup (31.66ms perfTest total)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7452]
At all hands, we discussed removed Sentry or delaying its init until after visual completeness. Check with the Fenix & a-c teams if this is possible. Stefan also had a concern that we might be over our quota for server use in the release population – keep it mind it may not even be possible to use Sentry effectively.

Priority recommendation: low amount of gains, high risk so lowre.

---

_Old comment_

`setupCrashReporting` takes 5.67% of `FenixApplication.onCreate` (though 1.55% can be fixed by #7441). This method initializes several different services so **we may be hitting diminishing returns.** This ticket is to investigate if there is any decent perf improvements here and fixing them if so.

In particular, I wonder why we initialize 3 crash reporting services (Socorro, Glean, Sentry) on startup: can we initialize 1 on startup and initialize the others later? If we did this, would it have a significant startup improvement though?

**Comment by hawkinsw** [comment]
It might be possible to pass the `services` parameter to the `CrashReporter` constructor by lazy. That means that only when those services are actually needed by the `CrashReporter` to report a crash will they actually be instantiated. That said, 
1. I only did a minimal investigation
2. It might not be possible because to initialize those services *after* a crash because the application is in such a bad state that all further execution is impossible. 

I am happy to investigate this further, if you would like?

**Comment by mcomella** [comment]
>
> I am happy to investigate this further, if you would like?
>

Let's wait for this issue to be prioritized: iirc, I don't think there are
huge wins here.

**Comment by mcomella** [comment]
btw, thanks for adding notes with your understanding to these newly filed
issues. :)

**Comment by mcomella** [comment]
Closing: we're going to revisit startup holistically.
