### ISSUE TITLE
Improve performance of SessionControlView.init

### ISSUE THREAD

**Issue by emalysz** [mozilla-mobile/fenix#7465]
It is slow to create the HomeFragment (#4665).`SessionControlView.init`takes up 14.40% of `FragmentManager.moveToState` which creates the HomeFragment.

All time is spent within the `view.consumeFrom` call.

We should see what we can do to improve performance.

**Comment by hawkinsw** [comment]
Can you add your profile to this? I cannot recreate the attirbution of the delay in `SessionControlView.init<>` to `SessionControlView.consumeFrom()`.

**Comment by emalysz** [comment]
[HomeFragment.trace.zip](https://github.com/mozilla-mobile/fenix/files/4021249/HomeFragment.trace.zip)

**Comment by jimporter** [comment]
Looking at a locally-generated profile, it seems like 90% of the time inside `view.consumeFrom` is spent inside `androidx.lifecycle.LifecycleRegistry.addObserver`, from this call:

https://github.com/mozilla-mobile/android-components/blob/ebf112c3ec10a0bf5924bba117cac96da68873a4/components/lib/state/src/main/java/mozilla/components/lib/state/ext/StoreExtensions.kt#L126

I'm not super-familiar with this code, but that seems like something we need to have and that'd be hard to avoid/improve. @emalysz or @hawkinsw, do you have any ideas here, or suggestions on who I should ask about this?

**Comment by jimporter** [comment]
Here's a WIP patch based on @MarcLeclair's prior work: https://github.com/jimporter/fenix/commit/6864bd80014f366073f697ee070657bd088f24eb

I think there's a race condition in it that sometimes causes the SessionControlView to not render. However, it also doesn't seem to have a meaningful performance benefit anyway, and really just makes it take longer to load everything. While we're saving the 150ms or so from initializing SessionControlView synchronously, the async process takes ~1300ms to finish its work and let us render the rest of the UI. (Note: this is while profiling with trace logging, so end users would see faster results, but I still don't think it would result in an overall improvement of either "real" load times or perceived ones.)

**Comment by jimporter** [comment]
On current master, I'm seeing some new behavior: `SessionControlView.init` is faster (117ms, compared to ~150ms previously), only now we're also spending half our time (58ms) in `LayoutInflater.inflate`, with most of the remainder in `view.consumeFrom` (44ms).

However, with @MarcLeclair's patch in #8085, I'm no longer seeing `LayoutInflater.inflate`, so `SessionControlView.init` takes only 55ms (with `view.consumeFrom` taking 41ms). I think that reduces the importance of this issue quite a bit, since `SessionControlView.init` only takes 4.6% of the time in `FragmentManager.moveToState`.

As a possibly-interesting side note, the patch in #8085 does seem to move `SessionControlView.init` about a half-second later than on master (measured from when the app starts spawning new threads).

**Comment by mcomella** [comment]
Jim mentions there isn't much to be done here: closing. Jim may follow-up with a small investigation but closing to avoid making the project board too confusing.
