### ISSUE TITLE
Adding startpage.com as a search engine does not show startpage favicon

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#7491]
Install startpage.com as a search engine. Its favicon does not appear. I get a generic S favicon.

Its favicon DOES appear on Fennec, but not on Fenix.

thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15051)

**Comment by EmberHeartshine** [comment]
Perhaps a solution similar to the [Add custom search engine](https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/) plugin, with a text field that auto-fills to the favicon URL but also supports data URLs for custom favicons.

**Comment by crisalis2** [comment]
In general, Fenix basically doesn't fetch favicons for custom search engines, but it should.

**Comment by crisalis2** [comment]
This is still a valid issue... Pretty sad this new "stale bot" scheme... It only means issues are ignored even more now.

**Comment by EmberHeartshine** [comment]
> It only means issues are ignored even more now.

Agreed... Pretty discouraging to the casual contributor.

**Comment by AndiAJ** [comment]
Still reproducible on **`Firefox 88.0.0 Beta 1`** using a OnePlus A3 (Android 6.0.1)

**Comment by carallo** [comment]
Is this so complicated to be fixed? Seems a pretty important bug to me, all other browsers let you add search engines pretty easily, automatically fetching favicon and search suggestion url...

**Comment by lobontiumira** [comment]
This is still reproducible on 6/30 Nightly build with Google Pixel (Android 10).

**Comment by Nojuuu** [comment]
I also had this issue with Qwant and Brave Search, but after literally spamming delete and add atleast like 70 times for both, it somehow managed to fetch the favicon for those.

Maybe the same can happen with Startpage, if you get lucky, but I haven't seen it happen yet.

**Comment by Nojuuu** [comment]
Could the favicon fetching logic be improved in such a way that it would look if favicon for an almost identical address already exists in the history and take the favicon from there?

**Comment by EmberHeartshine** [comment]
This issue continues to persist.

**Comment by Pjjlltt** [comment]
This is still an issue on Nightly 106.0a1 (Build #2015904459). 
The workaround that is mentioned above where you visit the search page, with the url search adress, including %s and then go back to settings >search and select to edit the search engine, and just tap the check mark in top right corner will fetch the favicon for Brave Search and a couple of different SearXNG instances however _not_ for Startpage. 

On release version of Firefox, 104.2.0 (Build #2015902899) the workaround to get favicon works on both Brave Search, SearXNG _and_ Startpage.

Since the favicon fetching does not work automatically this is still a valid issue.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807574

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
