### ISSUE TITLE
[Bug] Fenix has trouble opening binary files

### ISSUE THREAD

**Issue by matejdro** [mozilla-mobile/fenix#7495]
## Steps to reproduce

1. Install [GadgetBridge](https://f-droid.org/en/packages/nodomain.freeyourgadget.gadgetbridge/)
2. Go to https://apps.rebble.io/en_US/application/52cc44e045ffdd31dd000180?dev_settings=true
3. Click on "Download PBW"
4. Try to open downloaded file

### Expected behavior

File should be opened by GadgetBridge. This can be verified by using native downloads screen.

### Actual behavior

Fenix errors out with "Could not open file".

### Device information

* Android device: OnePlus 7 Pro running Havoc OS (Android 10)
* Fenix version: Nightly 200105 18:00

![ezgif-7-205b05c0a3c3](https://user-images.githubusercontent.com/507922/71786553-c325da00-300c-11ea-8a87-5203e6047021.gif)

**Comment by sv-sdeiac** [comment]
Hello, thanks for your report. 
I can confirm that this issue is reproducible using the latest version of Nightly 1/6 on Nexus 5 (Android 6.0.1), LG G7 fit (Android 8.1) and Google Pixel (Android Q). 
I want to specify that also with the Chrome browser I wasn't able to open the files.
### Notes:
- Gadgetbridge app is only the unofficially build for Playstore.

**Comment by matejdro** [comment]
Possible duplicate of https://github.com/mozilla-mobile/fenix/issues/4044?

**Comment by matejdro** [comment]
This still appears to happen

**Comment by matejdro** [comment]
Actually, this seems to have been fixed in the recent builds.
