### ISSUE TITLE
[Bug] Contrast Issue with disconnected device warnings in 3 dot menu

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7504]
## Steps to reproduce
Disconnect firefox account login for fenix from accounts.firefox.com
open 3 dot menu either in a webpage or in the overview
![Screenshot_20200104-112810](https://user-images.githubusercontent.com/33252312/71839223-95936c00-30b2-11ea-8670-5c8defaa68ca.png)
![Screenshot_20200104-112818](https://user-images.githubusercontent.com/33252312/71839249-a2b05b00-30b2-11ea-8398-67ffb063a23a.png)

### Device information

* Android device: Asus Zenfone m1
* Fenix version: 

Nightly 200106 06:00 (Build #20060606)
27.0.0, 25da25a0d
GV: 73.0a1-20200105094728

**Comment by brampitoyo** [comment]
@s-ankur @mcarare This problem looks funky.

A couple of observations:

- I noticed that the background colour changes, but the icon colour stays red.
- What should the colour of these highlighted items be?
    - We do have `accent` colours, but if we apply that here, it would look too bright
    - We also have an `on-light` and `on-dark` colours with transparency percentages (8, 12, 16, 36, 60%) – perhaps this is a better idea

**Comment by brampitoyo** [comment]
I’d like to get a better understanding of where the problem comes from, to see whether we need to solve it with a new design, or just fix it by making the colour identical to all other list items.

**Comment by darkwing** [comment]
To repeat:

1.  Pair your phone
2.  Disconnect the pairing from "Manage Devices" on desktop
3.  Force-close the app on phone
4.  This effect should be there

**Comment by darkwing** [comment]
@AmyYLee What colors would you like use to use for these icons?

**Comment by AmyYLee** [comment]
> I’d like to get a better understanding of where the problem comes from, to see whether we need to solve it with a new design, or just fix it by making the colour identical to all other list items.

Hi, I agree with @brampitoyo about needing more context.
So we highlight the settings item if the user has disconnected from their Sync account? I'm wondering if this is really necessary to alert them at the top level of the 3-dot menu. I'm thinking this would be highlighted if the user goes into settings and we notify them that their sync account is disconnected.

**Comment by darkwing** [comment]
Interesting.  So context-wise, yes, the way to trigger this is to connect your account, then disconnect it via the browser, and restart Fenix.  IMO showing the indicator on the 3-dot menu is good, as it implies their history and bookmarks may not be in sync.  For the purpose of moving forward, however, I'm looking to know what colors we should use for the "Settings" icons and background, as well as the top "Reconnect to resume syncing" header.


![Screenshot_20200219-224026](https://user-images.githubusercontent.com/46655/74884428-c5cc5c80-5338-11ea-9d56-9e836678a101.png)

![Screenshot_20200219-224054](https://user-images.githubusercontent.com/46655/74884426-c4029900-5338-11ea-9eaf-62750f98768f.png)

**Comment by brampitoyo** [comment]
@darkwing – @AmyYLee and I went through the same set of screens and reached the same conclusion: showing warning in the Main Menu is good.

Unfortunately, I’m not able to create a collection; so instead of linking to one Abstract URL, I will have to link to individual artboards below.

-----

First thing first, on the three-dot icon, we recommend removing the yellow overlay + dot.

<img width="360" src="https://user-images.githubusercontent.com/51007/74895006-61230780-53f5-11ea-8355-6cd6a71c8c40.png">

---

Inside the main menu, we prefer a separate menu item called “Reconnect to sync”.

<img width="720" src="https://user-images.githubusercontent.com/51007/74892437-73e60e00-53ee-11ea-9f08-a6fc5d034480.png">

- Light theme: https://share.goabstract.com/40f4e482-ab61-4fd5-b771-5c21dd2c0937?mode=design&sha=b9bc6c4d44ef57f4418e3a2dc3848d62a6460701
    - Text colour: same as other labels
    - Warning icon: `#C45A27`
    - Overlay: `#FFF36E` @ 20% opacity (flattened colour value: `#FFFDE2`)
- Dark & private themes: https://share.goabstract.com/445f7ef6-0677-4ff3-8671-aefe805a3038?mode=design&sha=b9bc6c4d44ef57f4418e3a2dc3848d62a6460701
    - Text colour: same as other labels
    - Warning icon: `#FFF36E`
    - Overlay: `#FFF36E` @ 20% opacity (flattened colour value: `#5B5846`)

When tapped, this menu item should deeplink to the “Sign in to continue to Firefox Sync” webview. In other words, users will be able to bypass going into Settings, and go straight to the sign in step.

But this could present a few problems:

1. Is it easy to add a new menu item?
2. Even though the string is reused from something we already have, will it fit the menu when displayed in different locales?

-----

If this approach isn’t possible, we recommend what you’ve shown: put a warning icon to the side of Settings.

The difference is: we would change the exclamation mark icon into the “avatar warn” icon – the same one used under Settings.

<img width="720" src="https://user-images.githubusercontent.com/51007/74892675-2322e500-53ef-11ea-91b7-554523e7397f.png">

- Light theme: https://share.goabstract.com/a4e9ea36-c4bb-48ba-b4f6-4c3d7749099b?mode=design&sha=b9bc6c4d44ef57f4418e3a2dc3848d62a6460701
    - Text colour: same as other labels
    - Warning icon: `#C45A27`
    - Overlay: `#FFF36E` @ 20% opacity (flattened colour value: `#FFFDE2`)
- Dark & private themes: https://share.goabstract.com/0a5f994a-56da-40e9-a346-84db974dcc95?mode=design&sha=b9bc6c4d44ef57f4418e3a2dc3848d62a6460701
    - Text colour: same as other labels
    - Warning icon: `#FFF36E`
    - Overlay: `#FFF36E` @ 20% opacity (flattened colour value: `#5B5846`)

----

Under Settings, there’s a warning message, too.

This warning will be identical as we have today – same colours for light, dark and private themes.

<img width="720" src="https://user-images.githubusercontent.com/51007/74894566-3a180600-53f4-11ea-975f-68f2a6d55d17.png">

The only thing we need to tweak here are the colours:

- Light, dark & private themes
    - https://share.goabstract.com/1dc13190-c932-4bfd-8e80-cb080ea20706?mode=design&sha=bd59fb3762a7198e4a2581c27a6bc8eae54b13fb
    - https://share.goabstract.com/8ced52c8-d67a-4176-9469-9b4b279badfd?mode=design&sha=bd59fb3762a7198e4a2581c27a6bc8eae54b13fb
    - Text colour: `#960E18` (we had to darken it to maintain good colour contrast)
    - Warning icon: `#C45A27` (same as warning icon on light theme)
    - Overlay: `#FFF36E` (same as overlay colour in main menu, but without opacity)

**Comment by darkwing** [comment]
@magorlick Did you have any thoughts on telemetry for reconnecting to sync or the sync process?

**Comment by softvision-miralobontiu** [comment]
Verified on the 3/2 Nightly build the disconnected messages with HTC 10 (Android 8), Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1), and this is how they look on light theme and dark theme.

@brampitoyo the three-dot icon, the yellow overlay + dot, it is not removed, on light theme is barely visible.

I'll remove the qa-needed label, but not close the issue until we know if the three-dot yellow overlay will be removed or not.


![light](https://user-images.githubusercontent.com/40694158/75660258-23837180-5c74-11ea-9c74-001b477639d3.png)
![dark](https://user-images.githubusercontent.com/40694158/75660263-24b49e80-5c74-11ea-9bf6-39577a81e969.png)

**Comment by brampitoyo** [comment]
@softvision-miralobontiu wrote:

> …the three-dot icon, the yellow overlay + dot, it is not removed, on light theme is barely visible.

Let’s remove the yellow overlay and dot from all themes. @AmyYLee and I agreed that this issue doesn’t need a special notification dot. The yellow warning on its own will be enough.
