### ISSUE TITLE
Highlight `what's new` after each release

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#7506]
(issue based on https://github.com/mozilla-mobile/fenix/issues/7352#issuecomment-571146407)

### Why/User Benefit/User Problem
As a user, I want to be aware when the app changes, and easily know when to look at the `What's New` item.

### Acceptance Criteria (how do I know when I’m done?)
- After a release, the home screen three-dot-menu item `What's New` should be highlighted
- After checking `What's New`, the highlight should go away
- The home three-dot-menu should be highlighted whenever `What's New` is (engineering note, this should be handled automatically)

**Comment by Baron-Severin** [comment]
@topotropic after looking around, it looks like there's some current behavior around this:

- When the user opens the home menu
- If a new major version has been released, save today's date
- If 3 or fewer days have passed since that date, highlight `What's New` (the three-dot is not highlighted)

I will make the three-dot highlighted whenever `What's New` is, but are you otherwise happy with the behavior, or would you like me to make your other requested changes?  I'm happy to do whatever you think is best.

**Comment by topotropic** [comment]
here's the initial spec: 
- after an update to a major version, there is a blue notification dot on the 3-dot menu on home
- in the home menu is "What's new" with a blue notification dot
- the dots disappear after 3 days or once people interact with it
 https://github.com/mozilla-mobile/fenix/issues/4474

The only thing from your list above that's diverging is probably:
>     * If 3 or fewer days have passed since that date, highlight `What's New` (the three-dot is not highlighted)

Otherwise, I can't think of anything else to change at this point in time. Thanks!

**Comment by Baron-Severin** [comment]
My mistake, they do disappear after being interacted with as well.  Alright, I will work on getting the highlight on the 3-dot.  Thanks!

**Comment by sv-ohorvath** [comment]
- Verified on v3.2-beta1.
- Verified with TalkBack and a11y scanner. Logged 1 new issue: #7853  
- devices: Xiaomi Mi 8 Lite (Android 8.1), Galaxy Note 8 (Android 9), Xiaomi Mi Pad 2 (Android 5.1)
