### ISSUE TITLE
Validate top sites performance

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7513]
Like #7512, top sites is being introduced to the app #6190 and is expected to land by the end of this sprint. We should validate the impact it has on the startup of the app.

**Comment by mcomella** [comment]
The top sites PR is open: https://github.com/mozilla-mobile/fenix/pull/7523/

Looking at the layout, it dynamically creates a `ConstraintLayout` inside a RecyclerView (in `SessionControlAdapter`). I imagine this will impact startup performance but should not get in the way of any changes we try to make with the UI.

**Comment by mcomella** [comment]
Top sites appears to have landed on master.

**Comment by MarcLeclair** [comment]
Top sites seem to have pushed our performance of cold start by 30%  when 1 row only and it increases by about 5% with every row. It seems as if this is a result of loading our TopSites async since our first pass to `submitList()` with our list of `adapterItem` doesn't contain any info about Topsites, which means that our recyclerview has to resize once we get our info from `getTopSites` which then calls `dispatch()` on the `HomeFragmentStore`. This also seems to be an effect thats created by our list of tabs but isn't as noticeable since we have placeholder for those so we don't shift a lot on cold start on the screen.

**Comment by MarcLeclair** [comment]
Closed with this ticket:[ #6174](https://github.com/mozilla-mobile/android-components/issues/6174) in Android-Components which will introduce a cache to load TopSites from

**Comment by mcomella** [comment]
Let's leave this open to track the upstream issue.

**Comment by mcomella** [comment]
I don't think we need this to track the cache: we're aware of the problem and are looking at startup holistically.
