### ISSUE TITLE
Allow the user to set the home page to a URL

### ISSUE THREAD

**Issue by marker10** [mozilla-mobile/fenix#7551]
Users would like to be able to have Firefox open a web page instead of the homescreen. This allows the user to get to a consistent page to start their browsing experience.

* How does this work with Top Sites and Collections or other content on the home screen? 
* How should this behave when Firefox is swiped closed? Restore active tab or open home page?
* How should this behave when the OS kills Firefox in the background. 
* How should this behave when the user selects quit from the menu when clearing data?
* Where should this setting be placed in the settings?
* Should there be a home button/menu item?
* If there is a button/menu item where should it live?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15093)

**Comment by kbrosnan** [comment]
This does not have enough information to be a valid issue.

**Comment by topotropic** [comment]
Please add some context here otherwise we will close the issue. Thanks!

**Comment by marker10** [comment]
A customized html / web page when opening a new tab or starting the browser.

**Comment by yoasif** [comment]
This is a Fennec parity item.

![signal-attachment-2020-06-10-041000](https://user-images.githubusercontent.com/152493/84243542-59848d00-aad0-11ea-85fb-763866c40c58.png)

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1345733

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1350378

**Comment by DarkRookie00** [comment]
### How does this work with Top Sites and Collections or other content on the home screen?
It wouldn't. That would the point.

### How should this behave when Firefox is swiped closed? Restore active tab or open home page?
Add an option to change the behavior like the old versions. Prefer it to default to go to home page when reopening.

### How should this behave when the OS kills Firefox in the background.
Use the option above

### How should this behave when the user selects quit from the menu when clearing data?
Use the option 2 above

### Where should this setting be placed in the settings?
Menu -> Settings -> Customize -> Under the Home heading you could add the following:
Home page URL (about:blank should be allowed to work as well)
Reopen behavior (Restore tabs, or go to home)

### Should there be a home button/menu item?
Don't see the need to have one

### If there is a button/menu item where should it live?
But if you wanted one, either to the left of the address bar and/or in the menu under Downloads above Add-ons

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1362549

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1362942

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1363654

**Comment by kevinboone** [comment]
It blows my mind that even after what seems to be two years, it's still not possible to set a specific homepage. This is basic functionality that has existed in every browser since the 90s.

**Comment by jacz24** [comment]
> It blows my mind that even after what seems to be two years, it's still not possible to set a specific homepage. This is basic functionality that has existed in every browser since the 90s.

Glad I'm not the only one who thinks this. What's even more surprising is Firefox isn't the only one. I haven't been able to find a mobile browser worth using that has this feature.

**Comment by Venrexx** [comment]
Honestly I'm getting kind of tired of waiting for what is essentially a basic feature, solely because the devs can't understand that not everyone is interested in all that crap on their homepage. Even their desktop version has this feature. All browsers since the 90's have had this feature. How is this even still an issue here? We're not saying they need to remove the homepage altogether, just give us the ability to control what our homepage is, if we choose to not want the default one. Customization has always been a major part of Firefox, and this feels like a step backwards. The fact that they are even humming and hawing about it is just mind boggling.

**Comment by jhrush** [comment]
Bromite (Chromium fork) has this feature, I'd honestly use Fennec a lot more if I could just use my own webpages as the start page, new tab page, and home page. Firefox mobile used to have this feature as well before the revamp. Seems as though it would be pretty simple to implement. 

The current homepage implementation isn't that great because you can't reorder collections, top sites, etc. all that well, they are added by date instead. The lack of customization to a pretty bad homepage system is turning many off of Firefox mobile, it's the first thing they see. People want to organize things as they please not in some weird historical order.

**Comment by jr-johnson-support** [comment]
Customer Experience team: 

**Feature Description:**
Users are requesting to set a specific website as their Home page instead of viewing the actual Home page that includes shortcuts, bookmarks, Recs, etc. 

CX team has been tracking request for this over the google play store reviews since May, 2022. At this time we have seen 64 requests over those reviews. 

More info available to the product team upon request.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807866

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
