### ISSUE TITLE
[Bug] Permanently blocked by the system, camera and mic permissions don't appear in the site info panel

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7566]
## Steps to reproduce
Make sure to clear app data and have the default permissions settings.
1. Go to permission.site, switch to https
2. Tap the camera or mic buttons.
3. Deny access on the first system permissions prompt. 
4. Tap the cam or mic buttons again and tap "Deny and Don't ask again" on the system permissions prompt.
5. Tap the lock icon and check the site info panel.
### Expected behavior
The permissions appear as Blocked by Android and the user needs to go to App info and turn on the permissions. 
see also: 
https://github.com/mozilla-mobile/fenix/issues/7566#issuecomment-609426117
### Actual behavior
The 2 permissions permanently blocked by the system don't show up in the panel. The ones allowed/blocked by the app, do appear.
Note: if the system permissions are allowed first and then blocked in the App info>Permissions, they will appear correctly in the app.
### Device information

* Android device: Pixel 3
* Fenix version: RC 3.0.2

**Comment by vesta0** [comment]
@Amejia481  will take a closer look and comment.

**Comment by Amejia481** [comment]
This may be bit tricky as we are not storing non final state related to site permissions (nothing that doesn't have checkbox "Remember decision for this site"). For this reason, this info is not showing up in the panel the same can be seem with site permissions on private sessions.

This requires some significant effort from the ac team as this could change the way that we handle site permissions.

**Comment by Amejia481** [comment]
@sv-ohorvath  I was taking a look to what Fennec does [for non final state the permissions are not getting shown in the site info panel](https://drive.google.com/file/d/19k0Z-6tlJQLELDLlerN78efHJiLV4EWG/view?usp=sharing) neither.

**Comment by sv-ohorvath** [comment]
@Amejia481 yes, that is true, they do work the same on Fennec. 
Just a note that I was referring to camera and mic, which first show a system permission dialog, on which you can block the app's permissions (as opposed to location which first shows the in-app dialog and the system dialog only after)
I denied the cam & mic's permissions from the system dialog and set them to don't ask again. I was expecting to see a "Blocked by Android" status in the site info panel. 
But they have the same behavior on Fennec, you are right: they only appear as Blocked by Android if the change is made AFTER you make a selection for the in-app dialogs. 
Thanks. Do you think we can close this?

**Comment by Amejia481** [comment]
> Just a note that I was referring to camera and mic, which first show a system permission dialog, on which you can block the app's permissions (as opposed to location which first shows the in-app dialog and the system dialog only after)

I used the location permission as the only one on Fennec that has a checkbox in the dialog. Other permissions are always temporarily granted/allowed. 


> I denied the cam & mic's permissions from the system dialog and set them to don't ask again. I was expecting to see a "Blocked by Android" status in the site info panel.
> They only appear as Blocked by Android if the change is made AFTER you make a selection for the in-app dialogs.

@sv-ohorvath  this is good point, thanks for bring this up. Unfortunately this is also an [issue present on Fennec](https://drive.google.com/file/d/1_MHHJvHN705isi3g45wtGsoMlTuEstcX/view?usp=sharing), I believe we haven't covered this user path before. I think we should close this issue and open a new one for handling "the system permission dialog when the user clicks **Deny & don't ask again**", this has a completely different user flow, for example:

When the system permission dialog is requested for the first time, it only shows the **Allow** and **Deny** buttons, but if the **Deny** button is clicked, and we request the permission again, now the system permission dialog shows the **Allow**, **Deny** and **Deny & don't ask again** buttons, then if the  **Deny & don't ask again** button is clicked, we can't show the system dialog again, this permission is always going to get auto-rejected by Android, the only way to access it is to take the user to **"App Info"** and there the user have to select the permission and allow it there otherwise it will be always **denied** .

**Comment by sv-ohorvath** [comment]
@Amejia481 This is the case that it was meant to be covered in this ticket but I have to admit it was described lazily. I've modified the title and description to better match the issue. Sorry for that, I hope it makes more sense now.

**Comment by Amejia481** [comment]
> @Amejia481 This is the case that it was meant to be covered in this ticket but I have to admit it was described lazily. I've modified the title and description to better match the issue. Sorry for that, I hope it makes more sense now.

👍

**Comment by Amejia481** [comment]
This should be fixed in master, @sv-ohorvath would you mind taking a look ? :)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 4/23. 
Devices: Pixel 4 (Android 10), HTC Desire (Android 6.0.1)
