### ISSUE TITLE
[Bug] Metrics nav bar position is reported to telemetry in locale instead of english

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7574]
We should just send the pref key 

Note: this **may** be an issue with other telemetry events we're sending and we should verify those too.

![image](https://user-images.githubusercontent.com/4400286/72090758-846d7980-32c3-11ea-84c2-bece8e5ea2c1.png)

**Comment by boek** [comment]
When we fix this let's verify we're not sending any other translated strings to telemetry

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** using a Google Pixel 3a XL (Android 10) on:

### Fenix Nightly Build #20230608 from 1/23 (Locale changed in Fenix)

• Italian
Event type pings:
✔️ Toolbar Top - Ping 6bd7b212-1ead-4a57-af26-f7cef9d28d12
✔️ Toolbar Bottom - Ping d3262a29-f499-49ee-b559-8ba3d199b3ca

Metrics type pings:
✔️ Toolbar Top - Ping ecbfa4a3-ddf8-4d08-9216-9d0333ea0e36
✔️ Toolbar Bottom - Ping 2abe8d45-1eef-4e82-aa6c-7751af0b155c

[Logcat](https://github.com/mozilla-mobile/fenix/files/4103414/Nightlyitalian.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t2323010113)

• German
Event type pings:
✔️ Toolbar Top - Ping 4c9b43f1-00a6-4fe7-ab55-01cad57a6e0c
✔️ Toolbar Bottom - Ping 02227809-c69c-4133-9ae7-fa279b6758b7

Metrics type pings:
✔️ Toolbar Top - Ping 6089301c-ef9e-4794-afab-562b54377633
✔️ Toolbar Bottom - Ping 67244ebb-1610-4408-925b-686d59359332

[Logcat](https://github.com/mozilla-mobile/fenix/files/4103423/Nightlygerma.txt)
https://debug-ping-preview.firebaseapp.com/pings/aj-t2323010114


 
### Fenix Beta 3.0.0-beta.2 Build #20230233 from 1/23 (Locale changed from the device's "Language and input" settings due to the fact that the "Language" advanced Setting isn't available)

• Italian
Event type pings:
✔️ Toolbar Top - Ping 8f8c3f9f-19a0-47db-b3bf-47cfa64c8b65
✔️ Toolbar Bottom - Ping 7ecca23d-e31b-41d4-96dc-191bd1cbbaea

Metrics type pings:
✔️ Toolbar Top - Ping ecbfa4a3-ddf8-4d08-9216-9d0333ea0e36
✔️ Toolbar Bottom - Ping 2abe8d45-1eef-4e82-aa6c-7751af0b155c


[Logcat](https://github.com/mozilla-mobile/fenix/files/4103400/Betaitalian.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t2323010111)

• German
Event type pings:
✔️ Toolbar Top - Ping 63335c52-3da7-4661-9930-9d8265ded4f6
✔️ Toolbar Bottom - Ping eb2310f8-8077-4ad7-9a71-8f8fec85bdfe

Metrics type pings:
✔️ Toolbar Top - Ping dc1c3d30-90c1-4e95-afc2-9be9489d2b97
✔️ Toolbar Bottom - Ping a92164f4-b92e-4bb4-8103-5f5e624c6820

[Logcat](https://github.com/mozilla-mobile/fenix/files/4103402/Betadeutsch.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t2323010112)
