### ISSUE TITLE
[Bug] Reader View Appearance tab does not go away after clicking 3 dot menu with top toolbar

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7591]
## Steps to reproduce
Set Toolbar to top
Go to any page with reader view
toggle reader view
click on appearance from 3 dot menu
click on 3 dot menu

### Expected behavior
Appearance menu goes away
### Actual behavior
Does not. It is possible to navigate to other sites (webcompat, help) which are not even in reader view and yet the appearance menu persists on these sites 
### Device information

* Android device:Asus Zenfone m1
* Fenix version: Nightly 200109 18:00 (Build #20091807)
28.0.0, a53f8eaba
GV: 74.0a1-20200107215758

**Comment by sv-sdeiac** [comment]
This issue seems to be much important since the Reader view appearance menu is not disappear even when the Reader view mode is disabled.
The Appearance menu disappears if you start to scroll or tap on the page.
![Screenshot_20200226-103910](https://user-images.githubusercontent.com/40264165/75327356-edfe1300-5884-11ea-86f4-69969f42384c.png)

Device: Nexus 9 (Android 7.1.1) and Xiaomi Mi 8 Lite (Android 9).
Build: 2/26 #20570604.

**Comment by jakefleming156** [comment]
This is pretty similar to #13390 and can probably be handled by the same fix. Thanks for filing.
