### ISSUE TITLE
External Download manager support

### ISSUE THREAD

**Issue by Daplugg23** [mozilla-mobile/fenix#7620]
Add support for idm+ and adm download manager. In fennec if I saved files it would recognize the external download manager. In Fenix it currently does not work. 

### What/Requirements
Idm+ app
Advanced download manager app

**Comment by NotWoods** [comment]
Android Components issue: https://github.com/mozilla-mobile/android-components/issues/4772

**Comment by SS1113** [comment]
The reason why this feature is useful is because if I download large files and the link expires after some time I'll be able to replace the expired link with a new one and be able to resume the download from where it was interrupted as third-party download managers have a feature that lets you refresh the link for a given download if the download link expires in the middle while the file is being downloaded.

The built-in download managers of most browsers don't usually have this feature so I  request you to add this feature as soon as possible as I don't have access to Broadband internet; I only have mobile internet data which is costly, if I was able to refresh an expired download link it'll save me a lot of precious mobile data.

**Comment by test2a** [comment]
On a related note, I dont see a downloads manager in ff preview nightly? It it hidden? Not implemented yet?

**Comment by astarq** [comment]
Any update on this?

**Comment by Amejia481** [comment]
@vesta0 what is the priority on this ticket?

**Comment by vesta0** [comment]
It hasn't been prioritized.

**Comment by Amejia481** [comment]
> It hasn't been prioritized.

Thanks :)

**Comment by SS1113** [comment]
@vesta0 I request you to please prioritise this feature soon and implement it, this is really important for me as the large downloads most of the time have time limit to them and after that the links to them expire and I have to download the whole file again. Third-party download managers make it easy to refresh the download links and I can start the download where it stopped and save a lot of mobile data. 

None of the browsers I have come across have the link refreshing feature. So this feature would be really really useful.

**Comment by opusforlife2** [comment]
Since the original comment lists two proprietary download managers, I just want to mention that there are proper _free and open source_ download managers available on F-Droid.

Aria2App (open source) (Aria2App allows you to handle your downloads on aria2 wherever you are!) - https://f-droid.org/app/com.gianlu.aria2app

Download Navi (Download Navi is a free and Open Source download manager for Android 4.4+) - https://f-droid.org/app/com.tachibana.downloader

If at all Fenix advertises support for download managers, they should be FOSS ones.

**Comment by ShatteredPixel** [comment]
Does anyone know when this feature is coming to Fenix? This is really important for me and it's the only reason I'm not yet completely moving from other browsers.

Please bring this feature soon to Fenix. 

Thanks!

**Comment by ShatteredPixel** [comment]
> Does anyone know when this feature is coming to Fenix? This is really important for me and it's the only reason I'm not yet completely moving from other browsers.
> 
> Please bring this feature soon to Fenix. 
> 
> Thanks! 

And Also, the https://github.com/mozilla-mobile/fenix/issues/7620#issuecomment-634508932 is mine.

**Comment by Amejia481** [comment]
We are adding support for this on https://github.com/mozilla-mobile/android-components/pull/7923 but we need UX feedback as we need to expose a setting for activating it. Should we just add another setting under the "**Advance**" section?

![image](https://user-images.githubusercontent.com/773158/88919572-5472cd00-d239-11ea-931e-c00932784694.png)

**Comment by opusforlife2** [comment]
> components/feature/downloads/src/main/res/layout/mozac_downlaod_app_list_item.xml

The spelling of "download" needs correction, @Amejia481.

**Comment by FrostedIce339** [comment]
@Amejia481 There was this behaviour I noticed a few weeks ago (I have since been upgraded to the new Firefox) on the old Firefox browser that when downloading the file it used to bring a dialogue which contained the Firefox browser and other apps that I can download from like ADM but the browser used to begin the download as immediately as I pressed the link even when I have not select any apps yet -- I noticed it because my internet usage spiked as soon as I pressed the download link with internet speed measuring apps like Internet Speed Meter, is the new browser also behaving the same as the previous old browser? The old browser was wasting data.


And also I think it'd worth refering the Kiwi browser's implementation (https://github.com/kiwibrowser/src) on how they're handling it since it is also open-source and handles the external download manager very efficiently and I think flawlessly too. When adding support for external download managers they said they are in contact with third-party download manager developers on how this would need to be implemented (IIRC, they (Kiwi Dev(s)) said they'd need to pass some cookies to the ADM download manager to make the download work correctly in ADM when the link gets passed on to it).

**Comment by Amejia481** [comment]
> @Amejia481 There was this behaviour I noticed a few weeks ago (I have since been upgraded to the new Firefox) on the old Firefox browser that when downloading the file it used to bring a dialogue which contained the Firefox browser and other apps that I can download from like ADM but the browser used to begin the download as immediately as I pressed the link even when I have not select any apps yet -- I noticed it because my internet usage spiked as soon as I pressed the download link with internet speed measuring apps like Internet Speed Meter, is the new browser also behaving the same as the previous old browser? The old browser was wasting data.

The initial feature is going to work as is shown in this [video](https://github.com/mozilla-mobile/fenix/issues/12297), if you selected in settings that you want to download files with third party apps, every time that you download a file a dialog is going to show allowing you to select with which app you want to download. In a follow up, we are going to introduce the functionality for selecting a preferred app for download a type of file you can find more info here https://github.com/mozilla-mobile/android-components/issues/7943 and a setting where you can change your previous selection.


> And also I think it'd worth refering the Kiwi browser's implementation (https://github.com/kiwibrowser/src) on how they're handling it since it is also open-source and handles the external download manager very efficiently and I think flawlessly too. When adding support for external download managers they said they are in contact with third-party download manager developers on how this would need to be implemented (IIRC, they (Kiwi Dev(s)) said they'd need to pass some cookies to the ADM download manager to make the download work correctly in ADM when the link gets passed on to it).

Thank you for the reference :)

> And also I'd say to keep the dialogue for 'Download with third party apps' after the 'Open links in apps' so it becomes such that users options (Add-ons, Open in apps etc.) are first and developer options (like Remote debugging, etc.) are at last.
> 
> You might also consider moving developer specific options (Leak canary, Remote debugging via USB, etc.) to a separate section. As general users, I think, might not use them and mistakenly even enable them accidentally.

Great feedback, the UX team will help us with the decision :).

**Comment by AmyYLee** [comment]
Assigning to @brampitoyo - If this requires more effort than UX feedback. Please update the flag to needs:UX-investigation and remove needs:UX-feedback. Thanks!

**Comment by brampitoyo** [comment]
@Amejia481 I would advise adding a new menu item under Settings → Advanced → Open links in apps.

- This item should be a toggle
- This item should be located under Advanced, and below “Open links in apps”
- String: “Use external download manager”
    - @betsymi, while I worry about the word “external” being too jargony, we also know that the usage of download managers is very likely limited only to advanced users.

<img width="360" src="https://user-images.githubusercontent.com/51007/89366871-d0827e80-d72b-11ea-8da7-a0151c776ed2.png">

-----

Looking towards the future when we have more download-related settings (e.g.: select default download folder), we can make a new menu item called “Downloads”. When tapped, it can lead to a sub-page that contains “Use external download manager” as one of the items inside it.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/12. Tested using ADM and IDM to download different file types and the popup was displayed in order to choose between the Nightly and the external download manager. 
Devices:
- Samsung Galaxy Note 10 (Android 10)
- Google Pixel 3 (Android 11)
- Huawei MediaPad M2 (Android 5.1.1)

**Comment by FrostedIce339** [comment]
@Amejia481 Any chance that this would come to the stable version of the the browser anytime soon? Honestly speaking, this would be the only feature that would make my browsing experience almost complete apart from the uBlock Origin support that is already implemented. 

Sorry for the interruption and thank you very very much for adding this feature.

**Comment by opusforlife2** [comment]
Well, yeah? Now that the stable version of Fenix is rolled out, the normal feature train is probably back on track. Nightly -> Beta -> Release, except for things like about:config which are explicitly blocked for now.

**Comment by FrostedIce339** [comment]
@Amejia481, @sflorean 


I want to point out this:

From the above https://github.com/mozilla-mobile/fenix/issues/7620#issuecomment-674085844:

>Also in the Nightly I tested, it doesn't look like the mocks posted here: https://github.com/mozilla-mobile/fenix/issues/7620#issuecomment-668949688

**Comment by sflorean** [comment]
> @Amejia481, @sflorean
> 
> I want to point out this:
> 
> From the above [#7620 (comment)](https://github.com/mozilla-mobile/fenix/issues/7620#issuecomment-674085844):
> 
> > Also in the Nightly I tested, it doesn't look like the mocks posted here: [#7620 (comment)](https://github.com/mozilla-mobile/fenix/issues/7620#issuecomment-668949688)

Could you please add a screenshot?

**Comment by opusforlife2** [comment]
@sflorean It's a ghost account now.

**Comment by PandoraHayami** [comment]
I know this is old, but would be cool to select one default download manager (Which currently isn't an option).
