### ISSUE TITLE
[Bug] Selecting the entire text in a page, displays an extra button overlapping some elements

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7676]
## Steps to reproduce
1. Load a page that has a lot of text (i.e. wikipedia.org).
2. Long-tap on a non-linked word, then choose to select all.
3. Observe the top-left corner.

### Expected behavior
No extra buttons or options are displayed.

### Actual behavior
An extra "Open" button is displayed, which is overlapping some elements from the page.

### Device information
* Android device: all
* Fenix version: RC 3.0.2, Beta build 3.1.0-beta 3, Nightly build from 01/14

![Untitled](https://user-images.githubusercontent.com/40694158/72345785-271b6300-36dd-11ea-9f20-fa715df820ca.png)

**Comment by FoxDie12x** [comment]
After investigating: It seems this issue is not related to Fenix, but to wikipedia's mobile page itself.

**In Fenix**: The issue can only be reproduced when visiting a wikipedia article's mobile page, such that the menu icon is shown on the top left. Selecting all text indeed shows the text 'open' right under the icon. You don't even need to select all text; you can simply long tap the menu icon (in top left) on a wikipedia article's page to reproduce the issue. Tried the same approach on other mobile web pages with similar menu icons (with an overlay upon clicking the icon), but none displayed extra text under the menu icon.

**Other browsers**: Tried to reproduce this issue in other browsers (Chrome for Android, Firefox for Android, Opera for Android), and all display the same issue on wikipedia pages, but not on other webpages.

* My conclusion**: it seems this is an issue not related to Fenix, but to Wikipedia's mobile page.


Screenshots added below from other browsers with proof of same result on wikipedia's pages:
OPERA FOR ANDROID: ![Screenshot_20200311-221509](https://user-images.githubusercontent.com/1681771/76465676-6832a980-63e6-11ea-82e8-386bcebcb970.png)

CHROME FOR ANDROID: ![Screenshot_20200311-221604](https://user-images.githubusercontent.com/1681771/76465694-71bc1180-63e6-11ea-8649-c2a341751d6e.png)

FIREFOX FOR ANDROID: 
![Screenshot_20200311-221622](https://user-images.githubusercontent.com/1681771/76465726-7e406a00-63e6-11ea-96f0-7f08814fd8d3.png)

**Comment by kbrosnan** [comment]
Thank you @FoxDie12x for doing some cross browser investigation.
