### ISSUE TITLE
[Bug] ANR on selecting language from the search bar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#7677]
## Steps to reproduce
1. Go to Settings>Language.
2. Type in the search bar the letter "f": will show 2-3 languages
3. Tap to select one: French, for e.g. Wait for the app to update to the new language.
4. Search again, select Suomi.
### Expected behavior
Language is selected, shows a checkmark.
### Actual behavior
App either stops responding, or the selected language is hidden from the search results.
When the app stops responding, it only shows a black screen, even after a restart, eventually it shows the ANR dialog.

[logcat](https://github.com/mozilla-mobile/fenix/files/4059447/log.txt)

### Device information

* Android device: Nexus 9(Android 7.1.1), OnePlus 5T (Android 9)
* Fenix version: Beta 3.1.0, Nightly 1/14

**Comment by ekager** [comment]
Can you still reproduce @sv-ohorvath ?

**Comment by sv-ohorvath** [comment]
@ekager I do, just that you need to change the language twice, my bad. 
![20200127_171935](https://user-images.githubusercontent.com/4037709/73187110-8a6bb300-4129-11ea-9b39-b79583564fc9.gif)

**Comment by BranescuMihai** [comment]
A bit more info: 
There are 2 types of action in this fragment, select and search.
Writing in the searchView dispatches the search action to the store, that modifies its state. When we write 'f', Suomi appears in the filtered list because the exonym(subtitle) is Finnish. However, when we press it, the activity recreates and the locale is changed. Its exonym no longer contains F, therefore it should disappear from the list.

I've tracked down the problem to Store.kt in AC, method `dispatchInternal`, line `subscription.dispatch(newState)` inside the synchronized section. It seems that for the crashing languages, it enters this block 2 times (select followed by search), while the error-free languages only enter it once(select), because the search doesn't modify the state (in our example, if we have 'f' in search, and we select French, the list stays the same, because all items still contain F). The second time it enters the block, it looks like the coroutine dies or the scope gets canceled for some reason. 

**Putting the synchronized block inside a different coroutine works:**
```
scope.launch(dispatcherWithExceptionHandler) {
      synchronized(subscriptions) {
                subscriptions.forEach { subscription ->
                    subscription.dispatch(newState)
                }
      }
}
```
This seems like an overkill however, so if someone has the time and expertise, feel free to take it up :)

**Comment by boek** [comment]
I think this might have been fixed in an a-c update.

I tried the STR on my Pixel 3 and Android 5 sim and couldn't get the ANR on either case.

**Comment by boek** [comment]
What is the locale your device is set to?

**Comment by sv-ohorvath** [comment]
I cannot reproduce it either now on Nightly. We can finally close it. Thanks!
