### ISSUE TITLE
[Bug] Fix Nightly androidTest apk for startup test

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#7702]
## Summary
The nightly startup test: [NavigationToolbarTest#visitUrlTest](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt#L117-L125)  is a gating UI test that is intended to run just prior to publishing to playstore.  If test fails, app crashes, etc., nightly should not be published.  Test is currently disabled because it perma-fails on Firebase (and locally from command line) even though the very same test works 100% of the time on debug builds on github events.

## git PR or merge to master
When submitting a PR or merging to master, both the (debug) app and androidTest apks are built and the UI tests pass.  The package names from the apks in the taskcluster payload are identical:
`org.mozilla.fenix.debug` and
`org.mozilla.fenix.debug.test` respectively

## Nightly startup test
When the same test is run prior to publishing Nightly, both the (nightly) app and androidTest apks are built and the UI test fails.  The package names from the apks in the taskcluster payload are different:
`org.mozilla.fenix.nightly` and
`org.mozilla.fenix.debug.test`

when trying to run the tests locally from the command line these apks produces the following error....

```
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation
```

## Notes
**get apks**
wget apks from [taskcluster payload](https://firefox-ci-tc.services.mozilla.com/tasks/MRGKqXFaR5mUs0TYp_57AQ)

**get package name**
```
$ ~/Library/Android/sdk/build-tools/29.0.2/aapt dump badging app.apk  | grep package:\ name
package: name='org.mozilla.fenix.debug' versionCode='1' versionName='1.0.2003' compileSdkVersion='28' compileSdkVersionCodename='9'
```
**run test w/ pre-installed apks**
```
adb shell am instrument -w -r -e debug false -e class org.mozilla.fenix.ui.NavigationToolbarTest#visitURLTest org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner
```

**Comment by rpappalax** [comment]
@JohanLorenzo I'm not 100% sure this is the issue, but it seems to be the only difference between the two. Perhaps we need to build instead an androidTest apk with a matching package name?
`org.mozilla.fenix.nightly.test`?

https://github.com/mozilla-mobile/fenix/blob/master/taskcluster/ci/startup-test/kind.yml#L42

**Comment by rpappalax** [comment]
If I'm not mistaken, it's not safe for us to sign the androidTest apk with the same key and deploy that to Firebase but we could in theory run this test safely in a Docker container in taskcluster instead, true @JohanLorenzo?

**Comment by JohanLorenzo** [comment]
I'm sorry, I'm not sure to fully understand your question. I'm going to reply with what I get from the issue, for the sake of timezones. Feel free to ask any other questions if I didn't reply to what you had in mind.

To me, the main problem is this: `org.mozilla.fenix.nightly` and
`org.mozilla.fenix.debug.test`. If I understand correctly, the latter should be `org.mozilla.fenix.nightly.test`. In my opinion, changing the signature won't help. In fact, if I remember correctly, the gradle people said the signature doesn't matter as long as the test APK and the APK under test are signed with the same key at a given time. The key can change from a run to another. Both debug and nightly sign both APKs with same key at a given time. 

If renaming `org.mozilla.fenix.debug.test` doesn't work, I suspect the nightly APK doesn't have embed the debug instructions to instrument the APK under test. That's what the error message makes me think. I seem to remember that's the reason why we ended up creating a dedicated APK for performance tests (aka "raptor"):

https://github.com/mozilla-mobile/fenix/blob/320fc4e4aeb0bda537865fb87e035929d13c6efc/app/build.gradle#L69-L73

This build type was added in https://github.com/mozilla-mobile/fenix/pull/1245. I'm no expert in these types of builds, so I guess @csadilek would have a better option than mine. 

Maybe we need to create a second nightly build whose sole purpose is to be used by the startup test. This nightly build won't be the one we ship, but it will have the instrumentation instructions and it will be built against the same revision as the one we ship. For the record, if we go this way, we don't need to sign the test APK with the nightly key anymore, since the APK under test will never reach Google Play and isn't meant to be installed by users.

**Comment by csadilek** [comment]
> This build type was added in #1245. I'm no expert in these types of builds, so I guess @csadilek would have a better option than mine.

That's a longer story :), but the TL;DR: This build type was introduced so we can exclude the test activity from production / release builds, which would have otherwise introduced a security problem. That security problem has long been addressed, but we decided to keep the build type based on the discussion here: https://github.com/mozilla-mobile/fenix/issues/4132#issuecomment-512914393

> Maybe we need to create a second nightly build whose sole purpose is to be used by the startup test. This nightly build won't be the one we ship, but it will have the instrumentation instructions and it will be built against the same revision as the one we ship.

Yes, that's my understanding too.

**Comment by isabelrios** [comment]
I would like to share some progress here. 
After some changes I got the desired `org.mozilla.fenix.nightly.test` package. 

But in order to get it by running `./gradlew assembleAndroidTest` successfully, I had to disable optimizations by adding `-dontoptimize` in `proguard-rules.pro` file. I was blocked with some 
`Task ':app:transformClassesAndResourcesWithR8ForGeckoNightlyFenixNightly'`  errors and tried that, I know that's not an option. Just wanted to give some context. Without that line I'm blocked with this error R8 error: 

`~/.gradle/caches/transforms-2/files-2.1/16e5c3df20b94866f7472d2779ef0788/feature-tab-collections-39.0.20200422203205/jars/classes.jar: R8: NullPointerException during IR Conversion` 

In app:minifyGeckoBetaFenixNightlyWithR8 task

Full logs: 
[minifyError.docx](https://github.com/mozilla-mobile/fenix/files/4530664/minifyError.docx)

Wondering if you may have idea/feedback about this error or how to get a fix for it.. @pocmo @csadilek Thanks!!

**Comment by isabelrios** [comment]
I think this issue can be closed now since we know how to create the correct apks for both Nightly and Beta. 
All the info related to that is in this [doc](https://docs.google.com/document/d/1g3PsB_e6J0QoAtKESBn7XfgAmBwz36s30IwOrB8Y8Go/edit?usp=sharing) 
@rpappalax please confirm and I will close it.

**Comment by isabelrios** [comment]
Future work to have a test working on Nightly on automation will be done in Fenix: Add Start Up Nightly test mozilla-mobile/mobile-test-eng#164 and [PR 17017](https://github.com/mozilla-mobile/fenix/pull/17017)
