### ISSUE TITLE
Web pages cannot be added to homescreen when the site supports PWA

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#7758]
### Why/User Benefit/User Problem
Even if a site supports PWA, the user may still want to add a certain page of that site as a shortcut on the home screen. 
Problem is, the "Install" option for PWA replaces the "Add to homescreen" option which is not available anymore.

### What/Requirements
the Add to homescreen option should still be available in addition to the PWA option (in Firefox for Android, it is the case, as the PWA is an icon in the navigation bar).

### Acceptance Criteria (how do I know when I’m done?)
When browsing a page within a PWA-compatible site, I should be presented both options "Install" and "Add page to homescreen"

Thanks :)

**Comment by brampitoyo** [comment]
@klint
- On a normal site, “Add to homescreen” is available as an action
- On a PWA-enabled site, “Install” is available as an action, but not “Add to homescreen”

Clarifying question: when you visit a PWA-enabled site, can you think of a plausible scenario where you want to add to homescreen instead of installing?

We’ve put install as the only action, because we thought that users would always prefer that action, 100% of the time, over “Add to homescreen”.

**Comment by klint** [comment]
The context is the following: I'm widely using the phone home screen to place, order and group apps, PWA-apps shortcuts and a variety of direct page shortcuts (instead of using top sites or collections within the browser, as I find this way more direct, all kind of accesses to information being at the same place, on a well organized phone launcher ).
 
For instance, I have a shortcut to the Le Monde newspaper as a PWA, but also some direct shortcuts to specific articles of Le Monde, or specific sections of Le Monde, like Science or Culture (using the "old" Firefox for Android where the option to have both shortcuts is still available).

PWA is nice because it looks more like an app, but the options are reduced compared to what can be done on a page browsed natively in a browser. Also, since the navbar is now masquable in Fenix, I don't see any real difference any more, visually speaking between, a PWA and a page in the browser. 

I hope that helps clariying the use case :)
Thank you!

**Comment by ekager** [comment]
From a technical perspective: I've separated out the menu items in #9838 for another reason, but we are still only displaying 1 - either "Add to home screen" or "Install", but showing both at the same time would now be trivial.

**Comment by AmyYLee** [comment]
@brampitoyo to follow-up

**Comment by brampitoyo** [comment]
I recommend going with only displaying one option in the menu, to keep it as streamlined as possible. Unfortunately, it’s a trade-off between having more functionality and keeping the menu easy to scan and access.

There’s likely no perfect solution, but I would be really curious if we would get more reports from users who want _both_ PWA and direct shortcuts for the same site. If we get multiple reports, then it would help bolster the case that we need both “Install” and “Add to Homescreen” in our menu.

**Comment by clientenq** [comment]
Imho we have a serious problem if the solution is to put website driven pwa preference and developer driven streamlined menu first and user control last.

Only providing the PWA option is not user friendly and does not give the user control.

Of course the website owner would prefer users to install PWA. They tend to install outside the browser creating more prominent appearence even when the browser is not used.
As a user having a browser that does prefer only providing this invasive option to the user this does not only feel wrong, it does not give users control. Control to prefer less invasive options. Control to keep website appearance in the browser. Control over not mixing up all options the browser homescreen is designed to provide to keep managing site listing and managing to the user.

The argument adding an extra option is not keeping a menu streamlined does not sound valid from a user perspective. In such case the developer clearly does not realize streamlined menus are not a main goal that is important for users. Certainly not when it causes disruption of normal functionality and most certainly not when the developer also prefers the website wish above the user control.

This is also not necesary since it can be prevented by adding an option to prefer showing add to home or install in the menu. User happy, developer happy, maybe website owner happy. 

Please reopen since more users start asking for having control instead of developer/website friendly design over users.

**Comment by JohannVII** [comment]
Issue has been reposted (not by me) because the response is absurd, as @clientenq notes. The original excuse was, 'We did this because we thought literally everyone would want it that way.' (@brampitoyo apparently couldn't even _imagine_ a scenario where someone might want to visit a specific page rather than the frontpage of a website packaged as an app; I'll add another to the cases that @klint notes - I link to a directory of in-network providers on my health insurer's website that I have routine cause to use, and it's much easier to go directly there from the Android launcher than it is to navigate through the full site every time in their PWA, but I can only install a PWA rather than creating a shortcut).

But then when you found out that wasn't true, you came up with another dismissal - that there's a trade-off between having features available and how "streamlined" the menu looks. And apparently the Fenix team would rather cut features than have to display menu items for those features. (Which raises the question: why have ANY features? They ALL require some sort of ugly menu entry to access. Why even make a browser? Nothing looks more streamlined with plenty of beautiful empty space than a blank screen, after all, and if that's the most important design goal...)

This attitude from too many of the developers is beyond ridiculous. This is trivial to implement, only creates additional menu clutter* in the limited set of circumstances where the website is set up as a PWA, and would maintain UI consistency across websites (because the option to add a shortcut to the specific page is always there, with an additional option displayed in the context when there is the additional option to save as a PWA link). It's not like there's even a workaround available that would make the feature possible while hiding it from the precious streamlined top-level menu, because the Fenix team ALSO hasn't implemented the Fennec behavior of allowing Android launcher shortcuts to be created from the context menu for saved bookmarks or top sites.

*Seriously, what's going on with the obsession with "clutter"? I've now been in dozens of discussions where people have done things like insist that half the home page must be kept blank because "clutter" rather than even allowing people to pin bookmarks - as an option, not a requirement. When did authoritarians hostile to user customization take over Mozilla, and which part of the mission statement is that approach supporting?

**Comment by nudgegoonies** [comment]
I have to agree with the opener and the opener here https://github.com/mozilla-mobile/fenix/issues/15450 and this feature is a must. I recently updated Fennec and to be true - not the post above this one is disruptive - all the changes introduced with the update to Fenix are disruptive in the users UI- and Functionality- expectations!

**Comment by argymeg** [comment]
I'd like to add my vote to this. In my use case (the NYT puzzle website) I would like separate app icons on my home screen for the different puzzles. If I "install" the PWA from a specific puzzle, it does open directly on that puzzle, but it's impossible to customise the app name, making the concept unusable.

FWIW regardless of whether a website supports PWA Chrome always displays "add to home screen" as an option and allows customising the name, though I'm not sure what the underlying behaviour is.

**Comment by ricardoV94** [comment]
> We’ve put install as the only action, because we thought that users would always prefer that action, 100% of the time, over “Add to homescreen”.

Do extensions work as normal in WPAs?

**Comment by RalfJung** [comment]
I opened a similar issue at https://github.com/mozilla-mobile/fenix/issues/20612, since I had not found this one.

The effect of the current Firefox behavior is that Firefox lets the page take away the option of adding a particular URL to the home screen. I realize that is not the *intention* of replacing "Add to homescreen" by "Install", but that does not change the facts of what *happens*. This is the opposite of "empowering users"; I'd expect Firefox to put me in control, not the website.

**Comment by dyura** [comment]
I also  opened a similar issue  #22560 . Definitely we need  shortcuts on Home screen to specific URLs and not to the home pages
