### ISSUE TITLE
[Bug] Re-evaluate the multiple entry points into the app.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#7791]
While working on https://github.com/mozilla-mobile/fenix/issues/7788, in the `HomeActivity.onNewIntent` there are multiple intent processors that increase the entry point surface area of the app.

The `StartSearchIntentProcessor` that processes the search widget intent is invoked from the `NewTabShortcutIntentProcessor`, which is invoked from the `IntentReceiverActivity`.

For the voice search intent, we get the transcription results in the `VoiceSearchActivity` that then invokes the `IntentReceiverActivity`. <- correct.

We should do an evaluation of why these are there and if they can all move be done in one place to reduce the entry points to the app by using just the IntentReceiverActivity.

**Comment by mcomella** [comment]
From #7917 (review), I noticed a fairly empty "router" Activity, `MigrationDecisionActivity`, adds about 40ms to startup (P2 performance test build). As such, I would like to remove as many of these "router" activities as possible and filed https://github.com/mozilla-mobile/fenix/issues/7927 to do so. I'm not sure if we should dupe that bug to this one because they seem to address similar issues.

**Comment by jonalmeida** [comment]
We should talk more about this in Berlin if you have time. :)
