### ISSUE TITLE
[Bug] Search <--> Browser transition feels really clunky/jumpy

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7841]
When I transition from Browser -> Search or Search -> Browser the animations feel really clunky.

### Browser -> Search
* "This time, search with" flashes for a brief second before hiding
* There's really no animation that happens to transition between the two states so it just "flashes" onto the screen

![open search 2020-01-21 13_59_55](https://user-images.githubusercontent.com/4400286/72847026-93a2de80-3c56-11ea-80c6-f7e6bc7f498e.gif)

### Search -> Browser
* The collapsing of the keyboard and snapping of the toolbar to the bottom is very jarring. 
* The flashing of icons / text (we start with a star icon and no text -> lock icon & text)

![hide search 2020-01-21 14_01_41](https://user-images.githubusercontent.com/4400286/72847019-91408480-3c56-11ea-971f-0336df8f9823.gif)

We should really just create smooth animations for these cases.

Perhaps that's something @AmyYLee has already designed 🤔 I cannot remember.

**Comment by AmyYLee** [comment]
@sblatz This was the original search/keyboard animation from #167

Tapping search bar from home screen - Transition duration 150ms

• Search bar slides up and transitions in size and colour (search bar height is condensed, search field goes grey, text changes colour).
• Fenix logo slides up with search bar
• Fenix logo fades out along with options/PBM icons once it reaches the top of the screen
• Contents below the search bar fade out at the same time as search bar slides up
• Keyboard fades in and slides up at the same time as content fades out.

Animation reference:
https://drive.google.com/file/d/1gPL3JO3uNgl9LmpJ8P2cnEey3YsLGyGL/view?usp=sharing

**Comment by brampitoyo** [comment]
We’ve decided against shipping the back button on the search screen (#6666) for a number of reasons:

- It introduces a list scanning issue by breaking icon and text alignment (ie. the search icon on the URL bar misalign with the search engines underneath).
- It’s internally inconsistent: we have recently removed the UI Back button from the menu, because we’ve decided to rely on the system back (whether that’s a visible button or a gesture).
- We have no other indicator besides #6666 that users struggle to get back from this screen.

Because the back button is due to be removed, we don’t need to fix this transition.

**Comment by darkwing** [comment]
@brampitoyo So this can be closed?

**Comment by brampitoyo** [comment]
@darkwing Yes, let’s close this issue.
