### ISSUE TITLE
[Bug][a11y] Play/pause button accessibility updates

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7859]
### Prerequisites
1. Make sure you have Google Accessibility Scanner installed.
2. Have a freshly installed build or a clean profile.

## Steps to reproduce
1. Launch Fenix.
2. Open a media playback in the background page;
2. Using the Accessibility Scanner, scan the "Open tabs" section.

### Expected behavior
There are no suggestions to make any changes.

### Actual behavior
There is a suggestion to consider making the play/pause button larger - as seen in the screenshot below.

### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8.0)
* Fenix version: 3.2.0-beta.1 #20220333
![Screenshot_20200122-154243_Accessibility Scanner](https://user-images.githubusercontent.com/40264165/72899789-637b3e80-3d2f-11ea-8514-fa8fa57baf82.jpg)

**Comment by sblatz** [comment]
A few things here:

1) Increase touch target
2) When the user selects the tab, announce the state of the media button (playing or paused media)
3) Media button should say which tab it references
4) Media button, when tapped loses focus (this is probably because we're getting a refreshed state and redrawing the whole tab, let's try to avoid this)
