### ISSUE TITLE
[Bug] Color difference in Reader mode and desktop mode toggles 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7919]
## Steps to reproduce
Open any page with reader mode
Open 3 dot menu
activate bot reader mode and desktop mode toggles
### Expected behavior
There is no difference in the activated toggles
### Actual behavior
There is a  color difference in the toggles
one is blue and the other is voilet
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly 200124 06:01 (Build #20240607)
29.0.0, ae1ba0f02
GV: 74.0a1-20200122094859

**Comment by kbrosnan** [comment]
@brampitoyo is this intentional? Can still reproduce in a current Fenix Nightly.

**Comment by brampitoyo** [comment]
@kbrosnan This colour issue is definitely not intentional.

It seems that the Reader Mode toggle doesn’t follow the same colour used on:

- Main menu → Desktop Mode
- Settings → Open links in apps
- Settings → Remote debugging via USB
- And other places

The correct colours are as follows:

- Light theme: ON toggle is dark blue
- Dark and private themes: ON toggle is violet

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Screenshot
![rsz_read](https://user-images.githubusercontent.com/51314259/75338892-2d822a80-5898-11ea-9c73-6741a27a1d76.png)
