### ISSUE TITLE
As a Product Owner I want to have telemetry for Search Shortcuts

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#793]
### Why/User Benefit/User Problem

We want to understand how this feature is used.

### What / Requirements

-Track when when shortcut mode is triggered
-Track when search is completed using shortcuts

### Acceptance Criteria (how do I know when I’m done?)

- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by st3fan** [comment]
Asking @mconnormoz for feedback on this one too.

**Comment by mconnormoz** [comment]
So, this one depends a little on how the feature is implemented.  On the desktop side we have interactions with the Top Sites impl, + we track alias searches for that plugin.  That's not quite ideal, because we can only imply conversion rate.

Is there a link to the current visual spec? @shorlander @verdi 

ideally, we'd have some form of event tracking for shortcut interactions (trigger shortcut mode + complete shortcut search) that would allow us to refine the UX.  I can help more with a final spec.

**Comment by st3fan** [comment]
This issue is blocked on telemetry requirements which can be provided either by the Fenix Product Team or the Search Team.

**Comment by mconnormoz** [comment]
Pending a final design, here's some minimal requirements:

- Shortcut searches should be tagged with a separate source (i.e. regular searches are recorded like google.actionbar, shortcut searches should be google.shortcut) (this is in SEARCH_COUNTS)
- we should track events for shortcut selected and shortcut used, to help us understand how well the UX converts people over time.

**Comment by sv-ohorvath** [comment]
@npark-mozilla Is there a way for QA to verify telemetry? If so, could you send us some details about it? Thank you!

**Comment by npark-mozilla** [comment]
@sv-ohorvath Yes, @rpappalax will contact you shortly on how to verify telemetry via Glean.

**Comment by boek** [comment]
Just checked and the data is available in Glean :+1:
