### ISSUE TITLE
Top Sites:- make text font bigger

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#7933]
### Why/User Benefit/User Problem
If I need to use the text to distinguish between two Top Sites, it's hard because the text font is very small. 

### What/Requirements
Make the text bigger

### Acceptance Criteria (how do I know when I’m done?)
Text is bigger.

(Having a grid which is 5 Top Sites wide might be an issue with a larger font... there might be too few characters to be useful)

**Comment by cadeyrn** [comment]
Yes, the font size is small, but it's already a problem to get a meaningful description to the top sites due to the limited space. A larger font would made the situation even worse.

Fennec and Chrome both have a four columns grid instead of five columns and a slightly larger font, the result is very similar.

I guess four columns, a slightly larger font and two text lines in combination are the only way to improve the readability AND to make the top site titles really useful. Only changing the font size without any other change would be a bad change.

**Comment by topotropic** [comment]
I agree with @cadeyrn – and we can consider this with https://github.com/mozilla-mobile/fenix/issues/9548. I'll close this issue. Thanks for the feedback.
