### ISSUE TITLE
Prefix a search with a shortcut

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#794]
### Why/User Benefit/User Problem

As a User I want to be able to prefix a search with a shortcut when i do a search. Like on Desktop, quick keyboard typers can just fully type the shortcut instead of going through the buttons.

### Acceptance Criteria (how do I know when I’m done?)

I can type `@wikipedia herring` in the search bar to use the a search shortcut

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15383)

**Comment by topotropic** [comment]
@st3fan, @vesta0  Is this something we can do post MVP? 
I think this case is especially interesting for voice searches

**Comment by sblatz** [comment]
@bbinto, @vesta0: are we able to remove this as a requirement for MVP? It is not in the current UX mocks.

**Comment by ekager** [comment]
@brampitoyo I read your comments in this Focus PR https://github.com/mozilla-mobile/focus-android/pull/4492 about a similar feature and wondering if you have any feedback for a Fenix implementation of search shortcuts? Seems pretty straight forward to go with the Comment 0 implementation but IIRC on Desktop they allow setting custom shortcuts as well.

**Comment by brampitoyo** [comment]
@ekager This seems fairly straightforward to implement, but note that @Verdi had designed Fenix’s search shortcuts feature so users don’t need to know (or to be taught about) the existence of `@`. And secondly, so users don’t need to type any more character than necessary (which on a mobile keyboard takes longer than desktop).

But if this feature is meant to address quick keyboard typers and those that prefers to type instead of selecting buttons, then maybe there’s something to it?

I think that our current implementation works great, but would like to know what @Verdi thinks of this idea.

Just thinking out loud. Maybe what happens is, when users type the `@` symbol, we change from this:

<img width="360" src="https://user-images.githubusercontent.com/51007/79711052-e9048f80-831a-11ea-9d91-c7b7501eab56.png">

To this:

<img width="360" src="https://user-images.githubusercontent.com/51007/79711800-03d80380-831d-11ea-89ce-33f1c8b006fd.png">

Is this helpful, or redundant? We care about casual everyday users who do quick informational searches, as well as keyboard typers (who I’m guessing is more ‘pro’).

**Comment by AmyYLee** [comment]
@brampitoyo to follow-up - Is UX feedback still needed?

**Comment by ekager** [comment]
I agree that I'm not sure this makes sense when we show "This time search with" all the time. If we ever changed that, we could revisit this as an alternative to clicking that shortcut icon maybe?

**Comment by brampitoyo** [comment]
Agreed, @ekager. This behaviour might make a lot more sense if “Search with” isn’t shown all the time. Let’s shelve this for now.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807704

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
