### ISSUE TITLE
[Bug] Make undo actionable in snackbars for accesibility users

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7969]
Currently our snackbars are displayed and announced via TalkBack but are not focused.

We don't really want them focused as the user would lose their focus on the page, but we also want them to be aware of "undo" functionality on snackbars.

We need to brainstorm how to handle this with @eeejay

**Comment by asadotzler** [comment]
It seems to me that when I close a tab, which triggers the undo bar, focus goes to nowhere. Talkback announces "Tab closed. Undo. Button." but double tapping reveals I am not actually on the undo button. Focus appears to be totally absent at this point and a swipe puts it on the addressbar. A couple of backswipes puts me on the undo button. Why not just land there to start with since that's what you're announcing.
