### ISSUE TITLE
improve processes for release quality (avoid shipping a large number of regressions)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7988]
The stable Firefox Preview 3.2.0 release has been shipped to end users via Google Play Store and the large number of **known and and thus avoidable regressions** is alarming. The worst case happened: You shipped a browser which can't resolve some domains…

- #7800: Not so few domains contains characters like "-". Firefox Preview 3.2.0 can't open these URLs directly. Instead all the requests are redirected to your default search engine. The issue is known since 11 days and should have been a release blocker.

- #7799: The "tab closed" snackbar no longer disappears. This regression is also known since 11 days and someone could see this as a release blocker because it's a highly visible regression.

- #7880: You regressed the cold startup performance noticeable (pulsating icon before the app launches). It's not a tragedy but still noticeable.

- #7604: The status bar and the action bar no longer have the same color. This is also not a tragedy but it's a highly visible regression and known since three weeks.

I wonder how such a large number of visible regressions can be avoided in the future. There are already release checklistes like #7845 and there are Beta builds so there should be long enough test period between Nightly and stable releases. I guess at least bad regressions like #7800 should be tested in Beta builds by someone to see if Beta builds are affected. Or do you see this as the responsibility of the issue reporter to test fixes in Beta builds and "nominate" these issues for Beta uplift? If so, what is the process for doing this? There are no "tracking flags" like in Bugzilla. What else can be done to avoid such situations in the future?

**Comment by liuche** [comment]
Thanks for raising these, @cadeyrn! During the 3.2.0 development period, we were focusing on the Fennec Nightly migration, so the opportunity for uplifts was more limited/shorter than usual, but you're right that we should have a more formal process around beta uplifts - currently, they're generally nominated by the engineer. We're also trying out a performance experiment in #7795 that additionally restricted our timing.

Over the next handful of releases we plan to land the remaining large moving parts, and stabilize Fenix. It's helpful to have these issues highlighted - consider raising them in the #Fenix Matrix channel, which is at chat.mozilla.org. Once our release schedule becomes more regular (and aligns with Desktop Firefox), we'll also publish it so it's more clear what bugs are fixed in which releases.
