### ISSUE TITLE
[Bug]Significant distance between the top Toolbar and Private browsing button

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8099]
## Steps to reproduce
1. Go to the settings;
2. Select the Toolbar option;
3. Set the toolbar to the top;
4. Return to the Homepage.

### Expected behavior
No visual defects are presented.

### Actual behavior
There is a significant distance between Toolbar and Private browsing button.

### Device information

Android device: 
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q);
- Google Pixel 3 (Android Q).

* Fenix version: Firefox Preview Nightly 2/5 @20360606.
![scadscsaca](https://user-images.githubusercontent.com/40264165/73827003-7437b400-4807-11ea-809b-24f39e932df0.png)

**Comment by sv-sdeiac** [comment]
Also, I found that the shadow overlaps the logo if the Toolbar is set to Top. 
![addition](https://user-images.githubusercontent.com/40264165/73829221-4a808c00-480b-11ea-8e69-759e911cd17e.png)

**Comment by ekager** [comment]
That top margin is currently dynamically set to `40` in `HomeFragment` here
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L848

@brampitoyo should we change that value? 

The second is certainly a bug we should fix.

**Comment by brampitoyo** [comment]
@ekager Yes, please. Let’s change the value so that the private browsing button isn’t shifted down. It should be the same distance as when the URL bar is on the bottom.

If the positioning on toolbar-bottom looks like this:

<img width="320" src="https://user-images.githubusercontent.com/51007/73902684-73804a00-48fb-11ea-9d09-1dc930314615.png">

Then the positioning on toolbar-top should look like this:

<img width="320" src="https://user-images.githubusercontent.com/51007/73902697-809d3900-48fb-11ea-9087-1a907d46b727.png">

**Comment by ekager** [comment]
I think this is fixed by #8085 . Let's verify and close :)

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Nightly 2/6 #20370604.

Devices:
- Nokia 6 (Android 7.1.1).
- Samsung Galaxy S8 (Android 9);
- Google Pixel (Android Q).
