### ISSUE TITLE
[Bug] Crash when accessing any of the links from "About" from the uBlock Origin's page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8117]
## Steps to reproduce
1. Install uBlock Origin.
2. Go to Settings - Add-ons - uBlock Origin - Settings - About section.
3. Tap on any of the links displayed.

### Expected behavior
A new tab is opened with the required details.

### Actual behavior
Crash.

### Device information
* Android device: all
* Fenix version: 2/5 Nightly build

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4160437/logcat.txt)

**Comment by csadilek** [comment]
I filed this yesterday with GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1613237

**Comment by csadilek** [comment]
@softvision-miralobontiu This crash is fixed now in the latest Nightly. Can you verify, please?

Note that since we're putting the Settings page in a popup, navigation is limited. Once a link is opened the device back button can be used to go back, but that's about it. The settings page is currently being redesigned and we might also end up putting it in a regular tab for better navigation, but that's a separate discussion :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 2/24 with Sony Xperia Z2 (Android 6.0.1), Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1). 
Indeed, the pages from About load slowly, but no crashes..

Thank you!
