### ISSUE TITLE
Some icons are dark in settings when in private browsing

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#824]
## Steps to reproduce
* Enter private mode
* Open settings

### Expected behavior
* Icons have consistent color

### Actual behavior
* Icons have inconsistent color

### Device information

* Android device:  Samsung Galaxy S5
* Fenix version: March 1 

![screenshot_2019-03-04-08-53-24](https://user-images.githubusercontent.com/250273/53755880-85947580-3e6c-11e9-877e-0ba35933d39f.png)

**Comment by kbrosnan** [comment]
This is still present on Android 6.0 and 5.1 devices. See this on a Nexus 10 as well. Build from March 5th @ 12:07 PM

**Comment by ekager** [comment]
@kbrosnan is it only this one icon...? How strange.

**Comment by kbrosnan** [comment]
No, several icons are affected. The Language, Data Choices, Help and Rate on Google Play icons are dark as well.

**Comment by kbrosnan** [comment]
Using an API 21 x86 emulator reproduces this problem.

**Comment by ekager** [comment]
Thanks, was finally able to get my emulator working to test this! 

The problem was fillType:evenOdd does not play well with fillColor from theme attributes on =<24. Think I caught all of them that needed the change except for the language icon, which I cannot find the vector asset for in Sketch, so I will file a followup issue for UX to get that for me!

**Comment by sv-ohorvath** [comment]
Verified as fixed on a Nexus 5(Android 6). Master build 3/11
