### ISSUE TITLE
Change menu for Custom Tabs

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#832]
When we open a custom tab from certain apps, our menu is overridden (for example in Slack it presents a few options like "Share in Slack"). However in other apps (like Yelp) our normal menu is inflated. We should decide if we want to hide our menu button if the custom tab app is not overriding the behavior

**Comment by vesta0** [comment]
Should be a custom menu (Mocks in #203)

**Comment by bsurd** [comment]
Could still reproduce the  Slack issue on:
* Google Pixel (Android 9) 
* Nexus 5 (Android 6.0.1)
* Build: 1.0.1911 (#10731207)
* [Logcat](https://github.com/mozilla-mobile/fenix/files/2966796/log.txt)
* [Video](https://drive.google.com/open?id=1ygH6HtBcMg3mQGlzvAUt_CzO6LtpRmAG)

The issue is not reproducible on Samsung Galaxy Note 8 (Android 9). Reopening.

**Comment by sblatz** [comment]
Did some more investigation. Looks like this is the behavior that Focus has as well, but it does not happen in other browsers including Fennec, so I will start there with implementing a solution for all devices!
