### ISSUE TITLE
[Bug] "Prevent websites from opening links in external apps" is not in the "Set as default browser" section in the settings menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8380]
## Steps to reproduce
1. Launch Fenix and reach settings menu.
2. Scroll down and observe the `Open links in apps`.
### Expected behavior
The `Prevent websites from opening links in external apps` should be in the `Set as default browser` section in the settings menu.
### Actual behavior
Prevent websites from opening links in external apps" should be in the "Set as default browser" section in the settings menu.
### Device information

* Android device: **All.**
* Fenix version: **Nightly 2/13.**

![20200213-142600](https://user-images.githubusercontent.com/42831109/74435512-42f55e80-4e6d-11ea-9569-7da16371595a.gif)

![74378968-e33b7c80-4db4-11ea-8060-650ca949ac0b](https://user-images.githubusercontent.com/42831109/74749442-d7e3c780-5272-11ea-9647-c652d588d08c.png)

**Comment by Poopooracoocoo** [comment]
I wouldn't expect it to be in the Set as default browser section. A browser doesn't have to be the default for a link to open in another app, right?

**Comment by abodea** [comment]
Hi, @Poopooracoocoo this was a follow up for the Review settings organization and it was a requirement from [UX Team.](https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-585859479)

**Comment by Poopooracoocoo** [comment]
@abodea i wonder why they went with that

**Comment by abodea** [comment]
@AmyYLee I have a question regarding the screenshot from my description as it was mentioned by you [here](https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-585427769) or the design from [here](https://app.abstract.com/share/ee40800d-4b36-49d5-8a5b-a89f8ab21141?mode=design&sha=2b7a1bf44fa2c02a3b7e470075e94c587a491d3b)?

**Comment by brampitoyo** [comment]
“Open links in app” was originally specced out to be under “Set as default browser” because we didn’t have an “Advanced” section.

Now that we have the right section to put it (as well as to contain other things), @AmyYLee and I thought that we should put “Open links in app” under it.

So a slightly revised Settings organisation look like this. Note two things:

- “Set as default browser” is a menu item on the root-level with a toggle. Same position as before: underneath “Language”
- Similarly, “Open links in apps” is also a menu item on the root-level with a toggle. It has a different position now: in the “Advanced” section, underneath “Add-ons”

<img width="360" src="https://user-images.githubusercontent.com/51007/81242538-8a9d1800-9061-11ea-9832-333cb79a814e.png">

We hope that this helps bring it up to the forefront!

**Comment by ValentinTimisica** [comment]
@brampitoyo should we open a new issue based on your last comment and close this one since the specifications are now different?

**Comment by brampitoyo** [comment]
Hi @ValentinTimisica – @AmyYLee and I thought that “Open links in apps” should have its own sub-page, because the explanation text is a bit long.

So the design I posted above isn’t totally final yet.

We’ll have the new Settings structure finalised within the next day or two. When that’s posted, we can file a new issue and close this one. Stay tuned!

**Comment by AmyYLee** [comment]
@brampitoyo for follow-up

**Comment by brampitoyo** [comment]
@ValentinTimisica I just went into our Settings page, had a think, and rechecked everything.

Let’s go ahead with the change I proposed above, on https://github.com/mozilla-mobile/fenix/issues/8380#issuecomment-624967123

This will remove sub-pages on both “Set as default browser” and “Open links in apps”, and make our Settings a little cleaner.

**Comment by ValentinTimisica** [comment]
Created #11365 based on @brampitoyo's [comment](https://github.com/mozilla-mobile/fenix/issues/8380#issuecomment-624967123). Closing this since the specifications are now different.
