### ISSUE TITLE
[Logins] Show favicons when possible in the login capture panel

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8549]
Show favicons when possible in the login capture panel - Please see screenshot below.
![Screen Shot 2020-02-19 at 2 49 18 PM](https://user-images.githubusercontent.com/5992746/74870111-2b175200-5327-11ea-95cb-0351b7523059.png)

**Comment by BranescuMihai** [comment]
Related AC ticket: https://github.com/mozilla-mobile/android-components/issues/7700

**Comment by Mugurell** [comment]
With the above ticket now being merge this should be available to text in the next nightly.

Expected behavior:
![SaveLoginsFragmentIcons](https://user-images.githubusercontent.com/11428869/91267394-f4117580-e77b-11ea-8902-370d9b47f7d1.gif)
[video](https://drive.google.com/file/d/1hh38hp1OyZZHFW1Gl2YMiqmzQykqCW9E/view?usp=sharing)

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on Nightly 8/31 with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)
- Sony Xperia Z5 (Android 7)

<details closed><summary>Testing domains</summary>

- https://twitter.com/
- https://www.instagram.com/?hl=ro
- https://ro.pinterest.com/
- https://www.linkedin.com/
- https://www.facebook.com/
- https://www.reddit.com/

Screen
![Screenshot_20200831-102810_Firefox Nightly](https://user-images.githubusercontent.com/49859863/91697021-1db20e80-eb79-11ea-88f4-6897964207d7.jpg)
<details>
