### ISSUE TITLE
[Bug] From PB shortcut, clearing tabs from notification returns to Normal mode

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#8590]
We want the PBM shortcut to replace "Focus" so you should not be leaving PB mode.

## Steps to reproduce
Open Fenix from PB shortcut
Open a url
Click on "Close private tabs" notification

### Expected behavior
Return to PB search screen

### Actual behavior
Returns to Normal mode search screen

### Device information

* Android device: P3
* Fenix version: Nightly 2/20

**Comment by sv-ohorvath** [comment]
I've noticed 2 things here:
1. If the app is open and in focus when you tap the notification, the behavior described by @liuche happens. It also happens if you open a new private tab by simply switching to PB from the homescreen.
2. If you press home to background the app, then tap the notification, the app is closed (removed from recent apps).

**Comment by BranescuMihai** [comment]
Is this still reproducible? Tried it on nightly and develop, for me clicking the notification returns to PB home

**Comment by liuche** [comment]
Hi @brampitoyo ! When you get back, could you chime in on this issue, specifically, for usage of the Private Browsing Shortcut, which I believe is made to support the use case of "always private" like Firefox Focus?

Your [comment](https://github.com/mozilla-mobile/fenix/issues/9100#issuecomment-607006341) about "closing PB tabs should open to Normal mode" might not address this case, and users of the PB shortcut might not like being bumped back to Normal mode all the time.

**Comment by brampitoyo** [comment]
@liuche Ooh. I forgot about this use case!

You’re absolutely right. Users who access Fenix using the Private Browsing Shortcut will not like to return to normal mode (there are multiple ways to create this shortcut: through CFR, inside Settings, by dragging the PBM shortcut out of Fenix long-press context menu).

**Is there a way for us to distinguish whether PBM is opened through the mask icon or the shortcut?**

If we can, then we can have two behaviours:

Users who access PBM through the mask icon must always go through normal mode. It’s more likely that they don’t want to stay in PBM forever. In this case, after the notification shade is tapped, return to normal start screen.

Users who access PBM through the Android homescreen shortcut doesn’t go through normal mode. It’s more likely that they want to stay in PBM forever. In this case, after the notification shade is tapped, return to Private start screen.

But if there’s no way for us to distinguish origin, we can default to returning to Private start screen. For some users, it would be less convenient to have to tap on the mask to exit PBM, but it’s better to err on the side of more privacy, rather than less.

**Comment by Diana-Rus** [comment]
Hi, verified the issue with Sony Xperia Z5 (Android 7), Samsung Galaxy S9 (Android 8) and Pixel 3 XL (Android 9) on latest Nightly.

Scenarios 
1. Open through PB shortcut, close notification while in recent apps and open through PB shortcut. ✔️
2. Open through PB shortcut, close notification while in background and open through PB shortcut.✔️
3. Open through PB shortcut  and close through notification with opened tab and in focus ✔️
4. Verify scenarios 1, 2 and 3 with normal tabs added and continuing with opening browser through PB shortcut.✔️
5. When access PBM through the mask icon must always go through normal mode after the notification is tapped.✔️
6. When access PBM through tabs tray, private mode tab, it goes through normal mode after the notification is tapped.✔️
7. When opening the app through "Open private tab" from homescreen, search after and close notification will go in PB. ✔️ (Only Samsung and Pixel)

Samsung - GIF - Scenario 1
![20200626-121014](https://user-images.githubusercontent.com/49859863/85842032-a9897200-b7a7-11ea-8ce8-458c1e611781.gif)

Samsung - GIF - Scenario 2
![20200626-121042](https://user-images.githubusercontent.com/49859863/85842007-9c6c8300-b7a7-11ea-9f25-e3661a2c18a3.gif)

Samsung - GIF - Scenario 3
![20200626-124133](https://user-images.githubusercontent.com/49859863/85843952-a9d73c80-b7aa-11ea-97c9-470ba9ef878b.gif)
