### ISSUE TITLE
Support RTL for theme / toolbar position picker images in Onboarding

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#8693]
This would provide a better RTL experience.
Initially reported in https://github.com/mozilla-mobile/fenix/issues/8469, it was seen in https://github.com/mozilla-mobile/fenix/issues/8673 that simply mirroring the existing imagery is not a solution.
For actually fixing this we need new images that would reflect the actual experience RTL users would have.

**Comment by brampitoyo** [comment]
@Mugurell I’ve designed an RTL variant that’s ready for export, and @apbitner (who’s the owner of this feature) will be able to post the assets here.

<img width="328" src="https://user-images.githubusercontent.com/51007/76476581-50e7d080-6467-11ea-9737-2097929596f6.png">

**Comment by brampitoyo** [comment]
@Mugurell RTL assets posted below. Thanks!

### MDPI

![onboarding_light_theme_rtl](https://user-images.githubusercontent.com/51007/76715624-07aebe00-6792-11ea-93ea-d09e4171be07.png)
![onboarding_dark_theme_rtl](https://user-images.githubusercontent.com/51007/76715625-0a111800-6792-11ea-997a-a112b09b55e7.png)

### HDPI - 1.5x

![onboarding_light_theme_rtl@1 5x](https://user-images.githubusercontent.com/51007/76715680-417fc480-6792-11ea-82bc-246ce6897b1e.png)
![onboarding_dark_theme_rtl@1 5x](https://user-images.githubusercontent.com/51007/76715683-447ab500-6792-11ea-968a-ef86fad1cd82.png)


### XHDPI - 2x

![onboarding_light_theme_rtl@2x](https://user-images.githubusercontent.com/51007/76715693-4cd2f000-6792-11ea-915c-8ce0ea2dd1bf.png)
![onboarding_dark_theme_rtl@2x](https://user-images.githubusercontent.com/51007/76715698-4fcde080-6792-11ea-946e-1a530f0be760.png)

### XXHDPI - 3x

![onboarding_light_theme_rtl@3x](https://user-images.githubusercontent.com/51007/76715702-56f4ee80-6792-11ea-9249-6f39ecd22edb.png)
![onboarding_dark_theme_rtl@3x](https://user-images.githubusercontent.com/51007/76715706-5a887580-6792-11ea-9996-86f296c8280b.png)

### XXXHDPI - 4x
![onboarding_light_theme_rtl@4x](https://user-images.githubusercontent.com/51007/76715930-3da07200-6793-11ea-832a-4982cc21a55c.png)
![onboarding_dark_theme_rtl@4x](https://user-images.githubusercontent.com/51007/76715931-4002cc00-6793-11ea-9a7d-b908d5d71b61.png)

**Comment by Mugurell** [comment]
@apbitner Although this ticket initially only referenced the theme picker images
in review it was seen,
based on https://drive.google.com/file/d/11-3sSjg9PvJAjTbRJ_UMC1gghWnPelVS 
that we'd also need similar rtl resources for the toolbar position picker images.

Can you help with these here so this ticket will land the resources for both pickers at the same time for a cohesive onboarding UX?

**Comment by Mugurell** [comment]
We also need to keep in mind the in-flight #7606 which comes to modify the same imagery.

**Comment by apbitner** [comment]
Gray border assets have also been added to https://github.com/mozilla-mobile/fenix/issues/7606

**Comment by Mugurell** [comment]
Thank you @apbitner for the images!

This patch will add just 
- the purple bordered rtl theme picker images and
- the gray bordered rtl toolbar position picker images

since the ltr versions of these images only had this purple / gray border and not both.
Will leave it for #7606 to add the rest of the imagery and properly handle switching between them.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that the radio button for the "Take a position" card on RTL language is displayed correctly but with the actual image, the radion button hovers the content from the displayed image.

Devices:
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 (Android 10).

Build:
- Firefox Preview Nightly 3/23 #20830607.

### Notes:
![Screenshot_10](https://user-images.githubusercontent.com/40264165/77301929-27e1fe00-6cf9-11ea-921d-55574b501fee.png)
- An additional note is that the images from the "Take a position" card don't display correctly the app experience.
- I think that till the images will be updated to a faithful experience with the app, the actual images need to be mirrored since the content from them are not in the same place as the position in the app. I filled the ticket #9316 for tracking this issue.
- Also, I want to specify that the "Choose your theme" card icons are mirrored correctly.
