### ISSUE TITLE
[Bug] <input type=file accept=image/jpeg> should allow camera capture

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8711]
> Takan from https://bugzilla.mozilla.org/show_bug.cgi?id=1616853

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

Click "Browse" on a file input with accept="input/jpeg": <input type=file accept="image/jpeg">

Actual results:

A file browsing UI opened, allowing me to pick from existing photos and images on the phone

Expected results:

I should be offered the choice between taking a new photo with the camera or picking from existing photos.

This expected behavior is how it works in Chrome for Android. Perhaps more interestingly, this is also how it works in Firefox if I add PNG to the accept list. So, for <input type=file accept="image/jpeg, image/png">, I _do_ get the choice to take a new photo with the camera. This is backwards: JPEG is the more likely format to get from the camera.

**Comment by maghoff** [comment]
I originally reported this on Bugzilla. The move from there has broken a couple of inline HTML-examples. The original text is:

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

Click "Browse" on a file input with accept="input/jpeg": `<input type=file accept="image/jpeg">`

Actual results:

A file browsing UI opened, allowing me to pick from existing photos and images on the phone

Expected results:

I should be offered the choice between taking a new photo with the camera or picking from existing photos.

This expected behavior is how it works in Chrome for Android. Perhaps more interestingly, this is also how it works in Firefox if I add PNG to the accept list. So, for `<input type=file accept="image/jpeg, image/png">`, I do get the choice to take a new photo with the camera. This is backwards: JPEG is the more likely format to get from the camera.

**Comment by softvision-miralobontiu** [comment]
Hi all,
I tried uploading an image on twitter.com, instagram.com, and imguh.com, and on all three websites, the app asks the user to choose an action: to take a photo or to search for one from the existing ones.
Tested on the 12/3 Firefox Nightly with Samsung Galaxy Tab S6 (Android 10).

![Untitled](https://user-images.githubusercontent.com/40694158/101024443-c5761880-357c-11eb-88d9-e1c9a5924066.png)

@maghoff could you try again on the latest Firefox Nightly?
Thank you!

**Comment by maghoff** [comment]
I can no longer reproduce the issue in Firefox for Android version 83. That is, in this version of Firefox, when I click such an input box, I _am_ offered the choice that was missing. I'm satisfied that this ticket should be closed.

Do note that testing against the above mentioned sites is not a valid test. Those sites all accept PNG uploads, either explicitly or through a wildcard such as image/*. To trigger the initial bug, it was necessary that the input field did not accept PNG.
