### ISSUE TITLE
Top Sites should have a header

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#8712]
Currently we don't have a header for "Top Sites" and it can be a little confusing to a new user what the purpose of these icons sitting on the homescreen are. Can we consider putting a "Top Sites" header here (similar to how we have for "open tabs" and "collections")?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/75201070-55e51a00-571c-11ea-8d0c-592432940e22.png">

**Comment by boek** [comment]
We want to wait for results from our usability studies to make a decision on this

**Comment by Diana-Rus** [comment]
Hi, verified the "Top Sites" header on Firefox Preview Nightly 200331 (Build #20910606) GV: 76.0a1-20200327094805 with:
- Google Pixel 3 XL (Android 9)
- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)

**Scenarios:**
1. Light theme - "Top Sites" header is displayed on home-screen in portrait mode ✔️ 
2. Light theme - "Top Sites" header is displayed on home-screen in landscape mode ✔️
3. Dark theme - "Top Sites" header is displayed on home-screen in portrait mode ✔️
4. Dark theme - "Top Sites" header is displayed on home-screen in landscape mode ✔️
5. Added multiple top sites to see whether the header is affected in portrait mode ✔️
6. Added multiple top sites to see whether the header is affected in landscape mode ❌
7. Moved the toolbar at top to see whether affects the top site header ✔️

**Please check GIF with scenarios on Google Pixel 3 XL (Android 9) ✔️**
![20200331-123306](https://user-images.githubusercontent.com/49859863/78012185-4b3a2800-734d-11ea-9f7c-31d50f190a5d.gif)

**Please check GIF for Samsung Galaxy S9 (Android 8) - Scenario 6 ❌**
![20200331-122156](https://user-images.githubusercontent.com/49859863/78012074-234ac480-734d-11ea-86a0-b3c01e9e0157.gif)

Note:
- The "Top Site" header is truncated when changed from portrait to landscape this happens on Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7). It isn't all the time reproducible. I think that a reproducible factor can be when having multiple top sites added.
- The truncation of the header for Samsung Galaxy S9 (Android 8) is also encountered when putting the app in background and then bring it to foreground.
- Also between "Top Sites" header and a top sites and "Open tabs" header to tabs section dotted border there is a slight difference.
- With Google Pixel 3 XL the issue was not encountered.

**Comment by mcarare** [comment]
Closing, as per above comment.
