### ISSUE TITLE
Images don't load on huffpost

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#872]
## Steps to reproduce
1. Go to huffpost.com and check the images on the homepage.
### Expected behavior
Images are displayed.
### Actual behavior
No images are loaded on this website
### Device information

* Android device: Pixel (android 9)
* Fenix version: 3/5 build.

**Comment by vesta0** [comment]
UX feedback required once we have tracking protection UI

**Comment by lime124** [comment]
I would guess that the images are not being displayed because we have tracking protection on by default. Unfortunately, at the moment there is not a way to turn those off so that the images can load. However, we are in progress of designing those controls so that tracking protection can be turned off and the images will load. #97 for the meta - we have also made a note to make sure huffpo loads the images when tracking protection has been disabled.
