### ISSUE TITLE
[Bug] Notification channel for marketing shows up as 'leanplum'

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#8745]
## Steps to reproduce
1. Open notifications settings for the app.

### Expected behavior
 - Some string like 'Mozilla Tips & Tricks' similar to Fennec.
    - cc @vesta0 for a more appropriate string if different from above.

### Actual behavior
 - It shows 'leanplum'. See screenshot.

### Device information

* Android device: Android 10 (Pixel 4)
* Fenix version: Nightly (2020-02-25)

<img width="467" alt="Screen Shot 2020-02-25 at 5 06 37 PM" src="https://user-images.githubusercontent.com/1370580/75291926-34a22d80-57f1-11ea-9df3-0a89e86ed573.png">

**Comment by jonalmeida** [comment]
@lwa-moz it seems like this channel name is coming from the LeanPlum service itself. Would you know who has access to changing this?

**Comment by lwa-moz** [comment]
@jonalmeida I can check with Leanplum support. My guess is that this string is being pulled from our Leanplum integration - we probably added a "leanplum" label somewhere, and that's being referenced here. That guess is reinforced somewhat by the fact that our Fennec integration behavior doesn't display this string.
I'll double check, but I believe this is a string we need to change in the SDK.

**Comment by lwa-moz** [comment]
Leanplum support suggests that we have defined this channel name. Perhaps this Android documentation is relevant? https://developer.android.com/reference/android/app/NotificationManager#createNotificationChannel(android.app.NotificationChannel)

**Comment by jonalmeida** [comment]
I've gone through our codebase and I don't see any references to us explicitly creating a notification channel. Our push messaging is rely entirely on the Leanplum Android SDK to create the relevant notification channels.

A quick browse through the Leanplum SDK seems to show the [notification channels are coming from a server response](https://github.com/Leanplum/Leanplum-Android-SDK/blob/7a29d5fb6f16ab58caa26a8767932124d7e8d8cf/AndroidSDKCore/src/main/java/com/leanplum/Leanplum.java#L758-L773) to Leanplum.

**Comment by jonalmeida** [comment]
After speaking with the Leanplum support, it seems like we need to set this channel via an API request the one time.

**Comment by mheubusch** [comment]
Dropping this related issue here https://github.com/mozilla-mobile/fenix/issues/4667

**Comment by mheubusch** [comment]
I asked that this be "Firefox news" in https://github.com/mozilla-mobile/fenix/issues/373 we should use this instead of "Leanplum"  and also use this label for consistency in 4667 - will comment there as well.

**Comment by jonalmeida** [comment]
I've fixed this for Fenix Nightly and done the same for Firefox Nightly

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly Build #20700607 from 03/10`** using the following devices:
• Google Pixel 4XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔️ On the Google Pixel 4XL , Google Pixel 3a, Huawei Mate 20 Lite **the notification channel is properly displayed**, "Firefox news"
►Screenshot from Google Pixel 3a
![rsz_screenshot_20200310-120351](https://user-images.githubusercontent.com/51314259/76302847-5ad3cd00-62c9-11ea-85dc-f5a2448f9924.png)

❓ On the other hand, Samsung Galaxy S7, OnePlus A3, & LG Nexus 4 the **notification channel isn't displayed in Fenix's notifications settings .**
![20200310-122457](https://user-images.githubusercontent.com/51314259/76303437-6a9fe100-62ca-11ea-8a8f-7ecfe480a9b1.gif)

@jonalmeida & @lwa-moz - Not sure how to proceed, could you please review and advise? ☺️ 
Is this happening due to the Android version ? 

I'll remove the QA needed label until further notice.

**Comment by jonalmeida** [comment]
@AndiAJ older Android devices don't have that API so you won't see the notification channel. I'll go ahead and close this issue then. Thanks!
