### ISSUE TITLE
Update collection design on home

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#8764]
### Why/User Benefit/User Problem
Reduce noise on home and improve how a collection entry is displayed.

### What/Requirements
- update design based on specs (see screenshot)
- remove icons (share, menu) in collapsed state
- remove URL preview text in collapsed sate
- show icons (share, menu) in opened state
- use [list component](https://github.com/mozilla-mobile/fenix/issues/8765) to show sites that are part of a collection

<img width="434" alt="image" src="https://user-images.githubusercontent.com/353960/75345953-fc0c5d80-589d-11ea-8f7f-5f9605fad5d3.png">
<img width="395" alt="image" src="https://user-images.githubusercontent.com/353960/75345988-07f81f80-589e-11ea-8e58-301923e72eef.png">

**Comment by ekager** [comment]
opening for verification

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 3/29 #20891805.

Devices: 
- Google Pixel 3 (Android 10);
- Samsung Galaxy Tab S6 (Android 9);
- LG g7 fit (Android 8.1).

Additionally, I want to specify that in the dark theme mode, the icons are weird since they have two rows of outlines(the grey outline with the see-through of the theme color and the favicon outline). This issue is displayed also when the page doesn't have a specific icon on Dark/Light mode.
