### ISSUE TITLE
Make dynamic nav bar optional 

### ISSUE THREAD

**Issue by tom-james-watson** [mozilla-mobile/fenix#8847]
### Why/User Benefit/User Problem

I, and many other users, find dynamic nav bars to be a frustrating UX. I don't like UI elements to move around underneath me and just find that it adds extra steps to achieve the same things when compared to a fixed nav bar.

As this was previously controlled by a flag, I assume adding a setting for this should be trivial, and would make a lot of users happy. 

## What/Requirements

Add a setting (probably to Customize->Toolbars) for whether nav bar should be dynamic or not. 

### Acceptance Criteria (how do I know when I’m done?)

I can toggle this setting off and have the nav bar be static.

**Comment by mattcoz** [comment]
Yes, this used to be controlled by browser.chrome.dynamictoolbar, but I've tried setting that to false and it does not do anything. Respecting that flag would seem to be the best thing to do here.

**Comment by AlbertoFabbri93** [comment]
According to me the best option would be to add this setting below the one that let you choose if you want the toolbar at the top or at the bottom. There is plenty of space in that screen.

**Comment by Mugurell** [comment]
Thank you for the patches @fredboy!
At a quick glance they look good! 👍

I know this is a highly requested feature but the UX specs for this are still in flux.
We have some initial feedback here - https://github.com/mozilla-mobile/fenix/issues/10240#issuecomment-641715313 but still no clear specs.
Also at this time we are in a stabilization period so big changes like this are unlikely.

But because of the work you already put in what could maybe help expedite this feature is documenting the changes (like the title for this new preference, removing the nightly flag, etc) and also adding a quick video so that UX can easily review and decide if and when we want this change.

**Comment by willfs84** [comment]
Also, this is probably an accessibility issue too. IIRC that is one of the reasons the option was added to Fennec. So not only should this be a preference under "Customize", but the dynamic nav bar should be disabled for users that have Android's "Remove animations" accessibility option enabled.

**Comment by hwinnemoe** [comment]
This has been implemented by #10240.

**Comment by Mugurell** [comment]
Closing as per the above comment.
