### ISSUE TITLE
[Bug] Closing all tabs quickly followed by 'Back' key lands the user in a 0 tab page

### ISSUE THREAD

**Issue by amitanilkulkarni** [mozilla-mobile/fenix#8894]
## Steps to reproduce

- Open one or more tabs
- Press 🗑 icon to delete all tabs
- Immediately press back button / gesture

### Expected behavior

- Not sure. Should exit the browser?

### Actual behavior

- A blank white page with 0 tabs is displayed.

### Device information

* Android device: Oneplus 7 Pro, Android 10
* Fenix version: Nightly (200301 build #20611807)

![Screenshot_20200302-133143](https://user-images.githubusercontent.com/5787171/75657073-67ce3c00-5c8b-11ea-8c82-5f6f0a0e2e05.jpg)

**Comment by sv-sdeiac** [comment]
Hi @amitanilkulkarni , I wasn't able to reproduce your issue either with the 3/1 nightly build or 3/2.
Can you perform more information regarding your problem, maybe a video with exact steps used by you. Also, please try with the latest version of Firefox Preview Nightly.
Thanks, I'll wait for your updates.

**Comment by amitanilkulkarni** [comment]
I tried it out again on the latest nightly. I am able to consistently reproduce it in these two cases:

- Use the private browsing shortcut added from settings. Keyboard pops up when you launch it. Type in any address to open a tab. Then repeat the steps I mentioned.
- Also works when you click on a link, and it opens up a private browsing instance.

I was not able to reproduce it when you open Firefox Preview from the launcher.

Here's a screen capture of this behaviour: https://gfycat.com/offbeatwellworncottontail

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 3/2 @20620608.

Devices:
- Google Pixel (Android Q);
- Google Pixel 2 (Android 9);
- Google Pixel 3 (Android Q);
- Motorola Moto G6 (Android 8).

The exact flow is:

### Prerequisites
Make sure that the app is freshly installed.

## Steps to reproduce:
1. Add a PB shortcut from Firefox Setting;
2. Close the app and open the PB shortcut;
3. Open a page;
4. Go to the tab drawer;
5. Close the tab by tapping the trash button;
6. Quick after that, tap the back button.

## Expected results
The PB app is closed.

## Actual results
A blank page is displayed.

![20200302_123029](https://user-images.githubusercontent.com/40264165/75668312-d3131080-5c81-11ea-8ac5-0770f8b66852.gif)

**Comment by opusforlife2** [comment]
> Quick after that, tap the back button.

You don't even need to be quick. If you wait for some time and _then_ tap back, you get a blank white screen with a solid purple bar instead of the address bar. (v4.1 release)

**Comment by opusforlife2** [comment]
I haven't actually seen this problem for quite a while now. Maybe it was fixed unintentionally. This could be closed unless someone mentions they're still facing this.

**Comment by sflorean** [comment]
I wasn't able to reproduce this issue either following the steps provided with Pixel 3 (Android 11) & latest Nightly. Closing based on the above comment.
