### ISSUE TITLE
[Bug] Pause/resume don't work when downloading more files

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8930]
## Steps to reproduce
1. Go to https://www.thinkbroadband.com/download and download two or three different files.
2. Go to the download notifications.
3. Pause/resume every download.

### Expected behavior
All the buttons react accordingly - pause when asked to, resume when asked to.

### Actual behavior
The user must tap 2-3 times until the pause/resume responds. 

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Google Pixel 3A (Android 9)
* Fenix version: 3/3 Nightly build 

![trim](https://user-images.githubusercontent.com/40694158/75778673-eea11880-5d60-11ea-8d7e-8ecb428d7706.gif)

**Comment by AndiAJ** [comment]
Hi, reproducible on **`Beta 4.0.0-beta.3`** using a OnePlus A3 (Android 6.0.1).
❗️ There's also an odd movement of the download notification bars.

► Video
![20200304-151608](https://user-images.githubusercontent.com/51314259/75883584-e8c43980-5e2b-11ea-97c2-169547fe5b9c.gif)

**Comment by sblatz** [comment]
Leaving for the AC team: Has something major changed in the download manager? This definitely didn't used to happen 😅

**Comment by Amejia481** [comment]
This https://github.com/mozilla-mobile/android-components/pull/6458 pr fixes, it will be available on the new AC build.

**Comment by Amejia481** [comment]
This is ready for QA :)

**Comment by sv-sdeiac** [comment]
Hi, the issue is partially fixed since the lack of response is shorter but it is still visible. 
Also, the odd movement is still displayed.

Devices:
- LG g7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9);
- Xiaomi Mi 8Lite (Android 9);
- Google Pixel 3 (Android 10).

@Amejia481 can you take a look?

![20200408_093933](https://user-images.githubusercontent.com/40264165/78752799-6b856a80-797d-11ea-83de-df7d28a6af07.gif)

**Comment by AndiAJ** [comment]
And still moving on a OnePlus A3 (Android 6.0.1) ☺️ 
► Video
![20200408-141505](https://user-images.githubusercontent.com/51314259/78778416-ea8d9980-79a3-11ea-8e36-9aac401a8d15.gif)

**Comment by Amejia481** [comment]
> Hi, the issue is partially fixed since the lack of response is shorter but it is still visible.
> Also, the odd movement is still displayed.
> 
> Devices:
> 
>     * LG g7 fit (Android 8.1);
> 
>     * Samsung Galaxy Note 8 (Android 9);
> 
>     * Xiaomi Mi 8Lite (Android 9);
> 
>     * Google Pixel 3 (Android 10).
> 
> 
> @Amejia481 can you take a look?
> 
> ![20200408_093933](https://user-images.githubusercontent.com/40264165/78752799-6b856a80-797d-11ea-83de-df7d28a6af07.gif)

[The slow response is a restriction imposed by Android](https://developer.android.com/training/notify-user/build-notification#Updating), we can't update a notification faster than 1 seconds, for example the slow response is only visible when the file is getting downloaded because we are updating the notification every second to reflect the file progress. Unfortunately, there nothing more that we can do to improve the response time

**Comment by Amejia481** [comment]
> And still moving on a OnePlus A3 (Android 6.0.1) ☺️
> ► Video
> ![20200408-141505](https://user-images.githubusercontent.com/51314259/78778416-ea8d9980-79a3-11ea-8e36-9aac401a8d15.gif)

The notification odd movement is only present in OnePlus A3 (Android 6.0.1). @sv-sdeiac  @AndiAJ ? Would you mind trying to download multiple files on Chrome? and see if the movement is present there?

**Comment by AndiAJ** [comment]
Hi @Amejia481 , I've just re-checked this matter.

✔️ No issues encountered on OnePlus A3 (Android 6.0.1) while downloading on Chrome
► Video
![20200408-175028](https://user-images.githubusercontent.com/51314259/78800798-8af3b600-79c4-11ea-8cae-560ffa02b3ec.gif)

❓ Noticed a flicker on a Huawei Mate 20 Lite (Android 9) of the "Just now" while downloading the files on Fenix
► Video
![20200408-175301](https://user-images.githubusercontent.com/51314259/78801330-3997f680-79c5-11ea-9175-fbc02030212c.gif)

✔️ No issues using the  Huawei Mate 20 Lite (Android 9) on Chrome 
► Video
![20200408-175439](https://user-images.githubusercontent.com/51314259/78802150-26395b00-79c6-11ea-87e3-6f31b608fe9e.gif)

**Comment by Amejia481** [comment]
@AndiAJ do you mind taking a look? It should be already on master :)

**Comment by AndiAJ** [comment]
Hi @Amejia481 , I've rechecked this matter on the on the latest **`Nightly Build #21060608 from 4/15`** using the following devices:
•  Google Pixel 3a (Android 10)
•  Huawei Mate 20 Lite (Android 9)
•  OnePlus A3 (Android 6.0.1)

✔️ Works properly on both Google Pixel 3a and  OnePlus A3 **(the previous movement issues got fixed)**

► Video
![20200415-155550](https://user-images.githubusercontent.com/51314259/79343458-16c29080-7f37-11ea-9edd-aef8c4015e70.gif)

❌ On the other had I've noticed a flicker while testing on the Huawei Mate 20 Lite.
Because of this I've opened #9954 

► Video
![20200415-155956](https://user-images.githubusercontent.com/51314259/79343426-0b6f6500-7f37-11ea-8cf2-83d9878bdbda.gif)

I'll mark this issue **verified as fixed** 
The remaining flicker problem will be tracked in #9954
