### ISSUE TITLE
[Bug] font inflation and css column collisions

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#8962]
## Steps to reproduce
1. Go to http://logs.guix.gnu.org/

### Expected behavior
the text is readable

### Actual behavior
the text is overlapped

### Device information

* Android device: pixel 2
* Fenix version: firefox preview nightly 75 2020-03-03

same family than #8448

This was reported on https://github.com/webcompat/web-bugs/issues/49396

there's a very long list, `li` elements, wrapped into a `ul`

```css
ul {
	column-count: 20;
	column-width: 170px;
}
```

note that it explodes in some ways on chrome too.

**Comment by ekager** [comment]
See also #8448

**Comment by ekager** [comment]
cc @buttercookie42 is this a known issue? 
Gecko nightly vs Chrome
![Screenshot_20200415-122418](https://user-images.githubusercontent.com/25442310/79379676-1bc21880-7f14-11ea-8475-2a43442d9907.png)
![Screenshot_20200415-122414](https://user-images.githubusercontent.com/25442310/79379681-1cf34580-7f14-11ea-93a7-ec35328253fd.png)

**Comment by buttercookie42** [comment]
I haven't checked all old bugs exhaustively, but at least to me its new, yes.
While Chrome ultimately renders overlapping columns as well if the column width is excessively small and it can't break the content, it seems in our case the problem is exacerbated because we don't seem to treat hyphens inside of pure runs of numbers as word-breaking opportunities.
In the end, though, the fix still should be on the font-inflation side, I guess... I'll try and take a look when I can find some time for that again.
