### ISSUE TITLE
[Bug] Crash when approving the password update

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8967]
## Steps to reproduce
1. Open twitter.com, or youtube.com, or any site that requires signing in.
2. Select to save the credentials.
3. Sign out. 
4. Open the page from step 1 again, with the same username, but a different password. When the "Update password" prompt is displayed, select to update the password.

### Expected behavior
The password is updated.

### Actual behavior
Fenix crashes. 

### Device information
* Android devices: Xiaomi MiPad 2 (Android 5.1), Huawei P9 Lite (Android 7)
* Fenix version: Beta 4.0.0-beta.3, and on 3/4 Nightly build
* Not reproducible on Beta 74.0.0-beta.2

[update login crash log.txt](https://github.com/mozilla-mobile/fenix/files/4286771/update.login.crash.log.txt)

**Comment by liuche** [comment]
AC issues here: https://github.com/mozilla-mobile/android-components/issues/6184

**Comment by softvision-miralobontiu** [comment]
This is not fixed on 3/6 Nightly build. Tested on LG G7 (Android 8.1), and Samsung Galaxy Note 8 (Android 9). I'll remove the qa:needed label for now.

**Comment by softvision-miralobontiu** [comment]
The crash is reproducible on Beta v4.0.0-beta.4 if the Autofill option from Logins and passwords is disabled.
Tested with:
- Xiaomi MiPad 2 (Android 5.1),
- LG G7 (Android 8.1),
- Google Pixel (Android 10), and
- Huawei P9 Lite (Android 7.0).

Please see the logcat:

[autofill disabled crash.txt](https://github.com/mozilla-mobile/fenix/files/4298254/autofill.disabled.crash.txt)

**Comment by ekager** [comment]
In AC, `GeckoLoginStorageDelegate#onLoginFetch`, we are returning an empty list to GV when Fenix autofill is toggled off so that it doesn't fill any fields on the page. Then when GV gives us a login to save, we use `validateCanPersist` in the `DefaultLoginValidationDelegate` and we know we can update a record. But when we go to update it, the login doesn't have a correct guid (probably because GV didn't know about the previous records when they asked for them earlier in `onLoginFetch`).

Ideally, we could toggle GV autofill off via a setting but that might take a while to get, but we could also look into doing a more robust handling of the different cases in `onLoginSave`. We are currently using a separate method in `GeckoLoginStorageDelegate` and we should probably be using the same `validateCanPersist` logic as in the `LoginDialogFragment`.

If we want to ship 4.0 ASAP we can hide the option to separately turn off autofill vs what we have now (can turn off autofill separately to "ask to save logins"). [Branch for this](https://github.com/ekager/fenix/tree/hide-autofill-option)

Otherwise I can keep looking into this and we can regroup next week

**Comment by ekager** [comment]
We've decided to temporarily remove the separate "autofill" pref while we investigate this with the involved teams. The "should ask to save login" pref will control saving and filling temporarily.

**Comment by ekager** [comment]
https://github.com/mozilla-mobile/fenix/issues/8967#issuecomment-595742919 is ready to retest on [v4.0.0-beta.5](https://github.com/mozilla-mobile/fenix/releases/tag/v4.0.0-beta.5)

**Comment by softvision-miralobontiu** [comment]
We're not able to reproduce the crash on Beta v4.0.0-beta.5 with the steps from [Comment 0](https://github.com/mozilla-mobile/fenix/issues/8967#issue-575294438).
The "Autofill" option is not available on Beta v4.0.0-beta.5, therefore we cannot test the scenario from this [comment](https://github.com/mozilla-mobile/fenix/issues/8967#issuecomment-595742919).

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce the crash again with Samsung Galaxy Tab A6 (Android 5.1.1), on the latest build from 3/18 (#20780606).
Not reproducible with OnePlus 5T (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), Xiaomi MiPad 2 (Android 5.1).

Logcat:
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4348036/logcat.txt)

![crash_Trim](https://user-images.githubusercontent.com/40694158/76945695-8ed37180-690b-11ea-96b5-3ec336f1bafb.gif)

**Comment by ekager** [comment]
There is a new GV runtime setting for `loginAutofillEnabled` so we can now stop conflating the two settings and expose the autofill setting again

**Comment by ekager** [comment]
In the next Nightly, you should be able to toggle autofill and toggle save logins separately without crashing. Let's test it!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 6/11 using Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi Mi4i (Android 5.1), and Google Pixel (Android 10).
