### ISSUE TITLE
[Bug] "Share" menu "All Actions" panel does not have correct scroll endpoints

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8985]
## Steps to reproduce
Open "Share" menu
Scroll "ALL ACTIONS" list left and right
Left end stops correctly and has overscroll crescent
Right end stop does not, half an icon visible, no overscroll crescent
--> incorrect behavior

### Device information

* Android device: Galaxy A40, Android 9.0.0
* Fenix version: Today's

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that the half icon problem is visible using:
-  Nokia 6 (Android 7.1.1) - 1080 x 1920 pixels (~403 ppi pixel density);
- LG g7 fit (Android 8.1) - 1440 x 3120 pixels, 19.5:9 ratio (~563 ppi density).

Also, the issue is not reproducible using Xiaomi Mi 8 Lite (Android 9) - 1080 x 2280 pixels, 19:9 ratio (~403 ppi density).

Additionally, the overscroll crescent is visible in any direction.

Build:  Firefox Preview Nightly 3/5 #20650606.

**Comment by AndiAJ** [comment]
Reproducible on **`Fenix Beta 4.0.0-beta.4`** using a OnePlus A3 (Android 6.0.1) device.
❗️ Some of the apps can't be reached while in portrait mode.

►  Video
![20200306-135628](https://user-images.githubusercontent.com/51314259/76082260-99107a00-5fb3-11ea-8165-bd5fbb713226.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #20700607 from 03/10`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video
![20200310-104124](https://user-images.githubusercontent.com/51314259/76294923-6967b780-62bc-11ea-9552-b229e4a0d6b8.gif)
