### ISSUE TITLE
[Meta] Bookmarks (formerly Favourites)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#90]
Favourite != bookmark and won't provide bookmark management 
Will be stored locally in your library, will show up in history, recency

Update Feb 22: We've agreed that we revert back to using Favourites as bookmarks.

### User story:
As a user, I want to be able to bookmark a site, view it, remove it, share it, and sync it with my other devices, so I can save time finding information I need, stay organized, and have a seamless experience switching between my devices. 

### Dependencies:
A-C (done)
Currently blocked by: https://github.com/mozilla/application-services/issues/880

**Comment by davismtl** [comment]
@bbinto I'm trying to get some clarification for myself, my team and some members of leadership who have asked me about bookmarks and bookmark syncing.

Would it be possible to get details on how favorites and bookmarks are different? User stories and or success criteria would be nice here if possible.

It is my hope to help you achieve your goals here.

For reference, here are some questions I've been asked:
- Will Fenix have bookmarks? If so, when?
- Will Fenix Sync bookmarks? If so, when?
- What's the difference between bookmarks and favorites? (asked above)
- Are favorites just a flat structure of bookmarks?
- Are favorites just a stop-gap until there is a bookmarks component with full management?
- If favorites are different than bookmarks, should they be synced?
  - If they are synced, how should they be displayed on desktop and how do we differentiate them from bookmarks?

Thanks in advance for looking into this.

CC @ryanfeeley

**Comment by ryanfeeley** [comment]
@bbinto Would love to hear more about this. It's very difficult to argue that favourites do not equal bookmarks when bookmarks are called favourites in Internet Explorer. I wholly support Fenix doing something different with the interface to present and manage bookmarks, but creating a datatype outside of the ecosystem without a clear plan is a form of cannibalization.

**Comment by bbinto** [comment]
@ryanfeeley I agree and talked to UX (@topotropic and @shorlander)

Finally replying here (although I've already caught up with Alex offline)

* Will Fenix have bookmarks? If so, when?
Yes, for MVP

* Will Fenix Sync bookmarks? If so, when?
Yes, ideally for MVP

> What's the difference between bookmarks and favorites? (asked above)
@shorlander should add more color here as he will be providing more details on that, however overall, we want to treat them similar than bookmarks from the data structure / syncing aspect. They might be shown different UI, i.e. in a flat structure

> Are favorites just a flat structure of bookmarks?
see above

> Are favorites just a stop-gap until there is a bookmarks component with full management?
No
  
> If they are synced, how should they be displayed on desktop and how do we differentiate them from bookmarks?
@shorlander and @topotropic to provide their input. 

Unless there is a really strong case from UX (I would need to be convinced with data :)
), I would like to go with the simplest way / feature parity to Fennec where possible, this will  make the transition from Fennec sync to Fenix sync easier.

**Comment by yoasif** [comment]
@bbinto This is very confusing to picture, I read this a couple of times, and the most I was initially able to  make out is that "favorites" is like "Top Sites" in Fennec and Firefox Desktop, except that they might be presented as a list instead of tiles -- and that they would be saved in bookmarks somehow (and so would appear on synced devices, unlike top sites).

> >Are favorites just a stop-gap until there is a bookmarks component with full management?

>No

This is worrisome though, since it sounds as if "Favorites" _replace_ bookmarks somehow (flattening them?) and so I don't quite understand how that reaches feature parity with Fennec when there is synced data from Desktop Firefox (which can contain folders). On Fennec, while users cannot choose where to create bookmarks initially, they are able to move them anywhere, including into "Desktop Bookmarks" folders, in either the bookmarks list or in the edit UI that appears after a user clicks "options" in the snackbar that appears after they bookmark an item. 

I have seen comments where users are confused as to why there is such a strict separation between Mobile and Desktop bookmarks, [example](https://www.reddit.com/r/firefox/comments/7p7v0z/who_else_thinks_that_ff_works_like_shit_in/dsg19p8/):

> And why the hell there are two groups of bookmarks? One says mobile and other says my Ubuntu OS? If I am the same person then why categorise bookmarks between phone and PC? 

Response

> You just cannot choose where to put bookmarks on mobile. Mobile can view properly organised bookmarks from desktop no problem. :/

I launched Chrome and realized why. While Chrome defaults users to "Mobile Bookmarks" like Fennec, users can choose to create folders _inside_ mobile bookmarks, but more importantly, unlike Fennec, it remembers the last place the user created a bookmark and saves it there, without the dance of "options > edit > move". 

So users can actually ignore "Mobile Bookmarks" on Chrome entirely (when Sync is enabled) and save directly into "desktop" bookmark folders. 

**It feels very intuitive and I think it belongs in Fenix.**

Bookmark discovery in Chrome is worse than in Fennec though - it is hidden behind a hamburger menu, whereas about:home has a nice tab for it. What is handy though, is that the bookmarks UI in Chrome remembers the last place you were, which would be another nice improvement to bring to about:home in Fenix (is that planned?) so that users don't need to drill into desktop bookmarks if they are defaulting their bookmark creation to a non root Mobile Bookmarks folder. 

I took a screen recording of the process to create bookmarks in non default (and flat) hierarchies in Fennec - it isn't very convenient, but it is possible (it is nicer in Chrome).

https://drive.google.com/open?id=1w1gpRAAiQ3UIS41U5BDbEAnpDr_FhL6W

**Comment by cadeyrn** [comment]
> This is worrisome though

I agree. Bookmarks are one of the most important features of any browser, especially on a smartphone where typing URLs is such an annoying thing. And because bookmarks are so important, the ability to organize them is important, too. With only five bookmarks you won't need folders. But with many bookmarks it's not easy to find your bookmarks if you don't have any structure. In my opinion a flat hierarchy is really not sufficient for bookmarks.

The bookmarks management in Fennec is not perfect. But it's good enough for a first version. To lose this feature would be a huge regression IMO.

**Comment by davismtl** [comment]
I'll try to shed some light here.
@bbinto mentioned:
>> Will Fenix have bookmarks? If so, when?
>Yes, for MVP

>> Will Fenix Sync bookmarks? If so, when?
>Yes, ideally for MVP

Ultimately, Fenix will have bookmarks and they will sync to desktop and other devices. The Application Services team has already been working on the Rust component for Bookmark storage and syncing. The component will be designed to provide Fenix with bookmark management that will be at parity with desktop. (i.e. full management with ability to create folders, rename, etc) It will just be a matter of surfacing UI to do it. 

Everything can be summarized by the answers of these two questions:
- Will users expect to find their desktop bookmarks on Fenix? We believe the answer is yes.
- Will Fenix users expect to find their bookmarks/favorites on Desktop? We also believe the answer to be yes.

In terms of UI/UX changes... @bbinto said:
> I would like to go with the simplest way / feature parity to Fennec where possible, this will make the transition from Fennec sync to Fenix sync easier.

This all being said, the initial post in this issue is inaccurate now based on Barbara's most recent [comment](https://github.com/mozilla-mobile/fenix/issues/90#issuecomment-461026811) (and my offline conversation with her):
> Favourite != bookmark and won't provide bookmark management

As a side note, bookmarks have a concept of **labels** which aren't widely used by users but are in the data model. In the future, we can explore and experiment with a new UI or various ways of sorting bookmarks. This should allow us to explore the types of experiences that Barbara initially had in mind while maintaining compatibility with other browsers.

**Comment by bbinto** [comment]
Thanks everyone (@yoasif @cadeyrn etc), I've updated my original comment and confirm that we will provide bookmark like functionality with the goal to have them also synced for MVP (should).

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.
https://docs.google.com/spreadsheets/d/1te0ap-CE9tzZGvdPRmYBB5aWTW3L5gZLZhxA8tG5tgM/edit?usp=sharing

**Comment by vesta0** [comment]
The work for MVP is completed.
