### ISSUE TITLE
Bottom of page missing (shows as white like it's cut off)

### ISSUE THREAD

**Issue by overholt** [mozilla-mobile/fenix#9086]
https://rachelbythebay.com/w/2020/03/09/bzzz/ renders with a blank bottom section in Fenix Nightly ("Tuesday 3/10 @ 6:06 AM" -> GV 75.0a1-20200309091841):

![Screenshot_20200310-085647](https://user-images.githubusercontent.com/591864/76339441-77273800-62d0-11ea-9317-438e15e54e10.png)

but renders correctly in Fennec (68.5.0):

![Screenshot_20200310-085654](https://user-images.githubusercontent.com/591864/76339503-8efebc00-62d0-11ea-8fb6-4103ae165166.png)

**Comment by sv-sdeiac** [comment]
Hello, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 3/11 #20710604.
This issue disappears after zoom-in a little bit the page but reappears after zoom-out.

#### Devices:
- Google Pixel (Android Q) - 1080 x 1920 pixels (~441 ppi pixel density);
- Nokia 6 (Android 7.1.1) - 1080 x 1920 pixels (~403 ppi pixel density).

Also, I can't reproduce this issue using Samsung Galaxy Note 10 (Android 9) - 1080 x 2280 pixels, 19:9 ratio (~401 ppi density).

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
