### ISSUE TITLE
Ensure VisualCompletenessTaskManager starts in all circumstances

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9179]
We're concerned that the `VisualCompletenessTaskManager` might not `start` if the frame that it posts from is never drawn, e.g. app is immediately put into the background on startup. We should validate this use case and others to ensure the task manager always runs. I wonder if we should also add telemetry to double-check.

emalysz has already done some work in this area.

**Comment by emalysz** [comment]
I verified that the `VisualCompletenessTaskManager` hooks into the first frame, so we will always start the task manager. 

I also implemented a delay before the `rootContainer.doOnPreDraw` call, backgrounded the app, and ensured that all of the tasks still executed. Those tasks are not retriggered when we navigate back into the app (warm/hot start). 

If we remove the application from memory and force a cold start, those tasks will be triggered again, which is to be expected. 

Closing the issue because these are the only use cases I could think of.
