### ISSUE TITLE
[Bug] Enhanced tracking protection - exceptions 

### ISSUE THREAD

**Issue by swejuggalo** [mozilla-mobile/fenix#9334]
Tried to find this reported but could not find it. So here it is. 
## Steps to reproduce
Add some exceptions. Remove one in settings. 
### Expected behavior
Removal of one exception rule 
### Actual behavior
Removal of all exceptions 
### Device information
OnePlus 7 Pro
* Android device: Oxygen OS beta 11 (Android 10)
* Fenix version: Nightly 200323 10:21 (Build #20831027)

**Comment by swejuggalo** [comment]
Tested in a most current dev build. Looks like it works as intended now

**Comment by Amejia481** [comment]
Thanks for reporting :)

**Comment by Diana-Rus** [comment]
Hi, reproduced the issue with Firefox Preview Nightly 200323 (Build #20831026) with all testing devices.

**Reproduced:**
![20200325-162317](https://user-images.githubusercontent.com/49859863/77548690-8b198f00-6eb7-11ea-98d0-6aea2c08e538.gif)

**Confirmed that the issue is not reproducible on Firefox Preview Nightly 200325 (Build #20850608) GV: 76.0a1-20200323092419 with:**
- Google Pixel 3 XL (Android 9)
![20200325-162640](https://user-images.githubusercontent.com/49859863/77548647-7ccb7300-6eb7-11ea-85e6-c7d509b757db.gif)

- Samsung Galaxy S9 (Android 8)
![20200325-161615](https://user-images.githubusercontent.com/49859863/77548727-979de780-6eb7-11ea-88f5-4856d6bc2b4c.gif)

- Sony Xperia Z5 (Android 7) 
![20200325-161430](https://user-images.githubusercontent.com/49859863/77548750-a2f11300-6eb7-11ea-80ae-06d53905a7be.gif)
