### ISSUE TITLE
[Bug] File types not supported > Download failure

### ISSUE THREAD

**Issue by andrecc-7** [mozilla-mobile/fenix#9380]
## Steps to reproduce
Upload .txt file to firefox send.
Download the file from firefox send.
(There are a few more types who fail, but for now I only tested in firefox send this)

### Expected behavior
Download success.

### Actual behavior
Download failure.

// You developed an entire browser, but it cannot download a .txt, even though .pdf are ok? I don't mean to be rude, but this lowers expectations for complex features.

**Comment by andrecc-7** [comment]
It's one of the top issues xd... (closing this dup)

**Comment by a2468834** [comment]
Why did you close this issue? So sad. 😢
It has been bothering me since I started to using Finix. 😭

At the beginning, I thought this bug might arise from downloading a large file (e.g. 1GB).
However, I would encounter this bug while downloading small files (e.g. few KBs).

Hope that project developers could fix this bug.
After all, Firefox Send is one of projects developing by Mozilla.

**Comment by andrecc-7** [comment]
It's a duplicate. They're aware of the issue.

**Comment by kbrosnan** [comment]
It is better to mention the issue number so that the dupe is clear. #3336

**Comment by a2468834** [comment]
Thanks for mention that issue number.
