### ISSUE TITLE
Browser language matching Android system settings

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#940]
### Why/User Benefit/User Problem

As a User I want to use Fenix in the same language I use for my device. I want Fenix to follow the language settings that I have chosen in the Android system settings. 

### What / Requirements

- TBD Determine the list of locales that Fenix MVP will support.

### Acceptance Criteria (how do I know when I’m done?)

The Fenix UI appears in the user's locale. If the system locale is not supported by Fenix, then Fenix appears in English.

**Comment by colintheshots** [comment]
This *should* happen automatically, but we'll want QA to validate it. Switching system locale on Android is a configuration change, so it'll force all activities to restart and re-draw.

**Comment by vesta0** [comment]
@cpeterso do we have a GV API for this?

**Comment by cpeterso** [comment]
> do we have a GV API for this?

No. We should make Gecko's `Accept-Language` HTTP header automatically detect the system language settings or add a GV API for the app to set the `Accept-Language` values. I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1543823. I don't think this Gecko or GV bug needs to block Fenix MVP because many websites (frustratingly) select a content language using GeoIP instead of the browser's `Accept-Language` HTTP headers.

Fenix can update its app UI's language to match the system language settings without a GV API.

**Comment by bsurd** [comment]
Verified with Deutsch, Fenix successfully manages to swap between en and de. If the selected language is not supported/implemented in Fenix the default fallback language is en.
