### ISSUE TITLE
Provide solution/handler for intermittent taskcluster job dependency download failures

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#9461]
In an effort to better handle intermittent taskcluster job failures, we'd like to address the issue where dependencies temporarily fail to download by retriggering the job. This will handle the most common case where there was a network interruption or momentary service outage (but probably not the case where there was a longer service outage).

@JohanLorenzo mentions we can do this in the following way:
[1] capture exit code returned by gradle 
[2] update the task payload to rerun the task whenever that same exit code is returned 

@JohanLorenzo is there a good example of updating task payload we could follow to implement this?

**Comment by JohanLorenzo** [comment]
Yes! 😃 

It should be a matter of defining `worker.retry-exit-status` in `kind.yml`. For instance: https://searchfox.org/mozilla-central/rev/9c6e7500c0015a2c60be7b1b888261d95095ce27/taskcluster/ci/release-final-verify/kind.yml#25

The numerical value here is just the plain shell exit code.

**Comment by rpappalax** [comment]
Sounds good, @JohanLorenzo!  @sblatz do you recall which jobs occasionally see dependencies fail to download? I'm gonna add `retry-exit-status: [1]` to the job-defaults for `/test` (test-debug) and `/build`.  I think the latter is the one that usually has the most flakiness when downloading dependencies. Perhaps we should start with those?

**Comment by rpappalax** [comment]
re-opening issue as this will require some additional checking in order not to re-try on true build failures:
[failed fenix tasks shouldn't get automatically retried, at least if build failed](https://bugzilla.mozilla.org/show_bug.cgi?id=1628807)

**Comment by rpappalax** [comment]
per @JohanLorenzo, caching external deps may solve this issue, see:
https://github.com/mozilla-mobile/reference-browser/pull/1117

**Comment by Archaeopteryx** [comment]
Questions when the task gets turned on again in the future:

1. Shall the intermittent failures be ignored like in the first deployment or shall the job get reported as failure and retried?
2. How difficult is it to retry the download instead of the task to reduce task and e.g. I/O overhead (for downloads before which succeed)
3. The tasks which got retried have short run durations, for longer running ones this would the delay the test result by duration x 6. 10 minute task => failure reported after one hour
