### ISSUE TITLE
[Bug] Wrong tab count after transferring from in-app to full browser

### ISSUE THREAD

**Issue by kyouma** [mozilla-mobile/fenix#9489]
## Steps to reproduce
1. Open a link with in-app variant of Fenix (e.g. in Telegram).
2. Open the 3 dot menu > Open in Firefox
3. The number of tabs will not count the new one until you open the tab list.

### Expected behavior
The tab count number must be increased by 1 after sending a tab from in-app Fenix to full Fenix.

### Actual behavior
The tab count number doesn't count the new tab.
The video demonstration on Yandex Cloud: https://yadi.sk/i/cYnySEt8A5WVzw

### Device information

* Android device: Galaxy S10e, Android 10.
* Fenix version: Firefox Preview 4.1.0 and the Nightly #20880607.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 3/31 (Build #20910607).

Devices:
OnePlus 6T (Android 9);
Huawei MediaPad M3 lite 10 (Android 7.0)
![9489](https://user-images.githubusercontent.com/50983519/78039381-bb10d880-7376-11ea-96e4-35968197a9a6.gif)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201215 (Build #2015781483).

### Devices used:
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus 6T (Android 9)
