### ISSUE TITLE
Add Button Ripples Animations to Dialog and Snackbar Buttons

### ISSUE THREAD

**Issue by theFireProject** [mozilla-mobile/fenix#9516]
### Why/User Benefit/User Problem
It's a visual improvement that enhances look and feel of the graphical user interface. This is a common feature for Material Design that gives feedback to the user when they interact with a button. That behavior is known and expected by users. Missing button animations for dialogues and snackbars in Fenix is a regression from Fennec.

### What/Requirements
Add the standard button animations from Android as known from Fennec to Fenix when interacting with buttons of dialogues and the button on snackbars:
- holding down the button by tapping it without releasing it
Animation: slowly fade in marking (see screenshots)
- releasing the button without activating it by moving away from it
Animation: display circular animation that increases in size while fading out (see screenshots)
- activating the button by releasing it
Animation: fade out marking

### Acceptance Criteria (how do I know when I’m done?)
If interaction with buttons of all dialogues and all snackbars is animated.

### Screenshots (6)
- Fenix, missing animations:

![20200330_152119](https://user-images.githubusercontent.com/61639215/77917805-49179100-729b-11ea-8744-b2581aad965b.jpg)
![20200330_152157](https://user-images.githubusercontent.com/61639215/77917825-50d73580-729b-11ea-84fc-7082e67e96e0.jpg)

- Fennec, common animations:

![20200330_152247](https://user-images.githubusercontent.com/61639215/77917898-68aeb980-729b-11ea-9f17-52352a80a29a.jpg)
![20200330_152303](https://user-images.githubusercontent.com/61639215/77917906-6c424080-729b-11ea-99e4-dccef4bdde3e.jpg)
![20200330_152409](https://user-images.githubusercontent.com/61639215/77917925-73694e80-729b-11ea-9696-ed3184bae73e.jpg)
![20200330_152335](https://user-images.githubusercontent.com/61639215/77917932-76643f00-729b-11ea-9809-fdfde0c99188.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16514)

**Comment by Poopooracoocoo** [comment]
The ripple animations you described sound like Android 7-8. Android 5-6 and Android 9-11 have different animations.

**Comment by sv-sdeiac** [comment]
Hi, I tested this issue and I found 3 different problems:

- In dark theme, the ripples don't display the circular animation that increases in size while fading out. This is reproducible in any type of ripples.
![20200422_105829](https://user-images.githubusercontent.com/40264165/79962286-87fec800-8490-11ea-8901-6462533cce80.gif)

- In light theme, the ripples are not displayed anywhere on confirmation pop-up(cancel/delete)
![20200422_110244](https://user-images.githubusercontent.com/40264165/79963057-8da8dd80-8491-11ea-9806-5ec3fcde8e1c.gif)

- In light theme, the ripples are not visible due to the contrast on snackbar (switch/undo)
![20200422_110118](https://user-images.githubusercontent.com/40264165/79962996-7d90fe00-8491-11ea-8be4-2ba03ff11ae4.gif)

@ekager, can you take a look at those details and come with updates about them?
I'll remove the qa:needed flag till we have some updates, thanks.

**Comment by Poopooracoocoo** [comment]
@sv-ohorvath those buttons don't have a shape too. On Android buttons are typically rounded rectangles but some people customise them. 

![image](https://user-images.githubusercontent.com/51363864/79983230-c9bc5c80-84ea-11ea-91e5-248f5118dba8.png)
https://material.io/components/dialogs

**Comment by ekager** [comment]
Yep, those all look like valid issues! I'm going to unassign myself for now, but anyone is free to pick this up if they have ideas.

**Comment by czlucius** [comment]
> Yep, those all look like valid issues! I'm going to unassign myself for now, but anyone is free to pick this up if they have ideas.

I would like to work on this issue

**Comment by czlucius** [comment]
`android:colorControlHighlight` seems to control the ripple color when using `?android:attr/selectableItemBackgroundBorderless`

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807131

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
