### ISSUE TITLE
[Bug] Incorrect behaviour when long-pressing on a tab

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9540]
## Steps to reproduce
- go to 'Open tabs' overview
- tap and hold a tab (don't release the tab, keep holding it)

### Expected behavior
- When you tap and hold a tab, after a short delay the 'Select Tabs' view appears to save that tab to a collection.
- Now, if you keep holding your finger on the screen, nothing should happen because an action has already been performed.

### Actual behavior
- Instead, if you move your finger, you can still scroll the 'Open tabs' view in the background while the 'Select Tabs' view is in the foreground.

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.2.0

**Comment by sv-sdeiac** [comment]
Hi, thanks for your report.
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 3/31 #20910606.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).
![20200331_143824](https://user-images.githubusercontent.com/40264165/78022328-6dd43d00-735d-11ea-8e19-e7a3b530d251.gif)

**Comment by sv-ohorvath** [comment]
The design was updated and this is no longer applicable. closing
