### ISSUE TITLE
Ability to rename top sites

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/fenix#9548]
### Why/User Benefit/User Problem

Some sites, e.g., The Guardian, have long titles that abbreviate poorly.  For example, "News, sport and opinion from the Guardian's US edition | The Guardian" turns into, "News, spor...".  Allowing users to rename these would enable more description titles.

### What/Requirements

Long press on top site currently brings up a dialog with "Open in private tab" and "Remove".  Add "Rename" which brings up a dialog with current name edit box and cancel and rename buttons.  Pressing rename will modify the underlying SQLite database and refresh the page.

### Acceptance Criteria (how do I know when I’m done?)

Users can rename top sites.

Update from UX:
- add a new menu entry "Rename" to the menu that appears on long press
- show a dialog (same design that we use for the "create new collection" case) where people can update the name
![image](https://user-images.githubusercontent.com/353960/96874548-84b3bb80-1476-11eb-9dda-3d99b01de35a.png)

**Comment by Matth7878** [comment]
Top sites text should also be displayed on 2 lines.
I have 3 top sites for direct link to GitHub Project. If you don't know which one is which it's impossible to tell them apart.

Being able to rename would be a nice improvement but still you got only 11 characters which is really short. 
What if I have 2 top sites one for a direct link to commits and another to issues or whatever? (And of course still having other top sites for other GitHub projects)
Having 22 characters would be very useful to have meaningful name.

Not sure if it should be a new issue but I feel it belongs with this one as "Top Sites text should be useful"

**Comment by gaul** [comment]
Alternatively, it would be nice to allow rename *during* adding a top site, similar to what is done for adding to the home screen.  Or store the top sites in bookmarks so we can use that interface to manage top sites.

**Comment by anotherus3r** [comment]
Yes, this would be a really useful feature. The Guardian and Euronews are two examples of sites I'd find this feature useful for.

> Alternatively, it would be nice to allow rename during adding a top site, similar to what is done for adding to the home screen. Or store the top sites in bookmarks so we can use that interface to manage top sites.

In my opinion, this solution would be somewhat better, but both the original one and this one would be good to have.

**Comment by liuche** [comment]
Needs minimal some basic UX (we can assume it's a dialog) and need AC db changes.

**Comment by AmyYLee** [comment]
Assigning to @topotropic

**Comment by R2R29** [comment]
> ### Why/User Benefit/User Problem
> 
> Some sites, e.g., The Guardian, have long titles that abbreviate poorly. For example, "News, sport and opinion from the Guardian's US edition | The Guardian" turns into, "News, spor...". Allowing users to rename these would enable more description titles.
> ### What/Requirements
> 
> Long press on top site currently brings up a dialog with "Open in private tab" and "Remove". Add "Rename" which brings up a dialog with current name edit box and cancel and rename buttons. Pressing rename will modify the underlying SQLite database and refresh the page.
> ### Acceptance Criteria (how do I know when I’m done?)
> 
> Users can rename top sites.

Agree but it would be good if we could also change the URL.

**Comment by mackeev** [comment]
Looking at most recent Nightlies, this feature has become crucial. They dropped naming top sites completely. Now, if your top sites are from the same domain (my case), they share the same icon... and there's no way to distinguish one from another.
As of today, it's more like just naming a site, not renaming it.

**Comment by 532910** [comment]
I edited `/data/data/org.mozilla.firefox/databases/top_sites` with sqlite and life becomes better (:
the root is needed of course

**Comment by cadeyrn** [comment]
> Looking at most recent Nightlies, this feature has become crucial. They dropped naming top sites completely. 

I can not confirm, all top sites have a name on my device.

**Comment by bjherbison** [comment]
I added cnn.com as a top site and it didn't get a name. I then updated to the latest Nightly and added about a dozen sites as top sites. About half the sites don't have names.

With names: google.com, bing.com, allrecipies.com, whitepages.com, hello.diply.com, etsy.com, kohls.com

Without names: cnn.com, huffpost.com, m.imgur.com, jcpenny.com, linkedin.com, microsoft.com

(I suspect the lack of names for some sites may belong better in a separate bug report, but allowing renaming would obviously mitigate the issue with some sites not getting names.)

**Comment by JohannVII** [comment]
This would literally make Top Sites bookmarks instead: bookmarks, those things that can save a web address and allow you to change the displayed name (and edit the URL, and group with tags, etc.).

To be clear, I think that's a good idea, because Mozilla attempting to deprecate bookmarks is utterly misguided. But the whole idea of Top Sites is that it's auto-generated based on browsing history; if you want control over how site addresses are stored and displayed, you want bookmarks, a thing that already exists (and only isn't providing the functionality desired because the dev team has intentionally hidden them deeper in menus and disallowed or didn't implement the home/default page display that was available in Fennec).

The solution (which also happens to be a solution for a number of other noted problems - several suggestions here as well as the linked tagging option request are literally just asking for home page bookmarks) is to reintroduce the ability to have bookmarks displayed on the home screen. If bookmarks can also get a cache-page flag/setting and the ability to open a group (which could be defined by the existing tagging system), they can additionally provide all of the functionality of Collections. In fact, Collections could have used the bookmark system to store information as a special group of bookmarks that are associated with a cached page (using tags or introducing an additional flag). I'm yet to find any coherent reason that multiple additional systems were developed to replicate existing functionality.

**Comment by Matth7878** [comment]
Isn't it possible to temporarily expose a rename action on long pressing top sites? It's really annoying when for instance you have pinned multiple pull request page on GitHub -> they all have same icons and all names are pull request....

**Comment by gabrielluong** [comment]
@betsymi can I have you take look at this copy? Thank you!

<img width="388" alt="Screen Shot 2020-10-29 at 12 51 29 PM" src="https://user-images.githubusercontent.com/1190888/97605972-a6b4bd00-19e5-11eb-9b08-af0a36fa4cbc.png">

**Comment by betsymi** [comment]
@gabrielluong Clarification question after reading the comments: Are people able to edit the name AND the URL in this view, or _only_ the name?

**Comment by sv-ohorvath** [comment]
@gabrielluong I started testing this on Nightly, but I would like to know too if we want this, in order to validate these changes:
> @gabrielluong Clarification question after reading the comments: Are people able to edit the name AND the URL in this view, or _only_ the name?

I personally don't think that is necessary, since you can just add a new top site with the URL you want, but I need a confirmation.

Also, the frequently visited top sites (the ones coming from the History list) don't have this option (only the pinned top sites). According to this: https://github.com/mozilla-mobile/fenix/issues/10342#issue-610539388 it would be nice to have.
Thanks!

**Comment by gabrielluong** [comment]
> @gabrielluong I started testing this on Nightly, but I would like to know too if we want this, in order to validate these changes:
> 
> > @gabrielluong Clarification question after reading the comments: Are people able to edit the name AND the URL in this view, or _only_ the name?
> 
> I personally don't think that is necessary, since you can just add a new top site with the URL you want, but I need a confirmation.
> 
> Also, the frequently visited top sites (the ones coming from the History list) don't have this option (only the pinned top sites). According to this: [#10342 (comment)](https://github.com/mozilla-mobile/fenix/issues/10342#issue-610539388) it would be nice to have.
> Thanks!

We only covered renaming the name for pinned site. I will check with @vesta0 and @topotropic about further follow ups.

**Comment by sv-ohorvath** [comment]
Ok, thanks. Closing the issue as verified then.

**Comment by 532910** [comment]
It doesn't allow to remove name! Please reopen!

**Comment by Dunexus** [comment]
This issue was about renaming top sites. If you want to hide top sites name, please open a new issue.

**Comment by 532910** [comment]
Aan empty string is just a special case. Moreover, just space isn't allowed too.
