### ISSUE TITLE
[Bug] Snackbar-Touch target needs resizing for "Undo" button from closed tab snackbar

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9594]
## Prerequisites:
- Have Google Accessibility Scanner installed.
### Steps to reproduce
1. Open app and make a search after a site.
2. Go back to homescreen by pressing tabs tray icon.
3. Close the opened tab.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
"Tab Closed" snackbar -> "Undo" button:
- org.mozilla.fenix.nightly:id/snackbar_btn
This item's size is 45dp x 18dp. Consider making this touch target 48dp wide and 48dp high or larger.
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 4/1 (Build #20920607)

**Screenshot:**
"Tab Closed" snackbar -> "Undo" button:
![Screenshot_20200401-181443_Accessibility Scanner](https://user-images.githubusercontent.com/49859863/78160599-dea65280-744c-11ea-8798-56eadd0f688b.jpg)

**Comment by asadotzler** [comment]
There's room to expand the touch area without actually increasing the height of the snackbar. Can we do that?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest Nightly build from 5/29 with:
- Google Pixel (Android 10),
- Sony Xperia Z5 Premium (Android 7.1.1):
<img src="https://user-images.githubusercontent.com/40694158/83256818-cee08b80-a1bb-11ea-90b9-22d3151232c9.png" width="300" height="550" />

 - OnePlus 5T (Android 9):
<img src="https://user-images.githubusercontent.com/40694158/83256839-db64e400-a1bb-11ea-9f0d-0a507d80b425.png" width="300" height="550" />
