### ISSUE TITLE
Make the Firefox Preview branding smaller

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#9682]
We want to have more space for other items on the home screen. In order to do this, let's reduce the size of the branding

### Acceptance Criteria
* A smaller, one line logo is displayed at the top of the homescreen
* The logo looks correct in dark, private, and normal mode.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that the new UI is displayed properly for the Firefox Preview branding logo/text on all dark/light, private mode.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

Build: Firefox Preview Nightly 4/8 #20990609.

Also, I found that with the new UI, the cut from scrolling down is made under the Firefox Preview branding and not above as the previous UI.
The new bug about this issue is here: [9808](https://github.com/mozilla-mobile/fenix/issues/9808)
