### ISSUE TITLE
[Meta] Tab Tray

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#9686]
Captures the ux effort on all the smaller issues - check out the board. 

https://github.com/orgs/mozilla-mobile/projects/53

**Comment by cadeyrn** [comment]
In the mockup I noticed that there is no spacing at all left of the thumbnails. This looks really out of place because you don't see something similar on any other screen in Fenix. It also feels unbalanced because the user interface sticks to the edge on the one side but not on the other side. Is this really intended?

**Comment by topotropic** [comment]
Thanks for the feedback @cadeyrn – it's a first pass and based off Material design guidelines https://material.io/components/lists#types; we'll keep iterating on it.
