### ISSUE TITLE
[Bug] PWA - The pwa icon's are displayed as white on device homescreen

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9916]
## Steps to reproduce
1. Open app and go to instagram.com.
2. Tap on Menu/Install.
3. Add to homescreen.
4. View the icon of the pwa from devices homescreen.
### Expected behavior
The PWA icon displays the instagram's favicon.
### Actual behavior
The PWA icon does not display the instagram's favicon. The pwa icon for instagram is white.
### Device information

* Android device: Google Pixel 3 XL (Android 9)
* Fenix version: Nightly debug build 39.0.20200413130047, d433836f0 GV: 77.0a1-20200410095419

Note: 
- The issue seems to be device specific as I could only reproduce with Google Pixel 3 XL (Android 9)
- With Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) I did not reproduce.
- It does not happen with twitter.com set as PWA nor with daleharvey.github.io/testapp.

GIF:
![20200414-154621](https://user-images.githubusercontent.com/49859863/79228340-ed87fe80-7e69-11ea-8747-dc233fcb0320.gif)

**Comment by sflorean** [comment]
Reproducible also with trivago.com on Samsung Galaxy Note 10 (Android 10).

**Comment by huuhaa** [comment]
In my device Firefox Preview picks up favicon for some sites, ie. mastodon works ok. But if I try with https://bikemap.finomena.fi/ I end up with black icon instead of favicon. My default theme at Android is dark, tried to change it bright but still got black icon for that site. Didn't restart phone between trying those, but did try to change browser theme also.

Anyway seems like it's getting white icon for some users, black for others, while working fine with some pwa.

My device is Nokia 7 Plus with Android 10.

**Comment by Diana-Rus** [comment]
Hi, i tried with Samsung Galaxy S9 (Android 8) yes it displays a black icon the pwa for:https://bikemap.finomena.fi/ , in my case with Samsung Galaxy S9 (Android 8) on Nightly 5/22 but my android does not support dark themes.
**Screenshot**
![Screenshot_20200522-115002_Samsung Experience Home](https://user-images.githubusercontent.com/49859863/82650100-e0a5ba00-9c22-11ea-9521-03db6da75962.jpg)

> Could some of you who are getting plain white icon, confirm that are you getting white icon also for that bikemap pwa ( https://bikemap.finomena.fi/ ) or will there be icon? Just thinking that could there be also one part of problem that it offers black background for dark theme even when icon is also black. If so there should be icon visible if background is white.

**Comment by Diana-Rus** [comment]
Hi, issue is reproducible on Beta 5.2.0-beta.1 with Samsung Galaxy S9 (Android 8).

**Comment by leela52452** [comment]
reproducible on 5.2.0 : resetera only, all other websites mentioned in above comnents are ok.

**Comment by Diana-Rus** [comment]
Reproducing the issue (as a white favicon) on latest Nightly 8/26 with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8) with the following pwa for:
- makemytrip.com
- flipboard.com

**Comment by sv-ohorvath** [comment]
flipboard.com also has no website name on my devices, on Nightly 9/14 and Beta 8.1.1.

**Comment by Trekky12** [comment]
Hey, I noticed that the background-color of the icon on the homescreen seems to match the `background_color` defined in the webmanifest.
When installing the demo application for "A2HS" from https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen the icons aren't using a transparent background:

In the screenshot the icon on the left is from Chrome and the icon on the right from Firefox:
![grafik](https://user-images.githubusercontent.com/3930110/93707835-13f54880-fb32-11ea-9513-d82d6451fc98.png)

Is this related to this issue?

**Comment by raviqqe** [comment]
@Trekky12 I have the same problem of the weird background too.

I also noticed that SVG icons in `manifest.json` do not work. They result in white circle icons on home screens after installation. I don't know if it's the same issue as this. Should I create a new one?

**Comment by Trekky12** [comment]
So apparently the background-color on the icon is the expected behaviour for adaptive launcher icons :confused:

Despite that the background-color is not parsed correct when there is an image with a transparent background and in the manifest the defined background-color is white.
The background-color attribute (#FFFFFF) from the webmanifest parses to -1. In this case the background-color is apparently retrieved from the main color of the image, which is not that good for images which only have one color:

![grafik](https://user-images.githubusercontent.com/3930110/102636753-56401d00-4155-11eb-9f2d-85c075c59fa1.png)

You can see the problem at https://fenix-test-f02a9.web.app/

**Comment by sflorean** [comment]
Reproducible also with Fortune.com, on latest Nightly 2/10 - Pixel 3 (Android 11). 
Not reproducible anymore with trivago.com on Samsung Note 10(Android 10).

**Comment by Trekky12** [comment]
Actually the problem still exists...

**Comment by kokbira** [comment]
Oh yeah, still exists...

**Comment by alex20465** [comment]
Still exists
