### ISSUE TITLE
[Bug] Tab opened with ACTION_VIEW intent and then saved to collection maintains source

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#9937]
## Steps to reproduce
1. Open link from other app using Fenix (ie Gmail) with ACTION_VIEW intent
2. Save that tab to a collection
3. Open tab from collection, press back button

### Expected behavior
Tab doesn't close

### Actual behavior
Tab closes because it still has the ACTION_VIEW source

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/6652

**Comment by sv-sdeiac** [comment]
Hi, using the information from this ticket and #9938, I can confirm that the URL from custom tabs saved as collections are still displayed and the browser doesn't close after going back from the page.

Also, the issue is reproducible using the Beta/RC Firefox Preview version.

Build:
- Firefox Preview Nightly 5/4 #21251804.

Devices:
- LG G7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android 10).
