### ISSUE TITLE
Duplicate tabs

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#9956]
### Why/User Benefit/User Problem
Users have seen this on desktop browsers and would like to be able to do this on mobile too. There's heaps of use cases and a benefit is keeping your tab history too.

### What/Requirements
Duplicate a tab from the homescreen/tab switcher

### Acceptance Criteria (how do I know when I’m done?)
I'm not sure about this one. Please help me fill this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16854)

**Comment by buttercookie42** [comment]
For Fennec there was a bug somewhere (too lazy to dig it up now) with the idea to e.g. use long pressing on an entry in a tab's history stack (#1048, ahem) to duplicate a tab and load the corresponding history entry (in analogy to desktop where you can middle-click the history list [1] to that effect).

[1] You can also middle-click the reload button, but on mobile that would conflict with the ability to force-reload a page (#2681).

**Comment by s-ankur** [comment]
Copying from #14096 as @Poopooracoocoo suggested

What is the user problem or growth opportunity you want to see solved?

Some times I need to open the current page in two different tabs. On desktop Firefox there are already many ways to duplicate an existing tab. See https://support.mozilla.org/bm/questions/762043
My Proposal

When you long press on the tab counter, a context menu opens with three options. My proposal is that you can have four options, including the Clone/Duplicate tab option in this order:

Close tab
Clone tab
New private tab
New tab

Ideally this option will duplicate the entire tab history and current tab state, much like collections do right now. But I would be happy even if it just opens a new tab with the current URL. In both cases this should open a tab in the background, so that you can continue browsing on the current page (or you can replicate the desktop behavior and navigate to the newly opened tab). You can also call this "Duplicate Tab", again for parity with desktop.
Who will benefit from it?

Users of sites like wikipedia, stackoverflow which can require a "branching" flow that the linear tab history cannot easily provide. and especially desktop users who already love and use this feature.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812931

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by boek** [comment]
ty actions
