### ISSUE TITLE
Better UX and UI with fewer clicks

### ISSUE THREAD

**Issue by githubSucs** [mozilla-mobile/fenix#9973]
### Why/User Benefit/User Problem

When it comes to UX, the least amount of clicks is quite significant. Currently, Firefox Preview requires a lot of clicks even for very simple tasks. Everybody suggests to mimic chrome. Instead, let Firefox prevail. Here I suggest some examples yet no matter what you do, please consider the amount of clicks when designing UX/UI. In addition, unnecessary elements have user lose time, draw useless attention such as Firefox logo on start page, one has to scroll down to see the content of interest.   

### What/Requirements

Design UI without clutter and actions requiring the least amount of clicks.

### Acceptance Criteria (how do I know when I’m done?)

1) A Tab tray / home like this:

![Fenix start page](https://user-images.githubusercontent.com/63744083/79383850-9029a580-7f6e-11ea-9105-e3690d8e10ee.png)

- The app/tab starts ready to search whether typing, QR, or voice search.
- Tabs are displayed if the user does not want to search, when scrolled keyboard disappears to serve the user's intent.
- If user wants neither, History, Bookmarks, and Downloads, whatever the user's destination is, it is almost always one click away. When one of these clicked and user wants to see tabs again they can go back with one back button press. A settings button also may be placed after Downloads tab.
- When clicked on tabs icon this appears again to let user do whatever they want with one click and instead of showing the top of the tabs page, the position of the tab from which tabs icon is pressed is shown, since when user clicks on tabs icon, they do not want to go to the top; the related tabs are usually successive.

2) A browsing page like this:
![fenix](https://user-images.githubusercontent.com/63744083/79385595-8bb2bc00-7f71-11ea-9a88-90a2227d210f.png)
- with ![this](https://github.com/mozilla-mobile/fenix/issues/176), the remaining common action is close tab. When searching for something, one opens many pages in new tab then eliminates one by one until they find what they are looking for. With such a button closing the current tab and switching to next one requires one click instead of three.

**Comment by ekager** [comment]
Thank you for your ideas @githubSucs ! We are actively working on redesigning the tabs tray experience. Please follow along in our project board here https://github.com/orgs/mozilla-mobile/projects/53

In terms of getting consideration for any of these ideas, it would probably be more conducive to file specific feature requests for each component instead of one large issue. In addition, some of these features we already have thought about for example, Voice Search https://github.com/mozilla-mobile/fenix/issues/1216
Reshuffling Search UI https://github.com/mozilla-mobile/fenix/issues/2106
