### ISSUE TITLE
[Bug] "Secure your logins and passwords" prompt is displayed while the recording in PB is disabled

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9987]
### Preconditions
Fresh install, as this prompt is displayed only once.
## Steps to reproduce
1. Launch Fenix.
2. Reach settings and disable PB recording option.
3. Access `Saved Logins`
### Expected behavior
Nothing is displayed in PB while the recording in PB is off.
### Actual behavior
"Secure your logins and passwords" prompt is displayed while the recording in PB is disabled
### Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 4/16.**

![20200416-132150](https://user-images.githubusercontent.com/42831109/79450807-1b964b80-7fee-11ea-89f0-f3f14e54736c.gif)

**Comment by mcarare** [comment]
The dialog also shows up in Account Settings, and it was secured in https://github.com/mozilla-mobile/fenix/pull/9998. For the dialog in Saved Logins it is secured here: https://github.com/mozilla-mobile/fenix/pull/10134
Please recheck after the second PR is merged. TY!

**Comment by Diana-Rus** [comment]
Hi verified as fixed with Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) on Firefox Preview Nightly 20200424
**- Settings/Logins and passwords - "Secure your logins and passwords" prompt**
**Pixel 3 XL - GIF**
![20200424-102701](https://user-images.githubusercontent.com/49859863/80187146-cb377300-8617-11ea-98e0-bf864c456a96.gif)

**Samsung Galaxy S9 - GIF**
![20200424-102234](https://user-images.githubusercontent.com/49859863/80187055-acd17780-8617-11ea-9fb3-c0dfa2b36b61.gif)

**Sony Xperia Z5 - GIF**
![20200424-103110](https://user-images.githubusercontent.com/49859863/80187165-d38fae00-8617-11ea-8756-f32387fc7a29.gif)


**- Log in with a valid account/Account Settings- Check and uncheck Logins checkbox in order to trigger the "Secure your logins and passwords" prompt
**Pixel 3 XL - GIF**
![20200424-115734](https://user-images.githubusercontent.com/49859863/80196298-dbeee580-8625-11ea-9620-a5453a35f960.gif)

**Samsung Galaxy S9 - GIF**
![20200424-120348](https://user-images.githubusercontent.com/49859863/80196311-e5784d80-8625-11ea-9a32-77e26a70430e.gif)

**Sony Xperia Z5 - GIF**
![20200424-121306](https://user-images.githubusercontent.com/49859863/80196389-08a2fd00-8626-11ea-954c-7889c0a9f0c9.gif)
